{100}{}{}
{101}{}{}
{110}{}{Seus pés realmente coçam.}
{120}{}{Você está desenvolvendo um joanete desagradável em cada pé.}
{130}{}{Seus sapatos parecem muito apertados; esses joanetes estão realmente ficando inflamados.}
{140}{}{Aquele joanete desagradável em cada pé parece ter se transformado em um dedo extra. Mas pelo
 menos aquela coceira persistente e ardente desapareceu.}
{141}{}{Oh, meu Deus, é Bess!}
{150}{}{Você ganhou }
{151}{}{ pontos de experiência por obter o GECK.}
{400}{}{Você não pode entender muita coisa do texto, mas as ilustrações são bastante informativas.}
{600}{}{Algo não parece muito certo em seu estômago.}
{601}{}{Você sente uma pressão intensa no estômago.}
{700}{}{Você junta os pedaços de papel rasgado para obter uma lista de três senhas.}
{900}{}{Algo não parece muito certo em seu estômago.}
{901}{}{Você sente uma pressão intensa no estômago.}
