{1}{}{You have become addicted to alcohol. The thirst for alcohol will soon consume you. You lost 1 Agility and 1 Charisma}
{2}{}{Le manque est en train d'empirer.}
{3}{}{Tu as des tremblements. Tu as cette envie intense de boire quelque chose alcoolisé, tout de suite.}
{4}{}{You feel as if a great burden has been lifted from your mind. No longer do you feel the need to drink alcohol. You regained 1 Agility and 1 Charisma}
