{1}{}{Tu es devenu accroc à l'alcool. Ta soif finira par te consumer très bientôt. Tu perds 1 point d'Agilité et 1 point de Charisme.}
{2}{}{Le manque est en train d'empirer.}
{3}{}{Tu as des tremblements. Tu as cette envie intense de boire quelque chose alcoolisé, tout de suite.}
{4}{}{Tu sens qu'un lourd fardeau s'est évacué de ton esprit. Tu ne ressens plus le manque d'alcool. Tu récupères un 1 point d'Agilité et 1 point de Charisme}
