{1}{}{Uzależniasz się od alkoholu. Nałóg cię wkrótce pochłonie. Tracisz 1 Zręczności i 1 Charyzmy.}
{2}{}{Te zachcianki są coraz gorsze.}
{3}{}{Dostajesz drgawek. Męczy cię intensywne pragnienie, musisz znaleźć coś do picia, koniecznie z alkoholem.}
{4}{}{Czujesz się jakby wielki ciężar został zdjęty z twojego umysłu. Nie odczuwasz już potrzeby picia alkoholu. Odzyskujesz 1 Zręczności i 1 Charyzmy.}
