{1}{}{You have become addicted to alcohol. The thirst for alcohol will soon consume you. You lost 1 Agility and 1 Charisma}
{2}{}{Te zachcianki są coraz gorsze.}
{3}{}{Dostajesz drgawek. Męczy cię intensywne pragnienie, musisz znaleźć coś do picia, koniecznie z alkoholem.}
{4}{}{You feel as if a great burden has been lifted from your mind. No longer do you feel the need to drink alcohol. You regained 1 Agility and 1 Charisma}
