{100}{}{}
{101}{}{}
{110}{}{Svrbí tě chodidla.}
{120}{}{Na nohou se ti začínají tvořit ošklivé puchýře.}
{130}{}{Boty ti začínají být těsné. Ty puchýře začínají být zanícené.}
{140}{}{Zdá se, že se puchýř na každé noze změnil v další prst. Ale aspoň, že to hrozné svědění přestalo.}
{141}{}{Můj bože, to je Bess!}
{150}{}{Získáváš }
{151}{}{ zkušenostních bodů za nalezení GECKu.}
{400}{}{Vůbec nerozumíš textu, ale obrázky jsou celkem srozumitelné.}
{600}{}{Něco není v pořádku s tvým žaludkem.}
{601}{}{Cítíš silný tlak v žaludku.}
{700}{}{Přiložíš k sobě roztrhané kousky papíru a získáš tak list se třemi hesly.}
{900}{}{Něco není v pořádku s tvým žaludkem.}
{901}{}{Cítíš silný tlak v žaludku.}
