{100}{}{}
{101}{}{}
{110}{}{Tes pieds te démangent vraiment beaucoup.}
{120}{}{Tu développes une grosse et vilaine boursouflure sur chaque pied.}
{130}{}{Tes chaussures te semblent trop serrées. L'inflammation gagne ces boursouflures.}
{140}{}{Ces horribles boursouflures sur chaque pied ressemblent de plus en plus à un orteil supplémentaire. Mais au moins, les démangeaisons persistantes et l'inflammation ont disparu.}
{141}{}{Bon Dieu, c'est Bess !}
{150}{}{Tu gagnes }
{151}{}{ points d'expérience pour avoir trouvé le J.E.K.}
{400}{}{Tu ne comprends absolument rien au texte, mais les images sont informatives.}
{600}{}{Quelque chose ne va pas avec ton estomac, tu peux le sentir.}
{601}{}{Tu ressens une pression intense dans ton estomac.}
{700}{}{Tu attaches les bouts de papier déchirés ensemble et tu récupères une liste de trois mots de passe.}
{900}{}{Quelque chose ne va pas avec ton estomac, tu peux le sentir.}
{901}{}{Tu ressens une pression intense dans ton estomac.}
