{100}{}{Bạn thấy một nữ tu mập mạp.}
{101}{}{Bạn thấy Elaine.}
{102}{}{Bạn vẫn thấy bà ta.}
{200}{}{Xin chào!}
{201}{}{Chào, tên bà là gì?}
{202}{}{Bà có thể kể gì cho tôi về Tu viện?}
{203}{}{Chào.}
{300}{}{Nếu cậu muốn tìm hiểu thêm về hội của chúng tôi, hãy nói chuyện với Trụ trì. Cậu có thể tìm thấy ông trong phòng riêng ở tầng ba.}
{301}{}{Tôi hiểu rồi. Hỏi thêm nhé...}
{400}{}{Dĩ nhiên rồi. Cậu muốn biết gì nào?}
{401}{}{Tên bà là gì?}
{402}{}{Không có gì, chào nhé.}
{403}{}{Bà có thể kể gì cho tôi về Tu viện?}
{500}{}{Tôi tên là Elaine.}
{501}{}{Tôi hiểu rồi. Hỏi thêm nhé...}
{600}{}{Này! Trước khi đi, có lẽ cậu có thể giúp tôi một việc. Tôi cần phải mang bộ phận máy này cho Max ở phòng
sao chụp dưới tầng hầm. Nhưng cậu thấy đấy, cái đầu gối bên trái của tôi dạo này sưng tướng lên, làm tôi đau ê ẩm
mỗi lần lên xuống cầu thang. Nếu không phiền thì cậu có thể mang thứ này cho ông ta hộ tôi được không?}
{601}{}{Được thôi.}
{602}{}{Xin lỗi, tôi không có thời gian. Xin chào.}
{603}{}{Trông tôi có giống nhân viên vận chuyển cá nhân của bà không? Tự đi mà làm lấy đi, con mụ béo ịch. Chào.}
{604}{}{Cám ơn! Bộ phận đây. Phòng sao chụp ở dưới tầng hầm. Cứ đi theo cầu thang đằng sau Thầy Matthew trong
khu vực nhà thờ.}
{605}{}{Không vấn đề. [Bạn nhận bộ phận]. Tôi sẽ chuyển xuống cho Max ngay đây.}
{700}{}{Ngộ }
{701}{}{. Ai bà?}
{710}{}{Hehe. Tên đẹp.}
{711}{}{Chào!}
{720}{}{Cậu nhỏ này đặc biệt thật đấy! Liệu cậu có thể GIÚP tôi và làm trợ thủ đặc biệt hôm nay của tôi được không?}
{721}{}{Cô nhỏ này đặc biệt thật đấy! Liệu cô có thể GIÚP tôi và làm trợ thủ đặc biệt hôm nay của tôi được không?}
{722}{}{Ngộ đặc biệt. Ngộ giúp.}
{723}{}{Ngộ không làm giúp.}
{730}{}{Thật à? Tuyệt! Vui lòng cầm bộ phận máy này xuống cho Max ở phòng sao chụp. Ông ta ở dưới TẦNG HẦM. Được chứ?}
{731}{}{Ngộ không thất vọng bà!}
{740}{}{Giờ thì cậu cứ ủi tiếp đi.}
