{100}{}{Bạn thấy một bia mộ.}
{101}{}{Trên bia mộ viết:}
{102}{}{"Thầy Gregory an nghỉ nơi đây. Người không biết lúc nào nên dừng."}
{103}{}{"Dì Patty. Đi cho nhẹ gánh."}
{104}{}{"Per Joner an nghỉ nơi đây. Chết khi chưa đá đời."}
{105}{}{"Đức cha Michael an nghỉ nơi đây. Người sáng lập, Đức cha, Chiến binh."}
{106}{}{"Một kẻ vô thần. Không nhà nhưng diêm dúa."}
{107}{}{"Johnny 12 giờ an nghỉ nơi đây. Xin lỗi vì đã không lên được."}
{108}{}{"Mary Jane. Người mẹ và vợ kính yêu."}
{109}{}{"'Chiếu tướng!' là lời cuối cùng mà Jon già nghe thấy. Trên bàn cờ cuộc đời, Ông chỉ là con tốt."}
{110}{}{"Ngài John Strange, vị luật sư chính trực an nghỉ nơi đây. Đúng là LẠ thật."}
{111}{}{"Nước mắt không thể đưa nàng trở lại -- vì vậy tôi khóc."}
{112}{}{"Mỗi ngày muôn nẻo, tôi dần tiến bước."}
{250}{}{Không có dấu tích nào trên bia mộ này.}
{251}{}{Tấm bia mộ này đã vỡ vụn và không đọc được vì quá nát.}
{252}{}{Trên bia mộ ghi tên John Doe.}
{253}{}{Tên và ngày tháng trên tấm bia đá đã bị thời gian bào mòn.}
