{100}{}{Bạn nhìn thấy một Lính gác mạnh mẽ.}
{101}{}{Bạn nhìn thấy một lính gác tuy đã đứng tuổi nhưng vẫn nổi cơ cuồn cuộn với làn da cháy nắng. Hẳn là ông ta hồi
trẻ chiến lắm. Cái nhìn xuyên thấu của ông ta cứ bám chặt lấy bạn.}
{200}{}{Xin chào, người lữ khách. Chào mừng đến với Tu viện. Chỉ cần đừng xía mũi vào mọi thứ là cậu sẽ ổn thôi.}
{201}{}{Ta đang quan sát ngươi đấy, đồ buôn nô lệ. Chỉ cần làm gì đó thôi là ngươi sẽ biến thành bùn tại nghĩa
trang của bọn ta đấy. Ta không muốn phải làm chuyện đó, và hẳn là ngươi cũng vậy. Vì thế đừng có
nảy ý gì hay ho trong cái đầu mốc của ngươi.}
{202}{}{Ông là ai?}
{203}{}{Tôi có thể trao đổi hàng hóa ở đâu?}
{204}{}{Có người đang đào mộ kìa, sao ông không làm gì đó đi chứ?}
{205}{}{Tôi nghe nói có vấn đề với lũ động vật ở dưới hầm. Biết gì về chuyện đó không?}
{206}{}{Tôi nghĩ đã đến lúc cho ông xuống mồ rồi. Cùng nhảy nào, lão già.}
{207}{}{Không có gì. Xin chào.}
{300}{}{Chẳng ai cả... Trước đây ta có từng đi bảo vệ đoàn lữ hành. Rất nhiều người tưởng ta là cớm trưởng gì đó vì
trông ta rất giống với đám bảo vệ pháp luật ở chỗ này, nhưng đếch phải. Ta chỉ trông coi khu cộng đồng này 
vì ta thấy chỗ này đáng để bảo vệ.}
{301}{}{Và đổi lại thì cả cộng đồng này giúp đỡ ta. Đám thầy tu cho ta bú rượu không mất tiền, Peterson thì lo đồ ăn còn
Bill thì đảm bảo ta luôn có đầy đủ đạn dược. Không quá tồi cho chân bảo vệ sau khi nghỉ hưu chứ hả?}
{302}{}{Ta là người đảm bảo ngươi tuân thủ luật lệ, đó là tất cả những gì ngươi cần biết. Giờ thì tiếp tục làm gì thì
làm đi và hãy để ta yên.}
{303}{}{Công việc hay đấy. Để tôi hỏi về chuyện khác.}
{304}{}{Sao cũng được, chào.}
{305}{}{Ông nghĩ ông xơi được tôi á? Cứ thử đi, lão già. Sẽ vui lắm đây.}
{400}{}{Cậu có thể tìm Bill chuyên bán hàng ở đây trong tòa nhà đối diện. Nếu không thì cậu nên đến chỗ Kho
đồ sinh tồn của Percy tại Bãi phế liệu ở Gecko hoặc quán của Harry Vui vẻ ở khu Sân của Thành phố Vault.}
{401}{}{Nghe hay đấy. Tôi muốn hỏi chuyện khác.}
{402}{}{Cám ơn, chào.}
{500}{}{Nếu có ai đói hoặc tham đến mức đi lật cả mộ thì đấy là việc của họ. Người chết rồi cũng đâu có dùng được
những đồ chôn theo. Không phải việc của ta... ta không thấy có vấn đề gì với chuyện đấy.}
{501}{}{Để tôi hỏi chuyện khác.}
{502}{}{Chào.}
{600}{}{Đúng vậy, và Thầy Thomas đang mất tích. Ông ta thông minh thật đấy nhưng có phần hơi ngơ. Ta không biết
dưới đó có gì, nhưng chắc không chỉ là lũ chuột với bò cạp đâu.}
{601}{}{Đúng vậy, và Thầy Thomas đang mất tích. Ta không biết dưới đó có gì, nhưng chắc không chỉ là lũ chuột với
bò cạp đâu. Sao cậu không xuống thử xem, cậu giai cứng cựa?}
{602}{}{Vậy thì sao ông không xuống xem đi?}
{603}{}{Ông mới là gã cứng cựa ở đây mà. Sao ông không lê đít xuống đấy mà xem?}
{610}{}{Nói ra thì hơi xấu hổ, nhưng do trước đây đi phượt với mấy đoàn lữ hành nhiều quá mà bây giờ ta thấy hốt
khi chui xuống đất. Mấy bức tường cứ ép sát lại khiến ta đếch thở nổi... Chắc là cậu có thể giúp ta tìm hiểu xem
chuyện gì đã xảy ra với Thầy Thomas được chứ?}
{611}{}{Để tôi xem tôi có thể làm gì, mà tôi muốn hỏi chuyện khác.}
{612}{}{Chào.}
{613}{}{Tôi là người cứng cựa, và vì vậy nên tôi sẽ dần cho ông một trận.}
{700}{}{Cậu muốn biết gì nữa nào?}
{800}{}{Rất vui được gặp lại cậu.}
{801}{}{Ta đang để mắt đến cậu đấy.}
