{100}{}{Bạn thấy một thầy tu trẻ đeo kính.}
{101}{}{bạn thấy Thầy Jason.}
{102}{}{Thầy tu này có vẻ đang chìm trong suy tư.}
{200}{}{[Thầy tu trẻ nhanh chóng nhét bộ bài "Tragic" vào túi khi bạn đến gần]. Anh muốn gì?}
{201}{}{Không gì cả. Chào.}
{202}{}{Tôi muốn biết tại sao cậu lại giấu tôi bộ bài đó.}
{210}{}{Tôi không biết anh đang nói gì. Tôi không có bộ bài nào cả.}
{211}{}{Đừng có chối. Tôi vừa thấy cậu nhét vào trong túi. Tôi chỉ muốn biết tại sao thôi.}
{212}{}{Được rồi, sao cũng được. Gặp lại sau.}
{220}{}{Này, đừng nói với ai nhé, được chứ? Chúng tôi đúng ra không được phép "sử dụng" các kỉ vật trước chiến tranh mà
chỉ tôn thờ thôi. Nhưng mấy lá Tragic này ngầu vãi. [Có vẻ như cậu ta chìm trong đê mê khi đắm đuối nhìn bộ bài.
Sau một thoáng, cậu ta nhìn bạn]. Ồ, xin lỗi, tôi là Thầy Jason. Tôi, ừm, chắc anh không chơi bài Tragic đâu nhỉ?}
{221}{}{CÙNG CHIẾN NÀO!!!}
{222}{}{Tuyệt cú mèo, tôi cực thích Tragic the Garnering.}
{223}{}{Tôi có thử, nhưng không hợp.}
{224}{}{Trước đây tôi cũng nghiện lắm. Giờ thì đỡ rồi.}
{225}{}{Không hề.}
{226}{}{Đéo. Trông tôi có giống bị dở không?}
{230}{}{Này, đm thằng chóa. Để tao yên.}
{231}{}{Này, đm con đũy. Để tao yên.}
{232}{}{Anh mày cũng muốn lắm, nhưng anh còn muốn nhìn mày ngồi xe lăn hơn kìa.}
{233}{}{Được rồi, thì thôi. Chào.}
{234}{}{Này, tôi xin lỗi. Tôi nói hơi quá. Tôi chỉ không thích bài Tragic thôi.}
{240}{}{Uầy bạn tôi ơi, tôi muốn chơi với bạn lắm, nhưng không ổn đâu. Tôi không muốn nó bị tịch thu. Đây là điều
mà tôi ghét ở nơi này. Chúng tôi đang nằm trên mỏ vàng chứa cả núi đồ cực ngầu trước chiến tranh, nhưng lại không được
phép động đến. Chẳng đúng tí nào cả. Ngu vl.}
{241}{}{Uầy bạn tôi ơi, tôi hiểu mà. Tôi ước gì mình có thể chơi nhiều hơn, nhưng không ổn lắm. Tôi không muốn nó bị tịch thu.
Đây là điều mà tôi ghét ở nơi này. Chúng tôi đang nằm trên mỏ vàng chứa cả núi đồ cực ngầu trước chiến tranh, nhưng
lại không được phép động đến. Chẳng đúng tí nào cả. Ngu vl.}
{242}{}{[Cậu ta cười khúc khích]. Thế là có thêm dân nghiện rồi. Tôi ước gì mình có thể chơi nhiều hơn, nhưng không ổn lắm.
Tôi không muốn nó bị tịch thu. Đây là điều mà tôi ghét ở nơi này. Chúng tôi đang nằm trên mỏ vàng chứa cả núi đồ
cực ngầu trước chiến tranh, nhưng lại không được phép động đến. Chẳng đúng tí nào cả. Ngu vl.}
{243}{}{Sao cũng được, đằng nào chúng ta cũng có chơi được đâu -- không ổn đâu. Tôi không muốn nó bị tịch thu. Đây là điều
mà tôi ghét ở nơi này. Chúng tôi đang nằm trên mỏ vàng chứa cả núi đồ cực ngầu trước chiến tranh, nhưng lại không được
phép động đến. Chẳng đúng tí nào cả. Ngu vl.}
{244}{}{Ừ, nghe ngu thật.}
{245}{}{Nếu cậu không đồng ý với lý tưởng của hội thì sao lại đi làm thầy tu?}
{250}{}{Anh nghĩ là tôi *chọn* làm thầy tu sao? Tôi sinh ra trong cái đống cứt này. Tôi chỉ ước là những người khác cũng
mở mắt và thấy ngu vl khi không tận dụng những thứ đồ tuyệt vời được thu thập ở đây. Nhưng không, họ hoàn toàn
hài lòng với việc tôn thờ và sắp xếp các kỉ vật, nhưng chẳng dùng chúng vào việc gì có ích cả. Ngu vcl.}
{251}{}{Cậu nói đúng, nghe ngu thật.}
{252}{}{Ngu chẳng kém gì việc tôi ngồi đây nghe con nghiện trình bày vậy. Tạm biệt.}
{253}{}{Nếu cậu cho rằng điều đó là ngu ngốc thì sao không thử cố gắng làm gì đó để thay đổi đi?}
{260}{}{Cuối cùng cũng có người đồng ý với tôi! Tôi có ý này, và chắc là anh có thể giúp tôi. Anh xem, đám thầy tu ở đây đã dành
*nhiều năm* để chuyển kiến thức trước chiến tranh vào cơ sở dữ liệu trong máy tính. Nếu ai đó "lỡ tay" định dạng dữ liệu
thì tất cả sẽ bị xóa sạch. Tôi nghĩ việc này sẽ khiến họ sốc đến mức tỉnh ra và chúng tôi cuối cùng cũng có thể từ bỏ lối
sống ngu ngốc này. Vậy đó, anh thấy sao?}
{261}{}{Tôi cho rằng đấy là một ý tưởng tệ hại và tôi chẳng còn gì để nói nữa.}
{262}{}{Xóa sạch toàn bộ công sức nhiều năm của ai đó? Nghe hay đấy. Cứ để tôi.}
{263}{}{Sao cậu không tự đi mà định dạng lấy?}
{264}{}{Nếu cậu ghét nơi này thì sao không rời đi?}
{270}{}{Thực ra thì tôi *có* ý này có thể thay đổi mọi thứ. chắc là anh có thể giúp tôi. Anh xem, đám thầy tu ở đây đã dành
*nhiều năm* để chuyển kiến thức trước chiến tranh vào cơ sở dữ liệu trong máy tính. Nếu ai đó "lỡ tay" định dạng dữ liệu
thì tất cả sẽ bị xóa sạch. Tôi nghĩ việc này sẽ khiến họ sốc đến mức tỉnh ra và chúng tôi cuối cùng cũng có thể từ bỏ lối
sống ngu ngốc này. Vậy đó, anh thấy sao?}
{271}{}{Tôi cho rằng đấy là một ý tưởng tệ hại và tôi chẳng còn gì để nói nữa.}
{272}{}{Xóa sạch toàn bộ công sức nhiều năm của ai đó? Nghe hay đấy. Cứ để tôi.}
{273}{}{Sao cậu không tự đi mà định dạng lấy?}
{274}{}{Nếu cậu ghét nơi này thì sao không rời đi?}
{280}{}{Anh điên à? Họ sẽ đóng đinh tôi nếu tôi động vào. Nhưng một nhà phiêu lưu giỏi giang như anh thì khác. Mẹ kiếp,
tôi cá là anh chỉ cần lật tay là có thể tàn sát tất cả mọi người ở đây. Vậy anh có làm không, hay sợ một đám thầy tu chết nhát?}
{281}{}{Tôi chẳng sợ ai cả. Cứ để tôi.}
{282}{}{Được. Cứ để tôi.}
{283}{}{Không, thay vào đó tôi nghĩ là tôi sẽ thử xem cậu cá có đúng không. Bắt đầu từ cậu.}
{284}{}{Thôi đi. Chuyện này không hợp với tôi. Chào.}
{285}{}{Không, tôi sẽ không làm đâu. Nếu cậu ghét nơi này thì sao không rời đi?}
{286}{}{Trừ phi muốn giúp tôi, còn không thì cút đi.}
{287}{}{Được. Cứ để tôi.}
{288}{}{Không, tôi sẽ không làm đâu. Nếu cậu ghét nơi này thì sao không rời đi?}
{290}{}{Thật á? Giàng ơi tuyệt cú mèo. Nhưng đầu tiên anh sẽ cần có quyền truy cập vì họ bảo vệ cơ sở dữ liệu khá kĩ. Nhưng
không khó lắm đâu, đám tu sĩ này tin người đến sái cả cổ. Chắc là họ sẽ nổi điên lên khi anh định dạng dữ liệu,
nhưng không cần lo đâu vì toàn một lũ èo uột ấy mà. Chỉ cần đừng giết ai là được -- Tôi không muốn mọi thứ
vượt khỏi tầm kiểm soát, anh biết đấy?}
{291}{}{Được. Còn gì nữa không?}
{292}{}{Tôi không hứa trước được. Còn gì nữa không?}
{300}{}{Chỉ cần định dạng dữ liệu rồi té thôi, vì họ sẽ không muốn anh ở đây đâu. Đừng có quay lại để báo là anh đã làm
xong, vì tôi cũng sẽ giả vờ nổi xung lên giống họ, nếu không thì họ sẽ nghi ngờ. Cám ơn lần nữa vì đã đồng ý, điều này
là để tốt cho họ thôi.}
{301}{}{Sao cũng được. Tạm biệt.}
{310}{}{Anh điên à? Tôi chưa thò chân ra hoang mạc lần nào, nhưng tôi biết rõ là ngoài đó có gì. May lắm
thì tôi bò được 50 bước trước khi bị bò cạp đâm đít. Tệ hơn nữa thì tôi có thể bị một đám cướp điên rồ túm cổ
và tra tấn *hoặc* bị lũ toọc ăn thịt người nhai sống. Đại loại thế. Tôi biết là nếu tôi mà rời khỏi đây thì tôi sẽ ăn lìn
ngay. Thế nên không đâu, tôi thà chết dí ở đây còn hơn.}
{311}{}{Này, ngoài đó *đâu* có tệ đến thế... Mà chắc là cậu nói đúng. Chắc là cậu còn không mò đến nổi Gecko.
Ít nhất là nếu tự đi. Nhưng nếu tôi dẫn cậu đi thì sao?}
{312}{}{Kém cỏi thật. Tạm biệt.}
{313}{}{Cứ mơ đi chứ. Tôi chắc là gần đây có sẽ có chỗ an toàn để chuyển đến.}
{315}{}{Ờ, nếu anh mà tìm thấy thì báo cho tôi nhé.}
{316}{}{Được thôi. Tạm biệt.}
{320}{}{Gecko á? Khu của đám ghoul đúng không? Cám ơn nhưng tôi đéo dại.}
{321}{}{Này, những người ghoul thực ra thân thiện lắm. Hơn nữa, tôi còn biết một gã thích đấu bài Tragic lắm.}
{322}{}{Này, những người ghoul thực ra thân thiện lắm.}
{323}{}{Này, tôi nghe nói thực ra họ thân thiện lắm.}
{324}{}{Được rồi. Tùy cậu thôi. Tạm biệt.}
{330}{}{Đm thật à, một tay chơi Tragic khác? Hừm, thế này thì... Liệu ông ta có lá Black Dahlia nào để đổi không nhỉ?
Được rồi. Tôi sẽ đi nếu anh đưa tôi đi.}
{331}{}{Lên đường nào.}
{332}{}{Được rồi, nhưng tôi cần phải thu xếp vài việc trước. Tôi sẽ báo khi nào xong xuôi.}
{340}{}{Thật à? Nhưng mà đâu có thay đổi được thực tế là chúng nó đặc mùi phân bò. Không đâu.}
{341}{}{Được rồi. Tùy cậu thôi. Tạm biệt.}
{350}{}{Muốn gì?}
{351}{}{Chỉ chào hỏi thôi. Gặp lại sau.}
{352}{}{Tôi đổi ý rồi. Tôi sẽ định dạng cái máy cho cậu.}
{353}{}{Này, có thể cậu sẽ muốn suy nghĩ lại về việc đi cùng tôi đến Gecko, vì tôi biết ở đó
có người thích đấu bài Tragic lắm.}
{354}{}{Này, tôi biết một gã ở Gecko thích đấu bài Tragic lắm đấy. Tôi có thể đưa cậu tới đó.}
{360}{}{Đi được chưa? Tôi hóng xem gã đấy có những loại bài Tragic nào đến sắp chết đây này.}
{361}{}{Được rồi, đi thôi.}
{362}{}{Chưa. Khi nào đi tôi sẽ báo.}
{370}{}{[Sau khi đến Gecko bạn giới thiệu vị thầy tu trẻ với Wooz. Bọn họ nhanh chóng làm thân và bắt đầu đọ chim bài
Tragic. Bạn chuẩn bị rời đi thì Thầy Jason cố dứt mình khỏi bài Tragic một khoảng để nói chuyện với bạn].}
{371}{}{[THÊM]}
{372}{}{Đcm, Wooz *có* lá Black Dahlia! Mỗi thế thôi cũng là đủ cho cả chuyến đi này rồi. Đám ghoul thoạt nhìn thì
đúng là như quỷ, nhưng bỏ kính ra thì cũng không đến nỗi nào. Mà cám ơn đã đưa tôi đến chỗ này. Đây, ờ, tôi
đã *mượn* thứ này từ Kho kỉ vật của Tu viện, và thật tuyệt rằng món đồ công nghệ cũ kĩ này vẫn còn hoạt động.
[Cậu ta dúi một cái Stealth Boy vào tay bạn]. Gặp lại sau nhé.}
{373}{}{Cám ơn. Tạm biệt.}
{374}{}{Tôi mừng là không còn phải nghe cậu lải nhải nữa. Tạm biệt.}
{380}{}{Đcm, Wooz *có* lá Black Dahlia! Mỗi thế thôi cũng là đủ cho cả chuyến đi này rồi. Đám ghoul thoạt nhìn thì
đúng là như quỷ, nhưng bỏ kính ra thì cũng không đến nỗi nào. Mà cám ơn đã đưa tôi đến chỗ này. Đây,
[Cậu ta thò tay vào túi, rồi nhăn mặt] cái đm, rõ ràng nó ở đây mà. Ờ, xin lỗi, có vẻ như tôi đã để quên phần
thưởng ở nhà rồi nên tôi chỉ có thể gửi lời cám ơn thôi. Gặp lại sau nhé.}
{381}{}{Ờ, ừm, không cần đâu. Tôi mừng vì đã giúp được cậu. Tạm biệt.}
{382}{}{Tôi mừng là không còn phải nghe cậu lải nhải nữa. Tạm biệt.}
{400}{}{Không rảnh để nói chuyện... phải tạo bộ bài mạnh hơn...}
{500}{}{Để tôi yên.}
{501}{}{Biến đi.}
{502}{}{Đm cút.}
{600}{}{Ồ bạn tôi à. Có thằng nào đấy làm nổ tung lò phản ứng ở Gecko và tất cả đám ghoul đều bỏ đi cả rồi. Tôi chẳng
còn lí do gì để ở đó nữa nên tôi cũng rời đi và quay trở lại đây. Thật may là các thầy tu khác không hỏi gì về lúc tôi không ở
đây, nên tôi không gặp rắc rối gì. Tệ thật đấy, tôi nghĩ rằng tôi đã được sống để làm điều tôi thích [Thở dài].}
{601}{}{Thật tiếc khi biết tin này. Gặp lại cậu sau.}
{602}{}{Cuộc sống mà. Mới trước đó thôi ta đang trên đỉnh, thế mà chỉ một thoáng sau đã tụt xuống bùn sâu. Cứ sống và phấn đấu thôi. Tạm biệt.}
{610}{}{Chắc là tôi chỉ còn cách chấp nhận nơi này.}
{1000}{}{Bạn đã đưa Thầy Jason đến nhà mới an toàn.}
