{100}{}{Bạn thấy Thầy John.}
{101}{}{Bạn thấy một trong số các Thầy tu già của Tu viện.}
{102}{}{Bạn thấy một thầy tu già. Có vẻ như ông ta hơn 70 tuổi.}
{300}{}{Xin chào, người trẻ.}
{301}{}{Ông là ai?}
{302}{}{Ông có biết gì về GECK hoặc Vault 13 không?}
{303}{}{Chào.}
{400}{}{Tên ta là John, ta là một trong số các thầy tu già nhất ở đây.}
{401}{}{Vậy, ông làm gì ở đây?}
{402}{}{Tôi hiểu rồi, tạm biệt.}
{403}{}{Ta từng đi cày ngoài đồng, nhưng việc đó khiến ta bị đau tim.}
{404}{}{Ông bị bệnh tim à?}
{405}{}{Tệ thật đấy, chào nhé!}
{406}{}{Ừ, ta bị dị tật tim. Nếu ta vẫn còn thuốc trợ tim thì cuộc sống này sẽ dễ thở hơn nhiều. Rất khó để tìm
được thuốc điều trị tim trong thế giới hiện tại.}
{407}{}{Tôi có thể có cách giải quyết bệnh tim của ông...}
{408}{}{Đáng tiếc thật đấy. Tạm biệt.}
{410}{}{Chào.}
{411}{}{Thật à? Cậu đang nói là cậu thật sự CÓ thuốc trợ tim?}
{412}{}{Đúng vậy. Tôi sẽ rất vui được đưa chúng cho ông.}
{413}{}{Đúng vậy, tôi có thuốc trợ tim. Ông có thể mua với giá 400$.}
{414}{}{Đùa thôi. Tôi làm gì có thuốc trợ tim.}
{415}{}{[Ông ta nhận thuốc từ tay bạn] Cám ơn con! Đây, vui lòng nhận thứ này thay lời cảm ơn.}
{416}{}{Rất vui vì đã giúp được ông, và cám ơn về món đồ. Tạm biệt!}
{417}{}{(Ông ta nổi cơn tức giận, nhưng sau đó bình tĩnh lại) Ok, được rồi, tiền của cậu đây. Giờ thì đưa thuốc cho ta!}
{418}{}{Tôi quyết định giữ lại thuốc cho mình rồi. Cám ơn vì chỗ tiền nhé!}
{419}{}{Rất vui được giao dịch với ông. Tạm biệt.}
{420}{}{Hừm, xin lỗi, ta không biết. Hãy nói chuyện với Thầy trụ trì, ông ta có thể sẽ biết gì đó.}
{421}{}{Cám ơn, tôi sẽ làm vậy. Giờ thì tôi muốn hỏi chuyện khác.}
{422}{}{Nếu ta mà không bệnh thì ta đã đánh cho cậu phọt cứt ra rồi. GIỜ THÌ CÚT ĐI!}
{423}{}{Được, tôi đi.}
{500}{}{Cám ơn con lần nữa vì những viên thuốc tim này. Chúc con may mắn trên cuộc hành trình.}
{600}{}{Đi chỗ khác đi, làm ơn.}
{700}{}{Bạn cho John thấy thế giới này tồi tệ đến thế nào.}
