{100}{}{Bạn thấy một thầy tu trung niên.}
{101}{}{Bạn thấy Thầy Matthew.}
{102}{}{Ông ta đang đứng trên bục giảng kinh cho người dân của Tu viện.}
{200}{}{Những cư dân thiện lành của Tu viện. Hãy dành thời gian lắng nghe, vì ta có nhiều điều muốn nói.}
{201}{}{Tại đây, chúng ta thu thập những đồ thánh tích từ quá khứ xa xưa.}
{202}{}{Bị trận Đại hỏa thiêu rụi, chúng ta chìm vào đêm đen.}
{203}{}{Dựng nên Kho kỉ vật, chúng ta bảo tồn trí tuệ xưa cũ.}
{204}{}{Chúng ta phải canh gác và giữ gìn, dù cho ngọn lửa đã tàn;}
{205}{}{Lửa vẫn có thể bùng lên, nếu trí tuệ bị dùng cho mục đích sai trái.}
{206}{}{Và không ai có thể học hỏi được nữa, trong nỗi sợ trận Đại hỏa.}
{207}{}{Nhưng một ngày, nhân loại sẽ vượt lên được ham muốn tàn phá.}
{208}{}{Và Kho kỉ vật sẽ ở đó, chờ được đưa trở lại.}
{209}{}{Vì vậy chúng ta hãy thực hành nghĩa vụ thiêng liêng của mình,
kẻo tất cả trí tuệ sẽ chìm vào sự lãng quên.}
{210}{}{Chúng ta phải lưu giữ và bảo vệ, nhưng không được phép sử dụng.}
{211}{}{Vậy nên giờ đây, các bạn của ta, hãy để tâm hồn được nâng đỡ;}
{212}{}{Với tư cách người bảo vệ kiến thức, mỗi người trong chúng ta, đều được ban phước.}
{213}{}{Giờ thì hãy dành thời gian để suy ngẫm về những điều ta vừa nói.}
{224}{}{Giờ thì hãy dành thời gian để suy ngẫm về những điều ta vừa nói.}
{300}{}{Xin chào, người bạn. Ta nghĩ rằng mình chưa từng gặp bạn ở đây trước kia. Tên ta là Thầy Matthew và ta
giúp truyền bá về tầm quan trọng của việc giữ gìn kiến thức của tiền nhân.}
{301}{}{Rất vui được gặp ông Matt. Tên tôi là }
{302}{}{ và tôi đang trên đường đi tìm GECK thần thánh.}
{303}{}{Xin lỗi, tôi phải đi đây.}
{400}{}{GECK à? Ta nhớ là hình như ta đã đọc điều gì đó về thứ này trong một lần phiên dịch sách. Vậy nên thứ này hẳn
phải có trong cơ sở dữ liệu, nhưng ta e là máy tính của chúng ta bị hạn chế quyền truy cập. Tuy vậy, nếu bạn hỏi
Thầy trụ trì thì có thể bạn sẽ được cấp quyền. Cũng đâu có mất gì. Ồ, và cứ tự do ngắm qua bộ sưu tập các đồ kỉ vật
trước chiến tranh ở đây. Đúng ra thì ta sẽ yêu cầu bạn không làm hỏng thứ gì, nhưng ta e là mọi thứ đều hỏng rồi.}
{401}{}{Chắc là tôi sẽ làm vậy. Mà tôi có vài câu hỏi.}
{402}{}{Cám ơn. Để tôi đi hỏi ngay.}
{500}{}{Sẵn lòng phục vụ bạn. Bạn muốn biết gì nào?}
{501}{}{Ông có thể nói gì về nơi này?}
{502}{}{Ông có vẻ vừa thuyết giảng vừa làm thơ. Có lí do gì không?}
{503}{}{Không có gì. Bảo trọng.}
{600}{}{Tu viện chào đón tất cả, miễn là họ không gây rắc rối. Chúng ta là một cộng đồng độc lập và thi thoảng mới có khách
như bạn. Hầu hết những người bạn thấy ở đây đều là hậu duệ của những người sáng lập ban đầu vốn định cư ở tu viện
cũ này không lâu sau trận Đại Hỏa.}
{601}{}{Tiếp tục đi.}
{602}{}{Sự yên tĩnh và bình yên tại nơi này đã khiến tu viện trở thành ngôi nhà hấp dẫn nhiều lữ khách khác ghé vào 
trong nhiều năm, tìm kiếm nơi ẩn trốn khỏi sự hỗn loạn u ám của hoang mạc. Dĩ nhiên, giá trị thực sự của nơi này
nằm ở thư viện đồ sộ xếp đầy những cuốn sách cổ, chứa đựng trí tuệ kì lạ của thời đã mất. Theo thời gian, chúng ta
dần tự coi mình là người giữ gìn và bảo vệ nguồn trí tuệ này.}
{603}{}{Thú vị đấy. Để tôi hỏi câu khác.}
{604}{}{Hay đấy. Mà tôi phải đi đây.}
{700}{}{[Ông ta cười khúc khích trước câu hỏi của bạn] Không, không có lí do gì cả. Ta chỉ đọc rất nhiều thơ trong suốt
cuộc đời và thích đưa thơ vào lời thuyết giảng. Việc đó tạo ra ấn tượng lớn hơn cho người nghe.}
{701}{}{Cũng đúng. Để tôi hỏi câu khác.}
{800}{}{Rất vui được gặp lại bạn }
{801}{}{. Ta có thể giúp gì cho bạn?}
{802}{}{Tôi có vài câu hỏi.}
{803}{}{Không có gì. Gặp lại ông sau.}
