{100}{}{Bạn thấy Bà Peterson.}
{101}{}{Bạn thấy một phụ nữ trẻ xinh đẹp. Cô ta cười khi thấy bạn.}
{200}{}{Chào mừng đến với Tu viện, người bạn.}
{201}{}{Hãy nói với chồng tôi nếu cần gì đó.}
{202}{}{Hôm nay đẹp trời nhỉ?}
{300}{}{Chào mừng đến với Tu viện, người bạn.}
{301}{}{Hãy nói với chồng tôi nếu cần gì đó.}
{302}{}{Buổi tối mát thật đấy, nhỉ?}
{400}{}{Tôi không có gì để nói. Vui lòng đi chỗ khác.}
