{100}{}{Bạn thấy máy bơm nước.}
{101}{}{Bạn thấy một chiếc máy bơm nước cũ có vẻ đã bị hỏng.}
{102}{}{Máy bơm nước giờ đã hoạt động bình thường.}
{103}{}{Bạn sẽ không thể sửa máy chỉ với đôi bàn tay không. Có thể bạn sẽ cần một ít dụng cụ để lắp bộ phận này.}
{104}{}{Bạn đã sửa máy bơm nước.}
{105}{}{Bạn không sửa được máy bơm.}
{106}{}{Bạn đã tìm ra vấn đề của máy bơm nước.}
{200}{}{Bạn mở máy ra và xem bên trong. Bạn thấy rất nhiều bánh răng và động cơ rỉ sét. Một động cơ trong
số này đã bị nứt.}
{201}{}{Dừng ở đây thôi.}
{202}{}{Tìm hiểu thêm.}
{203}{}{Sau khi tìm hiểu kĩ hơn, bạn thấy rằng vết nứt không phải là nguyên nhân mà là đầu nối
chỗ dây dẫn vào. Mấy điểm đầu nối đã cháy rụi sau nhiều năm sử dụng. Sẽ cần nguyên một bộ động cơ và dây điện
mới để làm cho cái máy này hoạt động trở lại.}
{204}{}{Thoát.}
