{100}{}{Bạn thấy một bảng máy tính nhỏ.}
{101}{}{Bạn thấy bảng máy tính của Tu viện.}
{102}{}{Bạn thấy một bảng máy tính nhỏ. Có vẻ như nó vẫn chạy.}
{103}{}{Bạn truy cập vào máy tính và quét tất cả tệp có sẵn. Bạn tìm thấy vài tệp có chứa từ khóa "GECK" và "Vault".}
{104}{}{Đọc thông tin về GECK.}
{105}{}{Đọc thông tin về Vault.}
{106}{}{LỖI! không tìm thấy thẻ truy cập. Vui lòng nhét thẻ truy cập vào khe mã hóa.}
{107}{}{(Bạn nhét thẻ truy cập vào khe) BÍP! thẻ truy cập hợp lệ. ĐANG TẢI Winblows 2075... XONG.}
{108}{}{Nhập lệnh.}
{109}{}{Quét tệp để tìm thông tin về GECK hoặc VAULT 13.}
{110}{}{Truy cập các tệp khác.}
{111}{}{Chơi Búa Bao Kéo.}
{112}{}{Trở lại.}
{113}{}{Đăng xuất.}
{114}{}{[TIẾP TỤC]}
{115}{}{Bạn tìm thấy vài tệp có chứa từ khóa "GECK" và "Vault".}
{116}{}{Xem các tệp có liên quan đến "GECK".}
{117}{}{Xem các tệp có liên quan đến "Vault".}
{118}{}{Bạn thấy chương trình tìm kiếm rất khó hiểu.}
{119}{}{Bạn tròn mắt và thở gấp khi phát hiện thấy thứ trông giống như một tin quảng cáo cũ về Bộ tạo Vườn Địa đàng. Trong
quảng cáo, một gã nhân vật hoạt hình mặc đồ vault cười toét miệng cầm một cái vali lớn có ghi "Bộ Sinh tồn". Cứ như
thể gã ta đang chọc tức bạn vậy.}
{120}{}{Bạn xem qua các tệp, trong đó hầu như chứa nội dung tuyên truyền của chính quyền về sự tuyệt vời của cuộc sống trong các Vault.
Bạn biết được là vào giữa thế kỉ 21, chính quyền Hoa Kỳ đã ủy quyền cho Vault-Tec xây dựng 122 Vault trên khắp đất nước. Những căn hầm
này được dùng làm nơi trú ẩn cho tối đa 1.000 công dân Hoa Kỳ trong trường hợp xảy ra thảm họa hạt nhân. Dưới sự bảo vệ có giới hạn của
các Vault dưới lòng đất, các Cư dân Vault có thể tận hưởng cuộc sống xa hoa trong lúc đợi tín hiệu thông báo thế giới trên mặt đất
một lần nữa đã an toàn.}
{121}{}{Bạn tìm thấy hàng trăm đầu sách và tạp chí điện tử được phân loại trên ổ cứng trong lúc tìm trên hệ thống. Bạn còn
chẳng biết phải bắt đầu tìm kiếm thông tin hữu ích từ đâu.}
{122}{}{Bạn tìm thấy hàng trăm đầu sách và tạp chí điện tử được phân loại trên ổ cứng trong lúc tìm trên hệ thống. Vì bạn đã thành thạo
với cách lưu trữ thông tin, có thể bạn nên tìm kiếm theo chủ đề để tìm ra được thứ gì đó có ích.}
{123}{}{[THÊM]}
{124}{}{Theo quảng cáo, bộ này có chứa một "Thiết bị Tái chế cơ bản", cho phép "tái tạo thực phẩm và các vật dụng cơ bản cần thiết
để xây dựng thế giới mới", một "Đầu đọc Holodisc và Thư viện" trong đó "có chứa các thông tin được đơn vị Thư viện Quốc hội lựa chọn,
bộ bách khoa toàn thư hoàn chỉnh cùng các thông tin cứu sinh khác, tất cả đều nằm trên 460 holodisc tiện dụng!" và thậm chí có cả một
"Đèn pin đầu bút thu nhỏ!" Chắc chắn thiết bị thần kì này chính là thứ bạn cần để cứu ngôi lành đang suy sụp của mình.}
{125}{}{Đọc thêm.}
{126}{}{Bạn tiếp tục xem các tệp, nhưng thông tin duy nhất mà bạn tìm thấy về Vault 13 là căn hầm này nằm ở California, không
có địa chỉ rõ ràng nên không có ích mấy.}
{130}{}{Thêm thông tin.}
{131}{}{[Bạn không có gì để thêm]. Trở về.}
{132}{}{Thêm thông tin về Cây trồng.}
{133}{}{Thêm thông tin [Rác].}
{140}{}{Đọc tệp Giúp đỡ/Thông tin.}
{141}{}{Chúc mừng bạn đã cài thành công Winblows 75! Đây là phiên bản Winblows hiện đại nhất đến thời điểm hiện tại. Với xác suất treo máy
chỉ trong một phần một triệu lần lập lệnh được xác thực, các kĩ thuật viên của chúng tôi tự tin rằng Winblows giờ đây đã trở nên hoàn hảo
cho bất kì môi trường doanh nghiệp nào. Phiên bản Winblows 2075 mới nhất là bản mã cơ bản được cải thiện và điều chỉnh để chỉ hao phí
15% vòng chạy CPU dành cho quản trị nền thay vì hao phí đến 25% trong phiên bản trước đó. Dĩ nhiên, nhiều tính năng hỗ trợ người dùng
đã được thêm vào trong bản mới nhất này. Cũng như các phiên bản Winblows trước đó, người dùng có thể sử dụng các lệnh phổ thông như 
Tìm kiếm, Thêm, Di chuyển, Xóa và Định dạng.}
{142}{}{Định dạng tệp hệ thống, bao gồm toàn bộ cơ sở dữ liệu sao lưu trên máy chủ và các máy kết nối.}
{143}{}{Trở lại.}
{144}{}{Đang định dạng cơ sở dữ liệu sao lưu... THÀNH CÔNG... Đang định dạng tệp hệ thống hiện tại... ĐANG CHỜ... Cảnh báo: Đã xảy ra lỗi
nghiệm trọng. Vui lòng chờ...}
{145}{}{Chờ.}
{146}{}{... Lỗi hệ thống: Quá trình đã hoàn tất thành công... (Tiếng rít bắt đầu phát ra từ bên trong máy tính và các máy gần đó).}
{147}{}{[Bỏ đi].}
{148}{}{Lỗi: Không tìm thấy bàn phím. Vui lòng nhấn phím bất kì để khởi động lại.}
{150}{}{Đang tải lên đĩa thông tin Thực vật của Cơ quan Bảo vệ Môi trường... Tải lên hoàn tất. Chúc một ngày tốt lành.}
{200}{}{Búa, Kéo, Bao V.0.3. Đưa ra lựa chọn.}
{201}{}{Chọn BÚA.}
{202}{}{Chọn BAO.}
{203}{}{Chọn KÉO.}
{204}{}{Quay về màn hình chính.}
{205}{}{Máy thực hiện chọn... Đang tính kết quả... Máy thắng!}
{206}{}{Máy thực hiện chọn... Đang tính kết quả... Người dùng thắng!}
{207}{}{Máy thực hiện chọn... Đang tính kết quả... Hòa!}
{300}{}{(Màn hình máy tính hiện nhiều dải màu).}
{301}{}{Ồ ồ ồ! Màu đẹp.}
{302}{}{Tắt nguồn.}
{400}{}{Đọc thêm.}
{401}{}{Quay về màn hình.}
{402}{}{Tìm kiếm theo chủ đề.}
{403}{}{Vui lòng nhập một chủ đề để tìm kiếm.}
{404}{}{Khoa học.}
{405}{}{Sửa chữa.}
{406}{}{Y dược.}
{407}{}{Sử dụng vũ khí.}
{408}{}{Lập luận thuyết phục.}
{410}{}{Sau vài giờ ngồi đọc, bạn đã học thêm được nhiều điều về bộ môn khoa học.}
{411}{}{Sau vài giờ ngồi đọc, bạn đã học thêm được nhiều điều về cách sửa chữa máy móc.}
{412}{}{Sau vài giờ ngồi đọc, bạn đã học thêm nhiều điều về môn y dược.}
{413}{}{Sau vài giờ ngồi đọc, bạn đã học thêm được nhiều điều về cách tự phòng vệ có vũ khí.}
{414}{}{Sau vài giờ ngồi đọc, bạn đã học thêm được nhiều điều về cách thuyết phục.}
{420}{}{Sau vài giờ ngồi đọc, bạn không học thêm được gì mới về bộ môn khoa học.}
{421}{}{Sau vài giờ ngồi đọc, bạn không học thêm được gì về cách sửa chữa máy móc.}
{422}{}{Sau vài giờ ngồi đọc, bạn không học được gì mới về môn y dược.}
{423}{}{Sau vài giờ ngồi đọc, bạn không học thêm được gì với về cách bắn súng.}
{424}{}{Sau vài giờ ngồi đọc, bạn không học thêm được gì mới về cách thuyết phục.}
{430}{}{Trở lại.}
{500}{}{Trong lúc đọc thêm thông tin, bạn biết được rằng GECK là do Future-Tec, một công ty nhánh của Vault-Tec, phát triển
và là trang bị tiêu chuẩn cho toàn bộ các hầm của Vault-Tec. Thiết bị này sẽ được sử dụng sau khi rời khỏi Vault để giúp
thiết lại cuộc sống trong môi trường khắc nghiệt của một thế giới bị chiến tranh hạt nhân tàn phá.}
{501}{}{Sau khi đọc kĩ hơn, bạn khám phá ra rằng GECK không hẳn là thiết bị thần kì như quảng cáo nói. Bộ "Tái tạo cơ bản" trên
thực tế chỉ là một hệ thống dưỡng cây có chứa hạt giống lương thực, chất bổ sung cho đất và các hóa chất được thiết kế đặc biệt để
biến đất hoang mạc khô cằn thành đất trồng. Tuyên bố về việc thiết bị có thể "sản xuất các vật dụng cơ bản" thực ra là nói về các
mã mới mà thiết bị cung cấp cho các máy móc trong Vault, cho phép tạo ra các vật dụng mới trong máy phân phối. GECK cũng chứa
bản thiết kế về các lớp trường lực cơ bản cũng như cách xây dựng tường và công trình bằng "bê tông cát".}
{502}{}{[THÊM]}
{503}{}{Có vẻ như bản thân bộ GECK sẽ được tháo rời ra trong quá trình sử dụng. Bạn đọc một ví dụ về cách sử dụng bộ nguồn hợp hạch lạnh
làm nguồn điện sản xuất chính cho thành phố. GECK thậm chí còn chứa cả hướng dẫn về cách tháo rời các phần của Vault để xây nhà
và các cấu trúc phòng thủ cho cộng đồng mới. Sau khi đọc xong, bạn nhận định rằng cho dù đây không phải là thiết bị thần kì như
Trưởng Lão đã nghĩ, thì đi tìm GECK vẫn là lựa chọn tốt nhất để cứu bộ tộc.}
{1000}{}{Bạn tải đĩa holodisk Thực vật EPA lên.}
{2000}{}{Bạn định dạng cơ sở dữ liệu sách của Tu viện.}
