{100}{}{B?n th?y Th?y tr? tr?, ngư?i đ?ng đ?u tôn giáo c?a Tu vi?n.}
{101}{}{Có th? g? đó v? th?y tu này khi?n b?n tin r?ng ông ta r?t quan tr?ng.}
{200}{}{Xin chào, ngư?i l? khách.}
{201}{}{B?nh an nhé.}
{202}{}{Chúng tôi là nh?ng ngư?i gi? g?n ki?n th?c.}
{203}{}{Tôi r?t ti?c, nhưng ki?n th?c trong sách c?a chúng tôi không giúp g? đư?c cho c?u.}
{300}{}{Chào m?ng đ?n v?i Tu vi?n, ngư?i l? khách. Tôi có th? giúp g? đây?}
{301}{}{Ông có th? nói g? v? h?i không?}
{302}{}{Ông có t?ng nghe nói đ?n m?t th? g?i là GECK chưa?}
{303}{}{Ông có bi?t tôi có th? t?m Vault 13 ? đâu không?}
{304}{}{Chào.}
{400}{}{Mu?n bi?t g? nào?}
{401}{}{Okay. Tôi mu?n h?i v? vi?c khác.}
{402}{}{H?m... nghe *có v?* quen. ?, có, tôi nh? là Th?y Thomas g?n đây có nh?c g? đó đ?n th? này. Th? l?i nhưng tôi không nh? chính xác ông ta đ? nói g?.}
{403}{}{Không sao. Ch? c?n nói cho tôi bi?t Th?y Thomas ? đâu và tôi s? đi h?i ông ta.}
{404}{}{Tôi không bi?t g? v? chuy?n đó.}
{405}{}{?, d?u sao th? c?ng cám ơn.}
{406}{}{Tôi e là tôi không làm đư?c chuy?n đó. C?u xem, tôi ng? là Th?y Thomas không c?n s?ng n?a. Nhưng th?t may cho c?u
th?y là m?t trong nh?ng ngư?i ghi chép đáng tin c?y nh?t. Tôi ch?c là b?t k? n?i dung nào mà ông ta có đư?c v? thông tin
c?u đang t?m ki?m đ? đư?c ghi vào trong máy tính c?a chúng tôi.}
{407}{}{Ch? đ?, ông đang "ng?" r?ng th?y Thomas đ? ch?t? ? ngoài kia cái ch?t r? ràng l?m. Ông ta th?c ra đ? ch?t hay chưa?}
{408}{}{Huynh Thomas đ? m?t tích trong nhi?u ngày k? t? khi ông ta đi xu?ng hang đ?ng bên dư?i Tu vi?n [Ông ta th? dài y?u ?t].
C?u th?y đ?y, m?t vài ngư?i trong Tu vi?n k? r?ng có nh?n th?y m?t con quái v?t to l?n ?n thân dư?i đó, nhưng Th?y Thomas
không tin đi?u đó. Ông ta t? m?nh đi xu?ng đ? xóa b? tin đ?n, v?y mà trên th?c t? vi?c ông ta m?t tích ch? là minh ch?ng r? hơn.}
{409}{}{H?m. Ch?c là tôi nên đi xem có g? dư?i đó. *TÔI* là c?u tinh cơ mà...}
{410}{}{Tôi chuyên đi phiêu lưu. Tôi có th? đi xem sao.}
{411}{}{C?u s? làm v?y th?t à? Ch?c là trong lúc xu?ng đó, c?u có th? t?m m?t cu?n sách này. C?u xem, th?y Thomas là ngư?i
cu?i cùng gi? cu?n sách, và nó r?t quan tr?ng v?i chúng tôi. Cu?n sách đ? đư?c truy?n l?i t? th?i ngư?i sáng l?p. N?u
c?u có th? l?y l?i cu?n sách th? tôi s? r?t bi?t ơn. Nói luôn là tôi s? c?p cho c?u toàn b? quy?n truy c?p vào máy tính
đ? c?u có th? t?m ki?m b?t c? cái g? c?u mu?n.}
{412}{}{C? v?y đi. Tôi s? s?m tr? l?i.}
{413}{}{Có th?. Đ? tôi ngh? thêm m?t lát đ?...}
{414}{}{Cám ơn. Vui l?ng nói cho tôi bi?t khi nào t?m th?y sách.}
{415}{}{Ok, t?m bi?t.}
{416}{}{Xin chào, b?n tôi.}
{417}{}{Tôi đ? tiêu di?t con quái v?t và l?y l?i sách đây.}
{418}{}{Tuy?t v?i! H?y đưa cho tôi!}
{419}{}{Đây.}
{420}{}{T? t? đ?. Cu?n sách này đáng giá bao nhiêu?}
{421}{}{[Ông ta nh?n cu?n sách t? tay b?n và vu?t ve b?a sách như th? đ? an ?i]. C?u đ? giúp chúng tôi r?t nhi?u. Gi?
th? c?u có đ?y đ? quy?n truy c?p vào máy tính trong thư vi?n. H?y nói v?i Huynh Paul là tôi c?p quy?n truy c?p cho c?u.}
{422}{}{Cám ơn.}
{423}{}{C?u mu?n l?y ti?n à? Đư?c r?i, c?m l?y 250$. Đ?n g?p Huynh Paul đ? l?y quy?n truy c?p máy tính.}
{424}{}{Cám ơn v? ch? ti?n, t?m bi?t.}
{425}{}{C?u nên dùng máy tính trên t?ng hai, gi? th? c?u đ? có đ?y đ? quy?n truy c?p r?i.}
{426}{}{Ok, t?m bi?t.}
{430}{}{H?i này có m?c đích g? v?y?}
{431}{}{L?ch s? c?a Tu vi?n ra sao?}
{432}{}{H?m, tôi hi?n không có câu h?i nào.}
{433}{}{Nhi?m v? th?n thánh c?a chúng tôi là đ?c, sao chép và b?o qu?n nh?ng cu?n sách ki?n th?c thiêng liêng cùng
nh?ng b?o v?t khác t? th?i đ? m?t. Chúng tôi hi v?ng là v?i ki?n th?c này, chúng tôi có th? t?o ra Khu k? v?t đ? m?t ngày
nào đó giúp nhân lo?i thoát kh?i th?i k? Đen t?i do m?nh t? gây ra. T?t c? nh?ng thông tin chúng tôi t?m th?y đ?u đư?c
ghi l?i đ? kh?i b? m?t như r?t nhi?u th? khác trong cơn Đ?i H?a.}
{434}{}{Sau Đ?i chi?n, bàn tay d?n l?i c?a v?n m?nh đ? ch? đư?ng cho t? tiên chúng tôi đ?n v?i Tu vi?n c? trong núi này. Nh?
v? trí bi?t l?p, tu vi?n đ? thoát kh?i cơn Đ?i H?a mà không b? hư h?i nhi?u. Trong lúc khám phá t?a nhà, t? tiên chúng tôi
phát hi?n m?t thư vi?n đ?y sách. Và không ch? có sách tôn giáo, ?, thư vi?n này c?n ch?a đ?ng r?t nhi?u tác ph?m vi?t
n?a, t? văn h?c c? đi?n đ?n bách khoa toàn thư khoa h?c.}
{435}{}{Sau đó th? sao?}
{436}{}{Tôi nghe đ? r?i.}
{437}{}{H? nhanh chóng nh?n ra kho báu ki?n th?c th?t s? ch?a trong nh?ng cu?n sách này -- nh?t là nh?ng cu?n
khoa h?c. Đây là biên niên s? v? m?t n?n văn minh đ? s?p đ?. M?t th?i đ? m?t. Có m?t s? ngư?i tin r?ng t?t nh?t
nên h?y nh?ng ki?n th?c này, s? r?ng chúng s? m?t l?n n?a hư?ng nhân lo?i đ?n t?n th?. Nhưng cu?i cùng h?
quy?t đ?nh r?ng thay vào đó, h? s? c?ng hi?n c? đ?i đ? b?o qu?n nh?ng cu?n sách, đ? đưa ki?n th?c tr? l?i khi và
n?u, th? gi?i đ? s?n sàng đón nh?n.}
{438}{}{(Thêm)}
{439}{}{Và như v?y, s? d?ng m?t máy in nh?, h? b?t đ?u sao chép các cu?n sách c?ng như ghi chép l?i chúng vào
máy tính c?a Tu vi?n đ? b?o qu?n d?ng s?, ph?ng khi sách b?n g?c b? hư h?i. Qua nhi?u năm dài, nh?ng ngư?i khác
đ? đ?n Tu vi?n và m?t s? đ? ch?n ? l?i đ? s?ng đ?i t?nh l?ng trong ngôi nhà trên núi này.}
{440}{}{Cám ơn v? câu chuy?n.}
{441}{}{T? tiên c?a các ông đ?n t? đâu?}
{442}{}{H? ch?ng nói g? v? ngu?n g?c ban đ?u c?. Chúng tôi ng? r?ng h? ban đ?u đ?n t? phía Đông.}
{443}{}{?, cám ơn v? câu chuy?n.}
{444}{}{Ông có c?n giúp g? ? tu vi?n không?}
{445}{}{Tôi đ? t?m ra lí do máy bơm nư?c b? h?ng r?i.}
{446}{}{Ông có bi?t g? v? nh?ng ngư?i sáng l?p ban đ?u không?}
{447}{}{Tôi không bi?t t?t c? tên c?a nh?ng ngư?i sáng l?p, nhưng ngư?i quan tr?ng nh?t mà tôi bi?t là Miller.
Trư?c Đ?i chi?n ông là m?t k? sư đi?n làm vi?c cho chính ph? Hoa K?. Không lâu sau đó, ông c?i sang đ?o Công giáo
và l?p l?i th? r?ng s? dành c? cu?c đ?i đ? b?o t?n ki?n th?c trong quá kh?. Đi?u khi?n ông s? nh?t là ki?n th?c s? b?
m?t đi m?i m?i và do đó, c?n đư?c b?o t?n đ? các th? h? tương lai đư?c hư?ng l?i.}
{448}{}{Ông đ?c nhi?u th? ch?c ph?i bi?t nhi?u l?m.}
{449}{}{Đúng là tôi đ? đ?c r?t nhi?u trong su?t cu?c đ?i. Nhưng có th? c?u s? th?y th?t v?ng trư?c gi?i h?n ki?n th?c
c?a tôi. C?u th?y đ?y, chúng tôi ghi chép và b?o t?n. Chúng tôi b? c?m s? d?ng tri th?c trong sách, do đó chúng tôi ch? hi?u m?t ph?n thôi.}
{450}{}{Ch? đ?, ông đang nói là các ông ch? nh?m m?t chép l?i sách ch? không thèm t?m hi?u chúng có ngh?a g??}
{451}{}{Như đ? nói, công vi?c c?a chúng tôi là b?o t?n ki?n th?c ch? không ph?i đ? hi?u. Trư?c khi nh?ng ki?n th?c
này tr? l?i v?i nh?n lo?i, loài ngư?i đ?u tiên c?n ch?ng minh h? đ? vư?t lên trên cái thói di?t ch?ng hàng lo?t. Đó là
cách duy nh?t đ? đ?m b?o r?ng l?ch s? s? không l?p l?i.}
{452}{}{?, v?y th? tôi có tin t?c cho ông đây: ngày đó s? ch?ng bao gi? đ?n c?. Trong lúc các ông đang ôm m? ki?n th?c trong
thiên đư?ng nh? trên núi này, nh?ng ngư?i khác ? hoang m?c đang v?t l?n h?ng ngày đ? sinh t?n. Th?c ra, c? t?c tôi đang
trên b? v?c di?t vong. Nh?ng ki?n th?c có trong đ?ng sách này có th? giúp ch?a b?nh, c?i t?o cây tr?ng và nâng cao kh? năng
s?ng sót c?a nhân lo?i đ?y.}
{453}{}{Ah, ch?c là ông nói có đi?m đúng. Nhưng có v? nh?ng thông tin đư?c lưu tr? ? đây có th? giúp đ? r?t nhi?u ngư?i.
Dù cho các ông có ngh? r?ng th? gi?i chưa s?n sàng đ? đón nh?n ki?n th?c, nhưng tôi không hi?u t?i sao *ông* chí ít
không th? h?c h?i chúng. N?u không th? vi?c lưu gi? có ngh?a lí g??}
{454}{}{Tôi hi?u là c?u th?y khó ch?u v?i l? s?ng này, nhưng c?u ph?i hi?u r?ng đây là cách mà chúng tôi luôn tuân theo.
Gi? mà thay đ?i, sau bao nhiêu năm... đi?u đó s? trái ngư?c hoàn toàn v?i đ?c tin c?a chúng tôi. Không, tôi th?y là
chúng tôi c?n ti?p t?c s?ng theo các gi?i lu?t do t? tiên đ?t ra.}
{455}{}{Tôi hi?u là c?u th?y khó ch?u v?i l? s?ng này, nhưng c?u ph?i hi?u r?ng đây là cách mà chúng tôi luôn tuân theo.
Gi? mà thay đ?i, sau bao nhiêu năm... đi?u đó s? trái ngư?c hoàn toàn v?i đ?c tin c?a chúng tôi. Tuy v?y, tôi s? suy
ngh? v? l?i c?a c?u. Tôi c?m nh?n đư?c trí tu? c?a c?u, ngư?i l? khách. Th?t ti?c là tôi ch? g?p đư?c s? ít ngư?i như c?u.}
{456}{}{Cám ơn. Tôi mu?n h?i v? vi?c khác n?a.}
{457}{}{Đư?c r?i. Tôi mu?n h?i v? vi?c khác n?a.}
{500}{}{D?ng l?i!}
{501}{}{B?n nh?n đư?c 200 đi?m kinh nghi?m v? đ? mang cu?n sách tr? l?i.}
{600}{}{I fixed your broken waterpump.}
{601}{}{That is great news, indeed. That waterpump had been acting up for quite some time. Those merchants said they
 could take care of it, but they didn't seem to be making much progress. It's a good thing you came along. Thank you again.}
{602}{}{I expect some money for this you know. Now cough it up!}
{603}{}{No problem. I have some other questions though.}
{604}{}{I'm glad to be of assistance. Take care.}
{605}{}{[Frowns.] I see. Fine, here, take these coins. Now go, and stop bothering me.}
{606}{}{Thank you, *father*.}
{700}{}{Uhh... no I seem to have misplaced it.}
{701}{}{What!? [He sighs deeply.] It is most unfortunate that you were unable to recover that book. But you say you've
 killed the beast? Hm, then it should be safe to send our own people down to continue searching for it. Anyway, for your
 service, I shall grant you access to our computers. Go see Brother Paul for the access key.}
{702}{}{Cám ơn.}
{800}{}{Actually, yes. Our main water pump has been acting up for some time, and now it finally seems to have broken down
 completely. If you know anything about machinery, do you think you could take a look and see if something could be done?
 There are a few merchants already working on it. I fear that little progress has been made though.}
{801}{}{I'm happy to help. I'll report back on the progress.}
{802}{}{Sure, I'll be glad to help... for a price of course.}
{803}{}{Actually on second thought, let me ask you something else.}
{804}{}{What!? Oh, fine. If that's the kind of person you are, then you shall receive payment for your service. Here's
 25 coins to begin with.  Please let me know if something can be done. [The man sighs as he hands you the coins]}
{805}{}{Hey, no need for the sighing. You think everything in life comes for free? Now, let me get to work.}
{806}{}{Really? Please, do tell.}
{807}{}{The motor gave out and fried all the connectors. I'm going to Vault City to get a new part.}
{808}{}{Oh thank you. You are indeed a great help. Please report back once you install the new part.}
{809}{}{I will. Be back soon.}
{900}{}{You explain to the Abbot that while the information they hold could lead to mankind's annihilation, it could also lead to mankind's salvation.}
{901}{}{You learn about the original founder of the Abbey.}
{1000}{}{I killie scary monster down in cave.}
{1010}{}{Really? That's great. That is very brave of you. You're a big boy.}
{1011}{}{Really? That's great. That is very brave of you. You're a big girl.}
{1012}{}{(smile) I know.}
{1020}{}{Did you happen to find a book lying there? A friend of mine had it, and he went missing.}
{1021}{}{I find book. Here, it heavy and no pitchers inside.}
{1022}{}{I no find book. Sorree. I go look now.}
{1030}{}{I find book.}
{1031}{}{That's great. Thanks. You're one special guy.}
{1032}{}{That's great. Thanks. You're one special gal.}
{1033}{}{YAY.}
{1100}{}{I was down there earlier. I saw a few dead bodies, so I'm guessing one of them belonged to your missing monk. If
 it makes you feel any better, I killed the thing responsible for his death.}
{1110}{}{Ah... so it's as I feared. Brother Thomas shall be dearly missed. You have my thanks for ridding us of whatever
 wasteland beasts lurked down there. However, I... I don't suppose you found a book while you were down there. It's a very
 important book that was last known to be in Brother Thomas's possession.}
{1111}{}{No, but I suppose I could go back and check.}
{1112}{}{Do you mean this book?}
{1113}{}{Before I go, let me ask you something else.}
{1411}{}{Very interesting. I have to go now.}
{3000}{}{Tôi giúp g? đư?c nh??}
{4091}{}{So no one else has even bothered to go down there and check on him? What if he's simply trapped down there somehow, and he's slowly starving to death?}
{4092}{}{I suppose that's possible, but you must understand. We are a peaceful people. The thought of going up against one of those wasteland monsters is terrifying to us. We're simply not equipped for such confrontations. }
{4177}{}{I've killed the beast.}
{4188}{}{Excellent! And how about the book; were you able to recover it?}
{6020}{}{If you truly want to show your gratitude, how about some money for my trouble?}
