{100}{}{Bạn thấy một thầy tu.}
{101}{}{Thầy tu này trông giống một lái buôn.}
{200}{}{Xin chào, người lữ khách.}
{201}{}{Bình an nhé.}
{202}{}{Thời tiết đẹp đấy.}
{203}{}{Đi chỗ khác chơi.}
{300}{}{Chào, tôi giúp gì được đây?}
{301}{}{Ông có thể nói gì về hội không?}
{302}{}{Hãy giao dịch.}
{303}{}{Chào.}
{400}{}{Nhiệm vụ thần thánh của chúng tôi là thu thập và bảo tồn các thánh tích của thời xa xưa. Mọi người đều được chào đón ở đây, miễn là không phá hỏng thứ gì.}
{401}{}{Ai là người lãnh đạo ở đây?}
{402}{}{Thánh tích gì vậy?}
{403}{}{Ông ta ở trên tầng ba. Nếu muốn tìm hiểu về hội thì hãy hỏi thầy trụ trì.}
{404}{}{Đủ các thể loại, nhưng đa số Kho kỉ vật của chúng tôi là các cuốn sách cổ. Trong các văn bản này có chứa rất nhiều thông tin. Nhiệm vụ của chúng tôi là bảo tồn kiến thức này để thế hệ tương lai có thể sử dụng để xây dựng một thế giới hòa bình và tốt đẹp.}
{405}{}{Okay.}
{406}{}{Ok.}
{500}{}{Dừng lại!}
