{100}{}{Bạn thấy một thầy tu.}
{101}{}{Bạn thấy một nữ tu.}
{102}{}{Thầy tu này trông có vẻ khá hiểu biết về máy tính.}
{103}{}{Nữ tu này trông có vẻ khá hiểu biết về máy tính.}
{200}{}{Đừng làm hỏng cái gì.}
{201}{}{Xin lỗi, giờ tôi đang bận.}
{202}{}{Xin chào.}
{203}{}{Cứ xem tự nhiên.}
{204}{}{Chúng tôi sao chép kiến thức cho thế hệ mai sau.}
{205}{}{Những quyển sách cổ này rất mỏng manh.}
{206}{}{Sao chép sách là một công việc nặng nhọc.}
{207}{}{Chào.}
{208}{}{Có rất nhiều thứ cần chép lại trong những cuốn sách này.}
{500}{}{Dừng lại!}
