{100}{}{Bạn thấy một thầy tu.}
{101}{}{Bạn thấy một nữ tu thần thánh.}
{102}{}{Bạn thấy một thầy tu bình thường của Tu viện.}
{103}{}{Bạn thấy một nữ tu bình thường của Tu viện.}
{200}{}{Xin chào.}
{201}{}{Chào mừng tới Tu viện.}
{202}{}{Hãy nói chuyện với trụ trì nếu muốn tìm thông tin.}
{203}{}{Chào ngày mới... hay là đêm rồi?}
{204}{}{Nhiều việc phải làm quá.}
{205}{}{Cuộc sống tại Tu viện rất yên bình. Đúng là nơi hiếm hoi ở chốn hoang tàn khốn khổ này.}
{500}{}{Dừng lại!}
