{100}{}{Bạn thấy một thầy tu.}
{101}{}{Bạn thấy một nữ tu thần thánh.}
{102}{}{Bạn thấy một thầy tu bình thường của Tu viện.}
{103}{}{Bạn thấy một nữ tu bình thường của Tu viện.}
{200}{}{Xin chào, người lữ khách.}
{201}{}{Bình an nhé.}
{202}{}{Chúng tôi là những người giữ gìn kiến thức.}
{203}{}{Chào.}
{204}{}{Thời tiết đẹp đấy.}
{205}{}{Hi vọng bạn thấy thoải mái khi ở đây.}
{500}{}{Dừng lại!}
