{100}{}{Bạn thấy một người mặc đồ quân đội.}
{101}{}{Bạn thấy một người mặc đồ quân đội.}
{102}{}{Bạn thấy một người mặc đồ quân đội nhưng trông có vẻ giống kĩ sư hơn là lính.}
{103}{}{Này, ổn chứ?}
{104}{}{"Hiểu rõ, đã bắt được tín hiệu" -- xin lỗi, nhưng tôi đang dở việc bây giờ.}
{105}{}{Giờ tôi không nói chuyện được.}
{106}{}{Cứ xem tự nhiên, nhưng đừng có chạm vào.}
{107}{}{Cậu bị điên à mà đi lại không mặc quân phục? Mặc đồ vào!}
{108}{}{Trung sĩ mà bắt được cậu không mặc quân phục thì ông ấy sạc cho teo chim.}
{109}{}{Sao cậu lại không mặc quân phục?}
{110}{}{Holy shit! We're being invaded! Alert!}
{111}{}{Intruders! Call the guard!}
{112}{}{Guard! Intruders in air traffic control!}
{113}{}{What's up? Are we under attack?}
{114}{}{Why the alert? What's happening?}
{115}{}{What the hell's going on?}
{200}{}{What are you doing? You have no reason to touch that.}
{201}{}{Touch that again and you die.}
