{100}{}{Bạn thấy ai đó mặc power armor. }
{101}{}{Bạn thấy Chỉ huy căn cứ Navarro.}
{102}{}{Bạn thấy một người mặc power armor có thiết kế khác lạ. Có miếng phù hiệu trên tấm giáp ngực mà bạn không nhận ra.}
{103}{}{Mấy người các ngươi là lũ quái nào thế... Báo động! Có kẻ đột nhập trong căn cứ!}
{104}{}{Ta không có thời gian tán nhảm với lính quèn. Giải tán.}
{105}{}{Đến lúc chết rồi.}
{106}{}{Okay.}
{107}{}{Ta đã bảo là ta không có thời gian rồi. Rời văn phòng và đừng có quay lại đây trừ khi ta có lệnh triệu tập. Giải tán!}
{108}{}{Không tuân lệnh trực tiếp của sĩ quan cấp trên là tội phản cấp. Ta không có thời gian lôi ra tòa án binh nên ta sẽ tự mình xử lí. Lính gác đâu! Tiêu diệt kẻ đần độn này!}
{109}{}{Okay.}
{110}{}{Chết đi!}
{111}{}{Fob ở trong tủ khóa đăng kia. Khi nào an toàn thì báo sĩ quan trực liên hệ với ta. Giải tán!}
{112}{}{Vâng, thưa chỉ huy!}
{113}{}{Nói nhanh lên, đồ linh, ta không có cả ngày để chờ đâu.}
{114}{}{Vâng, thưa chỉ huy!}
{115}{}{Đừng có động vào cái tủ khóa, không thì ta sẽ ra tay thật đấy.}
{116}{}{Vâng, thưa chỉ huy!}
{117}{}{Căn cứ đang báo động và ta không nhận ra ngươi. Này lính, trình giấy tờ ra.}
{118}{}{Giấy tờ nào?}
{119}{}{Mày bắn tao!}
{120}{}{Hình như tôi không mang theo người...}
{121}{}{Giấy tờ? Tôi có giấy tờ ở đây này!}
{122}{}{Trả lời sai rồi, đồ sâu bọ. Lúc nào mày cũng phải mang giấy tờ theo. Mày phải biết điều đó!}
{123}{}{Đmm.}
{124}{}{Đừng có động vào cái tủ khóa, không thì ta sẽ ra tay thật đấy.}
{125}{}{Đến lúc chết rồi.}
{200}{}{Được rồi, làm cho xong nào -- ta không thích lũ đột biến làm bẩn văn phòng và ta có nhiều việc phải làm. 
Có phải ngươi được nhà Salvatore thuê? }
{201}{}{Không phải việc của ông, đồ chó chết.}
{202}{}{Tôi không làm cho ai cả.}
{203}{}{Thế nếu phải thì sao?}
{204}{}{Đúng vậy, tôi làm cho nhà Salvatore.}
{205}{}{Trước khi trả lời câu hỏi, tôi có mấy câu cần hỏi.}
{210}{}{Ta không có thời gian cho trò vớ vẩn này. Lính gác đâu! Tiêu diệt tên đột biến này!}
{220}{}{Vậy ý ngươi là ngươi chỉ là một con chuột hoang mạc đi lạc vào một trong các máy bay của bọn ta?}
{221}{}{Ờ, đúng, gần như vậy... ngoại trừ việc tôi không phải chuột.}
{222}{}{Đúng vậy.}
{223}{}{Không, tôi đang muốn nói là tất cả chuyện này chỉ là hiểu lầm. Tôi không biết các ông là ai, và tôi không 
quan tâm. Vậy nên nếu ông không phiền thì tôi sẽ đi đây.}
{230}{}{Tốt, nếu ngươi hành động một mình thì ta không cần phải phí phạm thêm một giây nào nữa! Lính gác đâu! Tiêu diệt tên đột biến này!}
{240}{}{Ngươi sẽ không sống mà rời khỏi đây được đâu, người đột biến. Ta không thể mạo hiểm để ngươi phô vị trí
căn cứ này cho đám bạn ngoài hoang mạc được, đúng chứ? Lính gác đâu! Tiêu diệt tên đột biến này!}
{250}{}{Hãy nói những gì ta muốn biết và ta sẽ đảm bảo ngươi sẽ được chết nhanh chóng... và đau ít hơn. 
Có phải Salvatore chỉ cho ngươi đến đây?}
{251}{}{Ờ... không? Chờ đã, đúng. Chắc vậy.}
{252}{}{Không. Tôi tự nghĩ ra trò chơi trốn tìm trong cái máy bay của ông. Thiên tài chứ hả? Tôi biết.}
{253}{}{Đúng vậy, ông ta nghĩ có thể tăng cường cuộc trao đổi bằng cách gửi tôi đến đây. Món hời đấy chứ, hả?}
{254}{}{Trước khi trả lời câu hỏi, tôi có mấy câu cần hỏi.}
{260}{}{Ta không có thời gian cho trò vớ vẩn này. Lính gác đâu! Tiêu diệt tên đột biến này!}
{270}{}{Cách pha trò của mày đấy hả, đồ đột biến? Ta nghĩ là mày trông sẽ thú vị hơn nhiều khi thành xác chết đấy. Lính gác!
Tiêu diệt tên đột biến này!}
{280}{}{Ồ, ông ta làm thế à? [Hắn ta tặc lưỡi]. Chết tiệt, sao lại không chứ? Đằng nào ngươi chả chết. Ngươi muốn biết gì nào, người đột biến?}
{281}{}{Sao ông cứ gọi tôi là người đột biến?}
{282}{}{Các ông là lũ quái nào thế?}
{283}{}{Tôi đang ở đâu? }
{284}{}{Làm sao để tôi nhận được bộ giáp tuyệt cú mèo đó?}
{285}{}{Tôi nghe đủ rồi.}
{290}{}{Bởi vì ĐÓ là ngươi. Đúng là các ngươi trông cũng giống người, nhưng đừng có nghĩ vậy. Ngươi vẫn là người đột biến, 
ngươi và tất cả những kẻ khác ở đại lục. Tất cả đều bị nhiễm bẩn. Hỏi tiếp đi?}
{300}{}{Bọn ta là Enclave -- đơn vị cuối cùng của loài người thật sự trên cái hành tinh chết tiệt này. Chúng ta là những người
duy nhất còn lưu giữ vinh dự của lá cờ đỏ, trắng và xanh. Đúng vậy, chúng ta là những người yêu nước thật sự. Chúng ta
ăn thịt đại bàng đầu sói cũng như vứt bỏ cờ sao và kẻ sọc. Chúng ta là tất cả những gì còn lại của Hiệp chủng quốc Hoa Kì
vĩ đại. Nhưng chỉ vậy là đủ rồi. Ồ, đúng rồi, bọn ta đủ lực để thay đổi mọi thứ về đúng trật tự. Ngươi có thể tin vào điều đó,
tên đột biến ạ. Hỏi tiếp đi?}
{310}{}{Nơi đây là Navarro, căn cứ bí mật tại đại lục của chúng ta. Nơi này nằm ngay tại bờ biển của California với
biển Thái Bình Dương. Hỏi tiếp đi?}
{320}{}{Bằng cách lấy từ xác của ta. Cứ thử làm thế xem, đồ đột biến. Hỏi tiếp đi?}
{330}{}{Tốt, vì ta thấy mệt vl khi phải phí công mở mồm trả lời một tên đột biến rồi. Thực tế là chuyện này hoàn toàn 
phí phạm thời gian, vì ta đéo quan tâm xem ngươi cần nói gì. Lính gác đâu! Tiêu diệt tên đột biến này!}
