{100}{}{Bạn mở cửa tủ và tìm thấy hàng đống tài liệu cùng giấy tờ.}
{101}{}{Tìm kiếm trong tủ.}
{102}{}{Rời khỏi.}
{103}{}{Trong lúc tìm kiếm qua các bản lưu trong tủ, bạn để ý thấy một chiếc vali da mỏng được cất cẩn thận tít phía đằng trong.}
{104}{}{Kéo vali ra.}
{105}{}{Bỏ qua và tiếp tục lục lọi.}
{106}{}{30 phút trôi qua và bạn không tìm thấy gì quan trọng. Tất cả những gì bạn tìm được là Chad đã ghi lại từng
khoảng khắc trong đời hắn. Đúng là một gã chán đời. Đúng lúc bạn sắp đóng ngăn tủ, bạn nghe có tiếng ho ngoài
cửa trước và tay nắm đang xoay...}
{107}{}{Kéo vali ra.}
