{100}{}{Bạn thấy một chiếc máy tính vẫn hoạt động.}
{101}{}{Bạn thấy bảng máy tính kiểm soát không lưu.}
{102}{}{Chào mừng đến với kiểm soát không lưu. Bảng máy tính này điều khiển việc bố trí vệ tinh cho Máy bay
trực thăng di chuyển. Vui lòng nhập lệnh.}
{103}{}{Đăng xuất.}
{104}{}{Xếp vệ tinh để nhận tọa độ của Enclave.}
{105}{}{Đang căn chỉnh lại vệ tinh. Vui lòng chờ một lúc...}
{106}{}{[THÊM]}
{107}{}{Căn chỉnh lại thành công. Giàn neo đậu đã sẵn sàng đón tiếp máy bay.}
{108}{}{Đăng xuất.}
