{100}{}{Bạn thấy một chiếc máy bay lớn.}
{101}{}{Bạn thấy một chiếc Máy bay trực thăng.}
{200}{}{[Bạn trèo lên máy bay và truy cập vào bảng máy lái]. Chào mừng đến với PoseidoNet. Bảng máy tính này được giới hạn cho việc truyền tin giữa đội Trực thăng Enclave và giàn neo đậu. Lệnh?}
{201}{}{Trạng thái.}
{202}{}{Đăng xuất.}
{203}{}{Máy bay chỉ có đủ nguyên liệu để bay một vòng từ tiền đồn Navarro đến giàn neo rồi quay lại. Tất cả các bước
đều được tự động hoàn toàn và thành viên đội bay không cần can thiệp. Trạng thái xăng hiện tại: Đầy bình.}
{204}{}{Bay đến Giàn khoan dầu.}
{205}{}{Đăng xuất.}
{206}{}{Lỗi. Thẻ chìa hạt nhân vàng chưa được nhét vào. Tất cả phi công đều được cấp thẻ này khi nhận lệnh cất cánh.
Không thể thực hiện chuyến bay tự động nếu thiếu thẻ cất cánh.}
{207}{}{Nhét thẻ vào.}
{208}{}{Cứt thật. Có vẻ như mình phải đi tìm thẻ này.}
{209}{}{Xác nhận thẻ. Máy bay đã được kích hoạt.}
{210}{}{Chạy trình chẩn đoán trước khi bay.}
{211}{}{Đăng xuất.}
{212}{}{Bắt đầu chẩn đoán hệ thống... hoàn thành 35%... hoàn thành 75%... hoàn thành 100%. Toàn bộ hệ thống đều đang hoạt động. Đang kiểm tra phản hồi từ giàn neo...}
{213}{}{[THÊM]}
{214}{}{Không nhận được tín hiệu trả lời từ giàn neo. Lí do: Vệ tinh chưa được căn chỉnh để đậu tự động trên Dàn khoan dầu. Vui lòng đảm bảo rằng giàn neo biết về máy bay sắp đến.}
{215}{}{Hừm... Có vẻ như mình phải tìm cách căn chỉnh vệ tinh.}
{216}{}{Urg?}
{220}{}{Máy bay hiện đã kích hoạt. Lệnh?}
{221}{}{Chạy trình chẩn đoán trước khi bay.}
{222}{}{Đăng xuất.}
{230}{}{Đã nhận tín hiệu kiểm tra. Đang nhận tọa độ điểm hạ cánh... hoàn tất. Máy bay đã sẵn sàng cất cánh.}
{231}{}{Đi.}
{232}{}{Đăng xuất.}
{240}{}{Máy bay đã được khóa tọa độ. Thời gian bay xấp xỉ 6 tiếng. Hãy tận hưởng chuyến bay.}
{241}{}{Chính là đây -- thời điểm của sự thật. Bộ tộc đang gặp rắc rối và mọi chuyện đều phụ thuộc vào ta. Chân mỏi nhừ, toàn thân
ê ẩm, chẳng nhớ lần cuối được ăn một bữa ra hồn lúc nào. Đây là khoảng khắc chúng ta tồn tại. Không còn đường lùi.
Đã đến lúc cho thế giới thấy }
{242}{}{ chúng ta là ai. Hãy đến nào, Enclave!}
{243}{}{Hehe... Bay đi chim, bay! }
{244}{}{ ngày cứu thế rồi.}
{300}{}{[Bạn trèo lên máy bay và truy cập vào bảng máy lái]. Chào mừng đến với PoseidoNet. Bảng máy tính này được giới hạn cho việc truyền tin giữa đội Trực thăng Enclave và giàn neo đậu. Lệnh?}
{301}{}{Trạng thái.}
{302}{}{Đăng xuất.}
{303}{}{Máy bay chỉ có đủ nguyên liệu để bay một vòng từ tiền đồn Navarro đến giàn neo rồi quay lại. Tất cả các bước
đều được tự động hoàn toàn và thành viên đội bay không cần can thiệp. Trạng thái xăng hiện tại: Cạn kiệt.}
{304}{}{Đăng xuất.}
