{100}{}{Bạn thấy một người ở nhờ.}
{101}{}{Bạn thấy một người đàn ông ngập trong bụi đất và rác bẩn.}
{102}{}{Bạn thấy một phụ nữ ngập trong bụi đất và rác bẩn.}
{103}{}{Muốn gì?}
{104}{}{Tôi muốn ông và lũ bạn ra khỏi tòa nhà này. Tôi biết là Bà Má định biến nơi này thành một trại trẻ mồ côi và giúp
lũ trẻ vô gia cư không phải bám đường nữa. Và bà ấy không thể làm vậy nếu các người cứ chầu ở đây.}
{105}{}{[Hắn ta cười khẩy một cách chịu rồi liếc nhìn đám đồng bọn sống nhờ tìm kiếm sự trợ giúp]. Bà Má phải biết chứ. Bọn ta sẽ
không đi đâu cho đến khi bà ta nôn tiền ra. Vì vậy trừ phi ngươi mang một triệu xu đến đây, không thì biến.}
{106}{}{Xem này, Bà Má đào đâu ra khoản tiền đấy, mà nếu có thì bà ấy cũng không bao giờ đưa cho mấy người đâu, quên đi. Sao
không tốt tính lên một chút và đi chầu chỗ khác ấy? Lũ trẻ vô gia cư cần nơi này hơn bất kì ai trong số các ông.}
{107}{}{Mày là ai mà lên mặt dạy rằng ai xứng với cái gì? Bọn ta *thích* nơi này. Bọn ta sẽ không đi đâu cả.}
{108}{}{Nghe này, các người có hai sự lựa chọn: Tự đứng lên bằng hai chân và bước ra khỏi đây, hoặc *ta* có thể giúp -- bằng cách
kéo các ông ra, từng cái xác một.}
{109}{}{(Hắn ta nhìn lũ sống nhờ đồng bọn, rồi nhìn lại bạn và lắc đầu]. Mày không dọa được bọn ta đâu. Không ai đuổi được
bọn ta cả. Bọn ta sẽ chiến đấu vì lãnh thổ của mình.}
{110}{}{[Hắn ta nhìn lũ sống nhờ đồng bọn, rồi nhìn lại bạn và gật đầu]. OK, ngươi nói cũng có lí. Bọn ta cũng đâu có ghét trẻ con đâu,
mẹ nó chứ, phần lớn người ở đây đều từng là trẻ không nhà. Bọn ta chỉ đang cố kiếm chút tiền thôi, hiểu chứ? Công việc duy nhất
ở đây là đi bán cần hoặc đấm nhau, và bọn ta không muốn làm vậy [Hắn ta thở dài]. Bọn ta sẽ đi, nhưng ngươi thử nói xem bọn ta
phải đi đâu? Đây là nhà của bọn ta.}
{111}{}{Ta không biết. Không phải vấn đề của ta.}
{112}{}{Có thể ta sẽ thấy hối hận vì điều này, nhưng nếu các người thực sự muốn tìm việc thì chắc là Bà Má có thể sẽ cần người giúp sửa sang lại chỗ này. Bà ấy
là một phụ nữ tốt bụng, nên nếu các người xin lỗi thì bà ấy sẽ cho các người cơ hội để chứng tỏ rằng mình không chỉ là một lũ kền kền lười biếng. Ta sẽ
nói chuyện với bà ấy. Nhưng nếu các người giở trò thì ta sẽ đi săn từng đứa một và bắt các người trả giá.}
{113}{}{Mẹ nó chứ, tao đổi ý rồi. Bọn tao không đi đâu. Bọn tao sẽ ở đây và chiến đấu.}
{114}{}{[Hắn ta nhìn lũ đồng bọn sống nhờ và suy nghĩ về lời của bạn]. Biết gì không? Nghe có vẻ ổn đấy. Thật ra mà nói thì như vậy sẽ rất tốt, nếu ngươi thật sự
nghĩ rằng Bà Má sẽ đồng ý. Trong lúc ngươi đi nói chuyện với bà ta, bọn ta sẽ bắt đầu dọn dẹp nơi này. Ồ, cám ơn đã không dùng bạo lực.}
{115}{}{Quên đi.}
{116}{}{Bà ấy sẽ không trả tiền cho các người đâu. Nhưng ta đây sẽ cho các ngươi một thỏa thuận mới: ngươi và lũ bạn cuốn xéo khỏi đây ngay thì vẫn còn được sống.}
{117}{}{À, được rồi, để ta thử. Tạm biệt.}
{120}{}{Ý hay đấy. Bọn ta sẽ chuẩn bị sẵn sàng mọi thứ.}
{200}{}{Hở?}
{201}{}{Đây là lãnh địa của bọn ta.}
{202}{}{Ngươi cũng đến đây chầu à?}
{203}{}{Có gì đớp không?}
{300}{}{Bạn thấy một người đàn ông trong bộ đồ lao động.}
{301}{}{Bạn thấy một phụ nữ trong bộ đồ lao động.}
{310}{}{Ầy, cám ơn đã giúp chúng tôi việc này. Chúng tôi sẽ làm việc chăm chỉ.}
{311}{}{Phải vậy chứ. Nhớ trông chừng tránh để lũ trẻ gặp rắc rối nữa.}
{312}{}{Bọn tôi sẽ cố hết sức.}
{313}{}{Chào.}
{350}{}{Đâu chả được. The Den rộng thế này cơ mà, ta chắc là mấy người nằm chỗ nào cũng vừa. Thôi nào, các người thực sự muốn lũ trẻ phải bám đường sao?}
{351}{}{Chẹp, ngươi nói đúng, đám trẻ không đáng bị như vậy. Được rồi, bọn ta sẽ dọn đồ và đi chỗ khác. Nơi này đằng nào cũng dột nát rồi.}
{352}{}{Cám ơn. Bọn trẻ sẽ biết ơn lắm đấy. Bảo trọng.}
{353}{}{Này, đâu phải vấn đề của bọn ta. Nếu Bà Má nghĩ rằng bọn trẻ không cần phải sống trên vỉa hè thì bà ta nên thôi cái tính ki bo đi và chìa tiền ra. Ừ, ta đổi ý rồi.
Bọn ta sẽ ở đây cho đến lúc bà ta trả tiền. Bây giờ tán chuyện xong rồi, nếu ngươi biết điều thì tốt nhất là biến đi.}
{360}{}{Được rồi. Không cần phải xửng cồ lên thế. Ta sẽ để mặc các người.}
{361}{}{Đã đến lúc dọn dẹp chỗ này rồi. (Tấn công)}
{400}{}{Cám ơn nhé!}
{401}{}{Bọn tôi sẽ làm việc chăm chỉ.}
{402}{}{Cám ơn đã không dùng bạo lực.}
{403}{}{Bọn tôi sẽ không làm bạn thất vọng đâu.}
{500}{}{Bọn ta sẽ dọn đồ và biến khỏi đây ngay.}
{600}{}{Bạn đã tống cổ hết lũ sống nhờ.}
