{100}{}{Bạn thấy một kẻ buôn thuốc phiện.}
{101}{}{Bạn thấy một kẻ buôn thuốc phiện.}
{102}{}{Nếu anh giai đang tìm mối thì tôi có đồ đây.}
{103}{}{Được, cho xem nào.}
{104}{}{Có lẽ để sau đi.}
{105}{}{Tìm thấy đồ anh cần chưa?}
{106}{}{Cám ơn. Tạm biệt.}
{200}{}{Bạn thấy một kẻ du côn.}
{201}{}{Bạn thấy một kẻ du côn.}
{202}{}{Tôi ở đây để bảo kê. Nói với tay buôn hàng nếu cậu muốn mua.}
