{100}{}{Bạn thấy một cư dân của khu The Den.}
{101}{}{Bạn thấy Fred.}
{102}{}{Bạn thấy Fred ăn mặc rất bảnh.}
{150}{}{Ông ta có vẻ đang mải nghĩ về việc gì đó.}
{151}{}{Ông ta có vẻ rất hạnh phúc với bộ cánh xịn mới.}
{200}{}{Một ngày nào đó nhất định sẽ trúng to.}
{201}{}{Ồ, để tôi yên nào, đang bận.}
{202}{}{Kế hoạch tổng thể...}
{203}{}{Phải tính ra được...}
{204}{}{Sao lần đéo nào cũng thua thế nhỉ?}
{205}{}{Mấy cái bàn này giở trò chắc rồi.}
{206}{}{... một ngày nào đó tôi sẽ có nhà riêng.}
{207}{}{Đi kiếm quần áo hịn nào.}
{220}{}{Này, muộn lắm rồi. Để tôi yên.}
{221}{}{Không, tôi không cần bạn bè gì hết.}
{222}{}{Có biết mấy giờ rồi không?}
{223}{}{Tôi chẳng có gì cả.}
{224}{}{Sáng quay lại. Tôi mệt rồi.}
{225}{}{Thôi đi.}
{226}{}{Đéo có ai ở nhà đâu.}
{227}{}{Đéo nói. Tôi sắp ngủ rồi.}
{228}{}{Này, quý cô! Muộn rồi đấy, để tôi yên.}
{240}{}{Hết tiền rồi! Để tôi yên.}
{241}{}{Chẳng có việc gì cả. Làm gì bây giờ?}
{242}{}{Đừng có nói là tôi còn nợ ai nữa! Ahh!}
{243}{}{Thế này thì trúng quả to thế nào giờ.}
{244}{}{Nghèo vl.}
{245}{}{Ôi má ơi, cần tiền mặt.}
{246}{}{Chả bao giờ mua được quần áo mới nữa.}
{247}{}{Cần phải lên một kế hoạch mới...}
{260}{}{Cám ơn đã trả giúp tôi!}
{261}{}{Cậu đúng là cứu tinh đấy.}
{262}{}{Tôi sẽ sớm có tiền trả thôi.}
{263}{}{Chả mấy nữa mà tôi sẽ trúng to!}
{264}{}{Cậu sẽ là người đầu tiên biết tin tôi trúng lớn đấy.}
{275}{}{Kế hoạch tổng thể nói chung là ổn!}
{276}{}{Cám ơn đã cho vay! Tiền vào đây thì chắc như đinh đóng cột ấy!}
{277}{}{Mấy cái bàn này khó nhai thật, nhưng đừng lo.}
{278}{}{Có ngày tôi sẽ trúng lớn, nhờ cậu đấy.}
{279}{}{Thời sắp đến rồi! Tôi có thể sờ được rồi đấy.}
{280}{}{Hứa sẽ trả mà, thề!}
{281}{}{Tôi sẽ sớm thắng quả thật to. Mùi tiền xóc lên tận óc rồi đây này.}
{295}{}{Hả? Quen biết à? Muốn gì?}
{296}{}{Sao cứ làm phiền tôi thế? Quen biết đéo gì. Đi chỗ khác chơi đi.}
{297}{}{Tôi đến để thu tiền ông nợ người ta.}
{298}{}{Không có gì.}
{299}{}{Uk!}
{300}{}{Chào.}
{310}{}{NÀY! Cậu đây rồi! Tìm mãi đấy! Xem bộ cánh mới này đi!}
{311}{}{Cám ơn lần nữa.}
{312}{}{Nhìn đẹp đấy.}
{313}{}{Trông như mứt ấy!}
{314}{}{Yuk!}
{315}{}{Hực.}
{320}{}{Cám ơn, cám ơn nhiều lắm! Nhờ cậu mà tôi có đến bốn bộ như này!}
{321}{}{Vậy ông trúng lớn thật à?}
{322}{}{Thế tiền của tôi đâu?}
{330}{}{Cậu không thích bộ đồ mới của tôi à? Mà biết gì không, chắc vậy thật. Chính tôi cũng không thích. Đến lúc mua bộ khác rồi, bố giàu mà!}
{331}{}{Vậy ông trúng lớn thật à?}
{332}{}{Thế tiền của tôi đâu?}
{333}{}{Hừm.}
{340}{}{Sắp có rồi! Không để tôi tận hưởng chiến thắng à? Tôi phải cố mãi mới được đấy.}
{341}{}{Biết rồi, xin lỗi.}
{342}{}{Mẹ nó. Tiền tôi trả nợ hộ ông đâu rồi?}
{343}{}{Đéo quan tâm. Tiền của tôi đâu?}
{350}{}{Rồi. Đây. [Fred đưa bạn $500] Thêm một chút gọi là cảm ơn đã tin tưởng. Gặp lại sau nha. Cám ơn lần nữa.}
{351}{}{Cám ơn!}
{352}{}{Sao cũng được.}
{360}{}{Cám ơn nhiều vì đã trả giúp tôi. Việc đó thật sự có ý nghĩa với tôi đấy, được một người xa lạ tin tưởng. Để tôi đưa thứ này.}
{361}{}{Okay.}
{362}{}{Không cần đâu.}
{363}{}{Ừ.}
{370}{}{Tôi mắc nợ mà. Cậu giúp tôi khi tôi đang vận đen. Để thay lời cảm ơn, tôi có thứ này cho cậu.}
{371}{}{Okay.}
{372}{}{Không cần đâu.}
{373}{}{Ừ.}
{380}{}{Đây. [Fred đưa bạn $1000]. Hi vọng chỗ tiền này sẽ có ích. Tôi chắc là cậu sẽ tìm được chỗ để tiêu đấy.}
{381}{}{Thứ lỗi, tôi không thể nhận được.}
{382}{}{Cám ơn.}
{383}{}{Không có gì, nhưng tôi sẽ nhận.}
{384}{}{Yum.}
{390}{}{Đây. [Fred đưa bạn $2000, 5 Pin Hợp Hạch, 5 Pin Năng Lượng và một quả lựu đạn Plasma]. Tôi hi vọng mấy thứ này sẽ có ích, dù chỉ một chút thôi.}
{391}{}{Thứ lỗi, tôi không thể nhận được.}
{392}{}{Cám ơn nhiều lắm.}
{393}{}{Không có gì, nhưng tôi sẽ nhận.}
{394}{}{Yum.}
{400}{}{Sao? Ồ, okay nếu cậu nhất định thế. Cám ơn nhiều lắm. Bảo trọng đấy.}
{401}{}{Chào.}
{410}{}{Hả? Mày bú phải cỏ dại à? Trông thì cứ tưởng không nghiện ngập gì. Tránh xa tao ra.}
{411}{}{Beat it!}
{412}{}{Hực.}
{420}{}{What are you talking about? I don't owe anyone anything. Who the hell are you talking about?}
{421}{}{Yea, you said that last time. I don't know what you're talking about? Who's this imaginary person again?}
{422}{}{Becky says you owe her $500}
{423}{}{Becky sent me.}
{424}{}{Rebecca says she lent you $200.}
{430}{}{Oh yeah, right. Rebecca lent me $200... Oh, wait. Maybe- ummm...}
{431}{}{She's told me to break your neck if you don't pay.}
{432}{}{Hand it over.}
{440}{}{Yeah, right. I've never seen that much money before in my life.}
{441}{}{Hmmm.}
{442}{}{Oh.}
{450}{}{Right! That'll be the day. Becky wouldn't hurt a fly. She sure is pretty though.}
{451}{}{Well, you're wrong, asshole.}
{452}{}{Maybe it was someone else.}
{460}{}{Damn. I think you're right, but - I'm almost broke. I can't afford that kind of money! I've got to eat you know.}
{461}{}{Sorry.}
{462}{}{Tough luck.}
{470}{}{Oh, damn it. I can barely afford $100. Could you spot me half? I promise I'll pay you back!}
{471}{}{No sorry.}
{472}{}{Come on. Pay up the full amount!}
{473}{}{Okay, fine.}
{480}{}{Damn it. You're going to ruin me! Well, okay, here. Now I'm completely broke.}
{481}{}{Oh, fine. I'll cover you.}
{482}{}{Thanks. Manage your money better next time.}
{483}{}{Thank you for your business.}
{490}{}{I told you! I can't! I'll starve if I do. Oh, come on, can't you help me out?}
{491}{}{All right. I'll cover half of it.}
{492}{}{No sorry. I don't have the cash either.}
{493}{}{I'll be back.}
{500}{}{What? Really? Wow! Thanks a lot, man! Here's a $100. I'll get the other $100 to you as soon as possible!}
{501}{}{What? Really? Wow! Thanks a lot, lady! Here's a $100. I'll get the other $100 to you as soon as possible!}
{502}{}{No problem.}
{503}{}{You better pay me back.}
{510}{}{Oh, don't worry. I will! You have my word and I won't forget about it this time!}
{511}{}{Okay.}
{520}{}{Say, you know what? That hundred's really going to uh... delay things. Do you think I could borrow a little bit back?}
{521}{}{How much?}
{522}{}{Không đời nào.}
{530}{}{Wait! I know. Tell you what, I'll give you $100 and you spot me for the other $100 I owe Becky. I'll pay you back real soon.}
{531}{}{Okay fine.}
{532}{}{No deal.}
{540}{}{Just $50. Please! It's all part of the master plan!}
{541}{}{Được rồi.}
{542}{}{But that'll only leave me with $50 to pay your $200 loan.}
{543}{}{Không.}
{550}{}{Wha- uh... Damn! You won't regret this! I'm good for it!}
{551}{}{No problem.}
{560}{}{Uh, yeah. I see your math skills- I mean, please! It's not much to you I'm sure, but it's a hell of a lot for me.}
{561}{}{Okay.}
{562}{}{Không.}
{570}{}{Yeah, sure she did. Everyone knows she hates that name. You're not fooling me!}
{571}{}{I don't owe her anything.}
{572}{}{She said you were forgetful.}
{573}{}{Look, I don't have time for this. Pay up damn it!}
{574}{}{Rebecca said she lent it to you a while ago.}
{580}{}{I am not! I... wait. There was that one time. Didn't I pay her back? I thought I did...}
{581}{}{No, you didn't. That's why she sent me.}
{582}{}{Just pay up so I can get out of here.}
{590}{}{I don't remember... but Becky sure has helped me and my friends out in the past.}
{591}{}{Hand over the $200.}
{592}{}{Just give me the money.}
{600}{}{Để tôi yên.}
{601}{}{Whatever.}
{602}{}{Okay.}
{610}{}{Uh. Hi again. So, uh, I suppose you want the money. Do you think you could cover me for half?}
{611}{}{No, sorry.}
{612}{}{If she lent you $200, you'll pay it.}
{613}{}{Okay fine.}
