{100}{}{You see a door.}
{101}{}{You see an electronic door.}
{102}{}{You see an electronic door with an override, voice activated, lock.}
{200}{}{Confirm code:}
{201}{}{XY104FD}
{202}{}{BFN12}
{203}{}{Open}
{204}{}{Wheat}
{205}{}{Abre}
{206}{}{[KẾT THÚC]}
{300}{}{Incorrect door code. Locking door. Please contact the head of Public Relations for the override code.}
{301}{}{[KẾT THÚC]}
{400}{}{Confirm override code.}
{401}{}{[KẾT THÚC]}
{402}{}{This door is electronically locked.}
{403}{}{Unlocking door. Thank you and have a pleasant day.}
{404}{}{[KẾT THÚC]}
{500}{}{There is no lock to pick.}
