{100}{}{Bạn mở cửa tủ và tìm thấy hàng đống tài liệu cùng giấy tờ.}
{101}{}{Tìm kiếm trong tủ.}
{102}{}{Rời khỏi.}
{103}{}{As you search through the records in the dresser, you notice a thin leather briefcase stuffed carefully deep in the back.}
{104}{}{Kéo vali ra.}
{105}{}{Bỏ qua và tiếp tục lục lọi.}
{106}{}{30 phút trôi qua và bạn không tìm thấy gì quan trọng. Tất cả những gì bạn tìm được là Chad đã ghi lại từng
khoảng khắc trong đời hắn. Đúng là một gã chán đời. Đúng lúc bạn sắp đóng ngăn tủ, bạn nghe có tiếng ho ngoài
cửa trước và tay nắm đang xoay...}
{107}{}{Kéo vali ra.}
{108}{}{Inside the briefcase you find papers documenting a whole year's worth of skimming money from
 caravans by Chad.}
{109}{}{Wow, it really looks like Chad was skimming money. Apparently he is preparing to skip town as well,
 better tell Marcus all this.}
{110}{}{30 minutes pass and you find nothing of importance. All that you have found out is that Chad has records
 documenting every moment of his life. He's a pretty boring guy actually.}
