{100}{}{}
{101}{}{}
{110}{}{Your feet really itch.}
{120}{}{You're developing a nasty bunion on each foot.}
{130}{}{Your shoes feel really tight; those bunions are really getting inflamed.}
{140}{}{That nasty bunion on each foot seems to have turned into an extra toe. But at least that
 persistent, burning itch has gone away.}
{141}{}{Oh my God, it's Bess!}
{150}{}{You gain }
{151}{}{ experience points for getting the GECK.}
{400}{}{You can't understand a thing from the text, but the illustrations are quite informative.}
{600}{}{Something doesn't feel quite right in your stomach.}
{601}{}{You feel an intense pressure in your stomach.}
{700}{}{You attach the torn pieces of paper together to yield a list of three passwords.}
{900}{}{Something doesn't feel quite right in your stomach.}
{901}{}{You feel an intense pressure in your stomach.}
