{100}{}{}
{101}{}{}
{110}{}{Nagyon viszket a lábfejed.}
{120}{}{Kis ocsmány bütykök nőnek a lábfejeidre.}
{130}{}{A cipőd nagyon szorít, a bütykök tényleg nőnek.}
{140}{}{Az ocsmány kis bütykökből új lábujjak lettek. De legalább az a tartós, égő viszketés elmúlt.}
{141}{}{Úristen, ez Bess!}
{150}{}{ }
{151}{}{ experience points for getting the GECK.}
{400}{}{You can't understand a thing from the text, but the illustrations are quite informative.}
{600}{}{Something doesn't feel quite right in your stomach.}
{601}{}{You feel an intense pressure in your stomach.}
{700}{}{You attach the torn pieces of paper together to yield a list of three passwords.}
{900}{}{Something doesn't feel quite right in your stomach.}
{901}{}{You feel an intense pressure in your stomach.}
