{1}{}{Você se tornou viciado em álcool. A sede de álcool logo o consumirá. Você perdeu 1 de Agilidade e 1 de Carisma.}
{2}{}{Os impulsos estão piorando.}
{3}{}{Você tem uns tremores. Você tem um impulso intenso em beber algo com álcool.}
{4}{}{Você sente como se um grande fardo tivesse sido tirado de sua mente. Você não tem mais o vício em beber álcool. Você recuperou 1 de Agilidade e 1 de Carisma.}
