{1}{}{You have become addicted to alcohol. The thirst for alcohol will soon consume you. You lost 1 Agility and 1 Charisma}
{2}{}{Os impulsos estão piorando.}
{3}{}{Você tem uns tremores. Você tem um impulso intenso em beber algo com álcool.}
{4}{}{You feel as if a great burden has been lifted from your mind. No longer do you feel the need to drink alcohol. You regained 1 Agility and 1 Charisma}
