{100}{}{Widzisz handlarza Billa.}
{101}{}{Widzisz starszego mężczyznę, kupca.}
{200}{}{Witaj, podróżniku. Bill jestem. Co dla ciebie?}
{201}{}{Witam ponownie. Potrzebujesz jeszcze czegoś?}
{202}{}{Pohandlujmy.}
{203}{}{Słyszałem, że jesteś właściwą osobą żeby pogadać o karawanach.}
{204}{}{Nieważne. Cześć.}
{210}{}{Wygląda na to, że w Opactwie zgromadzono całkiem sporo starego sprzętu.
Nie znalazłeś tu może czegoś... wyjątkowego przez ten czas?}
{211}{}{Hah, więc zauważyłeś to, co? No tak, ludzie z Opactwa mają jakąś obsesję na punkcie wszystkiego sprzed wojny,
zwłaszcza jeśli chodzi o technologię. Zbudowali wokół tego jakąś pokręconą religię. Sam do końca tego nie 
ogarniam, ale to mili ludzie i dobrze płacą za każdy przedwojenny grat, który uda mi się zdobyć. Ale jeśli 
chodzi o coś naprawdę wyjątkowego... hmm... [Spogląda na Marcusa.] Zabawne, że o to pytasz. Może mam coś, 
co zainteresuje twojego kolegę.}
{212}{}{Hah, więc zauważyłeś to, co? No tak, ludzie z Opactwa mają jakąś obsesję na punkcie wszystkiego sprzed wojny,
zwłaszcza jeśli chodzi o technologię. Zbudowali wokół tego jakąś pokręconą religię. Sam do końca tego nie 
ogarniam, ale to mili ludzie i dobrze płacą za każdy przedwojenny grat, który uda mi się zdobyć. Ale jeśli 
chodzi o coś naprawdę wyjątkowego... hmm... [Patrzy na twoich towarzyszy.] Przykro mi, ale w tej chwili 
nie mam nic, co mogłoby ci się przydać.}
{213}{}{W takim razie zobaczmy co masz na stanie.}
{214}{}{W porządku. Pozwól, że zapytam cię o coś innego.}
{215}{}{Tak, na przykład?}
{216}{}{Widzisz, niedawno przez te okolice przejechała karawana, twierdzili, że przybyli z dalekiego południa.
Mieli podobno zostać zaatakowani przez te paskudne mutanty [zwraca się do Marcusa] bez urazy, wielkoludzie.
No i dużo się przechwalali, jak to nie powybijali tych mutków. Twierdzili, że było ich prawie tuzin, od razu pomyślałem,
że to bzdura. Jednak okazało się, że mieli na to jakiś dowód.}
{217}{}{Tak? A co takiego?}
{218}{}{Potężny pancerz mutanta, który udało im się zedrzeć z jednego z trupów. Oczywiście, moim zdaniem po prostu zdarli go 
z kości jakiegoś od dawna martwego mutka, na którego natknęli się na pustkowiach - ale kto to tam wie? Tak czy inaczej, 
nie byli zbyt chętni, by dalej targać to żelastwo, więc puścili mi to bezcen. Nie miałem pojęcia co z ty zrobić, 
ale pomyślałem, że jak promocja, to trzeba brać.}
{219}{}{Cóż, myślę, że przyda się Marcusowi. Ile?}
{220}{}{Interesujące. Jednak i bez tego Marcus jest wystarczająco wytrzymały. Nie sądzę, żebyśmy tego jeszcze potrzebowali.
Pozwól, że zapytam o coś innego.}
{221}{}{Pomyślmy, to cudo dałoby się przetopić na trzy albo cztery metalowe pancerze. Więc powiedzmy 3000$.}
{222}{}{Mogę sobie na tyle pozwolić.}
{223}{}{Myślę, że na razie to sobie daruję. Pozwól, że zapytam cię o coś innego.}
{224}{}{Czyli umowa stoi. Trzeba będzie nas obu żeby to ruszyć, pomogę ci to założyć na twojego kumpla.}
{225}{}{[Zrobione.]}
{226}{}{Hej, całkiem nieźle pasuje!}
{300}{}{Może i wiem co nieco. O czym chcesz usłyszeć?}
{301}{}{Jak często dostajesz towar?}
{302}{}{Szukają kogoś do karawan?}
{303}{}{W sumie, muszę już iść.}
{304}{}{Dostawy otrzymuję dwa razy w miesiącu. Właściwie chciałbym, żeby przyjeżdżały częściej, ale jesteśmy 
z dala od głównych szlaków handlowych, więc to wszystko, na co możemy liczyć.}
{305}{}{Nie jestem do końca pewien. Zazwyczaj ci, którzy się tu zatrzymują, są całkiem dobrze wyposażeni i nie mają ochoty 
zbyt długo tu zostawać. Ale jeśli chcesz się z kimś takim dogadać, to na twoim miejscu skierowałbym się do Redding 
albo nawet dalej - do RNK. Mają tam całkiem aktywne karawany i zawsze szukają dobrych pomocników.}
{306}{}{Interesujące. Jestem ciekaw jeszcze czegoś.}
{307}{}{Dzięki. Pohandlujmy.}
{308}{}{Cóż, dzięki za informację. Do zobaczenia.}
{400}{}{Masz wszystko czego potrzebowałeś?}
{401}{}{Właściwie, chciałbym jeszcze raz zerknąć na twoje towary, jeśli można.}
{402}{}{Tak, mam wszystko. Do zobaczenia.}
