{1}{}{You have become addicted to alcohol. The thirst for alcohol will soon consume you. You lost 1 Agility and 1 Charisma}
{2}{}{Ваша тяга к алкоголю становятся все хуже.}
{3}{}{Вас трясет по всему телу. Вам очень-очень нужно, что-то выпить алкогольное. Тяга невыносима.}
{4}{}{You feel as if a great burden has been lifted from your mind. No longer do you feel the need to drink alcohol. You regained 1 Agility and 1 Charisma}
