{100}{}{Vedi un paletto segnatombe. }
{101}{}{Sul paletto c'e' scritto: }
{102}{}{"Qui' giace Fratello Gregory. Un uomo che non conosceva limiti."}
{103}{}{Zia Patty. Ben tolto di mezzo, davvero.}
{104}{}{Qui giace Per Joner. Morì con un sasso di meno."}
{105}{}{Qui giace Padre Michael. Fondatore, Padre, Combattente.}
{106}{}{"Qui giace un Ateo vestito di tutto punto, ma senza un posto dove andare."}
{107}{}{"Qui giace Johnny Yeast. Scusate se non mi alzo."}
{108}{}{Mary Jane. Moglie e madre amorevole.}
{109}{}{"'Scacco matto!' fu il grido per il caro vecchio Jon, Sulla scacchiera della vita, Era solo un pedone.}
{110}{}{"Sir Giovanni Strano, qui giace un avvocato onesto, e questo e' invero Strano."}
{111}{}{"Le lacrime non possono restituirmela -- quindi piango."}
{112}{}{"Ogni giorno, in ogni modo, sto migliorando sempre di più."}
{250}{}{Non ci sono scritte su questo paletto.}
{251}{}{Il paletto segnatombe e' troppo incrinato e rotto per poter essere letto.}
{252}{}{Inciso su questo paletto c'e' il nome John Doe.}
{253}{}{Il nome e la data su questo paletto sono stati cancellati dalle intemperie.}
