{100}{}{Vedi Hank.}
{101}{}{Vedi un monaco viscido.}
{102}{}{Sta armeggiando con un alambicco.}
{200}{}{Ehi, amico. Hai un accendino con te?}
{201}{}{Sì. [Porgigli il tuo accendino.]}
{202}{}{Capisco. Grazie!}
{203}{}{Per curiosita', cosa stai facendo esattamente qui?}
{204}{}{Certo. Visto che mi hai portato un accendino, questo te lo offro io.}
{205}{}{[Bevilo.]}
{206}{}{Ho cambiato idea, non voglio dell'alcol. Arrivederci.}
{207}{}{(Ti senti caldo e rilassato dopo aver trangugiato il vino.)}
{208}{}{Dammene un altro, Hank.}
{209}{}{Me ne vado, arrivederci.}
{210}{}{(Improvvisamente ti senti uno schifo, poi la tua visione comincia ad annebiarsi. Cadi a terra...)}
{211}{}{[FATTO]}
{212}{}{No, mi dispiace.}
{213}{}{Ciao, di nuovo.}
{214}{}{Ciao e arrivederci.}
{215}{}{Questa non sara' gratis. Ti costera' $20.}
{216}{}{Certo. Ecco i soldi.}
{217}{}{No, ne ho avuto abbastanza. Forse la prossima volta.}
{218}{}{(Si intasca i soldi.) D’accordo allora, ecco da bere.}
{219}{}{Tornero' quando avro' piu' soldi.}
{220}{}{Hai trovato un accendino?}
{250}{}{Vorrei comprare un po' dell'alcol che produci qui.}
{251}{}{Sto solo guardando in giro. Stammi bene.}
{252}{}{Certo. $20 a bottiglia.}
{253}{}{[Tienilo.]}
{300}{}{Dove ho messo il mio accendino?}
{301}{}{I need a lighter.}
{302}{}{COULD SOMEONE BRING ME A LIGHTER!?}
{303}{}{Uh, hi there.}
{304}{}{Sorry, I can't chat with you now.}
{400}{}{Ooh, look at all those pretty stars!}
{500}{}{Hello. Need something?}
{501}{}{Hey, thanks again for the lighter. It's better than my old one.}
{600}{}{We brew our own alcohol here at the monastery. Some of the most powerful stuff you'll taste in the Wastes.}
{601}{}{Mind if I try some?}
{602}{}{Sounds interesting. I must be going.}
{700}{}{That's too bad. I lost mine recently and I can't seem to find it anywhere. If you ever get a hold of one,
 I'd be glad to take it off your hands.}
{701}{}{Sure. If I come across one I'll let you know. Bye.}
{702}{}{Sorry. I'm a bit of a collector and keep all that I find. Bye.}
{800}{}{Li-ter? I have fire maker. It burn me many times. (You hold up a lighter.)}
{810}{}{Yeah, that's what I need. Will you give it to me?}
{811}{}{Otay. I no likee it.}
{812}{}{I no give you.}
{820}{}{You no now burn self too. Bye!}
