{100}{}{Vedi Hank.}
{101}{}{Vedi un monaco viscido.}
{102}{}{Sta armeggiando con un alambicco.}
{200}{}{Ehi, amico. Hai un accendino con te?}
{201}{}{Sì. [Porgigli il tuo accendino.]}
{202}{}{Capisco. Grazie!}
{203}{}{Per curiosita', cosa stai facendo esattamente qui?}
{204}{}{Certo. Visto che mi hai portato un accendino, questo te lo offro io.}
{205}{}{[Bevilo.]}
{206}{}{Ho cambiato idea, non voglio dell'alcol. Arrivederci.}
{207}{}{(Ti senti caldo e rilassato dopo aver trangugiato il vino.)}
{208}{}{Dammene un altro, Hank.}
{209}{}{Me ne vado, arrivederci.}
{210}{}{(Improvvisamente ti senti uno schifo, poi la tua visione comincia ad annebiarsi. Cadi a terra...)}
{211}{}{[FATTO]}
{212}{}{No, mi dispiace.}
{213}{}{Ciao, di nuovo.}
{214}{}{Ciao e arrivederci.}
{215}{}{Questa non sara' gratis. Ti costera' $20.}
{216}{}{Certo. Ecco i soldi.}
{217}{}{No, ne ho avuto abbastanza. Forse la prossima volta.}
{218}{}{(Si intasca i soldi.) D’accordo allora, ecco da bere.}
{219}{}{Tornero' quando avro' piu' soldi.}
{220}{}{Hai trovato un accendino?}
{250}{}{Vorrei comprare un po' dell'alcol che produci qui.}
{251}{}{Sto solo guardando in giro. Stammi bene.}
{252}{}{Certo. $20 a bottiglia.}
{253}{}{[Tienilo.]}
{300}{}{Dove ho messo il mio accendino?}
{301}{}{Ho bisogno di un accendino.}
{302}{}{QUALCUNO PUO' PORTARMI UN ACCENDINO!?}
{303}{}{Uh, ciao.}
{304}{}{Mi dispiace, non posso parlare con te adesso.}
{400}{}{Ooh, guarda tutte quelle belle stelle!}
{500}{}{Ciao. Hai bisogno di qualcosa?}
{501}{}{Ehi, grazie ancora per l'accendino. E' meglio del mio vecchio.}
{600}{}{Qui al monastero produciamo il nostro alcol. E' roba tra le più forti che ti capiterà di assaggiare nelle Lande.}
{601}{}{Ti dispiace se ne assaggio un po'?}
{602}{}{Sembra interessante. Devo andare.}
{700}{}{Che sfortuna. Io l’ho perso di recente e non riesco a trovarlo da nessuna parte. Se mai dovessi metterne le mani su uno, sarei felice di toglierlo dalle tue.}
{701}{}{Certo. Se ne trovo uno te lo faccio sapere. Arrivederci.}
{702}{}{Scusa. Sono un po’ un collezionista e tengo tutto quello che trovo. Ciao.}
{800}{}{Li-ter? Io avere “fa?fuoco”. Brucia me molte volte. (Alzi un accendino.)}
{810}{}{Si', e' quello di cui ho bisogno. Me lo dai?}
{811}{}{Otay. A me non piaccee.}
{812}{}{Io no dare a te.}
{820}{}{Adesso anche tu no bruci te stesso. Ciao!}
