{100}{}{Vedi Jack, il medico dell'Abbazia.}
{101}{}{Ha una croce rossa sulla spalla.}
{200}{}{Se sei ferito, parla con me.}
{300}{}{Come posso aiutarti?}
{301}{}{Sono ferito. Puoi aiutarmi?}
{302}{}{[sbava]}
{303}{}{Allora, cosa fai qui all'Abbazia?}
{304}{}{Addio.}
{400}{}{E' fatto!}
{401}{}{Grazie.}
{402}{}{Smettila!}
{403}{}{[CONTINUA]}
{404}{}{[VIA]}
{405}{}{SMETTILA! SMETTILA! SMETTILA!}
{406}{}{[CONTINUA]}
{407}{}{[STOP]}
{408}{}{(All’improvviso, Jack comincia a sciogliersi.) MI STO SCI-OOO-GLIENDO, MI STO SCI-OOO-GLIENDO, OH CHE MONDO…}
{409}{}{Cosa dia...?!}
{500}{}{Ehi, non rubare le mie forniture mediche!}
{501}{}{Ottieni %d punti esperienza per aver fatto sciogliere Jack. Sei contento adesso, povero malato?}
{600}{}{Sono un dottore. Mi prendo cura della gente dell’Abbazia da… oh, saranno quindici anni ormai, credo.}
{601}{}{Capisco. Sono molti anni per studiare tutti i libri di medicina pre?bellici nella biblioteca dell’Abbazia. Devi essere davvero un ottimo dottore.}
{602}{}{Da dove hai preso tutto il tuo equipaggiamento medico?}
{603}{}{Interesting. I think I will be leaving now.}
{604}{}{[He frowns.] I fancy myself a fine doctor, but I can't credit the books for that since I'm not even allowed to... never mind, I won't get into that. My father was a doctor, and he passed his knowledge down to me.}
{605}{}{Ah, capisco.}
{700}{}{Some of these meds I received from my father. Most of the rest were already here at the Abbey.}
{701}{}{Interesting, bye.}
{702}{}{Do you think you could give me some of your meds? You seem to have plenty to spare.}
{703}{}{You want me to just *give* them to you? What makes you think you deserve them more than the people of the Abbey?}
{704}{}{Because I tend to get hurt... a lot.}
{705}{}{Because I'm on a holy quest to find a Garden Of Eden Creation Kit. You see, my entire village will perish if
 I don't find this device in time. Your people, on the other hand, seem to live a peaceful life without much need for so
 much healing equipment. I'm not asking for a lot, even the smallest amount you could give me would help me greatly.}
{706}{}{[He ponders over your words for a moment, then nods.] Alright, I'll give you some of our excess medical supplies.
 It sounds like you're gonna need 'em. Here. [He hands them to you.] Good luck, wanderer.}
{707}{}{Thanks, Jack. You're a true savior of the wastes. Bye.}
{708}{}{Then perhaps you should learn to be more careful. Sorry, I'm not going to just give away the Abbey's medical supplies.}
{709}{}{Fine. GOODBYE.}
{800}{}{Adesso non posso parlare.}
{801}{}{Sorry, I'm in the middle of something now. Come see me later.}
{802}{}{Ciao.}
