{100}{}{Vedi un giovane monaco con gli occhiali.}
{101}{}{Vedi Fratello Jason.}
{102}{}{Questo monaco sembra essere assorto nei suoi pensieri.}
{200}{}{[Il giovane monaco infila in fretta un mazzo di carte "Tragic" quando ti avvicini.] Che vuoi?}
{201}{}{Per il momento nulla. Ci vediamo.}
{202}{}{Voglio sapere perche' hai appena nascosto quel mazzo di carte.}
{210}{}{Non so di cosa stai parlando. Non ho nessun mazzo di carte.}
{211}{}{Non mentire. Ti ho visto infilarlo in tasca. Volevo solo sapere perche'.}
{212}{}{Certo, come no? Ci si vede.}
{220}{}{Senti, non dirlo a nessuno, va bene? Non dovremmo "usare" le reliquie prebelliche, solo venerarle. Ma queste carte Tragic sono dannatamente belle. 
[Sembra perdersi in un altro mondo mentre guarda il mazzo con aria sognante. Dopo un momento, rialza lo sguardo verso di te.] Oh, scusa. Io sono Fratello Jason, comunque. Tu, ehm... non e' che giochi a Tragic?}
{221}{}{PORTATE AVANTI LA RACCOLTA!!!}
{222}{}{Cavolo si', adoro Tragic the Garnering.}
{223}{}{L'ho provato, ma non fa per me.}
{224}{}{Ero dipendente da quel gioco, sul serio. Ora cerco di starne alla larga.}
{225}{}{No.}
{226}{}{Assolutamente no. Ti sembro un povero fallito?}
{230}{}{Ehi, vaffan… stronzo. Lasciami in pace.}
{231}{}{Ehi, fanculo puttana. Lasciami in pace.}
{232}{}{Mi piacerebbe, ma sono sopraffatto dal desiderio di farti del male.}
{233}{}{D'accordo, allora. Addio.}
{234}{}{Senti, mi dispiace. Sono stato scortese. E' solo che non sono un fan di Tragic.}
{240}{}{Ah, amico, mi piacerebbe un sacco giocare contro di te, ma e' troppo rischioso. Non voglio che me le portino via. 
E' questo che odio di questo posto. Siamo seduti su una dannata miniera d'oro di cose fantastiche di prima della guerra, ma ci proibiamo di godercele. 
Non ha alcun senso. E' semplicemente da idioti.}
{241}{}{Ah, amico, ti capisco benissimo. Vorrei poterci giocare anch'io piu' spesso, ma e' troppo rischioso. Non voglio che me le portino via. 
E' questo che odio di questo posto. Siamo seduti su una dannata miniera d'oro di cose fantastiche di prima della guerra, ma ci proibiamo di godercele. Non ha alcun senso. E' semplicemente da idioti.}
{242}{}{[Ride piano.] Abbiamo un dipendente tra le mani, vedo. Vorrei poter giocare anch'io piu' spesso, ma e' troppo rischioso. 
Non voglio che me le portino via. E' questo che odio di questo posto. Siamo seduti su una dannata miniera d'oro di cose fantastiche di prima della guerra, ma ci proibiamo di godercele. 
Non ha alcun senso. E' semplicemente da idioti.}
{243}{}{Non importa, tanto non potremmo giocare comunque: e' troppo rischioso. Non voglio che me le portino via. 
E' questo che odio di questo posto. Siamo seduti su una dannata miniera d'oro di cose fantastiche di prima della guerra, ma ci proibiamo di godercele. 
Non ha alcun senso. E' semplicemente da idioti.}
{244}{}{Sì, sembra davvero stupido.}
{245}{}{Se non condividi gli ideali del tuo ordine, perche' sei un monaco?}
{250}{}{Pensi che io abbia *scelto* di fare il monaco? Sono nato in questo stile di vita di merda. Vorrei solo che gli altri si
svegliassero e capissero quanto e' stupido non approfittare di tutta questa roba preziosa che abbiamo raccolto. Ma no, sono
perfettamente contenti di venerare e catalogare le reliquie, senza mai farne qualcosa di utile. Come ho detto, e' dannatamente idiota.}
{251}{}{Hai ragione, sembra davvero stupido.}
{252}{}{Tanto idiota quanto me che siedo qui ad ascoltarti lamentarti della tua vita. Addio.}
{253}{}{Se pensi che sia cosi' stupido, perche' non fai qualcosa per cercare di cambiare le cose?}
{260}{}{Finalmente qualcuno che e' d'accordo con me! Senti, ho un'idea, e forse potresti aiutarmi. Vedi, i monaci
qui hanno trascorso *anni* a trascrivere informazioni pre-guerra nel nostro database informatico. Se qualcuno dovesse "accidentalmente"
formattare il database, perderebbero tutto quel lavoro. Penso che una cosa del genere potrebbe farli tornare in senso e potremmo
finalmente abbandonare questo stupido stile di vita. Allora, che ne dici?}
{261}{}{Dico che e' una pessima idea e che ho finito di parlare con te.}
{262}{}{Cancellare anni del lavoro di qualcun altro? Sembra divertente. Lo faro'.}
{263}{}{Perché non lo formatti tu stesso?}
{264}{}{Se non ti piace stare qui, perché non te ne vai e basta?}
{270}{}{In realta' ho un'idea su come cambiare le cose. Magari potresti darmi una mano. Vedi, i monaci qui hanno passato anni a trascrivere informazioni pre?belliche nel nostro database. Se qualcuno dovesse “per sbaglio” formattare il database, perderebbero tutto quel lavoro. Una cosa del genere potrebbe scioccarli abbastanza da farli rinsavire, e forse finalmente rinunceremmo a questo stupido stile di vita. Allora, che ne dici?}
{271}{}{Dico che e' una pessima idea e che ho finito di parlare con te.}
{272}{}{Cancellare secoli del lavoro di qualcun altro? Sembra divertente. Lo faro'.}
{273}{}{Perché non lo formatti tu stesso?}
{274}{}{Se non ti piace stare qui, perché non te ne vai e basta?}
{280}{}{Stai scherzando? Mi crocifiggerebbero se lo facessi. Tu, invece… tu sei un avventuriero esperto. 
Diamine, scommetto che potresti massacrare tutti qui senza nemmeno sudare. Allora, lo fai o hai paura di un branco di monaci pacifisti?}
{281}{}{Non ho paura di nessuno. Lo faro'.}
{282}{}{Va bene, lo faro'. }
{283}{}{Nah, invece penso che mettero' alla prova la tua teoria del massacro. A partire da te.}
{284}{}{Passo. Non e' proprio il mio stile. Ciao.}
{285}{}{No, non lo faro'. Se ti trovi cosi' male qui, perche' non te ne vai tu?}
{286}{}{A meno che tu non abbia cambiato idea sull'aiutarmi, vaffanculo.}
{287}{}{Va bene, lo faro'. }
{288}{}{No, non lo faro'. Se ti trovi cosi' male qui, perche' non te ne vai tu?}
{290}{}{Lo farai? Sul serio? Oh, amico, fantastico. Pero' prima dovrai riuscire ad avere accesso, perche' sono parecchio protettivi riguardo al database. 
Non dovrebbe essere troppo difficile comunque: questi monaci si fidano di chiunque. Si incazzeranno da morire quando lo formatterai, ma sono tutti dei deboli, quindi non preoccuparti. Cerca solo di non ammazzare nessuno — non voglio che la situazione degeneri troppo, ok?}
{291}{}{Grande. Nient'altro?}
{292}{}{Non faccio promesse. Altro?}
{300}{}{Formatta il database e poi sparisci, perche' non vorranno piu' vederti in giro da queste parti. E non preoccuparti nemmeno di venire a dirmi che l’hai fatto: dovro' incazzarmi come tutti gli altri, altrimenti sospetteranno qualcosa. Grazie ancora per quello che stai facendo. E' per il loro bene.}
{301}{}{Come vuoi. Arrivederci.}
{310}{}{Sei impazzito? Non sono mai uscito nelle Lande, ma ho un’idea fin troppo chiara di com’e' la situazione la' fuori. 
Sarei fortunato ad arrivare a cinquanta metri prima che uno scorpione radioattivo mi pianti un pungiglione lungo un piede nel culo. O peggio: potrei venire catturato e torturato da una banda di razziatori fuori di testa oppure finire mangiato vivo da tribali cannibali. 
Qualunque cosa. So solo che, se me ne andassi da qui, sarei fottuto. Quindi no, sono bloccato qui.}
{311}{}{Ehi, non e' *cosi'* brutto la' fuori... In realta', hai ragione. Probabilmente non arriveresti nemmeno a Gecko.
Almeno, non senza aiuto. Ma cosa diresti se ti dicessi che ti scorto io?}
{312}{}{Che sfiga essere te. Arrivederci.}
{313}{}{Non perdere la speranza. Sono sicuro che ci sia una citta' nelle vicinanze dove potresti recarti in sicurezza.}
{315}{}{Si', beh, se ne trovi una, fammelo sapere.}
{316}{}{Lo faro'. Ci vediamo.}
{320}{}{A Gecko? E' la citta' dei ghoul, giusto? Grazie, ma no grazie.}
{321}{}{Ehi, i ghoul la' sono davvero molto amichevoli. Inoltre, ne conosco uno in particolare che ama fare una bella partita a Tragic.}
{322}{}{Hey, the ghouls there are actually really friendly.}
{323}{}{Hey, I hear the ghouls there are actually really friendly.}
{324}{}{Bene. Come preferisci. Arrivederci.}
{330}{}{No shit, another Tragic player? Hmm, that kind of changes things... I wonder if he'd have a Black Dahlia to
 trade. Alright. I'll go if you'll escort me.}
{331}{}{Andiamo.}
{332}{}{Va bene, ma devo prima sistemare alcune cose. Ti faro' sapere quando sono pronto a partire.}
{340}{}{Oh yeah? That doesn't change the fact that they look like brahmin shit. No thanks.}
{341}{}{Bene. Come preferisci. Arrivederci.}
{350}{}{Cosa vuoi?}
{351}{}{Volevo solo salutarti. Ci vediamo.}
{352}{}{Ho cambiato idea. Formattero' il computer per te.}
{353}{}{Hey, you might want to reconsider my offer to take you to Gecko, because I know
 someone there that loves a good game of Tragic.}
{354}{}{Hey, I know someone in Gecko that loves a good game of Tragic. I could take you there.}
{360}{}{Are we ready to go yet? I'm dying to know what kind of Tragic cards this guy's got.}
{361}{}{D'accordo, andiamo.}
{362}{}{Non ancora. Te lo faro' sapere.}
{370}{}{[Upon arriving in Gecko you introduce the young monk to Wooz. They quickly hit it off and begin comparing their
 Tragic card decks. You're about to leave when Brother Jason pulls himself away from Tragic long enough to have a word with you.]}
{371}{}{[AVANTI]}
{372}{}{Holy shit, Wooz *does* have a Black Dahlia! That alone has made this trip worthwhile. Sure, the ghouls are ugly
 as hell, but I found if I take off my glasses, then they're kinda tolerable. Anyway, thanks a lot for bringing me. Here,
 I, uh, "borrowed" this from the Abbey's Memorabilia, amazingly it's one of the few tech relics that still works.
 [He hands you a Stealth Boy.] See ya.}
{373}{}{Grazie. Ciao.}
{374}{}{Sono solo felice di non doverti sentire lamentare ancora. Arrivederci.}
{380}{}{Holy shit, Wooz *does* have a Black Dahlia! That alone has made this trip worthwhile. Sure, the ghouls are ugly
 as hell, but I found if I take off my glasses, then they're kinda tolerable. Anyway, thanks a lot for bringing me here.
 Here, [He reaches into his pocket, then frowns.] what the hell? I could swear I had it. Uh, sorry, but looks like I misplaced
 your reward, so you'll have to make due with a simple thanks. See ya.}
{381}{}{Oh, uh, non preoccuparti. Sono solo contento di aver potuto aiutare. Arrivederci.}
{382}{}{Sono solo felice di non doverti sentire lamentare ancora. Arrivederci.}
{400}{}{Can't talk... must build more powerful deck...}
{500}{}{Lasciami in pace.}
{501}{}{Vattene.}
{502}{}{Vaffanculo.}
{600}{}{Oh, hey, it's you. Somebody blew up the reactor at Gecko and all the ghouls left. No reason for me to stay there,
 so I left and came back here. Luckily for me the monks here didn't question my absence, so I'm not in any trouble for leaving.
 This sucks though, I thought I was going to have a new life doing what I love. [He sighs deeply]}
{601}{}{Mi dispiace sentire questo. A presto.}
{602}{}{That's life. One minute you're on top of the world and the next instant you're face down in the mud. Live and learn. Bye.}
{610}{}{Immagino che dovro' solo abituarmi a questo posto.}
{1000}{}{You safely escort Brother Jason to his new home.}
