{100}{}{Vedi un giovane monaco con gli occhiali.}
{101}{}{Vedi Fratello Jason.}
{102}{}{Questo monaco sembra essere assorto nei suoi pensieri.}
{200}{}{[Il giovane monaco infila in fretta un mazzo di carte "Tragic" quando ti avvicini.] Che vuoi?}
{201}{}{Per il momento nulla. Ci vediamo.}
{202}{}{Voglio sapere perche' hai appena nascosto quel mazzo di carte.}
{210}{}{Non so di cosa stai parlando. Non ho nessun mazzo di carte.}
{211}{}{Non mentire. Ti ho visto infilarlo in tasca. Volevo solo sapere perche'.}
{212}{}{Certo, come no? Ci si vede.}
{220}{}{Senti, non dirlo a nessuno, va bene? Non dovremmo "usare" le reliquie prebelliche, solo venerarle. Ma queste carte Tragic sono dannatamente belle. 
[Sembra perdersi in un altro mondo mentre guarda il mazzo con aria sognante. Dopo un momento, rialza lo sguardo verso di te.] Oh, scusa. Io sono Fratello Jason, comunque. Tu, ehm... non e' che giochi a Tragic?}
{221}{}{PORTATE AVANTI LA RACCOLTA!!!}
{222}{}{Cavolo si', adoro Tragic the Garnering.}
{223}{}{L'ho provato, ma non fa per me.}
{224}{}{Ero dipendente da quel gioco, sul serio. Ora cerco di starne alla larga.}
{225}{}{No.}
{226}{}{Assolutamente no. Ti sembro un povero fallito?}
{230}{}{Ehi, vaffan… stronzo. Lasciami in pace.}
{231}{}{Ehi, fanculo puttana. Lasciami in pace.}
{232}{}{Mi piacerebbe, ma sono sopraffatto dal desiderio di farti del male.}
{233}{}{D'accordo, allora. Addio.}
{234}{}{Senti, mi dispiace. Sono stato scortese. E' solo che non sono un fan di Tragic.}
{240}{}{Ah, amico, mi piacerebbe un sacco giocare contro di te, ma e' troppo rischioso. Non voglio che me le portino via. 
E' questo che odio di questo posto. Siamo seduti su una dannata miniera d'oro di cose fantastiche di prima della guerra, ma ci proibiamo di godercele. 
Non ha alcun senso. E' semplicemente da idioti.}
{241}{}{Ah, amico, ti capisco benissimo. Vorrei poterci giocare anch'io piu' spesso, ma e' troppo rischioso. Non voglio che me le portino via. 
E' questo che odio di questo posto. Siamo seduti su una dannata miniera d'oro di cose fantastiche di prima della guerra, ma ci proibiamo di godercele. Non ha alcun senso. E' semplicemente da idioti.}
{242}{}{[Ride piano.] Abbiamo un dipendente tra le mani, vedo. Vorrei poter giocare anch'io piu' spesso, ma e' troppo rischioso. 
Non voglio che me le portino via. E' questo che odio di questo posto. Siamo seduti su una dannata miniera d'oro di cose fantastiche di prima della guerra, ma ci proibiamo di godercele. 
Non ha alcun senso. E' semplicemente da idioti.}
{243}{}{Non importa, tanto non potremmo giocare comunque: e' troppo rischioso. Non voglio che me le portino via. 
E' questo che odio di questo posto. Siamo seduti su una dannata miniera d'oro di cose fantastiche di prima della guerra, ma ci proibiamo di godercele. 
Non ha alcun senso. E' semplicemente da idioti.}
{244}{}{Sì, sembra davvero stupido.}
{245}{}{Se non condividi gli ideali del tuo ordine, perche' sei un monaco?}
{250}{}{Pensi che io abbia *scelto* di fare il monaco? Sono nato in questo stile di vita di merda. Vorrei solo che gli altri si
svegliassero e capissero quanto e' stupido non approfittare di tutta questa roba preziosa che abbiamo raccolto. Ma no, sono
perfettamente contenti di venerare e catalogare le reliquie, senza mai farne qualcosa di utile. Come ho detto, e' dannatamente idiota.}
{251}{}{Hai ragione, sembra davvero stupido.}
{252}{}{Tanto idiota quanto me che siedo qui ad ascoltarti lamentarti della tua vita. Addio.}
{253}{}{Se pensi che sia cosi' stupido, perche' non fai qualcosa per cercare di cambiare le cose?}
{260}{}{Finalmente qualcuno che e' d'accordo con me! Senti, ho un'idea, e forse potresti aiutarmi. Vedi, i monaci
qui hanno trascorso *anni* a trascrivere informazioni pre-guerra nel nostro database informatico. Se qualcuno dovesse "accidentalmente"
formattare il database, perderebbero tutto quel lavoro. Penso che una cosa del genere potrebbe farli tornare in senso e potremmo
finalmente abbandonare questo stupido stile di vita. Allora, che ne dici?}
{261}{}{Dico che e' una pessima idea e che ho finito di parlare con te.}
{262}{}{Cancellare anni del lavoro di qualcun altro? Sembra divertente. Lo faro'.}
{263}{}{Perché non lo formatti tu stesso?}
{264}{}{Se non ti piace stare qui, perché non te ne vai e basta?}
{270}{}{In realta' ho un'idea su come cambiare le cose. Magari potresti darmi una mano. Vedi, i monaci qui hanno passato anni a trascrivere informazioni pre?belliche nel nostro database. Se qualcuno dovesse “per sbaglio” formattare il database, perderebbero tutto quel lavoro. Una cosa del genere potrebbe scioccarli abbastanza da farli rinsavire, e forse finalmente rinunceremmo a questo stupido stile di vita. Allora, che ne dici?}
{271}{}{Dico che e' una pessima idea e che ho finito di parlare con te.}
{272}{}{Cancellare secoli del lavoro di qualcun altro? Sembra divertente. Lo faro'.}
{273}{}{Perché non lo formatti tu stesso?}
{274}{}{Se non ti piace stare qui, perché non te ne vai e basta?}
{280}{}{Stai scherzando? Mi crocifiggerebbero se lo facessi. Tu, invece… tu sei un avventuriero esperto. 
Diamine, scommetto che potresti massacrare tutti qui senza nemmeno sudare. Allora, lo fai o hai paura di un branco di monaci pacifisti?}
{281}{}{I'm not afraid of anyone. I'll do it.}
{282}{}{Alright. I'll do it.}
{283}{}{Nah, instead I think I'll test out your massacre theory. Starting with you.}
{284}{}{I'll pass. That's just not my style. Bye.}
{285}{}{No, I'm not going to do it. If you hate it here, why don't you just leave?}
{286}{}{Unless you've changed your mind about helping me, fuck off.}
{287}{}{Alright. I'll do it.}
{288}{}{No, I'm not going to do it. If you hate it here, why don't you just leave?}
{290}{}{You will? Seriously? Oh man, that's awesome. But first, you'll need to get access, 'cause they're pretty protective
 of the database. It shouldn't be too hard though, these monks are pretty trusting. They're gonna be pissed as hell when
 you format it, but they're all a bunch of wimps, so don't worry about it. Just try not to kill anyone -- I don't want things
 to get too out of hand, you know?}
{291}{}{Sure. Anything else?}
{292}{}{I make no promises. Anything else?}
{300}{}{Just format it, then take off, cause they're not going to want you around here. Don't even bother to come tell me
 you did it, because I'll have to act just as pissed as everyone else or they'll suspect something's up. Thanks again for
 doing this. It's for their own good.}
{301}{}{Whatever you say. Bye.}
{310}{}{Are you crazy? I've never been out in the wastes, but I've got a pretty damn good idea as to what it's like. I'd
 be lucky to make if fifty yards before a radscorpion shoved a foot-long stinger up my ass. Or even worse, I'd get captured
 and tortured by a gang of maniac raiders *or* I'd be eaten alive by cannibalistic tribals. Whatever. I just know that if
 I left here, I'd be fucked. So no, I'm stuck here.}
{311}{}{Hey, it's not *that* bad out there... Actually, you're right. You probably wouldn't even make it to Gecko.
 At least, not without help. But what if I said I'd escort you?}
{312}{}{Sucks to be you. Bye.}
{313}{}{Keep your hopes up. I'm sure there is a town nearby that would be safe to travel to.}
{315}{}{Yeah, well if you find one, let me know.}
{316}{}{Lo faro'. Ci vediamo.}
{320}{}{To Gecko? That's the ghoul town, right? Thanks, but no thanks.}
{321}{}{Hey, the ghouls there are actually really friendly. Besides, I know one in particular that loves a good game of Tragic.}
{322}{}{Hey, the ghouls there are actually really friendly.}
{323}{}{Hey, I hear the ghouls there are actually really friendly.}
{324}{}{Alright. Suit yourself. Bye.}
{330}{}{No shit, another Tragic player? Hmm, that kind of changes things... I wonder if he'd have a Black Dahlia to
 trade. Alright. I'll go if you'll escort me.}
{331}{}{Lets go.}
{332}{}{Alright, but I need to take care of some things first. I'll let you know when I'm ready to go.}
{340}{}{Oh yeah? That doesn't change the fact that they look like brahmin shit. No thanks.}
{341}{}{Alright. Suit yourself. Bye.}
{350}{}{Cosa vuoi?}
{351}{}{I just wanted to say hi. See ya.}
{352}{}{I changed my mind. I'll format the computer for you.}
{353}{}{Hey, you might want to reconsider my offer to take you to Gecko, because I know
 someone there that loves a good game of Tragic.}
{354}{}{Hey, I know someone in Gecko that loves a good game of Tragic. I could take you there.}
{360}{}{Are we ready to go yet? I'm dying to know what kind of Tragic cards this guy's got.}
{361}{}{D'accordo, andiamo.}
{362}{}{Non ancora. Te lo faro' sapere.}
{370}{}{[Upon arriving in Gecko you introduce the young monk to Wooz. They quickly hit it off and begin comparing their
 Tragic card decks. You're about to leave when Brother Jason pulls himself away from Tragic long enough to have a word with you.]}
{371}{}{[AVANTI]}
{372}{}{Holy shit, Wooz *does* have a Black Dahlia! That alone has made this trip worthwhile. Sure, the ghouls are ugly
 as hell, but I found if I take off my glasses, then they're kinda tolerable. Anyway, thanks a lot for bringing me. Here,
 I, uh, "borrowed" this from the Abbey's Memorabilia, amazingly it's one of the few tech relics that still works.
 [He hands you a Stealth Boy.] See ya.}
{373}{}{Grazie. Ciao.}
{374}{}{I'm just happy I won't have to hear you bitch anymore. Bye.}
{380}{}{Holy shit, Wooz *does* have a Black Dahlia! That alone has made this trip worthwhile. Sure, the ghouls are ugly
 as hell, but I found if I take off my glasses, then they're kinda tolerable. Anyway, thanks a lot for bringing me here.
 Here, [He reaches into his pocket, then frowns.] what the hell? I could swear I had it. Uh, sorry, but looks like I misplaced
 your reward, so you'll have to make due with a simple thanks. See ya.}
{381}{}{Oh, uh, don't worry about it. Just glad I could help. Bye.}
{382}{}{I'm just happy I won't have to hear you bitch anymore. Bye.}
{400}{}{Can't talk... must build more powerful deck...}
{500}{}{Lasciami in pace.}
{501}{}{Vattene.}
{502}{}{Fuck off.}
{600}{}{Oh, hey, it's you. Somebody blew up the reactor at Gecko and all the ghouls left. No reason for me to stay there,
 so I left and came back here. Luckily for me the monks here didn't question my absence, so I'm not in any trouble for leaving.
 This sucks though, I thought I was going to have a new life doing what I love. [He sighs deeply]}
{601}{}{Sorry to hear that. See you around.}
{602}{}{That's life. One minute you're on top of the world and the next instant you're face down in the mud. Live and learn. Bye.}
{610}{}{Guess I just gotta get used to this place.}
{1000}{}{You safely escort Brother Jason to his new home.}
