{100}{}{Vedi un giovane monaco con gli occhiali.}
{101}{}{Vedi Fratello Jason.}
{102}{}{Questo monaco sembra essere assorto nei suoi pensieri.}
{200}{}{[Il giovane monaco infila in fretta un mazzo di carte "Tragic" quando ti avvicini.] Che vuoi?}
{201}{}{Per il momento nulla. Ci vediamo.}
{202}{}{Voglio sapere perche' hai appena nascosto quel mazzo di carte.}
{210}{}{Non so di cosa stai parlando. Non ho nessun mazzo di carte.}
{211}{}{Non mentire. Ti ho visto infilarlo in tasca. Volevo solo sapere perche'.}
{212}{}{Certo, come no? Ci si vede.}
{220}{}{Senti, non dirlo a nessuno, va bene? Non dovremmo "usare" le reliquie prebelliche, solo venerarle. Ma queste carte Tragic sono dannatamente belle. 
[Sembra perdersi in un altro mondo mentre guarda il mazzo con aria sognante. Dopo un momento, rialza lo sguardo verso di te.] Oh, scusa. Io sono Fratello Jason, comunque. Tu, ehm... non e' che giochi a Tragic?}
{221}{}{PORTATE AVANTI LA RACCOLTA!!!}
{222}{}{Cavolo si', adoro Tragic the Garnering.}
{223}{}{L'ho provato, ma non fa per me.}
{224}{}{Ero dipendente da quel gioco, sul serio. Ora cerco di starne alla larga.}
{225}{}{No.}
{226}{}{Assolutamente no. Ti sembro un povero fallito?}
{230}{}{Ehi, vaffan… stronzo. Lasciami in pace.}
{231}{}{Ehi, fanculo puttana. Lasciami in pace.}
{232}{}{Mi piacerebbe, ma sono sopraffatto dal desiderio di farti del male.}
{233}{}{D'accordo, allora. Addio.}
{234}{}{Senti, mi dispiace. Sono stato scortese. E' solo che non sono un fan di Tragic.}
{240}{}{Ah, amico, mi piacerebbe un sacco giocare contro di te, ma e' troppo rischioso. Non voglio che me le portino via. 
E' questo che odio di questo posto. Siamo seduti su una dannata miniera d'oro di cose fantastiche di prima della guerra, ma ci proibiamo di godercele. 
Non ha alcun senso. E' semplicemente da idioti.}
{241}{}{Ah, amico, ti capisco benissimo. Vorrei poterci giocare anch'io piu' spesso, ma e' troppo rischioso. Non voglio che me le portino via. 
E' questo che odio di questo posto. Siamo seduti su una dannata miniera d'oro di cose fantastiche di prima della guerra, ma ci proibiamo di godercele. Non ha alcun senso. E' semplicemente da idioti.}
{242}{}{[Ride piano.] Abbiamo un dipendente tra le mani, vedo. Vorrei poter giocare anch'io piu' spesso, ma e' troppo rischioso. 
Non voglio che me le portino via. E' questo che odio di questo posto. Siamo seduti su una dannata miniera d'oro di cose fantastiche di prima della guerra, ma ci proibiamo di godercele. 
Non ha alcun senso. E' semplicemente da idioti.}
{243}{}{Non importa, tanto non potremmo giocare comunque: e' troppo rischioso. Non voglio che me le portino via. 
E' questo che odio di questo posto. Siamo seduti su una dannata miniera d'oro di cose fantastiche di prima della guerra, ma ci proibiamo di godercele. 
Non ha alcun senso. E' semplicemente da idioti.}
{244}{}{Sì, sembra davvero stupido.}
{245}{}{Se non condividi gli ideali del tuo ordine, perche' sei un monaco?}
{250}{}{Pensi che io abbia *scelto* di fare il monaco? Sono nato in questo stile di vita di merda. Vorrei solo che gli altri si
svegliassero e capissero quanto e' stupido non approfittare di tutta questa roba preziosa che abbiamo raccolto. Ma no, sono
perfettamente contenti di venerare e catalogare le reliquie, senza mai farne qualcosa di utile. Come ho detto, e' dannatamente idiota.}
{251}{}{Hai ragione, sembra davvero stupido.}
{252}{}{Tanto idiota quanto me che siedo qui ad ascoltarti lamentarti della tua vita. Addio.}
{253}{}{Se pensi che sia cosi' stupido, perche' non fai qualcosa per cercare di cambiare le cose?}
{260}{}{Finalmente qualcuno che e' d'accordo con me! Senti, ho un'idea, e forse potresti aiutarmi. Vedi, i monaci
qui hanno trascorso *anni* a trascrivere informazioni pre-guerra nel nostro database informatico. Se qualcuno dovesse "accidentalmente"
formattare il database, perderebbero tutto quel lavoro. Penso che una cosa del genere potrebbe farli tornare in senso e potremmo
finalmente abbandonare questo stupido stile di vita. Allora, che ne dici?}
{261}{}{Dico che e' una pessima idea e che ho finito di parlare con te.}
{262}{}{Cancellare anni del lavoro di qualcun altro? Sembra divertente. Lo faro'.}
{263}{}{Perché non lo formatti tu stesso?}
{264}{}{Se non ti piace stare qui, perché non te ne vai e basta?}
{270}{}{In realta' ho un'idea su come cambiare le cose. Magari potresti darmi una mano. Vedi, i monaci qui hanno passato anni a trascrivere informazioni pre?belliche nel nostro database. Se qualcuno dovesse “per sbaglio” formattare il database, perderebbero tutto quel lavoro. Una cosa del genere potrebbe scioccarli abbastanza da farli rinsavire, e forse finalmente rinunceremmo a questo stupido stile di vita. Allora, che ne dici?}
{271}{}{Dico che e' una pessima idea e che ho finito di parlare con te.}
{272}{}{Cancellare secoli del lavoro di qualcun altro? Sembra divertente. Lo faro'.}
{273}{}{Perché non lo formatti tu stesso?}
{274}{}{Se non ti piace stare qui, perché non te ne vai e basta?}
{280}{}{Stai scherzando? Mi crocifiggerebbero se lo facessi. Tu, invece… tu sei un avventuriero esperto. 
Diamine, scommetto che potresti massacrare tutti qui senza nemmeno sudare. Allora, lo fai o hai paura di un branco di monaci pacifisti?}
{281}{}{Non ho paura di nessuno. Lo faro'.}
{282}{}{Va bene, lo faro'.}
{283}{}{Nah, invece penso che mettero' alla prova la tua teoria del massacro. A partire da te.}
{284}{}{Passo. Non e' proprio il mio stile. Ciao.}
{285}{}{No, non lo faro'. Se ti trovi cosi' male qui, perche' non te ne vai tu?}
{286}{}{A meno che tu non abbia cambiato idea sull'aiutarmi, vaffanculo.}
{287}{}{Va bene, lo faro'.}
{288}{}{No, non lo faro'. Se ti trovi cosi' male qui, perche' non te ne vai tu?}
{290}{}{Lo farai? Sul serio? Oh, amico, fantastico. Pero' prima dovrai riuscire ad avere accesso, perche' sono parecchio protettivi riguardo al database. 
Non dovrebbe essere troppo difficile comunque: questi monaci si fidano di chiunque. Si incazzeranno da morire quando lo formatterai, ma sono tutti dei deboli, quindi non preoccuparti. Cerca solo di non ammazzare nessuno — non voglio che la situazione degeneri troppo, ok?}
{291}{}{Grande. Nient'altro?}
{292}{}{Non faccio promesse. Altro?}
{300}{}{Formatta il database e poi sparisci, perche' non vorranno piu' vederti in giro da queste parti. E non preoccuparti nemmeno di venire a dirmi che l’hai fatto: dovro' incazzarmi come tutti gli altri, altrimenti sospetteranno qualcosa. Grazie ancora per quello che stai facendo. E' per il loro bene.}
{301}{}{Come vuoi. Arrivederci.}
{310}{}{Sei impazzito? Non sono mai uscito nelle Lande, ma ho un’idea fin troppo chiara di com’e' la situazione la' fuori. 
Sarei fortunato ad arrivare a cinquanta metri prima che uno scorpione radioattivo mi pianti un pungiglione lungo un piede nel culo. O peggio: potrei venire catturato e torturato da una banda di razziatori fuori di testa oppure finire mangiato vivo da tribali cannibali. 
Qualunque cosa. So solo che, se me ne andassi da qui, sarei fottuto. Quindi no, sono bloccato qui.}
{311}{}{Ehi, non e' *cosi'* brutto la' fuori... In realta', hai ragione. Probabilmente non arriveresti nemmeno a Gecko.
Almeno, non senza aiuto. Ma cosa diresti se ti dicessi che ti scorto io?}
{312}{}{Che sfiga essere te. Arrivederci.}
{313}{}{Non perdere la speranza. Sono sicuro che ci sia una citta' nelle vicinanze dove potresti recarti in sicurezza.}
{315}{}{Si', beh, se ne trovi una, fammelo sapere.}
{316}{}{Lo faro'. Ci vediamo.}
{320}{}{A Gecko? E' la citta' dei ghoul, giusto? Grazie, ma no grazie.}
{321}{}{Ehi, i ghoul la' sono davvero molto amichevoli. Inoltre, ne conosco uno in particolare che ama fare una bella partita a Tragic.}
{322}{}{Ehi, i ghoul la' sono davvero molto amichevoli.}
{323}{}{Ehi, ho sentito che i ghoul la' sono davvero molto amichevoli.}
{324}{}{Bene. Come preferisci. Arrivederci.}
{330}{}{Caspita, un altro giocatore di Tragic? Hmm, questo cambia le cose... Mi chiedo se avesse una Black Dahlia da
 scambiare. Va bene. Ci andro' se mi scortate.}
{331}{}{Andiamo.}
{332}{}{Va bene, ma devo prima sistemare alcune cose. Ti faro' sapere quando sono pronto a partire.}
{340}{}{Oh si'? Questo non cambia il fatto che sembrano escrementi di brahmin. No grazie.}
{341}{}{Bene. Come preferisci. Arrivederci.}
{350}{}{Cosa vuoi?}
{351}{}{Volevo solo salutarti. Ci vediamo.}
{352}{}{Ho cambiato idea. Formattero' il computer per te.}
{353}{}{Ehi, potresti voler riconsiderare la mia offerta di portarti a Gecko, perche' conosco
 qualcuno la' che ama una buona partita a Tragic.}
{354}{}{Ehi, conosco qualcuno a Gecko che ama una buona partita a Tragic. Potrei portarti la'.}
{360}{}{Siamo pronti a partire? Muoio dalla voglia di sapere che tipo di carte Tragic ha questo tizio.}
{361}{}{D'accordo, andiamo.}
{362}{}{Non ancora. Te lo faro' sapere.}
{370}{}{[Arrivati a Gecko, presenti il giovane monaco a Wooz. I due fanno subito amicizia e iniziano a confrontare i loro
 mazzi di carte Tragic. Stai per andartene quando Fratello Jason si stacca da Tragic quel tanto che basta per scambiare due parole con te.]}
{371}{}{[AVANTI]}
{372}{}{Wooz ha davvero una Black Dahlia! Da sola ha reso il viaggio degno. Certo, i ghoul sono brutti come il
 demonio, ma ho scoperto che se tolgo gli occhiali, sono quasi tollerabili. Comunque, grazie mille per avermi portato. Ecco, io,
 ehm, l'ho "preso in prestito" dai Memorabilia dell'Abbazia, stranamente e' una delle poche reliquie tecnologiche che funziona ancora.
 [Ti porge uno Stealth Boy.] Ci vediamo.}
{373}{}{Grazie. Ciao.}
{374}{}{Sono solo felice di non doverti sentire lamentare ancora. Arrivederci.}
{380}{}{Porca miseria, Wooz ha davvero una Black Dahlia! Da sola ha reso il viaggio degno. Certo, i ghoul sono brutti come il
 demonio, ma ho scoperto che se tolgo gli occhiali, sono quasi tollerabili. Comunque, grazie mille per avermi portato qui.
 Ecco, [Fruga in tasca, poi corruga la fronte.] che diavolo? Avrei giurato di averlo. Ehm, mi dispiace, ma sembra che abbia
 perso la tua ricompensa, quindi dovrai accontentarti di un semplice grazie. Ci vediamo.}
{381}{}{Oh, uh, non preoccuparti. Sono solo contento di aver potuto aiutare. Arrivederci.}
{382}{}{Sono solo felice di non doverti sentire lamentare ancora. Arrivederci.}
{400}{}{Non posso parlare... devo costruire un mazzo piu' potente...}
{500}{}{Lasciami in pace.}
{501}{}{Vattene.}
{502}{}{Vaffanculo.}
{600}{}{Oh, ehi, sei tu. Qualcuno ha fatto saltare il reattore a Gecko e tutti i ghoul se ne sono andati. Non avevo motivo di
 restare li', cosi' me ne sono andato e sono tornato qui. Fortunatamente per me i monaci qui non hanno messo in discussione
 la mia assenza, quindi non ho guai per essermene andato. Fa schifo pero', pensavo di avere una nuova vita facendo quello
 che amo. [Sospira profondamente]}
{601}{}{Mi dispiace sentire questo. A presto.}
{602}{}{E' la vita. Un momento sei in cima al mondo e quello dopo hai la faccia nel fango. Si vive e si impara. Ciao.}
{610}{}{Immagino che dovro' solo abituarmi a questo posto.}
{1000}{}{Scorti Fratello Jason sano e salvo nella sua nuova casa.}
