{100}{}{Vedi Fratello John.}
{101}{}{Vedi uno dei monaci piu' anziani dell'Abbazia.}
{102}{}{Vedi un vecchio monaco. Sembra avere poco piu' di settant'anni.}
{300}{}{Ciao, giovanotto.}
{301}{}{Chi sei?}
{302}{}{Hai sentito parlare di un GECK o del Vault 13?}
{303}{}{Addio.}
{400}{}{Mi chiamo John, sono uno dei monaci piu' anziani qui.}
{401}{}{Allora, qual e' il tuo compito?}
{402}{}{Capisco. Arrivederci.}
{403}{}{Be', lavoravo in una fattoria, ma faceva male al mio cuore.}
{404}{}{Hai problemi al cuore?}
{405}{}{Che peccato, arrivederci!}
{406}{}{Si', ho un cuore malato. Se avessi ancora le mie pillole per il cuore, la mia vita sarebbe molto piu' semplice. E' molto difficile 
 trovare medicine per quel problema nel mondo di oggi, sai.}
{407}{}{Potrei avere una soluzione per i tuoi problemi al cuore...}
{408}{}{Mi dispiace sentire questo. Arrivederci.}
{410}{}{Addio.}
{411}{}{Davvero? Stai dicendo che hai DAVVERO le pillole per il cuore?}
{412}{}{Si', ce li ho. Sarebbe un piacere darteli.}
{413}{}{Si', ho delle pillole per il cuore. Puoi averle per $400.}
{414}{}{Stavo solo scherzando. Non ho pillole per il cuore.}
{415}{}{[Ti prende le pillole.] Grazie, amico mio! Ecco, ti prego di accettare questo oggetto come gesto di gratitudine.}
{416}{}{Felice di aver aiutato, e grazie per l'oggetto. Arrivederci!}
{417}{}{(Diventa piuttosto arrabbiato, ma poi si calma) Ok, va bene, ecco i tuoi soldi. Ora dammi le pillole!}
{418}{}{Ho deciso di tenermi le pillole. Grazie per i soldi!}
{419}{}{E' stato un piacere fare affari con te. Arrivederci.}
{420}{}{Hmm, mi dispiace, non ne so nulla. Parla con l'Abate, potrebbe sapere qualcosa.}
{421}{}{Lo faro', grazie. Ora ho altre domande.}
{422}{}{Se non fossi cosi' malato, ti farei a pezzi. ORA VATTENE DA QUI!}
{423}{}{Bene, me ne vado.}
{500}{}{Grazie ancora per quelle pillole per il cuore, amico mio. Buona fortuna nei tuoi viaggi.}
{600}{}{Vai via, per favore.}
{700}{}{Hai mostrato a John quanto crudele possa essere il mondo.}
