{100}{}{Vedi Fratello John.}
{101}{}{Vedi uno dei monaci piu' anziani dell'Abbazia.}
{102}{}{Vedi un vecchio monaco. Sembra avere poco piu' di settant'anni.}
{300}{}{Ciao, giovanotto.}
{301}{}{Chi sei?}
{302}{}{Hai sentito parlare di un GECK o del Vault 13?}
{303}{}{Addio.}
{400}{}{Mi chiamo John, sono uno dei monaci piu' anziani qui.}
{401}{}{Allora, qual e' il tuo compito?}
{402}{}{Capisco. Arrivederci.}
{403}{}{Well, I used to work on a farm, but it was bad for my heart.}
{404}{}{Hai problemi al cuore?}
{405}{}{Che peccato, arrivederci!}
{406}{}{Yeah, I have a bad heart. If I still had my heart pills, it would ease my life a lot more. It is very difficult
 to find medicine for that problem in today's world you know.}
{407}{}{Potrei avere una soluzione per i tuoi problemi al cuore...}
{408}{}{Mi dispiace sentire questo. Arrivederci.}
{410}{}{Addio.}
{411}{}{You do? Are you saying that you actually HAVE heart pills?}
{412}{}{Si', ce li ho. Sarebbe un piacere darteli.}
{413}{}{Si', ho delle pillole per il cuore. Puoi averle per $400.}
{414}{}{I was only joking. I don't have any heart pills.}
{415}{}{[He takes the pills from you.] Thank you, my friend! Here, please take this item as a gesture of gratitude.}
{416}{}{Felice di aver aiutato, e grazie per l'oggetto. Arrivederci!}
{417}{}{(He becomes quite angry, but then calms down) Ok, fine, here's your money. Now give me the pills!}
{418}{}{Ho deciso di tenermi le pillole. Grazie per i soldi!}
{419}{}{E' stato un piacere fare affari con te. Arrivederci.}
{420}{}{Hmmm, sorry, I haven't. Talk to the Abbot, he might know something.}
{421}{}{Lo faro', grazie. Ora ho altre domande.}
{422}{}{If I weren't so sick, I would beat the shit out of you. NOW GET OUT OF HERE!}
{423}{}{Bene, me ne vado.}
{500}{}{Grazie ancora per quelle pillole per il cuore, amico mio. Buona fortuna nei tuoi viaggi.}
{600}{}{Vai via, per favore.}
{700}{}{Hai mostrato a John quanto crudele possa essere il mondo.}
