{100}{}{Vedi Fratello John.}
{101}{}{Vedi uno dei monaci piu' anziani dell'Abbazia.}
{102}{}{Vedi un vecchio monaco. Sembra avere poco piu' di settant'anni.}
{300}{}{Ciao, giovanotto.}
{301}{}{Chi sei?}
{302}{}{Hai sentito parlare di un GECK o del Vault 13?}
{303}{}{Addio.}
{400}{}{Mi chiamo John, sono uno dei monaci piu' anziani qui.}
{401}{}{Allora, qual e' il tuo compito?}
{402}{}{Capisco. Arrivederci.}
{403}{}{Well, I used to work on a farm, but it was bad for my heart.}
{404}{}{Hai problemi al cuore?}
{405}{}{Che peccato, arrivederci!}
{406}{}{Yeah, I have a bad heart. If I still had my heart pills, it would ease my life a lot more. It is very difficult
 to find medicine for that problem in today's world you know.}
{407}{}{Potrei avere una soluzione per i tuoi problemi al cuore...}
{408}{}{Mi dispiace sentire questo. Arrivederci.}
{410}{}{Addio.}
{411}{}{You do? Are you saying that you actually HAVE heart pills?}
{412}{}{Yes, I do. It would be a pleasure to give them to you.}
{413}{}{Yeah, I have heart pills. You can have them for $400.}
{414}{}{I was only joking. I don't have any heart pills.}
{415}{}{[He takes the pills from you.] Thank you, my friend! Here, please take this item as a gesture of gratitude.}
{416}{}{Happy to help, and thanks for the item. Bye!}
{417}{}{(He becomes quite angry, but then calms down) Ok, fine, here's your money. Now give me the pills!}
{418}{}{I have decided to keep the pills myself. Thanks for the money!}
{419}{}{Nice doing business with you, Bye.}
{420}{}{Hmmm, sorry, I haven't. Talk to the Abbot, he might know something.}
{421}{}{I'll do that, thanks. Now I have some other questions.}
{422}{}{If I weren't so sick, I would beat the shit out of you. NOW GET OUT OF HERE!}
{423}{}{Fine, I'll go.}
{500}{}{Thank you again for those heart pills, my friend. Good luck on your travels.}
{600}{}{Just go away, please.}
{700}{}{You showed John just how cruel the world is.}
