{100}{}{Vedi Max.}
{101}{}{Vedi un monaco ordinario dell'Abbazia.}
{102}{}{Sembra un po' nervoso.}
{200}{}{Ciao. Cosa posso fare per te?}
{201}{}{Ho qualcosa da parte di Elaine...}
{202}{}{Cos'e' questo posto?}
{203}{}{Addio.}
{300}{}{Lasciami indovinare. E' il pezzo di ricambio che ho richiesto, giusto?}
{301}{}{Si'. Ecco qua.}
{302}{}{No, stavo solo mettendoti alla prova.}
{303}{}{(Ti prende il pezzo dalle mani) Finalmente! Ora possiamo riparare questa macchina da stampa. Grazie, prendi questo manuale di sopravvivenza per il disturbo.}
{304}{}{Grazie.}
{305}{}{Senti, non ho tempo per questo. Hai il pezzo o no?}
{306}{}{Si', ce l'ho.}
{307}{}{Vabbene, me ne vado.}
{400}{}{Questa e' la nostra tipografia. Qui copiamo i nostri libri.}
{401}{}{Beh, grazie per le informazioni.}
{500}{}{Guadagni %d punti esperienza per aver consegnato il pezzo.}
{600}{}{Io essere GRANDE aiutante oggi. Io avere pezza macchina da donna bel nome.}
{610}{}{Deve essere il pezzo di ricambio che ho richiesto a Elaine. Grazie per averlo portato. Ecco, prendi questo
 manuale di sopravvivenza per il disturbo... ehm, se sai leggerlo, s'intende.}
{611}{}{Io leggere dieci parole. Io piacere piu' libri con figure. Bello guardare. Grazzie!}
