{100}{}{Vedi Max.}
{101}{}{Vedi un monaco ordinario dell'Abbazia.}
{102}{}{Sembra un po' nervoso.}
{200}{}{Ciao. Cosa posso fare per te?}
{201}{}{Ho qualcosa da parte di Elaine...}
{202}{}{Cos'e' questo posto?}
{203}{}{Addio.}
{300}{}{Let me guess. It's that service part I requested, right?}
{301}{}{Si'. Ecco qua.}
{302}{}{No, stavo solo mettendoti alla prova.}
{303}{}{(He takes the part from your hands) Finally! Now we can fix this printing machine. Thanks, take this survival manual for your trouble.}
{304}{}{Grazie.}
{305}{}{Senti, non ho tempo per questo. Hai il pezzo o no?}
{306}{}{Si', ce l'ho.}
{307}{}{Vabbene, me ne vado.}
{400}{}{This is our printing works. We copy our books here.}
{401}{}{Beh, grazie per le informazioni.}
{500}{}{Guadagni %d punti esperienza per aver consegnato il pezzo.}
{600}{}{I be BIG helper today. I have macheen part from pretty name woman.}
{610}{}{That must be the service part that I requested from Elaine. Thanks for bringing this to me. Here, take this
 survival manual for your trouble... uh if you can read it that is.}
{611}{}{I read ten words. I likie pitcher books more. They fun to look. Tankee!}
