{100}{}{Vedi un monaco di mezza eta'.}
{101}{}{Vedi Fratello Matthew.}
{102}{}{E' in piedi a un podio a predicare ai cittadini dell'Abbazia.}
{200}{}{Buona gente dell'Abbazia. Prendetevi un momento per ascoltare, perche' ho molto da dire.}
{201}{}{Qui raccogliamo le sacre reliquie di un'eta' ormai lontana.}
{202}{}{Bruciati dal Diluvio di Fiamme, nel buio fummo gettati.}
{203}{}{Un Memorabilia creeremo, per preservare la saggezza del passato.}
{204}{}{Dobbiamo custodirlo e preservarlo, anche se la fiamma si e' spenta;}
{205}{}{Potrebbe divampare di nuovo, se la saggezza venisse usata male.}
{206}{}{Percio', nessuno dovra' imparare, per timore di un altro Diluvio di Fiamme.}
{207}{}{Ma un giorno, gli uomini si eleveranno al di sopra del loro desiderio di distruzione.}
{208}{}{E il Memorabilia sara' li', in attesa di essere reintrodotto.}
{209}{}{Cosi' ci dedichiamo al nostro sacro compito, affinche' tutta quella saggezza non vada perduta.}
{210}{}{Dobbiamo preservarlo e proteggerlo, ma mai dovremmo usarlo.}
{211}{}{Ora andate, amici miei, e lasciate che il vostro spirito si sollevi;}
{212}{}{Poiche' custodi della conoscenza, ognuno di noi e' stato dotato di un dono.}
{213}{}{Ora, prendetevi un momento per riflettere su cio' che ho detto.}
{224}{}{Ora, prendetevi un momento per riflettere su cio' che ho detto.}
{300}{}{Salve, amico. Non credo di averti mai visto da queste parti. Mi chiamo Fratello Matteo e aiuto
 a diffondere la parola sull'importanza di preservare la conoscenza degli antichi.}
{301}{}{E' un piacere conoscerti Matt. Il mio nome e' }
{302}{}{ sono alla ricerca del sacro GECK.}
{303}{}{Scusa, devo andare.}
{400}{}{Un GECK, eh? Mi sembra di ricordare di aver letto qualcosa in merito durante una delle mie sessioni di trascrizione. Quindi deve
 essere nel nostro database, ma temo che l'accesso ai nostri computer sia limitato. Tuttavia, se parli con l'Abate, e'
 possibile che ti conceda l'accesso. Non costa nulla provare, comunque. Oh, e sentiti libero di curiosare tra la nostra collezione
 di sacre reliquie pre-guerra. Ti chiederei di non danneggiare nulla, ma temo che sia gia' tutto rotto oltre ogni riparazione.}
{401}{}{Penso proprio di si'. Ho alcune domande pero'.}
{402}{}{Grazie. Penso che lo faro' ora.}
{500}{}{Sono a tua disposizione. Cosa vorresti sapere?}
{501}{}{Cosa puoi dirmi di questo posto?}
{502}{}{Sembri molto poetico nelle tue prediche. C'e' un motivo?}
{503}{}{Non importa. Prenditi cura di te.}
{600}{}{L'Abbazia e' la casa di chiunque, a patto che non causi problemi. Siamo una comunita' indipendente e riceviamo raramente
 visitatori come te. La maggior parte di coloro che vedi qui sono discendenti dei fondatori originali che si stabilirono in
 questo vecchio monastero non molto tempo dopo il grande Diluvio di Fiamme.}
{601}{}{Continua.}
{602}{}{La qualita' tranquilla e pacifica di questo luogo ne ha fatto una casa accogliente per altri viaggiatori che vi sono giunti
 nel corso degli anni, cercando di fuggire dal buio caos delle Lande. Certo, il vero valore di questo posto risiede
 nella sua vasta biblioteca. E' piena di antichi tomi contenenti la strana saggezza di un'eta' perduta. Col tempo, ci siamo
 considerati i custodi e i guardiani di quella saggezza.}
{603}{}{Molto interessante. Un'altra domanda.}
{604}{}{Interessante. Beh, devo andare.}
{700}{}{[L'uomo ride della tua domanda] No, nessun motivo particolare. Ho semplicemente letto molta poesia nel corso della mia vita
 e mi piace applicarla ai miei insegnamenti. Aiuta a lasciare un impatto maggiore su chi ascolta.}
{701}{}{Abbastanza giusto. Un'altra domanda.}
{800}{}{E' bello rivederti. }
{801}{}{. Cosa posso fare per te?}
{802}{}{Ho delle domande da farvi.}
{803}{}{Niente. A presto.}
