{100}{}{Vedi un mercante.}
{102}{}{Vedi un mercante che sta cercando di riparare la pompa dell'acqua.}
{103}{}{Non riesco proprio a far funzionare questa cosa!}
{104}{}{Sembra davvero difficile da riparare.}
{105}{}{Che pezzo di merda!}
{106}{}{Piccolo testardo figlio di puttana, eh?}
{107}{}{Potresti darmi una mano?}
{108}{}{Forse tu avrai piu' fortuna con questa.}
{109}{}{Ehi, grazie per aver riparato la pompa dell'acqua!}
{110}{}{Dovresti avvisare il monaco capo che la pompa dell'acqua e' stata riparata.}
{200}{}{Grazie per averci aiutato con questa cosa.}
{300}{}{Ah, che pezzo di mer- ehm, sono un po' occupato adesso. Hai bisogno di qualcosa o stai solo
 sprecando il mio tempo?}
{301}{}{In realta' si', l'Abate mi ha mandato. Ha detto che la pompa dell'acqua ha qualche problema.}
{302}{}{Eh, "qualche problema" e' dire poco. Questo vecchio arnese e' completamente a pezzi. Non c'e' modo
 che funzioni di nuovo.}
{303}{}{Capisco. Allora immagino che non farebbe male se dessi un'occhiata.}
{304}{}{Certo, fai pure. Come se potessi romperla ancora di piu'.}
{305}{}{Non voglio disturbare, ma qual e' il problema qui?}
{306}{}{La pompa dell'acqua principale dell'Abbazia e' rotta. Il dannato aggeggio stava tirando le cuoia negli ultimi giorni
 e ora ha finalmente ceduto.}
{307}{}{Sono abbastanza esperto di tecnologia, ti dispiace se do un'occhiata?}
{308}{}{Be', non sono molto bravo con le macchine, ma forse riesco a vedere se si puo' fare qualcosa.}
{309}{}{Certo, nessuno te lo impedisce.}
{310}{}{Uh, scusa. Arrivederci.}
{311}{}{Vedro' di fare il possibile.}
{312}{}{Pensavo di poter aiutare, ma se vuoi fare lo stronzo, arrangiatevi pure da solo.}
{313}{}{Ho detto all'Abate che ero disposto ad aiutare, ma se vuoi fare lo stronzo, arrangiatevi pure da solo.}
{320}{}{[Ti fissa per un momento, poi lascia lentamente uscire il respiro in un sospiro.] Scusa amico, questa cosa e' una
 vera rottura, e mi ha fatto perdere la pazienza. Non volevo scattarti contro. }
{321}{}{Beh, qual e' il problema allora?}
{322}{}{Vabbe', ciao.}
{330}{}{Torna a trovarmi domani mattina.}
{400}{}{Oh, sei tu di nuovo. Hai avuto fortuna?}
{401}{}{No, non ancora. Ti faro' sapere se ne avro'.}
{402}{}{In realta' si'. Ho guardato dentro e sembra che il motore sia completamente a pezzi. I collegamenti sono bruciati, quindi
 dovremo procurarci un motore nuovo, oltre a dei cavi per ricollegare tutto dato che quelli vecchi sono fusi.}
{500}{}{Hmm... i connettori del motore principale sono bruciati, eh? Be', ho dei cavi qui con me che andrebbero bene, ma non
 quel motore specifico. Sono sicuro che Vault City abbia il pezzo. Vai la' e parla con Harry nel cortile principale. Digli
 che ti manda Dave. Il dannato motore e' costoso, ma dovrebbe farti un buon prezzo.}
{501}{}{Ci vado subito. Torno presto.}
{502}{}{Aspetta un secondo. Ero felice di aiutarti a capire il problema, ma chi ha detto che sono disposto a traversare
 le Lande per andare a comprare un costoso motore? Se vuoi il mio aiuto, avra' un costo.}
{503}{}{Perche' non lo dici *tu* a Harry quando vai a prendertelo da solo? Non sono il tuo cazzo di fattorino. Ciao.}
{510}{}{Va bene, non mi aspetto che qualcuno lavori gratis. Il pezzo ti costera' circa 500 e penso che altri 100 per
 il disturbo siano ragionevoli. Ecco 600.}
{511}{}{Meglio cosi'. Tornero' con il pezzo.}
{600}{}{Hai trovato il pezzo? Questa macchina non si ripara da sola.}
{601}{}{No, non ancora. Tornero' quando l'avro'.}
{602}{}{Si', ho il pezzo proprio qui.}
{700}{}{Eccellente. Vuoi che installi il dannato aggeggio, o vuoi il piacere di farlo tu?}
{701}{}{Penso di farcela. Fatti da parte.}
{702}{}{In realta', penso di aver fatto abbastanza in questo lavoro. Vai avanti e installalo tu stesso.}
{800}{}{Va bene, consegnalo.}
{801}{}{Ecco qua.}
{900}{}{Questo dovrebbe bastare.}
{901}{}{La pompa dell'acqua e' stata riparata.}
{910}{}{(Si asciuga il sudore dalla fronte.) Si', hai bisogno di qualcosa?}
{911}{}{L'Abate ha detto che potresti aver bisogno di aiuto. Qual e' il problema?}
{912}{}{Non importa. Arrivederci.}
{913}{}{Ho dato un'occhiata alla pompa dell'acqua e sembra che il motore sia completamente a pezzi. I collegamenti sono bruciati, quindi
 dovremo procurarci un motore nuovo, oltre a dei cavi per ricollegare tutto dato che quelli vecchi sono fusi.}
