{100}{}{Vedi la Signora Peterson.}
{101}{}{Vedi una giovane e bella donna. Sorride quando ti vede.}
{200}{}{Benvenuto all'Abbazia, amico.}
{201}{}{Se hai bisogno di qualcosa, parla con mio marito.}
{202}{}{Bella giornata, vero?}
{300}{}{Benvenuto all'Abbazia, amico.}
{301}{}{Se hai bisogno di qualcosa, parla con mio marito.}
{302}{}{Bella serata, vero?}
{400}{}{Non ho niente da dirti. Per favore, vattene.}
