{100}{}{Vedi un contadino.}
{101}{}{Vedi un contadino dall'aspetto sano.}
{102}{}{Vedi una persona.}
{103}{}{Drinking too much booze lately?}
{104}{}{Stai lontano dall'alcol per un po'.}
{105}{}{I see that you drank Hank's "special" mix.}
{106}{}{Benvenuto, eroe!}
{107}{}{Hai fatto vedere a quei bastardi dell'Enclave!}
{108}{}{Sei davvero un eroe!}
{109}{}{Ho sentito dire che hai distrutto l'Enclave, ben fatto!}
{110}{}{Salve.}
{111}{}{I hope that it starts to rain soon, or my crops will not survive.}
{112}{}{Non riceviamo molti visitatori qui.}
{113}{}{Benvenuti!}
{114}{}{Yeah, I know. It's pretty boring here, but at least we're safe from raiders and such...}
{115}{}{Ciao, selvaggio.}
{116}{}{It sure is a hot day today!}
{117}{}{Good farming grounds here...}
{118}{}{Buona giornata.}
{119}{}{Welcome to the Abbey, wanderer!}
{120}{}{Impressive monastery we have here, eh?}
{200}{}{Toglimi quelle fottute mani di dosso!}
