{100}{}{You see a young, strong looking man.}
{101}{}{You see Mr. Peterson.}
{200}{}{Hello, friend. Haven't seen you around here before. First time to the Abbey?}
{201}{}{Good to see you again. What can I do for you?}
{202}{}{Yeah. What can you tell me about this place?}
{203}{}{I'm on a quest to find the holy GECK. Do you know anything about this?}
{204}{}{Fratello Samuel ha detto che potresti sapere qualcosa su chi sta disturbando le tombe. Ha detto che hai sentito dei
 rumori provenire dai tuoi campi.}
{205}{}{Nevermind, I must be going.}
{300}{}{Mia moglie ed io siamo arrivati qui qualche anno fa con una carovana. Ci e' piaciuto cosi' tanto che abbiamo deciso di restare e avviare la
 nostra piccola fattoria. Lasciami dire, l'Abbazia potrebbe non essere sfarzosa come New Reno, ne' avanzata come Vault City, ma per
 quanto mi riguarda, questo posto e' il meglio che si possa trovare nelle Lande. La gente qui e' onesta e si aiuta a vicenda.
 Certo, alcuni posti potrebbero offrire piu' sicurezza, ma al costo della liberta' personale. No grazie.}
{301}{}{Sei arrivato con una carovana? Passano spesso da qui?}
{302}{}{Non molto. L'Abbazia e' troppo piccola e isolata perche' le carovane ci prestino molta attenzione. Non importa pero', siamo
 una comunita' abbastanza autosufficiente -- coltiviamo il nostro cibo, produciamo il nostro alcol -- quindi ce la caviamo benissimo. In ogni caso, Bill e' la persona
 con cui parlare delle carovane, gestisce il negozio di alimentari appena a sudovest di qui.}
{303}{}{That sounds great and all, but I really must be going.}
{304}{}{Interessante. Ero curioso riguardo altro.}
{305}{}{Nevermind, I must be going.}
{400}{}{What else would you like to know?}
{401}{}{Cosa puoi dirmi a proposito dell'Abazia?}
{402}{}{Sai nulla a proposito di un Kit di Creazione del Giardino dell'Eden?}
{500}{}{Mi dispiace amico, non ne ho mai sentito parlare. Ma se ha a che fare con i tempi pre-guerra, scommetto che ci sia qualcosa
 nei computer del monastero. Purtroppo per te, quei monaci sono molto protettivi delle loro informazioni -- temono che possa
 portare a un'altra guerra o qualcosa del genere se la gente impara troppo. Potrebbe comunque valere la pena chiedere li'.}
{501}{}{Thanks, I'll go do that. I've got some more questions though.}
{502}{}{Thanks for the tip. I'll go check that out right now.}
{600}{}{Ti ha mandato Fratello Samuel? Cosa sta combinando quel ubriacone adesso?}
{601}{}{A badare alle tombe come al solito, suppongo. Quindi riguardo a cio' che hai sentito...}
{602}{}{[John si siede sulla sedia e si versa un bicchierino di whiskey.] E' iniziato tutto un paio di giorni fa. Mia moglie ed
 io ci stavamo preparando per andare a letto quando abbiamo sentito dei fruscii nel campo. Ho preso la lanterna e sono corso fuori per vedere se
 riuscivo a trovare la fonte del rumore. Non appena sono arrivato ai campi pero', i rumori si erano fermati.}
{603}{}{Continua.}
{604}{}{Look, I really must be going.}
{605}{}{Be', la notte seguente non abbiamo sentito nulla. Ma la notte dopo ancora, abbiamo sentito di nuovo dei fruscii provenire dal campo.
 Questa volta mi sono avvicinato alla finestra e ho guardato fuori invece di correre fuori. Scrutando nel buio, ho visto una
 luce fioca, come quella di una vecchia lanterna o qualcosa del genere, muoversi tra i raccolti. Dopo un paio di minuti la luce si e' spostata verso
 il cimitero.}
{606}{}{Volevo uscire e affrontare chiunque -- o qualunque cosa -- fosse, ma mia moglie mi ha convinto a restare dentro e controllare
 la situazione al mattino. Cosi' la mattina dopo, vedo che alcuni dei miei raccolti erano stati mangiati e ci sono impronte fresche
 dappertutto. Ora, non mi dispiace sfamare i poveri, ma non sopporto i ladri.}
{607}{}{Provero' a catturare questo individuo. Forse aspettero' verso mezzanotte e vedro' se riesco a scoprire qualcosa. Be',
 grazie per le informazioni. Stammi bene.}
{608}{}{I'll see what I can do. I have some more questions before I go.}
{609}{}{This story is getting a little too long. Bye.}
{610}{}{Fammi capire bene. Saresti felice di aiutare qualcuno che si aggira intorno a casa tua di notte, ruba i tuoi
 raccolti e cerca di derubare i tuoi morti? Ho incontrato molti pazzi in vita mia, ma tu potresti superarli tutti. E' un miracolo
 che tu sia sopravvissuto cosi' a lungo.}
{611}{}{[Strizza gli occhi, ma riesce a mantenere la calma.] Cosi' facciamo le cose qui all'Abbazia. Se la gentilezza
 ti offende cosi' tanto, ti suggerisco di toglierti dai piedi da casa mia. Non me ne staro' seduto qui a lasciarmi insultare da qualche
 tribale girovago davanti a mia moglie.}
{612}{}{Alright, alright, I'm leaving.}
{613}{}{Ok duro, ora questo "tribale girovago" ti uccide davanti a tua moglie. Poi forse uccido anche lei.
 Cavolo, forse uccido tutti in questo posto del cazzo. Pensavate di potervi nascondere dall'orrore delle Lande?
 Indovina un po', amico mio ingenuo? L'orrore ti ha trovato, e il suo nome e' }
{700}{}{Get the hell outta here.}
{710}{}{Bello rivederti. Tom e' stato di grande aiuto qui. Grazie ancora per aver sistemato tutto. Allora, cosa posso fare per te?}
{6061}{}{Dopo, ho chiesto a Fratello Samuel se fosse successo qualcosa nel cimitero. E' allora che mi ha detto che qualcuno
 aveva iniziato a dissotterrare alcune tombe. A quanto pare, chiunque lo stia facendo non e' abbastanza forte da scavare in una notte sola.
 Direi che e' un vecchio mendicante che spera di dissotterrare qualche tesoro. Se mai scopri chi sta facendo questo, digli di
 passare da me. Non c'e' bisogno di rubare qui all'Abbazia e sarei felice di aiutare questa persona in qualsiasi modo io possa.}
