{100}{}{Vedi un contadino.}
{101}{}{Vedi un contadino dall'aspetto sano.}
{102}{}{Vedi una persona.}
{103}{}{Hai bevuto troppo alcol ultimamente?}
{104}{}{Stai lontano dall'alcol per un po'.}
{105}{}{Vedo che hai bevuto il mix "speciale" di Hank.}
{106}{}{Benvenuto, eroe!}
{107}{}{Hai fatto vedere a quei bastardi dell'Enclave!}
{108}{}{Sei davvero un eroe!}
{109}{}{Ho sentito dire che hai distrutto l'Enclave, ben fatto!}
{110}{}{Salve.}
{111}{}{Spero che inizi a piovere presto, o i miei raccolti non sopravviveranno.}
{112}{}{Non riceviamo molti visitatori qui.}
{113}{}{Benvenuti!}
{114}{}{Si', lo so. E' abbastanza noioso qui, ma almeno siamo al sicuro dai predoni e simili...}
{115}{}{Ciao, selvaggio.}
{116}{}{Che giornata calda oggi!}
{117}{}{Good farming grounds here...}
{118}{}{Buona giornata.}
{119}{}{Welcome to the Abbey, wanderer!}
{120}{}{Impressionante monastero quello che abbiamo qui, eh?}
{200}{}{Toglimi quelle fottute mani di dosso!}
