{100}{}{Vedi una pompa dell'acqua.}
{101}{}{Vedi una pompa dell'acqua molto vecchia che sembra rotta.}
{102}{}{La pompa dell'acqua funziona bene adesso.}
{103}{}{Per riparare questa macchina avrai bisogno di piu' delle sole mani. Forse degli attrezzi aiuterebbero ad installare
 questo pezzo.}
{104}{}{Hai riparato la pompa dell'acqua.}
{105}{}{Non sei riuscito a riparare la pompa.}
{106}{}{Hai scoperto cosa c'e' che non va nella pompa dell'acqua.}
{200}{}{Apri la macchina e guardi dentro. Vedi molti ingranaggi e motori arrugginiti. Uno dei motori
 ha una crepa.}
{201}{}{Smetti di giocare.}
{202}{}{Indaga ulteriormente.}
{203}{}{A un esame piu' attento vedi che la crepa non e' la causa del problema, ma piuttosto
 il collegamento dove vanno i cavi. I connettori sembrano essersi bruciati nel corso degli anni di utilizzo. Ci vorra'
 un motore completamente nuovo e un nuovo set di cavi per far funzionare di nuovo questa macchina.}
{204}{}{Esci.}
