{100}{}{You see a waterpump.}
{101}{}{You see a really old waterpump that appears to be broken.}
{102}{}{The waterpump is working fine now.}
{103}{}{Per riparare questa macchina avrai bisogno di piu' delle sole mani. Forse degli attrezzi aiuterebbero ad installare
 questo pezzo.}
{104}{}{You repaired the waterpump.}
{105}{}{You failed to repair the pump.}
{106}{}{You find out what is wrong with the water pump.}
{200}{}{Apri la macchina e guardi dentro. Vedi molti ingranaggi e motori arrugginiti. Uno dei motori
 ha una crepa.}
{201}{}{Smetti di giocare.}
{202}{}{Investigate more.}
{203}{}{A un esame piu' attento vedi che la crepa non e' la causa del problema, ma piuttosto
 il collegamento dove vanno i cavi. I connettori sembrano essersi bruciati nel corso degli anni di utilizzo. Ci vorra'
 un motore completamente nuovo e un nuovo set di cavi per far funzionare di nuovo questa macchina.}
{204}{}{Esci.}
