{100}{}{You see the monastery graveyard keeper.}
{101}{}{You see Brother Samuel, the graveyard keeper.}
{102}{}{Sembra ubriaco e un po' assonnato.}
{200}{}{*hic* Oh, s-salve, mi chiamo Samuel. Cosa, eh, *hic* ti porta qui?}
{201}{}{*hickup* Hello again.}
{202}{}{I'm just looking around. Do you tend to this graveyard?}
{203}{}{Do you know a Father Tully?}
{204}{}{Padre Tully, dici? [Sembra stia scavando nella memoria cercando di ricordare.] Si'... io *hic* mi ricordo di Tully.
 Come sta quel tipo? Non lo vedo da quando e' stato cacciato via di qui tanto *hic* tanto tempo fa.
 [Sorride ebbro mentre riflette.] Accidenti era un mattacchione. Lui ed io insieme, *hic* che coppia.}
{205}{}{Vive a New Reno adesso, a predicare la buona parola, ehm, qualcosa del genere. Sai, voi due sembrate molto simili.}
{206}{}{New Reno, eh? [Si appoggia alla pala, tira fuori una fiaschetta e fa un lungo sorso.] Mi ricordo che diceva che sarebbe
 *hic* andato da quella parte. Sono contento che ci sia arrivato sano e salvo. Ho sempre *hic* voluto bene a quel tipo. Un vero mattacchione. Se
 lo rivedi, digli che il Vecchio Sammy e' ancora vivo e vegeto.}
{207}{}{I'll do that. I got some other questions though.}
{208}{}{I'll do that. Take care Sam.}
{209}{}{Come non detto. Scusa il disturbo.}
{210}{}{In realta' volevo solo dirti che ti manda i suoi saluti. Mi assicurero' di dirgli che lo saluti anche tu. Ho ancora qualche altra domanda pero'.}
{211}{}{In realta' volevo solo dirti che ti manda i suoi saluti. Mi assicurero' di dirgli che lo saluti anche tu. Stammi bene Sam.}
{300}{}{What do you *hickup* wanna know?}
{301}{}{Are you the gravekeeper?}
{302}{}{Cosa puoi dirmi a proposito dell'Abazia?}
{303}{}{Posso aiutarti in qualcosa?}
{400}{}{Si', *hic* mi occupo di queste tombe. Nessun altro vuole *hic* farlo, quindi il Vecchio Sammy si e' preso il lavoro. Non e'
 cosi' brutto come si potrebbe pensare. Ha i suoi... vantaggi, se capisci cosa intendo. [Ti sorride sbavando e agita i suoi folti
 sopracciglia.]}
{401}{}{No. I don't know what you mean, and I never want to. Bye.}
{402}{}{No. I don't know what you mean. But I think I'd rather ask you something else. }
{403}{}{No. I don't know what you mean, but I'm morbidly curious...}
{404}{}{Certo che capisco. Niente mi eccita come un cadavere marcio.}
{410}{}{Be', posso stare all'aperto, e non c'e' nessuno intorno a dire al Vecchio Sammy quando ne ha avuto abbastanza. Io *so* quando ne ho
 avuto abbastanza... quando non ce n'e' piu'! [Ride sguaiatamente, il che si trasforma rapidamente in una tosse orribile. Dopo aver tossito
 un polmone o due, ti sorride.]}
{411}{}{Oh, of *course* that's what you meant. [Sigh of relief.] Let me ask you something else, though.}
{420}{}{[I suoi occhi si spalancano per lo shock e sembra istantaneamente sobrio.] Non e' quello che intendevo, tu... tu MOSTRO! DEMONIO!
 Vattene da me! }
{421}{}{Come vuoi, vecchio ubriacone del cazzo. Non sai cosa ti perdi.}
{430}{}{Demonio immondo! Via da qui!}
{500}{}{L'Abbazia, be', questo posto *hic* e' stata la mia casa per la maggior parte della mia vita. Tutti qui *hic* sono gentili, e
 chiunque e' benvenuto, purche' *hic* non causi problemi. Io stesso non passo molto tempo nel
 mona-*hic*-monastero, ma so che i nostri computer hanno ogni tipo di informazione raccolta nel corso degli anni. Forse
 qualcosa *hic* potrebbe esserti utile.}
{501}{}{Non passi molto tempo in chiesa? Sei un monaco, no?}
{502}{}{[Sorride, rivelando una serie di denti marci con molti buchi.] Be', *hic* diciamo solo che gli altri monaci non
 vedono *hic* di buon occhio le mie, ehm, abitudini col bere.}
{503}{}{Makes sense I guess. I got some more questions.}
{504}{}{I guess so. See you around Sammy.}
{505}{}{I see. Look I must be going.}
{600}{}{Hmm... *hic* lasciami... lasciami pensare un attimo. Si', potrei avere qualcosa, se te la senti.}
{601}{}{Uh, nevermind Sam. I must be going now.}
{602}{}{Sure Sam, what do you need?}
{603}{}{Be', negli ultimi giorni ho *hic* notato che alcune di queste tombe vengono scavate. Ora, chiunque lo stia facendo
 non sembra andare molto lontano, ma e' una *hic* una seccatura per me riempirle di nuovo.}
{604}{}{Hmm, hai provato a scoprire chi sta facendo questo?}
{605}{}{Certo *hic* che ho provato. Una notte sono rimasto fino a mezzanotte circa e non si e' presentato nessuno. Devo essermi addormentato
 poco dopo. Troppo bere suppongo. [Sorride, tira fuori la fiaschetta e fa un lungo sorso.] Allora, cosa *hic*
 dici? Vuoi dare una mano?}
{606}{}{Alright, I'll see what I can do. Do you know anything else that might help me?}
{607}{}{Be', ora che lo menzioni, mi *hic* ricordo che il Sig. Peterson diceva qualcosa di aver sentito dei rumori provenire
 dal suo campo. Potrebbe sapere qualcosa. Lui e la sua bella mogliettina vivono proprio la'.
 [Indica l'edificio a sud del cimitero.]}
{608}{}{Vedro' di fare il possibile.}
{609}{}{I think I'll pass. I must be going.}
{700}{}{I took care of the grave digging situation. You shouldn't have any more problems out here.}
{701}{}{Be', questa e' *hic* una buona notizia. Contento di non cadere piu' in tombe aperte *hic*. Grazie per l'aiuto.}
{702}{}{Glad to help. I got some questions though.}
{703}{}{Well, take care then.}
{704}{}{Non credo che le tombe aperte siano il vero motivo per cui cadi, Samuel, ma prendila con calma adesso.}
{1000}{}{*Whistle*}
{1001}{}{*Cough* *Cough*}
{1002}{}{*Si schiarisce la voce*}
{1003}{}{*Cough*}
{1004}{}{*Sigh*}
{1005}{}{*Hic*}
{2000}{}{It's been a *hickup* long day. Come back in th' morning.}
