{100}{}{Vedi il custode del cimitero del monastero.}
{101}{}{Vedi Fratello Samuel, il custode del cimitero.}
{102}{}{Sembra ubriaco e un po' assonnato.}
{200}{}{*hic* Oh, s-salve, mi chiamo Samuel. Cosa, eh, *hic* ti porta qui?}
{201}{}{*hic* Bentornato.}
{202}{}{Sto solo dando un'occhiata. Ti occupi di questo cimitero?}
{203}{}{Conosci un certo Padre Tully?}
{204}{}{Padre Tully, dici? [Sembra stia scavando nella memoria cercando di ricordare.] Si'... io *hic* mi ricordo di Tully.
 Come sta quel tipo? Non lo vedo da quando e' stato cacciato via di qui tanto *hic* tanto tempo fa.
 [Sorride ebbro mentre riflette.] Accidenti era un mattacchione. Lui ed io insieme, *hic* che coppia.}
{205}{}{Vive a New Reno adesso, a predicare la buona parola, ehm, qualcosa del genere. Sai, voi due sembrate molto simili.}
{206}{}{New Reno, eh? [Si appoggia alla pala, tira fuori una fiaschetta e fa un lungo sorso.] Mi ricordo che diceva che sarebbe
 *hic* andato da quella parte. Sono contento che ci sia arrivato sano e salvo. Ho sempre *hic* voluto bene a quel tipo. Un vero mattacchione. Se
 lo rivedi, digli che il Vecchio Sammy e' ancora vivo e vegeto.}
{207}{}{Lo faro'. Ho ancora qualche altra domanda pero'.}
{208}{}{Lo faro'. Prenditi cura di te, Sam.}
{209}{}{Come non detto. Scusa il disturbo.}
{210}{}{In realta' volevo solo dirti che ti manda i suoi saluti. Mi assicurero' di dirgli che lo saluti anche tu. Ho ancora qualche altra domanda pero'.}
{211}{}{In realta' volevo solo dirti che ti manda i suoi saluti. Mi assicurero' di dirgli che lo saluti anche tu. Stammi bene Sam.}
{300}{}{Cosa *hic* vuoi sapere?}
{301}{}{Sei il custode del cimitero?}
{302}{}{Cosa puoi dirmi a proposito dell'Abazia?}
{303}{}{Posso aiutarti in qualcosa?}
{400}{}{Si', *hic* mi occupo di queste tombe. Nessun altro vuole *hic* farlo, quindi il Vecchio Sammy si e' preso il lavoro. Non e'
 cosi' brutto come si potrebbe pensare. Ha i suoi... vantaggi, se capisci cosa intendo. [Ti sorride sbavando e agita i suoi folti
 sopracciglia.]}
{401}{}{No. Non so cosa intendi, e non voglio saperlo. Arrivederci.}
{402}{}{No. Non so cosa intendi. Preferisco chiederti qualcos'altro. }
{403}{}{No. Non so cosa intendi, ma sono morbosamente curioso...}
{404}{}{Certo che capisco. Niente mi eccita come un cadavere marcio.}
{410}{}{Be', posso stare all'aperto, e non c'e' nessuno intorno a dire al Vecchio Sammy quando ne ha avuto abbastanza. Io *so* quando ne ho
 avuto abbastanza... quando non ce n'e' piu'! [Ride sguaiatamente, il che si trasforma rapidamente in una tosse orribile. Dopo aver tossito
 un polmone o due, ti sorride.]}
{411}{}{Oh, *certo* che era quello che intendevi. [Sospiro di sollievo.] Lasciami chiedere qualcos'altro, pero'.}
{420}{}{[I suoi occhi si spalancano per lo shock e sembra istantaneamente sobrio.] Non e' quello che intendevo, tu... tu MOSTRO! DEMONIO!
 Vattene da me! }
{421}{}{Come vuoi, vecchio ubriacone del cazzo. Non sai cosa ti perdi.}
{430}{}{Demonio immondo! Via da qui!}
{500}{}{L'Abbazia, be', questo posto *hic* e' stata la mia casa per la maggior parte della mia vita. Tutti qui *hic* sono gentili, e
 chiunque e' benvenuto, purche' *hic* non causi problemi. Io stesso non passo molto tempo nel
 mona-*hic*-monastero, ma so che i nostri computer hanno ogni tipo di informazione raccolta nel corso degli anni. Forse
 qualcosa *hic* potrebbe esserti utile.}
{501}{}{Non passi molto tempo in chiesa? Sei un monaco, no?}
{502}{}{[Sorride, rivelando una serie di denti marci con molti buchi.] Be', *hic* diciamo solo che gli altri monaci non
 vedono *hic* di buon occhio le mie, ehm, abitudini col bere.}
{503}{}{Ha senso, immagino. Ho ancora qualche domanda.}
{504}{}{Suppongo di si'. A presto, Sammy.}
{505}{}{Capisco. Senti, devo proprio andare.}
{600}{}{Hmm... *hic* lasciami... lasciami pensare un attimo. Si', potrei avere qualcosa, se te la senti.}
{601}{}{Ah, lascia perdere Sam. Devo andare adesso.}
{602}{}{Certo Sam, cosa ti serve?}
{603}{}{Be', negli ultimi giorni ho *hic* notato che alcune di queste tombe vengono scavate. Ora, chiunque lo stia facendo
 non sembra andare molto lontano, ma e' una *hic* una seccatura per me riempirle di nuovo.}
{604}{}{Hmm, hai provato a scoprire chi sta facendo questo?}
{605}{}{Certo *hic* che ho provato. Una notte sono rimasto fino a mezzanotte circa e non si e' presentato nessuno. Devo essermi addormentato
 poco dopo. Troppo bere suppongo. [Sorride, tira fuori la fiaschetta e fa un lungo sorso.] Allora, cosa *hic*
 dici? Vuoi dare una mano?}
{606}{}{Bene, vedro' cosa posso fare. Sai qualcos'altro che potrebbe aiutarmi?}
{607}{}{Be', ora che lo menzioni, mi *hic* ricordo che il Sig. Peterson diceva qualcosa di aver sentito dei rumori provenire
 dal suo campo. Potrebbe sapere qualcosa. Lui e la sua bella mogliettina vivono proprio la'.
 [Indica l'edificio a sud del cimitero.]}
{608}{}{Vedro' di fare il possibile.}
{609}{}{Lascio perdere. Devo andare.}
{700}{}{Mi sono occupato della situazione con gli scavatori di tombe. Non dovresti avere altri problemi qui.}
{701}{}{Be', questa e' *hic* una buona notizia. Contento di non cadere piu' in tombe aperte *hic*. Grazie per l'aiuto.}
{702}{}{Contento di aver aiutato. Ho ancora qualche domanda pero'.}
{703}{}{Bene, prenditi cura di te allora.}
{704}{}{Non credo che le tombe aperte siano il vero motivo per cui cadi, Samuel, ma prendila con calma adesso.}
{1000}{}{*Fischio*}
{1001}{}{*Tosse* *Tosse*}
{1002}{}{*Si schiarisce la voce*}
{1003}{}{*Tosse*}
{1004}{}{*Sospiro*}
{1005}{}{*Hic*}
{2000}{}{E' stata una giornata *hic* lunga. Torna domattina.}
