{100}{}{Vedi un vecchio curvo.}
{101}{}{Il vecchio decrepito puzza di sudore e probabilmente di urina. E' vestito con stracci sdruciti e infangati, e porta una pala.}
{102}{}{Vedi Tom.}
{200}{}{[Il vecchio trasalisce di sorpresa quando ti vede avvicinarti.] Eh, senti, devo proprio andare...}
{201}{}{Aspetta un momento. [Afferri l'uomo per un braccio mentre comincia ad allontanarsi.] Chi sei, e cosa stai
 facendo qui a quest'ora?}
{202}{}{Cosa? Be', ehm... mi chiamo Tom e un vecchio non puo' piu' godersi una passeggiata notturna senza essere tempestato di
 domande?}
{203}{}{Non quando se ne va in giro come un ladro e porta una pala.}
{204}{}{Va bene, ma perche' porti una pala?}
{205}{}{Come vuoi, me ne vado.}
{206}{}{Come non detto. Scusa il disturbo.}
{207}{}{Intendi questo vecchio arnese? [Abbassa lo sguardo sulla pala arrugginita tra le mani.] Be', ehm, non si sa mai quando
 potresti trovare qualcosa che ha bisogno di essere scavato. Bisogna essere sempre pronti, dico io.}
{208}{}{Trovare qualcosa, eh? Intendi tipo qualcosa in una tomba?}
{209}{}{E' davvero un buon motto. Bene, prenditi cura di te.}
{210}{}{(Gli occhi di Tom si spalancano) Non sono del tutto sicuro di cosa, ehm, intendi.}
{211}{}{Tom, sei in un cimitero, sei coperto di fango e sono passate la mezzanotte. Persino Torr potrebbe trarre una
 conclusione da questo. E' ora di darmi qualche risposta, Tom. Perche' stai dissotterrando queste tombe?}
{212}{}{[Posa la pala e sospira.] Va bene, te lo dico. Il mio corpo non e' piu' quello di una volta. Non ho lavoro,
 e nessun modo concreto per procurarmi del cibo. So che dissotterrare tombe non e' una cosa che la gente vede di buon occhio, ma e' stato un modo per
 racimolare qualche soldo. Sto solo cercando di sopravvivere... non voglio fare del male a nessuno.}
{213}{}{Non credo che dissotterrare tombe faccia bene a un uomo nelle tue condizioni. Senti. Vattene tranquillamente
 da qui e faremo finta che questa conversazione non sia mai avvenuta. Non voglio piu' vedere la tua faccia pero', chiaro?}
{214}{}{[Il vecchio sembra sul punto di protestare, poi si ferma.] Va bene, hai vinto. Non vedrai piu' il povero vecchio Tom.
 [Raccoglie la pala e si allontana trascinando i piedi.]}
{215}{}{Ripensandoci, forse il mondo starebbe meglio se ti ammazzassi.}
{216}{}{Arrivederci, Tom.}
{217}{}{Ho sentito che stavi anche rubando i raccolti al contadino qui.}
{218}{}{[Il vecchio si agita a disagio.] Non potevo farne a meno! Avevo cosi' tanta fame e il cibo sembrava cosi' buono. Per favore,
 non voglio causare problemi. Senti, me ne vado e non mi vedrai piu' qui. Lo prometto!}
{219}{}{Bene, muoviti allora. Prima che cambi idea.}
{220}{}{Aspetta, non ce n'e' bisogno. I Peterson sono i proprietari della fattoria qui e sono persone molto gentili. Il Sig. Peterson
 si e' persino offerto di parlare con chiunque stesse prendendo i suoi raccolti per trovare un accordo ragionevole. Va' a parlargli.
 Sono sicuro che possa aiutarti in qualche modo.}
{221}{}{(Gli occhi del vecchio si illuminano.) Non sembra affatto una cattiva idea. Ehi, grazie. Forse questo mondo non e' cosi'
 crudele come pensavo.}
{222}{}{Prenditi cura di te allora, Tom. Controllero' come vanno le cose piu' tardi.}
{223}{}{Spero proprio che quel Peterson sia amichevole come dici tu.}
{300}{}{Vedi Tom. Indossa abiti da lavoro nuovi e fischietta allegramente.}
{301}{}{Ehi! Wow, avevi ragione. Quel Sig. Peterson e' davvero un tipo gentile. Mi ha perdonato per quello che ho fatto e mi ha persino
 offerto un lavoro ad aiutare nei campi. Dice che una volta che avro' ripagato il cibo che ho preso, iniziero' a guadagnare uno
 stipendio settimanale. Grazie ancora per il disturbo.}
{302}{}{Prego, Tom. Prenditi cura di te.}
{303}{}{Va bene, lo fa- Oh, aspetta un secondo. Voglio darti qualcosa per aver aiutato un vecchio come me. Ho trovato questo
 accendino addosso a un ragazzo che ho dissotterrato un paio di settimane fa. A me non serve e sperabilmente potrebbe servirti.}
{304}{}{Grazie, Tom. Sono sicuro che mi tornera' utile. A presto.}
{305}{}{(Il vecchio annuisce e torna a quello che stava facendo.)}
{306}{}{[FINE]}
{307}{}{Rieccomi. Grazie mille di tutto!}
{308}{}{*Fischio*}
{400}{}{Voi giovani non imparate mai. Non sei il mio capo. Penso che ti ammazzero' invece.}
{450}{}{Senti, anch'io ho dissotterrato la mia parte di tombe. Sono un po' cleptomane. Qual e' il tuo motivo?}
{451}{}{Non sono estraneo al dissotterrare tombe, Tom. Ognuno ha i suoi piaceri. Ora vai per la tua strada.}
{1000}{}{Scopri chi sta dissotterrando le tombe e avvii Tom verso una nuova vita.}
{1001}{}{Scopri chi sta dissotterrando le tombe.}
{1002}{}{Me ne vado. Non c'e' bisogno di affrettare un vecchio.}
{1003}{}{Vedi Tom. Ha un sorriso in faccia e indossa dei vestiti da lavoro nuovi.}
{1004}{}{Sembra in condizioni molto migliori e sorride quando ti avvicini.}
