{100}{}{Vedi la guardia del ponte.}
{101}{}{Vedi Mynoc, la guardia del ponte.}
{150}{}{Davanti a te c'e' un possente guerriero del tuo villaggio che impugna una lancia.}
{151}{}{[PARLA]}
{152}{}{Salve, Prescelto. Stai partendo alla ricerca del GECK?}
{153}{}{Si'.}
{154}{}{Si'. Ma prima che io vada, vorrei farti qualche domanda.}
{155}{}{Adesso no. Voglio guardarmi in giro ancora un po'.}
{156}{}{Bene, che gli dei veglino su di te.}
{157}{}{Grazie, arrivederci.}
{158}{}{Cosa vuoi sapere?}
{159}{}{Cosa puoi dirmi degli uomini che commerciano col nostro villaggio?}
{160}{}{Cosa puoi dirmi di questo oggetto che e' stato preso da un Vault?}
{161}{}{Niente, non importa.}
{162}{}{Molto bene, ma non perdere troppo tempo. Senza il GECK, siamo spacciati.}
{163}{}{Lo so, non temere -- Ho tutto sotto controllo.}
{164}{}{Perche'?}
{165}{}{Devo andare. Arrivederci.}
{166}{}{I commercianti? Arrivano da Klamath ogni due mesi circa. Non ne arrivera' un altro per un mese o piu', ma Klamath e' solo pochi giorni a est di qui.}
{167}{}{Grazie. Arrivederci.}
{168}{}{Cosa puoi dirmi di questo oggetto che e' stato preso dal sacro Vault?}
{169}{}{Sembra una fiaschetta di metallo. Forse il Vault ce l'ha spedito come augurio.}
{170}{}{Puoi dirmi chi ha portato questo oggetto al nostro villaggio?}
{171}{}{Grazie. Devo andare. Arrivederci.}
{172}{}{Lo spero.}
{173}{}{La tua eccessiva sicurezza ci fa soffrire tutti! Addio!}
{174}{}{Arrivederci.}
{175}{}{Perche'? Guardati intorno -- il nostro villaggio muore. I campi avvizziscono e ogni giorno ci sono dei bambini e dei vecchi che muoiono. Devi portarci l'Eden prima che sia troppo tardi!}
{176}{}{Ci pensero' io. Arrivederci.}
{177}{}{Io sono il Prescelto -- Io "devo" fare solo cio' che voglio. Addio.}
{178}{}{Non ricordo il suo nome, so solo che era vecchio e rozzo -- troppo rozzo per avere delle buone maniere -- ma sapeva molte cose. Veniva da Klamath. Da est, come ho gia' detto.}
{179}{}{Grazie, arrivederci.}
{180}{}{Sei ancora qui? Devi trovare il GECK. Restando qui non ci aiuti di certo.}
{181}{}{Questo ponte e' l'unica cosa di cui ti devi preoccupare, amico. So badare benissimo a me stesso.}
{182}{}{Stavo appunto per andare. Arrivederci, amico.}
{183}{}{Non parlero' un attimo di piu' con te, porco insubordinato!}
{184}{}{Vorrei farti un'altra domanda.}
{185}{}{Che velocita'! Hai trovato il sacro Vault 13?}
{186}{}{Si'.}
{187}{}{No, non ancora.}
{188}{}{Davvero? Meraviglioso! Hai portato il GECK?}
{189}{}{No.}
{190}{}{No. Non ho ancora parlato con gli abitanti del Vault.}
{191}{}{Non credo che questi siano affari tuoi, amico mio.}
{192}{}{No? Prescelto, tre anziani sono morti da quando sei partito. Non devi sprecare altro tempo.}
{193}{}{Lo trovero', non preoccuparti.}
{194}{}{Mi sto stufando del tuo continuo brontolare.}
{195}{}{Beh, perche' stai parlando con me? Parla con loro, e recupera il GECK.}
{196}{}{Lo faro' -- a tempo debito, amico mio.}
{197}{}{Mi sto stufando del tuo continuo brontolare.}
{198}{}{Che notizie sul GECK, Prescelto?}
{199}{}{Ho trovato il Vault!}
{200}{}{Non sono stato in grado di trovare il Vault 13.}
{201}{}{Ma che sorpresa: il Prescelto.}
{202}{}{Salve.}
{203}{}{Taci.}
{204}{}{Posso farti una domanda?}
{205}{}{No, non ho tempo.}
{206}{}{Vabbe'. Arrivederci.}
{207}{}{Oh bene. Ci si vede.}
{208}{}{Muori.}
{209}{}{Salute, stupidone! Vedere ponte? Tu attraversare, tu stare attento. Ponte pericoloso. Tu non volere cadere. Okay?}
{210}{}{Umm... Hunh?}
{211}{}{Disgraziato! Hai deluso tutto il villaggio!}
{212}{}{Hai tradito la nostra fiducia. Per questo morirai!}
{213}{}{Sei un traditore della tua stessa gente.}
{214}{}{Perche' fai questo?}
{215}{}{L'Anziana si sbagliava. Sei malvagio.}
{300}{}{Mio padre mi ha insegnato come affilare le lance. Portami una selce e affilero' anche la tua. Ti servira', nel deserto.}
{301}{}{Dove posso trovare un po' di questa selce?}
{302}{}{Si dice che tua Zia Morlis ne abbia una provvista. E' cosi' permalosa che non penso che qualcuno gliel'abbia mai chiesta. Di sicuro quella strega vorra' qualcosa in cambio.}
{303}{}{Grazie. Arrivederci.}
{304}{}{Sei riuscito ad ottenere la selce da tua zia?}
{305}{}{Si', ne ho un pezzo proprio qui.}
{306}{}{Non ancora.}
{307}{}{E' un bel pezzo. Dammi la tua lancia.}
{308}{}{Ecco qua.}
{309}{}{Non credo di averne una.}
{310}{}{Ora, metti i pezzi in questo modo...}
{311}{}{Il Prescelto senza una lancia? Beh, dovrai prendere una delle mie. Mettiamoci al lavoro, adesso...}
{312}{}{Ecco la tua nuova lancia.}
{313}{}{Grazie, amico mio -- Questa mi sara' di grande aiuto.}
{314}{}{Si', ma la tua lancia mi incuriosisce. Sembra diversa dalle altre.}
{400}{}{Bentornato a casa, Prescelto! Hai trovato il Vault? Sei tornato con il GECK?}
{401}{}{Me no trovato ancora.}
{402}{}{No, non l'ho ancora trovato.}
{403}{}{Non sono in vena di rispondere alle tue domande. Addio.}
{404}{}{Le cose non vanno bene, Prescelto. La siccita' non ci da' tregua e i raccolti verranno sicuramente distrutti. Stiamo raccogliendo il possibile per creare delle scorte alimentari.}
{405}{}{Perche' non commerciare con altri villaggi?}
{406}{}{Io fa mio meglio. Me trova GECK. Me ritorna.}
{407}{}{Perche' non commerciare con altri villaggi per il cibo che ci serve? }
{408}{}{Faccio del mio meglio. Quando avro' trovato il GECK, tornero'.}
{409}{}{Siamo gente semplice e abbiamo poco da offrire in uno scambio commerciale. I pochi paesi che abbiamo contattato mentre eri via non hanno mostrato alcun interesse ad aiutarci.}
{410}{}{Me capisce.}
{411}{}{Capisco.}
{412}{}{Sei la nostra unica speranza, Prescelto. Per favore, non deluderci!}
{413}{}{E' bello vederti, Prescelto. Come va la tua missione?}
{414}{}{Me ancora cerca.}
{415}{}{La sto ancora cercando.}
{416}{}{Non ho voglia di parlarne.}
{417}{}{Devi sbrigarti. Qui le cose vanno sempre peggio. Presto ci sara' poco cibo e l'Anziana sta pensando di razionare quello che abbiamo. Temo per il futuro di Arroyo.}
{418}{}{Prescelto! Per favore, dimmi che hai portato a termine la tua missione. Il nostro villaggio sta morendo, cosi' come la nostra gente.}
{419}{}{No, me ancora cercare.}
{420}{}{No, sto ancora cercando.}
{421}{}{Come vanno le cose?}
{422}{}{Mi spiace, Prescelto, ma inizio a dubitare della mia fede in te. Le vite della nostra gente sono nelle tue mani. Per favore: trova il sacro Tredici e torna da noi con il GECK!}
{423}{}{I raccolti sono distrutti, i brahmin muoiono, tutti sono affamati. I pianti dei bambini, di notte, non consentono a nessuno di dormire. Siamo disperati.}
{424}{}{Me continua a cercare.}
{425}{}{Faro' quel che posso.}
{426}{}{Ancora una volta torni da noi, Prescelto. Non a mani vuote, vero?}
{427}{}{Me spiacente, no trovato GECK ancora.}
{428}{}{Mi dispiace, non ho ancora trovato il GECK.}
{429}{}{Ne ho abbastanza.}
{430}{}{Mentre tu passeggi per le lande, qui la nostra gente muore. Forse dovresti cercare da qualche altra parte invece che tornare qui.}
{500}{}{Hai gia' parlato con l'Anziana?}
{600}{}{Hai qualche consiglio finale per me prima che mi avventuri nell'ignoto?}
{601}{}{Certamente. Guardati dalle armi degli Estranei. Il morso del gecko non e' nulla rispetto al potere distruttivo dei loro bastoni-tuono.}
{602}{}{Got it. Anything else?}
{603}{}{Non dare la tua fiducia liberamente. L'onore significa molto poco nelle Lande. Resta vigile e metti sempre in dubbio le motivazioni degli altri.}
{604}{}{Sure thing. Is that all?}
{605}{}{Non dimenticare mai le tue radici. Il mondo fuori dal nostro villaggio e' pieno di giocattoli luccicanti e lussi che potrebbero far sembrare la nostra vita qui ad Arroyo semplice e banale.
 Ma ricorda che lo stile di vita degli Estranei produce uomini malvagi dominati dall'avidita' e dalla corruzione. Stai attento a non diventare come Colui-Che-Non-Deve-Essere-Nominato.}
{606}{}{I'll never forget my roots. Thanks for the advice, Mynoc.}
{607}{}{Colui-Che-Non-Deve-Essere-Nominato? Ehm... chi?}
{608}{}{Sei cosi' ubriaco della gloria di essere il Prescelto da aver dimenticato... [Mynoc si guarda velocemente intorno per assicurarsi che nessuno stia ascoltando, poi si sporge in avanti e abbassa la voce fino a un sussurro.] ... Kaga?}
{609}{}{Oh! Si', quel tipo. Faro' in modo di non finire come lui. Grazie.}
{610}{}{Oh, e' quello che pensavo intendessi. Ma, ehm, perche' non mi racconti di nuovo la sua storia. Adoro davvero quella storia.}
{611}{}{[Mynoc borbotta qualcosa tra se' e se' e scuote la testa prima di iniziare il racconto.] Come dovresti sapere, era un tempo il piu' grande guerriero della nostra tribu'. Ha guidato molte spedizioni nel mondo esterno, ed e' li' che la corruzione ha iniziato ad avvelenare la sua mente.}
{612}{}{Si infatuo' dei modi degli Estranei, dove il potere poteva portare a chiunque grande rispetto e lusso. Comincio' a considerarsi superiore ai suoi compagni di tribu' che erano contenti di vivere una vita piu' semplice.}
{613}{}{What a jerk.}
{614}{}{Continua.}
{615}{}{Quando la nostra tribu' cadde in questi tempi difficili, si ritenne il salvatore del nostro popolo ed entro' nel Tempio delle Prove per dimostrare di essere il Prescelto.}
{616}{}{Continua.}
{617}{}{Nevermind, I don't want to hear this story anymore. Bye.}
{618}{}{Si fece strada attraverso il Tempio, raggiungendo rapidamente la prova finale: un combattimento corpo a corpo con un altro guerriero.}
{619}{}{Continua.}
{620}{}{Aspetta, ha fatto saltare quella porta e tutto il resto? Lo facciamo ricostruire ogni volta che qualcuno attraversa il tempio? A proposito, chi ha costruito il tempio in primo luogo?}
{621}{}{Non ho tempo di rispondere a tutte le tue domande stupide. Vuoi che finisca il racconto, o no?}
{622}{}{Sorry. Please continue.}
{623}{}{Actually, I think I'm ready to go. See you around.}
{624}{}{Durante la prova finale, Colui-Che-Non-Deve-Essere-Nominato sfodero' una lama nascosta e la uso' per uccidere il suo avversario. Quando l'Anziano lo confronto' sul disonorevole uso di un'arma nascosta, sostenne che non era barare, ma piuttosto che dimostrava di essere un guerriero astuto.}
{625}{}{L'Anziano non era d'accordo. Colui-Che-Non-Deve-Essere-Nominato fu esiliato a forza dalla nostra tribu' e il suo nome non doveva essere mai piu' pronunciato tra noi. Mentre veniva scacciato nelle Lande, giuro' un voto di vendetta. Vendetta contro la nostra tribu', e specialmente contro di te.}
{626}{}{Me? What'd I do?}
{627}{}{Thanks for the story, but I'd best be on my way now.}
{628}{}{Tu sei il Prescelto, un titolo che lui ritiene essere giustamente suo. Il suo orgoglio non gli permettera' di lasciarti vivere.}
{629}{}{Non mi preoccupero' di questo. E' probabilmente morto nelle Lande ormai, comunque.}
{630}{}{Staro' in guardia. Sperabilmente e' morto nelle Lande ormai.}
{631}{}{Ascolta e capisci. Colui-Che-Non-Deve-Essere-Nominato e' la' fuori. Non si puo' trattare con lui. Non si puo' ragionare con lui. Non provera' pieta', ne' rimorso, ne' paura. E non si fermera' assolutamente mai, finche' non sarai morto.}
{632}{}{Sai, penso che tu stia esagerando un po' con il melodramma. Comunque, grazie per il consiglio. Ci vediamo in giro, Mynoc.}
{633}{}{I'll keep that in mind. Take care, Mynoc.}
{640}{}{Could you tell me anything about this Kaga guy?}
{641}{}{[I suoi occhi si spalancano e si guarda intorno nervosamente come se si aspettasse di essere colpito all'improvviso da un fulmine.] Hai perso il senno nelle Lande?! Dovresti sapere che non si deve pronunciare il nome del reietto! Deve essere indicato solo come Colui-Che-Non-Deve-Essere-Nominato.
 Il nostro villaggio soffre abbastanza senza attirare l'ira degli Dei su di noi. [Alza gli occhi nervosamente verso il cielo.]}
{642}{}{Mi dispiace, Mynoc. Ma ti dispiacerebbe raccontarmi ancora la storia di Ka... voglio dire, di "Colui-Che"? Adoro davvero quella storia.}
{643}{}{Sai, avevo dimenticato quanto stupidamente superstiziosa potesse essere la vostra gente. Ci vediamo in giro.}
{650}{}{L'ho gia' affrontato, quindi sono sicuro di poterlo gestire se le nostre strade si incroceranno di nuovo.}
{651}{}{In realta', e' gia' morto. Ho lasciato il suo cadavere la' fuori a marcire nelle Lande.}
{660}{}{[Mynoc annuisce cupamente.] Potrebbe essersi allontanato dal cammino, ma era un tempo un grande e rispettato guerriero. Spero che la sua anima tormentata abbia trovato pace nell'altro mondo.}
{661}{}{Indeed. I'll see you around, Mynoc.}
{662}{}{Whatever. He seemed like an asshole to me. I'll see you around, Mynoc.}
{1000}{}{Elder}
{1001}{}{Founder}
{1002}{}{Vault Dweller}
{1003}{}{Arroyo}
{1004}{}{Klamath}
{1005}{}{Vault}
{1006}{}{Chosen One}
{1007}{}{Shaman}
{1008}{}{Hakunin}
{1009}{}{Healing Powder}
{1010}{}{Bridge}
{1011}{}{Mynoc}
{1100}{}{The Elder is your mother and our leader.}
{1101}{}{Our great ancestor who gave us knowledge.}
{1102}{}{The first to fight and win over chaos.}
{1103}{}{That would be our beautiful village.}
{1104}{}{E' un avamposto commerciale a pochi giorni a est di qui.}
{1105}{}{The Vault is heaven.}
{1106}{}{You are the Chosen One.}
{1107}{}{Egli ci cura con le sue erbe e con la magia. Si trova nella zona nord del villaggio.}
{1108}{}{Egli ci cura con le sue erbe e con la magia. Si trova nella zona nord del villaggio.}
{1109}{}{E' una polvere magica che ti guarisce, ma che ti intorpidisce.}
{1110}{}{The Great Bridge exits our village in the south.}
{1111}{}{Si tratta di me.}
