{100}{}{Vedi un piccolo terminale di computer.}
{101}{}{Vedi il terminale del computer dell'Abbazia.}
{102}{}{Vedi un piccolo terminale di computer. Sembra essere funzionante.}
{103}{}{Accedi al computer e passi in rassegna tutti i file disponibili. Trovi alcuni file contenenti le parole chiave "G.E.C.K." e "Vault".}
{104}{}{Leggi informazioni GECK.}
{105}{}{Leggi le informazioni sul Vault.}
{106}{}{ERRORE! Tessera di accesso non trovata. Inserire la tessera di accesso nell'apposito slot.}
{107}{}{(Inserisci la tessera di accesso nello slot) BIP!, tessera di accesso accettata. CARICAMENTO Winblows 2075......FATTO.}
{108}{}{Inserisci un comando.}
{109}{}{Scansiona i file per informazioni su GECK o VAULT 13.}
{110}{}{Accedi ad altri file.}
{111}{}{Gioca a Morra Cinese.}
{112}{}{Indietro.}
{113}{}{Esci.}
{114}{}{[CONTINUA]}
{115}{}{Trovi alcuni file contenenti le parole chiave "GECK" e "Vault".}
{116}{}{Sfoglia i file riguardanti il "GECK".}
{117}{}{Sfoglia i file riguardanti il "Vault".}
{118}{}{Il programma di ricerca sembra essere un po' troppo difficile per te.}
{119}{}{I tuoi occhi si spalancano e il tuo cuore accelera quando scopri quella che sembra essere una vecchia pubblicita' per un Garden of Eden
 Creation Kit. La pubblicita' raffigura un personaggio dei cartoni animati sorridente in una tuta da vault che regge una grande custodia con scritto "Kit di Sopravvivenza". E'
 quasi come se il bastardo sorridente ti stesse prendendo in giro.}
{120}{}{Sfoglia i file, che contengono per lo piu' propaganda governativa su quanto sarebbe stata meravigliosa la vita nei Vault.
 Scopri che a meta' del XXI secolo, il governo degli Stati Uniti commissiono' alla Vault-Tec la costruzione di 122 Vault in tutti gli Stati Uniti.
 Questi Vault erano destinati a fungere da rifugi per un massimo di 1.000 cittadini americani in caso di olocausto nucleare. All'interno dei confini sicuri
 dei Vault sotterranei, gli Abitanti del Vault avrebbero potuto vivere un'esistenza lussuosa in attesa del segnale che li informasse che
 il mondo in superficie era di nuovo abitabile.}
{121}{}{Mentre cerchi nel sistema trovi centinaia di libri e riviste digitalizzati catalogati sull'hard drive. Non sapresti
 nemmeno da dove iniziare a cercare qualcosa di utile.}
{122}{}{Mentre cerchi nel sistema trovi centinaia di libri e riviste digitalizzati catalogati sull'hard drive. Dato che
 sei esperto di come vengono solitamente archiviate le informazioni, forse cercare per argomento potrebbe darti qualcosa di utile.}
{123}{}{[AVANTI]}
{124}{}{Secondo la pubblicita', il kit include un "Replicatore di Base", che "replica cibo e oggetti fondamentali necessari per costruire
 il tuo nuovo mondo", un "Lettore di Holodisc con Biblioteca", che "include selezioni dalla Biblioteca del Congresso, enciclopedie complete,
 e altre informazioni salvavita, contenute in quattrocentosessanta pratici holodisc!" e contiene persino una "Penna Torcia Tascabile!"
 Sicuramente, questo miracoloso dispositivo e' esattamente cio' di cui hai bisogno per salvare il tuo villaggio morente.}
{125}{}{Leggi altro.}
{126}{}{Continui a sfogliare i file, ma l'unica menzione che trovi del Vault 13 afferma semplicemente che si trova in California,
 il che non ti aiuta molto.}
{130}{}{Aggiungi informazioni.}
{131}{}{[Non hai nulla da aggiungere.] Indietro.}
{132}{}{Inserisci informazioni di Botanica.}
{133}{}{Inserisci informazioni [Blah].}
{140}{}{Leggi il file Guida/Informazioni.}
{141}{}{Congratulazioni per aver installato con successo Winblows 2075! Questa versione e' la piu' avanzata di Winblows fino ad oggi.
 Con la probabilita' confermata di un solo crash per milione di chiamate di funzione, i nostri tecnici sono certi che Winblows sia perfetto
 per qualsiasi ambiente aziendale. La novita' di Winblows 2075 e' una base di codice migliorata che ora spreca solo il 15%
 dei cicli CPU in amministrazione in background, rispetto alle versioni precedenti che ne sprecavano fino al 25%.
 Naturalmente, molta attenzione e' stata dedicata all'utente in questa ultima versione. Come nelle versioni precedenti di Winblows, i comandi
 comuni di Cerca, Aggiungi, Sposta, Elimina e Formatta sono disponibili per l'utente.}
{142}{}{Formatta il file system, inclusi tutti i database di backup sull'host e sulle macchine in rete.}
{143}{}{Indietro.}
{144}{}{Formattazione database di backup... COMPLETATA... Formattazione file system corrente... ATTESA... Attenzione: si e' verificato un errore catastrofico.
 Attendere prego...}
{145}{}{Aspetta.}
{146}{}{...Errore di Sistema: L'operazione e' stata completata con successo...(Un suono stridulo inizia a provenire dall'interno del computer e da quelli vicini.}
{147}{}{[Allontanati.]}
{148}{}{Errore: Nessuna tastiera trovata. Premere un tasto qualsiasi per riavviare.}
{150}{}{Caricamento disco informazioni di Botanica dell'Agenzia per la Protezione Ambientale... Caricamento completato. Buona giornata.}
{200}{}{Sasso, Carta, Forbice V.0.3. Seleziona un'opzione.}
{201}{}{Scegli SASSO.}
{202}{}{Scegli CARTA.}
{203}{}{Seleziona FORBICE.}
{204}{}{Torna al menu principale.}
{205}{}{Il terminale fa la sua scelta.....Calcolo.....Il terminale vince!}
{206}{}{Il terminale fa la sua scelta.....Calcolo.....L'utente vince!}
{207}{}{Il terminale fa la sua scelta.....Calcolo.....Pareggio!}
{300}{}{(Lo schermo del computer mostra vari schemi di colori.)}
{301}{}{Ohhh! Che bei colori.}
{302}{}{Allontanati.}
{400}{}{Leggi altro.}
{401}{}{Torna al menu.}
{402}{}{Cerca per argomento.}
{403}{}{Inserisci un argomento da cercare.}
{404}{}{Scienza.}
{405}{}{Riparazione.}
{406}{}{Medicina.}
{407}{}{Uso delle armi.}
{408}{}{Argomenti Persuasivi.}
{410}{}{Dopo alcune ore di lettura impari di piu' sull'arte della scienza.}
{411}{}{Dopo alcune ore di lettura impari di piu' sull'arte della riparazione delle macchine.}
{412}{}{Dopo alcune ore di lettura impari di piu' sull'arte della medicina.}
{413}{}{Dopo alcune ore di lettura impari di piu' sull'arte di difendersi con un'arma.}
{414}{}{Dopo alcune ore di lettura impari di piu' sull'arte della persuasione.}
{420}{}{Dopo alcune ore di lettura non impari nulla di nuovo sull'arte della scienza.}
{421}{}{Dopo alcune ore di lettura non impari nulla di nuovo sull'arte della riparazione delle macchine.}
{422}{}{Dopo alcune ore di lettura non impari nulla di nuovo sull'arte della medicina.}
{423}{}{Dopo alcune ore di lettura non impari nulla di nuovo sull'arte di sparare con un'arma da fuoco.}
{424}{}{Dopo alcune ore di lettura non impari nulla di nuovo sull'arte della persuasione.}
{430}{}{Indietro.}
{500}{}{Mentre leggi altri articoli, scopri che il GECK e' stato sviluppato dalla Future-Tec, una divisione della Vault-Tec, e che
 era dotazione standard in tutti i vault della Vault-Tec. Era destinato ad essere usato all'uscita da un Vault, per aiutare a ristabilire la vita
 negli ambienti ostili di un mondo devastato dalla guerra nucleare.}
{501}{}{Leggendo oltre, scopri che il GECK non e' proprio il dispositivo miracoloso che la pubblicita' lasciava intendere. Il "Replicatore di Base"
 non e' altro che un sistema di fertilizzazione contenente semi alimentari, integratori del suolo e sostanze chimiche appositamente progettate per
 trasformare le aride Lande in terreno fertile. L'affermazione che possa "costruire oggetti di base" allude in realta' ai nuovi codici che fornisce alle
 macchine del Vault, consentendo loro di creare nuovi oggetti dai distributori. Il GECK contiene anche schemi per campi di forza di base
 e per la costruzione di muri ed edifici in "sabbia-cemento".}
{502}{}{[AVANTI]}
{503}{}{Sembra che il GECK stesso sia destinato a essere smontato nel corso del suo utilizzo. Leggi un esempio di come la sua fonte di energia a fusione fredda
 sia destinata alla produzione di energia per la citta'. Il GECK contiene persino istruzioni per smontare sezioni del
 Vault per creare case e strutture difensive per la nuova comunita'. Mentre finisci di leggere i file, decidi che anche se
 non e' il dispositivo magico che l'Anziana sembra credere, trovare un GECK e' ancora la tua migliore opzione se speri di salvare la tua tribu'.}
{1000}{}{Carichi l'Holodisc di Botanica dell'EPA.}
{2000}{}{Formatti i database di libri dell'Abbazia.}
