{100}{}{Vedi l'Abate, la guida spirituale dell'Abbazia.}
{101}{}{C'e' qualcosa in questo monaco che ti fa credere che sia piuttosto importante.}
{200}{}{Benvenuto, viaggiatore.}
{201}{}{La pace sia con te.}
{202}{}{Noi siamo i custodi della conoscenza.}
{203}{}{Mi dispiace, ma la conoscenza dei nostri libri non ti e' di alcuna utilita'.}
{300}{}{Benvenuto all'Abbazia, viaggiatore. Come posso aiutarti?}
{301}{}{Cosa puoi dirmi a proposito del vostro ordine?}
{302}{}{Ha mai sentito parlare di un dispositivo chiamato G.E.C.K.?}
{303}{}{Sa dove potrei trovare il Vault 13?}
{304}{}{Addio.}
{400}{}{Cosa vuoi sapere?}
{401}{}{Capito. Vorrei sapere qualcos'altro.}
{402}{}{Hmm... *sembra* familiare. Ebbene si', ricordo che Fratello Thomas ha menzionato qualcosa a riguardo di recente. Mi dispiace, ma non ricordo esattamente cosa ha detto.}
{403}{}{Va bene. Indicami solo Fratello Thomas e vado a chiedergli.}
{404}{}{Non ne so nulla.}
{405}{}{Va bene, grazie lo stesso.}
{406}{}{Temo di non poterlo fare. Vedi, ho l'impressione che Fratello Thomas non sia piu' tra i vivi. Ma, fortunatamente per te,
 era uno dei nostri trascrittori piu' affidabili. Sono sicuro che qualunque articolo abbia trovato riguardo alle informazioni che cerchi
 sia stato trascritto nei nostri computer.}
{407}{}{Aspetta, hai "l'impressione" che Fratello Thomas sia morto? Da dove vengo io, la morte e' una cosa abbastanza chiara. Quindi, e' morto o no?}
{408}{}{Fratello Thomas e' scomparso da diversi giorni, da quando e' sceso nelle caverne sotto l'Abbazia. [Sospira stancamente.]
 Vedi, alcuni residenti dell'Abbazia sostenevano di aver visto una bestia enorme che si aggirava la' sotto, e Fratello Thomas era piuttosto scettico.
 Si e' preso l'incarico di andare a sfatare queste voci, eppure, a quanto pare, la sua scomparsa le ha solo ulteriormente confermate.}
{409}{}{Hmmm. Forse dovrei dare un'occhiata a cosa c'e' la' sotto. In fondo *SONO* il Prescelto...}
{410}{}{Sono avventuroso. Posso dare un'occhiata.}
{411}{}{Lo faresti davvero? Forse mentre sei la' sotto potresti cercare un certo libro. Vedi, si sapeva che era in possesso di
 Fratello Thomas, ed e' molto importante per noi, poiche' e' stato tramandato dai nostri fondatori.
 Se riuscissi a recuperare quel libro, ti sarei molto grato. In effetti, ti concederei pieno accesso ai nostri computer, cosi'
 puoi cercare tutto cio' che desideri.}
{412}{}{Affare fatto. Torno presto.}
{413}{}{Forse, lasciami pensare ancora un po'...}
{414}{}{Grazie. Per favore, fammi sapere se trovi il libro.}
{415}{}{Okay, ciao.}
{416}{}{Salve, amico mio.}
{417}{}{Ho ucciso la tua bestia e ho recuperato il tuo libro.}
{418}{}{Ottimo! Fammelo avere!}
{419}{}{Ecco qua.}
{420}{}{Non cosi' in fretta. Quanto vale per te?}
{421}{}{[Prende il libro da te e ne accarezza la copertina come per calmarlo.] Ci hai reso un grande servizio. Ora hai
 pieno accesso ai nostri computer in biblioteca. Di' a Fratello Paul che ti concedo il permesso di accedere ai nostri file.}
{422}{}{Grazie.}
{423}{}{Vuoi dei soldi per questo? Va bene, ecco $250. Vai da Fratello Paul per accedere ai computer.}
{424}{}{Grazie per i soldi, arrivederci.}
{425}{}{Dovresti cercare su un computer al secondo piano, ora che hai pieno accesso la'.}
{426}{}{Okay, ciao.}
{430}{}{Qual e' lo scopo del vostro ordine?}
{431}{}{Qual e' la storia dell'Abbazia?}
{432}{}{Hmm, non ho domande al momento.}
{433}{}{La nostra sacra missione e' leggere, copiare e custodire i nostri sacri libri di conoscenza e altre reliquie dell'eta' perduta.
 E' nostra speranza che con questa conoscenza siamo in grado di creare un Memorabilia che un giorno possa aiutare l'umanita' a emergere dal
 suo autoimposto Medioevo. Qualsiasi informazione che incontriamo viene registrata, affinche' non vada perduta come tanto e' andato perduto nel
 grande Diluvio di Fiamme.}
{434}{}{Dopo la Grande Guerra, le mani guida del destino hanno indirizzato i nostri antenati a questa vecchia Abbazia tra le montagne. Grazie
 alla sua posizione remota, il monastero sopravvisse al Diluvio di Fiamme per lo piu' illeso. Mentre i nostri antenati esploravano l'edificio,
 scoprirono un'ampia biblioteca di libri. E non solo testi religiosi, oh no, questa biblioteca conteneva la gamma completa
 di opere scritte, dai classici letterari alle enciclopedie scientifiche.}
{435}{}{Cos'e' successo dopo?}
{436}{}{Ho sentito abbastanza.}
{437}{}{Si resero presto conto del vero tesoro di saggezza custodito in quei libri -- specialmente nei tomi scientifici.
 Qui erano le cronache di una civilta' caduta. Un'eta' perduta. C'erano alcuni che pensavano fosse meglio
 distruggere questa conoscenza, per timore che guidasse di nuovo l'umanita' verso l'apocalisse. Ma alla fine
 si decise che si sarebbero invece dedicati a garantire la preservazione dei libri, da rilasciare quando,
 e se, il mondo fosse stato pronto per questo.}
{438}{}{(Altro)}
{439}{}{E cosi', utilizzando una piccola stampante, iniziarono a fare copie dei libri, trascrivendoli anche
 nei computer dell'Abbazia per preservarli digitalmente, nel caso in cui i libri fisici fossero mai distrutti. Nel corso degli anni,
 altri hanno trovato l'Abbazia, e alcuni hanno scelto di restare e vivere la propria vita nella tranquilla quiete della nostra dimora montana.}
{440}{}{Grazie per la storia.}
{441}{}{Da dove venivano i vostri antenati?}
{442}{}{Non hanno mai detto da dove venissero originariamente. Sospettiamo che siano venuti qui originariamente dall'est.}
{443}{}{Beh, grazie per la storia.}
{444}{}{Ha bisogno di aiuto qui al monastero?}
{445}{}{Ho scoperto cosa c'e' che non va nella vostra pompa dell'acqua.}
{446}{}{Sa nulla a proposito dei fondatori originali?}
{447}{}{Non conosco tutti i nomi dei nostri fondatori, ma il piu' importante di cui sono a conoscenza e' Miller.
 Prima della Grande Guerra era un ingegnere elettrico che lavorava per il governo degli Stati Uniti. Poco dopo,
 si converte' al cattolicesimo e fece un giuramento con se stesso che avrebbe trascorso il resto della sua vita a preservare la
 conoscenza del passato. La sua paura piu' grande era che questa conoscenza andasse perduta per sempre e che quindi dovesse essere preservata
 affinche' le generazioni future potessero trarne beneficio.}
{448}{}{Devi essere molto istruito avendo letto cosi' tanto.}
{449}{}{Ho davvero letto molto nella mia vita. Eppure potresti essere deluso dai limiti della mia conoscenza. Vedi,
 noi registriamo e preserviamo. Ci e' vietato agire sulla saggezza di questi libri, quindi la nostra comprensione del testo e' piuttosto limitata.}
{450}{}{Aspetta, mi stai dicendo che trascrivete ciecamente questi libri senza nemmeno cercare di comprenderli?}
{451}{}{Come ho detto, il nostro compito e' preservare questa conoscenza, non comprenderla. Prima che questa conoscenza possa essere
 restituita all'umanita', essa deve prima dimostrare di essersi elevata al di sopra della sua tendenza al genocidio di massa. E' l'unico modo per
 garantire che la storia non si ripeta.}
{452}{}{Be', ho una notizia per te: quel giorno non arrivera' mai. E mentre accumulate tutta questa conoscenza nel vostro
 piccolo paradiso di montagna, la gente nelle Lande lotta ogni giorno per sopravvivere. In realta', la mia intera tribu'
 e' sull'orlo della distruzione. La conoscenza contenuta in questi libri potrebbe aiutare a curare malattie, migliorare i raccolti e aumentare notevolmente
 le possibilita' di sopravvivenza dell'umanita'.}
{453}{}{Ah, suppongo che tu abbia ragione. Ma sembra proprio che le informazioni conservate qui potrebbero aiutare molte
 persone. Anche se non pensi che il mondo sia pronto per questa conoscenza, non vedo perche' *tu* non possa almeno cercare di imparare da essa.
 Altrimenti, qual e' il senso di conservarla?}
{454}{}{Capisco la tua frustrazione per i nostri metodi, ma devi capire che questo e' sempre stato il nostro modo di fare.
 Cambiare le cose ora, dopo tanti anni... sarebbe blasfemo contro la nostra fede. No, sento che dobbiamo continuare
 a vivere secondo le regole stabilite dai nostri antenati.}
{455}{}{Capisco la tua frustrazione per i nostri metodi, ma devi capire che questo e' sempre stato il nostro modo di fare.
 Cambiare le cose ora, dopo tanti anni... sarebbe blasfemo contro la nostra fede. Tuttavia, considerero'
 le tue parole. Percepisco grande saggezza in te, viandante. E' un peccato che ne abbia incontrati cosi' pochi come te.}
{456}{}{Grazie. Vorrei sapere qualcos'altro pero'.}
{457}{}{Molto bene. Vorrei sapere qualcos'altro pero'.}
{500}{}{Smettila!}
{501}{}{Guadagni %d punti esperienza per aver riportato il libro.}
{600}{}{Ho riparato la vostra pompa dell'acqua rotta.}
{601}{}{Questa e' davvero un'ottima notizia. Quella pompa dell'acqua aveva avuto problemi per parecchio tempo. Quei mercanti dicevano che
 se ne sarebbero occupati, ma non sembravano fare molti progressi. E' stata una fortuna che tu sia passato. Grazie ancora.}
{602}{}{Mi aspetto dei soldi per questo, sai. Ora fuori i soldi!}
{603}{}{Nessun problema. Avrei delle altre domande pero'.}
{604}{}{Sono felice di essere stato utile. Prenditi cura di te.}
{605}{}{[Corruga la fronte.] Capisco. Va bene, ecco, prendi queste monete. Ora vai, e smettila di disturbarmi.}
{606}{}{Grazie, *padre*.}
{700}{}{Uhh... no, sembra che l'abbia smarrito.}
{701}{}{Cosa!? [Sospira profondamente.] E' molto spiacevole che tu non sia riuscito a recuperare quel libro. Ma dici di aver
 ucciso la bestia? Hm, allora dovrebbe essere sicuro mandare la nostra gente la' sotto a continuare a cercarlo. Comunque, per il tuo
 servizio, ti concedo l'accesso ai nostri computer. Vai da Fratello Paul per la chiave di accesso.}
{702}{}{Grazie.}
{800}{}{In realta' si'. La nostra pompa dell'acqua principale ha avuto problemi per un po' di tempo, e ora sembra finalmente essersi rotta
 completamente. Se sai qualcosa di macchinari, pensi di poter dare un'occhiata e vedere se si puo' fare qualcosa?
 Ci sono gia' alcuni mercanti che ci lavorano. Temo pero' che siano stati fatti pochi progressi.}
{801}{}{Sono felice di aiutare. Ti riferiro' i progressi.}
{802}{}{Certo, sara' un piacere aiutare... per un compenso naturalmente.}
{803}{}{Ripensandoci, lasciami chiedere qualcos'altro.}
{804}{}{Cosa!? Oh, va bene. Se sei fatto cosi', allora riceverai un compenso per il tuo servizio. Ecco
 25 monete per cominciare. Fammi sapere se si puo' fare qualcosa. [L'uomo sospira mentre ti porge le monete]}
{805}{}{Ehi, non c'e' bisogno di sospirare. Pensi che tutto nella vita sia gratis? Ora lasciami lavorare.}
{806}{}{Davvero? Ti prego, racconta.}
{807}{}{Il motore ha ceduto e ha bruciato tutti i connettori. Vado a Vault City a prendere un pezzo nuovo.}
{808}{}{Oh grazie. Sei davvero di grande aiuto. Per favore riferiscimi non appena installi il nuovo pezzo.}
{809}{}{Lo farò. Torno subito.}
{900}{}{Spieghi all'Abate che mentre le informazioni che custodiscono potrebbero portare all'annientamento dell'umanita', potrebbero anche portare alla sua salvezza.}
{901}{}{Scopri del fondatore originale dell'Abbazia.}
{1000}{}{Io ammazzato mostro brutto giu' in grotta.}
{1010}{}{Davvero? Ottimo. Sei stato molto coraggioso. Sei un bravo ragazzo.}
{1011}{}{Davvero? Ottimo. Sei stata molto coraggiosa. Sei una brava ragazza.}
{1012}{}{(sorriso) Lo so.}
{1020}{}{Hai trovato per caso un libro la' dentro? Ce l'aveva un mio amico, ed e' scomparso.}
{1021}{}{Io trovato libro. Ecco, e' pesante e dentro no figure.}
{1022}{}{Io no trovato libro. Dispiacee. Io andare cercare adesso.}
{1030}{}{Ho trovato il libro.}
{1031}{}{Ottimo. Grazie. Sei davvero un tipo speciale.}
{1032}{}{Ottimo. Grazie. Sei davvero una tipa speciale.}
{1033}{}{EVVAI.}
{1100}{}{Ero la' giu' prima. Ho visto alcuni cadaveri, quindi immagino che uno di loro fosse il vostro monaco scomparso. Se
 puo' farti sentire meglio, ho ucciso la cosa responsabile della sua morte.}
{1110}{}{Ah... quindi e' come temevo. Fratello Thomas ci manchera' molto. Ti ringrazio per averci liberato da qualunque
 bestia delle Lande si nascondesse la' sotto. Tuttavia, io... non suppongo che tu abbia trovato un libro mentre eri la' giu'. E' un libro molto
 importante che si sapeva essere in possesso di Fratello Thomas.}
{1111}{}{No, ma suppongo di poter tornare a controllare.}
{1112}{}{Stai parlando di questo libro?}
{1113}{}{Prima di andare, lasciami chiedere qualcos'altro.}
{1411}{}{Molto interessante. Adesso devo andare.}
{3000}{}{Come posso aiutarti?}
{4091}{}{Quindi nessun altro si e' preoccupato di scendere la' giu' a controllare? E se fosse semplicemente intrappolato la' in qualche modo, e stesse lentamente morendo di fame?}
{4092}{}{Suppongo che sia possibile, ma devi capire. Siamo un popolo pacifico. Il solo pensiero di affrontare uno di quei mostri delle Lande ci terrorizza. Semplicemente non siamo attrezzati per tali scontri. }
{4177}{}{Ho ucciso la bestia.}
{4188}{}{Eccellente! E il libro; sei riuscito a recuperarlo?}
{6020}{}{Se vuoi davvero mostrare la tua gratitudine, che ne dici di qualche soldo per il disturbo?}
