{100}{}{Vedi un monaco.}
{101}{}{Questo monaco sembra un commerciante.}
{200}{}{Benvenuto, viaggiatore.}
{201}{}{La pace sia con te.}
{202}{}{Bel tempo.}
{203}{}{Va' a giocare da qualche altra parte.}
{300}{}{Ciao, come posso aiutarti?}
{301}{}{Cosa puoi dirmi a proposito del vostro ordine?}
{302}{}{Barattiamo.}
{303}{}{Addio.}
{400}{}{La nostra sacra missione e' raccogliere e preservare le reliquie del passato dimenticato. Chiunque e' il benvenuto, finche' non danneggia nulla.}
{401}{}{Chi e' il vostro leader?}
{402}{}{Che tipo di reliquie?}
{403}{}{Lo trovi al terzo piano. Se vuoi sapere di piu' sul nostro ordine, e' lui quello con cui parlare.}
{404}{}{Di ogni tipo, ma la maggior parte delle nostre Memorie consiste in antichi tomi. Da quei testi si puo' ricavare moltissima conoscenza. La nostra missione e' preservarla affinche' le generazioni future possano usarla per costruire un nuovo mondo di pace e gioia.}
{405}{}{Okay.}
{406}{}{Ok.}
{500}{}{Smettila!}
