{100}{}{Vedi un monaco esperto di computer.}
{101}{}{Vedi Fratello Paul.}
{102}{}{Questo monaco sembra un maniaco dei computer.}
{200}{}{Ciao!}
{201}{}{Salve.}
{202}{}{Ora, ho fatto il backup di quei file oggi...}
{203}{}{Mi dispiace, ma non ho tempo per qualcuno della tua intelligenza.}
{300}{}{Si'?}
{301}{}{Avete proprio un sacco di computer, qui.}
{302}{}{Cosa puoi dirmi a proposito dell'Abazia?}
{303}{}{Parlami del vostro leader.}
{304}{}{Hai informazioni su un G.E.C.K.?}
{305}{}{Sa dove potrei trovare il Vault 13?}
{306}{}{Addio.}
{307}{}{Ho bisogno di alcune informazioni specifiche.}
{308}{}{Ovvero?}
{400}{}{Si', ne abbiamo. Troppi, secondo me. Non posso spiegarti quanto sia noioso dover fare il backup di tutti questi file ogni singolo giorno. C'e' cosi' tanta informazione da preservare, ma ovviamente va fatto.}
{401}{}{Certo. Comunque, avrei delle altre domande.}
{402}{}{Siamo una comunita' indipendente. Chiunque e' il benvenuto, finche' si comporta bene.}
{403}{}{Ok.}
{404}{}{L'Abate e' un buon leader spirituale, ma e' un po' irritabile da quando abbiamo perso Fratello Thomas a causa della bestia.}
{405}{}{Che tipo di bestia?}
{406}{}{Non l'ho visto di persona — niente al mondo mi convincerebbe a scendere laggiu' a esplorare quelle caverne — ma se dovessi indovinare direi che e' probabilmente solo un radscorpion cresciuto troppo.}
{407}{}{Se non l'hai visto, cosa ti fa pensare che sia uno scorpione radioattivo?}
{408}{}{Perche' ho sentito suoni riecheggiare dalle caverne — rumori di artigli che schioccano e zampe che strisciano.}
{409}{}{Right.}
{410}{}{In effetti, si'. Dai un'occhiata a quel computer laggiu'. Tieni, puoi usare questa scheda per accedere ai nostri file criptati. [Ti porge una scheda di accesso.]}
{411}{}{Wow, grazie mille!}
{412}{}{Non so nulla del Vault 13, ma piu' a sud c'e' Vault City. Forse hanno le informazioni che ti servono.}
{413}{}{Grazie.}
{414}{}{Quel computer vicino a me dovrebbe avere le informazioni che cerchi, ma ti serve una scheda di accesso per usarlo. 
Siamo molto selettivi su chi puo' accedervi, ma se parli con l'Abate forse ti dara' il permesso.}
{415}{}{Ok, grazie.}
{420}{}{Immagino tu abbia letto molti libri nella tua vita. Quindi sono curioso: qual e' la cosa piu' affascinante che potresti raccontarmi?}
{421}{}{Hmm, vediamo. Sapevi che un'incisione su un albero rimane alla stessa altezza da terra mentre l'albero cresce?}
{422}{}{Certo. Se trovo qualcosa del genere, ti faro' sapere di sicuro.}
{423}{}{Capito... Beh, avrei delle altre domande.}
{424}{}{Lo faresti? Lo apprezzerei molto.}
{425}{}{Nessun problema. Avrei delle altre domande.}
{426}{}{Quando vuoi. Beh, a presto.}
{430}{}{Ho trovato alcune informazioni di Botanica che potrebbero interessarti.}
{431}{}{Davvero?! Fantastico. Ti prego, dimmi subito.}
{432}{}{Affascinante! Prendero' questo olodisco e lo aggiungero' subito al database. Apprezzo che tu abbia trovato il tempo per cercarlo per me. Grazie per avermelo portato.}
{433}{}{Vedi... Capire la distruzione degli habitat e l'estinzione delle specie dipende da un catalogo accurato e completo della sistematica e tassonomia delle piante. E questo significa che...}
{434}{}{Quando vuoi. Ho delle altre domande pero'.}
{435}{}{Nessun problema. Ci vediamo.}
{436}{}{Affascinante! Apprezzo che tu abbia trovato il tempo per cercarlo per me. Per favore, vai a caricare queste informazioni nei nostri computer.}
{437}{}{Nessun problema, lo faccio subito. Ci vediamo.}
{500}{}{Smettila, coglione!}
{550}{}{Quel computer vicino a me dovrebbe avere qualche informazione a riguardo. Ora hai l'accesso, quindi dai un'occhiata tu stesso.}
{600}{}{L'Abate mi ha dato il permesso di accedere ai computer qui.}
{601}{}{Ah si', ho sentito cosa hai fatto. Grazie per esserti occupato della situazione. Ecco la chiave di accesso. (Ti porge la chiave.) Divertiti!}
{602}{}{Grazie. Ci vediamo.}
{650}{}{Saluti, viaggiatore! Sono Fratello Paul e mi occupo della raccolta delle informazioni per l'Abbazia. Cosa posso fare per te?}
{651}{}{Piacere di conoscerti, Paul. Ho alcune domande.}
{652}{}{Niente. A presto.}
{4210}{}{Uh, no, non posso dire di saperlo. E'... interessante.}
{4211}{}{E sapevi che un cetriolo e' composto al 96% di acqua?}
{4212}{}{Wow, 96%, eh? Affascinante. Ma, uh, cos'e' un cetriolo?}
{4213}{}{Non ne ho mai visto uno, ma ne ho letto. [Si guarda intorno nervosamente e abbassa la voce.] 
So che non dovremmo davvero studiare questi libri, ma quando stavo trascrivendo un libro di botanica non ho potuto fare a meno di farmi trascinare. 
Il mondo delle piante e' semplicemente affascinante. Forse, se durante i tuoi viaggi trovassi qualche informazione di botanica, potresti portarmela? 
Te ne sarei molto grato. Ovviamente, dovrebbe restare un segreto.}
{4220}{}{Non credo di voler alimentare la tua ossessione per le piante. Mi dispiace.}
{4221}{}{Oh, beh. Va bene, fa' finta che non abbia chiesto.}
{4222}{}{Lascia che ti chieda qualcos'altro.}
