{100}{}{Vedi un monaco.}
{101}{}{Vedi una santona.}
{102}{}{Vedi un monaco ordinario dell'Abbazia.}
{103}{}{Vedi una comune suora dell'Abbazia.}
{200}{}{Salve.}
{201}{}{Benvenuto all'Abbazia.}
{202}{}{Dovresti parlare con il nostro leader se vuoi ottenere informazioni.}
{203}{}{Buona giornata... o e' gia' notte?}
{204}{}{C'e' cosi' tanto lavoro da fare.}
{205}{}{La vita qui all'Abbazia e' tranquilla. Qualcosa di raro in queste miserabili Lande.}
{500}{}{Smettila!}
