{100}{}{You see a monk.}
{101}{}{Vedi una santona.}
{102}{}{Vedi un monaco ordinario dell'Abbazia.}
{103}{}{You see a regular Abbey nun.}
{200}{}{Greetings.}
{201}{}{Welcome to the Abbey.}
{202}{}{You should talk to our leader if you wish to gain any information.}
{203}{}{Buona giornata... o e' gia' notte?}
{204}{}{There's so much work that must be done.}
{205}{}{La vita qui all'Abbazia e' tranquilla. Qualcosa di raro in queste miserabili Lande.}
{500}{}{Smettila!}
