{100}{}{You see a computer monk.}
{101}{}{You see Brother Paul.}
{102}{}{This monk looks like a computer geek.}
{200}{}{Ciao!}
{201}{}{Salve.}
{202}{}{Ora, ho fatto il backup di quei file oggi...}
{203}{}{I'm sorry, but I don't have time for someone of your intelligence.}
{300}{}{Si'?}
{301}{}{You guys sure have a lot of computers here.}
{302}{}{Cosa puoi dirmi a proposito dell'Abazia?}
{303}{}{Tell me about your leader.}
{304}{}{Do you have any info about a GECK?}
{305}{}{Do you know where I could find Vault 13?}
{306}{}{Addio.}
{307}{}{I am in need of some specific information.}
{308}{}{Ovvero?}
{400}{}{Si', ne abbiamo. Troppi, secondo me. Non posso spiegarti quanto sia noioso dover fare il backup di tutti questi file ogni singolo giorno. C'e' cosi' tanta informazione da preservare, ma ovviamente va fatto.}
{401}{}{Of course. Anyway, I have some other questions.}
{402}{}{Siamo una comunita' indipendente. Chiunque e' il benvenuto, finche' si comporta bene.}
{403}{}{Ok.}
{404}{}{L'Abate e' un buon leader spirituale, ma e' un po' irritabile da quando abbiamo perso Fratello Thomas a causa della bestia.}
{405}{}{What kind of beast?}
{406}{}{Non l'ho visto di persona — niente al mondo mi convincerebbe a scendere laggiu' a esplorare quelle caverne — ma se dovessi indovinare direi che e' probabilmente solo un radscorpion cresciuto troppo.}
{407}{}{If you haven't seen it, then what makes you think it's a radscorpion?}
{408}{}{Perche' ho sentito suoni riecheggiare dalle caverne — rumori di artigli che schioccano e zampe che strisciano.}
{409}{}{Right.}
{410}{}{In effetti, si'. Dai un'occhiata a quel computer laggiu'. Tieni, puoi usare questa scheda per accedere ai nostri file criptati. [Ti porge una scheda di accesso.]}
{411}{}{Wow, thanks a lot!}
{412}{}{Non so nulla del Vault 13, ma piu' a sud c'e' Vault City. Forse hanno le informazioni che ti servono.}
{413}{}{Grazie.}
{414}{}{Quel computer vicino a me dovrebbe avere le informazioni che cerchi, ma ti serve una scheda di accesso per usarlo. 
Siamo molto selettivi su chi puo' accedervi, ma se parli con l'Abate forse ti dara' il permesso.}
{415}{}{Ok, grazie.}
{420}{}{Immagino tu abbia letto molti libri nella tua vita. Quindi sono curioso: qual e' la cosa piu' affascinante che potresti raccontarmi?}
{421}{}{Hmm, vediamo. Sapevi che un'incisione su un albero rimane alla stessa altezza da terra mentre l'albero cresce?}
{422}{}{Sure. If I come across anything like that, I'll be sure to let you know.}
{423}{}{Right... Well, I have some other questions.}
{424}{}{Would you? I'd appreciate that.}
{425}{}{No problem. I have some other questions.}
{426}{}{Any time. Well, see you around.}
{430}{}{I found some information about Botany that might interest you.}
{431}{}{Davvero?! Fantastico. Ti prego, dimmi subito.}
{432}{}{Affascinante! Prendero' questo olodisco e lo aggiungero' subito al database. Apprezzo che tu abbia trovato il tempo per cercarlo per me. Grazie per avermelo portato.}
{433}{}{Vedi... Capire la distruzione degli habitat e l'estinzione delle specie dipende da un catalogo accurato e completo della sistematica e tassonomia delle piante. E questo significa che...}
{434}{}{Any time. I have some other questions though.}
{435}{}{No problem. See you around.}
{436}{}{Affascinante! Apprezzo che tu abbia trovato il tempo per cercarlo per me. Per favore, vai a caricare queste informazioni nei nostri computer.}
{437}{}{No problem, I'll do that now. See you around.}
{500}{}{Stop that, moron!}
{550}{}{Quel computer vicino a me dovrebbe avere qualche informazione a riguardo. Ora hai l'accesso, quindi dai un'occhiata tu stesso.}
{600}{}{L'Abate mi ha dato il permesso di accedere ai computer qui.}
{601}{}{Ah si', ho sentito cosa hai fatto. Grazie per esserti occupato della situazione. Ecco la chiave di accesso. (Ti porge la chiave.) Divertiti!}
{602}{}{Thanks. See you around.}
{650}{}{Saluti, viaggiatore! Sono Fratello Paul e mi occupo della raccolta delle informazioni per l'Abbazia. Cosa posso fare per te?}
{651}{}{Nice to meet you, Paul. I have some questions.}
{652}{}{Niente. A presto.}
{4210}{}{Uh, no, non posso dire di saperlo. E'... interessante.}
{4211}{}{E sapevi che un cetriolo e' composto al 96% di acqua?}
{4212}{}{Wow, 96%, eh? Affascinante. Ma, uh, cos'e' un cetriolo?}
{4213}{}{Non ne ho mai visto uno, ma ne ho letto. [Si guarda intorno nervosamente e abbassa la voce.] 
So che non dovremmo davvero studiare questi libri, ma quando stavo trascrivendo un libro di botanica non ho potuto fare a meno di farmi trascinare. 
Il mondo delle piante e' semplicemente affascinante. Forse, se durante i tuoi viaggi trovassi qualche informazione di botanica, potresti portarmela? 
Te ne sarei molto grato. Ovviamente, dovrebbe restare un segreto.}
{4220}{}{I don't think I want to contribute to your plant obsession. Sorry.}
{4221}{}{Oh, well then. Fine, forget I asked.}
{4222}{}{Lascia che ti chieda qualcos'altro.}
