{100}{}{You see a monk.}
{101}{}{You see a nun.}
{102}{}{This monk looks like he knows a thing or two about computers.}
{103}{}{Questa suora sembra sapere qualcosa di computer.}
{200}{}{Don't break anything.}
{201}{}{Sorry, I'm rather busy at the moment.}
{202}{}{Greetings.}
{203}{}{Feel free to look around.}
{204}{}{Copiamo la conoscenza per le generazioni future.}
{205}{}{These old books are very fragile.}
{206}{}{Copiare libri e' un lavoro piuttosto duro.}
{207}{}{Salve.}
{208}{}{There's much to copy down from these books.}
{500}{}{Smettila!}
