{100}{}{Vedi un monaco.}
{101}{}{Vedi una suora.}
{102}{}{Questo monaco sembra saperne qualcosa di computer.}
{103}{}{Questa suora sembra sapere qualcosa di computer.}
{200}{}{Non rompere nulla.}
{201}{}{Scusa, sono piuttosto occupato al momento.}
{202}{}{Salve.}
{203}{}{Sentiti libero di guardarti intorno.}
{204}{}{Copiamo la conoscenza per le generazioni future.}
{205}{}{Questi vecchi libri sono molto fragili.}
{206}{}{Copiare libri e' un lavoro piuttosto duro.}
{207}{}{Salve.}
{208}{}{C'e' molto da copiare da questi libri.}
{500}{}{Smettila!}
