{100}{}{You see a monk.}
{101}{}{This monk looks like a trader.}
{200}{}{Welcome traveler.}
{201}{}{Peace to you.}
{202}{}{Nice weather.}
{203}{}{Go play somewhere else.}
{300}{}{Hi, how can I help you?}
{301}{}{What can you tell me about your order?}
{302}{}{Barattiamo.}
{303}{}{Addio.}
{400}{}{La nostra sacra missione e' raccogliere e preservare le reliquie del passato dimenticato. Chiunque e' il benvenuto, finche' non danneggia nulla.}
{401}{}{Who is your leader?}
{402}{}{What kind of relics?}
{403}{}{Lo trovi al terzo piano. Se vuoi sapere di piu' sul nostro ordine, e' lui quello con cui parlare.}
{404}{}{Di ogni tipo, ma la maggior parte delle nostre Memorie consiste in antichi tomi. Da quei testi si puo' ricavare moltissima conoscenza. La nostra missione e' preservarla affinche' le generazioni future possano usarla per costruire un nuovo mondo di pace e gioia.}
{405}{}{Okay.}
{406}{}{Ok.}
{500}{}{Smettila!}
