{100}{}{Vedi una persona che indossa una Power-Armor. }
{101}{}{Vedi il Comandante della base di Navarro.}
{102}{}{Vedi una persona che indossa una Power-Armor dall'aspetto insolito. Sul petto c'e' uno stemma che non ti e' familiare.}
{103}{}{Chi diavolo...? Allarme! Intrusi nella base!}
{104}{}{Non ho tempo per chiacchierare con i soldati. Puoi andare.}
{105}{}{E' tempo... di morire.}
{106}{}{Okay.}
{107}{}{Ti ho detto che non ho tempo per te. Esci da questo ufficio e non tornare a meno che non ti mandi a chiamare. Puoi andare!}
{108}{}{Disobbedire ad un ordine diretto di un ufficiale superiore e' considerato tradimento. Non ho tempo per convocare la corte marziale, quindi me ne occupero' personalmente. Guardie! Uccidete questo idiota!}
{109}{}{Okay.}
{110}{}{Fottiti!}
{111}{}{Il FOB e' nell'armadietto la' in fondo. Fa' in modo che l'ufficiale di servizio mi contatti, una volta che il codice sara' stato messo al sicuro. Congedato!}
{112}{}{Sissignore!}
{113}{}{Fa' in fretta, soldato: non ho tutto il giorno.}
{114}{}{Sissignore!}
{115}{}{Lascia in pace il mio armadietto o te ne faro' pentire amaramente.}
{116}{}{Sissignore!}
{117}{}{La base e' allertata e io non ti riconosco. Fammi vedere i tuoi documenti, soldato.}
{118}{}{Che documenti?}
{119}{}{Andare a diavolo!}
{120}{}{Non credo di averli portati...}
{121}{}{Documenti? Eccoteli qua i documenti che cerchi!}
{122}{}{Risposta sbagliata, pidocchio. Devi sempre portare i documenti con te, in ogni momento. Dovresti saperlo!}
{123}{}{Fottiti.}
{124}{}{Lascia in pace il mio armadietto o te ne faro' pentire amaramente.}
{125}{}{E' tempo... di morire.}
{200}{}{Ok, sbrighiamola -- non mi piace avere mutanti che puzzano nel mio ufficio, e ho un sacco da fare. Lavori per i Salvatores?}
{201}{}{None of your business, asshole.}
{202}{}{Non lavoro per nessuno.}
{203}{}{So what if I do?}
{204}{}{Yeah, I work for the Salvatores.}
{205}{}{Before I answer any questions, I've got a few of my own.}
{210}{}{I don't have time for this bullshit. Guards! Kill this mutie!}
{220}{}{Quindi stai dicendo di essere solo un topo randagio della Landa capitato per caso in uno dei nostri vertibird?}
{221}{}{Uh, si', piu' o meno... tranne la parte in cui sarei un topo.}
{222}{}{Proprio cosi'.}
{223}{}{No, sto dicendo che e' tutto un grande malinteso. Non so chi siate e non mi interessa. Quindi, se non vi dispiace, me ne vado.}
{230}{}{Bene, se agisci da solo, non devo perdere un altro secondo con te. Guardie! Uccidete questo mutante!}
{240}{}{Non te ne andrai vivo da qui, mutante. Non posso rischiare che tu vada a spifferare la posizione di questa base ai tuoi amici della Landa, giusto? 
Guardie! Uccidete questo mutante!}
{250}{}{Dimmi quello che voglio sapere, e mi assicuro che la tua morte sia rapida e... relativamente indolore. E' stato Salvatore a mandarti?}
{251}{}{Uhh... no? Aspetta, si'. Forse.}
{252}{}{No. Giocare a nascondino nel vostro aggeggio volante e' stata tutta una mia idea. Geniale, lo so.}
{253}{}{Si', ha pensato di addolcire lo scambio mandando me. Che affare, eh?}
{254}{}{Before I answer any questions, I've got a few of my own.}
{260}{}{I don't have time for this bullshit. Guards! Kill this mutie!}
{270}{}{Dovrebbe essere divertente, mutante? Sarai molto piu' divertente quando sarai un cadavere sanguinante. Guardie! Uccidete questo mutante!}
{280}{}{Oh, davvero? [Ride.] Beh, perche' no? Tanto stai per morire comunque. Cosa vuoi sapere, mutante?}
{281}{}{Ma perche' continui a darmi del mutante?}
{282}{}{Chi diavolo siete voi?}
{283}{}{Where am I? }
{284}{}{How can I get some of that sweet armor?}
{285}{}{Ho sentito abbastanza.}
{290}{}{Perche' LO SEI. Certo, potresti sembrare quasi umano, ma non lasciarti ingannare. Sei comunque un mutante. 
Tu e tutti gli altri sulla terraferma. Tutti contaminati. Prossima domanda?}
{300}{}{Noi siamo l'Enclave, l'ultimo baluardo della vera umanita' su questo dannato pianeta. Siamo gli unici a mantenere l'onore del vecchio rosso, bianco e blu. 
Si', siamo veri patrioti. Mangiamo aquile e caghiamo stelle e strisce. Siamo tutto cio' che resta dei grandi Stati Uniti d'America. Ma siamo abbastanza. 
Oh si', siamo abbastanza per rimettere le cose a posto. Puoi contarci, mutante. Prossima domanda?}
{310}{}{Questa e' Navarro, la nostra base segreta sulla terraferma. Siamo proprio sulla costa della California e dell'oceano Pacifico. Prossima domanda?}
{320}{}{Strappandola dal mio cadavere. Buona fortuna, mutante. Prossima domanda?}
{330}{}{Bene, perche' sono stufo di sprecare fiato con un mutante. Anzi, tutta questa storia e' una perdita di tempo, perche' non me ne frega un cazzo di quello che hai da dirmi. 
Guardie! Uccidete questo mutante!}
