{100}{}{Apri il cassetto e trovi file e appunti ordinati in fila.}
{101}{}{Cerca nel cassettone.}
{102}{}{Te ne vai.}
{103}{}{Mentre cerchi tra i documenti nel cassetto, noti una sottile valigetta di pelle nascosta con cura in fondo.}
{104}{}{Tira fuori la valigetta.}
{105}{}{Ignora e continua a cercare.}
{106}{}{Passano 30 minuti e non trovi nulla di importante. Tutto cio' che scopri e' che Chad tiene registri che documentano ogni momento della sua vita. 
In realta' e' un tipo piuttosto noioso. Proprio mentre stai per chiudere i cassetti, senti un colpo di tosse dalla porta d'ingresso e una maniglia che gira...}
{107}{}{Tira fuori la valigetta.}
