{100}{}{Vedi un computer funzionante.}
{101}{}{Vedi il terminale del controllo del traffico aereo.}
{102}{}{Benvenuto al controllo del traffico aereo. Questo terminale gestisce l'allineamento dei satelliti per il movimento dei Vertibird. Inserire un comando.}
{103}{}{Esci.}
{104}{}{Allinea il satellite per ricevere le coordinate dell'Enclave.}
{105}{}{Riallineamento del satellite in corso. Un momento...}
{106}{}{[AVANTI]}
{107}{}{Riallineamento completato. La piattaforma di attracco e' pronta a ricevere i velivoli in arrivo.}
{108}{}{Esci.}
