{100}{}{Vedi un grosso aeromobile.}
{101}{}{Vedi un Vertibird.}
{200}{}{[Sali sull'aeromobile e accedi al terminale del pilota.] Benvenuti in PoseidoNet. Questo terminale e' limitato alle trasmissioni tra lo squadrone di Vertibird dell'Enclave e la piattaforma d'attracco. Comando?}
{201}{}{Stato.}
{202}{}{Esci.}
{203}{}{Questo velivolo ha carburante sufficiente solo per un viaggio completo dal avamposto di Navarro alla piattaforma di attracco e ritorno. 
Tutte le procedure sono completamente automatizzate e non e' richiesto intervento dell'equipaggio. Stato carburante attuale: Pieno.}
{204}{}{Vola verso la Piattaforma Petrolifera.}
{205}{}{Esci.}
{206}{}{Errore. La scheda gialla del reattore non e' inserita. Tutti i piloti ricevono questa scheda al momento dell'autorizzazione al decollo. 
Il volo automatico non puo' avvenire senza la presenza di questa scheda.}
{207}{}{Inserisci tessera.}
{208}{}{Merda. Sembra proprio che dovro' trovare questa tessera.}
{209}{}{Scheda accettata. Il velivolo e' ora attivato.}
{210}{}{Esegui la diagnostica pre-volo.}
{211}{}{Esci.}
{212}{}{Avvio diagnostica di sistema... 35% completato... 75% completato... 100% completato. Tutti i sistemi sembrano operativi. Controllo risposta dalla piattaforma di attracco...}
{213}{}{[AVANTI]}
{214}{}{Nessun segnale ricevuto dalla piattaforma di attracco. Motivo: satelliti non allineati per l'attracco automatico con la Piattaforma Petrolifera. Assicurarsi che la piattaforma sia consapevole dell'arrivo dei velivoli.}
{215}{}{Hmm... Sembra che dovro' trovare un modo per allineare i satelliti.}
{216}{}{Urg?}
{220}{}{Velivolo attualmente attivato. Comando?}
{221}{}{Esegui la diagnostica pre-volo.}
{222}{}{Esci.}
{230}{}{Segnale di test ricevuto. Recupero coordinate di attracco... completato. Velivolo pronto al decollo.}
{231}{}{Vai.}
{232}{}{Esci.}
{240}{}{Il velivolo e' agganciato al bersaglio. Tempo di volo stimato: circa 6 ore. Buon viaggio.}
{241}{}{Eccoci -- il momento della verita'. La tribu' e' nei guai e dipende tutto da me. I piedi mi fanno male, tutto il corpo duole, e non ricordo l'ultima volta che ho mangiato un pasto decente.
Sono questi i momenti per cui viviamo. Non si torna indietro. E' il momento di mostrare al mondo di cosa }
{242}{}{ siamo fatti. Avanti, Enclave!}
{243}{}{Hehe... Vola uccellino, vola!}
{244}{}{ me lasciare te, ora.}
{300}{}{[Sali sull'aeromobile e accedi al terminale del pilota.] Benvenuti in PoseidoNet. Questo terminale e' limitato alle trasmissioni tra lo squadrone di Vertibird dell'Enclave e la piattaforma d'attracco. Comando?}
{301}{}{Stato.}
{302}{}{Esci.}
{303}{}{Questo velivolo ha carburante sufficiente solo per un viaggio completo dall'avamposto di Navarro alla piattaforma di attracco e ritorno. 
Tutte le procedure sono completamente automatizzate e non e' richiesto intervento dell'equipaggio. Stato carburante attuale: Vuoto.}
{304}{}{Esci.}
