{100}{}{Vedi un abusivo.}
{101}{}{You see a man covered in dirt and filth.}
{102}{}{You see a woman covered in dirt and filth.}
{103}{}{Cosa vuoi?}
{104}{}{Voglio che tu e i tuoi amici usciate da questo edificio. Ho saputo che Mom vuole trasformare questo posto
 in un orfanotrofio per togliere quei bambini senzatetto dalle strade. E non puo' farlo finche' voi ci vivete abusivamente.}
{105}{}{[Ridacchia nervosamente e guarda gli altri abusivi in cerca di supporto.] Mom conosce l'accordo. Non ce ne andiamo
 finche' non sgancia i soldi. Quindi, a meno che tu non ci abbia portato un milione di monete, vaffanculo.}
{106}{}{Senti, Mom non ha quei soldi, e anche se li avesse non vi pagherebbe mai, quindi scordatelo. Perche' non mostrate
 un po' di decenza e andate ad accamparvi da un'altra parte? Quei bambini senzatetto hanno bisogno di questo posto molto piu' di voi.}
{107}{}{Chi sei tu per decidere chi merita cosa? A *noi* piace stare qui. Non puoi costringerci ad andarcene.}
{108}{}{Ascolta, hai due scelte: puoi uscire da qui con le tue gambe, oppure posso farlo io -- trascinandoti fuori,
 un cadavere alla volta.}
{109}{}{([Scambia uno sguardo con gli altri abusivi, poi ti guarda e scuote la testa.] Non ci intimidisci.
 Nessuno ci caccia da qui. Combatteremo per il nostro territorio.}
{110}{}{[Scambia uno sguardo con gli altri abusivi, poi ti guarda e annuisce.] Ok, hai ragione. Non e' che odiamo i bambini,
 anzi, la maggior parte di noi era un bambino senzatetto. Stavamo solo cercando di fare un po' di soldi, capisci? Qui gli unici lavori
 riguardano spacciare droga o fare male alla gente, e non e' il nostro stile. [Sospira.] Ce ne andremo, ma dove suggerisci
 di andare? Questo posto e' casa nostra.}
{111}{}{I don't know. That's not my problem.}
{112}{}{Potrei pentirmene, ma se davvero volete un lavoro, sono sicuro che Mom avrebbe bisogno di aiuto per sistemare questo posto. E' una brava donna,
 quindi magari, se vi scusate, vi dara' una possibilita' per dimostrare che non siete solo un branco di opportunisti pigri. Parlero' con lei. Ma se provate
 a fregarla, vi trovero' e ve la faro' pagare.}
{113}{}{Al diavolo, ho cambiato idea. Non ce ne andiamo. Restiamo qui e combattiamo.}
{114}{}{[Scambia uno sguardo con gli altri abusivi e riflette sulle tue parole.] Sai una cosa? Non sembra affatto male. Anzi, potrebbe funzionare alla grande,
 se davvero pensi che Mom accettera'. Mentre vai a parlarle, noi iniziamo a pulire questo posto. Ah, e grazie per essere stato cosi' comprensivo.}
{115}{}{Lasciamo stare.}
{116}{}{Non vi paghera'. Ma sono qui per offrirvi un nuovo accordo: tu e i tuoi amici ve ne andate subito, e vi tenete la vita.}
{117}{}{Alright, well, I gave it a shot. Bye.}
{120}{}{E' un'ottima idea. Ci prepareremo subito.}
{200}{}{Eh?}
{201}{}{This is our turf.}
{202}{}{You squatting here too?}
{203}{}{Got anything to eat?}
{300}{}{You see a man in work clothes.}
{301}{}{You see a woman in work clothes.}
{310}{}{Ehi, grazie per averci aiutato a sistemare tutto. Lavoreremo duro.}
{311}{}{You better. Make sure the children stay out of trouble too.}
{312}{}{We'll do our best.}
{313}{}{Addio.}
{350}{}{Ovunque ma non qui. The Den e' un posto grande, sono sicuro che potete trovare un altro posto dove stare. Dai, volete davvero che quei bambini vivano per strada?}
{351}{}{No, hai ragione, non e' giusto per i bambini. Va bene, faremo le valigie e ce ne andremo. Tanto questo posto aveva pure il tetto che perdeva.}
{352}{}{Thanks. This will mean a lot to them. Take care.}
{353}{}{No, non e' un nostro problema. Se Mom pensa che sia cosi' importante togliere quei bambini dalla strada, allora dovrebbe smetterla di essere tirchia e condividere
 la ricchezza. Si', ho cambiato idea, restiamo finche' non paga. Ora la conversazione e' finita, quindi e' meglio che te ne vada se sai cosa e' meglio per te.}
{360}{}{Va bene. Non c'e' bisogno che la situazione degeneri. Vi lascio in pace.}
{361}{}{E' ora di ripulire questo posto, allora. (Attacca)}
{400}{}{Thanks again!}
{401}{}{We'll work hard.}
{402}{}{Thanks for being so cool about things.}
{403}{}{We won't let you down.}
{500}{}{We'll collect our things and be out of here soon.}
{600}{}{You've cleared out all the squatters.}
