{100}{}{Vedi uno spacciatore di droga.}
{101}{}{Vedi uno spacciatore di droga.}
{102}{}{Se vuoi fare affari, ho la roba giusta.}
{103}{}{Certo, fammela vedere.}
{104}{}{Magari un'altra volta.}
{105}{}{Hai trovato quello che ti serve?}
{106}{}{Grazie. Arrivederci.}
{200}{}{Vedi un delinquente.}
{201}{}{Vedi un delinquente.}
{202}{}{Sono qui per protezione. Parla con il venditore se vuoi comprare.}
