{100}{}{Vedi un uomo magro, dall'aspetto untuoso.}
{150}{}{Vedi Flick. Si sta dando una prolungata grattata al pacco.}
{151}{}{Vedi un tipo poco pulito con un brutto tic facciale.}
{200}{}{Fora dae bae, goldon.}
{201}{}{Ehi, digo a ti! Si', ti. Fora.}
{202}{}{Ti xe sordo o cossa?}
{203}{}{Che problemi ti ga, eh?}
{204}{}{Fora dae bae.}
{220}{}{Ehila', me ciamo Flick. Cossa diavolo ti vol, eh?}
{221}{}{Cossa ti ga? Ti xe drio a sprecar il mio tempo.}
{222}{}{Come mai hai questo strano accento, Flick?}
{223}{}{Cosa diavolo fai qui?}
{224}{}{Sto cercando un Vault - ah si', e anche un certo mercante di nome Vic. Sai per caso dove potrebbero essere?}
{225}{}{Vorrei barattare con te.}
{240}{}{Te va ben, amico?}
{241}{}{Veramente, mi piacerebbe dare un'altra occhiata alla tua merce, se possibile.}
{242}{}{Veramente, vorrei farti una domanda.}
{243}{}{Sono a posto. Ci vediamo, Flick.}
{260}{}{Mi so un mercante, cossa ti credi? 'na specie de bon Samurai-tano.}
{261}{}{Come?}
{262}{}{Certo, ehm, beh…lascia che ti chieda qualcos'altro.}
{263}{}{Ah, oh. OK. Ci vediamo, Flick.}
{280}{}{Vendo per i miei fioi.}
{281}{}{Vendi fiori?}
{290}{}{Fi-o-i, ti sa, i bambini. I miei bambini.}
{291}{}{I tuoi bambini?}
{292}{}{Beh, non mi interessano composizioni floreali fatte da bambini. Lascia che ti chieda qualcos'altro.}
{300}{}{Certo, ostrega... beh, i lavora per mi. I me porta dele cosse. Picole cosse. Cio', ti sa?}
{301}{}{Uh, no.}
{302}{}{Oh, OK. Lascia che ti chieda qualcos'altro, allora.}
{303}{}{Ah, capisco. Beh, non vorrei rovinarti gli, ehm, affari, stando qui. Ci vediamo.}
{315}{}{Mi portano la roba che trovano. Piccole, piccole cose. Roba che nessuno usa piu'. In cambio, io mi prendo cura di loro.}
{316}{}{Sembra un ottimo accordo.}
{325}{}{(Alza le spalle) Non mi lamento.}
{326}{}{Lascia che ti chieda qualcos'altro, allora.}
{327}{}{Sicuramente ti hanno portato dei veri affari. Vediamo cos'hai da offrirmi.}
{328}{}{Ero solo curioso. Beh, ci vediamo, Flick.}
{340}{}{Cossa ti xe drio a dir? Ti credi che sia un goldon? Ti credi che abbia ea mare putana? Ti credi che sia un paiasso? Che sia qui per divertirte, eh?}
{341}{}{Ehm, no. Scusa, ero solo curioso. Lascia che ti chieda qualcos'altro.}
{342}{}{Si', esatto, testa di cazzo. E niente mi divertira' di piu' che sentire i tuoi lamenti prima di morire.}
{343}{}{Beh, se devi proprio diventare cosi' permaloso, me ne vado.}
{360}{}{Vault, eh? Forse ea Mama ne sa qualcossa, ma mi no so niente. Ma quel fio, Vic - lo cognosso. Metzger lo ga preso, sa morti cani.}
{361}{}{Vic? E chi xe quel vecio che ti ga co' ti? Goldon. Ma 'sto Volt... mi no so cossa sia. Forse ea Mama lo sa.}
{362}{}{Chi e' Metzger?}
{363}{}{Ea Mama?}
{364}{}{Grazie. Lascia che ti chieda qualcos'altro.}
{365}{}{Grazie, e' tutto quello che mi serviva sapere. Ci vediamo.}
{380}{}{Ea Mama xe la parona del bacaro nela parte est dela citta'. Subito dopo el simitero. Xe un bel posto, fa dea bona pasta, Mama mia.}
{381}{}{Grazie. Cosa mi sai dire a proposito di questo Metzger, il tipo che ha preso Vic?}
{382}{}{Grazie. Lascia che ti chieda qualcos'altro.}
{383}{}{Grazie, e' tutto quello che mi serviva sapere. Ci vediamo.}
{400}{}{Gia'. Metzger, quel cancaro, xe morto. No so cossa sia sucesso a Vic.}
{401}{}{Quel Metzger, el xe un vero rompiballe. Xe el paron dela Gilda dei Sciavi. Nea zona est dela citta', a nord del bacaro dea Mama. Comunque, xe lu che ga preso Vic, son sicuro.}
{402}{}{Grazie, ma cosa mi sai dire di Mama?}
{403}{}{Grazie. Lascia che ti chieda qualcos'altro.}
{404}{}{Grazie, e' tutto quello che mi serviva sapere. Ci vediamo.}
{410}{}{Ma guarda chi si vede, fanculo. Il buon samaritano che ha "salvato i bambini" ha deciso di onorarmi della sua presenza.
 Sai, anch'io sono un bravo Samurai-itan -- mi prendevo cura di quei piccoli paisanos e tutto il resto. Cioe', finche' non sei arrivato tu
 a trasformare quella cazzo di idea dell'orfanotrofio in realta'.}
{411}{}{Ma guarda chi si vede, fanculo. La buona samaritana che ha "salvato i bambini" ha deciso di onorarmi della sua presenza.
 Sai, anch'io sono un bravo Samurai-itan -- mi prendevo cura di quei piccoli paisanos e tutto il resto. Cioe', finche' non sei arrivata tu
 a trasformare quella cazzo di idea dell'orfanotrofio in realta'.}
{412}{}{Vendi fiori?}
{413}{}{Sembra che non ti piaccia il fatto che i bambini non vaghino piu' per strada.}
{420}{}{Ehi, non fraintendermi. La vita per strada e' dura per quei bambini, ma e' la fine del nostro piccolo accordo che mi butta giu'.}
{421}{}{What arrangement?}
{422}{}{Intendi che borseggiavano la gente e ti portavano gli oggetti da vendere.}
{430}{}{Non fare lo spiritoso con me, stronzo. I bambini mi portano oggetti che *trovano.* Non so dove li prendono e, sinceramente, non me ne frega un cazzo.}
{431}{}{Right.}
{432}{}{Sei pieno di merda. Sono stufo di feccia come te che usa gli altri per il proprio tornaconto. E' ora di morire!}
{440}{}{Fi-o-i, ti sa, i bambini. I miei bambini.}
{441}{}{E avevi un accordo con loro?}
{450}{}{Mi portano la roba che trovano. Piccole, piccole cose. Roba che nessuno usa piu'. In cambio, io mi prendo cura di loro.}
{451}{}{Sembra un ottimo accordo.}
{460}{}{Gia'... gli affari andavano bene finche' non sei arrivato tu. Vedi, la tua piccola trovata mi costera'. I miei affari ne risentiranno grazie a te.
 Per questo, non mi stai molto simpatico. Anzi, ti odio proprio. Ma sono un uomo d'affari, quindi se devi barattare,
 fallo. Altrimenti, vaffanculo.}
{461}{}{Alright, let's see what you have in stock then.}
{462}{}{I think I have all I need. Goodbye.}
{463}{}{I think I'll stay... and kick your ass.}
{470}{}{Ancora tu? Spero che tu sia qui per fare qualche buon affare, perche' mi sto rompendo il cazzo di guardarti.
 Anzi, vomito un po' in bocca ogni volta che vedo la tua faccia. E' cosi' che mi fai schifo. E se non sei qui per
 commerciare, allora ti suggerisco di girarti e levarmi dal cazzo.}
{471}{}{Barattiamo.}
{472}{}{Ero solo curioso. Beh, ci vediamo, Flick.}
{480}{}{You done wastin' my time?}
{481}{}{Let me take another look.}
{482}{}{That should do it. Goodbye Flick.}
