{100}{}{You see a middle aged man.}
{101}{}{He is unshaven and reeks of alcohol.}
{102}{}{*hickup* Do I know you?}
{103}{}{It's 11 O'clock. Do you know where your children are?}
{104}{}{(Ti guarda assonnato) Cosa? *hic* Sono gia' le undici?}
{105}{}{In realta' no, non lo sono, volevo solo dirlo. Ma seriamente, sai dove sono i tuoi figli?}
{106}{}{In realta' si', lo sono, ma non e' importante adesso. Seriamente, sai dove sono i tuoi figli?}
{107}{}{*hic* Ho dei figli? *hic* Oh si', e' vero. Lui... o lei... *hic* dovrebbe essere qui da qualche parte.}
{108}{}{Wow, sei proprio un ubriacone. Beh, per fortuna sto lavorando a un modo per portare via tuo figlio da qui.}
{109}{}{(Ignora quello che hai appena detto.) Si', fantastico. *hic* Ora fammi tornare al mio drink.}
{110}{}{Sei un eroe per tutti i padri la' fuori. Continua cosi'!}
{111}{}{zzzZZZZzzz...}
{112}{}{zZZZZzzZZzzz...}
{113}{}{*borbotta*}
{114}{}{Can't you see I'm drinking here? *hickup*}
{115}{}{Don't bother me. *hickup*}
{116}{}{In realta' e' un po' prima delle undici, ma non e' importante adesso. Seriamente, sai dove sono i tuoi figli?}
{117}{}{In realta' e' un po' dopo le undici, ma non e' importante adesso. Seriamente, sai dove sono i tuoi figli?}
