{100}{}{Vedi un bambino.}
{101}{}{Vedi un bambino. Sembra felice.}
{102}{}{Vedi una bambina. Sembra felice.}
{200}{}{Ciao, signore!}
{201}{}{Scusa se ho provato a rubarti.}
{202}{}{Mi piace davvero stare qui.}
{203}{}{Grazie per aver aiutato Mom ad avviare questo posto!}
{300}{}{Salve, signora!}
{301}{}{Scusa se ho provato a rubarti.}
{302}{}{Mi piace davvero stare qui.}
{303}{}{Grazie per aver aiutato Mom ad avviare questo posto!}
