{100}{}{You see a resident of The Den.}
{101}{}{You see a resident of The Den.}
{102}{}{Salve.}
{103}{}{E' bello vederti.}
{104}{}{Not from around here, are you?}
{105}{}{Mamma e' una gran bella persona, vero?}
{106}{}{Sono contento che gli orfani del Den abbiano un posto dove vivere adesso.}
{200}{}{Hi mister!}
{201}{}{I'm glad the other kids aren't stealing anymore.}
{300}{}{Hi miss!}
{301}{}{I'm glad the other kids aren't stealing anymore.}
{400}{}{Vedi un ragazzino.}
{401}{}{You see a small girl.}
