{100}{}{Vedi un abitante del Den.}
{101}{}{Vedi un abitante del Den.}
{102}{}{Salve.}
{103}{}{E' bello vederti.}
{104}{}{Non sei di queste parti, vero?}
{105}{}{Mamma e' una gran bella persona, vero?}
{106}{}{Sono contento che gli orfani del Den abbiano un posto dove vivere adesso.}
{200}{}{Ciao, signore!}
{201}{}{Sono contento che gli altri bambini non rubino più.}
{300}{}{Salve, signorina!}
{301}{}{Sono contento che gli altri bambini non rubino più.}
{400}{}{Vedi un ragazzino.}
{401}{}{Vedi una bambina.}
