{100}{}{You see a resident of The Den.}
{101}{}{You see a resident of The Den.}
{200}{}{Salve e benvenuto a- Ehi! Sei tu quello che ha aiutato a rendere possibile questo posto. La gente del Den apprezza davvero
 quello che hai fatto.}
{201}{}{It was my pleasure. How are the children?}
{202}{}{Stanno bene. Grazie a te, sono fuori dalle strade e ora hanno un posto dove vivere. Gli occupanti con cui hai trattato
 sono anche un grande aiuto qui. Grazie ancora per tutto!}
{203}{}{Stanno bene. Grazie a te, sono fuori dalle strade e ora hanno un posto dove vivere. Grazie ancora per tutto!}
{204}{}{Glad to hear it. Take care.}
{205}{}{Hello again! Help you with something?}
{206}{}{Nope, just looking around.}
