{100}{}{Vedi un vecchio diario.}
{101}{}{Sembra essere un diario appartenuto a una giovane ragazza. La scritta sul risvolto interno dice: "Di proprieta' di Anna"
 La maggior parte delle pagine e' strappata o sbiadita, ma una e' ancora leggibile. "Giorno 271: Oggi mia madre mi ha dato un medaglione d'oro.
 E' la cosa piu' bella che abbia mai posseduto. Non me ne separero' mai."}
{102}{}{Il vecchio diario e' troppo fragile per essere maneggiato.}
