{100}{}{You see MIBoba Fe88.}
{101}{}{You see a tough, ruthless bounty hunter.}
{110}{}{Vedi un duro e spietato cacciatore di taglie. Non sembra che parli molto. Ha aiutato con i nuovi script e le idee. E con l'uccidere persone.}
{200}{}{You see Hivan Zolo.}
{201}{}{Un farabutto dall'aspetto trasandato, ma affascinante.}
{210}{}{Ragazzo, ho volato da un lato all'altro di questa galassia, e ho visto un sacco di roba strana, ma non ho mai visto *nulla* che mi faccia credere che ci sia una Forza onnipotente che controlla tutto.
 Perche' nessun campo di energia mistico controlla *il mio* destino. E' tutta una questione di trucchi semplici e sciocchezze. Religioni bizzarre e armi antiche non valgono un buon blaster al tuo fianco. Capisco quando uno e' bravo
 con una pistola, quindi prendi questo. Fidati: tornera' utile quando hai una taglia sulla testa. (Ti porge un blaster.)}
{211}{}{My real name is Ivan Zaharath.}
{212}{}{Ho tradotto l'RP in Polski a beneficio della grande e potente Repubblica di Polonia... voglio dire Alleanza Ribelle.}
{213}{}{Ridi pure, pallone di pelo.}
{214}{}{Religioni bizzarre e armi antiche non valgono un buon blaster al tuo fianco, ragazzo.}
{215}{}{Chi stai chiamando 'dall'aspetto trasandato'!?}
{300}{}{You see Contie-bacca.}
{301}{}{He looks like a walking carpet.}
{310}{}{Roow rooo arrrrr rooow.}
{311}{}{Rrrrrrrrrrrrr .... squeak!}
{312}{}{Nowrrrrragh.}
{313}{}{Yawrrrk!}
{314}{}{Roow rooo Nowrrrrragh!}
{315}{}{Dice di chiamarsi Continuum, e ha creato grafica nuova e unica.}
{316}{}{Dice di averli creati usando la modellazione 3D. E' piuttosto intelligente, sai. Per essere un umano.}
{317}{}{Dice che non sta parlando in ceco, anche se suona un po' come il linguaggio dei bambini.}
{318}{}{Dice che non e' una balestra, e' un blaster. E no, non puoi averlo.}
{319}{}{He says you should thank him for bringing the sub back into the game.}
{400}{}{You see Darek Vader.}
{401}{}{Questo tipo sembra duro come la roccia e appare piu' macchina che uomo.}
{410}{}{Sono Darek. Ho aiutato a rispondere a un milione di domande da novellino per Obi-Wan-Killap.}
{411}{}{Unisciti a me! Insieme possiamo governare la galassia!}
{412}{}{Sapevi che il grande Obi-Wan-Killap ha chiesto aiuto a ME?}
{413}{}{Non dirlo a Obi-Wan-Killap, ma penso che stia perdendo il senno.}
{414}{}{Ho aiutato a schiacciare diversi bug fastidiosi. Puoi ringraziarmi dopo.}
{500}{}{You see Jotisz the Hutt.}
{501}{}{Questo tipo e' grande, grasso e verde.}
{510}{}{Sono Jotisz lo Hutt. Potrei sembrare una grossa lumaca verde e grassa, ma ho effettivamente aiutato a creare quei bei nuovi abiti corazzati che indossa il tuo amico Sulik.
 Sono stati creati da Yosan12 e da me. Lo so! E con queste manine tozze!}
{511}{}{Sono Jotisz lo Hutt. Potrei sembrare una grossa lumaca verde e grassa, ma ho effettivamente aiutato a creare quei bei nuovi abiti corazzati del tuo amico... ehi dov'e'
 Sulik? Dovresti andare a prenderlo e vedere come appare. I suoi abiti sono stati creati da Yosan12 e da me. Lo so! E con queste manine tozze!}
{512}{}{*fischietta* Sono una grossa lumaca verde e grassa...}
{513}{}{In case you didn't notice, I'm suspiciously easy to strangle.}
{514}{}{Now, where did I put Leia...?}
{600}{}{You see R2Qwerty.}
{601}{}{Un robotino vivace. Lampeggia e bippa.}
{610}{}{Beep beep!}
{611}{}{Rrrrrr bip Rrrrwow!}
{612}{}{*lampeggia e si agita eccitato*}
{613}{}{Balestre! Tattiche! Balestre!}
{700}{}{You see Chris3ParksO.}
{701}{}{Un robot umanoide dorato e lucente. Sembra sorpreso.}
{710}{}{Salve, sono Chris3ParksO, relazioni umano-cyborg. Sono esperto in oltre 3 milioni di linguaggi di programmazione.}
{711}{}{Ho aiutato a gettare le basi per la Tribu' Umbra e l'EPA.}
{712}{}{Questo e' R2QWERTY: il mio fedele assistente. Ha creato nuove creature e grafica.}
{800}{}{You see Yosan12.}
{801}{}{Un ometto verde. Sembra VECCHIO.}
{810}{}{Yosan12 sono io. Creato la mod dell'armatura degli NPC ho. Sollevato l'Xwing dalla palude ho fatto anche io. Parlare in modo molto strano anche faccio io.
 Difficile da capire, hmmm? Hagh Hah ha! Inoltre, create le nuove animazioni di Cecchino, Wakizashi e spada laser ho. }
{811}{}{Ricorda: rabbia, paura, odio: del lato oscuro sono essi.}
{812}{}{Quando andato sono io, un piccolo fantasma luminoso e sfocato diventero'.}
{813}{}{Un tempo, un burattino con saggezza e carattere ero io. Ora, un personaggio CGI vuoto per i bambini sono diventato.}
{814}{}{Stupido JarJar Binks e'.}
{900}{}{You see Obi-Wan-Killap.}
{901}{}{Sembra un vecchio bonario con qualcosa di vagamente orso in lui.}
{910}{}{Greetings }
{911}{}{. Vedo che te la sei cavata abbastanza bene. Sono Obi-Wan-Killap: faccio funzionare Fallout come avrebbe dovuto fin dall'inizio.}
{912}{}{Wow. Be', grazie per questo, Sig. Killap. Come l'ha fatto?}
{913}{}{What the Hell is Fallout?}
{914}{}{Ok. E chi sono, di grazia, queste altre persone?}
{920}{}{Sono un Maestro della Programmazione, esperto nella via del Sorgente. E' un campo energetico creato da tutte le cose digitali. Ci circonda e ci penetra.
 Tiene insieme la galassia. Tu, io - l'albero - la roccia. Esseri pixelati siamo....non questa rozza materia *ti punge*.
 Ho imparato a usare questo potere attraverso anni di fissare uno schermo di computer.}
{921}{}{Wow. Il nostro sciamano diceva sempre che c'era piu' in questo mondo di quello che posso vedere, sentire, toccare, gustare e percepire. Puoi insegnarmi a usare il potere del Sorgente?}
{922}{}{Penso di aver sentito abbastanza gergo religioso da tenermi rifornito per un altro inverno nucleare. Francamente, preferisco una pistola al plasma al mio fianco.}
{923}{}{Oh great, another kookie religious nutbag. I'm outta here.}
{930}{}{Fallout e' il mondo in cui ti trovi. L'ho creato io, o almeno, l'ho fatto funzionare come avrebbe dovuto. Vedi, non
 molto tempo fa, questo mondo era nel caos. I viaggiatori che venivano qui venivano spesso uccisi dall'enorme numero di bug che vagavano
 per le Lande corrompendo i salvataggi indiscriminatamente. Gli dei di questo mondo erano stati negligenti. Ma poi sono arrivato io, e,
 usando il potere del Sorgente, io e i miei amici abbiamo ripulito le Lande. Si potrebbe dire che sono il salvatore. Sono visto da
 molti come un eroe: L'Uomo Orso.}
{931}{}{Capisco. Be', in realta', avevo l'impressione di essere l'eroe di questa storia. Giro a saccheggiare roba e ammazzare gente - sai - eroicamente. Oh, e parlo con loro a volte, ma quella parte puo' diventare stancante.
 Clicco velocemente per arrivare alla parte divertente.}
{932}{}{Ottimo lavoro, Sig. Killap. Apprezzo davvero tutto il tempo e il duro lavoro che hai speso per ripulire le Lande. Se quello che dici e' vero, allora dovresti sapere che anch'io sono un eroe. In effetti, ho schiacciato parecchi bug anch'io.}
{935}{}{E siamo grati che tu abbia distrutto l'Enclave. Tu sei il vero eroe qui.}
{936}{}{Whatever gets you through the day.}
{937}{}{So, how exactly did you clean up this world?}
{938}{}{Who, pray tell, are these other people?}
{940}{}{Questi sono i miei compagni. Mi hanno aiutato a migliorare questo mondo: MIBoba Fe88, Hivan Zolo, Contie-bacca, Darek Vader, Jotisz lo Hutt,
 R2Qwerty, Chris3ParksO, Yosan12, Imperatrice Timeslip, Luke Skynet, Mon-Morticia, Kanhef, HawkEyE, Adam Dravean, Sig. Wolna, encinodude,
 Minigun Jim, Bofast, Pixote, Mash, Mikael Grizzly, x'il, Per, e le Masse. Hanno tutti aiutato nel grande progetto per ripristinare
 questo mondo dall'infestazione di bug. L'unico bug buono e' un bug morto.}
{941}{}{Hmm. Quei nomi suonano in qualche modo familiari... Be', penso che vada a parlare con loro.}
{950}{}{Certo che posso. Devi imparare a usare i tuoi sentimenti: lascia andare la tua mente cosciente. Spegni il monitor. Chiudi gli occhi, e SENTI il Sorgente scorrere attraverso il mouse... (Segui le sue istruzioni.)}
{951}{}{Ti manca l'esperienza per iniziare l'addestramento. Torna da me quando avrai imparato almeno la Programmazione di base, giovane padawan.}
{960}{}{As you wish, young }
{961}{}{. Ma prima di andare per la tua strada, ricorda questo: molte delle verita' a cui ci aggrappiamo dipendono molto dal nostro punto di vista. Ora vai, e che il Sorgente sia con te.}
{962}{}{. Le tue azioni nella tua missione ti hanno dimostrato buono, gentile e onesto. Prendi questo per aiutarti nella tua lotta contro il Lato Oscuro: e' la spada laser del tuo antenato. Questa e' l'arma di un Cavaliere Java.
 Non cosi' goffa o casuale come un blaster; un'arma elegante per un'era piu' civilizzata. E anche se potresti essere tentato di usarla per tagliare arbitrariamente le persone a meta' per divertimento, dovresti usarla solo al servizio del bene.
 Buona fortuna, e che il Sorgente sia con te, amico mio.}
{963}{}{Cosa?! Il mio antenato, l'Abitante del Vault, ne aveva una?! Non ricordo di averla trovata in Fallout 1! *corre a controllare*}
{964}{}{Grazie, Sig. Bear Dude. Per tutto. Che il Sorgente sia con te anche.}
{1000}{}{You see Empress Timeslip.}
{1001}{}{You see a mean-looking cloaked figure with a stoop.}
{1010}{}{Sono l'Imperatrice Timeslip. Sono una Maestra della Programmazione, esperta nella via del Sorgente. Sono stata io a permettere alle spie di Obi-Wan-Killap di rubare le mie
 correzioni al motore per migliorare notevolmente la stabilita' di questo mondo, e correggere gli STUPIDI ED INSENSATI ERRORI lasciati dagli originali.}
{1011}{}{Davvero, mio maestro. Parlami di te, oh grande.}
{1012}{}{Wow. Sei inquietante. E la tua faccia e' orribile.}
{1013}{}{That's nice. Gotta go.}
{1020}{}{Posso cambiare cio' che e' hardcodificato nel Sorgente con il solo pensiero, e determinare il destino di interi universi!
 Un'intera legione delle mie migliori correzioni di bug ti attende nel resto della tua avventura. Sono la maestra del Lato Oscuro del Sorgente.}
{1021}{}{Silenzio! Anni di lavoro nel buio potrebbero aver distorto il mio aspetto, ma in questa mente ci sono i poteri di un Dio! Usando il Sorgente creo il meteo, ho dominato interi mondi e modifico cio' che non puo' essere modificato!
 Sono stata io a permettere alla Malvagia Beth di dominare il mondo degli RPG con le mie mod. Tutto cio' che e' accaduto e' avvenuto secondo I MIEI desideri.}
{1022}{}{Sorgente? Che tipo di sorgente? Stai dicendo che cucinare e' la chiave per controllare l'universo? Come vuoi, chef.}
{1023}{}{Si' si'. Accidenti, come vuoi. Penso che me ne vada adesso.}
{1024}{}{Eh, ok. Fantastico. Be', devo andare... ehm... annaffiare le mie piante...}
{1030}{}{Sciocco ignorante. La tua eccessiva sicurezza e' la tua debolezza, e la mia fede nei tuoi amici e'... ehm... mia. *sembra confusa* Sparisci dalla mia vista!}
{1040}{}{Aspetta! Te ne andrai SE e QUANDO lo decidero' io. Nel caso non te ne fossi accorto, sei stato estremamente malvagio nella tua missione.
 Il tuo odio ti ha reso potente e il tuo personaggio si e' sviluppato secondo i miei desideri. Rabbia, paura, odio... del lato oscuro sono essi.
 Ora diventerai il mio apprendista e occuperai il tuo posto AL MIO FIANCO!}
{1041}{}{As you wish, my master. I'm at your bidding.}
{1042}{}{Not interested. Bye.}
{1045}{}{Vai e semina il caos, figlio mio.}
{1046}{}{Begone!}
{1050}{}{Ecceeeellente. Allora prendi quest'arma Java. Usala. Uccidi indiscriminatamente. USA I TUOI SENTIMENTI AGGRESSIVI, FIGLIO! (Ti porge una spada laser rossa.)}
{1051}{}{Quindi.... in pratica continuo come ho fatto finora. Nessun problema. Ciao!}
{1052}{}{I will not fail you, my master.}
{1053}{}{Kill everything? you mean ... even the children?}
{1060}{}{SOPRATTUTTO i bambini.}
{1100}{}{You see Luke Skynet.}
{1101}{}{Una figura incappucciata dall'aria tranquillamente sicura di se'.}
{1110}{}{I'm Luke Skynet: I'm here to rescue you.}
{1111}{}{Rescue me?}
{1112}{}{Do I look like a princess? What do you mean 'rescue'?}
{1113}{}{Giusto. Penso che tu sia quello che ha bisogno di essere salvato, amico... dalla tua stessa carriera cinematografica. Ciao.}
{1120}{}{Si', sono qui per salvarti. Ho creato le basi di cio' che vedi all'Abbazia, e li' troverai la salvezza. Li' troverai la luce!}
{1121}{}{In realta' ci sono gia' stato. Ho 'salvato' un sacco di roba dal perdersi in tutti quei cassetti e contenitori.}
{1122}{}{Amen fratello. Grazie per aver contribuito alla creazione di quel luogo di pace e conforto. E proprio quando avevo bisogno di riposare i miei piedi irradiati e cercare un rinnovamento spirituale.}
{1123}{}{Ricordo quel posto. Nessuno sciamano qualificato pero', e niente erbe-superbe. Non so di chi sia l'idea di centro spirituale, ma non e' la mia.}
{1124}{}{Oh? And where is this place that can rescue me?}
{1125}{}{Cu-cu'! Ciao ciao!}
{1130}{}{You should return there again. It is a safe haven in these harsh Wastes.}
{1131}{}{I'm on my way, Mr. Skynet. Thanks for everything. Goodbye.}
{1132}{}{Be', penso che DOVRESTI andarci tu, Skybrain, e restare li'. Me ne vado. Strambo.}
{1135}{}{Ecco. (Te lo mostra sul Pip-Boy). Dovresti andarci adesso.}
{1138}{}{The Abbey is a place of solitude.}
{1139}{}{Be careful out there.}
{1200}{}{You see Mon-Morticia.}
{1201}{}{A very diplomatic looking lady.}
{1210}{}{Ho aiutato a scrivere una guida per aiutare tutti i novellini nelle loro nuove avventure in questo mondo migliorato.}
{1211}{}{Cazzo! Sono dalla parte sbagliata! Non ero mai del tutto sicuro da che parte avrei dovuto stare.}
{1212}{}{Il mio sedere sembra grosso con questo?}
{1213}{}{L'Imperatrice Timeslip ha commesso un errore critico e il momento del nostro attacco e' arrivato. *strizza l'occhio*}
{1300}{}{You see Kanhef.}
{1301}{}{Now HE looks like a great guy.}
{1310}{}{Sono fondamentalmente l'helpdesk di NMA.}
{1311}{}{I'm not with these weirdoes.}
{1312}{}{Accidenti. Perche' il n. 23 e' sempre in ritardo?}
{1313}{}{Nel caso non lo sapessi, sono semplicemente un tipo utile a tutto tondo.}
{1400}{}{You see HawkEyE.}
{1401}{}{Una gemma scintillante di odio.}
{1410}{}{Bonjour. Je suis Hawk-Eye. J'ai translate le version Francais. }
{1411}{}{Sono Hawk-EyE. Ho guidato la traduzione della versione francese. Vive la France!!}
{1412}{}{Mi piace mangiare .... pesciolini cosi' dolciii!}
{1413}{}{Nobody here but us chickens.}
{1500}{}{You see Adam Dravean.}
{1501}{}{He nods in your direction.}
{1510}{}{Sono il Sig. Wolna. Ho guidato la traduzione della versione tedesca.}
{1511}{}{[per favore schiaffeggiami!!]}
{1512}{}{Ottimo lavoro, ragazzi! Continuate cosi'!}
{1513}{}{Look! A golden Eagle!}
{1514}{}{Ich komme aus…Vengo da… Deutschland! Io Tedesco!}
{1600}{}{You see Mr. Wolna.}
{1601}{}{Questo tipo e' seriamente entusiasta...}
{1610}{}{[Si toglie l'elmo e butta via il mantello cremisi, rivelando un uomo dall'aspetto rozzo ma affascinante con la testa rasata e una giacca di pelle. Sembra emanare carisma e grandiosita'.] Ehi straniero, mi chiamo Adam. Come va?}
{1611}{}{Abbastanza bene. E' stata una strada accidentata, ma sono finalmente arrivato alla fine.}
{1612}{}{I don't have time for this. Bye.}
{1620}{}{Bello sentirlo. [Si guarda intorno, poi corruga la fronte.] Dov'e' Dex? Ho passato un sacco di tempo a scrivere i dialoghi di quel tipo, e non lo stai nemmeno usando? [Sospira pesantemente e scuote la testa.]}
{1621}{}{Dex? Wrote his dialogue? What are you talking about?}
{1630}{}{Bello sentirlo. Scusami un momento. [Va da Dex, gli da' il cinque, poi torna da te.] Sono contento di vedere che tu e il mio amico Dex siate rimasti insieme. Sai che ho passato un sacco di tempo a scrivere i dialoghi di quel tipo.}
{1631}{}{How do you know Dex? And you "wrote his dialogue"? What are you talking about?}
{1640}{}{Senti, non preoccupartene. Ma se mai dovessi decidere di intraprendere un'altra epica missione, assicurati di passare dall'EPA. C'e' un sacco di roba da fare la' e se giochi bene le tue carte, potresti trovare un nuovo compagno. [Ti guarda e sorride.] Si', sei proprio il tipo di Dex, quindi sarete sicuramente amici.}
{1641}{}{Grazie. Me ne ricordero'.}
{1650}{}{Senti, non preoccupartene. Ma se mai dovessi decidere di intraprendere un'altra epica missione, assicurati di passare dall'EPA. C'e' un sacco di roba da fare la' e se giochi bene le tue carte, potresti trovare un nuovo compagno. [Ti guarda.] Probabilmente dovrai cambiare atteggiamento se vuoi fare amicizia con Dex. Preferisce che i suoi compagni siano un po' piu'... moralmente compromessi.}
{1651}{}{Grazie. Me ne ricordero'.}
{1660}{}{[Annuisce e guarda lontano.] Sai, Dex non e' stato il mio unico contributo. Ho anche aiutato l'Uomo Orso a migliorare questo mondo servendo come consigliere, tester e custode del canone e dell'intento originale. Ma soprattutto, sono stato incaricato di portare tutti i nuovi dialoghi delle Lande al livello giusto. E' stato un lungo cammino, ma se me lo chiedi, questa cosa e' venuta fuori dannatamente bene. [Ti guarda di nuovo e sorride.]}
{1661}{}{Whatever. I'm tired of listening to this. Bye.}
{1662}{}{E' molto nobile da parte tua. Hai fatto un lavoro notevole. Prenditi cura di te. Ciao.}
{1670}{}{*Guarda i membri del tuo gruppo* Stai bene, Dex.}
{1671}{}{Tieni d'occhio Dex, ok? Non voglio che si metta nei guai. Dopotutto, e' una mia creazione.}
{1672}{}{You're welcome for cleaning up the dialogue of the wastes.}
{1673}{}{Ehi, dov'e' Dex? Ho menzionato che sono il suo creatore?}
{1700}{}{You see encinodude.}
{1701}{}{He looks like a good guy.}
{1710}{}{*Guarda i membri del tuo gruppo* Stai bene Kitsune.}
{1711}{}{Tieni d'occhio Kitsune, hai capito. Non voglio che si metta nei guai. E' una mia creazione, sai.}
{1712}{}{I helped out with the sub, you know.}
{1713}{}{Ehi, dov'e' Kitsune? Ho scritto i suoi dialoghi, sai.}
{1714}{}{I helped out with the sub, you know.}
{1800}{}{You see Minigun Jim.}
{1801}{}{Indossa una maglietta dei Red Dwarf sotto l'armatura.}
{1810}{}{*Guarda i membri del tuo gruppo* Stai bene Cat.}
{1811}{}{Tieni d'occhio Cat, hai capito. Non voglio che si metta nei guai. E' una mia creazione, sai.}
{1812}{}{Ehi, dov'e' Cat? Ho scritto i suoi dialoghi, sai.}
{1900}{}{You see Bofast.}
{1901}{}{He stands up straight as he sees you looking at him.}
{1910}{}{Bravo per aver portato una fine pacifica ai Predoni che attaccavano Vault City. Ho aiutato a rendere possibile tutto cio'.}
{1911}{}{Non dovevi uccidere tutti quei Predoni che attaccavano Vault City. Ora esiste una soluzione pacifica, grazie a me.}
{2000}{}{You see Pixote.}
{2001}{}{You see a noble repair bot.}
{2010}{}{[Il robot annuisce mentre ti avvicini.] Salve. Stai godendo il tuo tempo in questo mondo?}
{2011}{}{Yes I am. Thanks for asking.}
{2012}{}{Not really. Things could be better.}
{2013}{}{I'm not in the mood to chat. Bye.}
{2020}{}{Bello sentirlo! Spero che tutto il duro lavoro che ho fatto per rendere ogni luogo il piu' unico e dettagliato possibile sia in qualche modo responsabile della tua felicita'. E' stato un gran lavoro sistemare tutto, ma l'atmosfera e l'aspetto generale sono di prima qualita' ora. Non sei d'accordo?}
{2021}{}{Oh, assolutamente. Tutto sembra fantastico. Sei davvero talentuoso!}
{2022}{}{Meh, it's alright.}
{2023}{}{That's nice. Bye.}
{2030}{}{Mi dispiace sentirlo. Forse non hai dato un'occhiata attenta al mondo intorno a te. Ho fatto molto
 per rendere ogni luogo il piu' unico e dettagliato possibile. Forse se guardi i dettagli, questo ti tirera' su il morale.
 E' stato un gran lavoro sistemare tutto, ma l'atmosfera e l'aspetto generale sono di prima qualita' ora.
 Non sei d'accordo?}
{2031}{}{Now that you mention it, I did notice things look a lot nicer now.}
{2032}{}{Didn't really notice.}
{2033}{}{That's nice. Bye.}
{2040}{}{[Il robot si dondola avanti e indietro di gioia.] Sono contento che ti piaccia. Be', devo andare adesso. Ho altre chicche
 da scatenare su questo mondo.}
{2041}{}{Alright. Take care.}
{2050}{}{[La testa del robot si abbassa con tristezza.] Be', suppongo che il mio lavoro non sia per tutti. Ora, se mi scusi,
 devo andare. Ho altre chicche da scatenare su questo mondo.}
{2051}{}{Vabbe'. Ci vediamo.}
{2060}{}{Mi piace tanto creare cose nuove.}
{2061}{}{Cosi' tanti nuovi dettagli adesso. Cosi' bello.}
{2100}{}{You see Mash.}
{2101}{}{He nods at you.}
{2110}{}{Saluti! Contento che tu sia arrivato fin qui. Spero che tu stia apprezzando la visibilita' espansa di questo mondo. Non abbastanza
 di questo mondo poteva essere mostrato in un solo momento. Ho cambiato tutto cio' pero'. L'Imperatrice Timeslip ed io siamo maestri del
 Sorgente. Lei ed io abbiamo portato questo vecchio mondo in una nuova era.}
{2111}{}{Wow, grazie per questo. Tutto e' molto meglio. A volte un po' troppo piccolo, ma posso facilmente regolarlo.}
{2112}{}{I don't have time for this. Bye.}
{2120}{}{Sono contento che tu stia apprezzando il mio duro lavoro. Ho anche reso possibile cambiare aspetto. Non sei piu' bloccato
 con una razza o un tipo di capelli specifici. Yosan12, x'il e altri hanno creato gli aspetti fisici stessi, ma io, con l'
 aiuto dell'Imperatrice Timeslip, ho scavato a fondo nel Sorgente per rendere tutto possibile. Vedo che hai approfittato di questa
 nuova abilita'. Eccellente!}
{2121}{}{Oh, adoro il mio nuovo aspetto. Grazie per questo!}
{2122}{}{Right. Goodbye.}
{2130}{}{Sono contento che tu stia apprezzando il mio duro lavoro. Ho anche reso possibile cambiare aspetto. Non sei piu' bloccato
 con una razza o un tipo di capelli specifici. Yosan12, x'il e altri hanno creato gli aspetti fisici stessi, ma io, con l'
 aiuto dell'Imperatrice Timeslip, ho scavato a fondo nel Sorgente per rendere tutto possibile. Vedo che non hai approfittato di
 questa funzione. Sappi solo che e' li' e disponibile. Un ottimo posto per provarla e' all'EPA. Oh, che divertimento!}
{2131}{}{I'll keep that in mind. Thanks.}
{2132}{}{Right. Goodbye.}
{2140}{}{Most excellent. Well, you take care.}
{2141}{}{Arrivederci.}
{2142}{}{Ci si vede.}
{2150}{}{Il Sorgente e' complicato, ma riesco a gestirlo.}
{2151}{}{Goditi la visibilita' espansa di questo mondo!}
{2152}{}{Enjoy the new you!}
{2200}{}{You see Mikael Grizzly.}
{2201}{}{This animal is extremely furry.}
{2210}{}{Salve. Ho aiutato a riportare il sottomarino in questo mondo.}
{2211}{}{Ti piace quanto sono peloso? A me si'.}
{2212}{}{Hope you enjoyed the sub.}
{2300}{}{You see x'il.}
{2301}{}{He looks at you with admiration.}
{2310}{}{Ho aiutato molto con gli aspetti delle creature. Spero che tu l'abbia apprezzato!}
{2311}{}{Bei capelli, amico. Ho contribuito a renderlo possibile.}
{2400}{}{You see a pile of rocks.}
{2401}{}{There is a plaque on the rocks.}
{2410}{}{C'e' una targa sul mucchio di rocce. Recita: "Dedicato a Per Jorner. Maestro delle guide,
 Re delle lucertole, e Accumulatore di tutte le rocce.}
{2500}{}{You see a large mass of goo.}
{2501}{}{Questa massa di melma sembra formare una scritta: "Dedicato a tutti coloro i cui nomi sono stati dimenticati, ma
 che hanno comunque contribuito a rendere tutto possibile."}
{2510}{}{}
{5000}{}{Combat is not allowed here.}
