{100}{}{Vedi un uomo che indossa un'armatura da combattimento.}
{101}{}{Vedi Kaga in armatura da combattimento.}
{102}{}{Indossa un'armatura da combattimento e sembra avere delle armi decenti.}
{103}{}{Questa volta sono pronto ad affrontarti.}
{104}{}{Il prescelto non ritornera' mai piu' ad Arroyo!}
{105}{}{Kaga ti schiaccera'!}
{106}{}{Kaga non ha paura di nessuno!}
{107}{}{Stai ferno, cosi' Kaga puo' prendere bene la mira.}
{108}{}{Ci rivedremo!}
{109}{}{Questa non sara' l'ultima volta che vedrai Kaga.}
{110}{}{Kaga ha sicuramente bisogno di allenarsi di piu'.}
{120}{}{Go away Kaga!}
{150}{}{[Un guerriero alto e possente ti sta davanti, i suoi occhi bruciano d'odio mentre ti osserva.] Quindi hanno scacciato Kaga, e poi hanno scelto TE come Prescelto? Ha! Pensi che essere il nipote dell'Abitante del Vault ti renda speciale?! Pensi di essere migliore di me, Kaga il Grande?!}
{151}{}{Well, I AM the Chosen One, aren't I?}
{152}{}{Ehi, aspetta un attimo. Non ho mai detto di essere migliore di te.}
{160}{}{Quel titolo non significhera' nulla quando Kaga ti strappera' la testa dalle spalle!}
{161}{}{Nessuna parola salvera' la tua pelle. Con la tua morte, l'onore di Kaga sara' restaurato. Ora Kaga avra' la sua vendetta!}
{200}{}{Ooglie?}
{201}{}{Cosa!? Hanno scelto *te* come Prescelto? Oh cielo, devono essere disperati.}
{202}{}{Me no likie. U lookie bad.}
{203}{}{Kaga non si degnera' nemmeno di parlarti oltre. Preparati a morire per mano di Kaga!}
