{100}{}{Vedi un uomo vestito di pochi stracci.}
{101}{}{Vedi Kaga.}
{103}{}{Indossa dei pantaloni e sembra provenire da una tribu'.}
{104}{}{Dovrei essere io il Prescelto!}
{105}{}{Come ha osato Arroyo? Cacciare ME dalla tribu'.}
{106}{}{Avro' la mia vendetta... a tue spese!}
{107}{}{Kaga ti spedira' nella vita seguente.}
{108}{}{Ci rivedremo!}
{109}{}{Non sono mai stato sconfitto prima d'ora!}
{110}{}{Dedichero' tutto me stesso alla tua distruzione.}
{150}{}{[Un guerriero alto e possente ti sta davanti, i suoi occhi bruciano d'odio mentre ti osserva.] Quindi hanno scacciato Kaga, e poi hanno scelto TE come Prescelto? Ha! Pensi che essere il nipote dell'Abitante del Vault ti renda speciale?! Pensi di essere migliore di me, Kaga il Grande?!}
{151}{}{Beh, SONO il Prescelto, no?}
{152}{}{Ehi, aspetta un attimo. Non ho mai detto di essere migliore di te.}
{160}{}{Quel titolo non significhera' nulla quando Kaga ti strappera' la testa dalle spalle!}
{161}{}{Nessuna parola salvera' la tua pelle. Con la tua morte, l'onore di Kaga sara' restaurato. Ora Kaga avra' la sua vendetta!}
{200}{}{Ooglie?}
{201}{}{Cosa!? Hanno scelto *te* come Prescelto? Oh cielo, devono essere disperati.}
{202}{}{A me no piace. Tu brutto.}
{203}{}{Kaga non si degnera' nemmeno di parlarti oltre. Preparati a morire per mano di Kaga!}
