{100}{}{Vedi un uomo che indossa un'armatura di metallo.}
{101}{}{Vedi Kaga.}
{102}{}{Gia'... e' Kaga il non-cosi-Grande. Ha un'armatura di metallo e vuole ammazzarti.}
{103}{}{Ancora tu!}
{104}{}{Mi sto stufando dei nostri continui incontri.}
{105}{}{Prescelto - hmph!}
{106}{}{Facciamola finita.}
{107}{}{Rimpiangerai di aver mai sentito il nome di Kaga!}
{108}{}{Le mie abilita' sono migliorate dall'ultima volta che ci siamo visti.}
{109}{}{Inizia a diventare una brutta abitudine.}
{110}{}{Kaga ha bisogno di allenarsi un po' di piu'.}
{111}{}{Kaga tornera'.}
{120}{}{Ci incontriamo di nuovo, Kaga.}
{150}{}{[Un guerriero alto e possente ti sta davanti, i suoi occhi bruciano d'odio mentre ti osserva.] Quindi hanno scacciato Kaga, e poi hanno scelto TE come Prescelto? Ha! Pensi che essere il nipote dell'Abitante del Vault ti renda speciale?! Pensi di essere migliore di me, Kaga il Grande?!}
{151}{}{Beh, SONO il Prescelto, no?}
{152}{}{Ehi, aspetta un attimo. Non ho mai detto di essere migliore di te.}
{160}{}{Quel titolo non significhera' nulla quando Kaga ti strappera' la testa dalle spalle!}
{161}{}{Nessuna parola salvera' la tua pelle. Con la tua morte, l'onore di Kaga sara' restaurato. Ora Kaga avra' la sua vendetta!}
{200}{}{Ooglie?}
{201}{}{Cosa!? Hanno scelto *te* come Prescelto? Oh cielo, devono essere disperati.}
{202}{}{A me no piace. Tu brutto.}
{203}{}{Kaga non si degnera' nemmeno di parlarti oltre. Preparati a morire per mano di Kaga!}
