{100}{}{Vedi un uomo che indossa un'armatura di cuoio.}
{101}{}{Vedi Kaga.}
{102}{}{Indossa un'armatura di cuoio e ha la seccante abitudine di parlare di se' in terza persona.}
{103}{}{Qeusta sara' l'ultima volta che Kaga ti incontra.}
{104}{}{After Kaga kill you, he will burn Arroyo to the ground.}
{105}{}{Assaggia l'ira di Kaga!}
{106}{}{Sono il grande Kaga!}
{107}{}{Tutti devono temere Kaga.}
{108}{}{Kaga prendera' la tua testa come trofeo.}
{109}{}{Arrenditi e la tua morte sara' rapida.}
{110}{}{Kaga tornera'!}
{111}{}{Non puoi uccidere il grande Kaga!}
{112}{}{Sei fortunato che Kaga abbia degli affari da sbrigare.}
{113}{}{Kaga ti incontrera' di nuovo.}
{120}{}{It's that Kaga guy again.}
{150}{}{[Un guerriero alto e possente ti sta davanti, i suoi occhi bruciano d'odio mentre ti osserva.] Quindi hanno scacciato Kaga, e poi hanno scelto TE come Prescelto? Ha! Pensi che essere il nipote dell'Abitante del Vault ti renda speciale?! Pensi di essere migliore di me, Kaga il Grande?!}
{151}{}{Well, I AM the Chosen One, aren't I?}
{152}{}{Ehi, aspetta un attimo. Non ho mai detto di essere migliore di te.}
{160}{}{Quel titolo non significhera' nulla quando Kaga ti strappera' la testa dalle spalle!}
{161}{}{Nessuna parola salvera' la tua pelle. Con la tua morte, l'onore di Kaga sara' restaurato. Ora Kaga avra' la sua vendetta!}
{200}{}{Ooglie?}
{201}{}{Cosa!? Hanno scelto *te* come Prescelto? Oh cielo, devono essere disperati.}
{202}{}{Me no likie. U lookie bad.}
{203}{}{Kaga non si degnera' nemmeno di parlarti oltre. Preparati a morire per mano di Kaga!}
