{100}{}{Vedi un uomo che indossa una Power-Armot Ver.II. Non sembra molto amichevole.}
{101}{}{Vedi Kaga in una Power Armor Ver.II.}
{102}{}{Un grosso blocco di metallo con braccia e armi.}
{103}{}{Sono stanco di inseguirti. Facciamola finita.}
{104}{}{Questa e' l'ultima volta che incontrerai Kaga.}
{105}{}{Sei un moscerino al confronto di Kaga.}
{106}{}{Non vedo l'ora di spedirti alla tua prossima vita.}
{107}{}{Sei stato un nemico valoroso.}
{108}{}{Questa parte delle lande non ha bisogno di un benefattore come te.}
{109}{}{Dopo che ti avro' ucciso, io saro' la persona piu' temuta di questa parte delle lande.}
{110}{}{Non vedo l'ora di tornare al villaggio, ad Arroyo - per ridurlo in cenere.}
{111}{}{Kaga sara' famoso per averti ucciso.}
{120}{}{Kagaaaaaaaa!}
{150}{}{[Un guerriero alto e possente ti sta davanti, i suoi occhi bruciano d'odio mentre ti osserva.] Quindi hanno scacciato Kaga, e poi hanno scelto TE come Prescelto? Ha! Pensi che essere il nipote dell'Abitante del Vault ti renda speciale?! Pensi di essere migliore di me, Kaga il Grande?!}
{151}{}{Beh, SONO il Prescelto, no?}
{152}{}{Ehi, aspetta un attimo. Non ho mai detto di essere migliore di te.}
{160}{}{Quel titolo non significhera' nulla quando Kaga ti strappera' la testa dalle spalle!}
{161}{}{Nessuna parola salvera' la tua pelle. Con la tua morte, l'onore di Kaga sara' restaurato. Ora Kaga avra' la sua vendetta!}
{200}{}{Ooglie?}
{201}{}{Cosa!? Hanno scelto *te* come Prescelto? Oh cielo, devono essere disperati.}
{202}{}{A me no piace. Tu brutto.}
{203}{}{Kaga non si degnera' nemmeno di parlarti oltre. Preparati a morire per mano di Kaga!}
