{100}{}{Vedi...Set.}
{101}{}{Vedi un ghoul marcescente con dei pezzi di macchinari impiantati nella testa. E' difficile stabilire se sia vecchio o meno.}
{102}{}{Vedi Set. Sta parlando da solo.}
{103}{}{Vedi Set. Sta parlando da solo.}
{104}{}{"Sotto terra!"}
{105}{}{"Sotto terra!"}
{106}{}{"Dirtnap... Fa ruggire la mia ombra."}
{107}{}{Heh-heh.}
{108}{}{Sotto.}
{109}{}{Terra.}
{110}{}{Sotto terra!}
{111}{}{Heh-heh. Necropolis e' miaaaaaaaaa.}
{112}{}{Normali. Dappertutto, normali.}
{113}{}{Il mio nome e' Set. Il tuo e' Mondolore.}
{114}{}{Chuckle-chuckle.}
{115}{}{Terra. Sotto. Terrasotto!}
