{100}{}{Vedi un ologramma.}
{101}{}{Vedi il Direttore della Scienza.}
{102}{}{Ologramma 00000. Si occupa degli aspetti scientifici dell'EPA.}
{200}{}{01001000 01100101 01101100 01110000 00100000 01101101 01100101 00100001}
{201}{}{Uh, cosa?}
{210}{}{01000101 01101100 01100101 01100011 01110100 01110010 01101001 01100011 01100001 01101100 00100000 01110011
 01101000 01101111 01110010 01110100 00101110}
{211}{}{Scusa, non ti capisco. Ciao.}
{212}{}{Interessante. Sembra che tu riesca a comunicare solo usando numeri binari. Aspetta, se scrivo quello che
 stai dicendo, forse riesco a capirci qualcosa.}
{220}{}{[Dopo un paio d'ore, credi finalmente di aver tradotto correttamente i numeri binari. Sembra che stia
 dicendo "Aiutami! Corto circuito."]}
{221}{}{Beh, e' stato divertente da decifrare. Ci si vede.}
{222}{}{Un corto circuito nel nastro, eh? Va bene, vediamo se riusciamo a sistemarti.}
{230}{}{01001000 01100101 01101100 01110000 00100000 01101101 01100101 00100001}
{231}{}{Passavo a salutare. Ci si vede.}
{232}{}{Non preoccuparti, sto lavorando per sistemarti.}
{240}{}{01010010 01100101 01100010 01101111 01101111 01110100 00100000 01101101 01100101 00100001}
{241}{}{D'accordo, mi arrendo. Scusa.}
{242}{}{Non funziona ancora? Aspetta, lascia che decifri questo.}
{250}{}{[Questa volta riesci a decodificare il messaggio molto piu' velocemente: "Riavviami!"] Oh, certo. [Riavvii la macchina
 che gestisce l'ologramma. Per passare il tempo, fischietti mentre esegue tutte le procedure di avvio.]}
{251}{}{[Continua]}
{260}{}{Per Hawking, ce l'hai fatta! Il mio programma vocale era bloccato in modalita' binaria da *anni*. Era da cosi' tanto
 che non avevo il piacere di scambiare un dialogo con un'altra mente. Penseresti che in tutto questo tempo *uno* dei miei
 colleghi avrebbe avuto la decenza di imparare il binario, ma nooo.}
{261}{}{Nessun problema--}
{270}{}{Non avevano tempo per me, capisci. Oh no, erano troppo *impegnati* a indulgere nelle loro sciocchezze burocratiche.
 Troppo impegnati a imporre regolamenti l'uno all'altro e a litigare come idioti. E guarda dove li ha portati: bloccati in un
 ciclo infinito nella sala conferenze. Ha! Ben gli sta.}
{271}{}{Bloccati in un ciclo?}
{272}{}{In realta' ho risolto io quel problema. Niente piu' cicli infiniti.}
{280}{}{Cosa? Oh, si', si', sembra che un malfunzionamento da qualche parte abbia generato un potente campo magnetico, che
 cancella la loro memoria a breve termine ogni pochi minuti, condannandoli a una sorta di purgatorio olografico. Ma lasciamo perdere,
 stiamo meglio senza di loro. Con loro intrappolati in una discussione infinita, questo lascia me, ehm, voglio dire, *noi*, a gestire
 la struttura. Con il mio intelletto supremo e il tuo corpo fisico, potremmo essere una grande squadra.}
{281}{}{Per prima cosa, perche' non mi dici esattamente che posto e' questo?}
{290}{}{Davvero? Secondo me stiamo meglio senza di loro, ma se tu la pensi diversamente chi sono io per lamentarmi. Con il mio
 intelletto supremo e il tuo corpo fisico, potremmo essere davvero una grande squadra, sai.}
{291}{}{Per prima cosa, perche' non mi dici esattamente che posto e' questo?}
{300}{}{Perche', e' l'Agenzia per la Protezione dell'Ambiente, naturalmente. Questa e' una struttura federale creata per
 regolare le sostanze chimiche e garantire la protezione dell'ambiente, ma e' diventata molto, molto di piu'! Stai
 in piedi in uno dei principali centri di ricerca sperimentale del paese. Abbiamo cosi' tante cose entusiasmanti in sviluppo.
 Certo, i progressi sono un po' lenti ultimamente, con il crollo della civilta' e tutto il resto...}
{301}{}{E' comprensibile.}
{302}{}{L'apocalisse non e' una scusa per poltrire.}
{310}{}{Si', se solo avessi un assistente in carne e ossa, potrei finalmente fare qualche progresso nella mia ricerca...}
{311}{}{Di che tipo di aiuto hai bisogno?}
{320}{}{Beh, dipende. Non credo che ti sentiresti a tuo agio a maneggiare una grossa arma sperimentale, vero?}
{321}{}{Certo che lo farei!}
{322}{}{Bene.}
{323}{}{Credo che passero'.}
{330}{}{Oh, capisco. Che peccato. Va bene, nessun rancore. Aspettero' semplicemente che un'altra persona in carne e ossa
 entri per caso in questa struttura. Succedera' di nuovo entro un secolo o due. Addio.}
{340}{}{Salve di nuovo. Non e' che hai ripensato alla mia offerta di aiutarmi a testare un'arma sperimentale?}
{341}{}{No. Mi spiace.}
{342}{}{D'accordo. Va bene.}
{350}{}{Eccellente! Sei il candidato perfetto. Vedi, nel tentativo di aiutare l'esercito a diventare piu' "ecologico",
 ho sviluppato una nuova arma che non richiede munizioni, perche' funziona completamente a *luce*. La chiamo
 *Solar Scorcher*. Tuttavia, non e' ancora stata testata alla luce diretta del sole, ed e' qui che entri in gioco tu.}
{351}{}{Quindi vuoi che esca e spari a quella cosa? Tutto qui?}
{352}{}{Si', si', dammi quella pistola e basta.}
{360}{}{Essenzialmente, si'. Ovviamente devo sapere come se la cava in una situazione di combattimento, quindi apprezzerei se
 riuscissi a trovare qualche forma di vita minacciosa la fuori, che poi potresti eliminare in modo spettacolare con il mio Solar Scorcher.}
{361}{}{Uscire e uccidere qualcosa, capito. Allora, dove si trova questo Solar Scorcher?}
{370}{}{Non cosi' in fretta, amico mio. Non voglio che tu spari a caso la fuori. Devo sapere come si comporta
 in una situazione di combattimento, quindi apprezzerei se trovassi qualche forma di vita minacciosa la fuori, che poi
 potresti eliminare in modo spettacolare con il mio Solar Scorcher.}
{371}{}{Uscire e uccidere qualcosa, capito. Allora, dove si trova questo Solar Scorcher?}
{380}{}{Oh, si', e' in quell'armadietto sul muro laggiu', vicino al mio proiettore. Il codice e' 03141879.}
{381}{}{D'accordo, lo provero' e ti faro' sapere com'e' andata.}
{390}{}{Ah, bentornato. Hai avuto modo di testare il Solar Scorcher?}
{391}{}{Eccome. Ha carbonizzato tutto.}
{392}{}{Si', l'ho fatto, ma quel pezzo di merda si e' rotto. Ho dovuto buttarlo.}
{393}{}{No, non ancora.}
{394}{}{Me ne occuperò.}
{400}{}{Eccellente! Sono felice di sapere che funziona come previsto. Grazie per avermi aiutato. Perche' non tieni
 pure il Solar Scorcher? Preferisco che venga usato piuttosto che resti qui a prendere polvere.}
{401}{}{Grazie!}
{402}{}{Bene, perche' non avevo intenzione di restituirlo comunque.}
{410}{}{Oh... capisco. Non capisco come sia possibile, quel prototipo ha resistito a test di laboratorio intensi... [Scuote
 la testa tristemente.] Comunque, grazie per avermi aiutato.}
{411}{}{Vabbe'.}
{412}{}{Nessun problema.}
{420}{}{Felice di rivederti. Tuttavia, se non ti dispiace, ho una miriade di progetti che richiedono la mia attenzione.}
{421}{}{[Fine]}
{500}{}{Hai riparato l'Ologramma 00000.}
{510}{}{Hai testato il Solar Scorcher per il Direttore della Scienza.}
