{100}{}{That's it... I think.}
{101}{}{No, ma non puo'... io, beh... hmmm...}
{102}{}{Il filo blu all'alloggiamento rosso...}
{103}{}{Those mutations are progressing nicely.}
{104}{}{It won't be long now.}
{105}{}{Just a few more drops of HCl...}
{106}{}{You see a man in a white lab coat.}
{107}{}{You see The Doctor.}
{108}{}{Il principale — e unico — dottore rimasto nell'EPA.}
{109}{}{It would be unwise to attack me.}
{120}{}{Si'?}
{121}{}{Hi, my name is }
{122}{}{. Who are you?}
{123}{}{Sorry to bother you. Goodbye.}
{130}{}{I'm known as the Doctor.}
{131}{}{Ah, giusto. Quindi cosa fai? Perche' sei qui tutto solo? Il resto del posto sembra deserto.}
{132}{}{OK, thanks.}
{140}{}{Vedo che hai abilita' adeguate nelle vie della scienza. Forse potresti capire cosa faccio qui, dopotutto. Cosa desideri sapere?}
{141}{}{Why are you here?}
{142}{}{Di che cosa ti occupi?}
{150}{}{Mi dispiace, ma non credo tu abbia le competenze necessarie per capire cosa sto facendo qui. Torna quando sarai mentalmente piu' forte.}
{151}{}{Ehi, un momento. Provero' qualsiasi cosa tu mi dia!}
{152}{}{Well, all right then. Goodbye.}
{160}{}{Facevo parte del team originale di scienziati che lavorava qui nell'EPA prima della guerra. Sfortunatamente, nessuno di loro era abbastanza competente nelle discipline scientifiche o possedeva sufficiente determinazione, e hanno dovuto andarsene. Ora, sono l'unico rimasto.}
{161}{}{Quindi, sei felice di questo? Voglio dire, di essere l'unico qui?}
{170}{}{Qualsiasi cosa io voglia, davvero. Al momento sto conducendo ulteriori ricerche genetiche su creature che ho creato per osservare gli effetti dell'FEV sui loro sistemi immunitari. Anni fa ho creato molti nuovi farmaci e ne ho adattati diversi altri, ma non lo faccio piu'.}
{171}{}{What's that about creatures you've created?}
{172}{}{What types of drugs have you made?}
{180}{}{No, non puoi. Non sei abbastanza competente nelle vie della scienza e dei potenziamenti biologici. Ora, se vuoi scusarmi, mi stai facendo perdere tempo.}
{181}{}{Assolutamente no. Mettimi alla prova.}
{190}{}{<sorride> Beh, forse e' cosi'. Va bene, se vuoi, ti daro' una possibilita'. Cosa vorresti sapere allora?}
{191}{}{Why are you here?}
{192}{}{Di che cosa ti occupi?}
{200}{}{Ma certo! Nessuno che mi controlla. Nessuna regola di alcun tipo. Faccio quello che voglio, quando voglio. Inoltre, essendo rimasto solo io qui, ho accesso a tutta l'attrezzatura di cui potrei mai avere bisogno. Altro?}
{201}{}{Who are the people over there in those cages?}
{202}{}{Che cos'e' tutto quel liquido dai colori strani che ho visto in giro per l'EPA?}
{203}{}{Where do you get all of the equipment from?}
{210}{}{Quelli nelle prime celle vicino a quel muro sono alcuni abitanti del villaggio entrati qui per sbaglio, e li ho catturati per usarli piu' avanti. Gli altri, quelli che sembrano piu' forti, sono i miei guerrieri per... emergenze.}
{211}{}{...for use later? What do you mean?}
{212}{}{Thanks. Can I ask another question?}
{213}{}{Right. Thanks. I must be going now.}
{220}{}{Sostanze chimiche e serbatoi di FEV, principalmente. Era tutto contenuto in grandi barili per essere conservato in sicurezza qui all'EPA. Sfortunatamente, c'e' stato un piccolo incidente e una grande perdita chimica ha costretto tutti ad andarsene, tranne quei tonti degli ologrammi. Alcune sostanze sono filtrate nei livelli inferiori. Ora le sto usando come materiale di sperimentazione. Finora hanno dato risultati promettenti!}
{221}{}{Che tipo di risultati? Vuoi dire che hai creato tu queste creature?}
{222}{}{So where do you get all your equipment from?}
{230}{}{Per lo piu' qui. L'EPA era stata progettata e fornita con ogni tipo di macchinario e, da quando gli altri scienziati se ne sono andati, non e' stato usato piu' nulla. Ora, dopo tanti anni, sto solo esaurendo alcune cose...}
{231}{}{Never mind. I must be going now.}
{240}{}{Droghe? Decine! Negli anni ho creato mentats, buffout, stimpak, kit medici di varie potenze, psycho e molte altre cose che non capiresti. Non lo faccio piu', comunque. Ho creato il robot Mr. Chemmie! per farlo al posto mio. Si trova nel complesso principale. Se hai davvero l'intelligenza e le capacita' scientifiche che dici, sentiti libero di usarlo per creare tutte le droghe che vuoi.}
{241}{}{What special drugs have you created?}
{242}{}{Where can I find Mr. Chemmie!?}
{243}{}{Thanks. Say, have you ever heard of Jet?}
{250}{}{Si', ho creato molte creature mentre ero all'EPA. Se sei un tipo che esplora, potresti averne incontrate alcune nelle Lande. Centauri? Flotter? Gli \"Alieni\"? Ora vagano liberamente nelle Lande. Ne ho tenute solo alcune qui e nella base principale per riferimento futuro.}
{251}{}{Un momento. Mi stai dicendo che tutte quelle creature la fuori, quelle cose che infestano le Lande e uccidono innocenti, le hai create tu?!}
{252}{}{Whoa, note to self: Do not anger the Doctor. Goodbye.}
{260}{}{'Cosa intendo?' Il Virus dell'Evoluzione Forzata, naturalmente! Sto solo iniziando a sperimentarne gli effetti sugli esseri umani. Abbiamo tutti sentito la storia del Master. Stavo pensando di fare qualcosa di simile anch'io. Un mio esercito sarebbe certamente molto utile!}
{261}{}{Non pensi che sia un po' immorale? Come puoi anche solo considerare una cosa cosi' orribile?}
{262}{}{Solo ora stai passando agli esseri umani? Su cos'altro hai lavorato allora?}
{263}{}{Well, good luck with that. I must get going now.}
{270}{}{Si', suppongo di si'. Mi diverti molto. Cos'altro posso risponderti? }
{271}{}{Tell me again about these people.}
{272}{}{What's all the funny-colored liquid around the EPA?}
{273}{}{Where do you get all the equipment and supplies for your experiments?}
{280}{}{No, no, no. Prima che tu vada, devo chiederti una cosa. Potresti farmi un piccolo favore? Non lascio la sicurezza del magazzino per paura che mi rubino qualcosa. Ho bisogno di alcune materie prime. Potresti aiutarmi?}
{281}{}{Yeah, I suppose so. What do you need?}
{282}{}{No, I'm too busy at the moment. Maybe some other time.}
{290}{}{Si', mi chiedevo cosa avrebbe fatto il virus sugli animali domestici conservati prima della guerra. Sfortunatamente, ha influenzato i loro cicli riproduttivi e si sono riprodotti molto rapidamente. Li ho liberati nelle Lande poco dopo averlo capito.}
{291}{}{Sei un mostro! Non c'e' da stupirsi che nessuno nella zona sappia di te! Dovresti essere eliminato.}
{292}{}{Well, I don't agree with what you are doing, but there's nothing I can do about it. Goodbye.}
{300}{}{Droghe speciali? Beh, ho coltivato una nuova coltura di marijuana. E' una droga prebellica che ho trovato in congelamento profondo. Ho solo letame proveniente dalle creature mutate che vedi qui, quindi era piu' pericoloso di quanto pensassi. Le prime prove non sono state molto riuscite, comunque...}
{301}{}{Can I get some of this drug?}
{302}{}{Why weren't they successful? What happened?}
{310}{}{Mr. Chemmie! si trova nella sezione nord-est del piano inferiore dell'EPA. O forse nord-ovest... In realta' e' al piano superiore. Oh, non ricordo piu'. E' un enorme pezzo di macchinario. Non puoi sbagliarti.}
{311}{}{Giusto. Grazie. Hai detto di aver creato alcune droghe speciali. Come quali?}
{320}{}{Facile. Sono uno scienziato. E' quello che faccio. Gli esperimenti sono la mia vita. Anche se diverso, e' comunque solo un altro tipo di esperimento.}
{321}{}{Stai giocando con cose che non dovresti alterare! E se qualcosa andasse storto? E se alcune delle persone su cui lavori morissero!?}
{330}{}{Eliminato! Oh, no. Non credo proprio. Sto facendo il lavoro per cui sono stato assunto: indagare e sperimentare. Col passare del tempo, pero', inizi a esaurire le cose da indagare, quindi devi essere piu' libero nelle tue idee. Credo che una volta lo chiamassero 'pensare fuori dagli schemi'.}
{331}{}{I've had enough of this! If no one else will stop you, then I will.}
{332}{}{You're sick and I'm leaving. Goodbye.}
{340}{}{Si', perche' no? Serviti pure. Ce n'e' in abbondanza nei magazzini al livello della superficie. Credo di aver programmato anche Mr. Chemmie! per produrla. Non ne tengo piu' qui perche' occupa troppo spazio.}
{341}{}{Grazie! Dicevi un attimo fa che le prime prove non erano state un successo? Perche'?}
{350}{}{Beh, alcuni soggetti di prova hanno avuto reazioni gravi al virus, ma non vale nemmeno la pena menzionarle. Qualche errore qua e la' e' previsto nel nostro lavoro. Ora, se vuoi scusarmi, ho delle cose da fare.}
{351}{}{Yeah, I suppose I do as well. Goodbye.}
{360}{}{Allora muoiono. Cosa ti aspetti che faccia? E' cosi' che si fa progresso.}
{361}{}{Mostruoso! Incredibile! Tu muori, adesso!}
{362}{}{I can't stand this anymore. Goodbye. I won't be back soon.}
{370}{}{Jet? Si', e' la droga di cui la maggior parte di Redding e' fatta, se non sbaglio. E' un composto eccezionalmente complesso e le mie macchine non riuscivano a riprodurlo nemmeno alla massima potenza. Perche'? Che cosa ne sai?}
{371}{}{Well, I have here with me it's creator.}
{380}{}{[*Gli brillano gli occhi*] Davvero!? Chi? Posso vederlo? Magari parlargli?}
{381}{}{Certo. Si chiama Myron. E' proprio qui.}
{390}{}{Grazie per avermi portato quel ragazzo, Myron. E' molto competente! Non proprio brillante quanto me, capisci, ma comunque valido. Se un giorno volesse stabilirsi, puo' venire qui come mio apprendista.}
{391}{}{Non sono sicuro che gli piacerebbe essere l'apprendista di qualcuno. E' meglio che andiamo.}
{400}{}{Un momento, prima che tu vada. Per favore, prendi questo come ringraziamento per aver portato Myron qui. Non mi serve davvero.}
{401}{}{Hey, thanks. Um, what is it?}
{410}{}{E' un Solar Scorcher. Era un mio esperimento. Si alimenta con l'energia del sole e quindi non richiede munizioni. Funziona davvero e ti sara' molto utile, ne sono certo, nelle Lande piu' profonde. Questo in realta' richiede un'altra domanda...}
{411}{}{Di cosa si tratta?}
{420}{}{Sembri un tipo avventuroso. Io sono confinato nei terreni dell'EPA per sorvegliare molti esperimenti, ma ho bisogno di alcune attrezzature che ho esaurito. Potresti raccogliere alcune cose per me?}
{421}{}{Yeah, I suppose so. What do you need?}
{422}{}{No, I'm too busy at the moment saving my village. Maybe some other time.}
{430}{}{Beh, uno dei pochi animali che non ho ancora studiato in dettaglio e' il Geco Dorato. Ho bisogno di materiale di ricerca prima di poter andare oltre. Potresti raccogliere, diciamo, 10 pelli di geco dorato e riportarmele qui? Sono sicuro che potrei trovare qualcosa da darti in cambio.}
{431}{}{No problem. I'll be back as soon as I have them.}
{432}{}{I already have 10 pelts with me.}
{440}{}{[Alza lo sguardo verso di te.] Cosa?}
{441}{}{Uh, ciao di nuovo. Non ho capito chi fossi l'ultima volta che abbiamo parlato.}
{450}{}{You again? What do you want now?}
{451}{}{Cosa fai qui? Questo posto sembra una citta' fantasma.}
{460}{}{Se non vuoi aiutarmi, allora per favore lasciami in pace. Oppure hai deciso di offrire le tue capacita'?}
{461}{}{Yes. What do you want me to do?}
{462}{}{No, but as soon as I'm free I'll be back to help you.}
{470}{}{Hello there. Have you calmed down at all yet?}
{471}{}{No, sono qui per ucciderti. Il mondo ha bisogno di meno persone come te.}
{472}{}{Yeah, I suppose so. I need to ask you some questions.}
{480}{}{Cosa vuoi? Ho esperimenti da sorvegliare, lo sai!}
{481}{}{Tell me about the drugs you're making.}
{482}{}{Tell me about those people again.}
{483}{}{I'm looking for work. Do you have any?}
{484}{}{Where do you get all your equipment from?}
{490}{}{Have you collected the pelts as I requested?}
{491}{}{Si', eccola.}
{492}{}{No, not as yet.}
{500}{}{Meraviglioso! Eccellente! Vediamo... ah si', questi andranno benissimo! Allora, vuoi un altro incarico?}
{501}{}{Yes, if you have anything}
{502}{}{Not just yet thanks. Bye.}
{510}{}{Beh, anche se il magazzino e' dove svolgo quasi tutto il mio lavoro, devo comunque entrare nel complesso principale di tanto in tanto. Tuttavia, le luci sono fissate permanentemente su un'impostazione bassa. Sistemalo per me cosi' posso entrare nell'edificio dell'EPA.}
{511}{}{Nessun problema.}
{512}{}{I'll get back to you when I have time to do it.}
{513}{}{L'ho gia' fatto! C'erano alcuni fili allentati sulla scheda principale e io stavo per—}
{520}{}{Ora che hai ucciso tutti i miei guerrieri, hai piu' che dimostrato il tuo valore. Considereresti di lavorare per me?}
{521}{}{What!? Working for you!? What would you want me to do?}
{522}{}{No thanks. Bye.}
{530}{}{Have you sorted out the power problem yet?}
{531}{}{Si', si', si', non ho bisogno dei dettagli. Grazie. Ora, ho ancora un altro compito se desideri affrontarlo.}
{532}{}{Di cosa si tratta?}
{533}{}{No, ci sto ancora lavorano.}
{540}{}{Sto sperimentando un nuovo siero per migliorare l'agilita' e la consapevolezza delle persone, cosi' da aiutarle a sopravvivere in questo mondo duro. Mi permetteresti di provarlo su di te, vero?}
{541}{}{Beh... suppongo di si', che male potrebbe fare?}
{550}{}{Piu' di quanto potresti mai immaginare, se qualcosa andasse storto... Ora stai fermo e mettiamoci al lavoro!}
{551}{}{Whoa! Wait a minute...}
{560}{}{Ahh, eccoti! Di nuovo nel mondo dei vivi, vedo! Come ti senti?}
{561}{}{Uh, fine why?}
{570}{}{Sei solo svenuto per un paio d'ore, ma ora dovresti stare bene. Gli indicatori mostrano che sei molto piu' vigile e reattivo.}
{571}{}{Wow! Thanks, Doctor.}
{580}{}{No problem. If you ever need anything, let me know.}
{581}{}{Lo faro'. Arrivederci.}
{590}{}{Have you decided to help me yet?}
{591}{}{Si', ti aiutero'. Tornero' quando l'energia sara' ripristinata.}
{592}{}{No, mi dispiace.}
{600}{}{Mi dispiace, ma non posso fare altro per te ora. Non ho altri incarichi da assegnare. Grazie per il tuo aiuto.}
{601}{}{Bye then.}
{602}{}{Si', c'erano alcuni fili allentati e ho dovuto trovare un po' di rottami per—}
{603}{}{NO! What are you doing?}
{700}{}{Un momento! Facevi parte del team *originale*?! Ma allora devi avere quasi 200 anni!}
{701}{}{Beh, suppongo sia vero, in un certo senso. In realta' sono nato 202 anni fa. Tuttavia, non avrei mai potuto vivere cosi' a lungo con mezzi normali.}
{702}{}{Go on. I'm listening.}
{703}{}{Quando la guerra e' iniziata, io e gli altri scienziati abbiamo usato le camere criogeniche. Abbiamo ceduto piu' controllo della struttura agli ologrammi e ai robot, poi ci siamo messi nelle camere per superare il peggio della distruzione.}
{704}{}{Ma la Grande Guerra e' finita moltissimi anni fa.}
{705}{}{Vero. Siamo usciti dall'ibernazione circa 90 anni fa e abbiamo scoperto che questo posto era molto deteriorato. La maggior parte degli altri scienziati ha continuato alcune delle loro ricerche originali, perche' non sapevano davvero cos'altro fare.}
{706}{}{[AVANTI]}
{707}{}{Non potevo credere alla loro miopia scientifica... alla totale mancanza di immaginazione! Avevamo un'incredibile opportunita' di fare cose straordinarie. Avevamo la possibilita' di rifare tutto come ritenevamo opportuno. Purtroppo, i miei compagni hanno pagato la loro mancanza di visione...}
{708}{}{You killed them!?}
{709}{}{Understandable.}
{710}{}{Please continue.}
{711}{}{No, non li ho uccisi. Ma non potevo permettere che restassero qui a interferire con i miei piani. Ho semplicemente manipolato gli eventi in modo che scegliessero di andarsene.}
{712}{}{Okay, questo risponde a una parte della storia. Ma manca ancora qualcosa...}
{713}{}{Ah, si'. Scusa. A volte divago o la mia mente vaga. Le grandi menti, sai com'e'. Comunque, continuo a usare la vasca. Anche se l'ho modificata un po'.}
{714}{}{What modifications have you done?}
{715}{}{I think I've heard enough of this. Goodbye.}
{716}{}{Beh, la prima volta che abbiamo usato le camere criogeniche, era come se fossi andato a dormire e mi fossi svegliato. Ma ho capito che era uno spreco di tempo. Ho reimpostato le camere in modo da poterle usare per anni alla volta, mantenendo pero' la mente cosciente! Uso quei lunghi periodi per riflettere sui progetti attuali e ideare nuovi esperimenti. Cosi' posso vedere gli effetti a lungo termine delle mie ricerche.}
{717}{}{Hai mai considerato che usare la camera in questo modo potrebbe danneggiarti in qualche modo?}
{718}{}{Sciocchezze! Semmai sto migliorando. Ora vedo tutto cosi' chiaramente, grazie ai miei periodi di ibernazione lucida.}
{719}{}{What a loon! Goodbye.}
{720}{}{In realta' e' un'ottima idea. Geniale! Ehi, pensi che potrei vedere questa camera criogenica?}
{721}{}{I see. Tell me about something else.}
{722}{}{Well of course. It's right over there. I had it moved up here some time ago. Keeping the chamber in the sublevels of this facility was just not a wise idea.}
{723}{}{Interesting. So, how does it work?}
{724}{}{Well, of course the scientific principles of cryogenics is quite advanced. However, the functions are governed by the computer here, has a fairly easy interface. [He takes a few minutes showing you how the system works.]}
{725}{}{Thanks for the information, Doctor. I guess I would still like to know about a few other things.}
{726}{}{Thanks for the information, Doctor. Who knows? Information like that just might prove useful someday. Goodbye.}
{727}{}{Well, enough chit-chat. I should be going. Goodbye, Doctor.}
{728}{}{No, it just wouldn't do to have them stay here interfering with my plans... not at all... [The Doctor gazes past you seemingly lost in his thoughts.]}
{729}{}{You know, you are one twisted person. I think I am going to have to show you how I 'experiment' on people. Time to die!}
{730}{}{So, are you happy with this situation? I mean, being the only one here?}
{731}{}{What else would you like to know about?}
{800}{}{Actually, wait one second. You look like an adventurous type. I may have a use for someone of your skills.}
{801}{}{Certo. Cosa ti serve?}
{802}{}{No thanks. Bye.}
{803}{}{Well, I was out collecting samples at one of my work sites and I seem to have left one of my tools there. Normally
 I would just go and get it myself, but I'm extremely busy at the moment and for the life of me I cannot remember the exact
 spot I left it at. In any case, head northwest from this building and you will find the area where I left my tool. Should
 be a piece cake.}
{804}{}{I'll get right on it.}
{805}{}{Not interested. Bye.}
{806}{}{Well, wait. Are you sure you won't help me with a little something?}
{810}{}{Excellent! Now, I must get back to work. [To himself.] It's all going according to plan.}
{811}{}{[FATTO]}
{820}{}{That's too bad. Well, I must be getting back to work. [To himself.] Almost had him. Now, where am I going to find another test subject...}
{821}{}{[FATTO]}
{830}{}{[The man looks up startled.] What the-?!}
{831}{}{I'm still looking for your part.}
{832}{}{Here's your tool. Piece of cake indeed.}
{833}{}{Were you trying to kill me out there? That was a maze full of mutated monsters. This wasn't an ordinary part
 retrieval job, now was it?}
{840}{}{What?! Give me that! [He snatched the tool from your hand.] How did you- Oh, nevermind. Back to the drawing board then...}
{841}{}{[You ignore the man's reaction.] Alright, well if you need anything else, let me know. Bye.}
{850}{}{That's none of your business. [He snatches the tool from your hand.] Now, get out of here. I've got things to do. [He looks
 away muttering to himself.]}
{851}{}{Vabbe'. Ci vediamo.}
{852}{}{I don't think so. You tried to kill me and now I will return the favor. Prepare to die!}
{860}{}{Uh, yes, of course. Well, get to it then.}
{861}{}{[FATTO]}
{900}{}{*Grumbles*}
{901}{}{*To himself* I was sure he wouldn't return.}
{1000}{}{You return the Doctor's forgotten tool.}
