{100}{}{That's it... I think.}
{101}{}{No, ma non puo'... io, beh... hmmm...}
{102}{}{Il filo blu all'alloggiamento rosso...}
{103}{}{Those mutations are progressing nicely.}
{104}{}{It won't be long now.}
{105}{}{Just a few more drops of HCl...}
{106}{}{You see a man in a white lab coat.}
{107}{}{You see The Doctor.}
{108}{}{Il principale — e unico — dottore rimasto nell'EPA.}
{109}{}{It would be unwise to attack me.}
{120}{}{Si'?}
{121}{}{Hi, my name is }
{122}{}{. Who are you?}
{123}{}{Sorry to bother you. Goodbye.}
{130}{}{I'm known as the Doctor.}
{131}{}{Ah, giusto. Quindi cosa fai? Perche' sei qui tutto solo? Il resto del posto sembra deserto.}
{132}{}{OK, thanks.}
{140}{}{Vedo che hai abilita' adeguate nelle vie della scienza. Forse potresti capire cosa faccio qui, dopotutto. Cosa desideri sapere?}
{141}{}{Why are you here?}
{142}{}{Di che cosa ti occupi?}
{150}{}{Mi dispiace, ma non credo tu abbia le competenze necessarie per capire cosa sto facendo qui. Torna quando sarai mentalmente piu' forte.}
{151}{}{Ehi, un momento. Provero' qualsiasi cosa tu mi dia!}
{152}{}{Well, all right then. Goodbye.}
{160}{}{Facevo parte del team originale di scienziati che lavorava qui nell'EPA prima della guerra. Sfortunatamente, nessuno di loro era abbastanza competente nelle discipline scientifiche o possedeva sufficiente determinazione, e hanno dovuto andarsene. Ora, sono l'unico rimasto.}
{161}{}{Quindi, sei felice di questo? Voglio dire, di essere l'unico qui?}
{170}{}{Qualsiasi cosa io voglia, davvero. Al momento sto conducendo ulteriori ricerche genetiche su creature che ho creato per osservare gli effetti dell'FEV sui loro sistemi immunitari. Anni fa ho creato molti nuovi farmaci e ne ho adattati diversi altri, ma non lo faccio piu'.}
{171}{}{What's that about creatures you've created?}
{172}{}{What types of drugs have you made?}
{180}{}{No, non puoi. Non sei abbastanza competente nelle vie della scienza e dei potenziamenti biologici. Ora, se vuoi scusarmi, mi stai facendo perdere tempo.}
{181}{}{Assolutamente no. Mettimi alla prova.}
{190}{}{<sorride> Beh, forse e' cosi'. Va bene, se vuoi, ti daro' una possibilita'. Cosa vorresti sapere allora?}
{191}{}{Why are you here?}
{192}{}{Di che cosa ti occupi?}
{200}{}{Ma certo! Nessuno che mi controlla. Nessuna regola di alcun tipo. Faccio quello che voglio, quando voglio. Inoltre, essendo rimasto solo io qui, ho accesso a tutta l'attrezzatura di cui potrei mai avere bisogno. Altro?}
{201}{}{Who are the people over there in those cages?}
{202}{}{Che cos'e' tutto quel liquido dai colori strani che ho visto in giro per l'EPA?}
{203}{}{Where do you get all of the equipment from?}
{210}{}{Quelli nelle prime celle vicino a quel muro sono alcuni abitanti del villaggio entrati qui per sbaglio, e li ho catturati per usarli piu' avanti. Gli altri, quelli che sembrano piu' forti, sono i miei guerrieri per... emergenze.}
{211}{}{...for use later? What do you mean?}
{212}{}{Thanks. Can I ask another question?}
{213}{}{Right. Thanks. I must be going now.}
{220}{}{Sostanze chimiche e serbatoi di FEV, principalmente. Era tutto contenuto in grandi barili per essere conservato in sicurezza qui all'EPA. Sfortunatamente, c'e' stato un piccolo incidente e una grande perdita chimica ha costretto tutti ad andarsene, tranne quei tonti degli ologrammi. Alcune sostanze sono filtrate nei livelli inferiori. Ora le sto usando come materiale di sperimentazione. Finora hanno dato risultati promettenti!}
{221}{}{Che tipo di risultati? Vuoi dire che hai creato tu queste creature?}
{222}{}{So where do you get all your equipment from?}
{230}{}{Per lo piu' qui. L'EPA era stata progettata e fornita con ogni tipo di macchinario e, da quando gli altri scienziati se ne sono andati, non e' stato usato piu' nulla. Ora, dopo tanti anni, sto solo esaurendo alcune cose...}
{231}{}{Never mind. I must be going now.}
{240}{}{Droghe? Decine! Negli anni ho creato mentats, buffout, stimpak, kit medici di varie potenze, psycho e molte altre cose che non capiresti. Non lo faccio piu', comunque. Ho creato il robot Mr. Chemmie! per farlo al posto mio. Si trova nel complesso principale. Se hai davvero l'intelligenza e le capacita' scientifiche che dici, sentiti libero di usarlo per creare tutte le droghe che vuoi.}
{241}{}{What special drugs have you created?}
{242}{}{Where can I find Mr. Chemmie!?}
{243}{}{Thanks. Say, have you ever heard of Jet?}
{250}{}{Si', ho creato molte creature mentre ero all'EPA. Se sei un tipo che esplora, potresti averne incontrate alcune nelle Lande. Centauri? Flotter? Gli \"Alieni\"? Ora vagano liberamente nelle Lande. Ne ho tenute solo alcune qui e nella base principale per riferimento futuro.}
{251}{}{Un momento. Mi stai dicendo che tutte quelle creature la fuori, quelle cose che infestano le Lande e uccidono innocenti, le hai create tu?!}
{252}{}{Whoa, note to self: Do not anger the Doctor. Goodbye.}
{260}{}{'Cosa intendo?' Il Virus dell'Evoluzione Forzata, naturalmente! Sto solo iniziando a sperimentarne gli effetti sugli esseri umani. Abbiamo tutti sentito la storia del Master. Stavo pensando di fare qualcosa di simile anch'io. Un mio esercito sarebbe certamente molto utile!}
{261}{}{Non pensi che sia un po' immorale? Come puoi anche solo considerare una cosa cosi' orribile?}
{262}{}{Solo ora stai passando agli esseri umani? Su cos'altro hai lavorato allora?}
{263}{}{Well, good luck with that. I must get going now.}
{270}{}{Si', suppongo di si'. Mi diverti molto. Cos'altro posso risponderti? }
{271}{}{Tell me again about these people.}
{272}{}{What's all the funny-colored liquid around the EPA?}
{273}{}{Where do you get all the equipment and supplies for your experiments?}
{280}{}{No, no, no. Prima che tu vada, devo chiederti una cosa. Potresti farmi un piccolo favore? Non lascio la sicurezza del magazzino per paura che mi rubino qualcosa. Ho bisogno di alcune materie prime. Potresti aiutarmi?}
{281}{}{Yeah, I suppose so. What do you need?}
{282}{}{No, I'm too busy at the moment. Maybe some other time.}
{290}{}{Si', mi chiedevo cosa avrebbe fatto il virus sugli animali domestici conservati prima della guerra. Sfortunatamente, ha influenzato i loro cicli riproduttivi e si sono riprodotti molto rapidamente. Li ho liberati nelle Lande poco dopo averlo capito.}
{291}{}{Sei un mostro! Non c'e' da stupirsi che nessuno nella zona sappia di te! Dovresti essere eliminato.}
{292}{}{Well, I don't agree with what you are doing, but there's nothing I can do about it. Goodbye.}
{300}{}{Droghe speciali? Beh, ho coltivato una nuova coltura di marijuana. E' una droga prebellica che ho trovato in congelamento profondo. Ho solo letame proveniente dalle creature mutate che vedi qui, quindi era piu' pericoloso di quanto pensassi. Le prime prove non sono state molto riuscite, comunque...}
{301}{}{Can I get some of this drug?}
{302}{}{Why weren't they successful? What happened?}
{310}{}{Mr. Chemmie! is located in the northeast section of the bottom floor of the EPA. Or maybe the northwest... Actually, it's on the top floor. Oh, I can't remember anymore. It's a huge chunk of machinery. You can't miss it.}
{311}{}{Right. Thanks. You mentioned you'd created some special drugs. Like what?}
{320}{}{Easily. I'm a scientist. That's what I do. Experiments are my life. Though different, it really is just another type of experiment.}
{321}{}{You're messing with things that you shouldn't be altering! What if things go wrong? What if some of the people you're working on die!?}
{330}{}{Disposed of! Oh, no. I don't think so. I'm doing the job I was originally hired to do. Investigate and experiment. As time goes on though, you start to run out of things to investigate, so you have to be more liberal in your ideas. I think it was once called 'thinking outside the box'.}
{331}{}{I've had enough of this! If no one else will stop you, then I will.}
{332}{}{You're sick and I'm leaving. Goodbye.}
{340}{}{Yeah, why not? Help yourself. There's plenty in the storage sheds on the surface level. I think I may have programmed Mr. Chemmie! to make it as well. I don't keep any around here anymore as it takes up a lot of space.}
{341}{}{Thanks! You were saying a moment ago that you weren't successful in early trials? Why is that?}
{350}{}{Well, some of the test subjects had severe reactions to the virus, but those are not even worth mentioning. A few errors here and there are expected in our line of work. Now, if you'll excuse me, I have things to do.}
{351}{}{Yeah, I suppose I do as well. Goodbye.}
{360}{}{Then they die. What do you expect me to do? This is how one makes progress.}
{361}{}{Monstrous! Unbelievable! You die - now!}
{362}{}{I can't stand this anymore. Goodbye. I won't be back soon.}
{370}{}{Jet? Yeah, that's the drug that most of Redding's been high on, if I'm not mistaken. It's an exceptionally complex compound and my machines couldn't reproduce it even on maximum power. Why? What do you know of it?}
{371}{}{Well, I have here with me it's creator.}
{380}{}{[*Eyes sparkle*] Really!? Who? Can I see him? Maybe speak to him?}
{381}{}{Of course. His name is Myron. He's right here.}
{390}{}{Thank you for bringing that Myron kid to me. He's very knowledgeable! Not quite as intellectually adept as me, understand, but well nonetheless. If he ever wants to settle down he can come here as my apprentice.}
{391}{}{I'm not sure he'd like being anybody's apprentice. We'd better be going.}
{400}{}{One moment, before you go. Please, take this as a token for bringing Myron here. I have no real use for it.}
{401}{}{Hey, thanks. Um, what is it?}
{410}{}{It's a Solar Scorcher. It was an experiment of mine. It feeds off the energy from the sun and thus no ammunition is required. It actually works and will be of great use to you, I'm sure, in the deep wastes. This requires a further question actually...}
{411}{}{Di cosa si tratta?}
{420}{}{You seem an adventurous type. I'm restricted to the grounds of the EPA to watch over many of the experiments, but I need some equipment that I've run out of. Could you collect a few things for me?}
{421}{}{Yeah, I suppose so. What do you need?}
{422}{}{No, I'm too busy at the moment saving my village. Maybe some other time.}
{430}{}{Well, one of the only animals I haven't looked into in detail is the Golden Gecko. I need some research material before I can go any further. Could you collect, say, 10 golden gecko pelts and bring them back here to me? I'm sure I could find something here to give you.}
{431}{}{No problem. I'll be back as soon as I have them.}
{432}{}{I already have 10 pelts with me.}
{440}{}{[Looks up at you.] What?}
{441}{}{Uh, hello again. I didn't catch who you are the last time we spoke.}
{450}{}{You again? What do you want now?}
{451}{}{What do you do here? This place is like a ghost town.}
{460}{}{If you do not wish to help me, then please leave me alone. Or, have you decided to lend your abilities?}
{461}{}{Yes. What do you want me to do?}
{462}{}{No, but as soon as I'm free I'll be back to help you.}
{470}{}{Hello there. Have you calmed down at all yet?}
{471}{}{No, I'm here to kill you. The world needs less people like you.}
{472}{}{Yeah, I suppose so. I need to ask you some questions.}
{480}{}{What do you want? I have experiments to watch over, you know!}
{481}{}{Tell me about the drugs you're making.}
{482}{}{Tell me about those people again.}
{483}{}{I'm looking for work. Do you have any?}
{484}{}{Where do you get all your equipment from?}
{490}{}{Have you collected the pelts as I requested?}
{491}{}{Si', eccola.}
{492}{}{No, not as yet.}
{500}{}{Wonderful! Excellent! Let me see... ahh yes, these will do nicely! Now then, do you want another job?}
{501}{}{Yes, if you have anything}
{502}{}{Not just yet thanks. Bye.}
{510}{}{Well, although the warehouse is where I do almost all of my work, I still need to enter the main complex from time to time. However, the lights have been permanently fixed on low setting. Sort this out for me so I can enter the EPA building itself.}
{511}{}{Nessun problema.}
{512}{}{I'll get back to you when I have time to do it.}
{513}{}{I've already done this! There were some loose wires on the main circuit board and I mana-}
{520}{}{Now that you've killed all of my warriors, you have more than proven yourself worthy. Would you consider working for me?}
{521}{}{What!? Working for you!? What would you want me to do?}
{522}{}{No thanks. Bye.}
{530}{}{Have you sorted out the power problem yet?}
{531}{}{Yes, yes, yes, I don't need to know the specifics. Thanks. Now, I still have one more task if you wish to undertake it.}
{532}{}{Di cosa si tratta?}
{533}{}{No, ci sto ancora lavorano.}
{540}{}{I am experimenting with a new serum at the moment to improve the agility and awareness of people to help them survive in this harsh world. You'd allow me to try it on you, wouldn't you?}
{541}{}{Well... I suppose so, what harm could it do?}
{550}{}{More than you'd ever believe if it goes wrong... Now hold still and let's get down to it!}
{551}{}{Whoa! Wait a minute...}
{560}{}{Ahh, there you are! Back in the land of the living, I see! How do you feel?}
{561}{}{Uh, fine why?}
{570}{}{You just blacked out for a couple of hours, but you should be fine now. Indications show you are much more alert and responsive.}
{571}{}{Wow! Thanks, Doctor.}
{580}{}{No problem. If you ever need anything, let me know.}
{581}{}{Lo faro'. Arrivederci.}
{590}{}{Have you decided to help me yet?}
{591}{}{Yes, I will help you. I'll return when the power is restored.}
{592}{}{No, mi dispiace.}
{600}{}{I'm sorry, but there's nothing more I can do for you now. I have no more jobs left to be done. Thanks for your help.}
{601}{}{Bye then.}
{602}{}{Yes, there were some loose wires and I had to find some junk to-}
{603}{}{NO! What are you doing?}
{700}{}{Wait a second! You were part of the *original* team?! But, that's got to make you almost 200 years old!}
{701}{}{Well, I suppose that's true, in a way. I was actually born 202 years ago. However, there is no way that I could have lived that long through regular means.}
{702}{}{Go on. I'm listening.}
{703}{}{When the war started, the other scientists and I used the cryogenic storage chambers. We handed over more control of the facility to the holograms and robots, then put ourselves in the chambers to wait out the worst of the destruction.}
{704}{}{But, the great war was over many, many years ago.}
{705}{}{True. We initially came out of hibernation about 90 years ago, and discovered that this place had deteriorated greatly. Most of the other scientists here continued some of their original research, as they didn't really know what else to do.}
{706}{}{[AVANTI]}
{707}{}{I couldn't believe their scientific short-sightedness... their utter lack of imagination! We had an incredible opportunity to do some amazing things. We had the chance to remake things how we saw fit. Sadly, my comrades paid for their lack of vision...}
{708}{}{You killed them!?}
{709}{}{Understandable.}
{710}{}{Please continue.}
{711}{}{No, I didn't kill them. But I couldn't have them stay here interfering with my plans. I merely manipulated events here so that they chose to leave.}
{712}{}{Okay, that answers part of the story. But there is still something missing...}
{713}{}{Ah, yes. Sorry about that. I sometimes go off on tangents or my mind just wanders. Great minds, you know? Anyway, I continue to use the tank. I have modified it somewhat, though.}
{714}{}{What modifications have you done?}
{715}{}{I think I've heard enough of this. Goodbye.}
{716}{}{Well, the first time we used the cryogenic chambers, it was as if I just went to sleep and woke up. But, I realized that was a waste of time. I reset the chamber settings so that I could use it for years at a time, but keep my mind conscious! I use those extended periods to ponder current projects and think up new experiments. By doing so, I can see the long-term effects of my research.}
{717}{}{Did you ever consider that maybe using the chamber like this might be damaging to you somehow?}
{718}{}{Nonsense! If anything I am getting better. I can see things so clearly, now, thanks to my periods of lucid hibernation.}
{719}{}{What a loon! Goodbye.}
{720}{}{That's actually a great idea. Genius! Hey, do you think that I could see this cryogenic chamber?}
{721}{}{I see. Tell me about something else.}
{722}{}{Well of course. It's right over there. I had it moved up here some time ago. Keeping the chamber in the sublevels of this facility was just not a wise idea.}
{723}{}{Interesting. So, how does it work?}
{724}{}{Well, of course the scientific principles of cryogenics is quite advanced. However, the functions are governed by the computer here, has a fairly easy interface. [He takes a few minutes showing you how the system works.]}
{725}{}{Thanks for the information, Doctor. I guess I would still like to know about a few other things.}
{726}{}{Thanks for the information, Doctor. Who knows? Information like that just might prove useful someday. Goodbye.}
{727}{}{Well, enough chit-chat. I should be going. Goodbye, Doctor.}
{728}{}{No, it just wouldn't do to have them stay here interfering with my plans... not at all... [The Doctor gazes past you seemingly lost in his thoughts.]}
{729}{}{You know, you are one twisted person. I think I am going to have to show you how I 'experiment' on people. Time to die!}
{730}{}{So, are you happy with this situation? I mean, being the only one here?}
{731}{}{What else would you like to know about?}
{800}{}{Actually, wait one second. You look like an adventurous type. I may have a use for someone of your skills.}
{801}{}{Certo. Cosa ti serve?}
{802}{}{No thanks. Bye.}
{803}{}{Well, I was out collecting samples at one of my work sites and I seem to have left one of my tools there. Normally
 I would just go and get it myself, but I'm extremely busy at the moment and for the life of me I cannot remember the exact
 spot I left it at. In any case, head northwest from this building and you will find the area where I left my tool. Should
 be a piece cake.}
{804}{}{I'll get right on it.}
{805}{}{Not interested. Bye.}
{806}{}{Well, wait. Are you sure you won't help me with a little something?}
{810}{}{Excellent! Now, I must get back to work. [To himself.] It's all going according to plan.}
{811}{}{[FATTO]}
{820}{}{That's too bad. Well, I must be getting back to work. [To himself.] Almost had him. Now, where am I going to find another test subject...}
{821}{}{[FATTO]}
{830}{}{[The man looks up startled.] What the-?!}
{831}{}{I'm still looking for your part.}
{832}{}{Here's your tool. Piece of cake indeed.}
{833}{}{Were you trying to kill me out there? That was a maze full of mutated monsters. This wasn't an ordinary part
 retrieval job, now was it?}
{840}{}{What?! Give me that! [He snatched the tool from your hand.] How did you- Oh, nevermind. Back to the drawing board then...}
{841}{}{[You ignore the man's reaction.] Alright, well if you need anything else, let me know. Bye.}
{850}{}{That's none of your business. [He snatches the tool from your hand.] Now, get out of here. I've got things to do. [He looks
 away muttering to himself.]}
{851}{}{Vabbe'. Ci vediamo.}
{852}{}{I don't think so. You tried to kill me and now I will return the favor. Prepare to die!}
{860}{}{Uh, yes, of course. Well, get to it then.}
{861}{}{[FATTO]}
{900}{}{*Grumbles*}
{901}{}{*To himself* I was sure he wouldn't return.}
{1000}{}{You return the Doctor's forgotten tool.}
