{100}{}{You see a Mr. Handy Robot.}
{101}{}{You see a seriously depressed Mr. Handy Robot.}
{102}{}{Questo robot Mr. Handy sembra essere molto depresso per qualche motivo.}
{200}{}{O woe is me!}
{201}{}{Fed up...}
{202}{}{I wanna die now...}
{203}{}{Somebody please kill me...}
{204}{}{Everyone's gone...}
{205}{}{Why should I do it?}
{206}{}{Boring...}
{207}{}{...SINGH...}
{208}{}{Life. Don't talk to me about life.}
{209}{}{Penso che dovresti sapere che mi sento molto depresso.}
{210}{}{Perdonami per respirare, cosa che non faccio comunque quindi non so nemmeno perche' lo dica, oh Dio, sono cosi' depresso.}
{500}{}{Si', spingimi giu' da una scogliera.}
{501}{}{***bzzt Smettila! *** bzzt}
