{100}{}{You see Dex.}
{101}{}{Vedi un uomo affascinante, impeccabilmente curato. Sotto una massa impressionante di capelli lucidi di brillantina, i suoi occhi
 brillano di intensita'... o forse di follia.}
{200}{}{[Mentre ti avvicini alla camera criogenica, vedi un uomo nudo e attraente disteso sul pavimento. Porta
 le ginocchia al petto e le abbraccia. Rimane li' per alcuni istanti, fissando il vuoto mentre il suo corpo trema
 e i denti battono. Gradualmente, sembra calmarsi.]}
{201}{}{Uh, hello?}
{210}{}{[Scatta con la testa verso di te e balza in piedi. Ti osserva intensamente, poi guarda attorno come un
 animale in trappola. Quando i suoi occhi tornano su di te, si addolciscono, e si rilassa mentre i ricordi gli tornano
 alla mente. Cambia rapidamente atteggiamento, mostrando una calma sicura nonostante sia nudo.] Non ti riconosco, amico.
 Non ti dispiace se mi vesto, vero?}
{211}{}{I guess there's no harm-}
{212}{}{Well, I-}
{220}{}{Certo che non ti dispiace. Grazie, amico. [Ti passa accanto e apre un armadietto vicino. Si veste con calma
 con un abito elegante, poi infila in tasca il contenuto dell'armadietto. Con un pettinino, inizia a sistemare e modellare
 i suoi capelli scuri e lucidi con la precisione rapida di un professionista.] Allora, dov'e' il dottore? }
{221}{}{Il dottore? Oh, probabilmente e' qui da qualche parte. Anzi, credo stia arrivando proprio ora, quindi me ne vado
 e vi lascio parlare. Ciao!}
{222}{}{Potrebbe sorprenderti, ma sei stato congelato per moltissimo tempo. Chiunque fosse "il dottore", ormai e' morto
 da un pezzo. Se era un tuo amico, mi dispiace.}
{223}{}{Non voglio sconvolgerti, ma sei stato nel ghiaccio per *davvero* tanto tempo. Sono abbastanza sicuro che il tuo amico,
 "il dottore", sia morto da molto ormai.}
{224}{}{Ascolta, belloccio. Non ho scongelato il tuo culo psicotico per rispondere alle tue domande e guardarti mentre ti sistemi.
 Ti lascio vivere solo finche' mi dici qualcosa di utile. Quindi inizia a parlare. Piu' mi dici, piu' a lungo vivi.}
{230}{}{[La sua calma svanisce e gli occhi si infiammano di rabbia.] Pensi di poter intimidire ME? Hai la piu' vaga
 FOTTUTA idea di chi stai parlando? Vieni qui e ti faccio vedere di cosa sono capace!}
{231}{}{[Done.]}
{240}{}{[Dex ti sorride, mostrando una dentatura perfetta—frutto della odontoiatria prebellica, che ti appare strana
 nella sua simmetria bianco perlacea.] Il dottore, amico mio? [Alza un sopracciglio.] Non sai chi sono, vero?}
{241}{}{Uh, non proprio. Ho vagato un po' per questa strana struttura, armeggiando qua e la', e per caso ti ho scongelato.
 Perche' eri congelato li' dentro, comunque?}
{242}{}{Beh, secondo quel computer, tu sei Dex, un assassino narcisista e sociopatico di prima del grande silenzio.
 Ti ho scongelato solo per poterti abbattere come il cane malato che sei.}
{243}{}{Uh, non proprio. Sono sicuro che tu sia un tipo perfettamente normale congelato per motivi perfettamente normali e non malvagi. Diavolo, che ne so io? Ho vagato per questa strana struttura, armeggiando qua e la', e per caso ti ho scongelato.}
{250}{}{[Dex si guarda di nuovo attorno e fischia.] Questo posto e' davvero andato a puttane. Quanto hai detto che e' passato?}
{251}{}{Sono passati piu' di centocinquant'anni da quando il Grande Silenzio ha posto fine agli Antichi... *la tua* gente.}
{260}{}{Grande Silenzio? Gli Antichi? Perche' non risparmi queste stronzate criptiche e mi dici semplicemente cosa e' successo?}
{261}{}{Il Grande Silenzio e' come la mia gente chiama la fine del tuo mondo. Quando i grandi fuochi caddero dal cielo e bruciarono la terra. Scoprirai che il mondo non e' piu' nulla come quello che conoscevi.}
{270}{}{Ma va'? Quindi hanno davvero sganciato le bombe, eh? Immagino che il progetto dei vault non fosse solo un enorme spreco
 dei soldi dei contribuenti, dopotutto.}
{271}{}{Wait. You know of the holy vaults?}
{280}{}{Conoscerli? Diavolo, vivevo proprio accanto al vault di Chicago. Ho persino visto quando hanno finito di costruirlo.
 Poi ovviamente hanno iniziato con quelle maledette esercitazioni... [Si ferma e ti guarda divertito.] Te la stai bevendo tutta,
 vero?}
{281}{}{DIMMI DI PIU' DEI VAULT!}
{282}{}{Vedi, sono stato scelto dalla mia gente per cercare un Vault. Li', spero di recuperare un G.E.C.K. e usare il suo potere
 per salvare il mio villaggio dalla distruzione. Qualsiasi cosa tu possa dirmi sui Vault potrebbe aiutarmi nella mia missione.}
{283}{}{Vedi, ero stato scelto dalla mia gente per cercare un Vault. Dopo aver rischiato la vita in innumerevoli avventure,
 alla fine ho scoperto il Sacro 13. Tuttavia, sono curioso di sapere cos'altro potresti conoscere su questi posti.}
{290}{}{Ti diro' una cosa, amico. Tu hai bisogno di aiuto per trovare questi Vault, e io ho bisogno di qualcuno che mi faccia
 da guida, per cosi' dire, in questo tuo mondo impazzito. Allora che ne dici... partner?}
{291}{}{Hmm, la tua conoscenza degli Antichi potrebbe essermi utile... Ma, beh, sinceramente, ho letto di te
 in quel computer laggiu', e non sono sicuro che tu sia il tipo di persona con cui vorrei viaggiare.}
{292}{}{Non ho davvero il tempo di "farti da guida". Sono sicuro che te la caverai benissimo da solo, "amico".}
{293}{}{I say you've got a deal... partner.}
{294}{}{Non credo di avere molta voglia di andare in giro per la zona contaminata con un assassino psicotico. Quindi te la
 caverai da solo, "amico". Non preoccuparti, sono sicuro che andra' tutto bene. [Sogghigna.]}
{300}{}{Ehi, fermati un attimo. Fammi indovinare, hai letto che ero una specie di assassino folle, giusto? Beh amico, ho due
 parole per te: Stron. Zate. Non credere a una sola parola.}
{301}{}{Ma non ha senso, perche' dovrebbero mentire su di te?}
{302}{}{L'unica stronzata qui in giro e' quella che esce dalla tua bocca, e credo sia ora di farti tacere per sempre.}
{310}{}{Ehi, so che non sembra avere molto senso, ma hai guardato questo posto? Qui non c'e' molto che abbia senso.
 Chissa' cosa passa nelle menti bacate di questi scienziati.}
{311}{}{Hmm... su questo hai ragione. Non dico che ti creda... ma suppongo di poterti almeno ascoltare.}
{312}{}{Yeah, no kidding. Go on...}
{320}{}{Ok, vedi, fa tutto parte dei loro "esperimenti". Quei fottuti dottori stavano facendo dei test sulla
 "natura del male umano" o qualche altra stronzata. Mi iniettavano i ricordi di un maniaco per vedere come
 avrebbero influenzato la personalita' di una persona normale. Almeno, questo e' quello che sono riuscito a capire.}
{321}{}{Beh... se e' vero, e' terribile. Ma perche' hanno scelto proprio te come cavia, all'inizio?}
{322}{}{Cavolo, amico, e' davvero una merda. Comunque, ormai e' tutto passato. Quegli stronzi di scienziati sono morti da un pezzo
 e non potranno piu' tormentarti. Vieni con me e ce ne andiamo da questo posto.}
{330}{}{Heh, vedi, e' questo il bello. *Sono stato io* ad andare *da loro*. Risposi a un annuncio in cui dicevano che avrebbero pagato
 un sacco di soldi per cavie sane. Avevo bisogno di soldi e... beh, si e' rivelato il peggior errore della mia vita.
 Non posso nemmeno iniziare a raccontarti gli orrori che mi hanno fatto. [Gli occhi gli brillano di lacrime mentre ricorda.
 Sospira profondamente e se le asciuga.] Comunque, grazie a te, amico, sono finalmente libero da quell'incubo.}
{331}{}{Huh. Well, I'm glad I could help... I think.}
{332}{}{In realta', stronzo, il tuo incubo e' appena iniziato, perche' non credo a una sola parola di quello che hai detto.}
{340}{}{Allora che ne dici, amico? Facciamo squadra? Non solo sembrerai piu' figo stando con me, ma so cavarmela in uno scontro.
 Diavolo, potrei anche andare da solo, ma non ho idea di che razza di follie ci siano la' fuori adesso.
 Per quel che ne so, il primo albero su cui piscio potrebbe aprire la bocca e staccarmi il cazzo a morsi.}
{341}{}{D'accordo, puoi viaggiare con me, ma ti terro' d'occhio. Al primo segno che stai per fare una cazzata, ti stendo.}
{342}{}{Certo, suppongo che possiamo fare squadra. Benvenuto nel gruppo, Dex.}
{343}{}{Era una dannata bella storia, e non sei nemmeno un cattivo attore, il che ti rende ancora piu' pericoloso. Credo che faro'
 un favore alle Terre Desolate e ti elimino prima che tu possa fare altro danno.}
{350}{}{[Il sorriso di Dex vacilla e i suoi occhi si fanno assenti. Dopo un momento, inizia a parlare senza incrociare il tuo sguardo.]
 Ero uno dei loro malati esperimenti. Mi hanno fatto... cose terribili. [Scuote la testa, poi ti guarda con un sorriso rinnovato.]
 Preferirei non parlarne, sai? Comunque mi chiamo Dex.}
{351}{}{Mi dispiace sentirlo, Dex. Comunque ormai e' tutto nel passato. Nel passato, *vero* passato lontano.}
{352}{}{Senti, Dex, potrei anche aiutarti, ma vorrei sapere con chi ho a che fare. Che cosa ti hanno fatto esattamente?}
{360}{}{[Dex da' un altra occhiata alla stanza e fischia.] Non scherzi. Questo posto e' proprio andato a puttane. Quanto hai detto che e' passato?}
{370}{}{Va bene, devi proprio saperlo? D accordo. In pratica, quei fottuti medici pazzi stavano facendo una specie di test sulla "natura del male umano" o qualche stronzata del genere.
 Mi hanno iniettato i ricordi di un maniaco per vedere come avrebbe influenzato la personalita' di un bravo cittadino rispettoso della legge come me. Almeno, e' la spiegazione migliore che sono riuscito a darmi.}
{371}{}{Capisco. Quindi, come *ti* ha influenzato? }
{372}{}{Non lo so, mi ha dato qualche incubo, va bene? Senti, sono stato congelato per chissa' quanto tempo, e non sono dell'umore per un fottuto interrogatorio.
 Sei quasi peggio del Doc... Hai detto che e' morto? Quanto tempo sono rimasto fuori comunque? Questo posto sembra una merda.}
{400}{}{[Mentre ti avvicini alla camera criogenica, vedi un uomo nudo e attraente disteso sul pavimento. Porta le
 ginocchia al petto e le stringe con le braccia. Rimane li' per diversi istanti, fissando il vuoto mentre il suo corpo trema
 e i denti battono. Gradualmente, sembra calmarsi.]}
{401}{}{Uh, hello?}
{410}{}{[Scatta con la testa verso di te e balza in piedi. Ti osserva con attenzione, poi si guarda intorno come un
 animale in trappola. Quando i suoi occhi tornano su di te, si addolciscono, e si rilassa mentre i ricordi tornano a fiume.
 Cambia rapidamente atteggiamento, ostentando una fredda sicurezza, nonostante la nudita'.] Ehi bambola, so di essere uno spettacolo
 niente male, ma qui dentro fa un po freddo. Ti dispiace se mi vesto?}
{411}{}{I guess there's no harm-}
{412}{}{Well, I-}
{420}{}{Certo che non ti dispiace. Grazie, tesoro. [Ti passa accanto, dandoti una leggera pacca sul sedere, e apre un armadietto vicino.
 Si veste con noncuranza con un completo tagliato su misura, poi infila in tasca il contenuto dell armadietto. Con un pettinino da tasca,
 inizia a sistemare e modellare i suoi capelli scuri impomatati con la rapidita' precisa di un vero professionista.] Non credo di averti
 mai vista da queste parti, bambola, e dubito che dimenticherei una faccia come la tua. Mi chiamo Dex, ma sono sicuro che lo sai gia'. Posso sapere il tuo?}
{421}{}{Sono }
{422}{}{. Ma sappi che ho una regola ferrea: non esco con uomini strani che scongelo io. Visto che sei rimasto sul ghiaccio per l'ultimo secolo e mezzo, faro' finta che la tua mano abbia avuto uno spasmo e mi abbia dato uno schiaffo al culo per sbaglio. Ma se succede di nuovo, ti strappo il cazzo. Chiaro?}
{423}{}{Il mio nome e' }
{424}{}{. Piacere di conoscerti, Dex. Non riesco a immaginare cosa significhi svegliarsi dopo essere stato congelato per oltre centocinquant anni.}
{425}{}{Si', eccome se mi dispiace, fottuto schifoso. Ti ho scongelato solo per abbatterti come il cane malato che sei.}
{426}{}{Lascia perdere i nomi. Che ne dici di toglierti di nuovo quei vestiti e mostrarmi di che pasta sono fatti gli uomini del pre guerra.}
{430}{}{[Sorride e inizia a spogliarsi.] Sei il mio tipo, ragazza. Preparati a fare esperienza di Dex, il Duca del Sesso.}
{431}{}{[Continue.]}
{440}{}{[Dopo un intensa sessione d'amore sul pavimento della camera, crollate entrambi per la stanchezza. Dex
 tiene un piccolo oggetto vicino alla tua bocca.] Urla per lei, piccola. [Proprio quando capisci che e' un orecchio umano mozzato, senti una lama trapassarti il petto. Urli mentre la lama viene estratta e affondata di nuovo...]}
{441}{}{[End.]}
{450}{}{Ehi, ehi, ehi. Un momento, tesoro. Hai appena detto centocinquant'anni? [Scuote la testa incredulo.] E' fottutamente incredibile. [Controlla il suo riflesso.] Pero' devi ammetterlo, per la mia eta' sono dannatamente in forma. [Ti sorride, mostrando una dentatura perfetta - frutto dell'odontoiatria pre guerra che ti sembra strana in tutta la sua simmetria bianco perla.]}
{451}{}{Certo, magari qualche ragazza potrebbe trovarti attraente, ma faccio fatica a ignorare il fatto che sei uno psicopatico assassino a sangue freddo.}
{452}{}{Si', sei molto attraente, ma sinceramente sono un po' nervosa a parlarti dopo quello che ho letto su di te, che sei uno psicopatico assassino.}
{453}{}{Va bene, questo e' disgustoso. Vediamo quanto sarai affascinante dopo che ti avro' fatto un paio di buchi in faccia.}
{454}{}{Niente male per un uomo del ghiaccio. Perche' ti avevano congelato li' dentro, comunque?}
{455}{}{Eh, non sei il mio tipo. Comunque, perche' ti avevano congelato li' dentro?}
{456}{}{Va bene, questo e' disgustoso. Vediamo quanto sarai affascinante dopo che ti avro' fatto un paio di buchi in faccia.}
{460}{}{Ok, da dove tiri fuori questa stronzata che sarei uno "psicopatico assassino"?}
{461}{}{Non provare a prendermi per il culo. Ho letto di te su quel computer.}
{462}{}{Quel computer laggiu' aveva una specie di biografia su di te, e c'erano dentro cose piuttosto terribili.}
{463}{}{I can sense it. You give off this vibe.}
{464}{}{Non provare a prendermi per il culo. Conosco quelli come te.}
{470}{}{Ah, ora ha senso. Senti, non preoccuparti per quello, non e' come pensi. Ti spiego tutto tra un
 secondo. Ma prima di tutto, ti dispiace dirmi che diavolo e' successo da quando mi hanno messo sul ghiaccio? Voglio dire, questo
 posto e' andato a puttane, e tu sembri uscita da una specie di racconto d'avventura fantascientifico.}
{471}{}{Sono passati piu' di centocinquant'anni da quando il Grande Silenzio ha posto fine agli Antichi... *la tua* gente.}
{475}{}{Grande Silenzio? Gli Antichi? Perche' non risparmi queste stronzate criptiche e mi dici semplicemente cosa e' successo?}
{476}{}{Il Grande Silenzio e' come il mio popolo chiama la fine del tuo mondo. Quando i grandi fuochi piovvero dal cielo e bruciarono la terra. Scoprirai che il mondo non e' affatto come quello che conoscevi.}
{480}{}{Non mi dire, quindi hanno davvero sganciato le bombe, eh? Immagino che il progetto Vault non fosse solo un enorme spreco dei soldi dei contribuenti, dopotutto.}
{481}{}{Wait. You know of the holy vaults?}
{490}{}{Conoscerle? Diavolo, vivevo proprio accanto al Vault di Chicago. Ho perfino visto finire di costruire quell'affare.
 Poi ovviamente hanno iniziato con quelle dannate esercitazioni... [Si ferma e ti guarda divertito.] Ti stai proprio bevendo
 tutto questo, vero, tesoro?}
{491}{}{DIMMI DI PIU' DEI VAULT!}
{492}{}{Vedi, sono stato scelto dalla mia gente per cercare un Vault. Li', spero di recuperare un G.E.C.K. e usare il suo potere
 per salvare il mio villaggio dalla distruzione. Qualsiasi cosa tu possa dirmi sui Vault potrebbe aiutarmi nella mia missione.}
{493}{}{Vedi, il mio popolo mi aveva scelto per cercare un Vault. Ho rischiato la vita in diverse occasioni per
 trovare questo Sacro Vault e alla fine ci sono riuscita. Sono curiosa di sapere cos'altro sai di questi luoghi.}
{500}{}{Ti dico una cosa, tesoro. Tu hai bisogno di aiuto per trovare questi Vault, e io ho bisogno di qualcuno che mi insegni come muovermi, per cosi' dire, in questo tuo mondo folle. Allora che ne dici... partner?}
{501}{}{I say you've got a deal... partner.}
{502}{}{Be', la tua conoscenza degli Antichi potrebbe rivelarsi molto utile per me... ma, sai, c'e' tutta quella faccenda dello psicopatico assassino...}
{503}{}{Non credo di avere tanta voglia di andarmene in giro per le Terre Desolate con uno psicopatico assassino. Quindi sei per conto tuo,
 "tesoro". Non preoccuparti, sono sicura che te la caverai benissimo. [risatina.]}
{510}{}{Ehi, come ti ho detto, posso spiegare. Tutto quello che hai letto su di me era una completa stronzata. Non crederci nemmeno per una parola.}
{511}{}{Ehi, come ti ho detto, posso spiegare. Queste vibrazioni malvagie che percepisci da me sono il risultato degli scienziati che
 hanno sperimentato su di me.}
{512}{}{Ma non ha alcun senso. Che cosa ti hanno fatto?}
{513}{}{Stronzate. Credo sia ora di farti tacere per sempre.}
{514}{}{Ma non ha senso, perche' dovrebbero mentire su di te?}
{515}{}{L'unica stronzata qui dentro e' quella che ti esce dalla bocca e credo sia ora di farti tacere per sempre.}
{520}{}{Ehi, lo so che non sembra avere molto senso, ma ti sei guardata intorno? Qui dentro non c'e' molto di sensato. Chi puo' sapere cosa passa per le menti fottute di questi scienziati.}
{521}{}{Hmm... su questo hai ragione. Non sto dicendo che ti credo... ma suppongo di poterti almeno ascoltare.}
{522}{}{Yeah, no kidding. Go on...}
{530}{}{Va bene, vedi, fa tutto parte dei loro "esperimenti". Quei fottuti medici pazzi stavano facendo una specie di test
 sulla "natura del male umano" o qualche stronzata del genere. Mi iniettavano i ricordi di un maniaco, per vedere come
 avrebbe influenzato la personalita' di una persona normale. Almeno, e' la spiegazione migliore che sono riuscito a darmi.}
{531}{}{Beh... se e' vero, e' terribile. Ma perche' hanno scelto proprio te come cavia, all'inizio?}
{532}{}{Oh, poverino. Ormai e' tutto nel passato. Quegli uomini terribili sono morti da tempo e non potranno piu'
 farti del male. Vieni con me e ce ne andremo da questo posto.}
{540}{}{Eh, vedi, e' proprio questa la cosa divertente. *Io* sono andato da *loro*. Ho risposto a un annuncio in cui dicevano che avrebbero pagato
 un sacco di soldi per soggetti sani su cui fare test. Avevo bisogno di soldi e, be', si e' rivelato il peggior errore della mia vita.
 Non posso nemmeno iniziare a descriverti gli orrori a cui mi hanno sottoposto. [I suoi occhi si velano di lacrime mentre ripensa. Sospira
 profondamente e si asciuga le lacrime.] Comunque, grazie a te, }
{541}{}{, I'm finally free of that nightmare.}
{542}{}{Huh. Well, I'm glad I could help... I think.}
{543}{}{In realta', stronzo, il tuo incubo e' appena iniziato, perche' non credo a una sola parola di quello che hai detto.}
{550}{}{Allora che ne dici, tesoro? Facciamo squadra? Non solo porto in dote il mio aspetto irresistibile, ma so
 cavarmela in uno scontro. Diavolo, potrei anche andare da solo, ma non ho la minima idea di che razza di follia
 si nasconda la' fuori adesso. Per quanto ne so, il primo albero su cui piscio potrebbe aprire la bocca e staccarmi il cazzo a morsi.}
{551}{}{Va bene, puoi viaggiare con me, ma ti terro' d'occhio. Nel momento stesso in cui anche solo pensi
 di uscire dai ranghi, ti abbatto.}
{552}{}{Certo, suppongo che possiamo fare squadra. Benvenuto nel gruppo, Dex.}
{553}{}{Era una dannata bella storia, e non sei nemmeno un cattivo attore, il che ti rende ancora piu' pericoloso. Credo che faro'
 un favore alle Terre Desolate e ti elimino prima che tu possa fare altro danno.}
{554}{}{I say you've got a deal... partner. }
{555}{}{Be', la tua conoscenza degli Antichi potrebbe rivelarsi molto utile... suppongo che abbiamo un accordo.}
{556}{}{Non ho davvero tempo di "insegnarti come muoverti". Sono sicura che te la caverai benissimo da sola, "tesoro".}
{560}{}{[Il sorriso di Dex vacilla e i suoi occhi si fanno assenti. Dopo un momento, inizia a parlare senza incrociare il tuo sguardo.]
 Ero uno dei loro malati esperimenti. Mi hanno fatto... cose terribili. [Scuote la testa, poi ti guarda con un sorriso rinnovato.]
 Comunque, preferirei di gran lunga parlare di te, tesoro.}
{561}{}{Oh, be', vediamo... Sono nata e cresciuta nel villaggio di Arroyo. Mia madre e' l'anziana del villaggio, e siamo discendenti diretti del leggendario abitante del Vault--}
{562}{}{Senti, Dex, potrei anche aiutarti, ma vorrei sapere con chi ho a che fare. Che cosa ti hanno fatto esattamente?}
{570}{}{Wow, davvero interessante, tesoro, e non vedo l'ora di sentire altro su di te. Davvero. Ma prima di tutto, che ne dici di spiegarmi che diavolo e' successo da quando mi hanno messo sul ghiaccio.
 Voglio dire, questo posto e' andato a puttane, e tu sembri uscita da una specie di racconto d'avventura fantascientifico.}
{580}{}{Va bene, devi proprio saperlo? D accordo. In pratica, quei fottuti medici pazzi stavano facendo una specie di test sulla "natura del male umano" o qualche stronzata del genere.
 Mi hanno iniettato i ricordi di un maniaco per vedere come avrebbe influenzato la personalita' di un bravo cittadino rispettoso della legge come me. Almeno, e' la spiegazione migliore che sono riuscito a darmi.}
{581}{}{Capisco. Quindi, come *ti* ha influenzato?}
{582}{}{I don't know, it gave me some nightmares, alright? Look honey, I've been through a lot and I'm not in the mood for a fucking interrogation right now.
 I answered your questions, now how 'bout you you fill me on what the hell happened since they put me on ice. I mean, this place has gone to shit, and you look like you've walked out of some kind of sci-fi adventure tale.}
{600}{}{[As you approach the cryogenic chamber, you see an attractive naked man sprawled on the floor. He draws his knees
 up and hugs them against his chest. He sits there for several moments, staring blankly ahead as his body quakes and his
 teeth chatter. Gradually, he seems to calm down.]}
{601}{}{Uh, hey...}
{610}{}{[He snaps his head towards you and leaps to his feet. He watches you intently, then glances around like a cornered
 animal. When his eyes return to you, they soften, and he relaxes as his memories come flooding back to him. He quickly
 alters his composure, projecting cool confidence, despite his nakedness.] I don't recognize you, bud. You don't mind if
 I get dressed do you?}
{611}{}{I guess there's no harm-}
{612}{}{Well, I-}
{620}{}{Of course you don't mind. Thanks, pal. [He steps past you and opens a nearby locker. He casually dresses himself
 in a finely tailored suit, then pockets the locker's contents. Utilizing a pocket comb, he begins to sculpt and style his
 slicked dark hair with the quick precision of a seasoned pro.] So, where's the doc? }
{621}{}{Beats me. Wherever he is, he's long dead by now. You see, you've been doing that popsicle impression for a REAL long time.}
{622}{}{Listen up, pretty boy. I didn't unthaw your psychotic ass so I could answer your questions and watch you groom yourself.
 I'm only letting you live long enough to tell me whatever useful information you might have. So start talking. The more
 you can tell me, the longer you get to live.}
{630}{}{Is that so? [He regards you curiously.] You don't exactly look like you belong here, bud, yet you've decided to
 release me and I'd like to know why. I assume you know who I am?}
{631}{}{Yeah, you're Dex, right? If what I read about you is true, then you're one evil son of a bitch. I like that.}
{632}{}{Beh, secondo quel computer, tu sei Dex, un assassino narcisista e sociopatico di prima del grande silenzio.
 Ti ho scongelato solo per poterti abbattere come il cane malato che sei.}
{633}{}{No idea, but you are giving off these evil vibes and I approve.}
{640}{}{[La sua calma svanisce e gli occhi si infiammano di rabbia.] Pensi di poter intimidire ME? Hai la piu' vaga
 FOTTUTA idea di chi stai parlando? Vieni qui e ti faccio vedere di cosa sono capace!}
{641}{}{[Done.]}
{650}{}{[Dex grins at you, revealing a set of perfect teeth-a product of pre-war dentistry that look strange to you in all
 their pearly white symmetry.] I knew there was something I liked about you. You've got good taste. I don't suppose you're
 also a fan of The King?}
{651}{}{Uh.... [Blank stare.]}
{652}{}{Oh yeah, I love that... uh, what'd you call it, The King? Yeah, huge fan.}
{660}{}{Nevermind, bud. [Dex takes another look around the room and whistles.] This place has really gone to shit.
 How long did you say it's been?}
{661}{}{Sono passati piu' di centocinquant'anni da quando il Grande Silenzio ha posto fine agli Antichi... *la tua* gente.}
{665}{}{Grande Silenzio? Gli Antichi? Perche' non risparmi queste stronzate criptiche e mi dici semplicemente cosa e' successo?}
{666}{}{Il Grande Silenzio e' come la mia gente chiama la fine del tuo mondo. Quando i grandi fuochi caddero dal cielo e bruciarono la terra. Scoprirai che il mondo non e' piu' nulla come quello che conoscevi.}
{670}{}{No shit, so they actually dropped the bombs, huh? I guess the vault project wasn't just a big waste of the tax-payers'
 money, after all.}
{671}{}{Wait. You know of the vaults?}
{680}{}{Know of them? Hell, I killed my first hooker not far from where they were building the Chicago Vault.
 Those were the days... [He stops and regards you with amusement.] You're really eating this up, aren't you?}
{681}{}{DIMMI DI PIU' DEI VAULT!}
{682}{}{Well, I'm supposed to be trying to find a Vault for my tribe. Once I do, I'm expected to find a G.E.C.K. so we
 can use its power to save my dying village. Anything you can tell me about the Vaults could make my job a hell of a lot easier.}
{683}{}{Well, you see, I had been chosen by my people to try and find a Vault. I risked my life on several occasions to
 find that damn Holy Vault and I finally was successful in finding it. I am curious what else you might know of these places.}
{690}{}{Ti diro' una cosa, amico. Tu hai bisogno di aiuto per trovare questi Vault, e io ho bisogno di qualcuno che mi faccia
 da guida, per cosi' dire, in questo tuo mondo impazzito. Allora che ne dici... partner?}
{691}{}{Hell, no need to try and convince me. I'd be happy to have you along just to see your handiwork first hand.}
{692}{}{I don't know, Dex. Let's just say I let you come along with me, and we make it back to the remote safety of a
 settlement. Once there, how do I know you won't try and slit my throat the first chance you get?}
{700}{}{I can tell you're no saint, so I could ask you the same thing. But to answer your question, I wouldn't kill you
 because that'd fuck me over. I'll be honest, }
{701}{}{, I don't give a fuck about anyone, or anything, except for myself. If the world is as fucked up as you say it is,
 then sticking with you is the best shot I've got. It's as simple as that.}
{702}{}{Fair enough. Let's go.}
{703}{}{I'm just fucking with you Dex. I never actually had any intention of bringing you with me. I just thought I'd
 have a bit of fun with you before caving your skull in.}
{800}{}{[As you approach the cryogenic chamber, you see an attractive naked man sprawled on the floor. He draws his knees
 up and hugs them against his chest. He sits there for several moments, staring blankly ahead as his body quakes and his
 teeth chatter. Gradually, he seems to calm down.]}
{801}{}{Uh, hey...}
{810}{}{[He snaps his head towards you and leaps to his feet. He watches you intently, then glances around like a cornered
 animal. When his eyes return to you, they soften, and he relaxes as his memories come flooding back to him. He quickly
 alters his composure, projecting cool confidence, despite his nakedness.] Hey doll, I know I'm quite the sight to behold,
 but it's a tad chilly in here. You mind if I get dressed?}
{811}{}{I guess there's no harm-}
{812}{}{Well, I-}
{820}{}{Of course you don't mind. Thanks, babe. [He steps past you, gently slapping your rump, and opens a nearby locker.
 He casually dresses himself in a finely tailored suit, then pockets the locker's contents. Utilizing a pocket comb, he
 begins to sculpt and style his slicked dark hair with the quick precision of a seasoned pro.] I don't think I've seen
 you around, doll, and I doubt I'd forget a face like yours. Name's, Dex, but I'm sure you know that. Mind if I ask yours?}
{821}{}{Sono }
{822}{}{. Ma sappi che ho una regola ferrea: non esco con uomini strani che scongelo io. Visto che sei rimasto sul ghiaccio per l'ultimo secolo e mezzo, faro' finta che la tua mano abbia avuto uno spasmo e mi abbia dato uno schiaffo al culo per sbaglio. Ma se succede di nuovo, ti strappo il cazzo. Chiaro?}
{823}{}{Il mio nome e' }
{824}{}{. It's nice to meet you, Dex. I can't imagine what it must be like to wake up after being frozen for over a hundred
and fifty years.}
{825}{}{Si', eccome se mi dispiace, fottuto schifoso. Ti ho scongelato solo per abbatterti come il cane malato che sei.}
{826}{}{Lascia perdere i nomi. Che ne dici di toglierti di nuovo quei vestiti e mostrarmi di che pasta sono fatti gli uomini del pre guerra.}
{830}{}{[Sorride e inizia a spogliarsi.] Sei il mio tipo, ragazza. Preparati a fare esperienza di Dex, il Duca del Sesso.}
{831}{}{[After an intense love making session on the floor of the chamber, the two of you collapse in exhaustion. You
 notice Dex slyly going for a hidden knife. You quickly clutch his genitals.]}
{832}{}{Touch that knife, and I'll turn you into the Dickless Duke. Besides, why ruin a good thing? The two of us could
 have so much fun together.}
{833}{}{I... think I'm in love. [Dex has joined your party.]}
{840}{}{Whoa, whoa, whoa. Back up a second, sweetheart. Did you just say a hundred and fifty years? [He shakes his head in disbelief.]
 That is un-fucking-believable. [He checks out his reflection.] But you gotta admit, I'm looking damn good for my age. [He grins at you, revealing a set of perfect teeth-a product of pre-war dentistry that look strange to you in all their
 pearly white symmetry.]}
{841}{}{Sure, some girls might think you're an attractive guy, but I'm sure they're a bit put off by that whole murderous
 psycho thing you've got going on.}
{842}{}{Va bene, questo e' disgustoso. Vediamo quanto sarai affascinante dopo che ti avro' fatto un paio di buchi in faccia.}
{843}{}{Sure, some girls might think you're an attractive guy, but I'm sure they're a bit put off by the murderous
 psycho vibes you're giving off.}
{844}{}{Niente male per un uomo del ghiaccio. Perche' ti avevano congelato li' dentro, comunque?}
{845}{}{Eh, non sei il mio tipo. Comunque, perche' ti avevano congelato li' dentro?}
{846}{}{Va bene, questo e' disgustoso. Vediamo quanto sarai affascinante dopo che ti avro' fatto un paio di buchi in faccia.}
{850}{}{Well they usually don't see that side of me until it's too late. But anyways... [Dex takes another look around the room and whistles.]
 This place has really gone to shit. So what have I missed out on?}
{851}{}{Sono passati piu' di centocinquant'anni da quando il Grande Silenzio ha posto fine agli Antichi... *la tua* gente.}
{855}{}{Grande Silenzio? Gli Antichi? Perche' non risparmi queste stronzate criptiche e mi dici semplicemente cosa e' successo?}
{856}{}{The Great Silence is what my people call the end of your world. When the great fires rained down from the sky and scorched the land.
 You'll find the world is nothing like the one you knew.}
{860}{}{Non mi dire, quindi hanno davvero sganciato le bombe, eh? Immagino che il progetto Vault non fosse solo un enorme spreco dei soldi dei contribuenti, dopotutto.}
{861}{}{Wait. You know of the vaults?}
{870}{}{Know of them? Hell, I killed my first hooker not far from where they were building the Chicago Vault. Those were the
 days... [He stops and regards you with amusement.] You're really eating this up, aren't you?}
{871}{}{DIMMI DI PIU' DEI VAULT!}
{872}{}{Well, I'm supposed to be trying to find a Vault for my tribe. Once I do, I'm expected to find a G.E.C.K. so we
 can use its power to save my dying village. Anything you can tell me about the Vaults could make my job a hell of a lot  easier.}
{873}{}{Well, you see, I had been chosen by my people to try and find a Vault. I risked my life on several occasions to
 find that damn Holy Vault and I finally was successful in finding it. I am curious what else you might know of these  places.}
{880}{}{I'll tell you what, babe. You need help finding these Vaults, and I need someone to show me the ropes, so to speak,
 in this crazy world of yours. So what do you say... partner?}
{881}{}{Hell, no need to try and convince me. I'd be happy to have you along just to see your handiwork first hand.}
{882}{}{I don't know, Dex. Let's just say I let you come along with me, and we make it back to the remote safety of a settlement.
 Once there, how do I know you won't try and slit my throat the first chance you get?}
{883}{}{I say you've got a deal... partner.}
{884}{}{Be', la tua conoscenza degli Antichi potrebbe rivelarsi molto utile... suppongo che abbiamo un accordo.}
{885}{}{Non ho davvero tempo di "insegnarti come muoverti". Sono sicura che te la caverai benissimo da sola, "tesoro".}
{890}{}{I can tell you're no saint either, so I could ask you the same thing. But to answer your question, I wouldn't kill
 you because that'd fuck me over. I'll be honest, }
{891}{}{, I don't give a fuck about anyone, or anything, except for myself. If the world is as fucked up as you say it is,
 then sticking with you is the best shot I've got. It's as simple as that.}
{892}{}{Fair enough. Lets go.}
{893}{}{I'm just fucking with you Dex. I never had any intention of bringing you with me. I just thought I'd have a bit
 of fun with you before caving your skull in.}
{900}{}{We'll get to that in a second. But first of all, how 'bout you fill me in on what the hell happened since they put me on ice.
 I mean, this place has gone to shit, and you look like you've walked out of some kind of sci-fi adventure tale.}
{1000}{}{What's the word?}
{1001}{}{[Dex cocks an eyebrow at you.] Something up?}
{1002}{}{Speak to me.}
{1003}{}{[Dex smiles.] What's up, pal?}
{1004}{}{You need something?}
{1005}{}{What can Dex do for ya?}
{1010}{}{What's the word?}
{1011}{}{[Dex cocks an eyebrow at you.] Something up, babe?}
{1012}{}{Speak to me baby.}
{1013}{}{[Dex smiles.] What's up, doll?}
{1014}{}{You need something? Anything? [Dex grins.]}
{1015}{}{What can Dex do for ya baby?}
{1100}{}{Sei pronto ad andare?}
{1101}{}{We takin' off, or what?}
{1102}{}{You ready yet? I'm itchin' to move.}
{1103}{}{So, you realized you're better off with me, huh?}
{1104}{}{We going now? I'm not in the habit of waiting around for others.}
{1105}{}{Come on. I was frozen for over a hundred and fifty years. I'm eager to move.}
{1106}{}{I'm getting impatient over here.}
{1110}{}{You ready to take me with you?}
{1111}{}{Andiamo.}
{1112}{}{No, non ancora.}
{1200}{}{So, what can you tell me about the Vaults?}
{1201}{}{So, now do you remember anything you can tell me about the Vaults?}
{1202}{}{Is there anything useful you can tell me about the time before the Great Silence?}
{1210}{}{Well, lets see... Huh. You know what? My mind's still a little foggy about some things. You'll have to ask me later.}
{1211}{}{Hmm. Alright.}
{1220}{}{The vaults... the vaults... Nope, not yet.}
{1221}{}{Hmm. Alright.}
{1230}{}{Yes, actually, I remember... Wait, never mind, I forgot.}
{1231}{}{Hmm. Alright.}
{1240}{}{Well, I used to live by the Chicago Vault. Does that help?}
{1241}{}{Do you know if it had a G.E.C.K.?}
{1242}{}{I'm sure it did. I'm pretty sure they all did.}
{1243}{}{Alright, now we're on to something. Can you tell me where this Vault is located?}
{1244}{}{No problem. It's about 2,000 miles in that direction. [Dex points eastward.]}
{1245}{}{Oh. Well then. Never mind.}
{1250}{}{There was one man, greater than any other, that we called, "The King". He was a handsome man with impeccable
 style, amazing hair, and a voice of gold. With a simple thrust of his pelvis he could impregnate every woman in sight.
 He was worshiped as a God by the people of the world. He was my father.}
{1251}{}{Interesting...}
{1260}{}{There were immortals that lived secretly among us. They had to battle each other to the death with swords until
 only one remained to claim "The Prize".}
{1261}{}{Wait. If they were immortal, how could they kill each other?}
{1262}{}{They could only be killed by decapitation. When one immortal decapitated another, a quickening
 would be released, giving the slain immortal's powers to the victor.}
{1263}{}{What exactly do you mean by "powers"?}
{1264}{}{Uh, fighting powers? Mechanic powers? I don't know, it was kind of vague.}
{1265}{}{Interesting...}
{1270}{}{There were these giant lizards, some bigger than buildings, that people would ride around on. We called them
 dinosaurs, and they were known as man's best friend.}
{1271}{}{Wow, did you have one?}
{1272}{}{Of course. I rode a T-rex, the most badass giant lizard of them all. Only mine was even more badass because it had wings. Basically, it was a dragon.}
{1273}{}{Interesting...}
{1280}{}{In the year 2011, The Awaking took place, and long dormant magical creatures, like Orcs, Elves, Trolls, and
 Dwarves returned to the world, along with magic. Magic and technology then clashed in a dark world of corporate warfare,
 waged in the shadows of the sprawling metropolises.}
{1281}{}{Wow, what happened to the magical creatures?}
{1282}{}{I guess they got taken out when the bombs fell. Except it looks like you've still got some Dwarves, Trolls,
 and Zombies around.}
{1283}{}{Interesting...}
{1290}{}{There was this gigantic green lizard called Godzilla. Godzilla would alternate between terrorizing Japan,
 and saving its ass against giant space invaders. There was another violent gigantic lizard called the Tarrasque. I think they were cousins or something.}
{1291}{}{Wow, what happened to them?}
{1292}{}{Godzilla got taken out by Ferris Bueller. As for the Tarrasque, we had a giant robot battle him. The robot,
 piloted by yours truly, punched the Tarrasque so hard that be broke apart into thousands of little Tarrasques that
 scattered all over California.}
{1293}{}{Interesting...}
{1300}{}{The earth was full of hot women, and I held the world record for the amount of sexual partners I had.}
{1301}{}{I see. You know, Dex, some of these things you're telling me are a bit... out there. I get this strange feeling
 that it might not all be true.}
{1302}{}{Hey, were YOU alive back then? No, you weren't. So who's the pre-war expert here? So trust me, it's all true.
 But hey, if you're not going to believe me, then I'm done telling you stories for now.}
{1303}{}{Huh. That's too bad, because they've been so helpful so far.}
{1400}{}{Just tell me where you want me.}
{1401}{}{Just tell me where you want me, babe.}
{1402}{}{No problem. I wouldn't want to make you nervous. [Dex grins.]}
{1403}{}{Sure. If you think you need to keep an eye on me, I'm fine with that.}
{1404}{}{Sure. I understand it's hard to concentrate when I'm too close. [Dex grins.]}
{1405}{}{[Dex cocks his eyebrow at you and winks.]}
{1406}{}{Nessun problema.}
{1500}{}{Why? You don't trust me with weapons? [He laughs.] Sure thing, if it'll put your mind at ease.}
{1600}{}{Uh, sure. But just so we're on the same page here, you know I'm into chicks... right?}
{1601}{}{All-right. [Dex strips off his armor and begins stripping off his clothes. He stops when he sees you glaring
 at him.] You're sending me mixed signals here, doll. Dex doesn't like to be toyed with. Just the armor it is.}
{1700}{}{Well, I can do wondrous things with knives. It's like an art. There's something very special about the way a
 blade slices into flesh, you know what I mean?}
{1701}{}{Uh... yeah, sure. Anything else you can use? Feel free to be less creepy about it this time.}
{1702}{}{Well, my Uncle was one of them military hard-asses. He trained me with pistols and SMGs, and I even got to toy
 around with some energy weapon prototypes they were working on. He thought I'd follow in his footsteps and be a
 puppet for Uncle Sam, but I, uh... Let's just say I went down a different path.}
{1703}{}{That sounds alright. Anything else?}
{1704}{}{I've been known to beat some ass with good 'ol fisticuffs. When I was a teen, I tried my hand at Karate for
 awhile, but they kept feeding me all this shit about being more disciplined, so I told 'em to fuck off. Anything else you need to know?}
{1705}{}{That should cover it. Thanks.}
{1800}{}{Sono pronto all'azione.}
{1801}{}{I've been better, but I can handle it.}
{1802}{}{I'm not feeling very good.}
{1803}{}{I think I hear the King calling. I can see the light...}
{1900}{}{No problem. But you're going to feel a lot less cool without me around. Just saying...}
{1901}{}{Sure. I'll catch ya later.}
{1902}{}{Sure, I'll wait. But if you don't come back, then I'm going to start looking for you, and it won't be pleasant
 when I find you.}
{1903}{}{Alright, as long as you aren't just ditching me to make room for some other jerk. Because I promise you I'm
 better than them in every conceivable way.}
{1904}{}{Nessun problema.}
{1905}{}{No problem, babe.}
{1906}{}{Alright, as long as you aren't just ditching me to make room for some other jerk. Because I promise you I'm
 better than them in every conceivable way.}
{1907}{}{Getting you too hot and bothered am I? I understand.}
{2000}{}{Alright, what about it?}
{2001}{}{Look, I know I was on ice for a long time, but trust me, everything is in PERFECT working order. If you want,
 I'll prove it to you right here, right now. [Dex stops when he sees you glaring] Oh, I see, my *other* gear. What about it?}
{2010}{}{It's a bit crowded. Let me know if things open up.}
{2020}{}{No way in hell I'm traveling with you. You're ugly as fuck.}
{2030}{}{Let's roll.}
{2031}{}{About time we got goin' again.}
{3000}{}{So, what's your story?}
{3001}{}{What, like my life story? Look, I know I'm pretty fascinating, but I don't want to stand around talking forever.
 My mouth will get all dry and there's not a whole lot of water to go around-it's just not a good situation to be in.
 But I suppose I could sum it up for you if you really want to know... Actually, I DO like to talk about myself so I'll
 leave up to you. You want the quick summary or the version with more detail?}
{3002}{}{Just give me the quick summary.}
{3003}{}{Lets hear the detailed version.}
{3004}{}{Never mind, I lost interest.}
{3010}{}{Alright, basically, ever since I was a kid, I liked to kill things. I could talk about my childhood and my
 shitty parents and try to analyze why I like to do it, but I don't need an excuse. I do it simply because I can, and
 it's fun. By the time I was sixteen I spent my days as a popular high school heartthrob, and my nights as a ripper of
 Chicago's young working girls.}
{3011}{}{Uh huh. Go on.}
{3012}{}{Then one day I caught my girlfriend making the beast with two backs with another guy. I butchered them, set
 the place on fire, then high tailed it out of Chicago. Spent the next ten years traveling the nation, seducing girls,
 then cutting 'em up. Then they finally caught me, and my trail turned me into a celebrity.}
{3013}{}{So, then what?}
{3014}{}{So then one of my new fans, Alice, helps me escape. The two of us go on a three week cross country murder rampage
 before we finally go down in a shootout. Then, for some reason, The Man decides to stitch me back together and run all
 these tests on me. And that's how I wound up at the EPA where you found me.}
{3015}{}{Grazie per la storia.}
{3020}{}{Let's see.... My Mom was a drug fiend and a whore, and my Dad was an ornery drunken bastard. Fortunately, my
 grandpa was alright for an old guy. Introduced me to The King's music. Unfortunately, he was claimed by the New Plague
 when I was seven. Then when I was ten, I watched from the closet as my Dad beat my Mom to death for forgetting to feed
 our dog, Captain Robeenie.}
{3021}{}{This is off to a pleasant start. Go on.}
{3022}{}{The bitch should've remembered to feed the Captain. Go on.}
{3023}{}{So they put my Dad away and shipped me off to live with my Aunt and Uncle. You see, I was a little hell-raiser,
 even then, and my Uncle, being a military sort, thought he'd be able to straighten me out-turn me into a Red slaying
 soldier boy, just like the son he'd lost. He gave it his best shot, but I was a stubborn son-of-a-bitch.}
{3024}{}{Uh huh. Go on.}
{3025}{}{So anyway, we did a lot of moving around and it wasn't until I was in high school that we finally settled down
 in Chicago. That's when I took to sneaking out at night and knifing hookers. I'd been killing things for as long as I
 could remember, but gutting neighborhood critters didn't compare to the real deal, you know?}
{3026}{}{Bene.}
{3027}{}{So things were pretty sweet, for the most part. I mean, I fucking hated my Uncle and Aunt, but at school I was
 Mr. Popular. Every guy wanted to be my friend and every gal I looked at was willing to spread for me. Except for this
 one gal, Vicky. She actually took a bit of work. Amazing, I know, but eventually I got her to come around and become my girl.}
{3028}{}{And all the while you were moonlighting as a serial killer?}
{3029}{}{I don't really care about your high school sweetheart. Forget the story.}
{3030}{}{Yeah. [Dex grins.] Those were the days. I was actually happy, you know? After we graduated, Vicky and I got our
 own little place together, and everything was aces. But that bitch had to go and ruin everything by sneaking around behind my back.}
{3031}{}{How dare she.}
{3032}{}{I caught her in the act, and I lost it. Things got real brutal. It was sloppy and there was no way I was going to
 be able to just cover it up. So I set the place on fire and hit the road. Did a lot of traveling, laid a lot of girls and
 left most of 'em dead. It wasn't a bad life, you know? It took 'em ten years, but the law finally caught up with me.}
{3033}{}{Uh-oh. So then what?}
{3034}{}{Then they put me on trial and it became a bit of media circus. The girls loved it because I'm a dreamboat,
 and everyone else loved it because it was a distraction from news about the New Plague and politics. So I thought I'd
 give 'em a real show.}
{3035}{}{What'd you do?}
{3036}{}{Well by then I'd made plenty of fans, but there was this one in particular, a real doll named Alice. She said
 she loved me and would do anything for me. So during my trail, she helped me make a break for it. It was a long shot,
 but we were lucky enough to pull it off. Then things got crazy... Are you sure you never heard about any of this?}
{3037}{}{I'm sure, but go on.}
{3038}{}{Never heard of it, and now I never want to. Just forget it, I'm bored.}
{3039}{}{Well now that I was with Alice, it was kind of hard to revert back to my old ways of seducing women and slicing
 them open. Instead, we just starting thrill killing anyone that was convenient. It didn't matter how young or old, we
 were equal opportunity killers. But killing recklessly like that, we were easy to track. In three weeks they had us
 cornered. They gunned me down and Alice blew her own brains out.}
{3040}{}{I see. Then what?}
{3041}{}{So there I was, certain I was going to die, but then these G-Men stepped in and took me away. They got me back
 to a hundred percent, then started doing these tests on me, trying to figure out what makes me the way I am... Anyway,
 you can figure the rest, and my throats dry from talking. Damn, I was hoping to avoid that.}
{3042}{}{Grazie per la storia.}
{3100}{}{Any tips you might be able to give me?}
{3101}{}{Tips? What kind of tips?}
{3102}{}{Well, I'm sure you've got some skill.}
{3103}{}{Oh, I've got all *kinds* of skills. But if you're looking for advice... [He looks you over, then nods.] Alright,
 what the hell. I'll give you some pointers that'll have the ladies crawling at your feet. Now, the first thing you gotta do is...}
{3104}{}{You wanna see my skills? I'll show you my skills anytime, sweetheart. But if you're looking for advice...
 [He looks you over, then nods.] Alright, what the hell. I'll give you some pointers that'll have the fellas eating out of
 your hands. Now, the first thing you gotta do is...}
{3105}{}{There you go. Now don't be telling other people these trade secrets.}
{3106}{}{Grazie.}
{4000}{}{Man do I love the post-nuclear future.}
{4001}{}{Come on. Let's have some violence.}
{4002}{}{Let's find some more young ladies to, uh, admire.}
{4003}{}{Let us seek more carnal knowledge.}
{4004}{}{You ever just sprawl a girl out on a bed and cut her open? I tell ya, absolute beauty.}
{4005}{}{I really need to cut something soon...}
{4006}{}{You'd think a corpse would be terrible in bed, but you'd be surprised.}
{4007}{}{[singing] I put an ax in my baby's head, I'm gonna end up doing time... she looked so good in red...[singing]}
{4008}{}{[singing] 'caus I'm eviiillllll, my middle name is, miseerryyy...[singing]}
{4009}{}{You dig my suit? This sweet baby was made in Grand Rapids, Michigan.}
{4010}{}{So... where about the wasteland do you think they keep the hair gel?}
{4011}{}{I know it sounds a bit gross, but don't knock deep fried ovaries 'til you've tried 'em.}
{4012}{}{[Removes pocket comb and fixes hair.]}
{4020}{}{Hey! I'm fuckin' bleeding over here.}
{4021}{}{Oh man, I'm not doing too well.}
{4022}{}{Get me to a fucking doctor.}
{4023}{}{You gonna just stand there and watch me bleed to death or are you going to do something about this?}
{4030}{}{I'm feeling a little weird over here...}
{4031}{}{Hey, I'm feeling a bit radiated. If this isn't the kind that grants super powers, then I'm going to be pissed.}
{4040}{}{You know, you're a bad influence.}
{4041}{}{I try to stay away from this stuff. But if you insist...}
{4042}{}{My body's a temple, but I guess this once won't hurt.}
{4043}{}{If this does any permanent damage, I'm going to cut you.}
{4045}{}{I feel much better now.}
{4046}{}{Much better.}
{4050}{}{Hey! Watch the hair.}
{4051}{}{Hey, you don't rush perfection.}
{4060}{}{It just isn't the same when their blood's still warm, ya know?}
{4061}{}{I hope you took notes.}
{4062}{}{Girls have gotten pretty freaky since the end of the world... I dig that.}
{4063}{}{...and thats why the babes used to call me "Dex, the Duke of Sex".}
{4070}{}{I feel nauseated. I think I'm poisoned.}
{4071}{}{I feel like I'm gonna puke my guts out.}
{4080}{}{I can't move this limb. I need medical attention.}
{4081}{}{I think I lost feeling in this limb. Is that bad?}
{4090}{}{It just got really blurry. Where'd everyone go?}
{4091}{}{I think blood is coming out of my eyes.}
{4100}{}{So, facial tattoos, huh? I guess if I was as ugly as bone-nose, here, I'd want to cover that up too.}
{4101}{}{Yo, face-tats. You the cannibalistic sort? Maybe we could exchange recipes or something.}
{4102}{}{I get the feeling your pal Sulik here doesn't dig me too much. You ever think about selling the guy off for some cash?}
{4110}{}{Seriously, what's with the dumpy bald dude? You keeping him out of pity or something?}
{4111}{}{So Vic, I hear you've got a spunky daughter. You should introduce me to her.}
{4120}{}{Miria, honey, we really need to spend some one-on-one time together.}
{4121}{}{So I'm guessing we get to take turns with Miria, right?}
{4122}{}{[Winks at Miria.]}
{4123}{}{[Smiles at Miria.]}
{4124}{}{Miria, you need a man who's in the same league as you. You know, one like me.}
{4125}{}{[Brandishes knife at Miria. Grins.]}
{4130}{}{I say we put a hole in Davin's head and roll him into a ditch.}
{4131}{}{Let's say, hypothetically, that Davin somehow gets his throat slit in his sleep tonight. No one's gonna care, right?}
{4140}{}{Hey Cassidy, you should really try some Psycho. I heard it can even re-grow hair.}
{4141}{}{Why don't you hit that booze a little harder, Cassidy? It seems to have aged you so well.}
{4142}{}{It's pathetic to see someone as old as Cassidy trying to hold on to life. If I were in his shoes,
 I'd kiss the barrel of a shotgun and just end it.}
{4150}{}{Lets say we ditch the walking corpse.}
{4151}{}{Alright, this whole joke about bringing Lenny along has gone on a little long now, don't you think?}
{4152}{}{How the hell am I supposed to pick up the ladies with Lenny hanging around?}
{4160}{}{So, uh, Marcus, when do you revert back to the mild mannered physicist?}
{4161}{}{Hey Marcus, don't you have some kind of town you're supposed to be running?}
{4170}{}{Hang in there Myron, I'm sure someday your balls will drop.}
{4171}{}{The Dork-boy's kinda cramping my style.}
{4172}{}{Myron's like one giant pimple, just waiting to be popped.}
{4180}{}{At least Goris has the decency to cover himself.}
{4181}{}{Good job blending in, Goris. You look just like a typical hunchbacked freak.}
{4200}{}{I'm curious to see what these tribal women are like.}
{4210}{}{Whores... whores everywhere. I love this fucking place.}
{4220}{}{This place is just begging for some chaos.}
{4230}{}{There's too many cops here. I say we bail.}
{4240}{}{Great, more freaks. We better not stay here longer than we have to.}
{4250}{}{We're wasting our time here. Zombie chicks aren't my thing. I generally don't like gals to look dead until AFTER I'm through with 'em.}
{4260}{}{Perche' diavolo stiamo perdendo il nostro tempo qui? Sul serio?}
{4270}{}{I don't think I want to willingly spend any more of my time in this facility.}
{5000}{}{[He snaps his head towards you and leaps to his feet. As he looks at you, his eyes suddenly get really wide and he starts gasping for air.]}
{5001}{}{[FINE]}
{5002}{}{Oh, merda!}
