{100}{}{Vedi il Sergente Cat Jules.}
{101}{}{Vedi un bell'uomo di colore con canini piuttosto pronunciati. Si muove con aria spavalda e ha un'espressione
 compiaciuta sul volto.}
{200}{}{[Mentre ti avvicini alla camera criogenica, vedi un uomo di colore snello e nudo disteso sul pavimento.
 Il suo corpo muscoloso trema ancora per l'acqua gelida e fredda. Ti guarda mentre ti avvicini.]}
{201}{}{Chi sei?}
{210}{}{[Alzandosi in piedi e scuotendosi per asciugarsi come un animale bagnato, l'uomo ti guarda e sorride beffardo, rivelando alcuni denti anteriori stranamente affilati.]
 Chi sono *io*? Chi sei *tu*? Sembri un barbone pesantemente armato!}
{211}{}{[Alzandosi in piedi e scuotendosi per asciugarsi come un animale bagnato, l'uomo ti guarda sorridendo ampiamente, rivelando alcuni denti anteriori stranamente affilati.]
 Chi sono *io*. Ma dai, sono solo il Serg. Jules, il soldato piu' bello di questa base, bella!}
{212}{}{Sono }
{213}{}{. Ma, come ti chiami?}
{214}{}{Non fare il galletto con me. Cos'ha di speciale questo posto comunque?}
{215}{}{Capisco. Bene, Serg. Jules, cosa sta succedendo qui comunque?}
{216}{}{Come mai sei vivo? Il Dottore ha detto che era l'unico sopravvissuto.}
{220}{}{Mi chiamo Serg. Jules, ma puoi chiamarmi Cat. Sono il soldato piu' veloce e piu' bello di questa base.}
{221}{}{Certo, come dici tu. Allora, cosa c'e' con questo posto?}
{230}{}{Intendi il Dottor C? Perche' si sarebbe dimenticato di me? Diavolo, ha contribuito a plasmare questa opera d'*ARTE* [Indica il proprio corpo].}
{231}{}{Certo, come dici tu. Allora, cosa c'e' con questo posto?}
{232}{}{Penso che stiamo parlando di due persone diverse... Allora, cosa sta succedendo qui intorno comunque?}
{240}{}{E' una struttura governativa per quanto ne so. Fanno ogni tipo di ricerca top secret. Ma...[Si guarda intorno
 nella stanza.] e' stranamente silenziosa. Dove sono tutti?}
{241}{}{Be', questo probabilmente ti sconvolgera', ma sei stato congelato per oltre un secolo. Il mondo
 non e' piu' lo stesso. Hanno sganciato le bombe e la Terra e' piombata nel silenzio. La societa' sta ancora cercando di ricostruirsi dalle
 ceneri.}
{250}{}{[Il Serg. Jules ti guarda con un sopracciglio alzato.] Non stai scherzando, vero? Be', allora l'hanno davvero fatto.
 Accidenti. Immagino di essere stato fortunato ad essere stato tolto dall'esercito e portato qui.}
{251}{}{Sei stato nell'esercito?}
{260}{}{Esatto. Ero l'esperto di armi energetiche. Abbastanza agile sui piedi anche. Ero stato nell'esercito solo per circa un anno
 prima di essere riassegnato qui. E' un peccato che non vedro' mai piu' nessuno dei miei amici. Avrei voluto scambiarci qualche addio.}
{261}{}{Mi dispiace.}
{262}{}{Mi dispiace per le tue perdite, ma devi andare avanti. Crogiolarti nella tua miseria non ti portara' da nessuna parte.}
{270}{}{Si', lo siamo tutti. Cosa faro' adesso pero'?}
{271}{}{Suppongo che tu abbia ragione. Ma cosa faro' adesso?}
{272}{}{Beh, potrei usare un compagno. Vuoi unirti a me?}
{273}{}{Be', devo proprio andare. In bocca al lupo la' fuori.}
{280}{}{Ehi, perche' no! Ti mostro che questo Cat ha ancora quello che ci vuole.}
{281}{}{Sembra un buon piano. Andiamo.}
{282}{}{Come desideri.}
{290}{}{Non preoccuparti per questo vecchio gatto. Trovero' il mio posto in questo mondo. Ora fatti da parte e lascia fare al Cat.}
{291}{}{[FINE]}
{300}{}{Allora, come sei finito in quella camera criogenica? E cosa e' successo ai tuoi denti?}
{301}{}{Ero la guardia di uno dei laboratori di genetica. Stavano giocando con il DNA umano e felino.
 Cercando di creare qualcosa con il meglio di entrambi i mondi, suppongo. Ed e' qui che entra in gioco il sottoscritto.
 [Cat ti mostra il suo sorriso dentuto.] Volevano un volontario per uno dei loro progetti. Era per le reclute e simili, doveva
 renderti piu' agile e flessibile. Mi piaceva l'idea *sorride maliziosamente*. Comunque, mi hanno fatto questa iniezione, mi hanno addormentato, e
 la prossima cosa che ricordo, avevo questi denti, e mi sentivo.... piu' acuto? Un po' predatorio.}
{302}{}{Continua.}
{303}{}{Be', apparentemente l'esperimento non stava andando come previsto e qualunque cosa mi avessero messo dentro non si adattava
 bene al mio sistema. Non so cosa intendessero con quello, visto che mi sentivo meglio che mai. Hanno deciso di buttarmi nel
 congelatore criogenico finche' non capivano cosa fare di me.}
{304}{}{E poi ti ho scongelato. Sembra che tu me ne debba una.}
{305}{}{Si', mi hai salvato. In cambio, forse posso salvare il tuo senso dello stile, scimmia.}
{306}{}{Scimmia? Dev'essere il DNA felino che parla. E' tutto quello che mi serve sapere per adesso.}
{310}{}{Visto che sei stato nell'esercito, pensi di potermi insegnare qualcosa?}
{311}{}{Potrei insegnarti qualcosa sulle armi energetiche e altre armi pesanti. Ora devi ricordare...}
{312}{}{[Continua]}
{313}{}{Ecco fatto. Questo dovrebbe aiutarti a far sciogliere quei mutanti che ti si mettono in mezzo.}
{314}{}{Grazie.}
{390}{}{Sei pronto a portarmi con te?}
{391}{}{Andiamo.}
{392}{}{No, non ancora.}
{400}{}{Ti serve qualcosa?}
{401}{}{Come puo' servirti il Gatto?}
{402}{}{Si'?}
{410}{}{Che cosa vuoi sapere?}
{411}{}{Be', sono stato addestrato a usare la roba militare solita. Fucili, pistole, mitra e simili. Preferisco pero' le armi laser
 e simili. Quelle hanno stile! Ma se mi dai dei tirapugni o uno di quei pugni potenziati,
 salto addosso a qualsiasi tirapiedi prima che capiscano cosa li ha colpiti!}
{421}{}{Cosa c'e' che non va?}
{422}{}{D'accordo. Ti copro le spalle.}
{423}{}{A me sta bene.}
{424}{}{Comunque lavoro meglio da solo.}
{430}{}{Non ho molta pazienza, quindi torna in fretta.}
{431}{}{Non sono un tipo paziente. Non metterci troppo.}
{440}{}{Stiamo partendo?}
{441}{}{Era ora che tornassi.}
{450}{}{E' bello essere di nuovo in movimento. Le mie gambe hanno bisogno di continuare a muoversi.}
{451}{}{Era ora che facessimo qualcosa insieme di nuovo.}
{460}{}{Certo, fa schifo comunque. Hai qualcosa in blu?}
{470}{}{Ok, ma questa e' la mia cosa *lucente*. E se cerchi di togliermela, potrei doverti sparare.}
{480}{}{Mi sento in perfetta forma.}
{481}{}{Solo qualche graffio, niente di cui preoccuparsi.}
{482}{}{Ho visto di peggio nell'esercito.}
{483}{}{Chiama un medico. Sto cedendo in fretta.}
{484}{}{Adesso sto sanguinando da ogni parte...}
{490}{}{Gesu', sei brutto. Dovresti farti controllare. Me ne vado.}
{491}{}{Tesoro, sei diventato davvero brutto. Me la squaglio.}
{500}{}{Non fraintendermi, e' bello stare insieme, ma stai esagerando un po'. Torna quando hai meno gente.}
{501}{}{Non fraintendermi, e' bello stare insieme, ma stai esagerando un po'. Torna quando hai meno gente. Ora mentre fai spazio,
 vado a trovare dei vestiti da indossare. [Guardandosi intorno, Cat Jules scorge un armadietto, lo apre e guarda dentro.]
 Non sono proprio il mio stile, ma immagino che andranno bene. [Si veste rapidamente.]
 Bene, fammi sapere quando sei pronto.}
{510}{}{Ho mangiato del pesce andato a male o cosa? Mi sento avvelenato.}
{520}{}{Mi sento come se stessi sciogliendomi. Dev'essere avvelenamento da radiazioni.}
{530}{}{Come ti aspetti che faccia del mio meglio con questo arto rotto?}
{540}{}{Chi ha spento le luci? Credo che ci sia qualcosa che non va con i miei occhi.}
{600}{}{Qualcuno potrebbe dire che sono un tipo piuttosto superficiale, ma un tipo superficiale con un gran fondoschiena.}
{601}{}{Nell'esercito era sempre, "Cat fai questo. Cat fai quello." Cosa sono, un cane?}
{602}{}{[cantando] Perche' mi fai annodare la lingua, annodare la lingua... [cantando]}
{700}{}{SIGNORE! Signore, una alla VOLTA, per favore!}
{710}{}{Ho il naso per i guai, e sta suonando come una sirena d'attacco nucleare!}
{720}{}{Miniere d'ORO? E' qui che scavano le cose lucenti?}
{730}{}{Pensavo che ce ne fossimo andati da questo posto per sempre.}
{800}{}{Ne ho abbastanza di pazzi arroganti! Possiamo lasciare questo piccolo idiota untuoso?}
{810}{}{Cosa te ne fai dell'osso, Neanderthal?}
{820}{}{Almeno non sono finito come TE, Lenny!}
{830}{}{Almeno non sono finito come TE, Marcus!}
{2900}{}{Ho bisogno di mettermi qualcosa addosso prima. [Guardandosi intorno, Cat scorge un armadietto, lo apre e guarda dentro.]
 Non sono proprio il mio stile, ma immagino che andranno bene. [Si veste rapidamente.] Bene, sono pronto.}
{2901}{}{[FINE]}
{5000}{}{[L'uomo si alza in piedi e si scuote per asciugarsi come un animale bagnato. Mentre ti guarda, i suoi occhi si spalancano improvvisamente e inizia ad ansimare per l'aria.]}
{5001}{}{[FINE]}
{5002}{}{Oh, merda!}
