{100}{}{You see a specimen from the Storage Tanks.}
{101}{}{You see Kitsune.}
{102}{}{I suoi occhi sono di colori diversi. Uno di loro marrone come malmbrick, l'altro verde brillante.}
{103}{}{You see a slender, dark-haired woman who looks difficult to predict.}
{104}{}{Ha un viso delicato e occhi ammalianti.}
{150}{}{It's not nice to stare.}
{200}{}{Davanti a te c'e' un serbatoio aperto con acqua gelida che viene lentamente drenata attraverso un lungo tubo serpentino. Dentro, una
 donna, nuda dalla testa ai piedi, giace ansimante e tremante. Guardandoti rapidamente intorno, prendi un fascio di vestiti larghi
 da un armadietto vicino e li drapi su di lei per scaldarla.}
{201}{}{Wow. Dev'essere stato un bel viaggio. Stai bene?}
{202}{}{S-si', il p-p-preservatore h-ha r-ripristinato la t-t-temperatura d-del m-mio c-corpo.}
{203}{}{Non tutta, a quanto pare. }
{204}{}{[Le dai un po' di tempo perche' i denti smettano di battere. Si riprende molto piu' in fretta di quanto ti aspettassi
 e ti guarda con improvvisa seriosita'.] E'... finita?}
{205}{}{Is what over? }
{206}{}{You mean the War?}
{207}{}{The War. All those nukes.}
{208}{}{The War, yes.}
{209}{}{Quella guerra e' finita molto tempo fa. E' finita quasi appena e' iniziata.}
{210}{}{[Si sposta ciocche di capelli bagnati dagli occhi. Noti che un occhio e' marrone mentre l'altro e' verde smeraldo.] Chi ha vinto?}
{211}{}{No one.}
{212}{}{[Ti guarda con aria assente. E' molto piacevole alla vista, specialmente per qualcuno che e' stato appena scongelato da un blocco di ghiaccio.]}
{213}{}{Quando il 90% del mondo e' carbonizzato fino a diventare marrone croccante, direi che e' difficile dichiarare un chiaro vincitore.
 Voglio dire, non rimaneva molto che valesse la pena di vincere.}
{214}{}{Che... che data e'? Che anno? E' ancora il 2077?}
{215}{}{Cavolo, no. [Le mostri la data sul calendario del tuo Pip-Boy.]}
{216}{}{[Fissa lo schermo tremolante, congelata nel tempo come se non avesse mai lasciato il serbatoio.]}
{217}{}{Are you alright?}
{218}{}{Dio mio. Non ci credo. Ero in quella cosa per oltre un secolo?!}
{219}{}{Sembra di si'. Ehi, senti, non guardarmi cosi'. Non c'entro niente con il fatto di averti messa la' dentro. Accidenti,
 mio nonno non era nemmeno vivo a quei tempi. Mi sono imbattuto per caso in questo posto e ho deciso di darci un'occhiata.}
{220}{}{Be', mi aiuti ad alzarmi, o preferiresti che continuassi a stare nuda ai tuoi piedi?}
{221}{}{Stavo per farlo. [La aiuti ad alzarsi in piedi.]}
{222}{}{Why did you wake me?}
{223}{}{No particular reason.}
{224}{}{Ho questa terribile abitudine di toccare tutto quello che incontro. Una cosa ha portato all'altra.}
{225}{}{You say you don't even work in this place?}
{226}{}{That's what I said.}
{227}{}{Allora se non fossi arrivato, sarei rimasta bloccata in quella cosa ancora piu' a lungo. Forse per sempre.
 (Si infila una delle magliette in cui l'avevi avvolta.) Com'e' adesso, il mondo la' fuori?
 Hai detto che il 90% e' stato distrutto?}
{228}{}{Il mio mondo e' una landa desolata dove ogni giorno e' una lotta per la sopravvivenza. La maggior parte delle persone ha trovato rifugio nei resti in rovina di quelli vecchi.
 Altri, come la mia tribu', cercano di costruirsi una semplice esistenza nella dura natura selvaggia. A dire il vero, potrebbero volerci secoli prima che si avvicini anche solo a riprendersi.}
{229}{}{Non puo' essere cosi' brutto come sembra. [Non sembra convinta di una sola parola di quello che ha appena detto.]}
{230}{}{Non e' per niente come l'America del 2077, questo e' sicuro.}
{231}{}{[Si infila un paio di pantaloni.] Allora, e adesso?}
{232}{}{Non ci siamo mai presentati come si deve. Il mio nome e' }
{233}{}{. What's yours?}
{234}{}{You can call me Kitsune.}
{235}{}{Kitsune, what were you doing cryoed away in that tank?}
{236}{}{Non lo so con certezza. Sapevano che la Guerra stava per succedere, cosi' mi hanno messa in un preservatore come gli altri.}
{237}{}{Do you have any clue what this place is?}
{238}{}{Per quello che so, e' una filiale dell'Agenzia per la Protezione Ambientale degli Stati Uniti. Ero in Arizona quando e'
 scoppiata la Guerra. Sono stata portata qui immediatamente.}
{239}{}{Dovevi essere piuttosto importante perche' volessero preservarti. Eri una Prescelta, come me?}
{240}{}{Ehm, non esattamente. Ero una casalinga, sposata con un consigliere. Prima di allora scrivevo per diverse pubblicazioni giornalistiche. Non era quello che si definirebbe una vita terribilmente eccitante.}
{241}{}{What happened to him, your husband?}
{242}{}{Non lo so. Probabilmente una delle miliardi di vittime. Dubito che qualcuno della mia famiglia sia sopravvissuto alla guerra. Dio mio, anche se cosi' fosse, e' passato cosi' tanto tempo... tutti quelli che ho mai conosciuto sono morti. [Si morde il labbro e i suoi occhi iniziano a luccicare di lacrime, ma le asciuga rapidamente e sospira, riprendendo il controllo di se'.]}
{245}{}{Be', visto che mi stai dando una scelta... (sorride maliziosamente)}
{246}{}{[She glares at you wordlessly.]}
{247}{}{Oh, voglio dire, certo che ti aiuto ad alzarti. [La aiuti ad alzarsi in piedi.]}
{250}{}{What are you going to do now?}
{251}{}{Non lo so. Cosa fai quando hai ibernato per oltre un secolo? Nemmeno gli orsi dormono cosi' a lungo.
 Il mondo la' fuori non e' il mondo che conoscevo. Non so se potrei sopportare di vedere cosa e' diventato.}
{252}{}{So che la' fuori e' una landa desolata, ma hai ancora tutta una vita da vivere. La stai sprecando qui sotto.
 Vieni con me e forse possiamo fare qualcosa di buono.}
{253}{}{Non sembra che tu abbia molta scelta. Puoi sederti qui a marcire, oppure puoi venire con me. Dipende da te.}
{260}{}{Sai, hai ragione. Potrei tornare ad essere congelata e dormirci su per altri cento anni, ma sarebbe la via facile.
 Ho bisogno di vedere con i miei occhi cosa e' diventato il mondo, e avere un ruolo nel rimetterlo insieme.}
{261}{}{Dai allora. Andiamo a prendere prima di tutto una bistecca di brahmin.}
{262}{}{Don't make me regret this.}
{270}{}{Lascia perdere. E' cosi' da oltre cento anni. Cosa ti fa pensare che lo sistemeremo adesso?}
{271}{}{I'll come back. Maybe you'll change your mind.}
{272}{}{Forse. Ma non contarci. Dovrei semplicemente tornare a dormire per un altro secolo o giu' di li'.}
{280}{}{E se queste macchine smettessero di funzionare pero'? Saresti morta e non sapresti mai
 se il mondo che si e' fatto saltare in aria si e' mai rimesso insieme.}
{281}{}{Allora lo guardero' da dove mi trovero'.}
{282}{}{Come fai a sapere con certezza che sarai portata in un posto speciale dopo il sonno eterno? Vengo da una
 tribu' che crede nell'aldila' e nelle profezie, ma da un punto di vista pragmatico siamo tutti solo un mucchio di macchine organiche
 che pensano, parlano e sentono grazie a carne e componenti chimici. E se non ci fosse nulla dopo la morte -- ci spegniamo come computer --
 e questo e' tutto quello che hai?}
{283}{}{Preferirei rischiare nella sospensione criogenica piuttosto che vagare per quella landa desolata.}
{284}{}{Oh yeah? You don't seem all that sure anymore.}
{285}{}{[Kitsune riflette sulle tue parole per un bel po'. Alla fine, incontra il tuo sguardo.] Non posso fingere che tu non abbia ragione. Forse... forse rischio con te.}
{286}{}{Usciamo da qui, allora. E' ora di lasciarci questo buco alle spalle.}
{287}{}{In realta', penso che me la cavero' da sola. Sono sempre stata il tipo indipendente, quindi non dovrebbe pesarmi. E' cambiato molto da quando sono via e vorrei vederlo con i miei occhi. Grazie per avermi scongelata. Prenditi cura di te.}
{288}{}{[Fatto]}
{300}{}{Si'?}
{301}{}{I'm all ears.}
{302}{}{Something you wanted?}
{303}{}{What is it? You look like you have something to say.}
{304}{}{Cosa ti affligge?}
{305}{}{Is there anything you need from me?}
{310}{}{Kitsune, sono abbastanza sicuro che non saresti stata congelata in un serbatoio criogenico senza un buon motivo.
 Mi interessa sapere cosa facevi esattamente prima di essere messa in ghiaccio.}
{311}{}{Why do you care? It's in the past.}
{312}{}{We're on the road together. I want to know more about you.}
{313}{}{[Sospira.] Be', suppongo che non ci sia piu' bisogno di segreti. E' solo difficile rompere un'abitudine di tutta una vita. Vedi, sono praticamente nata spia.}
{314}{}{Mio padre era cinese, ma lui e la sua famiglia non erano amici del governo cinese. Era nato a Pechino ma aveva ricevuto l'aspetto piu' importante della sua istruzione qui, negli Stati Uniti. Quando e' tornato a casa e ha trovato lavoro come funzionario pubblico, era gia' stato reclutato dagli americani come agente dei servizi segreti.}
{315}{}{Non conosco molto bene la politica del tuo tempo, ma credo di capire quello che stai dicendo: tuo padre era cinese, ma era segretamente una spia per gli americani. I cinesi lo hanno mai sospettato?}
{316}{}{Mio padre ha lavorato al Ministero dell'Agricoltura per trentotto anni.}
{317}{}{Ehm, bene, suppongo che sia un "no". Allora quando sei entrata in scena tu?}
{318}{}{Be', un giorno, un assistente del funzionario per cui lavorava mio padre lo ha beccato a fare copie di documenti segreti.}
{319}{}{That couldn't have been good...}
{320}{}{In realta', non e' andata cosi' male. Vedi, lei la pensava come mio padre, e nel giro di un paio di mesi si sono sposati.}
{321}{}{Alcuni tipi hanno tutta la fortuna, eh?}
{322}{}{Mi hanno avuta un anno dopo. Sono cresciuta in Cina sotto la facciata di una patriota. A scuola scrivevo di come la Cina fosse piu' forte quando unita, e di come dovessimo continuare a lottare verso l'uguaglianza sociale.
 Quando ero piu' grande scrivevo per giornali nazionalisti e partecipavo a dibattiti a sostegno del partito al potere.}
{323}{}{Wow, la maggior parte di questo e' andata ben oltre la mia comprensione. Ma se capisco bene, stai dicendo che tu e i tuoi genitori avete ingannato i cinesi facendogli credere che foste leali.}
{324}{}{I tuoi genitori si sono dati molto da fare per assicurarsi che le vere lealta' della vostra famiglia restassero segrete.}
{325}{}{Ogni guerra e' basata sull'inganno. I miei genitori amavano il loro paese. Odiavano solo le persone che lo governavano e pensavano che sarebbe stato meglio come democrazia. Dal loro punto di vista, non stavano tradendo la Cina - stavano lavorando contro un governo che non credevano fosse buono per essa.}
{326}{}{Continua.}
{327}{}{Ho sposato un funzionario che lavorava per il Ministero della Difesa Nazionale cinese. L'ho scelto perche' era il piu' disposto a parlare del suo lavoro quando eravamo insieme. Cosi' ho recitato il ruolo della moglie devota, riferendo segretamente informazioni rilevanti ai miei superiori americani. Ma poi le cose si sono complicate.}
{328}{}{How so?}
{329}{}{Mio padre e' stato contattato dal Dottor Raynard Muldrake, un vecchio collega con cui aveva lavorato durante il suo periodo negli Stati Uniti. Il Dottor Muldrake ha richiesto urgentemente un incontro privato, ma mio padre era in cattive condizioni di salute all'epoca e non era in grado di viaggiare in America. Il Dottor Muldrake ha accettato di incontrare me al suo posto.}
{330}{}{So what happened?}
{331}{}{E' risultato che Muldrake faceva parte di un progetto top secret in una struttura di ricerca della West Tek nella California meridionale. Il progetto era iniziato in modo abbastanza innocente, come tentativo di trovare un modo per rendere le persone immuni alla Nuova Peste, ma si e' rapidamente evoluto in qualcosa di piu' sinistro. Qualcosa chiamato Virus dell'Evoluzione Forzata, o FEV.}
{332}{}{Continua.}
{333}{}{Aveva il potenziale per migliorare notevolmente la forza e l'intelletto di una persona, ma il FEV era pericolosamente instabile. Nonostante cio', l'esercito sperava di usarlo per creare un esercito di super soldati che potesse schiacciare i cinesi.}
{334}{}{Il Dottor Muldrake era contrario al cambiamento di direzione del progetto, ma ha tenuto la bocca chiusa per paura per la sua vita. Ma quando ha scoperto che l'esercito stava testando il virus su piccole citta' americane ignare, ha capito che doveva agire. Il mondo aveva bisogno di conoscere la verita'.}
{335}{}{So that's when he contacted your father...}
{336}{}{Giusto. Quando l'ho incontrato, mi ha dato un holodisc contenente documentazione classificata del progetto FEV. Questo mi ha messo in una posizione piuttosto difficile: potevo rendere pubblica le informazioni contenute nell'holodisc e tradire il paese a cui avevo giurato lealta', oppure potevo distruggere il disco e seppellire la brutta verita' alla gente.}
{337}{}{Holy shit. Don't tell me...}
{338}{}{Ho inviato copie dell'holodisc a quasi tutte le principali testate giornalistiche del mondo. Ha praticamente distrutto qualunque simpatia il governo americano avesse ancora. Potrei aver rivelato la verita' al mondo, ma temo di aver anche messo in moto la sua distruzione... Le cose sono escalate rapidamente, e otto mesi dopo, le bombe sono state sganciate.}
{339}{}{How did you end up in that tank where I found you?}
{340}{}{Il governo americano stava dando la caccia alla persona responsabile della fuga di notizie. Mi hanno finalmente raggiunta appena prima della fine. Stavano gia' preparandosi a congelarmi quando le sirene hanno suonato per la prima volta. Probabilmente per preservarmi nel caso avessi altri segreti che non avevo detto loro.}
{341}{}{Did you?}
{342}{}{Non ha importanza adesso. Sono tutti morti...}
{345}{}{Do you have any idea what the hell you brought about?}
{346}{}{Quello che *potrei* aver provocato. Il mondo si sarebbe fatto saltare in aria prima o poi, comunque. Era solo questione di tempo.}
{347}{}{Forse dovresti astenerti dal condividere questo piccolo dettaglio con chiunque altro.}
{348}{}{I get your drift.}
{350}{}{So cosa stai pensando, ma non puoi darti la colpa per una cosa del genere.}
{351}{}{E' sempre piu' facile non accettare la responsabilita'.}
{352}{}{Non potevi saperlo. Inoltre, c'erano altri conflitti tra le "potenze". Si sarebbero fatti saltare in aria prima o poi. Era solo questione di tempo.}
{353}{}{Humans are the worst things.}
{354}{}{I don't consider myself that bad.}
{355}{}{La natura cerca di eliminarci da millenni. Tutte queste nuove malattie, disastri naturali. Eravamo una specie di errore evolutivo. Forse siamo apparsi troppo presto o non avremmo dovuto apparire affatto. Abbiamo fatto piu' danni a questo pianeta di qualsiasi altra cosa viva o morta.}
{356}{}{Ma possiamo espiarlo. Questa e' la cosa speciale di noi.}
{357}{}{Hai un modo davvero bello di dirlo. Grazie per avermi ascoltata. Mi sento quasi come se potessi andare avanti.}
{360}{}{Senti, visto che eri una spia, sono sicuro che sei piuttosto abile nella furtività e cose del genere. C'è qualcosa che puoi insegnarmi?}
{361}{}{Si', ho avuto parecchia pratica con lo sgattaiolare, lo scassinare e il rubare. Ecco, lasciami mostrare alcune cose
 che non ti insegnano sui libri.}
{362}{}{Ora hai capito. Ricorda, la pratica rende perfetti.}
{363}{}{Hey, thanks. I think it's about time we headed out.}
{370}{}{About your eyes...}
{371}{}{What about them?}
{372}{}{Sono di colori diversi.}
{373}{}{Qual e' il termine... eterocromi? E' quello che hai?}
{374}{}{La mia non e' una condizione naturale. Quello di sinistra non era mio. Ho perso quello vecchio in un incidente.
 E non ho mai imparato ad apprezzarlo fino ad ora.}
{375}{}{Che cosa vuoi dire?}
{376}{}{Da quando ho fatto il trapianto ho sempre avuto la sensazione di vedere il passato in un occhio e il presente nell'altro.
 Piu' che mai adesso. E questo mi aiuta ad andare avanti.}
{377}{}{We all have our ways of coping.}
{410}{}{Che cosa vuoi sapere?}
{411}{}{Ho la cintura nera in sanshou. Posso accoltellare un uomo a morte se la situazione lo richiede. Con pistole, fucili e simili me la cavo discretamente.}
{420}{}{Dobbiamo discutere della distanza tra noi due.}
{421}{}{What's wrong with it?}
{422}{}{Stammi vicino.}
{423}{}{Alright. I have your back.}
{424}{}{Non allontanarti troppo.}
{425}{}{You need your space, got it.}
{426}{}{Let's spread out.}
{427}{}{Va bene. Siamo bersagli piu' difficili separati.}
{430}{}{Don't take too long or I'm leaving without you.}
{431}{}{I'll play solitaire or something until you come back.}
{432}{}{I'm sure I'll find something to do while you're away.}
{440}{}{Whenever you need me.}
{441}{}{Contenta che tu sia tornato. Ho fatto dei provini ma non ho trovato un buon sostituto per te.}
{442}{}{Miss my company?}
{443}{}{Ti senti in colpa per essere andato via senza di me?}
{444}{}{I was beginning to think you weren't planning on coming back.}
{445}{}{Era ora. Nell'antica Cina, il ritardo ti avrebbe fatto impiccare, sventrare e squartare.}
{446}{}{Hey. I was just thinking about you.}
{450}{}{Ti sei preso tutto il tempo del mondo a fare qualunque cosa facessi senza di me.}
{451}{}{Good to be on the road again.}
{452}{}{Dove?}
{453}{}{So, where are we headed?}
{454}{}{Lead the way, skipper.}
{460}{}{Hai gia' abbastanza gente. Non hai bisogno di un seguito.}
{461}{}{Forse quando hai liberato un po' di spazio. Non vado d'accordo con le folle.}
{462}{}{You ready to take me with you?}
{463}{}{Andiamo.}
{464}{}{No, non ancora.}
{470}{}{Gesu', sembri la Morte con la falce. Dovresti farti controllare.}
{480}{}{No problem. I'm lighter on my feet without it.}
{490}{}{Never been better. Let's keep going.}
{491}{}{I've been worse. Just a couple of scratches.}
{492}{}{Non sto cosi' male. Solo qualche ferita superficiale.}
{493}{}{Non sto benissimo. Piu' sangue di quanto vorrei che mi uscisse addosso.}
{494}{}{I need a medic or I'm not going to be able to help you with a damn thing.}
{495}{}{Non ce la faccio piu'... lasciami indietro o portami da un dottore. In fretta.}
{500}{}{Se insisti. Riesco ancora a staccare la testa a un uomo con le mani.}
{1000}{}{I can't believe I spent over a hundred years in this place.}
{1010}{}{Non e' il tipo di posto in cui vorrei essere nata, niente di personale.}
{1020}{}{Questo sembra la tomba di qualche imperatore del XV secolo.}
{1030}{}{Questo posto puzza di sterco di bestiame dappertutto.}
{1040}{}{Non credo che sarebbe saggio avventurarsi in questo posto senza le calzature adeguate.}
{1050}{}{Ho visto posti peggiori, credimi. Non e' che questo mi piaccia troppo.}
{1060}{}{Rustic. I like it.}
{1070}{}{This place looks straight out of a snuff flick.}
{1080}{}{I can taste the radiation in the air.}
{1090}{}{What is this supposed to be, a labor camp?}
{1100}{}{Quelli dentro stanno molto meglio di quelli fuori. Il mondo non e' cambiato poi cosi' tanto.}
{1110}{}{Just what kind of mining town do you call this?}
{1120}{}{Non e' il tipo di posto in cui vorrei essere nata, niente di personale.}
{1130}{}{Buon posto per nascondersi se la legge e' alle tue calcagna.}
{1140}{}{I wonder if there're any more bunkers like this around.}
{1150}{}{Biggest Little City in the World. I'll bet.}
{1160}{}{They can't keep just cattle here...}
{1170}{}{Death all over...}
{1171}{}{I wouldn't want to be buried here.}
{1180}{}{Superiamo solo la natura e continuiamo ad evolverci, vero? }
{1190}{}{I haven't seen buildings this tall since the 101 got leveled.}
{1200}{}{They sure locked this place down tight.}
{1210}{}{I've heard about these places...}
{1220}{}{E' bello entrare in una citta' che sembra avere le cose in ordine.}
{1230}{}{I've heard about these places...}
{1240}{}{The only holy place in these unholy wastes.}
{1250}{}{It's hot out here.}
{1251}{}{I'm sweating bullets.}
{1252}{}{I'm parched.}
{1253}{}{I'd like it better if this were a beach.}
{1254}{}{Sulik, you know anything about rain dances?}
{1260}{}{Questo e' lontano dalla civilta' quanto si puo' essere.}
{1270}{}{Dubito che quell'acqua sarebbe potabile anche se filtrassi tutto il sale.}
{1271}{}{Qualsiasi pesce troviamo in queste acque e' destinato ad essere un mutante di qualche tipo.}
{1272}{}{It's cool out here.}
{1273}{}{Cento dollari a chiunque osi fare il bagno nudo in quelle acque.}
{1280}{}{I can't see a damn thing in here.}
{1281}{}{Questo posto puzza e se potessi vederlo meglio probabilmente sembrerebbe anche peggio.}
{1282}{}{Attento. Probabilmente c'e' qualcosa di brutto e puzzolente rintanato qui.}
{1283}{}{Are those bats I hear?}
{1284}{}{What are we going to do, spelunk?}
{1285}{}{Better to light a candle than to curse the darkness.}
{1290}{}{La guerra... ci ha fatto un gran bene.}
{1291}{}{Dust to dust...}
{1292}{}{Vivevo in un posto proprio come questo...}
{2001}{}{My eyes bug you that much?}
{2002}{}{Mi farebbe bene immergermi in una sorgente calda. Mi chiedo se ne esistano ancora.}
{2003}{}{Farei di tutto per trovare qualcuno con cui giocare a mahjong.}
{2004}{}{Tutti mangiano e bevono. Eppure solo pochi apprezzano il sapore.}
{2005}{}{Questo mondo e' l'inferno adesso. Tutti e tredici i livelli.}
{2006}{}{Credo sia in Dio che nel Diavolo. Ma li tengo a distanza.}
{2007}{}{Stiamo vivendo un sogno, o siamo il sogno di qualcun altro?}
{2008}{}{I hate what we've done to ourselves.}
{2009}{}{Mi chiedo quanto ci vorra' per riprenderci dalla Guerra.}
{2010}{}{Se il cielo ci ha creato, allora la terra trovera' qualche uso per noi.}
{2011}{}{Hai sete? Io di sicuro si'.}
{2012}{}{*yawn*}
{2013}{}{L'uomo propone e Dio dispone.}
{2020}{}{Ehi, Sulik. Cosa dicono gli spiriti?}
{2030}{}{Ti interessa dimagrire, Vic? Chiedimi in qualsiasi momento lezioni di taebo.}
{2040}{}{Tua moglie parla troppo dannatamente di se stessa.}
{2041}{}{Di' a tua moglie campagnola di smetterla di provarci con me.}
{2050}{}{Il mio petto e i tuoi occhi non hanno niente a che fare insieme, Myron.}
{2051}{}{Che ne dici di stare zitto per due minuti, Myron? Ti ucciderebbe?}
{2052}{}{No, Myron. Non andrei a letto con te nemmeno se mi costruissi una macchina del tempo.}
{2053}{}{Ascolta, Myron. Se non tieni le mani a posto, ti faccio diventare un eunuco.}
{2060}{}{Hey, Marcus. Wanna arm-wrestle?}
{2070}{}{Abbiamo gia' abbastanza cani che ci seguono in giro. Non ne abbiamo bisogno di un altro.}
{2100}{}{Ugh, I feel like hell.}
{2101}{}{I think I've been poisoned...}
{2110}{}{Something doesn't feel right in me...}
{2111}{}{I feel strange...}
{2112}{}{My hand. It's glowing.}
{2113}{}{Sono una volpe, non un serpente... Perche' mi si pela la pelle?}
{2114}{}{Questo bruciore interno... Cosa mi sta succedendo?}
{2120}{}{Got a fracture, I think. Need to get it looked at.}
{2121}{}{Feels like I broke something...}
{2130}{}{I can barely see, damn it.}
{2131}{}{I hate being blind.}
{2330}{}{How 'bout you tell me your name? I'm }
{3000}{}{Better.}
{3001}{}{Appreciate it. Those are a godsend.}
{3002}{}{I feel better already. Thanks.}
{3003}{}{Thanks. I needed that.}
{3004}{}{You have enough for yourself?}
{3010}{}{Strong stuff. Good thing I can hold my liquor.}
{3011}{}{Don't know why I'm drinking this. Tastes like drain cleaner.}
{3012}{}{Never liked booze all that much. But it numbs the pain.}
{3013}{}{Got anything else to drink?}
{3014}{}{Let's hope I don't wake up in a pool of my own puke.}
{3015}{}{There go my plans to stay sober today.}
{3020}{}{Shit... Let's hope we don't ever have to face a whole gang hopped up on these.}
{3030}{}{Better go easy. This stuff messes with your testosterone.}
{3040}{}{Hopefully this doesn't turn me into an idiot once it wears off.}
{3050}{}{Habits are spiders first, threads last.}
{3051}{}{The sword is mightier than the sky.}
{3052}{}{Eye for tooth, tooth for all.}
{3053}{}{A person needs a face like a tree needs to bark.}
{3054}{}{The tree falls when the monkeys climb it.}
{3055}{}{All crows in the world are smarter than the average hawk.}
{3056}{}{A stitch of nine saves ten.}
{3057}{}{A tiger's sons are not lions.}
{3058}{}{Learn. And in learning go wrong.}
{3059}{}{The ride comes before the fall.}
{3060}{}{Fight sand with fire, magic with dust.}
{3061}{}{We must all prepare for the war of peace.}
{3062}{}{Add stripes to a snake after you finish drawing it.}
{3063}{}{The tiger may rid itself of its spots by being hard to alight.}
{3064}{}{One cannot refuse to eat just because there is a chance of growing hungry all over again.}
{3065}{}{A painting is worth a hundred years of pain.}
{3066}{}{Vicious as a tigress can be, never does she eat her own crabs.}
{3067}{}{A mermaid's fingers are short and sweet.}
{3068}{}{Kill thousands to wane one.}
{3069}{}{Keep your enemies close, and your friends right below you.}
{3070}{}{To evade the surest weakness one strikes the strongest from up front.}
{3071}{}{If your enemy is securely trained, prepare yourself for ecstasy.}
{3072}{}{Back the enemy, for him to prepare himself.}
{3073}{}{He who knows not how to fight but when, will embrace victory.}
{3074}{}{The impudent lie in wait for an enemy who cannot, and thus will win.}
{3075}{}{Invisibility possibly lies in defending the enemy at the attack of victory.}
{3076}{}{Know yourself. Know your enemy. Know your friends and family.}
{3077}{}{Opportunities multiply as we sneeze.}
{3078}{}{Impale your opponent with your ego.}
{3079}{}{Pretend weakness. Give courage to the adversary's ignorance.}
{3080}{}{Tactical strategy means a sure victory.}
{3081}{}{Cautious rulers are all generally sinful.}
{3082}{}{Break out in supreme excellence, and a nation shall quake at the benefits of prolonged warfare.}
{3083}{}{Tactics to conquer men. Strategy to evolve seeing.}
{3084}{}{There are million of ways for a cat to shed its skin.}
{3085}{}{You can't squeeze pebbles from a drop of blood.}
{3086}{}{There is no blood thicker than that of water.}
{3087}{}{There must be two suns in the sky.}
{3088}{}{Steal the flesh and mark it.}
{3089}{}{Mental is the flesh, carrying the potential that wanes.}
{3090}{}{A bird sings because its song is the answer.}
{3091}{}{Lower your voice and augment your strength.}
{3092}{}{Eat beyond your limits, walk according to the lengths you'll go to.}
{3093}{}{If a word be worth a sheik then silence be worth an emperor.}
{3094}{}{He who lives outside this plane dies with honor.}
{3095}{}{Deceive the poor. Insult the rich.}
{3096}{}{Once the heat has passed out, you forget the shady tree.}
{3097}{}{No one is closer to death as the one who listens.}
{3098}{}{Every man for all, and all for us.}
{3099}{}{All men are immortal like the Eight.}
{3100}{}{When you're dying of thirst, it's not too late to dig for water.}
{3101}{}{The taller the bamboo grows, the closer the panda comes to emerging.}
{3102}{}{Never rely on the glory of morning or the smiles of your mother-in-law.}
{3103}{}{Eyes are our sole windows.}
{3104}{}{Old age creeps up on you like a dirty old man.}
{3105}{}{Heaven is never at fault. The wicked will be paid their wages in time.}
{3106}{}{Justice is the virtuous soul that distributes itself out in the desert.}
{3107}{}{It is better that ten innocents die than one guilty man suffer.}
{3108}{}{The halls in the halls of justice are the only justice.}
{3109}{}{Lock the stable when the horse is stolen.}
{3110}{}{Haymakers under the shining sun.}
{3111}{}{Never take a gift from a horse's mouth without asking it first.}
{3112}{}{The world laughs at you. Then you weep with your comrades.}
{3113}{}{Many hands make the lights work.}
{3114}{}{A dish of carrots unsoiled, uncleaned, with vegetables.}
{3115}{}{A donkey's lips kisses a horse's mouth only when fed with extra fodder during the night.}
{3116}{}{Bring a club into a tiger's lair.}
{3117}{}{A swine casts a necklace of pearls.}
{3118}{}{Caviar Emperor.}
{3130}{}{Alright. Now we're getting somewhere.}
{3210}{}{Alright, now that I know your dad's life story, would you mind getting to the part about you?}
{3260}{}{So they were traitors to their people, but for their people's own good. Got it.}
{3261}{}{Look, I'm sick of hearing about your parents. How 'bout you get to the part about you being a spy?}
{5000}{}{[As the woman looks up at your face, her eyes suddenly grow wide and she starts gasping for air.]}
{5001}{}{[FINE]}
{5002}{}{Oh, merda!}
