{100}{}{Vedi un ologramma.}
{101}{}{Vedi il Direttore delle Operazioni.}
{102}{}{Ologramma 12001. Dirige le operazioni all'interno dell'EPA.}
{200}{}{[Questo ologramma dall'aria viscida ti guarda con un sorriso nervoso.] Salve, benvenuto all'EPA. Avrai notato che stiamo avendo qualche piccolo problema, ma ci penseremo quando sara' il momento.}
{201}{}{Uh, okay. Chi sei?}
{210}{}{Sono il Direttore delle Operazioni dell'EPA.}
{211}{}{Oh, giusto. [Ti gratti la testa] Cosa significa esattamente?}
{220}{}{[Ride nervosamente.] Beh, coordino le cose. Do il via ai processi. Ora tocca a te. Mi piace tirare fuori il meglio dalle persone. Qui all'EPA, e' questo che conta. Onesta'. Integrita'. Grazie, apprezziamo la tua opinione.}
{221}{}{Di che cosa diavolo stai parlando?}
{230}{}{Ti assicuro che stiamo lavorando diligentemente per risolvere tutti i problemi. Abbiamo avuto un po' di ridimensionamento, ma le cose stanno migliorando. Sono fiducioso che tutte le quote verranno raggiunte a tempo debito.}
{231}{}{Quali quote? Non ha senso quello che dici. Fai davvero qualcosa qui? Puoi aiutarmi o no?}
{240}{}{Dipende tutto dal tuo punto di vista. Le mie mani sono legate su questa questione, ma sarei felice di aiutarti se potessi.}
{241}{}{Scordatelo. Addio.}
{242}{}{Mi dispiace di non poter essere piu' d'aiuto.}
{243}{}{Grazie per il tuo tempo.}
{244}{}{Non voglio commentare.}
{245}{}{Nessun commento.}
{246}{}{Lo farei, ma al momento ho qualche problema con l'autorita'.}
{247}{}{Affronteremo la questione quando sara' il momento.}
{248}{}{Questa riunione serve per discutere, non per agire.}
{249}{}{Sono fiducioso che l'EPA sia sulla strada del successo.}
{250}{}{La rilevanza di questa questione e' discutibile.}
{251}{}{Non siamo precipitosi, potremmo agire troppo in fretta.}
{252}{}{Sembra adeguato.}
{253}{}{Capisco la tua preoccupazione.}
