{100}{}{Vedi un robot Mr. Handy.}
{101}{}{Vedi un robot Mr. Handy profondamente depresso.}
{102}{}{Questo robot Mr. Handy sembra essere molto depresso per qualche motivo.}
{200}{}{Oh, povero me!}
{201}{}{Stufo...}
{202}{}{Voglio morire adesso...}
{203}{}{Qualcuno mi uccida, per favore...}
{204}{}{Sono andati via tutti...}
{205}{}{Perche' dovrei farlo?}
{206}{}{Noioso...}
{207}{}{...SINGH...}
{208}{}{La vita... non parlarmi della vita.}
{209}{}{Penso che dovresti sapere che mi sento molto depresso.}
{210}{}{Perdonami per respirare, cosa che non faccio comunque quindi non so nemmeno perche' lo dica, oh Dio, sono cosi' depresso.}
{500}{}{Si', spingimi giu' da una scogliera.}
{501}{}{***bzzt Smettila! *** bzzt}
