{100}{}{Vedi un grande computer.}
{101}{}{Vedi Mr. Chemmie!}
{102}{}{Un grande computer per la produzione di farmaci.}
{200}{}{Ciao utente! Sono il farmacista del futuro, Mr. Chemmie! Come posso aiutarti?!}
{201}{}{Che cosa fai?}
{210}{}{Faccio droghe! Tutti i tipi di droghe! Quando la vita ti butta giu', Mr. Chemmie e' qui per tirarti su! Come funziona Mr. Chemmie?! E' semplice! Ti servono solo un po' di conoscenze scientifiche e gli ingredienti giusti, poi lascia fare tutto a me! Dai! Provami! E bambini, ricordate di chiedere il permesso a mamma o papa' prima di giocare con Mr. Chemmie!}
{211}{}{D'accordo, ci proverò.}
{212}{}{Magari piu' tardi.}
{220}{}{Bene! Produciamo farmaci! Cosa vuoi creare?!}
{221}{}{Stimpak}
{222}{}{Super Stimpak}
{223}{}{Veleno}
{224}{}{Antidoto al veleno}
{225}{}{Kit di Pronto Soccorso}
{226}{}{Borsa del Dottore}
{227}{}{Buffout}
{228}{}{Mentat}
{229}{}{Psichiatra}
{230}{}{Ottima scelta! Per creare uno Stimpak, dammi: un Fiore di Broc, una Radice di Xander e un'Ago Ipodermico Vuoto! Gnam-gnam!}
{231}{}{Produci uno Stimpak.}
{232}{}{Non li ho con me al momento.}
{233}{}{Torna al menu.}
{240}{}{Ottima scelta! Per creare un Super Stimpak, dammi: uno Stimpak normale, un Frutto e una Nuka-Cola! Gnam-gnam!}
{241}{}{Produci Super Stimpak}
{250}{}{Ottima scelta! Per creare del Psycho, dammi: una scatola di Mentats, un Buffout, un Frutto e uno Stimpak! Gnam-gnam!}
{251}{}{Produci un Psycho.}
{260}{}{Ottima scelta! Per creare dei Mentats, dammi: un Kit di Primo Soccorso, un Frutto e una bottiglia di Alcol! Gnam-gnam!}
{262}{}{Produci dei Mentats.}
{263}{}{Esci}
{270}{}{Ottima scelta! Per creare una Borsa del Medico, dammi: uno Stimpak, un Kit di Primo Soccorso, un Ago Ipodermico Vuoto e un Antidoto al Veleno! Gnam-gnam!}
{272}{}{Produci Borsa del dottore}
{280}{}{Ottima scelta! Per creare un Kit di Primo Soccorso, dammi: uno Stimpak, un Ago Ipodermico Vuoto, un Antidoto al Veleno e un RadAway! Gnam-gnam!}
{282}{}{Produci Kit di pronto soccorso}
{290}{}{Ottima scelta! Per creare del Veleno, dammi: un Ago Ipodermico Vuoto, una Coda di Scorpione e una Nuka-Cola! Gnam-gnam!}
{292}{}{Produci del veleno.}
{300}{}{Ottima scelta! Per creare del Buffout, dammi: un Kit di Primo Soccorso, una bottiglia di Birra e una Nuka-Cola! Gnam-gnam!}
{302}{}{Produci Buffout}
{310}{}{Ottima scelta! Per creare del Rad-X, dammi: un Kit di Primo Soccorso e una Nuka-Cola! Gnam-gnam!}
{312}{}{Prepara un Rad-X.}
{320}{}{Ottima scelta! Per creare del RadAway, dammi: una Nuka-Cola, un Ago Ipodermico Vuoto e uno Stimpak! Gnam-gnam!}
{322}{}{Produci RadAway.}
{330}{}{Ottima scelta! Per creare un Antidoto al Veleno, dammi: una Coda di Scorpione e una bottiglia di Alcol! Gnam-gnam!}
{331}{}{Make Poison Antidote.}
{340}{}{Oh cielo! Una richiesta speciale! Che tipo di droga speciale vuoi che Mr. Chemmie crei per te oggi?!}
{341}{}{Marijuana.}
{342}{}{Composti medici}
{343}{}{Il mio amico Cassidy ha un problema al cuore. Puoi creare qualcosa che lo aiuti?}
{344}{}{Inibitori della Sindrome da Rigetto Ambientale}
{350}{}{E' il tuo giorno fortunato! Ho abbastanza sostanze nei miei serbatoi per crearle! Vuoi che Mr. Chemmie le prepari per te?!}
{351}{}{Crea}
{352}{}{Torna al Menu Principale}
{360}{}{Oh-oh! Mi dispiace, ma non ho piu' le sostanze necessarie per crearle!}
{370}{}{Selezione completata! E' stato divertente! Ritira l'oggetto dalla macchina! Grazie per aver usato Mr. Chemmie! Facciamo altre droghe insieme un'altra volta!}
{371}{}{Altre opzioni}
{375}{}{Mr. Chemmie adora aiutare! Posso creare una sostanza chiamata nitroglicerina, che controlla un battito cardiaco irregolare e previene gli attacchi di cuore!}
{380}{}{Rad-X}
{381}{}{RadAway}
{382}{}{Qualcosa di speciale}
{383}{}{Niente}
{390}{}{E' il tuo giorno fortunato! Ho giusto abbastanza sostanze nei miei serbatoi per creare un lotto di ERSI! Vuoi che Mr. Chemmie li prepari per te?!}
{391}{}{Crea}
{392}{}{Esci.}
