{100}{}{Vedi un ologramma.}
{101}{}{You see the Director of Public Relations.}
{102}{}{Ologramma 40011. E' responsabile dei tour e dei comunicati stampa dell'EPA.}
{200}{}{[Questo attraente ologramma femminile ti accoglie con un sorriso amichevole.] Salve visitatore, e benvenuto all'EPA. Come posso aiutarti? Il pranzo verra' servito in mensa a meta' giornata per tutti i dipendenti.}
{201}{}{What? Oh nevermind. Who are you?}
{202}{}{I need to be going. Bye.}
{210}{}{Io? Sono l'Ologramma 40011, la Direttrice delle Relazioni Pubbliche. Organizzo viaggi, tour e altre attivita' e mi assicuro che tutto funzioni senza problemi per il pubblico ogni giorno. Il tour del museo dell'EPA iniziera' a breve. Per favore, preparate i vostri pass.}
{211}{}{That sounds like a riveting job. Goodbye.}
{212}{}{So maybe you could help me with something?}
{220}{}{Certo. Mi farebbe piacere aiutarti. Come posso assisterti? I volantini del tour si trovano nell'ufficio principale e nelle cassette postali in tutta l'EPA.}
{221}{}{Ci sono alcune porte nel complesso che non posso aprire senza pronunciare una password. Mi piacerebbe davvero oltrepassarle e vedere di piu' della vostra struttura. Non e' che per caso conosci la password?}
{230}{}{Certo che conosco la password, ma purtroppo non posso condividerla con te. Capisco il tuo entusiasmo nel voler vedere tutto cio' che questa grande struttura ha da offrire, ma ci sono regole da seguire per la tua sicurezza. Ricordate tutti, offriamo visite guidate del complesso a orari prestabiliti.}
{231}{}{Oh, non devi preoccuparti per la mia sicurezza, sono il Prescelto. E poi, quand'e' stata l'ultima volta che avete avuto un *vero* visitatore? Vuoi davvero lasciarmi deluso?}
{232}{}{Right then. Goodbye}
{240}{}{Certo che no. Ma se ti dessi la password, potrei mettere in pericolo te e anche il complesso. Bambini, per favore non prendete in giro gli ologrammi.}
{241}{}{Come potrebbe mettere in pericolo il complesso? Mi dispiace dirtelo, signora, ma questo posto e' gia' andato all'inferno e ritorno. Qui non c'e' altro che sostanze pericolose e robot rotti. Onestamente, non vedo come potrei peggiorare la situazione.}
{242}{}{Oh forget it then.}
{250}{}{Io... non lo so. Andrei contro il protocollo. Ma... forse se potessi aiutarmi con qualcosa. Visitatori, per favore notate che il livello blu e' limitato per ragioni molto poco interessanti. Non c'e' alcun motivo di esserne curiosi.}
{251}{}{Sure, I could assist you. Just tell me what you need.}
{260}{}{Ah si', ora qui sembra molto meglio, grazie. La password e' ABRE. Basta parlare chiaramente alla porta e si
 aprira'. Ora, se tutti quanti volessero per favore...}
{261}{}{YES, we've heard you already. Thanks for the code. Goodbye.}
{270}{}{Salve di nuovo. Di cosa hai bisogno? Il complesso dell'EPA restera' chiuso per il prossimo futuro a causa della mancanza di personale.}
{271}{}{Now that I have more time, could you tell me what you do here?}
{272}{}{Lasciamo stare.}
{280}{}{Bentornato, visitatore. Al momento non c'e' alcun tour, ma se vuoi aspettare che arrivino abbastanza visitatori, saro' felice di organizzarne uno.}
{281}{}{I don't want to go on a tour, thanks. Goodbye.}
{282}{}{I wonder if you could do something for me?}
{290}{}{Salve. Sono un po' impegnata al momento a progettare un nuovo programma di tour per la prossima stagione. Potresti tornare piu' tardi?}
{291}{}{Lo farei, ma ho troppa fretta. Vedi, ho *davvero* bisogno della password per quelle porte. Me la daresti, per favore?}
{300}{}{Grazie ancora per il tuo aiuto, e per favore usa responsabilmente la password che ti ho dato. Ricorda, e' il nostro piccolo segreto. Grazie per aver visitato l'EPA, spero tu abbia una piacevole esperienza.}
{301}{}{Grazie. Ciao.}
{302}{}{Come visit us again sometime.}
{303}{}{Non dimenticare di visitare il banco dei souvenir dell'EPA.}
{310}{}{Pensi di poter sistemare l'illuminazione? Non e' appropriato per me condurre tour in un complesso cosi' poco illuminato.
 Se potessi rendere questo posto piu' luminoso, ti daro' la password. Per favore, ricordate di lavarvi accuratamente le mani
 dopo aver visitato il nostro zoo tattile.}
{311}{}{Alright. I'll see what I can do.}
{312}{}{Nevermind. I'm not interested.}
{320}{}{Il complesso sembra ancora piuttosto cupo. Sistemarai le luci, vero? Ricordate visitatori, tutte le liberatorie devono essere firmate prima della fine del tour.}
{321}{}{Don't worry. I'm working on it.}
{322}{}{I'll get around to it.}
{330}{}{Avremmo piu' visitatori se i terreni fossero puliti.}
{331}{}{How am I supposed to conduct tours without proper lighting?}
{332}{}{Quelle piante stanno uccidendo tutti i potenziali turisti.}
{333}{}{Tutti quei robot rotti sono *davvero* un brutto spettacolo.}
{334}{}{10031, sei stato inutile per decenni.}
{335}{}{Tutto quello che dico e' che questo posto deve essere piu' presentabile.}
{336}{}{Destroying the complex is not the answer.}
