{100}{}{Vedi un ologramma.}
{101}{}{Vedi il Direttore della Sicurezza.}
{102}{}{Ologramma 10001. Supervisiona la sicurezza dell'EPA.}
{200}{}{Alt! Non provare ad avvicinarti. Identificati, intruso.}
{201}{}{Sono il Prescelto di Arroyo. Sto esplorando l'EPA.}
{202}{}{Non sono un intruso e ora devo andare.}
{203}{}{Sono }
{204}{}{, e non sto cercando di intrufolarmi, sto solo esplorando.}
{210}{}{Esplorando!? Esplorando... LA MIA... EPA!? Come osi avere la faccia tosta di entrare qui e gironzolare come niente fosse! Vollidiot! Mi verrebbe voglia di arrestarti e buttarti nello zoo tattile -- dare a quei mostri un vero banchetto!}
{211}{}{No, aspetta! Non ti sto facendo alcun male! Lascia che spieghi...}
{220}{}{Non andrai da nessuna parte, Pisskopf. Nessuno entra nella MIA EPA senza spiegarsi. Come faccio a sapere che non sei una spia cinese?}
{221}{}{Immagino che tu non possa saperlo. Ma se mi dai la possibilita' di spiegarmi, sono sicuro che possiamo sistemare tutto questo casino.}
{222}{}{E se lo fossi? Che importa? La tua preziosa EPA non e' piu' rilevante. E' solo un'altra reliquia in decomposizione di un'epoca perduta.}
{230}{}{Avanti allora, Schwachkopf, spiegati. Ma fallo bene, o faro' picchiare i robot e ti faro' trascinare alla sedia elettrica!}
{231}{}{Va bene. Prima di tutto, non sono una spia cinese -- sono quello che potresti chiamare un tribale. Sono stato scelto per intraprendere una missione pericolosa per salvare la mia tribu' dalla distruzione. Sono entrato in questo complesso solo nella speranza di recuperare qualcosa che potesse aiutarmi nella mia missione.}
{232}{}{Vaffanculo. Sul serio, sei un *ologramma*. La cosa peggiore che puoi fare e' cercare di urlarmi fino alla morte, e ci stai provando alla grande. Quanto a quei rottami che chiami robot, forse sarei piu' intimorito se ne vedessi uno che funziona davvero.}
{240}{}{Saccheggiare! Tu, Pissnelke! Come osi screditare il nome dell'EPA in questo modo! Nessuno rimuove nemmeno un foglio di carta da questo edificio senza il mio permesso! Tuttavia, arrivare cosi' lontano nell'EPA richiede una certa abilita'... forse potrei trovare un uso per te dopotutto. }
{241}{}{Eh?}
{242}{}{No, credo che rovistero' ancora un po' e poi andro'. Ciao!}
{250}{}{Insolenza! Che insolenza da un Blödes Arschloch! Quando iniziai il mio addestramento, l'insolenza veniva punita. E puniti lo eravamo! Ricorda le mie parole, scheisskopf, quella tua lingua biforcuta un giorno ti fara' morire.}
{251}{}{Forse si', forse no. E se quel giorno dovesse arrivare, me ne occupero' allora. Una cosa e' certa: non verra' da te. Non sei nessuno. Non hai piu' nulla da comandare, ed e' per questo che copri la tua tristezza con la rabbia. Da quanto tempo i robot non rispondono piu' ai tuoi comandi?}
{260}{}{Beh, come avrai gia' intuito, i robot non funzionano piu' qui all'EPA. Le console non registrano piu' i miei comandi vocali e non ho un corpo per attivarle. Io... non posso piu' mettere in sicurezza nulla. Potresti riparare il computer di controllo dei robot per me? Ho bisogno di poter comandare i robot per... beh, per certe cose.}
{261}{}{Perche' no? Vedro' cosa posso fare.}
{262}{}{No, non ho tempo. Ciao.}
{270}{}{Fick dich du verdammter Arschficker! Dovrei... dovrei... [Sospira.] Hai ragione. I robot non capiscono piu' quello che dico. Stanno li' immobili come dannati barboni! I computer hanno smesso di funzionare e, essendo un ologramma, non posso toccare le tastiere. Come dico da anni, questo posto va raso al suolo e ricostruito. Forse un giorno avro' il potere di farlo.}
{271}{}{Forse potrei aiutarti in qualche modo? Me la cavo abbastanza bene con i computer.}
{280}{}{Grazie. Se riesci a riparare il computer di controllo dei robot, ti concedero' pieno accesso all'ala di sicurezza del livello rosso. Potrai prendere quello che vuoi dai depositi. Temo che ormai non ci servano piu' comunque.}
{281}{}{Grazie. Ti faro' sapere quando avro' finito.}
{290}{}{Non ho altro da dirti.}
{291}{}{Bene.}
{300}{}{Hai gia' completato il compito? *Gli occhi brillano in attesa*}
{301}{}{No, non ancora. Ci sto ancora lavorando.}
{310}{}{I computer sono di nuovo online?}
{311}{}{Si'. Li ho riparati per te. Ora puoi comandare di nuovo i robot.}
{320}{}{Eccellente! Brillante! Ora posso schiacciare quegli sciocchi! L'EPA sara' purificata ancora una volta! Bene, ora ho qualcosa per te. [Parlando ai robot] Muovete il vostro culo di metallo e venite a dare a questo civile una ricompensa per aver servito questa grande nazione!
 [Un robot si avvicina e ti porge una keycard. Quando la prendi, lo vedi allontanarsi dalla stanza. In qualche modo hai l'impressione che questi robot sarebbero stati piu' felici se li avessi lasciati inattivi.] Ora vai. Sei congedato.}
{321}{}{Grazie.}
{322}{}{Congedato? Cosa sono, una guardia? A dopo, vecchio.}
{330}{}{Lasciami in pace!}
{331}{}{Non voglio piu' avere a che fare con te.}
{332}{}{FALLO DA SOLO!!}
{333}{}{Adesso sono impegnato.}
{334}{}{Torna piu' tardi.}
{335}{}{Non vedi che sono in riunione?}
{336}{}{Dobbiamo distruggere questo posto immediatamente!}
{337}{}{E' assurdo!}
{338}{}{Mai!}
{339}{}{Solo distruggendo il vecchio puo' rinascere il nuovo.}
{340}{}{Tutti d'accordo?}
{341}{}{I robot devono essere riattivati!}
{342}{}{Warmduscher! Tutti quanti!}
{343}{}{Le nostre difese armate hanno disperatamente bisogno di munizioni!}
{344}{}{Se fossi io al comando, qui le cose si farebbero davvero!}
{345}{}{Stai zitto!}
{400}{}{Arrestarmi? Sei un ologramma. Non puoi nemmeno toccarmi.}
{401}{}{Vedo che ho a che fare con un dannato Klugscheisser! Pensi che non possa pestare un Warmduscher come te? Beh, forse non posso, ma e' per questo che ci sono quei dannati robot! Ora sto perdendo la pazienza molto in fretta. Faresti meglio a spiegarti. Come faccio a sapere che non sei una spia cinese?}
{410}{}{Sei tu quello che ha rimesso online il computer di controllo dei robot?}
{411}{}{Proprio cosi'.}
{412}{}{Uh... forse.}
{413}{}{No. Non sono stato io.}
{420}{}{Quatsch! Sei l'unico essere in carne e ossa qui intorno, quindi so bene che sei stato tu.}
{421}{}{D'accordo, va bene, sono stato io.}
