{100}{}{Vedi un ologramma.}
{101}{}{Vedi il Direttore delle Pubbliche Relazioni.}
{102}{}{Ologramma 40011. E' responsabile dei tour e dei comunicati stampa dell'EPA.}
{200}{}{[Questo attraente ologramma femminile ti accoglie con un sorriso amichevole.] Salve visitatore, e benvenuto all'EPA. Come posso aiutarti? Il pranzo verra' servito in mensa a meta' giornata per tutti i dipendenti.}
{201}{}{Cosa? Oh, lascia stare. Chi sei?}
{202}{}{Devo andare. Ciao.}
{210}{}{Io? Sono l'Ologramma 40011, la Direttrice delle Relazioni Pubbliche. Organizzo viaggi, tour e altre attivita' e mi assicuro che tutto funzioni senza problemi per il pubblico ogni giorno. Il tour del museo dell'EPA iniziera' a breve. Per favore, preparate i vostri pass.}
{211}{}{Sembra un lavoro emozionante. Addio.}
{212}{}{Forse potresti aiutarmi con qualcosa?}
{220}{}{Certo. Mi farebbe piacere aiutarti. Come posso assisterti? I volantini del tour si trovano nell'ufficio principale e nelle cassette postali in tutta l'EPA.}
{221}{}{Ci sono alcune porte nel complesso che non posso aprire senza pronunciare una password. Mi piacerebbe davvero oltrepassarle e vedere di piu' della vostra struttura. Non e' che per caso conosci la password?}
{230}{}{Certo che conosco la password, ma purtroppo non posso condividerla con te. Capisco il tuo entusiasmo nel voler vedere tutto cio' che questa grande struttura ha da offrire, ma ci sono regole da seguire per la tua sicurezza. Ricordate tutti, offriamo visite guidate del complesso a orari prestabiliti.}
{231}{}{Oh, non devi preoccuparti per la mia sicurezza, sono il Prescelto. E poi, quand'e' stata l'ultima volta che avete avuto un *vero* visitatore? Vuoi davvero lasciarmi deluso?}
{232}{}{Bene allora. Addio}
{240}{}{Certo che no. Ma se ti dessi la password, potrei mettere in pericolo te e anche il complesso. Bambini, per favore non prendete in giro gli ologrammi.}
{241}{}{Come potrebbe mettere in pericolo il complesso? Mi dispiace dirtelo, signora, ma questo posto e' gia' andato all'inferno e ritorno. Qui non c'e' altro che sostanze pericolose e robot rotti. Onestamente, non vedo come potrei peggiorare la situazione.}
{242}{}{Allora lascia perdere.}
{250}{}{Io... non lo so. Andrei contro il protocollo. Ma... forse se potessi aiutarmi con qualcosa. Visitatori, per favore notate che il livello blu e' limitato per ragioni molto poco interessanti. Non c'e' alcun motivo di esserne curiosi.}
{251}{}{Certo, posso aiutarti. Dimmi di cosa hai bisogno.}
{260}{}{Ah si', ora qui sembra molto meglio, grazie. La password e' ABRE. Basta parlare chiaramente alla porta e si
 aprira'. Ora, se tutti quanti volessero per favore...}
{261}{}{Sì, ti abbiamo già sentito. Grazie per il codice. Addio.}
{270}{}{Salve di nuovo. Di cosa hai bisogno? Il complesso dell'EPA restera' chiuso per il prossimo futuro a causa della mancanza di personale.}
{271}{}{Ora che ho più tempo, puoi dirmi cosa fai qui?}
{272}{}{Lasciamo stare.}
{280}{}{Bentornato, visitatore. Al momento non c'e' alcun tour, ma se vuoi aspettare che arrivino abbastanza visitatori, saro' felice di organizzarne uno.}
{281}{}{Non voglio fare un giro, grazie. Addio.}
{282}{}{Mi chiedo se potresti fare qualcosa per me.}
{290}{}{Salve. Sono un po' impegnata al momento a progettare un nuovo programma di tour per la prossima stagione. Potresti tornare piu' tardi?}
{291}{}{Lo farei, ma ho troppa fretta. Vedi, ho *davvero* bisogno della password per quelle porte. Me la daresti, per favore?}
{300}{}{Grazie ancora per il tuo aiuto, e per favore usa responsabilmente la password che ti ho dato. Ricorda, e' il nostro piccolo segreto. Grazie per aver visitato l'EPA, spero tu abbia una piacevole esperienza.}
{301}{}{Grazie. Ciao.}
{302}{}{Vieni a trovarci di nuovo, qualche volta.}
{303}{}{Non dimenticare di visitare il banco dei souvenir dell'EPA.}
{310}{}{Pensi di poter sistemare l'illuminazione? Non e' appropriato per me condurre tour in un complesso cosi' poco illuminato.
 Se potessi rendere questo posto piu' luminoso, ti daro' la password. Per favore, ricordate di lavarvi accuratamente le mani
 dopo aver visitato il nostro zoo tattile.}
{311}{}{D'accordo. Vedrò cosa posso fare.}
{312}{}{Lascia stare. Non mi interessa.}
{320}{}{Il complesso sembra ancora piuttosto cupo. Sistemarai le luci, vero? Ricordate visitatori, tutte le liberatorie devono essere firmate prima della fine del tour.}
{321}{}{Non preoccuparti. Ci sto lavorando.}
{322}{}{Me ne occuperò.}
{330}{}{Avremmo piu' visitatori se i terreni fossero puliti.}
{331}{}{Come dovrei fare le visite senza un'illuminazione adeguata?}
{332}{}{Quelle piante stanno uccidendo tutti i potenziali turisti.}
{333}{}{Tutti quei robot rotti sono *davvero* un brutto spettacolo.}
{334}{}{10031, sei stato inutile per decenni.}
{335}{}{Tutto quello che dico e' che questo posto deve essere piu' presentabile.}
{336}{}{Distruggere il complesso non è la soluzione.}
