{100}{}{Vedi un tostapane color argento opaco appoggiato su una scrivania.}
{101}{}{You see The Brave Little Toaster.}
{102}{}{BLT, il tuo allegro, anche se leggermente fastidioso, compagno di colazione.}
{200}{}{Howdy Doodley-Do! Sono il Piccolo Tostapane Coraggioso, il tuo allegro compagno di colazione. Ma puoi chiamarmi BLT. Allora, qualcuno vuole del toast?}
{201}{}{No thanks, but I do want some information.}
{202}{}{Not now, I need to be going.}
{210}{}{Nessun problema! Sono un asso in meccanica quantistica, biologia submolecolare e sigle di serie TV. Chiedimi qualsiasi cosa. Ma prima, posso farti una domanda?}
{211}{}{I guess so. What can I do for you?}
{220}{}{Are you sure you won't have some toast?}
{221}{}{NO! Non voglio toast. Niente muffin, niente dolcetti. Niente panini, baps, baguette o bagel. Niente croissant, niente crumpet, niente pancake, niente focaccine di patate e soprattutto niente maledetti flapjack!!!}
{230}{}{Ah! Allora sei un tipo da waffle!}
{231}{}{Oh, I've had enough of this.}
{232}{}{[Ti dai una manata in fronte dalla frustrazione.] Devo andare. Io... devo solo essere da qualche parte. Ovunque, purche' non qui.}
{240}{}{No, aspetta. Mi dispiace. Non sono solo un elettrodomestico ossessionato dal toast. Cosa posso fare per te?}
{241}{}{I just need some information about this place. What can you tell me about it?}
{250}{}{Posso dirti una cosa: questo e' un posto terribile per qualcuno con la mia esperienza nel fare toast. Sapevi che e'
 passato piu' di un secolo dall'ultima volta che ho avuto il piacere di preparare toast per qualcuno? Sei il primo consumatore
 di toast a passare di qui dalla guerra e, ecco la parte migliore: anche se tu chiedessi del toast, non sono nemmeno sicuro
 di essere in grado di farlo. Vedi, mi sento un po' fuori forma dentro. E' piuttosto imbarazzante, davvero.}
{251}{}{That's, uh, quite tragic. So, why are you here?}
{252}{}{Capisco. Grazie delle informazioni.}
{260}{}{Penso che avesse fatto arrivare una partita di maschere antigas prima dell'incidente. Alcuni dicevano persino che fossero stati i suoi errori a causare il problema.}
{261}{}{So, why are you here?}
{262}{}{Grazie delle informazioni.}
{270}{}{Per rendere le tue mattine il piu' allegre possibile, naturalmente! Dimmi, dopo tutto questo parlare non e' che ti sia venuta
 un po' di fame per del toast, vero?}
{271}{}{Credevo avessimo superato questa cosa!! Non ho fame e non ne avro' mai. Allora, perche' sei davvero qui?}
{280}{}{Va bene, non c'e' bisogno di urlare. Arrabbiarsi non e' mai un buon modo per iniziare la giornata. Sono stato creato come
 compagno per la colazione, ma posso essere usato anche per pranzo e cena. Non c'e' un momento della giornata in cui un po' di toast
 farebbe male. Se ti stai chiedendo perche' sono qui seduto con un filo che mi penzola di lato, beh, sembra che Mr. Handy non sia
 sempre all'altezza del suo nome -- il tizio ha iniziato a rompersi proprio nel mezzo del mio controllo di manutenzione annuale.
 Ovviamente e' scappato verso una baia di manutenzione e mi ha lasciato cosi'.}
{281}{}{Capisco. Beh, grazie di tutto.}
{290}{}{Nessun problema. Passa di nuovo, magari allora avrai fame.}
{291}{}{I doubt it. Bye.}
{300}{}{Sapevo che saresti tornato. Tornano sempre. Allora, vuoi del toast adesso?}
{301}{}{Sapevo che saresti tornato. Tornano sempre. E ora che sono di nuovo completamente funzionante, posso fare toast meglio che mai. Allora, vuoi del toast adesso?}
{302}{}{Not right now. I need to ask you something.}
{303}{}{Nope. I must be going.}
{310}{}{Sure, what would you like to know? I hope it's about toast.}
{311}{}{Cos'e' questo posto?}
{312}{}{Lasciamo perdere. Ci vediamo.}
{350}{}{Ehi, mi hai riparato! Sapevo che Mr. Handy aveva lasciato il lavoro a meta'. Ora mi sento meglio che mai! Grazie.}
{351}{}{Sure, it's what I do. See you later.}
{352}{}{Ora aspetta un attimo. Se non vuoi che ti ricompensi con del toast, allora almeno lascia che ti dia un piccolo consiglio. Sai
 quelle slot machine che trovi nei casinò? Beh, ho calcolato un metodo per far perdere alle macchine i loro soldi.
 Ho un QI di 6000, sai. Quando non faccio toast, mi piace riflettere su queste cose. Per avermi aiutato,
 ti diro' questi codici segreti. Usa una delle macchine come faresti normalmente e...}
{353}{}{[AVANTI]}
{354}{}{...E questo e' tutto. Sarai ricco in un attimo, mangiando toast a volonta'.}
{355}{}{Thanks. I appreciate this. So long.}
{400}{}{You successfully repair the toaster.}
{401}{}{You fail to repair the toaster.}
{402}{}{The toaster is already repaired.}
{403}{}{ ripara con successo il tostapane.}
{404}{}{ fails to repair the toaster.}
