{100}{}{You see Sergeant Cat Jules.}
{101}{}{You see a good-looking black man with rather pronounced canines. He moves with a constant swagger and has a smug
 expression on his face.}
{200}{}{[Mentre ti avvicini alla camera criogenica, vedi un uomo di colore snello e nudo disteso sul pavimento.
 Il suo corpo muscoloso trema ancora per l'acqua gelida e fredda. Ti guarda mentre ti avvicini.]}
{201}{}{Chi sei?}
{210}{}{[Alzandosi in piedi e scuotendosi per asciugarsi come un animale bagnato, l'uomo ti guarda e sorride beffardo, rivelando alcuni denti anteriori stranamente affilati.]
 Chi sono *io*? Chi sei *tu*? Sembri un barbone pesantemente armato!}
{211}{}{[Alzandosi in piedi e scuotendosi per asciugarsi come un animale bagnato, l'uomo ti guarda sorridendo ampiamente, rivelando alcuni denti anteriori stranamente affilati.]
 Chi sono *io*. Ma dai, sono solo il Serg. Jules, il soldato piu' bello di questa base, bella!}
{212}{}{Sono }
{213}{}{. But, what's your name?}
{214}{}{Non fare il galletto con me. Cos'ha di speciale questo posto comunque?}
{215}{}{Capisco. Bene, Serg. Jules, cosa sta succedendo qui comunque?}
{216}{}{Come mai sei vivo? Il Dottore ha detto che era l'unico sopravvissuto.}
{220}{}{Mi chiamo Serg. Jules, ma puoi chiamarmi Cat. Sono il soldato piu' veloce e piu' bello di questa base.}
{221}{}{Right, whatever you say. So, what's with this place?}
{230}{}{Intendi il Dottor C? Perche' si sarebbe dimenticato di me? Diavolo, ha contribuito a plasmare questa opera d'*ARTE* [Indica il proprio corpo].}
{231}{}{Right, whatever you say. So, what's with this place?}
{232}{}{Penso che stiamo parlando di due persone diverse... Allora, cosa sta succedendo qui intorno comunque?}
{240}{}{E' una struttura governativa per quanto ne so. Fanno ogni tipo di ricerca top secret. Ma...[Si guarda intorno
 nella stanza.] e' stranamente silenziosa. Dove sono tutti?}
{241}{}{Be', questo probabilmente ti sconvolgera', ma sei stato congelato per oltre un secolo. Il mondo
 non e' piu' lo stesso. Hanno sganciato le bombe e la Terra e' piombata nel silenzio. La societa' sta ancora cercando di ricostruirsi dalle
 ceneri.}
{250}{}{[Il Serg. Jules ti guarda con un sopracciglio alzato.] Non stai scherzando, vero? Be', allora l'hanno davvero fatto.
 Accidenti. Immagino di essere stato fortunato ad essere stato tolto dall'esercito e portato qui.}
{251}{}{You were in the army?}
{260}{}{Esatto. Ero l'esperto di armi energetiche. Abbastanza agile sui piedi anche. Ero stato nell'esercito solo per circa un anno
 prima di essere riassegnato qui. E' un peccato che non vedro' mai piu' nessuno dei miei amici. Avrei voluto scambiarci qualche addio.}
{261}{}{Mi dispiace.}
{262}{}{Mi dispiace per le tue perdite, ma devi andare avanti. Crogiolarti nella tua miseria non ti portara' da nessuna parte.}
{270}{}{Si', lo siamo tutti. Cosa faro' adesso pero'?}
{271}{}{I guess you're right. What am I going to do now though?}
{272}{}{Well, I could use a companion. Want to join me?}
{273}{}{Be', devo proprio andare. In bocca al lupo la' fuori.}
{280}{}{Hey, why not! I'll show you this Cat still got what it takes.}
{281}{}{Sounds good. Let's go.}
{282}{}{Come desideri.}
{290}{}{Don't you worry about this ol' cat. I'll find my place in this world. Now step aside and let the Cat do his thing.}
{291}{}{[FINE]}
{300}{}{So, how did you end up in that cryo chamber? And what happened to your teeth?}
{301}{}{I used to be the guard for one of the genetics labs. They were messing with human and feline DNA.
 Trying to make something with the best of both worlds, I suppose. And that's where yours truly comes in.
 [Cat flashes you his toothy grin.] They wanted a volunteer for one of their projects. It was for scouts and the like, supposed to
 make you more agile and flexible. I liked the sound of that *leers*. Anyway, they gave me this shot, put me under, and
 the next thing I knew, I had these teeth, and I felt.... sharper? Kind of predatory.}
{302}{}{Continua.}
{303}{}{Well, apparently the experiment wasn't going as planned and whatever they put inside me wasn't sitting
 well with my system. I don't know what they meant by that, since I felt better than ever. They decided to throw me in
 the cryo freezer until they figured out what to do with me.}
{304}{}{And then I thawed you out. Seems like you owe me one.}
{305}{}{Yeah, you saved me. In return, maybe I can save your sense of style, monkey.}
{306}{}{Monkey? Must be the cat DNA talking. That's all I need to know for now.}
{310}{}{Since you were in the army, you think you might be able to teach me anything?}
{311}{}{I might be able to teach you a thing or two about energy weapons and other big weapons. Now you have to remember...}
{312}{}{[Continue.]}
{313}{}{There you go. That should help you melt those mutants who get in your way.}
{314}{}{Grazie.}
{390}{}{You ready to take me with you?}
{391}{}{Andiamo.}
{392}{}{No, non ancora.}
{400}{}{Ti serve qualcosa?}
{401}{}{How can the Cat be of service?}
{402}{}{Si'?}
{410}{}{Che cosa vuoi sapere?}
{411}{}{Well, I was trained to use the usual military stuff. Rifles, pistols, SMGs and the like. I prefer laser
 weapons and the like better though. Those have style! But if you give me some brass knuckles or one of those power fists,
 I'll pounce on any flat-footed goons before they know what hit them!}
{421}{}{What's wrong with it?}
{422}{}{Alright. I have your back.}
{423}{}{A me sta bene.}
{424}{}{I work better solo anyway.}
{430}{}{I don't have much patience, so hurry back.}
{431}{}{I'm not a fan of waiting. Don't take too long.}
{440}{}{We moving out?}
{441}{}{It is about time you got back.}
{450}{}{It's good to be on the move again. My legs need to keep moving.}
{451}{}{It's about time we did something together again.}
{460}{}{Sure, it looks like crap anyway. Got anything in blue?}
{470}{}{Ok, but this is *my* shiny thing. And if you try and take it off me, I may have to shoot you.}
{480}{}{I'm feeling top notch.}
{481}{}{Just a few scratches, nothing to worry about.}
{482}{}{I've seen worse in the army.}
{483}{}{Call a medic. I'm going down fast.}
{484}{}{I'm bleeding out of everything now...}
{490}{}{Jesus, your ugly. You ought to get yourself checked out. I'm outta here.}
{491}{}{Baby, you got real ugly. I'm outta here.}
{500}{}{Don't get me wrong, it is good to stick together, but you are taking this a little too far. Come back when you
 got less people.}
{501}{}{Don't get me wrong, it is good to stick together, but you are taking this a little too far. Come back when you
 got less people. Now while you are making room, I'm going to find some clothing to wear. [Looking around, Cat Jules spots
 a locker, opens it and looks inside.] These really are not my style, but I guess they will do. [He quickly puts the clothing on.]
 Alright, let me know when you are ready.}
{510}{}{Did I eat bad fish or something? I feel poisoned.}
{520}{}{I feel like I am melting away here. Must be radiation poisoning.}
{530}{}{How do you expect me to perform at my best with this broken limb?}
{540}{}{Who turned out the lights? I think something's wrong with my eyes.}
{600}{}{Some might say I'm a pretty shallow guy, but a shallow guy with a great ass.}
{601}{}{In the army it was always, "Cat do this. Cat do that." What am I, a dog?}
{602}{}{[singing] 'Cause you make me tongue tied, tongue tied... [singing]}
{700}{}{LADIES! Ladies, one at a TIME, please!}
{710}{}{I've got a nose for trouble, and it's going off like a nuke attack siren!}
{720}{}{GOLD mining? This where they dig up the shiny things?}
{730}{}{I thought we were leaving this place for good?}
{800}{}{I've had enough of smart-ass lunatics! Can we leave this greasy little idiot?}
{810}{}{What's with the bone, Neanderthal?}
{820}{}{Least I didn't end up like YOU, Lenny!}
{830}{}{Least I didn't end up like YOU, Marcus!}
{2900}{}{I need to put on some clothing first. [Looking around, Cat spots a locker, opens it and looks inside.]
 These really aren't my style, but I guess they'll do. [He quickly puts the clothing on.] Alright, I'm good to go.}
{2901}{}{[FINE]}
{5000}{}{[The man stands up and shakes himself dry like a wet animal. As he looks at you, his eyes suddenly get really wide and he starts gasping for air.]}
{5001}{}{[FINE]}
{5002}{}{Oh, merda!}
