{100}{}{Vedi un ologramma.}
{101}{}{Vedi un ologramma.}
{200}{}{Zzzzzt... Ciao... zzZzzt..Mi..zzzZzzZtt... capi... sci?}
{201}{}{Mi scusi?}
{202}{}{Certo. Addio.}
{203}{}{Il mio... zZzzzt..sensore... ZzzzzzZzt...*disturbi*..riparato?}
{204}{}{Mi dispiace, ma non riesco a capirti. C'e' troppo disturbo. Vedro' se riesco a sistemarlo in qualche modo.}
{205}{}{Non ho tempo per questo. Ciao.}
{300}{}{Ah, grazie mille per avermi riparato! Temevo l'idea che qualche visitatore potesse arrivare e farmi domande a cui non avrei potuto rispondere correttamente a causa di tutto il disturbo. Certo, sei il primo visitatore che vedo dalla guerra, ma comunque, *se* ne avessi incontrato un altro, sarebbe stato piuttosto imbarazzante.}
{301}{}{Nessun problema. Quindi, che posto e' esattamente questo?}
{302}{}{[Sorride, apparentemente felice di avere domande a cui rispondere.] Ti trovi nell'Environmental Protection Agency, piu' comunemente chiamata EPA. Siamo una struttura di ricerca governativa specializzata nel testare sostanze chimiche per garantire che siano sicure per l'ambiente terrestre. Ma questo e' solo l'inizio. Qui succedevano un sacco di cose interessanti, almeno finche' la struttura non e' stata evacuata a causa della guerra. Da allora le cose non sono piu' state le stesse.}
{303}{}{Interessante. Quindi, qual e' esattamente il tuo scopo qui?}
{304}{}{Beh, a differenza degli altri ologrammi che incontrerai, non sono stato creato per un compito specifico. Sono qui semplicemente per rispondere alle domande dei visitatori o aiutare a risolvere problemi matematici difficili che la mente umana non puo' affrontare.}
{305}{}{Capisco. Allora forse potresti rispondere ad alcune domande?}
{310}{}{Oh, adorerei rispondere alle tue domande. Chiedi pure e rispondero' al meglio delle mie capacita'.}
{311}{}{Continuo a vedere riferimenti a un Livello Blu. Come posso accedervi?}
{312}{}{Ho trovato un altro modo per entrare nella struttura, ma richiede un codice di accesso. L'ascensore di servizio ci porta.}
{313}{}{Puoi identificare alcuni oggetti che ho trovato qui intorno?}
{314}{}{Non importa. Non ho bisogno di nulla.}
{320}{}{Ma certo, l'ascensore principale in superficie dovrebbe portarti dove vuoi andare! Perche' dovresti passare dal sistema di ventilazione?}
{321}{}{Beh, quell'ascensore non funziona piu' e l'unico modo che ho trovato per entrare era attraverso le prese d'aria.}
{322}{}{Oh, capisco. Ha piu' senso. Beh, c'e' un altro modo per entrare. C'e' un ascensore di servizio che si ferma al livello due. 
Dovrebbe essere accessibile da sotto l'officina del Dottore. Lo trovi all'esterno, a est dell'ingresso principale dell'EPA. 
Avrai bisogno di un codice di accesso per entrare, comunque. Poiche' ti sono grato per avermi riparato, ti diro' il codice. Il codice e' "FLOWERPOT".}
{323}{}{Grazie. Lascia che ti chieda qualcos'altro.}
{324}{}{Oh, mi dispiace, ma il Livello Blu contiene ricerche top secret. L'accesso a quel livello e' limitato a... oh, al diavolo. Sei stato cosi' gentile da ripararmi, quindi credo di poterti dare la password. E' "FLOWERPOT".}
{330}{}{Faro' del mio meglio. Quale oggetto vuoi che identifichi?}
{331}{}{A cosa serve questo cibo per cani?}
{332}{}{Ho trovato questa siringa piena di una sostanza sconosciuta. Puoi dirmi cosa fa?}
{333}{}{Ho trovato questo supporto con provette. C'e' qualcosa di specifico che posso farci?}
{334}{}{Quali sono gli effetti dell'uso di queste droghe che ho trovato?}
{335}{}{Ho creato alcune sostanze sconosciute con la macchina Mr. Chemmie!. A cosa servono?}
{336}{}{Ho trovato della dinamite diversa da quella che ho visto finora. Come la uso?}
{337}{}{In realta', lasciami chiedere qualcos'altro.}
{340}{}{Beh, i progettisti originali di questo posto amavano inserire piccoli riferimenti a film, libri e altre
 fonti simili ovunque. Lo trovavano divertente, e anche molti altri. Il cibo per cani e' un riferimento a un film,
 ma lascero' a te il compito di capirlo.}
{341}{}{Bene. Lasciami chiedere qualcos'altro.}
{350}{}{Beh, sono strumenti di base per qualsiasi chimico. Suppongo che, se vuoi creare qualcosa, potresti
 trovarci un utilizzo.}
{351}{}{Bene. Lasciami chiedere qualcos'altro.}
{360}{}{Ah, quello e' uno specimen interessante. Temo di non riconoscerlo. Per favore, mettilo nel contenitore accanto a me e saro' felice di analizzarlo per te.}
{361}{}{D'accordo. [Metti l'oggetto nel contenitore e chiudi il coperchio.]}
{362}{}{Ripensandoci, lasciami chiedere qualcos'altro.}
{363}{}{Lettura della composizione molecolare del liquido nella siringa... Successo. Analisi completata. Interessante, sembra che questa siringa contenga un siero unico con tracce di DNA felino. Sembra essere una droga sperimentale con il potenziale di aumentare l'agilita' umana. Ovviamente, non consiglierei di usare qualcosa che e' ancora in fase sperimentale.}
{364}{}{Bene. Lasciami chiedere qualcos'altro.}
{370}{}{Ah, quella sarebbe cannabis, conosciuta anche come marijuana, weed e ganja, tra le altre cose. E' una droga illegale che puo' indurre effetti psicoattivi quando viene fumata o consumata. Alcuni tecnici qui erano soliti fumarla per rilassarsi. Se la fumi, devi sapere che potrebbe offuscare la mente e ridurre i tuoi tempi di reazione per un certo periodo.}
{371}{}{Bene. Lasciami chiedere qualcos'altro.}
{380}{}{Ah, quello e' uno specimen interessante. Temo di non riconoscerlo. Per favore, mettilo nel contenitore accanto a me e saro' felice di analizzarlo per te.}
{381}{}{D'accordo. [Metti l'oggetto nel contenitore e chiudi il coperchio.]}
{382}{}{Ripensandoci, lasciami chiedere qualcos'altro.}
{383}{}{Sfortunatamente, non ho informazioni nel mio database che descrivano questo oggetto. Come per qualsiasi sostanza sconosciuta, ti consiglierei di essere molto cauto prima di decidere di usarla. Mi dispiace di non poter essere piu' utile.}
{384}{}{Bene. Lasciami chiedere qualcos'altro.}
{390}{}{Questo e' un oggetto interessante. A differenza della dinamite normale, che ha un timer, questa e' controllata da un detonatore radio.
 Basta posizionarla dove vuoi che esploda e premere il grilletto per farla detonare. Un oggetto davvero ingegnoso,
 non credi?}
{391}{}{Assolutamente. Lasciami chiedere qualcos'altro.}
{400}{}{Bentornato. Posso aiutarti in qualcos'altro?}
{401}{}{Ho delle domande da farvi.}
{402}{}{Lasciamo perdere. Ci vediamo.}
{500}{}{Apri il pannello laterale dell'emettitore olografico e guardi all'interno. Vedi un groviglio di cavi e schede elettroniche.}
{501}{}{Bene, cominciamo.}
{502}{}{Dopo un po' riesci a isolare il problema e a correggerlo. Richiudi il pannello e ti asciughi il sudore dalla fronte.}
{503}{}{Hai riparato con successo l'ologramma.}
{504}{}{Dopo alcuni tentativi non riesci a capire cosa non va nell'ologramma.}
{505}{}{Maledizione. E' troppo difficile per me. Le riparazioni non sono il mio forte.}
{506}{}{Non sei riuscito a riparare l'ologramma.}
{507}{}{[FATTO]}
