{100}{}{E' tutto... credo.}
{101}{}{No, ma non puo'... io, beh... hmmm...}
{102}{}{Il filo blu all'alloggiamento rosso...}
{103}{}{Quelle mutazioni stanno progredendo bene.}
{104}{}{Non manca molto adesso.}
{105}{}{Solo qualche altra goccia di HCl...}
{106}{}{Vedi un uomo con un camice da laboratorio bianco.}
{107}{}{Vedi il Dottore.}
{108}{}{Il principale — e unico — dottore rimasto nell'EPA.}
{109}{}{Sarebbe poco saggio attaccarmi.}
{120}{}{Si'?}
{121}{}{Salve, mi chiamo }
{122}{}{. Chi sei?}
{123}{}{Mi dispiace disturbarla. Arrivederci.}
{130}{}{Sono conosciuto come il Dottore.}
{131}{}{Ah, giusto. Quindi cosa fai? Perche' sei qui tutto solo? Il resto del posto sembra deserto.}
{132}{}{Ok, grazie.}
{140}{}{Vedo che hai abilita' adeguate nelle vie della scienza. Forse potresti capire cosa faccio qui, dopotutto. Cosa desideri sapere?}
{141}{}{Perche' sei qui?}
{142}{}{Di che cosa ti occupi?}
{150}{}{Mi dispiace, ma non credo tu abbia le competenze necessarie per capire cosa sto facendo qui. Torna quando sarai mentalmente piu' forte.}
{151}{}{Ehi, un momento. Provero' qualsiasi cosa tu mi dia!}
{152}{}{Bene, d'accordo allora. Arrivederci.}
{160}{}{Facevo parte del team originale di scienziati che lavorava qui nell'EPA prima della guerra. Sfortunatamente, nessuno di loro era abbastanza competente nelle discipline scientifiche o possedeva sufficiente determinazione, e hanno dovuto andarsene. Ora, sono l'unico rimasto.}
{161}{}{Quindi, sei felice di questo? Voglio dire, di essere l'unico qui?}
{170}{}{Qualsiasi cosa io voglia, davvero. Al momento sto conducendo ulteriori ricerche genetiche su creature che ho creato per osservare gli effetti dell'FEV sui loro sistemi immunitari. Anni fa ho creato molti nuovi farmaci e ne ho adattati diversi altri, ma non lo faccio piu'.}
{171}{}{Cosa sono quelle creature che hai creato?}
{172}{}{Che tipo di droghe hai prodotto?}
{180}{}{No, non puoi. Non sei abbastanza competente nelle vie della scienza e dei potenziamenti biologici. Ora, se vuoi scusarmi, mi stai facendo perdere tempo.}
{181}{}{Assolutamente no. Mettimi alla prova.}
{190}{}{<sorride> Beh, forse e' cosi'. Va bene, se vuoi, ti daro' una possibilita'. Cosa vorresti sapere allora?}
{191}{}{Perche' sei qui?}
{192}{}{Di che cosa ti occupi?}
{200}{}{Ma certo! Nessuno che mi controlla. Nessuna regola di alcun tipo. Faccio quello che voglio, quando voglio. Inoltre, essendo rimasto solo io qui, ho accesso a tutta l'attrezzatura di cui potrei mai avere bisogno. Altro?}
{201}{}{Chi sono quelle persone laggiù nelle gabbie?}
{202}{}{Che cos'e' tutto quel liquido dai colori strani che ho visto in giro per l'EPA?}
{203}{}{Da dove prendi tutto questo equipaggiamento?}
{210}{}{Quelli nelle prime celle vicino a quel muro sono alcuni abitanti del villaggio entrati qui per sbaglio, e li ho catturati per usarli piu' avanti. Gli altri, quelli che sembrano piu' forti, sono i miei guerrieri per... emergenze.}
{211}{}{...da usare in seguito? Cosa intendi?}
{212}{}{Grazie. Posso fare un'altra domanda?}
{213}{}{Capito. Grazie. Devo andare adesso.}
{220}{}{Sostanze chimiche e serbatoi di FEV, principalmente. Era tutto contenuto in grandi barili per essere conservato in sicurezza qui all'EPA. Sfortunatamente, c'e' stato un piccolo incidente e una grande perdita chimica ha costretto tutti ad andarsene, tranne quei tonti degli ologrammi. Alcune sostanze sono filtrate nei livelli inferiori. Ora le sto usando come materiale di sperimentazione. Finora hanno dato risultati promettenti!}
{221}{}{Che tipo di risultati? Vuoi dire che hai creato tu queste creature?}
{222}{}{Allora da dove ti procuri tutto il tuo equipaggiamento?}
{230}{}{Per lo piu' qui. L'EPA era stata progettata e fornita con ogni tipo di macchinario e, da quando gli altri scienziati se ne sono andati, non e' stato usato piu' nulla. Ora, dopo tanti anni, sto solo esaurendo alcune cose...}
{231}{}{Non importa. Devo andare adesso.}
{240}{}{Droghe? Decine! Negli anni ho creato mentats, buffout, stimpak, kit medici di varie potenze, psycho e molte altre cose che non capiresti. Non lo faccio piu', comunque. Ho creato il robot Mr. Chemmie! per farlo al posto mio. Si trova nel complesso principale. Se hai davvero l'intelligenza e le capacita' scientifiche che dici, sentiti libero di usarlo per creare tutte le droghe che vuoi.}
{241}{}{Che tipo di droghe speciali hai creato?}
{242}{}{Dove posso trovare il Signor Chemmie!?}
{243}{}{Grazie. Senti, hai mai sentito parlare del Jet?}
{250}{}{Si', ho creato molte creature mentre ero all'EPA. Se sei un tipo che esplora, potresti averne incontrate alcune nelle Lande. Centauri? Flotter? Gli \"Alieni\"? Ora vagano liberamente nelle Lande. Ne ho tenute solo alcune qui e nella base principale per riferimento futuro.}
{251}{}{Un momento. Mi stai dicendo che tutte quelle creature la fuori, quelle cose che infestano le Lande e uccidono innocenti, le hai create tu?!}
{252}{}{Whoa, promemoria: non fare arrabbiare il Dottore. Arrivederci.}
{260}{}{'Cosa intendo?' Il Virus dell'Evoluzione Forzata, naturalmente! Sto solo iniziando a sperimentarne gli effetti sugli esseri umani. Abbiamo tutti sentito la storia del Master. Stavo pensando di fare qualcosa di simile anch'io. Un mio esercito sarebbe certamente molto utile!}
{261}{}{Non pensi che sia un po' immorale? Come puoi anche solo considerare una cosa cosi' orribile?}
{262}{}{Solo ora stai passando agli esseri umani? Su cos'altro hai lavorato allora?}
{263}{}{Beh, buona fortuna. Devo andare adesso.}
{270}{}{Si', suppongo di si'. Mi diverti molto. Cos'altro posso risponderti? }
{271}{}{Parlami ancora di queste persone.}
{272}{}{Cos'e' tutto quel liquido dai colori strani intorno all'EPA?}
{273}{}{A cosa si ispira per i suoi modelli?}
{280}{}{No, no, no. Prima che tu vada, devo chiederti una cosa. Potresti farmi un piccolo favore? Non lascio la sicurezza del magazzino per paura che mi rubino qualcosa. Ho bisogno di alcune materie prime. Potresti aiutarmi?}
{281}{}{Si', suppongo di si'. Cosa ti serve?}
{282}{}{No, sono troppo occupato al momento. Forse un'altra volta.}
{290}{}{Si', mi chiedevo cosa avrebbe fatto il virus sugli animali domestici conservati prima della guerra. Sfortunatamente, ha influenzato i loro cicli riproduttivi e si sono riprodotti molto rapidamente. Li ho liberati nelle Lande poco dopo averlo capito.}
{291}{}{Sei un mostro! Non c'e' da stupirsi che nessuno nella zona sappia di te! Dovresti essere eliminato.}
{292}{}{Beh, non approvo quello che stai facendo, ma non c'e' nulla che io possa fare al riguardo. Arrivederci.}
{300}{}{Droghe speciali? Beh, ho coltivato una nuova coltura di marijuana. E' una droga prebellica che ho trovato in congelamento profondo. Ho solo letame proveniente dalle creature mutate che vedi qui, quindi era piu' pericoloso di quanto pensassi. Le prime prove non sono state molto riuscite, comunque...}
{301}{}{Posso avere un po' di questa droga?}
{302}{}{Perche' non hanno avuto successo? Cosa e' successo?}
{310}{}{Mr. Chemmie! si trova nella sezione nord-est del piano inferiore dell'EPA. O forse nord-ovest... In realta' e' al piano superiore. Oh, non ricordo piu'. E' un enorme pezzo di macchinario. Non puoi sbagliarti.}
{311}{}{Giusto. Grazie. Hai detto di aver creato alcune droghe speciali. Come quali?}
{320}{}{Facile. Sono uno scienziato. E' quello che faccio. Gli esperimenti sono la mia vita. Anche se diverso, e' comunque solo un altro tipo di esperimento.}
{321}{}{Stai giocando con cose che non dovresti alterare! E se qualcosa andasse storto? E se alcune delle persone su cui lavori morissero!?}
{330}{}{Eliminato! Oh, no. Non credo proprio. Sto facendo il lavoro per cui sono stato assunto: indagare e sperimentare. Col passare del tempo, pero', inizi a esaurire le cose da indagare, quindi devi essere piu' libero nelle tue idee. Credo che una volta lo chiamassero 'pensare fuori dagli schemi'.}
{331}{}{Ne ho abbastanza! Se nessun altro ti fermera', lo faro' io.}
{332}{}{Sei malato e me ne vado. Arrivederci.}
{340}{}{Si', perche' no? Serviti pure. Ce n'e' in abbondanza nei magazzini al livello della superficie. Credo di aver programmato anche Mr. Chemmie! per produrla. Non ne tengo piu' qui perche' occupa troppo spazio.}
{341}{}{Grazie! Dicevi un attimo fa che le prime prove non erano state un successo? Perche'?}
{350}{}{Beh, alcuni soggetti di prova hanno avuto reazioni gravi al virus, ma non vale nemmeno la pena menzionarle. Qualche errore qua e la' e' previsto nel nostro lavoro. Ora, se vuoi scusarmi, ho delle cose da fare.}
{351}{}{Si', suppongo anch'io. Arrivederci.}
{360}{}{Allora muoiono. Cosa ti aspetti che faccia? E' cosi' che si fa progresso.}
{361}{}{Mostruoso! Incredibile! Tu muori, adesso!}
{362}{}{Non ne posso piu'. Arrivederci. Non tornero' presto.}
{370}{}{Jet? Si', e' la droga di cui la maggior parte di Redding e' fatta, se non sbaglio. E' un composto eccezionalmente complesso e le mie macchine non riuscivano a riprodurlo nemmeno alla massima potenza. Perche'? Che cosa ne sai?}
{371}{}{Beh, ho qui con me il suo creatore.}
{380}{}{[*Gli brillano gli occhi*] Davvero!? Chi? Posso vederlo? Magari parlargli?}
{381}{}{Certo. Si chiama Myron. E' proprio qui.}
{390}{}{Grazie per avermi portato quel ragazzo, Myron. E' molto competente! Non proprio brillante quanto me, capisci, ma comunque valido. Se un giorno volesse stabilirsi, puo' venire qui come mio apprendista.}
{391}{}{Non sono sicuro che gli piacerebbe essere l'apprendista di qualcuno. E' meglio che andiamo.}
{400}{}{Un momento, prima che tu vada. Per favore, prendi questo come ringraziamento per aver portato Myron qui. Non mi serve davvero.}
{401}{}{Ehi, grazie. Uhm, cos'e'?}
{410}{}{E' un Solar Scorcher. Era un mio esperimento. Si alimenta con l'energia del sole e quindi non richiede munizioni. Funziona davvero e ti sara' molto utile, ne sono certo, nelle Lande piu' profonde. Questo in realta' richiede un'altra domanda...}
{411}{}{Di cosa si tratta?}
{420}{}{Sembri un tipo avventuroso. Io sono confinato nei terreni dell'EPA per sorvegliare molti esperimenti, ma ho bisogno di alcune attrezzature che ho esaurito. Potresti raccogliere alcune cose per me?}
{421}{}{Si', suppongo di si'. Cosa ti serve?}
{422}{}{No, sono troppo occupato al momento a salvare il mio villaggio. Forse un'altra volta.}
{430}{}{Beh, uno dei pochi animali che non ho ancora studiato in dettaglio e' il Geco Dorato. Ho bisogno di materiale di ricerca prima di poter andare oltre. Potresti raccogliere, diciamo, 10 pelli di geco dorato e riportarmele qui? Sono sicuro che potrei trovare qualcosa da darti in cambio.}
{431}{}{Nessun problema. Tornero' non appena li avro'.}
{432}{}{Ho gia' con me 10 pelli.}
{440}{}{[Alza lo sguardo verso di te.] Cosa?}
{441}{}{Uh, ciao di nuovo. Non ho capito chi fossi l'ultima volta che abbiamo parlato.}
{450}{}{Ancora tu? Cosa vuoi adesso?}
{451}{}{Cosa fai qui? Questo posto sembra una citta' fantasma.}
{460}{}{Se non vuoi aiutarmi, allora per favore lasciami in pace. Oppure hai deciso di offrire le tue capacita'?}
{461}{}{Si'. Cosa vuoi che faccia?}
{462}{}{No, ma non appena saro' libero tornero' ad aiutarti.}
{470}{}{Salve. Ti sei calmato un po'?}
{471}{}{No, sono qui per ucciderti. Il mondo ha bisogno di meno persone come te.}
{472}{}{Si', suppongo di si'. Ho bisogno di farti alcune domande.}
{480}{}{Cosa vuoi? Ho esperimenti da sorvegliare, lo sai!}
{481}{}{Parlami delle droghe che stai producendo.}
{482}{}{Parlami ancora di quelle persone.}
{483}{}{Sto cercando lavoro. Ne hai?}
{484}{}{Da dove prendi tutto il tuo equipaggiamento?}
{490}{}{Hai raccolto le pelli come ti avevo chiesto?}
{491}{}{Si', eccola.}
{492}{}{No, non ancora.}
{500}{}{Meraviglioso! Eccellente! Vediamo... ah si', questi andranno benissimo! Allora, vuoi un altro incarico?}
{501}{}{Si', se hai qualcosa}
{502}{}{Non ancora, grazie. Arrivederci.}
{510}{}{Beh, anche se il magazzino e' dove svolgo quasi tutto il mio lavoro, devo comunque entrare nel complesso principale di tanto in tanto. Tuttavia, le luci sono fissate permanentemente su un'impostazione bassa. Sistemalo per me cosi' posso entrare nell'edificio dell'EPA.}
{511}{}{Nessun problema.}
{512}{}{Tornero' da te quando avro' tempo di farlo.}
{513}{}{L'ho gia' fatto! C'erano alcuni fili allentati sulla scheda principale e io stavo per—}
{520}{}{Ora che hai ucciso tutti i miei guerrieri, hai piu' che dimostrato il tuo valore. Considereresti di lavorare per me?}
{521}{}{Cosa!? Lavorare per te!? Cosa vorresti che facessi?}
{522}{}{No grazie. Arrivederci.}
{530}{}{Hai gia' risolto il problema dell'energia?}
{531}{}{Si', si', si', non ho bisogno dei dettagli. Grazie. Ora, ho ancora un altro compito se desideri affrontarlo.}
{532}{}{Di cosa si tratta?}
{533}{}{No, ci sto ancora lavorano.}
{540}{}{Sto sperimentando un nuovo siero per migliorare l'agilita' e la consapevolezza delle persone, cosi' da aiutarle a sopravvivere in questo mondo duro. Mi permetteresti di provarlo su di te, vero?}
{541}{}{Beh... suppongo di si', che male potrebbe fare?}
{550}{}{Piu' di quanto potresti mai immaginare, se qualcosa andasse storto... Ora stai fermo e mettiamoci al lavoro!}
{551}{}{Whoa! Aspetta un attimo...}
{560}{}{Ahh, eccoti! Di nuovo nel mondo dei vivi, vedo! Come ti senti?}
{561}{}{Uh, bene, perche'?}
{570}{}{Sei solo svenuto per un paio d'ore, ma ora dovresti stare bene. Gli indicatori mostrano che sei molto piu' vigile e reattivo.}
{571}{}{Wow! Grazie, Dottore.}
{580}{}{Nessun problema. Se mai avessi bisogno di qualcosa, fammelo sapere.}
{581}{}{Lo faro'. Arrivederci.}
{590}{}{Hai deciso di aiutarmi?}
{591}{}{Si', ti aiutero'. Tornero' quando l'energia sara' ripristinata.}
{592}{}{No, mi dispiace.}
{600}{}{Mi dispiace, ma non posso fare altro per te ora. Non ho altri incarichi da assegnare. Grazie per il tuo aiuto.}
{601}{}{Arrivederci allora.}
{602}{}{Si', c'erano alcuni fili allentati e ho dovuto trovare un po' di rottami per—}
{603}{}{NO! Cosa stai facendo?}
{700}{}{Un momento! Facevi parte del team *originale*?! Ma allora devi avere quasi 200 anni!}
{701}{}{Beh, suppongo sia vero, in un certo senso. In realta' sono nato 202 anni fa. Tuttavia, non avrei mai potuto vivere cosi' a lungo con mezzi normali.}
{702}{}{Va' avanti. Sto ascoltando.}
{703}{}{Quando la guerra e' iniziata, io e gli altri scienziati abbiamo usato le camere criogeniche. Abbiamo ceduto piu' controllo della struttura agli ologrammi e ai robot, poi ci siamo messi nelle camere per superare il peggio della distruzione.}
{704}{}{Ma la Grande Guerra e' finita moltissimi anni fa.}
{705}{}{Vero. Siamo usciti dall'ibernazione circa 90 anni fa e abbiamo scoperto che questo posto era molto deteriorato. La maggior parte degli altri scienziati ha continuato alcune delle loro ricerche originali, perche' non sapevano davvero cos'altro fare.}
{706}{}{[AVANTI]}
{707}{}{Non potevo credere alla loro miopia scientifica... alla totale mancanza di immaginazione! Avevamo un'incredibile opportunita' di fare cose straordinarie. Avevamo la possibilita' di rifare tutto come ritenevamo opportuno. Purtroppo, i miei compagni hanno pagato la loro mancanza di visione...}
{708}{}{Li hai uccisi!?}
{709}{}{Comprensibile.}
{710}{}{Per favore, continua.}
{711}{}{No, non li ho uccisi. Ma non potevo permettere che restassero qui a interferire con i miei piani. Ho semplicemente manipolato gli eventi in modo che scegliessero di andarsene.}
{712}{}{Okay, questo risponde a una parte della storia. Ma manca ancora qualcosa...}
{713}{}{Ah, si'. Scusa. A volte divago o la mia mente vaga. Le grandi menti, sai com'e'. Comunque, continuo a usare la vasca. Anche se l'ho modificata un po'.}
{714}{}{Che modifiche hai apportato?}
{715}{}{Credo di aver sentito abbastanza. Arrivederci.}
{716}{}{Beh, la prima volta che abbiamo usato le camere criogeniche, era come se fossi andato a dormire e mi fossi svegliato. Ma ho capito che era uno spreco di tempo. Ho reimpostato le camere in modo da poterle usare per anni alla volta, mantenendo pero' la mente cosciente! Uso quei lunghi periodi per riflettere sui progetti attuali e ideare nuovi esperimenti. Cosi' posso vedere gli effetti a lungo termine delle mie ricerche.}
{717}{}{Hai mai considerato che usare la camera in questo modo potrebbe danneggiarti in qualche modo?}
{718}{}{Sciocchezze! Semmai sto migliorando. Ora vedo tutto cosi' chiaramente, grazie ai miei periodi di ibernazione lucida.}
{719}{}{Che pazzo! Arrivederci.}
{720}{}{In realta' e' un'ottima idea. Geniale! Ehi, pensi che potrei vedere questa camera criogenica?}
{721}{}{Capisco. Parlami di qualcos'altro.}
{722}{}{Ma certo. E' proprio li'. L'ho fatta spostare qui sopra qualche tempo fa. Tenere la camera nei livelli inferiori della struttura non era una buona idea.}
{723}{}{Interessante. Allora, come funziona?}
{724}{}{Beh, ovviamente i principi scientifici della criogenia sono piuttosto avanzati. Tuttavia, le funzioni sono controllate dal computer qui, che ha un'interfaccia abbastanza semplice. [Ti mostra per alcuni minuti come funziona il sistema.]}
{725}{}{Grazie delle informazioni, Dottore. Credo di voler sapere ancora qualche altra cosa.}
{726}{}{Grazie delle informazioni, Dottore. Chissa'? Informazioni del genere potrebbero rivelarsi utili un giorno. Arrivederci.}
{727}{}{Beh, basta chiacchiere. Devo andare. Arrivederci, Dottore.}
{728}{}{No, non sarebbe affatto opportuno lasciarli qui a interferire con i miei piani... proprio no... [Il Dottore guarda oltre di te, perso nei suoi pensieri.]}
{729}{}{Sai, sei proprio una persona contorta. Credo che dovro' mostrarti come 'sperimento' sulle persone. E' ora di morire!}
{730}{}{Quindi, sei felice di questa situazione? Voglio dire, di essere l'unico qui?}
{731}{}{Cos'altro vorresti sapere?}
{800}{}{In realta', aspetta un secondo. Sembri un tipo avventuroso. Potrei avere bisogno di qualcuno con le tue capacita'.}
{801}{}{Certo. Cosa ti serve?}
{802}{}{No grazie. Arrivederci.}
{803}{}{Beh, ero fuori a raccogliere campioni in uno dei miei siti di lavoro e sembra che abbia lasciato li' uno dei miei strumenti. 
Normalmente andrei a prenderlo da solo, ma al momento sono estremamente impegnato e, per quanto mi sforzi, non riesco a ricordare il punto esatto in cui l'ho lasciato. 
In ogni caso, vai a nord-ovest da questo edificio e troverai l'area dove ho lasciato il mio strumento. Dovrebbe essere una passeggiata.}
{804}{}{Me ne occupo subito.}
{805}{}{Non mi interessa. Ciao.}
{806}{}{Beh, aspetta. Sei sicuro di non voler aiutarmi con una piccola cosa?}
{810}{}{Eccellente! Ora devo tornare al lavoro. [Tra se'.] Sta andando tutto secondo i piani.}
{811}{}{[FATTO]}
{820}{}{Che peccato. Beh, devo tornare al lavoro. [Tra se'.] Quasi l'avevo convinto. Ora, dove trovero' un altro soggetto di prova...}
{821}{}{[FATTO]}
{830}{}{[L'uomo alza lo sguardo, sorpreso.] Ma che—?!}
{831}{}{Sto ancora cercando il tuo pezzo.}
{832}{}{Ecco il tuo strumento. Una passeggiata, davvero.}
{833}{}{Cercavi di uccidermi la fuori? Era un labirinto pieno di mostri mutati. Questo non era un normale recupero pezzi, vero?}
{840}{}{Cosa?! Dammi quello! [Ti strappa lo strumento di mano.] Come hai— Oh, lascia perdere. Torniamo al tavolo da disegno allora...}
{841}{}{[Ignori la reazione dell'uomo.] Bene, se hai bisogno di qualcos'altro, fammelo sapere. Arrivederci.}
{850}{}{Non sono affari tuoi. [Ti strappa lo strumento di mano.] Ora vattene. Ho delle cose da fare. [Distoglie lo sguardo, borbottando tra se'.]}
{851}{}{Vabbe'. Ci vediamo.}
{852}{}{Non credo proprio. Hai cercato di uccidermi e ora ricambiero' il favore. Preparati a morire!}
{860}{}{Uh, si', certamente. Bene, mettiti al lavoro allora.}
{861}{}{[FATTO]}
{900}{}{*Borbottii*}
{901}{}{*Tra se'* Ero sicuro che non sarebbe tornato.}
{1000}{}{Restituisci al Dottore l'attrezzo dimenticato.}
