{100}{}{Vedi un terminale.}
{101}{}{Vedi un'unita' di controllo del campo di forza.}
{200}{}{Terminale di controllo del campo di forza. Inserisci un comando:}
{201}{}{Disabilita campo di forza.}
{202}{}{Esci.}
{203}{}{Giocherelli con l'interfaccia senza ottenere nulla. Sei sicuro che potresti violarla con abilita' piu' elevate.}
{204}{}{[Dopo diversi minuti di tentativi, compare un conto alla rovescia di 5 secondi insieme a un messaggio.] Rilascio dei soggetti in corso...}
