{100}{}{Postazione Computer della Sedia Elettrica: Seleziona un'opzione.}
{101}{}{Attiva la Sedia Elettrica.}
{102}{}{Disattiva la Sedia Elettrica.}
{103}{}{Sedia attivata. Per favore, incoraggia la persona ad avvicinarsi il piu' possibile alla sedia da entrambi i lati. Grazie.}
{104}{}{Chair disempowered.}
{105}{}{Esci.}
{106}{}{You see a computer whirring to itself.}
{107}{}{You see the Electric Chair Computer.}
{108}{}{You see a computer controlling the electric chair.}
