{100}{}{Archiviazione Dati e Manutenzione. Seleziona un'Opzione.}
{101}{}{Esegui Diagnostica.}
{102}{}{[FATTO]}
{103}{}{Controllo in esecuzione... Avvio... Compilazione... Grazie per la pazienza durante questa procedura... Completato. L'archiviazione dati funziona all'84% di efficienza. Un guasto nel cablaggio del mainframe di questo computer sta causando un funzionamento ad alta potenza delle bobine magnetiche. Il campo magnetico risultante potrebbe interferire con altri dispositivi se non viene corretto. Fine controllo.}
{104}{}{[FATTO]}
{105}{}{Vedi un computer}
{106}{}{Vedi il Computer di Archiviazione Dati dell'EPA.}
{107}{}{Vedi un computer che garantisce che i dati siano archiviati correttamente e in sicurezza nell'EPA.}
{108}{}{Capito!}
{109}{}{Il problema della bobina magnetica e' stato risolto.}
{1030}{}{Controllo in esecuzione... Avvio... Compilazione... Grazie per la pazienza durante questa procedura... Completato. L'archiviazione dati funziona al 100% di efficienza. Grazie e buona giornata. Fine controllo.}
