{100}{}{Il generatore ha una scheda di circuito danneggiata. Forse potresti recuperare pezzi di ricambio da qualche rottame.}
{101}{}{Vedi un generatore.}
{102}{}{Vedi un generatore d'illuminazione dell'EPA.}
{103}{}{Vedi un generatore che controlla l'illuminazione dell'EPA.}
{104}{}{Dopo una lunga ricerca, viene trovata una scheda di circuito con alcune parti danneggiate. Forse, trovando dei rottami da cui recuperare materiale, si potrebbero ottenere pezzi di ricambio.}
{105}{}{Ecco il problema!}
{106}{}{Le parti rotte sono state riparate e il generatore e' tornato online.}
{107}{}{Non riesci a trovare nulla che non vada nel generatore. Sembra semplicemente non funzionare.}
{108}{}{Funziona. Non c'e' altro da fare.}
{109}{}{Qualcosa non sembra andare bene con questo generatore.}
{200}{}{*whirr*}
{201}{}{*bzzt*}
