{100}{}{Il generatore ha una scheda di circuito danneggiata. Forse potresti recuperare pezzi di ricambio da qualche rottame.}
{101}{}{You see a generator.}
{102}{}{You see an EPA lighting generator.}
{103}{}{Vedi un generatore che controlla l'illuminazione dell'EPA.}
{104}{}{Dopo una lunga ricerca, viene trovata una scheda di circuito con alcune parti danneggiate. Forse, trovando dei rottami da cui recuperare materiale, si potrebbero ottenere pezzi di ricambio.}
{105}{}{There's the problem!}
{106}{}{Le parti rotte sono state riparate e il generatore e' tornato online.}
{107}{}{Nothing wrong can be found with the generator. It just doesn't seem work.}
{108}{}{It's working. There's nothing else to do.}
{109}{}{Something doesn't seem right with this generator.}
{200}{}{*whirr*}
{201}{}{*bzzt*}
