{100}{}{You see a pamphlet.}
{101}{}{}
{102}{}{Questo e' un opuscolo introduttivo distribuito all'inizio delle visite guidate.}
{200}{}{Benvenuto all'EPA! Durante la visita della nostra struttura, non allarmarti alla vista di persone traslucide
 che vagano per i corridoi. Non sono fantasmi -- sono il nostro amichevole nuovo personale di ologrammi! Considerali come programmi informatici
 a cui e' stata data forma umana grazie alla magia e alle meraviglie della scienza! Saranno felici di rispondere a qualsiasi domanda tu possa avere,
 quindi non esitare ad avvicinarti. ATTENZIONE! Gli ologrammi esistono grazie a un cristallo sospeso con proprieta' antigravitazionali.
 Questi possono essere altamente instabili se manomessi, quindi, per la tua sicurezza, non tentare di toccare
 nessuno degli ologrammi. Grazie e buona visita!}
{201}{}{END}
{202}{}{You need to take this out of inventory first.}
