{100}{}{Ciao, benvenuto all'Environmental Protection Agency, comunemente chiamata EPA! Per tua comodita',
 questo terminale ti fornira' descrizioni delle varie aree codificate a colori che compongono la nostra splendida struttura
 di ricerca. Seleziona un livello di cui desideri maggiori informazioni.}
{101}{}{SOTTO-LIVELLO ARANCIONE}
{102}{}{SOTTO-LIVELLO ROSSO}
{103}{}{SOTTO-LIVELLO GIALLO}
{104}{}{SOTTO-LIVELLO INDACO}
{105}{}{SOTTO-LIVELLO VIOLA}
{106}{}{SOTTO-LIVELLO VERDE}
{107}{}{SOTTO-LIVELLO BLU}
{108}{}{Il Sotto-livello Arancione contiene le sale conferenze dove vengono prese tutte le decisioni importanti, una mensa dove viene servito cibo delizioso e alcune sostanze chimiche pericolose.}
{109}{}{Il Sotto-livello Rosso ospita il nostro reparto di sicurezza (quindi comportati bene!) e un piccolo ma informativo museo. Inoltre, non dimenticare di comprare qualche snack e di visitare la camera di esecuzione pubblica! [Avvertenza: La camera di esecuzione potrebbe non essere adatta ai bambini sotto i quattro anni.]}
{110}{}{Il Sotto-livello Giallo ospita le sale di alimentazione dei nostri incredibili nuovi ologrammi, ed e' anche dove troverai l'elettrodomestico preferito da tutti per creare droghe, Mr. Chemmie! [Nota: A causa dello spazio limitato, abbiamo spostato alcune sostanze pericolose in quest'area, quindi fai attenzione a dove metti i piedi!]}
{111}{}{Il Sotto-livello Indaco e' dove i nostri brillanti scienziati stanno conducendo ricerche Top Secret! Sembra emozionante, vero? Ricorda, qualsiasi visitatore non autorizzato trovato a questo livello verra' colpito a vista. Quindi, genitori, non lasciate che i vostri figli vaghino senza supervisione.}
{112}{}{Il Sotto-livello Viola contiene il nucleo di memoria per l'archiviazione dei dati dell'EPA e altre cose che non sono molto interessanti per i visitatori. Scusa! Tuttavia, e' collegato direttamente al Sotto-livello Giallo, che contiene cose piu' interessanti, come il farmacista del futuro, Mr. Chemmie!}
{113}{}{Il Sotto-livello Verde e' un livello entusiasmante che contiene un arboreto, ricerche sulle armi biologiche, nuove creature affascinanti e, il preferito di ogni bambino, il nostro esclusivo zoo tattile.}
{114}{}{Il Sotto-livello Blu non esiste. Se qualcuno ti ha detto il contrario, e' un bugiardo e con ogni probabilita' un simpatizzante comunista. Segnalalo al nostro reparto di sicurezza al Sotto-livello Rosso cosi' potra' essere trattato di conseguenza. Grazie per aver fatto la tua parte da orgoglioso americano!}
{115}{}{Torna al menu principale.}
{116}{}{Grazie per aver utilizzato il localizzatore.}
{117}{}{[FATTO]}
{118}{}{Vedi un computer.}
{119}{}{Vedi il Localizzatore dell'EPA.}
{120}{}{Vedi un computer con informazioni dettagliate sui livelli dell'EPA.}
