{100}{}{Vedi un computer.}
{150}{}{Please select an option below.}
{151}{}{Information}
{152}{}{Employee Access}
{160}{}{Please select an option below.}
{161}{}{Lower Force Field}
{162}{}{[INDIETRO]}
{170}{}{Per abbassare i campi di forza, inserisci la password di accesso. (Se la password e' stata persa o dimenticata, rivolgiti all'Ologramma 40011, Direttore delle Pubbliche Relazioni.)}
{171}{}{ABRE}
{172}{}{[INDIETRO]}
{180}{}{Thank you. Force fields are now disengaged.}
{181}{}{[FATTO]}
{200}{}{Benvenuto nello Zoo Tattile dell'EPA! Qui avrai il piacere di interagire con queste creature uniche che
 sembrano esseri umani orribilmente deformati! Questo perche' queste bestie sono il risultato di entusiasmanti esperimenti in cui i nostri
 brillanti scienziati stanno tentando di unire DNA umano e animale!}
{201}{}{[AVANTI]}
{210}{}{In teoria, questa nuova scienza potrebbe un giorno permetterci di creare una "Super Persona". Immagina un Soldato Americano con la vista
 di un'aquila, la velocita' di un ghepardo e la forza di un gorilla! Immagina come questo "Super Soldato" incuterebbe timore
 nei cuori dei comunisti! Sembra fantascienza, ma potrebbe presto diventare realta' scientifica!}
{211}{}{[AVANTI]}
{220}{}{Le creature che vedi qui sono il risultato di esperimenti che non hanno avuto pieno successo. Invece di sopprimere
 queste abominazioni fallite, abbiamo pensato che sarebbe stato divertente metterle in uno zoo tattile. Non preoccuparti, nonostante il loro aspetto terrificante,
 e' improbabile che attacchino finche' sono ben nutrite. Siamo lieti di riportare che solo tre visitatori sono rimasti uccisi
 nell'ultimo anno!}
{221}{}{[Logoff.]}
{300}{}{Benvenuto nella nostra nuova esposizione! Le strane creature tentacolate che vedi in questa gabbia potrebbero sembrare venute
 dallo spazio, ma non sono alieni: in realta' sono state create proprio qui in America! Come avrai intuito,
 non sono state create da madre natura, ma dalla scienza!}
{301}{}{[AVANTI]}
{310}{}{Esatto, queste spaventose mostruosita' sono state create dagli scienziati americani in laboratori top secret,
 come nuova arma nella guerra per la liberta'. I loro potenti tentacoli e i denti affilati sono stati progettati apposta per fare a pezzi
 i nemici dell'America. I tentacoli sono anche eccellenti nello scavare, quindi i comunisti non saranno al sicuro nemmeno nei loro bunker
 sotterranei! Inoltre, questi feroci assassini hanno una pelle cosi' spessa che i proiettili fanno fatica a penetrarla!}
{311}{}{[AVANTI]}
{320}{}{Stai osservando il futuro della guerra biologica! Ma non preoccuparti, queste feroci macchine da macello non possono
 raggiungerti, perche' sono rinchiuse in sicurezza nella loro gabbia altamente protetta. Scusa la scarsa illuminazione,
 ma questi tipi sono piu' felici quando vivono in luoghi freschi e bui, e non vorresti farli arrabbiare, vero?}
{321}{}{[Logoff.]}
{400}{}{Qui puoi vedere forme di vita vegetale come non ne hai mai viste! Questa nuova ed entusiasmante specie, derivata dalla Venere
 acchiappamosche, e' stata progettata dai nostri brillanti scienziati per sopravvivere in un mondo devastato da una guerra nucleare.
 Perche' vorremmo farlo? E' semplice.}
{401}{}{[AVANTI]}
{410}{}{Dopo una guerra nucleare globale, gli scienziati credono che gran parte della Terra diventera' una landa desolata. La vita vegetale
 avra' enormi difficolta' a sopravvivere in questo nuovo ambiente ostile. Ora immagina di uscire dai nostri vault Vault-Tec
 solo per scoprire che tutte le piante sono morte! Vorrebbe dire niente piu' insalate per mamma, e niente piu' prati dove
 Billy e Rover possano giocare a riportare la palla.}
{411}{}{[AVANTI]}
{420}{}{Sembra terribile, vero? Ma non preoccuparti. Queste nuove piante potrebbero essere la risposta al problema. Invece di
 dipendere dal suolo fertile e dalla pioggia, sono in grado di ottenere nutrienti uccidendo e mangiando animali, proprio come
 le persone! Tutto grazie alle meraviglie della scienza!}
{421}{}{[Logoff.]}
