{100}{}{Vedi una macchina peculiare.}
{101}{}{Vedi il proiettore di backup dell'Ologramma 00000.}
{102}{}{Vedi una macchina che proietta esclusivamente l'Ologramma della Scienza.}
{103}{}{Il guasto nella macchina e' stato riparato.}
{104}{}{Questa macchina funziona gia' bene.}
{105}{}{Riparare questa macchina sembra troppo complicato.}
{106}{}{Cosa sto cercando qui?}
{107}{}{Anche con i tuoi strumenti, non hai le capacita' necessarie per riparare questa macchina.}
