{100}{}{You see a modified Auto-Doc.}
{101}{}{Questo Auto-Doc sembra essere stato modificato per eseguire cambiamenti sperimentali dell'aspetto.}
{200}{}{[La macchina ti parla mentre ti avvicini.] Benvenuto, Soggetto di Test. Grazie per aver offerto la tua carne
 alla scienza. Per favore, entra dentro di me e possiamo iniziare.}
{201}{}{Ehi, non ho mai detto di voler offrire niente. Prima di fare un passo, perche' non mi dici esattamente cosa fai?}
{202}{}{[Scrollata di spalle.] Va bene. [Entri nel dispositivo.]}
{203}{}{Mi hai confuso con qualcun altro. Ciao.}
{300}{}{Bentornato, Soggetto di Test. Per favore, entra dentro di me e possiamo iniziare.}
{301}{}{Before I step anywhere, why don't you tell me exactly what you do?}
{302}{}{Alright. [Step into the device.]}
{303}{}{I don't think so. Bye.}
{400}{}{Sono il prototipo piu' recente della tecnologia Auto-Doc, sviluppato dal Dr. Wood. Sono specializzato in modifiche
 estreme del corpo -- il restyling definitivo. Non c'e' bisogno di essere nervosi, il mio tasso di mortalita' dei pazienti e' significativamente piu' basso
 rispetto al prototipo precedente. Non essere timido, entra dentro di me e possiamo iniziare.}
{401}{}{You're not touching me. Bye.}
{402}{}{I'd love to, but I really need to get going. Sorry.}
{403}{}{Alright. [Step into the device.]}
{410}{}{Per favore, effettua la tua scelta. Essendo un prototipo iniziale, posso offrirti solo opzioni limitate. Mi dispiace.}
{411}{}{Alter Gender.}
{412}{}{Alter Race. (Currently only White to African American or vice versa).}
{413}{}{Alter Hairstyle (Regular Hair).}
{414}{}{Alter Hairstyle (Long Hair).}
{415}{}{Alter Hairstyle (Bald).}
{416}{}{Alter Hairstyle (Blond Hair).}
{417}{}{Alter Hairstyle (Red Hair).}
{418}{}{On second thought, I don't really have time for this right now. Bye.}
{500}{}{This procedure will take four weeks for you to recover and has a 50% chance of death. Do you wish to begin now?}
{501}{}{Cominciamo.}
{502}{}{Yes. Finally, I can be the person I've always been on the inside.}
{503}{}{Eh, maybe later. Bye.}
{504}{}{Let me choose another procedure.}
{505}{}{Hell no! I'm outta here!}
{510}{}{Excellent choice. This procedure will take two weeks for you to recover and has a 25% chance of death. Do you wish to begin now?}
{511}{}{Cominciamo.}
{512}{}{Yes. Finally, I can be the person I've always been on the inside.}
{513}{}{Eh, maybe later. Bye.}
{514}{}{Let me choose another procedure.}
{515}{}{Hell no! I'm outta here!}
{520}{}{Excellent choice. This procedure will take one day for you to recover and has a 1% chance of death. Do you wish to begin now?}
{521}{}{Cominciamo.}
{522}{}{Yes. Finally, I can be the person I've always been on the inside.}
{523}{}{Eh, maybe later. Bye.}
{524}{}{Let me choose another procedure.}
{525}{}{Hell no! I'm outta here!}
{600}{}{Congratulations! The experiment was a success. Thank you, and enjoy the new you.}
{601}{}{[Exit.]}
{650}{}{I'm sorry, this particular procedure is not currently available for females.}
{700}{}{I'm sorry, but something went terribly wrong with the procedure. We apologize for this inconvenience, but thank
 you for volunteering for the sake of science.}
{701}{}{Oh, merda...}
