{100}{}{Vedi una porta.}
{101}{}{You see an electronic door.}
{102}{}{You see an electronic door with an override, voice activated, lock.}
{200}{}{Conferma il codice:}
{201}{}{XY104FD}
{202}{}{BFN12}
{203}{}{Apri}
{204}{}{Wheat}
{205}{}{Abre}
{206}{}{[FINE]}
{300}{}{Codice della porta errato. Blocco della porta in corso. Contatta il capo delle Pubbliche Relazioni per il codice di sblocco.}
{301}{}{[FINE]}
{400}{}{Conferma il codice di sblocco.}
{401}{}{[FINE]}
{402}{}{This door is electronically locked.}
{403}{}{Sblocco della porta in corso. Grazie e buona giornata.}
{404}{}{[FINE]}
{500}{}{There is no lock to pick.}
