{100}{}{Vedi una macchina peculiare.}
{101}{}{La macchina che controlla la proiezione dell'ologramma in questa stanza.}
{103}{}{Un guasto nella macchina viene individuato e riparato rapidamente.}
{104}{}{Questa macchina e' gia' stata riparata.}
{105}{}{Sembra che ci fosse un'interferenza che rendeva incomprensibile la voce dell'ologramma.}
{106}{}{Riparare questa macchina sembra troppo complicato.}
{107}{}{Cosa sto cercando qui?}
{108}{}{Maledizione. E' troppo difficile per me. Le riparazioni non sono il mio forte.}
{109}{}{Maledizione, anche con questi strumenti e' troppo difficile per me. Le riparazioni non sono il mio forte.}
