{200}{}{Se ci legassi una corda, probabilmente potrei calarmi laggiu'.}
{201}{}{Della corda sarebbe sicuramente utile qui.}
{300}{}{Questo dovrebbe bastare.}
{301}{}{I already placed the rope.}
{302}{}{Lighi la corda a una delle sbarre della grata e lasci cadere il resto. Senti un tonfo quando raggiunge
 il fondo.}
{400}{}{Entri in uno dei condotti di ventilazione dell'EPA. Senti vari insetti che si muovono rapidamente.}
