{100}{}{Vedi un computer funzionante.}
{101}{}{Vedi il terminale di botanica dell'EPA.}
{200}{}{Benvenuto nel terminale di botanica dell'EPA. Seleziona una delle seguenti opzioni.}
{201}{}{Accedi al database informazioni.}
{202}{}{Accedi al deposito sementi.}
{203}{}{Esci.}
{210}{}{Attualmente sono disponibili due database da consultare. Effettua la tua scelta qui sotto.}
{211}{}{Accedi al file sulla rotazione delle colture.}
{212}{}{Accedi al file di botanica.}
{213}{}{Accedi al file sui test animali e biologici.}
{214}{}{Indietro.}
{220}{}{La rotazione delle colture evita la diminuzione della fertilita' del suolo, poiche' coltivare ripetutamente la stessa pianta nello stesso punto
 finisce per impoverire il terreno di vari nutrienti. Una coltura che sottrae un certo tipo di nutriente viene seguita,
 nella stagione successiva, da una coltura diversa che restituisce quel nutriente al suolo o assorbe un rapporto differente
 di sostanze nutritive.}
{221}{}{[AVANTI]}
{222}{}{La rotazione delle colture serve anche a controllare parassiti e malattie che possono stabilirsi nel terreno nel tempo.
 Le piante della stessa famiglia tendono ad avere parassiti e agenti patogeni simili. Cambiando regolarmente il luogo di semina,
 i cicli dei parassiti possono essere interrotti o limitati.}
{223}{}{Indietro.}
{230}{}{La botanica e' lo studio scientifico della vita vegetale. Come per altre forme di vita in biologia, le piante possono essere studiate
 da diverse prospettive, da quella molecolare fino ai singoli organismi. Una buona comprensione delle piante e' fondamentale per il nostro futuro, poiche' ci permette di:

 -Produrre cibo per nutrire una popolazione in crescita.
 -Comprendere i processi vitali fondamentali.
 -Produrre medicine e materiali per trattare malattie e disturbi.
 -Comprendere piu' chiaramente i cambiamenti ambientali.

 Il resto delle informazioni consiste in vari grafici, tabelle e immagini di sezioni trasversali di piante.}
{231}{}{Scarica le informazioni su un olodisco.}
{232}{}{Indietro.}
{240}{}{Questa struttura e' stata il luogo di vari esperimenti su diverse forme di vita animali e vegetali. Sono stati condotti test approfonditi
 su una forma di vita simile a una pianta chiamata pianta delle spore e su alcune creature simili ad animali note come Centauri, Fluttuanti e Radscorpioni.}
{241}{}{Leggi sugli esperimenti botanici.}
{242}{}{Leggi sulle Piante Sporigene.}
{243}{}{Leggi sui Centauri e i Fluttuanti.}
{244}{}{Leggi sugli Scorpioni Radioattivi.}
{250}{}{Sono stati condotti vari esperimenti per far crescere nuove forme di vita vegetale. Diversi di questi tentativi hanno avuto successo
 e ora possono essere visti crescere in buone condizioni nell'arboreto. I serbatoi di stoccaggio indicano che sono ancora disponibili campioni di semi per ulteriori test.}
{251}{}{La pianta delle spore e' una forma mutata di una pianta simile a una Venere acchiappamosche. Ulteriori test hanno mostrato che la pianta e' piuttosto
 aggressiva e possiede due modalita' di attacco. Una consiste nello sputare spore contro i nemici. L'altra e' un morso con la sua bocca spinosa.
 Si consiglia grande cautela quando si maneggiano o si studiano queste forme di vita.}
{252}{}{Dopo test approfonditi, i Centauri sembrano essere un sottoprodotto del Virus dell'Evoluzione Forzata. Sembrano essere
 un miscuglio di cane, gatto, brahmin e altri animali. Tuttavia, il FEV non e' l'unica causa della mutazione, poiche' anche le radiazioni
 sembrano aver avuto un ruolo. Sembrano preferire ambienti fortemente irradiati e, di conseguenza, irradiano tutto cio' che li circonda.}
{253}{}{[AVANTI]}
{254}{}{L'origine e l'etimologia dei Fluttuanti sono sconosciute, ma si ritiene che siano imparentati con i Centauri, con cui vengono spesso trovati.
 Anche loro sembrano essere il risultato del FEV. Ulteriori test hanno mostrato che sono completamente immuni ai danni elettrici.}
{255}{}{I Radscorpioni sono una versione estremamente grande dello scorpione Imperatore nordamericano, mutato dalle radiazioni.
 Contrariamente alle aspettative iniziali, il loro veleno e' diventato piu' potente, non diluito. Sono notturni e sensibili alla luce.
 Ulteriori test hanno mostrato che campioni di veleno dalle loro code possono essere usati per creare antidoti.}
{256}{}{Indietro.}
{257}{}{Sono stati condotti vari esperimenti per far crescere nuove forme di vita vegetale. Diversi di questi tentativi hanno avuto successo
 e ora possono essere visti crescere in buone condizioni nell'arboreto. I serbatoi di stoccaggio indicano che non ci sono piu' campioni di semi disponibili per ulteriori test.}
{260}{}{I contenitori di stoccaggio dell'EPA indicano che ci sono ancora semi nei Serbatoi Uno e Due.}
{261}{}{I contenitori di stoccaggio dell'EPA indicano che ci sono ancora semi nel Serbatoio Due.}
{262}{}{I contenitori di stoccaggio dell'EPA indicano che ci sono ancora semi nel Serbatoio Uno.}
{263}{}{I contenitori di stoccaggio dell'EPA riportano che non ci sono piu' semi in nessuno dei Serbatoi.}
{264}{}{Accedi al Serbatoio di Stoccaggio Uno.}
{265}{}{Accedi al Serbatoio Due.}
{266}{}{Indietro.}
{270}{}{Il Serbatoio Uno riporta 5 pacchetti rimanenti dal Programma di Potenziamento Alimentare degli Stati Uniti. I semi di mais sono stati geneticamente modificati
 per essere immuni a malattie e infestazioni di insetti.}
{271}{}{Il Serbatoio Due riporta 2 pacchetti di semi rimanenti, ciascuno di famiglie simili o differenti. Non e' stata condotta alcuna ricerca e l'esito della germinazione e' sconosciuto.}
{273}{}{Recupera i semi.}
{280}{}{Raccolta dei campioni di semi... Raccolti con successo 5 pacchetti di semi di mais geneticamente modificati. Deposito dei pacchetti nel contenitore di raccolta... Successo...
 Chiusura del contenitore di stoccaggio... Successo.}
{281}{}{Raccolta dei campioni di semi... Raccolti con successo 2 pacchetti di semi sconosciuti. Deposito dei pacchetti nel contenitore di raccolta... Successo...
 Chiusura del contenitore di stoccaggio... Successo.}
{290}{}{Download del database di Botanica su un olodisco... 75% completato... Terminato. Rimuovi il disco e torna al menu.}
{291}{}{Indietro.}
