{100}{}{Questa porta e' chiusa a chiave.}
{101}{}{Vedi una porta chiusa a chiave, che impedisce qualsiasi ulteriore accesso.}
{102}{}{Vedi una porta dall'aspetto robusto.}
{103}{}{La porta e' ora sbloccata.}
{104}{}{Questa porta e' gia' sbloccata e aperta.}
{105}{}{Non riesci a sbloccare la porta.}
{106}{}{La serratura si e' inceppata.}
{107}{}{La porta e' ora chiusa a chiave.}
{108}{}{Non riesci a chiudere a chiave la porta.}
