{100}{}{Computer di Controllo delle Camere di Ibernazione. Seleziona un'opzione.}
{101}{}{Subject history.}
{102}{}{Retrieve a test subject.}
{103}{}{[FATTO]}
{104}{}{Camere di Ibernazione. Tre individui sono stati sigillati in queste camere prima della guerra, ciascuno per motivi
 classificati. I soggetti restano sigillati e ignari dell'ambiente circostante. Sono disponibili registri per ogni soggetto.}
{105}{}{Return to Main Menu.}
{106}{}{ATTENZIONE: Periodi prolungati in un ambiente di congelamento profondo alterano i processi chimici del corpo.
 Senza la corretta applicazione di sostanze chimiche al corpo del soggetto all'uscita dalle camere, potrebbero soffrire di ERS
 (Sindrome da Rigetto Ambientale). Per garantire la sicurezza del soggetto, si raccomanda vivamente di inserire un contenitore ERSI
 (Inibitore della Sindrome da Rigetto Ambientale) nel distributore prima di procedere.}
{107}{}{Oh, fantastico. Ho appena svegliato un mucchio di ossa.}
{108}{}{No, return to Main Menu.}
{109}{}{Retrieving test subject.}
{110}{}{Retrieving test subject.}
{111}{}{Retrieving test subject.}
{112}{}{Thank you for using the Hibernation Control Computer.}
{113}{}{You see a large computer.}
{114}{}{You see The Hibernation Control Computer.}
{115}{}{Vedi un computer usato per regolare tutto cio' che riguarda le Vasche di Ibernazione.}
{116}{}{Inserisci il contenitore ERSI nel distributore.}
{117}{}{Proceed anyway.}
{118}{}{Gli Inibitori della Sindrome da Rigetto Ambientale sono stati applicati con successo al soggetto. Il battito cardiaco del soggetto appare normale. Per favore,
 procedi alla camera criogenica per il recupero.}
{119}{}{ATTENZIONE: Nessun Inibitore della Sindrome da Rigetto Ambientale e' stato applicato al soggetto. Lo stato del soggetto e' sconosciuto. Per favore,
 procedi alla camera criogenica per il recupero.}
{120}{}{Hmm, forse dovrei vedere se riesco a trovare uno di questi contenitori ERSI. Ci sara' sicuramente un posto qui intorno dove prendere quelle sostanze...}
{200}{}{Read log entries.}
{210}{}{Please choose a subject.}
{211}{}{Soggetto A.}
{212}{}{Soggetto B.}
{213}{}{Soggetto C.}
{214}{}{Indietro.}
{220}{}{Registro #87983: E' finalmente successo. Hanno lanciato i loro missili nucleari contro di noi e noi abbiamo lanciato i nostri contro di loro.
 I superiori non vogliono entrare nei dettagli, ma probabilmente e' gia' il Giorno del Giudizio lassu'. Le comunicazioni radio sono state interrotte
 a tempo indeterminato. Per fortuna mi sono abituato a questo posto. Non ho alcuna illusione di rivedere mai piu' la superficie.}
{221}{}{[AVANTI]}
{222}{}{Hanno portato una donna da ibernare. Non hanno detto perche'; solo che era una questione top secret. Era davvero notevole.
 Minute, con tratti cinesi, e c'era qualcosa nei suoi occhi. Ha messo al tappeto due agenti dei servizi segreti quando ha scoperto
 cosa avevamo in mente. Li ha colti di sorpresa e li ha aperti entrambi con uno dei bisturi di Delnay, Cristo santo. Una scena incredibile.
 Il terzo e' riuscito a immobilizzarla. Non e' che avrebbe passato il resto della vita qui sotto anche se li avesse uccisi tutti, comunque.
 Ora e' incosciente e stanno preparando la sua vasca. E' proprio accanto a quella di quel psicopatico di Patrick, tra l'altro. Che peccato.
 Mi sarebbe piaciuto conoscerla meglio.
 -Dr. David Kimble, 23/10/2077}
{230}{}{Registro #81977: Dexter "Dex" Patrick e' uno specimen piuttosto interessante. E' un assassino sociopatico, narcisista e misogino,
 noto per occasionali episodi di necrofilia e cannibalismo. E' freddo fino all'estremo, senza alcun rimorso per le sue vittime,
 che andavano da bambini innocenti ad anziani e disabili. I suoi bersagli preferiti erano giovani donne attraenti, che di solito
 seduceva prima di ucciderle brutalmente.}
{231}{}{[AVANTI]}
{232}{}{Nonostante il suo comportamento antisociale, rimane sorprendentemente socievole, persino affascinante. Infatti, diverse
 membri del personale femminile sembrano esserne attratte, pur conoscendo le numerose atrocita' che ha commesso. Le vittime
 confermate di Dex sono attualmente 68, anche se lui ha vantato che il numero reale supera ampiamente le tre cifre.
 Sebbene Dex si sia dimostrato un bugiardo compulsivo, trovo comunque difficile dubitare della veridicita' della sua affermazione.}
{233}{}{[AVANTI]}
{234}{}{L'unico legame emotivo che Dex sembra avere e' verso un idolo rock 'n roll della meta' del XX secolo, che ammira
 come modello e forse persino come figura paterna. Ha inoltre mostrato un attaccamento malsano a un orecchio umano reciso,
 che abbiamo identificato come appartenente a Vicky Safron, la fidanzatina del liceo di Dex e una delle sue prime vittime.
 Afferma di tenere l'orecchio in tasca cosi' Vicky puo' sentire le urla di tutte le sue vittime.}
{235}{}{[AVANTI]}
{236}{}{Ho deciso di far ibernare Dexter per il momento, poiche' il governo ha dirottato i fondi lontano dal nostro
 progetto per sostenere ulteriormente lo sforzo bellico, e il mio team sta venendo riassegnato ad altre sedi. Sia chiaro
 che considero questo un grave errore, poiche' i nostri studi sulla natura del male umano stanno avanzando rapidamente e credo
 siamo vicini a una scoperta importante che sarebbe molto piu' utile al nostro governo della produzione di altre "armature di latta".
 Ma sto divagando.}
{237}{}{[AVANTI]}
{238}{}{Dex restera' ibernato qui finche' chi comanda non rinsavira' e non riportera' in vita questo progetto di enorme
 importanza. Spero solo di essere ancora vivo per riprendere il mio lavoro quando quel giorno arrivera'.
 -Dr. Dustin C. Delnay, 13/04/2075}
{240}{}{Registro #80052: Il Sergente Christopher "Cat" Jules e' stato assegnato al reparto di sicurezza militare dell'EPA il 17/02/2074.
 Prima di questo, era parte di un'unita' di ricognizione della 205a Aviotrasportata. Il Sergente ha un impressionante record di combattimento
 ed e' uno dei migliori specialisti del suo reparto nelle armi energetiche e nel combattimento disarmato. Tuttavia, questi risultati sono
 offuscati da una lunga storia di accuse per piccoli furti, ripetute infrazioni per uniforme non regolamentare e un atteggiamento
 di estrema arroganza verso i superiori.}
{241}{}{[AVANTI]}
{242}{}{Il Sgt. Jules e' stato reclutato come soggetto di prova per il Progetto di Potenziamento dei Riflessi Umani il 10/05/2075, in cambio della rimozione
 di alcune di queste segnalazioni dal suo fascicolo. Sono sorte complicazioni durante il primo test e il Sgt. Jules e' stato sedato per la sicurezza
 sua e di chi gli stava intorno.}
{243}{}{[AVANTI]}
{244}{}{Sono passati alcuni giorni e il Sgt. Jules sembra in buona salute, ma ha sviluppato canini allungati e
 alcune caratteristiche eccentriche oltre agli obiettivi del progetto, cioe' riflessi migliorati e capacita' sensoriali aumentate.
 Ho inviato diversi rapporti al Comandante della base chiedendo ulteriori fondi, ma purtroppo sembra che ci siano persone che non
 desiderano che il mio progetto continui. E' un vero peccato, poiche' i campioni di tessuto e i rapporti psicologici del Sgt. Jules indicano
 solo lievi deformazioni e una tendenza a un'attenzione leggermente ridotta. A parte questo, e' perfettamente idoneo
 al servizio e, anzi, probabilmente piu' capace di prima grazie al trattamento. Finche' non arriveranno nuovi fondi
 per questo progetto, il Sgt. Jules restera' in animazione sospesa.
 -Dr. R.D. Crichton, 11/04/2075}
{300}{}{Scegli un argomento:}
{301}{}{Sergente Christopher "Cat" Jules}
{302}{}{Dexter "Dex" Patrick}
{303}{}{Kitsune}
