{100}{}{Postazione Computer della Sedia Elettrica: Seleziona un'opzione.}
{101}{}{Attiva la Sedia Elettrica.}
{102}{}{Disattiva la Sedia Elettrica.}
{103}{}{Sedia attivata. Per favore, incoraggia la persona ad avvicinarsi il piu' possibile alla sedia da entrambi i lati. Grazie.}
{104}{}{Sedia disattivata.}
{105}{}{Esci.}
{106}{}{Vedi un computer che ronza da solo.}
{107}{}{Vedi il Computer della Sedia Elettrica.}
{108}{}{Vedi un computer che controlla la sedia elettrica.}
