{100}{}{Pannello di controllo del campo di forza.}
{200}{}{Riesci a disabilitare il campo di forza.}
{201}{}{Non riesci a disabilitare il campo di forza.}
{202}{}{Riesci ad attivare il campo di forza.}
{203}{}{Non riesci ad attivare il campo di forza.}
{210}{}{ disattiva il campo di forza.}
{211}{}{ non riesce a disabilitare il campo di forza.}
{212}{}{ attiva il campo di forza.}
{213}{}{ non riesce ad attivare il campo di forza.}
{300}{}{Hai distrutto il computer.}
