{100}{}{You see a peculiar machine.}
{101}{}{Vedi il proiettore di backup dell'Ologramma 00000.}
{102}{}{Vedi una macchina che proietta esclusivamente l'Ologramma della Scienza.}
{103}{}{The fault in the machine has been fixed.}
{104}{}{This machine is working fine already.}
{105}{}{Riparare questa macchina sembra troppo complicato.}
{106}{}{What am I looking for here?}
{107}{}{Anche con i tuoi strumenti, non hai le capacita' necessarie per riparare questa macchina.}
