{100}{}{Vedi un Auto-Doc modificato.}
{101}{}{Questo Auto-Doc sembra essere stato modificato per eseguire cambiamenti sperimentali dell'aspetto.}
{200}{}{[La macchina ti parla mentre ti avvicini.] Benvenuto, Soggetto di Test. Grazie per aver offerto la tua carne
 alla scienza. Per favore, entra dentro di me e possiamo iniziare.}
{201}{}{Ehi, non ho mai detto di voler offrire niente. Prima di fare un passo, perche' non mi dici esattamente cosa fai?}
{202}{}{[Scrollata di spalle.] Va bene. [Entri nel dispositivo.]}
{203}{}{Mi hai confuso con qualcun altro. Ciao.}
{300}{}{Bentornato, Soggetto di Test. Per favore, entra dentro di me e possiamo iniziare.}
{301}{}{Prima che vada da qualsiasi parte, perche' non mi dici esattamente cosa fai?}
{302}{}{Bene. [Entra nel dispositivo.]}
{303}{}{Non credo. Arrivederci.}
{400}{}{Sono il prototipo piu' recente della tecnologia Auto-Doc, sviluppato dal Dr. Wood. Sono specializzato in modifiche
 estreme del corpo -- il restyling definitivo. Non c'e' bisogno di essere nervosi, il mio tasso di mortalita' dei pazienti e' significativamente piu' basso
 rispetto al prototipo precedente. Non essere timido, entra dentro di me e possiamo iniziare.}
{401}{}{Non mi tocchi. Arrivederci.}
{402}{}{Mi piacerebbe, ma devo proprio andare. Mi dispiace.}
{403}{}{Bene. [Entra nel dispositivo.]}
{410}{}{Per favore, effettua la tua scelta. Essendo un prototipo iniziale, posso offrirti solo opzioni limitate. Mi dispiace.}
{411}{}{Modifica Sesso.}
{412}{}{Modifica Razza. (Attualmente solo da Caucasico a Afroamericano o viceversa).}
{413}{}{Modifica Acconciatura (Capelli Normali).}
{414}{}{Modifica Acconciatura (Capelli Lunghi).}
{415}{}{Modifica Acconciatura (Calvo).}
{416}{}{Modifica Acconciatura (Capelli Biondi).}
{417}{}{Modifica Acconciatura (Capelli Rossi).}
{418}{}{Ripensandoci, non ho davvero tempo per questo adesso. Arrivederci.}
{500}{}{Questa procedura richiedera' quattro settimane di recupero e ha una probabilita' di morte del 50%. Vuoi iniziare ora?}
{501}{}{Cominciamo.}
{502}{}{Si. Finalmente posso essere la persona che sono sempre stato dentro.}
{503}{}{Beh, magari piu' tardi. Arrivederci.}
{504}{}{Lasciami scegliere un'altra procedura.}
{505}{}{Neanche per sogno! Me la squaglio!}
{510}{}{Ottima scelta. Questa procedura richiedera' due settimane di recupero e ha una probabilita' di morte del 25%. Vuoi iniziare ora?}
{511}{}{Cominciamo.}
{512}{}{Si. Finalmente posso essere la persona che sono sempre stato dentro.}
{513}{}{Beh, magari piu' tardi. Arrivederci.}
{514}{}{Lasciami scegliere un'altra procedura.}
{515}{}{Neanche per sogno! Me la squaglio!}
{520}{}{Ottima scelta. Questa procedura richiedera' un giorno di recupero e ha una probabilita' di morte dell'1%. Vuoi iniziare ora?}
{521}{}{Cominciamo.}
{522}{}{Si. Finalmente posso essere la persona che sono sempre stato dentro.}
{523}{}{Beh, magari piu' tardi. Arrivederci.}
{524}{}{Lasciami scegliere un'altra procedura.}
{525}{}{Neanche per sogno! Me la squaglio!}
{600}{}{Congratulazioni! L'esperimento e' stato un successo. Grazie, e goditi il tuo nuovo te stesso.}
{601}{}{[Esci.]}
{650}{}{Mi dispiace, questa procedura non e' attualmente disponibile per soggetti femminili.}
{700}{}{Mi dispiace, ma qualcosa e' andato terribilmente storto durante la procedura. Ci scusiamo per l'inconveniente, ma grazie
 per esserti offerto volontario per il bene della scienza.}
{701}{}{Oh, merda...}
