{100}{}{Vedi un computer.}
{101}{}{Vedi il computer del museo dell'EPA.}
{200}{}{Benvenuto nel museo dell'EPA! Questo terminale proiettera' un film utilizzando una nuova ed entusiasmante tecnologia olografica!
 Il film offre una visione divertente e informativa della spaventosa, ma possibile, realta' di un mondo post-nucleare.}
{201}{}{[Riproduci filmato.]}
{202}{}{[Disconnetti.]}
{210}{}{[Il terminale proietta l'ologramma di un uomo alto, con occhiali e camice da laboratorio. Ti saluta con un sorriso cordiale.]
 Salve, sono il Dr. Caleb, e saro' la guida di questo video olografico sull'America post-olocausto.}
{211}{}{[AVANTI]}
{220}{}{[Attorno al Dr. Caleb si materializza un soggiorno, dove una famiglia sembra rilassarsi per la serata. Il Dr. Caleb
 accarezza il cane di famiglia, poi ti sorride.] Ti presento i Johnson. Sono la tipica famiglia americana. Papa' fuma
 la pipa, mamma legge il suo libro di cucina, e i piccoli Billy e Susie guardano un po' di televisione prima di andare a letto. Pensano che
 andra' tutto bene. Ignorano le sirene d'allarme, convinti che sia solo un'altra esercitazione. Oh, ma cos'e' questo?}
{221}{}{[AVANTI]}
{230}{}{[Attraverso la finestra sul retro, vedi una grande bomba schiantarsi al suolo, creando un'enorme esplosione a fungo,
 seguita da una luce accecante. Quando la luce svanisce, il Dr. Caleb si trova tra le rovine bruciate del soggiorno,
 con la famiglia ridotta a scheletri.] Uh-oh! Sembra che i comunisti abbiano sganciato il "botto grosso", e i Johnson
 non erano poi cosi' al sicuro come credevano. Ora, cosa possiamo imparare dall'errore della famiglia Johnson?}
{231}{}{[AVANTI]}
{240}{}{Esatto! In caso di guerra nucleare, vorrai che la tua famiglia sia al sicuro all'interno di un Vault marchiato Vault-Tec.
 Vault-Tec ha costruito 122 vault pubblici in tutta la nostra grande nazione, quindi ce ne sara' sicuramente uno vicino a te.
 Come puoi immaginare, lo spazio e' molto limitato, quindi prenota il tuo posto oggi stesso, altrimenti *la tua* famiglia potrebbe finire come
 i Johnson qui. [Il Dr. Caleb accarezza la testa del cane scheletrico. Il cranio si stacca dal corpo e cade a terra,
 frantumandosi. Un robot Mr. Handy arriva fluttuando e spazza via i frammenti.]}
{241}{}{[AVANTI]}
{250}{}{Sembra che Mr. Handy avra' parecchio lavoro da fare se intende ripulire *questo* disastro. [Il Dr. Caleb
 ride mentre l'immagine svanisce e viene sostituita da del testo.] Grazie per la visione. Questo video educativo e' stato offerto
 dai gentili collaboratori della Vault-Tec. Vault-Tec, l'ultima parola americana in fatto di abitazioni.}
{251}{}{[Disconnetti.]}
