{100}{}{Data Storage and Maintenance. Select Option.}
{101}{}{Run Diagnostic Check.}
{102}{}{[FATTO]}
{103}{}{Controllo in esecuzione... Avvio... Compilazione... Grazie per la pazienza durante questa procedura... Completato. L'archiviazione dati funziona all'84% di efficienza. Un guasto nel cablaggio del mainframe di questo computer sta causando un funzionamento ad alta potenza delle bobine magnetiche. Il campo magnetico risultante potrebbe interferire con altri dispositivi se non viene corretto. Fine controllo.}
{104}{}{[FATTO]}
{105}{}{You see a computer}
{106}{}{You see the EPA Data Storage Computer.}
{107}{}{Vedi un computer che garantisce che i dati siano archiviati correttamente e in sicurezza nell'EPA.}
{108}{}{Got it!}
{109}{}{The magnetic coil problem has been fixed.}
{1030}{}{Controllo in esecuzione... Avvio... Compilazione... Grazie per la pazienza durante questa procedura... Completato. L'archiviazione dati funziona al 100% di efficienza. Grazie e buona giornata. Fine controllo.}
