{100}{}{Vedi un computer funzionante.}
{101}{}{Vedi il Terminale Ricerca e Sviluppo Top Secret dell'EPA.}
{102}{}{Benvenuto nel Terminale Top Secret di Ricerca e Sviluppo dell'EPA. Errore nell'inizializzazione della procedura di accesso rapido. Per favore,
 cerca qualcosa di specifico.}
{103}{}{Cerca qualcosa di importante.}
{104}{}{Esci.}
{105}{}{Dopo 30 minuti passati a setacciare tutti i file, ne trovi quattro che sembrano utili. Per favore, scegli qui sotto.}
{106}{}{Accedi al registro storico del FEV.}
{107}{}{Accedi al file sulla cura dell'epilessia.}
{108}{}{Continua a cercare.}
{109}{}{Scegli un'opzione qui sotto.}
{110}{}{Con l'aumentare delle tensioni tra Stati Uniti e Cina, uno dei timori principali dei nostri ufficiali militari
 era che i cinesi potessero usare armi biologiche contro le truppe americane. Di conseguenza, la West Tek, un importante appaltatore
 della difesa ad alta tecnologia, venne incaricata di sviluppare un agente di contrasto. Questo porto' la West Tek a ricercare il Pan-Immunity Virion
 Project (PVP) con l'intento di creare immunita' nei soldati ristrutturando il loro DNA. Durante i test del PVP nel 2076,
 furono osservati effetti collaterali anomali nei soggetti. Gli animali da test iniziarono a crescere enormemente e la loro attivita' cerebrale
 aumento'.}
{111}{}{[AVANTI]}
{112}{}{Vedendone il potenziale, l'Esercito requisito' rapidamente il progetto e lo rinomino' FEV: Forced Evolutionary Virus.
 Non soddisfatti della sola immunita' alle malattie, il FEV avrebbe potuto trasformare i soldati in "superuomini"
 anormalmente forti e intelligenti. Una volta conclusi i test sugli animali, la ricerca sul FEV venne trasferita nella sua sede attuale,
 la Base Militare di Mariposa. Li', abbiamo appreso che i test passeranno al livello successivo, iniziando esperimenti top
 secret sui prigionieri militari. Attendiamo con entusiasmo i risultati di questi esperimenti.}
{113}{}{Indietro.}
{120}{}{Uno dei nostri ricercatori, il dottor Hodkin, ha fatto una scoperta straordinaria nei suoi studi sul modo in cui il cervello umano
 elabora le risposte verbali. A quanto pare, ripetendo una serie di lettere con le giuste inflessioni, un ascoltatore puo'
 essere curato da numerose malattie neurologiche, come autismo o epilessia. In questo registro e' inclusa la sequenza esatta di lettere
 (e le inflessioni corrette) usate dal dottor Hodkin nei suoi esperimenti. Una notizia meravigliosa e un ottimo inizio per
 ulteriori ricerche sui disturbi neurologici cronici.}
{121}{}{Potrebbe essere utile. Prendi nota della sequenza e cerca qualcos'altro.}
{130}{}{Non trovi nient'altro di interessante.}
{131}{}{Non trovi ancora nient'altro di interessante.}
{132}{}{Forse, cercando un po' di piu', potresti trovare qualcosa?}
{133}{}{Forse un'altra ricerca?}
{134}{}{Dopo una lunga e faticosa ricerca, trovi un file nascosto.}
{135}{}{Accedi al file etichettato: Progetto di Fluorizzazione di Massa.}
{136}{}{Nell'ulteriore tentativo di rendere i cittadini degli Stati Uniti piu' controllabili, l'inclusione di fluoruro
 di sodio in tutta l'acqua potabile disponibile e' immediatamente effettiva. Gli effetti a lungo termine nei test hanno mostrato
 che i soggetti diventavano piu' "stupidi e docili". Inoltre, e' stato osservato che il fluoruro di sodio causava lievi danni
 a una specifica parte del cervello, rendendo piu' difficile per la persona difendere la propria liberta' e portandola
 a diventare piu' docile verso l'autorita'.}
{137}{}{[AVANTI]}
{138}{}{Nella nostra sperimentazione piu' recente, abbiamo scelto come soggetto l'ufficiale militare, Generale J. Ripper. Inizialmente,
 non era consapevole delle nostre intenzioni, ma ora sembra aver capito. E' diventato ossessionato dalla frase "preziosi fluidi
 corporei" ed evita di bere qualsiasi sostanza di cui non conosca l'origine. Ha persino smesso di avere rapporti sessuali,
 temendo che le donne cerchino "l'essenza vitale".}
{139}{}{Indietro.}
{150}{}{Modifica del Sesso.}
{151}{}{Moscerini della frutta carichi di virus.}
{160}{}{Il dottor Glen Wood ha ottenuto una nuova svolta nella sua ricerca sulla modifica del genere, che sostiene rivoluzionera'
 gli sforzi di spionaggio del nostro paese. Con una semplice procedura, un uomo potrebbe diventare una donna, o viceversa.
 Il dottor Wood ha insistito per essere il primo a sottoporsi alla trasformazione radicale. Una volta completata l'operazione,
 ha richiesto che ci si riferisca a lui, o a lei, come Glenda.}
{170}{}{I moscerini della frutta mutati ora trasportano con successo il virus. Tuttavia, prima di liberarli su suolo straniero,
 e' stato deciso di esporli prima a una piccola comunita' americana isolata, dove possiamo monitorare
 gli effetti al di fuori di un ambiente di laboratorio. Le vittime civili che probabilmente ne risulteranno sono un sacrificio
 sfortunato, ma necessario. Inoltre, qualsiasi vero americano sarebbe onorato di dare la propria vita per il bene della nostra grande nazione.}
{200}{}{Scopri il vero intento della fluorizzazione dell'acqua.}
{311}{}{Whirrrr....}
{312}{}{BEEP!!}
{313}{}{Clunk...}
{1311}{}{Non mollare. Di sicuro si trovera' qualcosa.}
