{100}{}{Vedi una porta.}
{101}{}{Vedi una porta elettronica.}
{102}{}{Vedi una porta elettronica con una serratura a comando vocale e override.}
{200}{}{Conferma il codice:}
{201}{}{XY104FD}
{202}{}{BFN12}
{203}{}{Apri}
{204}{}{Grano}
{205}{}{Abre}
{206}{}{[FINE]}
{300}{}{Codice della porta errato. Blocco della porta in corso. Contatta il capo delle Pubbliche Relazioni per il codice di sblocco.}
{301}{}{[FINE]}
{400}{}{Conferma il codice di sblocco.}
{401}{}{[FINE]}
{402}{}{Questa porta e' chiusa elettronicamente.}
{403}{}{Sblocco della porta in corso. Grazie e buona giornata.}
{404}{}{[FINE]}
{500}{}{There is no lock to pick.}
