{100}{}{This door is locked.}
{101}{}{Vedi una porta chiusa a chiave, che impedisce qualsiasi ulteriore accesso.}
{102}{}{You see a sturdy-looking door.}
{103}{}{The door is now unlocked.}
{104}{}{This door is already unlocked and open.}
{105}{}{You fail to unlock the door.}
{106}{}{The lock is now jammed.}
{107}{}{The door is now locked.}
{108}{}{Non riesci a chiudere a chiave la porta.}
