{100}{}{Benvenuto nel Computer di Controllo dei Robot dell'EPA. Cosa desideri fare?}
{101}{}{Command Robots.}
{102}{}{Run diagnostic check.}
{103}{}{Te ne vai.}
{104}{}{!ERRORE! !ERRORE! RISCONTRATO PROBLEMA DURANTE LA SEQUENZA DI TERMINAZIONE!}
{105}{}{Ritorna al Menu Principale}
{106}{}{Controllo diagnostico... errore nella scheda di circuito... sezione quattro... cablaggio allentato.}
{107}{}{Fatto}
{108}{}{It's too difficult to repair this.}
{109}{}{Il guasto nel computer viene riparato e la macchina torna online.}
{110}{}{Benvenuto nel Computer di Controllo dei Robot dell'EPA. Non hai piu' l'autorizzazione di sicurezza per usare questi file. Sequenza terminata.}
{111}{}{OK}
{112}{}{BEEP!}
{113}{}{BOOP!}
{114}{}{Bzzzt..}
{115}{}{You already repaired it.}
