{100}{}{You see an anxious Shi guard.}
{101}{}{Gli occhi della guardia si muovono nervosi nell'oscurita'.}
{200}{}{Questo posto e' sacro. Inquietante da morire, ma sacro.}
{201}{}{Let's get this over with.}
{202}{}{I can feel the spirits of my ancestors among us.}
{203}{}{Vai a fare le tue cose da tecnico cosi' possiamo tornare sulla terraferma.}
{204}{}{Did you hear that? I swear I heard something.}
{205}{}{Why do I always get assigned to this? }
