{100}{}{Vedi una guardia Shi vigile.}
{101}{}{Quest'uomo accigliato sembra fare la guardia al motoscafo. Sembra prendere il suo lavoro molto sul serio.}
{200}{}{[Ti guarda con sospetto.] Posso aiutarti in qualcosa?}
{201}{}{No. Sono a posto. Arrivederci.}
{202}{}{Stavo solo chiedendomi cosa stai facendo.}
{203}{}{Ehi, bel motoscafo quello li'. Funziona ancora?}
{204}{}{Io andare su pesce?pesce di metallo?}
{210}{}{Non sono affari tuoi, forestiero. Vaffanculo.}
{211}{}{Pessima scelta di parole, stronzo. Saranno le ultime.}
{212}{}{Ho capito il messaggio. Non c'e' bisogno di fare lo stronzo. Ciao.}
{213}{}{Come dici tu, amico.}
{220}{}{[Ti guarda come se fossi la creatura piu' stupida che possa immaginare. Scuote lentamente la testa.] Tu no andare su pesce?pesce di metallo. Tu vai. Tu vai, o io sparo. Capito?}
{221}{}{Oke, ci-ciao!}
{222}{}{Tu uomo?cattivo. Io spacco uomo?cattivo!}
{230}{}{[La guardia stringe l'arma e ti fissa senza dire una parola.]}
{231}{}{Posso prendere in prestito la tua barca per un minuto?}
{232}{}{Stavo solo controllando se eri ancora uno stronzo. Si', direi proprio di si'. Ciao.}
{233}{}{Mi dispiace, pensavo fossi, uh, qualcun altro. Arrivederci.}
{234}{}{Spero tu sappia usare quella cosa, perche' ho intenzione di prendermi quel dannato motoscafo, in un modo o nell'altro.}
{240}{}{[Ti guarda come se fossi la creatura piu' stupida che possa immaginare. Scuote lentamente la testa.] No. Ora vai via. Fammi un'altra domanda e ti faccio male.}
{241}{}{D'accordo, me ne vado. Arrivederci.}
{242}{}{Davvero?}
{250}{}{Vattene da qui!}
{251}{}{Toccalo ancora e ti ammazzo.}
{252}{}{Ti avevo avvertito!}
