{100}{}{You see a vigilant Shi guard.}
{101}{}{Quest'uomo accigliato sembra fare la guardia al motoscafo. Sembra prendere il suo lavoro molto sul serio.}
{200}{}{[He eyes you suspiciously.] Help you with something?}
{201}{}{Nope. I'm all set. Bye.}
{202}{}{I was just wondering what you're doing.}
{203}{}{Ehi, bel motoscafo quello li'. Funziona ancora?}
{204}{}{Io andare su pesce?pesce di metallo?}
{210}{}{None of your business, outsider. Piss off.}
{211}{}{Pessima scelta di parole, stronzo. Saranno le ultime.}
{212}{}{Ho capito il messaggio. Non c'e' bisogno di fare lo stronzo. Ciao.}
{213}{}{Whatever you say, buddy.}
{220}{}{[Ti guarda come se fossi la creatura piu' stupida che possa immaginare. Scuote lentamente la testa.] Tu no andare su pesce?pesce di metallo. Tu vai. Tu vai, o io sparo. Capito?}
{221}{}{Okie, bu-bye!}
{222}{}{Tu uomo?cattivo. Io spacco uomo?cattivo!}
{230}{}{[La guardia stringe l'arma e ti fissa senza dire una parola.]}
{231}{}{Can I borrow your boat for a minute?}
{232}{}{Stavo solo controllando se eri ancora uno stronzo. Si', direi proprio di si'. Ciao.}
{233}{}{Sorry, I thought you were, uh, someone else. Bye.}
{234}{}{Spero tu sappia usare quella cosa, perche' ho intenzione di prendermi quel dannato motoscafo, in un modo o nell'altro.}
{240}{}{[Ti guarda come se fossi la creatura piu' stupida che possa immaginare. Scuote lentamente la testa.] No. Ora vai via. Fammi un'altra domanda e ti faccio male.}
{241}{}{Alright, I'm going. Bye.}
{242}{}{Is that a fact?}
{250}{}{Vattene da qui!}
{251}{}{Touch that again and I'll kill you.}
{252}{}{I warned you!}
