{100}{}{Vedi una guardia Shi agitata.}
{101}{}{Gli occhi della guardia si muovono nervosi nell'oscurita'.}
{200}{}{Questo posto e' sacro. Inquietante da morire, ma sacro.}
{201}{}{Finiamola qui.}
{202}{}{Posso sentire gli spiriti dei miei antenati tra noi.}
{203}{}{Vai a fare le tue cose da tecnico cosi' possiamo tornare sulla terraferma.}
{204}{}{Hai sentito? Giuro di aver sentito qualcosa.}
{205}{}{Perche' mi assegnano sempre a questo posto? }
