{100}{}{You see a dockworker. He looks up at you as you approach.}
{101}{}{Vedi un portuale malinconico. I suoi occhi pieni di tristezza si alzano verso di te mentre ti avvicini.}
{200}{}{[Borbottando tra se'.] Oh, quali atrocita' avra' mai commesso il povero Meng in una vita passata per meritare
 tanta sfortuna? Ora arriva il lao wai da me, e quale bene potrebbe mai venire da cio'? Nessuno, ovviamente. Nessuno...}
{201}{}{Perche' non lasci in pace il povero Meng? [Borbottando tra se'.] Non che io abbia mai conosciuto la pace. O, se l'ho conosciuta,
 e' ormai dimenticata, come un sogno lontano...}
{202}{}{Uh, sembra di averti beccato in un brutto momento. Ciao.}
{203}{}{What's your problem, Mumbles?}
{204}{}{Ho notato che sembri turbato da qualcosa. Mi chiedevo se potessi aiutarti.}
{210}{}{Il mio problema? [Ride amaramente.] Lao wai, non vuoi conoscere il mio problema. Sentire dolori come i miei
 significa dimenticare il suono della risata di un bambino e il caldo abbraccio di un amante. No, fidati, non vuoi dare uno sguardo al mio inferno personale.}
{211}{}{Ho visto molte cose terribili nella mia vita. Sono sicuro che qualunque sia il tuo problema, posso affrontarlo.}
{212}{}{Pensi che i *tuoi* problemi siano gravi? Scommetto che non *reggono il confronto* con quello che ho passato io.}
{213}{}{Mi dispiace che tu abbia passato momenti difficili, ma parlarne potrebbe aiutare. Se hai voglia di raccontarlo, io sono qui ad ascoltare.}
{214}{}{Va bene, signor Dramma, me ne vado prima che tu deprima anche me. Ciao.}
{220}{}{Va bene. Vuoi sapere qual e' il mio problema? Te lo dico. Due anni fa, mio fratello, che mi assomiglia molto,
 ebbe una relazione con la ragazza di un capo banda locale. Il capo lo scopri' e mio fratello fuggii' dalla citta'.
 La banda prese me al suo posto e, credendo che fossi lui, mi punii' in modo terribile. Ora devo urinare attraverso un tubo.}
{221}{}{Oh, well-- }
{230}{}{Oh no! Non ho ancora finito. Poi la mia splendida ragazza mi lascio', perche' secondo lei non ero piu' un "vero uomo"
 e non potevo piu' renderla felice. Sposo' il mio vicino di casa, che per giunta e' anche il mio capo. Ora, tutto il giorno,
 lui mi comanda e mi prende in giro davanti ai colleghi. E ogni notte devo cercare di dormire sentendo lui con la donna che
 avrei dovuto sposare io.}
{231}{}{Ahah! Santo cielo, che disastro. Perche' non ti fai un favore e la smetti di rovinarti la vita cosi'?}
{232}{}{Io... wow, non so cosa dire. E' una storia davvero terribile.}
{233}{}{Mi dispiace per quello che ti e' successo, Meng. La vita puo' essere crudele, ma puo' anche migliorare. Se fossi in te,
 me ne andrei altrove e cercherei un altro lavoro. Altrimenti non riuscirai mai ad andare avanti.}
{240}{}{Si. Si, e' cio' che avrei dovuto fare molto tempo fa. E' l'unico modo per conservare quel poco di onore che mi resta.
 Grazie, lao wai. [Estrae un coltello e si ferisce mortalmente alla gola. Cadi' a terra in pochi istanti.]}
{241}{}{[FATTO]}
{250}{}{Yes. This I warned you about. Now, let me be. I have nothing else to say to you.}
{251}{}{[FATTO]}
{260}{}{Forse hai ragione. Per tutta la vita ho conosciuto solo gli Shi. Ma qui non mi resta altro che dolore.
 Si, credo che andro' nel mondo a cercare un nuovo destino. Anche se le Lande mi offrissero solo una fine rapida,
 sarebbe comunque meglio che restare qui. Grazie, lao wai.}
{261}{}{Buona fortuna, Meng. Spero che la tua vita migliori.}
{262}{}{Prima che tu faccia i bagagli, mi chiedevo se potessi rispondere a un paio di domande.}
{270}{}{Perche' no? Sto recidendo ogni legame con gli Shi. I loro segreti ormai non significano piu' nulla per me. Chiedi pure.}
{271}{}{What can you tell me about that guarded motorboat over there? }
{272}{}{Never mind. Good luck on your new life, Meng.}
{280}{}{Gli Shi usano quel motoscafo per raggiungere il nostro guardiano addormentato, il sottomarino.}
{281}{}{What can you tell me about the sub?}
{290}{}{Lo Shi-Huang-Ti e' il sottomarino che porto' qui i nostri antenati da una terra lontana. Dopo la Grande Guerra
 perse potenza e si incaglio' nella baia di San Francisco. Il Capitano Ye Li e il suo equipaggio raggiunsero la citta'
 e fondarono quella che sarebbe diventata la societa' degli Shi.}
{291}{}{Lo hai chiamato "guardiano addormentato". Cosa intendevi?}
{300}{}{Come un drago in letargo le cui fauci possono ancora sputare fuoco mortale: il sottomarino e' immobile, ma non indifeso.
 Gli Shi ci lavorano in segreto, facendo visite clandestine durante la notte. Le sue armi sono state riattivate e distruggeranno
 qualsiasi nave non cinese che osi attraversare questa baia.}
{301}{}{Quindi, diciamo *ipoteticamente*, se quella grande petroliera attraccata qui provasse a salpare...}
{310}{}{Allora... BOOM!}
{311}{}{Gotcha. I don't suppose you know how I could disarm it?}
{320}{}{Solo i tecnici degli Shi saprebbero una cosa del genere. Ti ho detto tutto cio' che so.}
{321}{}{Thanks, Meng. Good luck with your new life.}
{330}{}{Now it is time to begin anew...}
{350}{}{Leave me be, lao wai.}
{400}{}{You convince Meng to move on with his life.}
