{100}{}{Vedi una guardia che indossa degli abiti trasandati; sul suo volto c'e' un'espressione attenta, ma annoiata.}
{101}{}{Vedi una guardia del porto. E' insolitamente ben armata.}
{102}{}{Vedi la guardia del motoscafo.}
{150}{}{Ehi! Allontanati da li'!}
{151}{}{Non ci pensare nemmeno. Questo e' il tuo ultimo avvertimento.}
{152}{}{Ti avevo avvertito, lao wai, adesso muori!}
{200}{}{Cosa vuoi, lao wai?}
{201}{}{Sei ancora tu. Cosa vuoi, lao wai?}
{202}{}{Cosa stai sorvegliando?}
{203}{}{Ho bisogno di usare il motoscafo.}
{204}{}{Nulla. Arrivederci.}
{210}{}{Tutto. Non provare a fare niente di strano.}
{211}{}{Non puoi essere piu' specifico?}
{220}{}{No. Adesso indietro, forestiero.}
{221}{}{Okay. Ci vediamo.}
{222}{}{Nessuno mi dice cosa fare. Sei finito!}
{230}{}{E io ho bisogno che tu te ne vada subito. Non ti e' permesso usare il motoscafo, sei un lao wai, non uno Shi.}
{231}{}{Ascolta, sono in una situazione disperata. Se non mi lasci usare quel motoscafo, la mia intera tribu' potrebbe morire.
 In questo momento sono nelle mani di quei bastardi dell'Enclave e contano su di me per salvarli. Ma per farlo ho bisogno
 di quel motoscafo. Se non me lo lasci usare, dovro' prenderlo con la forza e uno di noi finira' male. Ti prego, non arriviamo a questo.}
{232}{}{In realta' sono un membro onorario degli Shi. Sono stato assunto per il team di manutenzione del sottomarino grazie alla mia esperienza in... subologia. Ecco la mia password...}
{233}{}{Non credo che tu sappia chi stai insultando. E' ora di morire, stronzo.}
{234}{}{D'accordo, me ne vado... Certe persone...}
{240}{}{[Ti fissa a lungo, poi sospira.] Senti, nessuno sale su questa barca senza la password corretta. Sai, come quella che mi hai appena dato. [Borbottando.] Ken Lee mi fara' a pezzi per questo...}
{241}{}{Grazie, amico. E non preoccuparti, non diro' una parola a nessuno.}
{250}{}{Spero di no, per il bene di entrambi... Fammi sapere quando sei pronto a usare la barca. Non puoi portare nessuno con te, attirerebbe troppa attenzione. Dovrai andare da solo.}
{251}{}{Vorrei usarlo adesso.}
{252}{}{Non adesso.}
{260}{}{[La guardia ascolta la password e annuisce.] Immagino che tu sia davvero un tecnico. Hmm, gli Shi devono essere disperati per assumere stranieri... Comunque, sei in anticipo. Non ti hanno detto che la squadra tecnica parte solo a mezzanotte? Puoi aspettare qui il resto del team, se vuoi.}
{261}{}{Non ho niente di meglio da fare, quindi certo...}
{262}{}{Tornero' piu' tardi.}
{270}{}{Usa il palo d'ormeggio e scivola lungo la corda fino alla barca. Ma non starci troppo, non voglio finire nei guai.}
{271}{}{Capito. Ci vediamo.}
{272}{}{Abbastanza semplice. Arrivederci.}
{280}{}{Pronto ad unirti al team tecnico?}
{281}{}{Si', sono pronto ad andare.}
{282}{}{No, non ancora.}
{290}{}{Non vedi che sono occupato?}
{300}{}{Io andare su pesce?pesce di metallo?}
{310}{}{[Ti guarda come se fossi la creatura piu' stupida che possa immaginare. Scuote lentamente la testa.] Tu no andare
 su pesce?pesce di metallo. Tu vai. Tu vai, o io sparo. Capito?}
{311}{}{Oke, ci-ciao!}
{312}{}{Tu uomo?cattivo. Io spacco uomo?cattivo!}
{500}{}{Riesci a convincerlo e ottieni l'accesso al motoscafo.}
