{100}{}{You see a crazed-looking Shi scientist.}
{101}{}{You see Dr. Sheng.}
{200}{}{[Vedi uno scienziato Shi con una barba rada e uno sguardo folle. Capelli e vestiti sono in disordine e sembra non dormire da giorni.] Ah! Si! Si, ti stavo aspettando. Mi hanno detto che saresti arrivato. [Ti squadra dalla testa ai piedi.] Si, sei perfetto.}
{201}{}{I won't argue with that, but what the hell is going on here?}
{202}{}{Devi essere il dottor Sheng. Il dottor Wong mi ha detto dove trovarti. Gli Shi pensavano fossi morto.}
{203}{}{First of all, what are these creatures?}
{204}{}{Perfetto per cosa, esattamente?}
{205}{}{Who told you I was coming?}
{210}{}{Scienza! Cos'altro? Io sono il dottor Sheng e queste creature sono le mie creazioni. Belle, non trovi?}
{211}{}{Uh, yeah ... But, what are they?}
{212}{}{A dire il vero le trovo piuttosto ripugnanti. Da conati, davvero. E quell'odore, dolciastro e marcio allo stesso tempo, come sciroppo fatto con liquami di cadavere. Che cosa sono queste cose?}
{220}{}{Ha! Il dottor Wong spera che io sia morto. Oh no, sto meglio che mai. E le cose miglioreranno ancora, se sei disposto ad aiutarmi.}
{221}{}{Assist you with what?}
{222}{}{Aspetta. Prima di accettare di aiutarti, dimmi che cosa sono queste creature.}
{230}{}{Sono il futuro! Una nuova razza di forme di vita vegetali senzienti, create da me. Ho finalmente avuto successo nel sintetizzare la mia nuova vita vegetale con cadaveri umani freschi! Come puoi vedere, questo dona alle piante capacita' sensoriali, motorie e vocali che altrimenti non avrebbero. E conferisce loro un aspetto umanoide che permettera' una piu' facile assimilazione nella nostra cultura.}
{231}{}{E dove trovi questi "cadaveri umani freschi"? }
{232}{}{Assimilarsi nella nostra cultura? Buona fortuna. I ghoul e i mutanti a malapena ci riescono, e loro sono stati umani, almeno un tempo. Queste cose sono abomini.}
{233}{}{A dire il vero ho incontrato una pianta di spore che parlava senza essere stata fusa con un corpo umano.}
{234}{}{Incredibile. Da collega amante della scienza, devo sapere come sia stato possibile.}
{240}{}{Perfetto per il compito che ho in mente. Vedi, non tutte le mie creature sperimentali hanno avuto successo come questi esemplari. La maggior parte finisce per essere bestie violente e senza cervello. Tengo questi fallimenti rinchiusi in un recinto nel mio laboratorio, ma di recente sono fuggiti. Sono riuscito a uscire e chiudere la porta prima che qualcuno scappasse nelle Lande, ma ora non posso piu' tornare nel mio laboratorio.}
{241}{}{So what do you want me to do about it?}
{250}{}{Le mie creazioni, naturalmente. Sono sempre vigili sulle Lande. C'e' molto di cui diffidare la fuori, come saprai bene. Quando mi hanno avvisato del tuo arrivo, ho detto loro di portarti da me, perche' credo tu possa aiutarmi.}
{251}{}{Assist you with what?}
{252}{}{Prima di accettare di aiutarti, dimmi che cosa sono queste creature.}
{260}{}{Oh, per lo piu' da predoni che hanno la pessima idea di attaccarci. Ma basta con questo. Devo sapere se sei disposto ad aiutarmi.}
{261}{}{Assist you with what?}
{270}{}{Vedi, non tutte le mie creature sperimentali hanno avuto successo come questi esemplari. La maggior parte diventa bestie violente e senza cervello. Tengo questi fallimenti rinchiusi in un recinto nel mio laboratorio, ma di recente sono fuggiti. Sono riuscito a uscire e chiudere la porta prima che qualcuno scappasse nelle Lande, ma ora non posso piu' tornare al laboratorio.}
{271}{}{So what do you want me to do about it?}
{280}{}{Come ti senti riguardo al mio lavoro non mi interessa. Ora saro' diretto. Ho un compito per cui sembri qualificato. Una volta completato, verrai ricompensato. Sei interessato?}
{281}{}{Sono tutto orecchi.}
{282}{}{I want nothing to do with you or your disgusting creations.}
{290}{}{Eccellente! Consegnameli, e verrai ricompensato.}
{291}{}{Sure, it's not like I have much use for them. Here you go.}
{292}{}{No. Mi sono affezionato a quei cosetti. Credo che li terro'. Magari ci faccio un giardino o qualcosa del genere.}
{293}{}{I don't have them on me but I'll go see if I can find them.}
{294}{}{Non li ho con me, e anche se li avessi non te li darei. Non voglio avere nulla a che fare con te o con i tuoi zombie?vegetali.}
{300}{}{La struttura e' conosciuta come EPA. L'ho segnata sul tuo dispositivo di mappatura. Per favore, vai li' e prova a trovare dei semi. E non semi qualunque: devono essere unici.}
{301}{}{Ah, sembra che tu conosca gia' la posizione dell'EPA. Per favore, vai li' e prova a trovare dei semi. E non semi qualunque: devono essere unici.}
{302}{}{Tornero'.}
{303}{}{Eh, ripensandoci, non mi interessa piu' lavorare per te. Abbiamo finito qui.}
{310}{}{[I suoi occhi si accendono di rabbia] Uccidetelo, miei figli! Il suo corpo sara' un ottimo ospite per il vostro nuovo fratellino!}
{311}{}{[I suoi occhi si accendono di rabbia] Uccidetela, miei figli! Il suo corpo sara' un ottimo ospite per il vostro nuovo fratellino!}
{312}{}{[FATTO]}
{320}{}{Eccellente! Ora preparero' la tua ricompensa. Mettiti comodo. Potrebbe volerci un po'.}
{321}{}{[CONTINUA]}
{322}{}{Keep your reward. I don't have time to wait around.}
{330}{}{Si, porta i semi a me e potrai reclamare la tua ricompensa.}
{331}{}{Tornero'.}
{340}{}{Darti la posizione della struttura e' gia' una ricompensa di per se', visto che sara' piena di provviste utili. Puoi ovviamente tenere tutto cio' che trovi. A me interessano solo campioni di semi unici. Una volta che me li avrai portati, ti daro' un dono da presentare agli Shi.}
{341}{}{Alright, I'll do it. I'll be back.}
{342}{}{Quella la chiami una ricompensa? Posso esplorare rovine quando voglio. Non mi interessa.}
{350}{}{[Ti guarda in attesa.]}
{351}{}{Here are the seeds you wanted.}
{352}{}{I'll come back when I have the seeds.}
{360}{}{Allora sembra che tu non mi serva piu'. [Fa un gesto verso le creature vegetali.] Uccidetelo, miei figli! Il suo corpo sara' un ottimo ospite per il vostro nuovo fratellino!}
{361}{}{Allora sembra che tu non mi serva piu'. [Fa un gesto verso le creature vegetali.] Uccidetela, miei figli! Il suo corpo sara' un ottimo ospite per il vostro nuovo fratellino!}
{362}{}{[FATTO]}
{370}{}{[Il dottore se ne va. Dopo circa un'ora ritorna e ti consegna un singolo seme.] Questo campione vegetale e' il mio dono agli Shi. Cambiera' tutto. Ti do l'onore di presentarlo al dottor Wong.}
{371}{}{What's so special about this plant sample?}
{372}{}{Tutto qui? Sono andato a prenderti quei dannati semi e questa e' la ricompensa? Un altro seme? Al diavolo te e i tuoi inquietanti zombie?vegetali. Credo che faro' un favore al mondo mettendo fine a questa tua operazione morbosa.}
{380}{}{Gli Shi hanno tentato di creare vita vegetale resistente alle radiazioni. Io ero a capo del progetto, ma durante le mie ricerche ho fatto una scoperta che mi ha portato su un'altra strada. Ho creato un siero di senzienza vegetale, ma dopo alcuni... spiacevoli incidenti, gli Shi volevano chiudere il progetto. Cosi' me ne sono andato per continuare il mio lavoro senza ostacoli.}
{381}{}{Okay. E questo campione vegetale cosa c'entra con tutto cio'?}
{382}{}{Continua...}
{390}{}{Ironia della sorte, proprio mentre mi stavo concentrando sulle mie nuove piante senzienti, ho fatto una grande scoperta nella ricerca sulle piante resistenti alle radiazioni. Ho tenuto segreta questa scoperta, per non distogliere l'attenzione dalla mia invenzione piu' importante. Quando gli altri non hanno capito il valore delle mie piante senzienti, ho deciso di tenere il segreto per ripicca. Fino ad ora. Con il campione che ti ho dato, persino un ottuso come il dottor Wong potrebbe raggiungere l'obiettivo di creare piante resistenti alle radiazioni.}
{391}{}{So why the change of heart?}
{392}{}{Okay. I'll deliver it to Dr. Wong.}
{393}{}{Lo portero' al dottor Wrong. Ma se non mi dara' una ricompensa adeguata, ci rivedremo.}
{394}{}{Tieniti pure il campione. Sono sicuro che il dottor Wong e gli altri scienziati Shi sapranno cavarsela senza il tuo aiuto. Ho finito di farti favori.}
{400}{}{Non ho cambiato idea. Oltre a essere resistente alle radiazioni, il campione vegetale e' infuso con il mio siero di senzienza. Come un padre orgoglioso, desidero solo vedere la mia creazione prosperare. Consegnalo per me, e riceverai una vera ricompensa.}
{401}{}{Okay. I'll deliver it to Dr. Wong.}
{402}{}{Nah. Keep your sample. I'm done helping you.}
{403}{}{Il dottor Wong sembra un tipo furbo. Pensi davvero che si fiderebbe di un campione vegetale proveniente da te?}
{410}{}{Mi e' giunta voce che esista una vecchia struttura del governo degli Stati Uniti dove si possono ottenere semi vegetali unici, non toccati dalle radiazioni. La struttura e' troppo lontana perche' possa andarci di persona, ma credo sarebbe un compito semplice per un wastelander esperto come te.}
{411}{}{Oh, stai parlando di quei semi strani dell'EPA. Ci sono stato, li ho presi.}
{412}{}{Sono sempre pronto a esplorare vecchie rovine. Dammi la posizione e andro' a vedere cosa riesco a trovare.}
{413}{}{And what do I get out of it?}
{420}{}{Si, il dottor Wong e' un ostacolo. Se venisse tolto di mezzo, le cose andrebbero molto piu' lisce. Dai il campione al dottor Wong. Anche se non si fida di me, la curiosita' avra' la meglio e lo accettera'. Una volta che il campione sara' stato messo al sicuro, trova un modo per eliminare il dottor Wong senza allertare gli altri Shi. Magari una sorta di overdose. Fallo, e faro' in modo che la tua ricompensa sia triplicata.}
{421}{}{Vedro' di fare il possibile.}
{422}{}{If you want Wong dead, you'll need to give me something up front.}
{423}{}{Sai, sta diventando tutto un po' troppo complicato. Credo che preferirei fare a pezzi te e poi fare a pezzi gli Shi.}
{424}{}{There's no way I'm killing Dr. Wong for you. I'm done here.}
{430}{}{Molto bene. Questo veleno potrebbe tornarti utile. L'ho estratto da una delle mie creazioni. E' estremamente letale. [Ti porge una siringa.]}
{431}{}{Vedro' di fare il possibile.}
{440}{}{[Ti guarda in attesa.]}
{441}{}{I'm still working on things. I'll get back to you.}
{442}{}{I delivered the sample to the Shi.}
{443}{}{The Shi have the sample and Dr. Wong is dead.}
{444}{}{Il tuo metodo di vendetta non era abbastanza diretto per i miei gusti, quindi ho ucciso tutti io per te.}
{445}{}{Dr. Wong is dead.}
{446}{}{Ho consegnato il campione agli Shi e ho detto al dottor Wong quali erano le tue intenzioni. Ha distrutto il campione immediatamente.}
{450}{}{Impossibile! Una pianta di spore non puo' parlare, indipendentemente dalla sua intelligenza. O stai scherzando, oppure eri sotto l'effetto di qualche allucinazione indotta da droghe. A giudicare dal tuo aspetto, direi la seconda. Ma basta con queste sciocchezze. Devo sapere se sei disposto ad aiutarmi.}
{451}{}{Si, immagino che *suoni* piuttosto assurdo. Comunque, con cosa volevi che ti aiutassi?}
{452}{}{Non cambiare argomento — stavo dicendo la verita'! Lo giuro sul Vault Dweller, si chiamava Seymour e sapeva parlare. Voleva che lo ripiantassi in un posto migliore. Non me lo sto inventando e non stavo allucinando.}
{460}{}{Basta! Non ho tempo per queste sciocchezze. Mi aiuterai o no?}
{461}{}{Assist you with what?}
{462}{}{No! Non ti aiutero', idiota! Seymour era reale! SEYMOUR ERA REALE!}
{470}{}{[Sorride, chiaramente impaziente di mostrare il suo genio.] Sono sempre stato affascinato dalle piante. Sono cosi' straordinariamente diverse dagli animali, eppure sorprendentemente simili. Quando guardi un animale, sai che puo' pensare, che e' consapevole di cio' che lo circonda, che prova dolore e paura. Che ha ragione. Ovviamente il livello varia, ma il punto e' che un animale possiede tutto questo.}
{471}{}{Continua.}
{480}{}{Ma quando guardi una pianta, pensi le stesse cose? Se dai un calcio a una pianta, reagisce? Ti risponde in qualche modo? Parlare a una pianta influisce sulla sua crescita? Alcune culture prima della Grande Guerra testarono queste teorie. Un popolo noto come i tedeschi condusse esperimenti che li portarono a credere che le piante fossero capaci di emozioni e che si potesse favorirne la crescita con parole, attenzione e affetto.}
{481}{}{Ma le piante non hanno un sistema nervoso, e senza di esso cio' che suggerisci non e' possibile.}
{482}{}{Penso che tutte le forme di vita percepiscano in un modo o nell'altro.}
{483}{}{Quelle piante di spore che ho incontrato reagiscono eccome. Quindi si', direi che le piante sentono qualcosa.}
{490}{}{E non saresti il solo a pensarlo. Anche io ero scettico all'inizio. Ma vedi, nel ventesimo secolo il governo degli Stati Uniti condusse esperimenti simili, concentrandosi sulla comunicazione. Certo, tutte le forme di vita hanno un modo per percepire il danno, cioe' il dolore, ma comunicano questo dolore in qualche modo? E quale fu la conclusione di questi esperimenti? L'idea della biocomunicazione — che le piante siano senzienti.}
{491}{}{Are you suggesting that plants are almost like humans?}
{500}{}{E non saresti il solo a pensarlo. Nel ventesimo secolo il governo degli Stati Uniti condusse esperimenti simili, concentrandosi sulla comunicazione. Tutte le forme di vita percepiscono il danno, cioe' il dolore, ma lo comunicano in qualche modo? E quale fu la conclusione? L'idea della biocomunicazione — che le piante siano senzienti.}
{501}{}{Are you suggesting that plants are almost like humans?}
{510}{}{Sto suggerendo che POTREBBERO essere come gli esseri umani. E come puoi vedere, avevo ragione. Avevano solo bisogno di un piccolo aiuto.}
{511}{}{A little help?}
{520}{}{Ingegneria genetica! Grazie alla magia della scienza, sono riuscito a sviluppare un siero di senzienza botanica. Ma dare alle piante un'intelligenza simile a quella umana era solo meta' dell'equazione. Per sfruttare davvero tale intelligenza, sapevo che avrebbero avuto bisogno di un corpo e di sensi simili a quelli umani.}
{521}{}{Ah, e qui entrano in gioco i "cadaveri umani freschi". Devi dirmi come sei riuscito a far interfacciare la vita vegetale con un sistema nervoso umano e a prenderne il controllo. E per di piu' uno morto. Non ci avrei mai creduto se non lo avessi visto con i miei occhi.}
{530}{}{Molto bene, non posso promettere che comprenderai pienamente cio' che sto per dirti, ma faro' del mio meglio per spiegartelo. [Con lo zelo di un predicatore che delira del suo dio davanti a un ascoltatore rapito, passa due ore a descrivere nei dettagli il processo dei suoi esperimenti, mostrando chiaramente grande orgoglio per i suoi risultati.]}
{531}{}{[AVANTI]}
{540}{}{E quindi ora capisci, spero?}
{541}{}{Si, capisco. Sembrava del tutto impossibile, ma il modo in cui l'hai spiegato ha perfettamente senso. E quella cosa delle spugne, assoluto genio! Macabro, ma genio. Ma c'e' una cosa che non hai spiegato. Dove esattamente trovi questi "cadaveri umani freschi"?}
{550}{}{Aspetta un momento. Il dottor Wong sara' un ostacolo. Se venisse tolto di mezzo, le cose andrebbero molto piu' lisce. Dai il campione al dottor Wong. Anche se non si fida di me, la curiosita' avra' la meglio e lo accettera'. Una volta che il campione sara' stato messo via, trova un modo per eliminare il dottor Wong senza allertare gli altri Shi. Magari una sorta di overdose. Fallo, e faro' in modo che la tua ricompensa sia triplicata.}
{551}{}{Vedro' di fare il possibile.}
{552}{}{If you want Wong dead, you'll need to give me something up front.}
{553}{}{Sai, sta diventando tutto un po' troppo complicato. Credo che preferirei fare a pezzi te e poi fare a pezzi gli Shi.}
{554}{}{There's no way I'm killing Dr. Wong for you. I'm done here.}
{560}{}{Eccellente. E il dottor Wong?}
{561}{}{He is still alive. I'll return once he's out of the picture.}
{562}{}{Non uccidero' il dottor Wong per te. Ho dato loro il campione vegetale, e ora ho finito di aiutarti.}
{570}{}{Ho bisogno che vengano eliminati, e tu sembri piu' che capace di farlo.}
{571}{}{Perche' non mandi questi, uh, quelli piu' riusciti, a occuparsene?}
{572}{}{Sounds fun. I'll do it.}
{573}{}{Io cosa ne ricavo?}
{574}{}{I'm not interested in cleaning up your messes.}
{580}{}{Non attaccheranno i loro simili. Capiscono perche' devo liberarmi dei loro fratelli meno fortunati, ma non compiranno il compito da soli. Questo mi ha lasciato in una situazione piuttosto delicata. Ed e' per questo che sono stato cosi' felice di sapere del tuo arrivo. Allora, mi aiuterai?}
{581}{}{All right. I'll do it.}
{582}{}{Io cosa ne ricavo?}
{583}{}{I'm not interested in cleaning up your messes.}
{590}{}{Il laboratorio e' proprio li' a nord. La sentinella ti lascera' passare. Fai attenzione. Queste creature sono incredibilmente forti, quindi cerca di non farle avvicinare troppo. Oh, e attento alle spore velenose che lanciano. Ma non preoccuparti. Ho un antidoto, nel caso venissi avvelenato.}
{591}{}{Okay. I'll be back.}
{592}{}{Quindi sono incredibilmente forti e hanno proiettili velenosi? Ripensandoci, passo.}
{600}{}{Ti daro' del denaro, naturalmente. Inoltre, ho informazioni che credo ti interesserebbero molto. Allora, mi aiuterai?}
{601}{}{All right. I'll do it.}
{602}{}{I'm not interested in cleaning up your messes.}
{610}{}{[Ti guarda in attesa.]}
{611}{}{I'll come back after I've taken out the creatures in the lab.}
{612}{}{All the creatures in the lab are dead.}
{613}{}{Tutte le creature nel laboratorio sono morte, ma sono stato avvelenato. Avevi detto qualcosa riguardo un antidoto?}
{620}{}{Si, te lo somministro subito. Ecco.}
{621}{}{Ah. I feel better already.}
{630}{}{E' un peccato perdere quegli esemplari, ma un male necessario per riprendere il mio laboratorio. Hai fatto bene. Ecco la tua ricompensa in denaro. [Ti consegna 1000$.] La seconda parte della ricompensa e' informazione — e un secondo compito da svolgere.}
{631}{}{E' un peccato perdere quegli esemplari, ma un male necessario per riprendere il mio laboratorio. Hai fatto bene. La tua ricompensa e' informazione — e un secondo compito da svolgere.}
{632}{}{Let's hear it.}
{633}{}{Lascia perdere. Tieniti le tue informazioni. Ho finito di lavorare per te.}
{640}{}{Eccellente. E gli Shi hanno il campione che ti ho dato?}
{641}{}{Oh, uh... No, in realta'. Mi sono dimenticato di darglielo.}
{700}{}{You clear out Dr. Sheng's lab.}
{710}{}{You deliver plant seeds to Dr. Sheng.}
{800}{}{*gasp* Ahhh...}
