{100}{}{Vedi uno Shi basso e paffuto.}
{101}{}{Vedi il dottor Wong Yi Tze.}
{102}{}{Vedi uno Shi basso e paffuto.}
{103}{}{Posso aiutarla in qualche modo?}
{104}{}{Daghi nu?}
{105}{}{Chi tu?}
{106}{}{Mi hanno detto che lei ha la milza di qualcuno.}
{107}{}{Chi sei?}
{108}{}{Di che cosa ti occupi?}
{109}{}{No, grazie. E' tutto.}
{110}{}{Devo confessarle che non parlo la sua lingua. Forse dovrebbe parlare con Ken Lee, che conosce molte lingue.}
{111}{}{Aagh!}
{112}{}{Io sono il Dr. Wong. Sono il capo scienziato di questo insediamento.}
{113}{}{Altre domande, per cortesia.}
{114}{}{Grazie. Ciao.}
{115}{}{Io soprintendo agli esperimenti scientifici che vengono qui concepiti e realizzati. Sono anche il responsabile della rete informatica.}
{116}{}{Che cosa state progettando?}
{117}{}{Come si fa ad accedere alla rete informatica?}
{118}{}{Ho delle altre domande.}
{119}{}{Capisco. Arrivederci.}
{120}{}{Ah, ma se io le rivelassi i nostri progetti, tutti li conoscerebbero. Mi dispiace, ma i nostri progetti sono segreti, per il momento.}
{121}{}{D'accordo, d'accordo. Ho delle altre domande.}
{122}{}{Grazie. Ciao.}
{123}{}{Cosa ne diresti se ti piantassi una pistola nel naso e ti obbligassi a rivelarmeli?}
{124}{}{Beh, per farlo, una persona dovrebbe scoprire o come violare il sistema o come farsi amico uno dei miei sottoposti. Sto scherzando, ovviamente, a proposito di violare il sistema - se lei tentasse di farlo, manderei qualcuno ad ucciderla. [Sorride per indicare che non sta minacciando.]}
{125}{}{Davvero mi farebbe uccidere?}
{126}{}{Dunque lei non porrebbe nessuna reale opposizione se io tentassi di accedere al computer?}
{127}{}{Ho delle altre domande.}
{128}{}{Certo che lo farei. Arrivederci.}
{129}{}{A quel punto io dovrei considerarla come una minaccia e dovrei avvertirla che un tale comportamento potrebbe essere dannoso per la sua salute.}
{130}{}{Facciamo una prova.}
{131}{}{Stavo solo scherzando. Ho delle altre domande.}
{132}{}{[Sorride] Dobbiamo difendere il nostro onore, straniero.}
{133}{}{Err, giusto. Dunque lei non porrebbe nessuna reale opposizione se io tentassi di accedere al computer?}
{134}{}{Giussssto. Ho delle altre domande.}
{135}{}{Posso immaginarlo. Addio.}
{136}{}{Solo se lei riuscisse a convincere uno dei miei sottoposti a farlo. Ma io di certo non lo farei.}
{137}{}{E se ficcassi una pistola nel tuo naso?}
{138}{}{Ottimo. Beh, ho delle altre domande.}
{139}{}{Hmm. Capisco. Beh, addio.}
{140}{}{Ahh, si'! E' vero. La preparero' con un contorno di fave e un buon Chianti.}
{141}{}{Ce l'ha ancora? Bene. Chip la rivuole.}
{142}{}{Quella e' una milza umana, pazzo bastardo!}
{143}{}{Lei lo sa che con quel vino si dovrebbe servire il fegato, e non la milza, non e' vero?}
{144}{}{Quella e' una milza umana, lo sa?}
{145}{}{Chi e' questo Chip? Questa milza adesso e' mia, e me la mangero' per cena.}
{146}{}{Chip e' il proprietario originale della milza. Era ubriaco e l'ha venduta a Lao Chou.}
{147}{}{Gli serve per sopravvivere, sa com'e'... Viene dall'interno del suo corpo.}
{148}{}{Forse allora farei meglio ad ucciderla.}
{149}{}{Gli affari sono affari. Non puo' averla. Mi dispiace, ma abbiamo fatto una transazione regolare e non possiamo dichiararla nulla solo perche' questo Chip se n'e' pentito.}
{150}{}{[AVANTI]}
{151}{}{E' una milza umana? Lao Chou non me l'aveva detto!}
{152}{}{Tuttavia, a causa della scortesia del messaggero, credo che riterro' comunque valido l'affare. Invece di cucinarla, la usero' per i miei esperimenti.}
{153}{}{Dica al suo amico di venire a riprendersela entro domani e saro' ben lieto di restituirgliela. Spero solo che possiate trovare un modo per rimetterla nel suo corpo in tempo.}
{154}{}{Molto bene.}
{155}{}{Ah ah! Si', anch'io ho visto quel vecchio film. Un attimo... cosa significa? Vuole forse dire che...?}
{156}{}{Si', e' una milza umana.}
{157}{}{In realta' avrei da obiettare su questo punto. Lei stesso non ha certo dimostrato di avere un buon carattere. Proprio non so perche' io stia parlando con lei. Buona giornata.}
{158}{}{[FATTO]}
{159}{}{Aiee! Guardie! Il lao wai intruso e' qui!}
{160}{}{Ha quegli schemi tecnici da darmi?}
{161}{}{Ken Lee mi ha detto di dare questi a lei.}
{162}{}{Si'. E io cosa ottengo in cambio?}
{163}{}{No, non ancora.}
{164}{}{Parli con Ken Lee, che decidera' cosa sara' del suo futuro. Grazie. Con questi saremo in grado di verificare alcuni nostri dati. Buona giornata.}
{165}{}{Veramente avrei delle altre domande.}
{166}{}{Ci vediamo.}
{200}{}{Ho trovato questo cadavere nascosto nella base degli Hubologist. Credo possa essere il vostro esemplare mancante del Progetto Xeno.}
{201}{}{Si, e' proprio lui! Il mio predecessore aveva investito molto in questo soggetto ed era molto turbato quando scomparve. Anche se ora non c'e' piu', potremmo comunque trovare un uso per questo esemplare. Grazie per averlo recuperato.}
{202}{}{Nessun problema. Ci vediamo dopo.}
{203}{}{Aspetta un attimo. Nessuno ha detto che lo faccio gratis.}
{204}{}{Corretto. E nessuno ti ha chiesto di recuperare il soggetto. L'hai fatto e lo hai portato qui di tua spontanea volonta'. Ora il soggetto rubato e' stato restituito ai suoi legittimi proprietari, e te ne siamo grati.}
{205}{}{Bello, ma l'ho trovato io, quindi se lo rivolete, vi costera'.}
{206}{}{Non ho tempo per questo... Guardie!}
{207}{}{[L'uomo sembra sul punto di urlare, poi si calma.] Va bene. Ecco 500$. Piu' che sufficienti per qualcosa che e' sempre appartenuto a noi. Ora vai, sono un uomo impegnato.}
{208}{}{È stato un piacere fare affari con te. Addio.}
{209}{}{Oh, merda!}
{210}{}{Balliamo!}
{211}{}{Recuperi l'esemplare mancante del Programma Xeno.}
{220}{}{E allora dov'e'? Stai cercando di prendermi in giro?}
{221}{}{Scusa, mi piace accumulare piu' oggetti possibile. E' un po' il mio stile.}
{230}{}{Non ho tempo per questo. Torna quando avrai il campione.}
{240}{}{[Annusa l'aria.] Che odore e'? Sembra carne marcia. [Ti guarda e alza un sopracciglio.]}
{241}{}{Oh, devi sentire questo corpo che ho trovato. A dire il vero non so nemmeno perche' lo sto portando in giro.}
{242}{}{Uh?uh! [Tiri fuori il cadavere in decomposizione] Corpo puzzolente! Tu volere?}
{250}{}{Aspetta un secondo, questo e' il soggetto del Progetto Xeno! Il mio predecessore aveva investito molto in questo soggetto ed era piuttosto sconvolto quando scomparve. Anche se ora non c'e' piu', potremmo comunque trovare un uso per questo soggetto. Grazie.}
{251}{}{No, non lo voglio-- Aspetta un secondo, questo e' il soggetto del Progetto Xeno! Il mio predecessore aveva investito molto in... [Nota il tuo sguardo vuoto.] Ehm. Voglio dire, grazie per il corpo. Ben fatto. Ma non portarne altri. Questo basta. Arrivederci!}
{252}{}{Ciao, ciao!}
{253}{}{Io tenere cose. Io nascondere tutto.}
{300}{}{Allora, qual è la storia di questo dottor Sheng?}
{310}{}{Come fai a conoscere il dottor Sheng? Eh, suppongo non importi. Il dottor Sheng Ming era un uomo brillante, ma piuttosto sgradevole, che ha servito come mio predecessore. Non ha piu' alcuna grande rilevanza qui.}
{311}{}{Se non è importante per te, perché dovrebbe importare a me? Lascia che ti chieda qualcos'altro.}
{312}{}{Allora, cosa gli è successo?}
{320}{}{Cosa e' successo? Direi che ha perso la testa. Durante i suoi esperimenti si imbatti' in qualcosa che, lo ammetto, era piuttosto notevole, ma anche estremamente pericoloso e del tutto estraneo agli obiettivi degli Shi. Ma questo non importava al dottor Sheng. Divenne ossessionato dalla sua creazione e, poiche' i suoi esperimenti furono giudicati troppo pericolosi per continuare qui, decise di portarli altrove. Parti' per un congedo e non torno' mai piu'. Fu allora che presi il suo posto.}
{321}{}{Che tipo di esperimenti stava conducendo il dottor Sheng? E qual era esattamente la sua grande scoperta?}
{322}{}{E ora dove si trova il dottor Sheng?}
{330}{}{Come uomo di scienza, rispetto la tua natura inquisitiva. Tuttavia, temo di non essere disposto a condividere i segreti degli Shi con te, straniero.}
{331}{}{E ora dove si trova il dottor Sheng?}
{332}{}{Bene, tieniti pure i tuoi segreti raffinati. Anch'io ho i miei segreti, sai. Segreti migliori di quanto tu possa mai immaginare.}
{340}{}{[Sorride educatamente.] Ne sono certo. Ora, se vuoi scusarmi, ho molto lavoro da fare. Buona giornata.}
{341}{}{[FATTO]}
{350}{}{Il dottor Sheng fu accompagnato verso sud, un giorno o giu' di li'. Si stabili' in una casa abbandonata, se non sbaglio. Doveva restare via solo un mese, ma e' passato molto piu' tempo e non abbiamo ancora sue notizie. Se dovessi indovinare, direi che e' stato distrutto dalle sue stesse creazioni, oppure e' caduto vittima dei numerosi pericoli delle Lande.}
{351}{}{Uno dei vostri scienziati principali potrebbe essere morto, e non vi importa? Non avete nemmeno intenzione di indagare?}
{352}{}{Penso che vorrei approfondire la questione del dottor Sheng. Potresti darmi la sua ultima posizione conosciuta?}
{353}{}{Bene, questo è tutto. Ora vorrei farti un'altra domanda.}
{360}{}{Dovrai scusarmi se sembro cosi' indifferente alla questione. La verita' e' che il dottor Sheng non era molto popolare da queste parti e non credo che nessuno di noi senta minimamente la sua mancanza.}
{361}{}{Penso che vorrei approfondire la questione del dottor Sheng. Potresti darmi la sua ultima posizione conosciuta?}
{362}{}{Capisco. Lascia che ti chieda qualcos'altro.}
{370}{}{Suppongo di poterlo fare... Devo ammettere che sono un po' curioso di conoscere la sua sorte. Ecco, segnero' l'ultima posizione conosciuta del dottor Sheng sul tuo dispositivo di mappatura. Ma devo avvertirti che potrebbe essere molto pericoloso. Naturalmente, e' sempre pericoloso nelle Lande. Comunque, se trovi qualcosa di interessante, fammelo sapere.}
{371}{}{Grazie, lo farò. Arrivederci.}
{372}{}{Lascia che ti chieda qualcos'altro.}
{380}{}{Il dottor Sheng e' ancora vivo e ha creato una sorta di pianta che mette radici e controlla i cadaveri umani.}
{390}{}{Dunque ha ottenuto qualche successo con il suo Progetto Xeno. Affascinante... e inquietante. Abbiamo posto fine ai suoi esperimenti sulle piante senzienti dopo aver perso uno dei nostri tecnici. Quando se ne ando' per continuare le sue ricerche, pensai che sarebbe caduto vittima delle sue stesse creazioni. E' riuscito a ottenere una qualche forma di controllo su di esse?}
{391}{}{Si, alcune sembrano essere sottomesse. Lo chiamano persino "maestro."}
{400}{}{Hmm... Se riuscisse in qualche modo a creare un esercito di quelle creature vegetali, non sarebbe affatto un bene per gli Shi. Speravo non si arrivasse a questo, ma sembra che non abbiamo altra scelta che assicurarci che il dottor Sheng e i suoi esperimenti vengano eliminati. Dato che si fida abbastanza di te da permetterti di avvicinarti, sei il candidato migliore. E' qualcosa che saresti disposto a fare? Verresti ricompensato, naturalmente.}
{401}{}{Sarebbe un piacere. Lui e tutta la sua operazione mi fanno venire i brividi.}
{402}{}{Di che tipo di compenso stiamo parlando?}
{403}{}{Non mi interessa. Il dottor Sheng è un vostro problema: arrangiatevi voi.}
{410}{}{Gli Shi ti saranno estremamente grati per questo servizio. Una volta che il dottor Sheng e tutte le sue creazioni saranno stati eliminati, torna da me per ricevere la tua ricompensa.}
{411}{}{[FATTO]}
{420}{}{Lo lascio decidere a te. Possiamo offrirti armi, provviste o denaro. Potrai scegliere una volta completato il compito.}
{421}{}{D'accordo. Lo farò.}
{422}{}{Non mi interessa. Il dottor Sheng è un vostro problema: arrangiatevi voi.}
{423}{}{D'accordo. Lo faro'. Ma prima di andare, il dottor Sheng voleva che ti consegnassi questo campione vegetale. Ha detto che dovrebbe aiutarvi a raggiungere l'obiettivo di creare vita vegetale resistente alle radiazioni.}
{430}{}{D'accordo. Ci occuperemo noi del problema, ma per ora dovremo aspettare, dato che al momento non disponiamo delle risorse necessarie. Speriamo che non sia troppo tardi quando potremo intervenire. Nel frattempo, se dovessi cambiare idea, fammelo sapere.}
{431}{}{Non contarci. Addio.}
{432}{}{Ci penserò. Arrivederci.}
{433}{}{Vedremo. Lascia che ti chieda qualcos'altro.}
{440}{}{Hai cambiato idea? Ci aiuterai a eliminare il dottor Sheng e le sue creature?}
{441}{}{No, volevo chiederti qualcos'altro.}
{442}{}{D'accordo, me ne occuperò io.}
{443}{}{Lo faro', ma per un prezzo. Stavi parlando di compenso prima?}
{450}{}{I nostri esploratori hanno riferito che il dottor Sheng e i suoi esperimenti sono stati distrutti. Che spreco di una mente brillante... Ad ogni modo, puoi reclamare la tua ricompensa. Ti interessano armi, rifornimenti o denaro?}
{451}{}{Le nostre spie hanno riferito che il Dottor Sheng e i suoi esperimenti sono stati distrutti. Che spreco di una mente brillante... Comunque, non ti abbiamo mai chiesto di coinvolgerti cosi' tanto, ma siamo grati. Per i tuoi problemi, puoi reclamare una ricompensa. Sei interessato ad armi, rifornimenti o denaro?}
{452}{}{Prenderò delle armi.}
{453}{}{Un po' di provviste in più fanno sempre comodo.}
{454}{}{Dammi solo dei soldi.}
{455}{}{Tieniti la ricompensa. L'ho fatto solo perche' era la cosa giusta da fare.}
{460}{}{Eccoti. [Ti porge varie armi ad alto potenziale]}
{461}{}{[FATTO]}
{470}{}{Eccoti. [Ti porge vari rifornimenti]}
{471}{}{[FATTO]}
{480}{}{Eccoti. [Ti porge 5.000 dollari]}
{481}{}{[FATTO]}
{490}{}{Gli Shi apprezzano il tuo aiuto. Ora, ho molto lavoro da fare. Buona giornata.}
{491}{}{[FATTO]}
{500}{}{Prima di andare, il Dottor Sheng voleva che ti consegnassi questo campione di pianta. Ha detto che dovrebbe aiutarti a raggiungere l'obiettivo di creare flora resistente alle radiazioni.}
{501}{}{Il Dottor Sheng voleva che ti consegnassi questo campione di pianta. Ha detto che dovrebbe aiutarti a raggiungere l'obiettivo di creare flora resistente alle radiazioni.}
{502}{}{Il Dottor Sheng voleva che ti dessi questo campione di pianta come regalo, ma ho pensato di doverti avvertire che e' infuso con il suo siero della coscienza. Non so cosa dovrebbe fare, ma sono abbastanza sicuro che non sara' una buona cosa per gli Shi.}
{510}{}{Interessante. [Prende il campione e lo ripone.] Il mio team ed io lo esamineremo piu' tardi. Non posso dire di fidarmi di nessun regalo del Dottor Sheng, ma suppongo che ci sia una remota possibilita' che si riveli utile. Lo vedremo. Ora se non c'e' altro, dovrei tornare al lavoro.}
{511}{}{Interessante. [Prende il campione e lo ripone.] Il mio team ed io lo esamineremo piu' tardi. Non posso dire di fidarmi di nessun regalo del Dottor Sheng, ma suppongo che ci sia una remota possibilita' che si riveli utile. Lo vedremo. Ma pensavo che dovessi eliminare il Dottor Sheng, non fare il suo corriere? In ogni caso, dovrei tornare al lavoro.}
{512}{}{In realtà vorrei chiederti qualcos'altro.}
{513}{}{Arrivederci.}
{514}{}{In realta', ho fatto parecchia fatica per procurarti quel campione. Credo che valga una ricompensa.}
{520}{}{Davvero? Gli Shi non ti hanno richiesto questo campione di pianta, ma se ritieni che le tue azioni abbiano guadagnato un compenso, suppongo che potremmo cedere questo. [Ti porge un Super Stimpak.] Ora devo davvero tornare al lavoro.}
{521}{}{In realtà vorrei chiederti qualcos'altro.}
{522}{}{Grazie. Ciao.}
{523}{}{Davvero? Chiami questa una ricompensa? Ti faccio a pezzi finche' non cade fuori qualcosa di piu' prezioso.}
{530}{}{[Prende il seme.] Grazie, lo elimino immediatamente. [Sospira.] Sapevo che il Dottor Sheng aveva perso la testa, ma non pensavo si sarebbe spinto fino a cercare di distruggere il suo stesso popolo. Deve essere eliminato immediatamente.}
{531}{}{Sono d'accordo. È completamente fuori di testa.}
{540}{}{*si porta la mano al cuore* Wahh.}
{541}{}{Urgh.}
{542}{}{Dottor Wong!}
{600}{}{Elimini il dottor Sheng per gli Shi.}
{601}{}{Consegni il campione di pianta al dottor Wong.}
{602}{}{Hai assassinato il dottor Wong.}
