{100}{}{Vedi un uomo che sembrerebbe proprio essere un negoziante.}
{101}{}{Vedi Lao Chou, il negoziante.}
{102}{}{Vedi un uomo in abiti comodi e funzionali.}
{103}{}{Salve! Benvenuto nel mio negozio, il Drago Volante 8.}
{104}{}{Cosa posso fare per te?}
{105}{}{Da aggle oo!}
{106}{}{Roba!}
{107}{}{Chi sei?}
{108}{}{Vorrei dell'equipaggiamento.}
{109}{}{Sto cercando delle informazioni.}
{110}{}{Addio.}
{111}{}{Vuoi comprare qualcosa?}
{112}{}{::fai cenno di si' con la testa::}
{113}{}{::fai cenno di no con la testa::}
{114}{}{Questo e' quello che abbiamo.}
{115}{}{[FATTO]}
{116}{}{Beh, temo che questo sia tutto quello che posso fare per lei. Buona giornata.}
{117}{}{[FATTO]}
{118}{}{Io sono Lao Chou. Sono il proprietario di questo esercizio commerciale, il Dragone Volante 8, un emporio. Sono noto per la mia compravendita di... informazioni.}
{119}{}{Che tipo di informazioni?}
{120}{}{Capisco. Vorrei acquistare dell'equipaggiamento.}
{121}{}{Poche cose in questa citta' accadono senza che io lo sappia. Naturalmente, lei deve conoscere la domanda giusta da farmi, si'? Cosa le serve sapere?}
{122}{}{Sto cercando dei potenziamenti per il mio equipaggiamento.}
{123}{}{Dove posso trovare degli schemi tecnici di un vertibird?}
{124}{}{Ho bisogno di trovare del carburante per la petroliera VMP Valdez.}
{125}{}{Mi e' stato detto che mi serve un FOB per accedere al computer della Valdez.}
{126}{}{Ho bisogno di alcuni componenti per il computer del VMP Valdez.}
{127}{}{Sto cercando una milza.}
{128}{}{Mi e' stato detto che alcune macchine volanti hanno portato qui un carico di selvaggi.}
{129}{}{Nulla. Arrivederci.}
{130}{}{Parli con Crocket, giu' al campo Hubologista. E' il loro scienziato capo.}
{131}{}{Grazie. Vorrei delle altre informazioni.}
{132}{}{Grazie. Ciao.}
{133}{}{Provi a nord, a Navarro. C'e' una base segreta vicino alla pompa di benzina.}
{134}{}{Grazie. Vorrei delle altre informazioni.}
{135}{}{Grazie. Ciao.}
{136}{}{Ha provato a cercare nei vecchi Vault? Ho sentito dire che sono una vera miniera di informazioni e tecnologia degli antenati.}
{137}{}{Grazie. Vorrei delle altre informazioni.}
{138}{}{Grazie. Ciao.}
{139}{}{Una milza? Ah ah! Si', Chip della Valdez ha perso la sua milza durante una partita a carte, l'altro giorno. L'ho venduta al dottor Wong. Ne era affascinato.}
{140}{}{Il dr. Wong? Dove posso trovarlo?}
{141}{}{Come si fa a perdere la milza?}
{142}{}{Grazie. Ho delle altre domande.}
{143}{}{Ah, e' cosi'... Arrivederci.}
{144}{}{Il dr. Wong e' il capo scienziato del Palazzo d'Acciaio. Provi a cercarlo li'.}
{145}{}{Come si fa a perdere la milza, comunque?}
{146}{}{Grazie. Vorrei delle altre informazioni.}
{147}{}{Grazie. Ciao.}
{148}{}{Era ubriaco. Molto, molto ubriaco. Per tutta la notte e' rimasto fissato con la sua milza. E allora l'ha scommessa.}
{149}{}{E cosi' tu hai preso la sua MILZA?}
{150}{}{Capisco. Beh, ho delle altre domande.}
{151}{}{Si'. Era un debito. E' un uomo onorevole.}
{152}{}{Capisco. Mi servono altre informazioni.}
{153}{}{Sei un rozzo bastardo malato, non e' vero?}
{154}{}{Certo. Addio.}
{155}{}{Lei e' una persona disonorevole. Non voglio averla nel mio negozio. Torni un'altra volta.}
{156}{}{Vabbe'.}
{157}{}{No, non e' esatto. Arrivavano da nord e hanno sorvolato la citta', dirigendosi poi verso il mare aperto.}
{158}{}{Al di la' dell'orizzonte? Come diavolo ci arrivo laggiu'?}
{159}{}{Si', certo, hanno fatto cosi'... Dimmi dove si trovano prima che ti apra come una scatola di sardine.}
{160}{}{Beh... nessuna delle nostre barche e' in grado di coprire una simile distanza. A meno che...}
{161}{}{A meno che...?}
{162}{}{Grazie dell'"aiuto". Andro' a cercare qualcuno che mi sia davvero utile.}
{163}{}{...a meno che lei non riesca a far funzionare la vecchia petroliera giu' al porto. E' una vecchia nave, ma probabilmente puo' ancora funzionare, se ci si lavora un po'. Chieda ai punk per altre informazioni.}
{164}{}{Grazie. Vorrei delle altre informazioni.}
{165}{}{Grazie. Ciao.}
{166}{}{Voci dicono che gli Hubologisti sono entrati in possesso di una grande quantita' di carburante, recentemente. Provi a contrattare con loro.}
{167}{}{Grazie. Vorrei delle altre informazioni.}
{168}{}{Grazie. Ciao.}
{169}{}{Potrebbe provare con qualcuno degli scienziati Shi all'interno del Palazzo d'Acciaio. Forse loro potranno fornirle il carburante che le serve.}
{170}{}{Grazie. Vorrei delle altre informazioni.}
{171}{}{Grazie. Ciao.}
{172}{}{Tu sei un nemico della mia gente. Muori!}
{173}{}{Ha reso un grande servizio alla mia gente, assassinando AHS-9. Spero di poterle essere d'aiuto in qualche modo.}
{174}{}{Chi sei?}
{175}{}{Vorrei dell'equipaggiamento.}
{176}{}{Sto cercando delle informazioni.}
{177}{}{Addio.}
{178}{}{Li ha gia' consegnati agli Hubologisti. No?}
{179}{}{Oh, certo... ahem... Posso chiederle qualcos'altro?}
{180}{}{Oh, certo... Arrivederci.}
{200}{}{What else can you tell me about the tanker?}
{210}{}{Even if you could get the NavCom working and the tanker fueled up, you'll still need considerable good fortune
 if you really want the ship to sail again.}
{211}{}{What do you mean by 'considerable good fortune?'}
{220}{}{I mean, the hunk of junk is older than most ghouls. It would be a miracle if it didn't sink on you. That is all
 I meant.}
{221}{}{I have a feeling that there's something you're not telling me about the tanker.}
{230}{}{Perhaps there is. (smiles) Perhaps the wasteland has made you paranoid.}
{231}{}{Listen, I need to find my tribe. Those bastards who took them are dangerous and need to be stopped.}
{232}{}{Come on. What's so special about the tanker? We're just two people talking.}
{233}{}{You sure? I'll make it worth your while.}
{234}{}{I don't have time for these mind games. Goodbye.}
{240}{}{Bah. They are nothing. However, it's not the tanker that's special. It's just a big rusty tanker like you said.
 Our submarine, on the other hand...}
{241}{}{Submarine?}
{250}{}{Let's talk, then. But there's nothing special about the tanker. I give you my word.}
{251}{}{What if I paid you to tell me?}
{260}{}{Hmm... Business has been slow lately. I could use more customers. Or a donation from a very generous one. Say, $2000?}
{261}{}{Here you go. But your information better be worth it.}
{262}{}{$1500 and that's my final offer.}
{263}{}{I don't think so. That's too much.}
{270}{}{(Lao Chou pockets the $2000.) It's not the tanker that's special. It's just a big rusty tanker like you said.
 Our submarine, on the other hand...}
{271}{}{Submarine?}
{280}{}{We have nothing further to discuss, then.}
{281}{}{You sure? My lovely wife Miria will certainly make it worth your while.}
{282}{}{Arrivederci.}
{285}{}{You drive a hard bargain. Fine, $1500.}
{286}{}{Here you go. But your information better be worth it.}
{287}{}{(Lao Chou pockets the $1500.) It's not the tanker that's special. It's just a big rusty tanker like you said.
 Our submarine, on the other hand...}
{288}{}{Submarine?}
{290}{}{Well if you put it that way, I have been cooped up in this dusty shop for a long time. It has been a quite a while since
 I enjoyed the company of a charming woman like yourself.}
{291}{}{[CONTINUA]}
{300}{}{[Hours past with no end in sight. You begin to suspect that Lao Chou may not be completely human. You black out, eventually.]}
{301}{}{hhh... What happened?}
{310}{}{You fainted as I moved us into the triple-lotus position, and I had to finish pleasuring myself with the grinning-panda kata.
 But a deal's a deal. It's not the tanker that's special -- it's just a big rusty tanker like you said. Our submarine, on the other hand...}
{311}{}{Submarine?}
{330}{}{I... don't think so.}
{331}{}{Don't try and fight it now. You want me and you know it.}
{340}{}{No, actually. You are not my type.}
{341}{}{Oh, I see. You're not into women.}
{350}{}{I am. I just do not find you very attractive. Perhaps if I were drunk.}
{351}{}{You're obviously blind. Whatever. It's your loss.}
{360}{}{What are you proposing? Ahh... well, I have been cooped up in this shop for a long time. I will reveal all I know
 in exchange for a sample of your lady friend's charms.}
{361}{}{Miria, tesoro... credo che dovrai, ehm, spremere questo tizio per ottenere informazioni.}
{362}{}{Scherzavo, vecchio. Come se ti lasciassi passare del tempo con mia moglie... Me ne vado.}
{370}{}{[Aspetti fuori e senti gemiti soffocati provenire dall'interno del Flying Dragon 8. Passa un'ora, poi un'altra.
 Bussi alla porta gridando: "Sbrigatevi la' dentro!" Alla fine, i gemiti diventano un urlo primordiale.]}
{371}{}{[Bang on the door] Hey, what are you two doing in there!?}
{380}{}{Un Lao Chou sorridente esce dalla sua stanza, ancora intento a tirarsi su i pantaloni. Pochi istanti dopo Miria barcolla fuori dietro di lui, stordita e confusa ma profondamente soddisfatta.] Tua moglie e' molto piu' esperta di quanto sembri.}
{381}{}{Lo... ehm... so. Ora tirati su quei dannati pantaloni e dimmi cosa c'e' di cosi' speciale nella petroliera.}
{390}{}{Non c'e' nulla di speciale nella petroliera. E' solo una grande petroliera arrugginita, come hai detto tu. Il nostro sottomarino, invece...}
{391}{}{Submarine?}
{400}{}{Lo Shi?Huang?Ti. Mio bisnonno, Ye Li, ne era il capitano. Scateno' i suoi fuochi nucleari come un terribile drago sulla costa della California.}
{401}{}{No shit.}
{410}{}{Ironia della sorte, un missile difettoso della nostra stessa nazione ancestrale usci' dalla rotta ed esplose sull'oceano vicino al sottomarino. L'esplosione mise fuori uso i sistemi dello Shi?Huang?Ti, lasciando il capitano Ye Li e il suo equipaggio alla deriva.}
{411}{}{That's karma for you.}
{420}{}{Ma ci fu salvezza. Dopo settimane alla deriva, il sottomarino si fermo' nelle acque basse della baia di San Francisco.
 Questa citta' divenne la nostra nuova casa. Alla fine restaurammo lo Shi?Huang?Ti: i suoi sistemi di puntamento, le sue armi.
 Ha abbastanza potenza di fuoco da spazzare via qualsiasi invasore. Quindi, anche se riuscissi a far partire quella vecchia petroliera,
 non andrebbe lontano: il sottomarino distruggera' qualsiasi nave non cinese che attraversi la baia.}
{421}{}{That sounds like a problem alright. So how would I get to the submarine?}
{430}{}{Puoi nuotare. Oppure prendere il motoscafo al molo. Ma e' sorvegliato da uno dei nostri migliori soldati, e non lascera' passare un estraneo come te.}
{431}{}{Hai idea di come potrei passare, allora, senza sparargli in faccia?}
{440}{}{E' sotto ordini severi di sorvegliarlo 24 ore su 24. Non lascera' passare nessuno senza la password corretta.}
{441}{}{I don't suppose you know it?}
{450}{}{Dipende. Non e' che per caso hai 10000$ per garantire la continua prosperita' del mio negozio?}
{451}{}{Here's your $10000.}
{452}{}{E' assurdo per una semplice password. Arrivo al massimo a 5000$.}
{453}{}{No.}
{460}{}{Ah, molto apprezzato. La password e' XY8QIV2SHI. Potrebbero tenermi d'occhio dopo questo, quindi non dimenticarla. Se dovessimo parlarne di nuovo, avro' bisogno di ancora piu' soldi per le tangenti.}
{461}{}{Grazie. Arrivederci.}
{470}{}{Sei furbo, questo te lo concedo. Va bene. Accetto la tua offerta. La password e' XY8QIV2SHI. Non dimenticarla, o dovrai ricomprarla da me.}
{471}{}{Grazie. Arrivederci.}
{480}{}{Don't insult me with your meager offers. $10000. Take it or leave it.}
{481}{}{Fine. Here's your $10000.}
{482}{}{No.}
{490}{}{Your loss then. I don't believe we have anything else to discuss. Goodbye.}
{491}{}{Addio.}
