{100}{}{Vedi un umanoide ricoperto di vegetazione. Gocciola melma verde.}
{101}{}{You see one of Dr. Sheng's foul creations.}
{102}{}{You see one of Dr. Sheng's foul creations. It looks like this one didn't turn out so well.}
{200}{}{Speak to the master, human.}
{201}{}{Your body would make a fine host...}
{202}{}{Il maestro ha detto che non possiamo toccarti... per ora.}
{300}{}{[Una mezza dozzina di strane creature umanoidi avanza barcollando verso di te. I loro corpi cadaverici coperti di rampicanti e muschio emettono suoni ripugnanti a ogni passo. La creatura in testa ti parla con un raschio aspro.] Il maestro vuole parlarti. Vieni con noi, umano, e non resistere... o faremo di te un ospite.}
{301}{}{[Scrolli le spalle] Questo dovrebbe essere interessante. Fate strada.}
{302}{}{I'm not going anywhere with you, plant ... creature ... things.}
{303}{}{Non ho tempo per queste stronzate.}
{304}{}{Aspettate. Chi e' il vostro maestro? E voi cosa siete, esattamente?}
{310}{}{Non hai scelta, umano. O vieni a parlare con il Maestro, oppure ricorreremo alla violenza.}
{311}{}{Then let's dance.}
{312}{}{All right. I'll meet this master of yours.}
{320}{}{Master will answer all questions. Now, come.}
{321}{}{Non credo proprio.}
{322}{}{All right. I'll meet this master of yours.}
{400}{}{Uuuhhhhh...}
{401}{}{Grrraaah!}
{402}{}{Hheesssss...}
{403}{}{Ohhh...}
{410}{}{The master says no one may enter.}
{420}{}{The master says you may enter, human.}
{500}{}{Spruzzi la creatura e questa emette un gemito profondo. Parti della vegetazione che la ricopre cadono flosce a terra.}
{501}{}{Spruzzi la creatura; emette un gemito profondo e si scioglie in una pozza davanti ai tuoi occhi.}
