{100}{}{Vedi un umanoide ricoperto di vegetazione. Gocciola melma verde.}
{101}{}{Vedi una delle disgustose creazioni del dottor Sheng.}
{102}{}{Vedi una delle creazioni del dottor Sheng. Sembra che questa non sia riuscita molto bene.}
{200}{}{Parla con il maestro, umano.}
{201}{}{Il tuo corpo sarebbe un ottimo ospite...}
{202}{}{Il maestro ha detto che non possiamo toccarti... per ora.}
{300}{}{[Una mezza dozzina di strane creature umanoidi avanza barcollando verso di te. I loro corpi cadaverici coperti di rampicanti e muschio emettono suoni ripugnanti a ogni passo. La creatura in testa ti parla con un raschio aspro.] Il maestro vuole parlarti. Vieni con noi, umano, e non resistere... o faremo di te un ospite.}
{301}{}{[Scrolli le spalle] Questo dovrebbe essere interessante. Fate strada.}
{302}{}{Non vengo da nessuna parte con voi… piante… creature… qualunque cosa siate.}
{303}{}{Non ho tempo per queste stronzate.}
{304}{}{Aspettate. Chi e' il vostro maestro? E voi cosa siete, esattamente?}
{310}{}{Non hai scelta, umano. O vieni a parlare con il Maestro, oppure ricorreremo alla violenza.}
{311}{}{Allora balliamo.}
{312}{}{D'accordo. Incontrerò il vostro maestro.}
{320}{}{Il Maestro risponderà a tutte le domande. Ora vieni.}
{321}{}{Non credo proprio.}
{322}{}{D'accordo. Incontrerò il vostro maestro.}
{400}{}{Uuuhhhhh...}
{401}{}{Grrraaah!}
{402}{}{Hheesssss...}
{403}{}{Ohhh...}
{410}{}{Il Maestro dice che nessuno può entrare.}
{420}{}{Il Maestro dice che puoi entrare, umano.}
{500}{}{Spruzzi la creatura e questa emette un gemito profondo. Parti della vegetazione che la ricopre cadono flosce a terra.}
{501}{}{Spruzzi la creatura; emette un gemito profondo e si scioglie in una pozza davanti ai tuoi occhi.}
