{100}{}{You see a person in funny pajamas. He seems preoccupied.}
{101}{}{You see a Shi submarine technician.}
{150}{}{Uh, what are you doing, sneaking around like that?}
{151}{}{Are you some kind of spy?}
{200}{}{I hate working with this junk.}
{201}{}{Let's recalibrate this... there.}
{202}{}{Tutti quei cavi scoperti e nessuna traccia di isolamento...}
{203}{}{Spero di non restare folgorato mentre ricarico il generatore.}
{300}{}{Hey, I'm busy here.}
{301}{}{Sorry, I'm working.}
{302}{}{Questi cavi non si aggiusteranno da soli, trova qualcun altro da importunare.}
