{100}{}{You see a person in funny pajamas. He seems preoccupied.}
{101}{}{You see a Shi submarine technician.}
{150}{}{Uh, what are you doing, sneaking around like that?}
{151}{}{Are you some kind of spy?}
{200}{}{Sarebbe piu' facile se il mio cinese fosse migliore...}
{201}{}{Errore I/O!? Come puo' un sistema di guida avere un errore I/O!?}
{202}{}{001100010010011110100001101101110011? Dov'e' la mia tabella dei codici di errore...}
{203}{}{Vorrei che il database IFF funzionasse ancora. Renderebbe tutto molto piu' semplice.}
{300}{}{Cosa vuoi, lao wai? Non vedi che sto cercando di riconfigurare i sistemi di puntamento?}
{301}{}{In realta' sono qui proprio per questo. Ho nuove specifiche per quei sistemi, controllate dall'Imperatore, ehm, personalmente. Puoi inserirle? Sembri il piu' competente su questo sottosistema.}
{302}{}{E' per questo che sono qui, posso aiutarti a configurare i sistemi. Sembra che la connessione tra il sottosistema di navigazione marittima e il transponder IFF sia finalmente morta, quindi devi fare un aggiramento. Ti dispiace se ti aiuto?}
{303}{}{Sorry to bother you.}
{310}{}{Oh, aspettavo queste nuove specifiche da secoli! Dovevi essere qui una settimana fa, quando stavo lavorando a quel che restava del database di battaglia. Ora devo riaprirlo di nuovo... Oh beh, la vita di un tecnico, immagino.}
{311}{}{Have fun. I'll see what else needs fixing.}
{320}{}{Non ti conosco affatto! Per quanto ne so, lao wai, potresti essere una specie di spia straniera, venuta qui per disattivare questo sottomarino, cosi' il tuo piano di attraversare i mari verso luoghi strani puo' compiersi senza che i siluri affondino la tua barca! Sono certo che Ken Lee non lascerebbe mai salire sullo Shi?Huang?Ti uno sconosciuto con cattive intenzioni, quindi mi dispiace, ma non posso accettare queste coordinate a meno che non mi arrivino dal nostro leader in persona.}
{321}{}{Be', posso almeno aiutarti a configurare il sottomarino? Ho un po' di esperienza con sistemi informatici antichi, abbastanza da capire come un sistema a valvole di 200 anni possa rifiutarsi di obbedire al suo padrone.}
{322}{}{Alright, sorry to bother you.}
{330}{}{Immagino di poter usare il tuo aiuto, tieni, prova tu. [Il tecnico Shi ti lascia prendere i comandi. Dopo qualche istante per familiarizzare con l'interfaccia, inizi a lavorare. Pochi minuti dopo non solo hai riconfigurato i parametri di puntamento, cosi' il sottomarino non affonda la petroliera, ma hai anche rimosso un guasto che impediva ai tecnici di accedere facilmente al sottosistema.]}
{331}{}{Okay, ecco fatto. Ho sistemato il sistema. Non dovrebbe darti piu' problemi. Spero ti aiuti nel tuo lavoro.}
{340}{}{Grazie per l'aiuto, e' difficile trovare un buon tecnico informatico di questi tempi.}
{350}{}{Mi dispiace, ma no. Potresti rompere qualcosa e perderemmo il sottosistema per sempre, e io *non* ho intenzione di impostare i moduli di acquisizione dei bersagli dei siluri a mano. Quindi, a meno che tu non abbia qualcosa di *importante* per me, lasciami tornare al lavoro.}
{351}{}{In realta' si'. Ho nuovi parametri di puntamento per i siluri, controllati dall'Imperatore, ehm, in persona. Sei tu il mago dei computer qui, quindi penso di potermi fidare di te per questo.}
{352}{}{Sorry to bother you.}
{360}{}{No, non ho bisogno di aiuto ne' di nuovi dati. Sono qui per lavorare e tu mi stai impedendo di farlo, quindi vattene o faro' in modo che ti portino *via*!}
{361}{}{Sorry to bother you.}
{370}{}{Hey, I'm busy here.}
{371}{}{Sorry, I'm working.}
{400}{}{You tricked the technician into disabling the submarine.}
