{100}{}{Vedi una persona con uno strano pigiama. Sembra preoccupato.}
{101}{}{Vedi un tecnico del sottomarino degli Shi.}
{150}{}{Uh… perché ti muovi così furtivamente?}
{151}{}{Sei una specie di spia?}
{200}{}{Odio lavorare con questa ferraglia.}
{201}{}{Ricalibriamo questo… ecco fatto.}
{202}{}{Tutti quei cavi scoperti e nessuna traccia di isolamento...}
{203}{}{Spero di non restare folgorato mentre ricarico il generatore.}
{300}{}{Ehi, sono occupato qui.}
{301}{}{Scusa, sto lavorando.}
{302}{}{Questi cavi non si aggiusteranno da soli, trova qualcun altro da importunare.}
