{100}{}{You see a person in funny pajamas. He seems preoccupied.}
{101}{}{You see a Shi submarine technician.}
{150}{}{Uh, what are you doing, sneaking around like that?}
{151}{}{Are you some kind of spy?}
{200}{}{E' disgustoso, guarda tutta quella ruggine!}
{201}{}{Non capisco perche' dobbiamo continuare a far funzionare questa cosa.}
{202}{}{Those torpedoes are an accident waiting to happen.}
{300}{}{Non ricordo di averti mai visto da queste parti, cosa ci fai nella sala siluri? E chi sei, esattamente?}
{301}{}{Ancora tu? Cosa ci fai ancora nella sala siluri? E chi sei, esattamente?}
{302}{}{Sono un'aggiunta dell'ultimo minuto alla vostra squadra tecnica. Scusa se non ti ho avvisato prima. Oh, e sono qui per fare un po' di manutenzione ai siluri. Sembrano terribili, un incidente che aspetta solo di accadere!}
{303}{}{Sono stato aggiunto alla vostra lista solo di recente. Mi hanno chiesto di lavorare sui sistemi di puntamento dei siluri, visto che ultimamente danno problemi. Credo possa dipendere da certi difetti non correggibili nel design delle schede madri Sungsam.}
{304}{}{Sono un riparatore, appena aggiunto alla vostra lista. Dovrei fare la manutenzione periodica ai siluri, visto che sono messi malissimo! 
Guarda tutta quella ruggine! E le eliche sembrano sul punto di staccarsi!}
{305}{}{Sorry, wrong room.}
{310}{}{Oh, finalmente un meccanico qualificato a bordo. Volevo sistemarli da tempo, ma non riesco a superare la mia paura di quei siluri. 
Sapevi che trasportano abbastanza esplosivo da trasformare l'intera nave in rottami finissimi?}
{311}{}{Faro' attenzione, lo prometto.}
{320}{}{Finalmente mi hanno mandato un meccanico, dopo tutte quelle settimane a supplicare...}
{330}{}{Uh, non sembri un meccanico. Sinceramente, non credo tu sappia distinguere una chiave inglese da un cacciavite, a giudicare dall'aspetto. 
Perche' non torni ad aiutare gli altri invece di bighellonare nella sala siluri? Non voglio che ci fai saltare in aria per sbaglio.}
{331}{}{Bene, me ne vado.}
{340}{}{Tutto bello, ma... perche' stai cercando la console nella sala siluri? E' nella stanza dietro di te. Ho bisogno di un meccanico, non di un altro tecnico, quindi a meno che tu non sia anche un riparatore capace, ho bisogno che tu vada.}
{341}{}{In realta' si', sono anche un riparatore, con parecchia esperienza nella tecnologia antica. Credo di poter gestire quei siluri. 
Rimettero' a posto le eliche e mi assicuro che non ci trasformino in rottami finissimi.}
{342}{}{Bene, me ne vado.}
{350}{}{Oh, specialisti in entrambi i campi non sono comuni nelle Lande. Credo di potermi fidare di te, quindi vai e sistema quei
 siluri cosi' posso finalmente sentirmi un po' piu' al sicuro.}
{351}{}{Okay.}
{360}{}{Hey, I'm busy here.}
{361}{}{Sorry, I'm working.}
{370}{}{Don't touch that!}
{371}{}{What did I tell you?!}
{372}{}{Ti avevo avvertito!}
{375}{}{What the hell are you doing! Guards!}
{380}{}{Stop wasting time and get to work.}
