{100}{}{Questo portello sembra strano – a differenza del resto dell'imbarcazione, e' relativamente privo di ruggine e ha una serratura
 intricata e complessa.}
{200}{}{Lotti con il portello, ma alla fine riesci a strapparlo. Pezzi della serratura rotta ricoprono la
 torre e scricchiolano sotto i tuoi stivali.}
{201}{}{Fai del tuo meglio, ma il portello proprio non si muove. Forse degli esplosivi potrebbero aiutare.}
{202}{}{Sembra che il portello possa essere aperto applicando abbastanza forza. Marcus potrebbe aiutare con quello.}
{210}{}{Hey Marcus, can you help me open this hatch?}
{211}{}{Sure, just give me some room.}
{212}{}{*hrrrgnnnr*}
{213}{}{Il supermutante fatica a sollevare il portello. Per un momento sembra che stia per spaccarsi in due, ma
 proprio allora lo strappa, spargendo pezzi della serratura rotta sulla torre.}
{220}{}{Trafficchi con la serratura per un po' e la apri. Scassinare e' decisamente piu' di un semplice hobby per te.}
{221}{}{Trafficchi con la serratura, ma alla fine rinunci. Deve esserci un altro modo per aprirla.}
{230}{}{The explosion rips open the hatch and the lock, apart from deafening you.}
{240}{}{Trafficchi con la serratura per un po' e la richiudi. Scassinare e' decisamente piu' di un semplice hobby per te.}
{241}{}{Trafficchi con la serratura, ma alla fine rinunci. Deve esserci un altro modo per richiuderla.}
