{100}{}{Vedi una vecchia console.}
{101}{}{La console di alimentazione e' quasi completamente distrutta. Fili sporgono in ogni direzione, tenuti insieme dal nastro adesivo,
 e il monitor di stato sembra rotto. Questo aggeggio si regge insieme a malapena.}
{200}{}{Esamini la console e i cavi allentati. Sembra che qualcuno con un po' di abilita' nelle riparazioni (o un piede di porco)
 potrebbe disabilitare completamente il sottosistema di alimentazione.}
{210}{}{La console cede rapidamente e il generatore di emergenza si spegne. Senza energia, il sottomarino non rappresenta alcuna minaccia.}
{211}{}{Non riesci a disattivare il generatore.}
{212}{}{*beep*}
{213}{}{*beeboop*}
