{100}{}{Vedi una vecchia console.}
{101}{}{Sembra che questa consolle gestisca il sistema di lancio e caricamento dei siluri. Come tutto il resto nel sottomarino,
 e' arrugginita fino in fondo e funziona appena.}
{200}{}{Questo sottosistema, se disattivato, dovrebbe impedire che i tubi vengano ricaricati con siluri di riserva. Disattivarlo
 non dovrebbe essere troppo difficile - il metallo si sta letteralmente sgretolando e puoi vedere chiaramente i tubi a vuoto.}
{210}{}{Proprio come pensavi - il metallo cede facilmente e la consolle viene presto smontata. Questo sottomarino non sara' in grado
 di ricaricare i suoi tubi tanto presto.}
{211}{}{Non riesci a disattivare il sistema.}
{212}{}{*beep*}
{213}{}{*beeboop*}
