{100}{}{Vedi una vecchia console.}
{101}{}{Sembra che questa sia la vecchia console di controllo dei bersagli dei siluri. La maggior parte dei monitor e' rotta o mancante, con
 solo uno appena funzionante. Di tanto in tanto compaiono frammenti casuali di dati sullo schermo tremolante.}
{200}{}{Sembra che il sistema operativo sia corrotto, dato che non risponde ai tuoi comandi come dovrebbe. Potresti
 capirci qualcosa adottando un approccio piu' scientifico.}
{210}{}{Con alcuni comandi avanzati, il sistema viene sovvertito e inizia a comportarsi correttamente. Qualche tasto dopo, i
 sistemi di guida dei siluri sono disattivati e predisposti per esplodere pochi istanti dopo aver lasciato i tubi. Scienza!}
{211}{}{Armeggi col sistema per qualche minuto, ma e' troppo compromesso per riuscire a salvarlo. Sembra che
 tu debba trovare un altro modo per disattivare i siluri.}
{212}{}{*beep*}
{213}{}{*beeboop*}
