{100}{}{Vedi dei siluri.}
{101}{}{Queste armi dall'aspetto pericoloso sono piene fino all'orlo di esplosivi. I rivestimenti sono corrosi e
 sembra che le eliche cadranno da un momento all'altro.}
{200}{}{Nonostante l'aspetto, questo siluro e' ancora un'arma potente. L'elica allentata e' in realta' parte integrante del
 suo sistema di navigazione, conferendogli una manovrabilita' senza precedenti. Sembra che tu debba tirare fuori gli attrezzi per disattivarlo.}
{210}{}{Grazie a due secoli di degrado, il sistema di propulsione arrugginito e' facile da smontare. Pochi istanti dopo, viene rimesso
 insieme, questa volta completamente immobilizzato.}
{211}{}{Il sistema di propulsione completamente arrugginito e' troppo difficile da gestire. I dadi sono bloccati e non riesci proprio a capire
 come staccare l'elica senza tagliarti.}
{220}{}{Hai piazzato degli esplosivi vicino a diversi siluri ad alto potenziale esplosivo. Potrebbe essere una buona idea togliersi
 dai piedi al piu' presto.}
