{100}{}{Vedi il terminale di un computer.}
{101}{}{Vedi il terminale del Computer Imperatore.}
{102}{}{Vedi un computer che come interfaccia usa un "touch screen" integrato. Incisa su di un lato c'e' la scritta "Terminale del Computer Imperatore v8.8".}
{103}{}{Benvenuti. Siete pregati di inserire la password per confermare la vostra identita'.}
{104}{}{::sbava::}
{105}{}{CSPDMSHR-Shih-huang-ti-X9372}
{106}{}{KSLJKJ:Ken-Lee-97313}
{107}{}{TIUASPO-Lo-Shi-S12908}
{108}{}{::viola il sistema di sicurezza del computer::}
{109}{}{Logout.}
{110}{}{Identita' confermata.}
{111}{}{A quale funzione desiderate accedere?}
{112}{}{Diagnostica.}
{113}{}{Database.}
{114}{}{Previsioni.}
{115}{}{Nessuna.}
{116}{}{Rivolgersi all'amministratore di sistema. Arrivederci.}
{117}{}{::viola il sistema di sicurezza del computer::}
{118}{}{::lascia perdere::}
{119}{}{Allarme intruso attivato. Spegnimento in corso. Buona giornata.}
{120}{}{[FATTO]}
{121}{}{Funzioni Diagnostiche?}
{122}{}{Scansione di rete.}
{123}{}{Formattazione disco.}
{124}{}{Controllo integrita' disco rigido.}
{125}{}{Indietro.}
{126}{}{Quale database desiderate consultare?}
{127}{}{Biologia.}
{128}{}{Chimica.}
{129}{}{Fisica.}
{130}{}{Storia.}
{131}{}{Indietro.}
{132}{}{I figli di Shi-town sono in pericolo. Probabilita' che un assassino si insinui tra di loro = 50%.}
{133}{}{Un pericolo e' giunto a Shi-town. Probabilita' che un danno sia causato ai residenti = 75%.}
{134}{}{Probabilita' che il lancio dell'astronave hubologista fallisca = 95%. Cause: Mancanza di carburante, sigillatura inadatta, incapacita' dei leader, mancanza di iniziativa.}
{135}{}{Probabilita' che il "Prescelto" riesca nella sua missione = 15%.}
{136}{}{I dati indicano che l'"Enclave" e' molto piu' potente di quanto ritenuto in precedenza; si consiglia di tenersi alla larga.}
{137}{}{Probabilità che un sottomarino ricompaia in questo gioco: 100%}
{138}{}{Probabilita' che i vagabondi della petroliera si liberino, senza aiuti esterni, delle creature che infestano la loro stiva = 0%. Calcolo dei vantaggi di un eventuale intervento in corso.}
{139}{}{Dati attuali: Petroliera Poseidon Oil inadatta a navigare. Ulteriori dati richiesti.}
{140}{}{Funzione non attiva. Ulteriori dati richiesti.}
{141}{}{[AVANTI]}
{142}{}{Indietro.}
{143}{}{Postazione Biologia: Attiva}
{144}{}{Postazione Biologia: Inattiva}
{145}{}{Postazione Chimica: Attiva}
{146}{}{Postazione Chimica: Inattiva}
{147}{}{Postazione Fisica: Attiva}
{148}{}{Postazione Fisica: Inattiva}
{149}{}{Disattivare Postazione Biologia.}
{150}{}{Disattivare Postazione Chimica.}
{151}{}{Disattivare Postazione Fisica.}
{152}{}{Accedere a Postazione Biologia.}
{153}{}{Accedere a Postazione Chimica.}
{154}{}{Accedere a Postazione Fisica.}
{155}{}{Attivare Postazione Biologia.}
{156}{}{Attivare Postazione Chimica.}
{157}{}{Attivare Postazione Fisica.}
{158}{}{Indietro.}
{159}{}{Formattazione disco: Tutti i dati contenuti andranno persi. Continuare?}
{160}{}{Si'.}
{161}{}{No.}
{162}{}{L'integrita' funzionale del sistema e' del 92%. L'integrita' del nucleo protetto del Computer Imperatore e' del 100%. L'integrita' dei dati e' del 100%. Riscontrati limitati cali di potenza nel Sistema Predittivo - tempo necessario per le riparazioni: 6 giorni. Modulo Predizioni operativo al 15%.}
{163}{}{Indietro.}
{164}{}{Siete sicuri di voler formattare questa unita'? Questo e' un processo irreversibile.}
{165}{}{Si'.}
{166}{}{No.}
{167}{}{Formattazione in corso... formattazione in corso... formattazione completa. Il riavvio richiede l'installazione completa. Spegnimento in corso. Spegnimento... completato...}
{168}{}{[FATTO]}
{169}{}{Dati da consultare: - Programma botanico - Programma genetico - Programma Xeno.}
{170}{}{Programma botanico.}
{171}{}{Programma genetico.}
{172}{}{Programma Xeno.}
{173}{}{Indietro.}
{174}{}{(Dopo circa venti minuti, scopri queste informazioni: I risultati iniziali degli esperimenti sull'eliminazione botanica delle radiazioni si rivelano insoddisfacenti. Il dr. Sheng crea una forma di vita vegetale resistente alle radiazioni - seguono spiacevoli effetti collaterali. Forma di vita vegetale ritenuta troppo pericolosa. Sheng insiste nella sua linea e cerca di integrare il programma botanico con quello genetico.)}
{175}{}{Programma genetico.}
{176}{}{Programma Xeno.}
{177}{}{Indietro.}
{178}{}{(Dopo circa venti minuti riesci a mettere insieme queste informazioni: Studiando le basi del virus FEV, il dr. Long Wang si convince della possibilita' di creare soldati mutanti. Crea un siero che da' risultati interessanti negli esperimenti sui roditori. Si inietta il siero e si dissolve, diventando un ammasso di gelatina. Il dr. Sheng interrompe questa linea di ricerca. Con la morte del dr. Long, il dr. Sheng diventa capo del progetto. Sheng chiede di concentrare le ricerche sulle forme di vita vegetali in grado di eliminare le radiazioni.)}
{179}{}{Programma botanico.}
{180}{}{Programma Xeno.}
{181}{}{Indietro.}
{182}{}{"Il soggetto sul quale speravamo di poter eseguire una serie di importanti esperimenti e' scomparso; si presume che sia stato distrutto o rubato dagli Hubologisti. Ulteriori indagini si sono rivelate vane. Finche' non saranno disponibili altri campioni, questo database rimarra' non operativo." - Dr. Sheng.}
{183}{}{Programma botanico.}
{184}{}{Programma genetico.}
{185}{}{Indietro.}
{186}{}{Database chimico: Carburante e derivati - Polimeri}
{187}{}{Combustibile e derivati.}
{188}{}{Polimeri.}
{189}{}{Indietro.}
{190}{}{(Dopo aver esaminato le complesse formule chimiche e le note di laboratorio, giungi alla conclusione che gli Shi hanno creato un tipo di combustibile a base di estratti di piante terrestri e marine. Pare che gli Shi si siano agganciati a tubature pre-esistenti in modo tale da poter trasferire il combustibile verso varie destinazioni.)}
{191}{}{(Ti imbatti in una vasta serie di formule chimiche complesse e note di laboratorio. Non sei molto sicuro di cosa possano significare.)}
{192}{}{Inviare il combustibile alla petroliera Poseidon.}
{193}{}{Inviare il combustibile agli Hubologisti.}
{194}{}{Indietro.}
{195}{}{(Dopo aver superato la simbologia e le disquisizioni tecniche, scopri che gli Shi stanno lavorando a un nuovo tipo di armatura da combattimento polimerica, resistente alle fiamme e alla penetrazione. E' ancora molto lontana dall'essere completata. Trovi anche degli accenni a nuove armi e a moderne tecniche di costruzione. Apparentemente gli Shi hanno dei piani per il futuro.)}
{196}{}{Indietro.}
{197}{}{Combustibile inviato come richiesto. Cisterne = Vuote. Chiusura programma in corso.}
{198}{}{[FATTO]}
{199}{}{Combustibile inviato come richiesto. Cisterne = Vuote. Chiusura programma in corso.}
{200}{}{[FATTO]}
{201}{}{Database Fisica: Esplorazione - Teoria}
{202}{}{Esplorazione.}
{203}{}{Teoria.}
{204}{}{Indietro.}
{205}{}{"Con la recente acquisizione degli schemi tecnici del vertibird, le possibilita' di creare una macchina volante operativa sono aumentate esponenzialmente. Riteniamo di poter avere un prototipo funzionante entro la fine dell'anno e di essere in grado di avviare la produzione di massa di questi veicoli entro due anni." -Dr. Wong}
{206}{}{::copia schemi tecnici:: Indietro.}
{207}{}{Indietro.}
{208}{}{"Stiamo ancora lavorando ad un modello funzionante di un velivolo aereo. Nessuno dei progetti da noi elaborati si e' dimostrato sicuro o aerodinamico. Se solo potessimo entrare in possesso dei documenti degli antenati..." - Dr. Wong}
{209}{}{Indietro.}
{210}{}{(Dopo aver faticosamente letto l'introduzione e la parte dedicata alla matematica, scopri che gli Shi stanno imparando a sfruttare nuovamente l'energia nucleare, sono a buon punto nella riscoperta delle teorie degli antenati sul viaggio spaziale - una vera e propria sfida agli Hubologisti - e sono prossimi ad imbrigliare l'energia del sole, del vento e del mare. Almeno, questo e' quanto ti pare dicano questi dati.)}
{211}{}{Indietro.}
{212}{}{Postazione attivata.}
{213}{}{Indietro.}
{214}{}{Il terminale del computer non sembra avere l'interfaccia adatta per quello.}
{215}{}{Il computer non sembra essere operativo.}
{216}{}{Il sistema e' stato compromesso. Gli ordini sono di attaccare!}
{217}{}{Attaccare l'intruso!}
{218}{}{E' giunto il tempo di pagare per le tue azioni, lao wai!}
{219}{}{C'e' un traditore tra le nostre fila!}
{220}{}{Geo-puntamento.}
{221}{}{Cosa desiderate localizzare?}
{222}{}{Gli abitanti del mio villaggio.}
{223}{}{Probabilita' complessive: 97% - Gli abitanti si trovano alle coordinate del complesso Enclave.}
{230}{}{[Lo schermo lampeggia per un secondo prima di passare a un display monocromatico pieno di simboli cinesi.
 Dopo qualche istante, lo schermo si svuota e mostra un elenco di contenuti. La maggior parte dei file e' antica e corrotta,
 ma ce ne sono diversi che sembrano essere ancora intatti.]}
{231}{}{Marina dell’Esercito di Liberazione del Popolo                                    Terminale di Accesso Emperor v. 4.01
                                  Si prega di effettuare una selezione:}
{232}{}{Stato del sottomarino}
{233}{}{Rete d’Intelligence Cinese}
{234}{}{Collegamenti di comunicazione}
{235}{}{Registri del personale}
{236}{}{::indietro::}
{240}{}{Nome: Shi-Huang-Ti                                                     Classe: Tipo 088 Sottomarino nucleare
 a missili balistici   Armamento: Otto missili balistici nucleari JL-3
                  Varato: 8 agosto 2068                                         In servizio: 18 aprile 2069
                                       Capitano: Ammiraglio Classe AAAA Ye Li
                                Equipaggio: 15 ufficiali, 28 sottufficiali, 27 arruolati, 16 tecnici civili}
{241}{}{Continua a leggere.}
{250}{}{Servizio:                                                               2069 - 2071: Pattugliamento acque
 territoriali cinesi              2071 - 2077: Pattugliamento di combattimento nei teatri operativi dell'Alaska e del Pacifico
                                            Ottobre 2077: Missione di combattimento nel teatro operativo californiano.
 Schema missione R.}
{251}{}{Continua a leggere.}
{260}{}{Stato attuale:
                                                     Sottomarino danneggiato oltre ogni riparazione. Mainframe rimosso dal vascello e
 ricollocato. Nave riallestita come struttura difensiva stazionaria a due miglia NNE del porto di San Francisco.}
{261}{}{Cosa diceva riguardo alle pattuglie da combattimento?}
{262}{}{Leggi di piu' sullo Schema Missione R.}
{263}{}{Struttura difensiva stazionaria suonava interessante.}
{264}{}{::indietro::}
{270}{}{Su richiesta del comandante del fronte alaskano, il Generale Jingwei, lo Shi-Huang-Ti fu trasferito nel
 teatro operativo dell'Alaska/Pacifico per intercettare i convogli americani in acque aperte. Sotto il comando del Contrammiraglio
 Ye Li, ha affondato 9 mercantili e 4 navi da guerra, danneggiando altre 18 imbarcazioni e mettendo a dura prova le linee di rifornimento nemiche.}
{271}{}{Continua a leggere.}
{275}{}{L'Ammiraglio Ye Li e' stato anche accreditato dalla Marina dell'Esercito Popolare di Liberazione per aver portato all'affondamento della USS
 Ebon Atoll da parte di un sottomarino americano, la USS Interference.}
{276}{}{::indietro::}
{280}{}{2220, Maggio: La nave marina Poseidon Valdez arriva in porto, equipaggiata con un equipaggio dotato di armatura
 fanteria potenziata di tipo sconosciuto. La nave e' disabilitata e infestata da mutanti.
                                                                  2220, Giugno: A seguito di consultazioni con l'Imperatore, Chiang Lee
 ordina che lo Shi-Huang-Ti venga riattivato e trasformato in un'installazione difensiva contro ulteriori minacce navali.
                                                           2220, Luglio: Il sottomarino viene riattivato. E' stata necessaria
 energia di emergenza per accenderlo.                                  2231, Maggio: Il generatore di emergenza si spegne. Ken Lee ordina
 che un generatore ElectroBox venga collegato al sistema elettrico per continuare ad alimentare il sottomarino.
                                     2238, Agosto: Un motoscafo Neptune Waveskimmer viene restaurato e trasferito all'
 equipaggio di manutenzione del sottomarino.}
{281}{}{Hmm, vediamo se riesco a trovare qualcosa di piu' su quell'equipaggio di manutenzione...}
{282}{}{::indietro::}
{290}{}{[Bingo! Dopo qualche minuto di armeggio con i comandi, riesci a tirare fuori un piccolo file di testo riguardante il
 generatore del sottomarino. Sembra che siano necessari viaggi regolari per rifornire e mantenere il generatore. Il file elenca anche
 il registro attuale dell'equipaggio di manutenzione.]}
{291}{}{Equipaggio manutenzione sottomarino (dal 2241): Tsing Tao, Hun Kwai, Shin Fai, Lo Chang, Wu Fei}
{292}{}{::aggiungimi al registro dell'equipaggio di manutenzione::}
{293}{}{::indietro::}
{300}{}{[Con qualche rapida pressione di tasti, diventi parte dell'equipaggio di manutenzione del sottomarino. Un elenco di password per
 la guardia del motoscafo e' ora accessibile.]}
{301}{}{::scarica elenco password sul PIP-Boy::}
{310}{}{[Colleghi il PIP-Boy a una delle porte di accesso. Dopo un momento, hai un elenco aggiornato di password
 per il prossimo anno. Bella sicurezza.]}
{311}{}{::indietro::}
{320}{}{Ora sei un tecnico di sottomarini Shi a tutti gli effetti.}
{325}{}{Errore. Tabella Codici di Comando richiesta. Inserire la tabella corretta.}
{330}{}{[Grazie alla tabella dei codici di comando recuperata dal sottomarino, riesci ad accedere ai file riservati sui
 dischi dell'Imperatore]}
{331}{}{Codice di comando riconosciuto. Restrizioni di sicurezza revocate. Rete di Intelligence Cinese inizializzata..
...
...
Avviso! Collegamento al server centrale CIN di Pechino non disponibile. Recupero dati archiviati in corso.
 [Sembra che la maggior parte degli archivi sia corrotta. Tuttavia il mainframe riesce a recuperare diversi file intatti]}
{332}{}{Rapporto di intelligence 2069-11-5}
{333}{}{Rapporto di intelligence 2072-4-18}
{334}{}{Rapporto di intelligence 2073-12-4}
{335}{}{Rapporto di intelligence 2074-9-17}
{336}{}{Rapporto di intelligence 2075-10-17}
{337}{}{Rapporto di intelligence 2076-8-12}
{338}{}{Rapporto di intelligence 2077-10-12}
{339}{}{Rapporto di intelligence 2077-10-23}
{340}{}{}
{341}{}{::altro::}
{342}{}{::indietro::}
{345}{}{Da: Divisione Controspionaggio
                                  Le rivolte in Tibet e nelle province vicine continuano, minacciando la costruzione
 del complesso satcom Drago d'Oriente. Il Presidente Xin ordina l'intervento militare contro la popolazione. In seguito
 a significative perdite tra gli insorti, la provincia viene ripristinata sotto il controllo cinese e i rimanenti insorti vengono reinsediati.}
{346}{}{::indietro::}
{350}{}{Da: Divisione Guerra Biochimica
                          Un'epidemia nell'Unione Sovietica minaccia i protettorati settentrionali della RPC. La Div.
 BioChem consiglia quarantena e isolamento dei territori a rischio. Potenziale luogo di reinsediamento per insorti, terroristi
 e indesiderabili e area di raccolta per nuovi ceppi di armi biologiche. Piano sottoposto al Partito per approvazione.}
{351}{}{::indietro::}
{360}{}{Da: Comandante del Fronte Alaskano, Generale Jingwei
                Il ceppo #23-110 e' stato impiegato contro le truppe americane, demoralizzando e indebolendo la loro
 forza operativa. Si richiedono truppe aggiuntive e armatura Battlemaster per la spinta finale contro le forze americane asserragliate ai
 confini dell'Alaska.}
{361}{}{::indietro::}
{370}{}{Da: Comando Centrale
                                           Unita' americane dispiegate sul territorio continentale dopo aver eluso il nostro blocco del Giappone.
 Le forze alaskane devono continuare le operazioni. Le forze militari nei territori annessi devono potenziare la difesa del fronte interno.
 Il Comando autorizza l'uso di armi biologiche e chimiche sul suolo patrio - i diavoli stranieri devono essere sterminati!}
{371}{}{::indietro::}
{380}{}{Da: Drago Rosso
                                                     Le operazioni di guerriglia e gli attacchi terroristici sono molto efficaci nel
 demoralizzare la popolazione americana. Il supporto alle operazioni militari all'estero diminuisce mentre rivolte e proteste vengono istigate
 su tutto il suolo americano. Si raccomandano attacchi contro obiettivi di ricerca e militari designati in tutti gli Stati Uniti,
 priorita': Raven Rock, West Tek, Mariposa, Boulder, Institute.}
{381}{}{::indietro::}
{390}{}{Da: Comando Centrale
                                              La superiorita' militare americana e' ora evidente - unita' di Power Armor T-51b dispiegate
 sul territorio continentale. L'APL non ha un adeguato contrattacco e perde terreno ogni giorno. Il Presidente Cheng esige che Pechino rimanga in
 mani cinesi - la fortificazione e' in corso. Il Comando ordina l'intensificazione delle operazioni di guerriglia dietro le linee nemiche.
 Gli operativi in tutti i Commonwealth americani devono prepararsi a organizzare insurrezioni. Spedizioni di armi e attrezzature inviate.
 Obiettivo prioritario: Washington, DC, Columbia Commonwealth}
{391}{}{::indietro::}
{400}{}{Da: Presidente del Partito Cheng
                                         Con il crollo del Fronte Alaskano e la presenza americana sempre piu' forte sul
 suolo cinese la sconfitta e' imminente. In conformita' con la risoluzione 636860 del Partito Comunista Cinese, ordino con la presente a tutte le
 forze militari leali di avviare operazioni nucleari contro gli americani, schema missione R. Gli obiettivi prioritari sono
 contenuti nelle direttive operative. Possano le nostre anime tornare su questa Terra.}
{401}{}{::indietro::}
{410}{}{Da: Comando Centrale                                            Tutte le forze in posizione. Trasmissione codici di conferma finali.
 Operazione Youmíng e' via libera.}
{411}{}{::indietro::}
{420}{}{Scansione dei canali di comunicazione...                                    PLA CentCom... offline
                                                CIN Pechino...  offline
                                                   SSC Naval Yard...    offline
                                              SCA Eastern Dragon... offline
                                        Avviso: impossibile stabilire una connessione con i server esterni.}
{421}{}{Che delusione...}
{430}{}{Scansione delle unità locali...}
{431}{}{[CONTINUA]}
{440}{}{Trovato un file accessibile. [Sembra che la maggior parte degli archivi sia corrotta. Tuttavia il mainframe riesce a
 recuperare un file intatto.]}
{441}{}{Diario personale: Li Ye, Ammiraglio, Capitano}
{450}{}{2077-10-12: Stiamo perdendo questa guerra. Ho appena ricevuto conferma che il Partito ha finalmente deciso di procedere
 con il piano R. Follia! Come ci dara' la vittoria una guerra nucleare? Nessuno vince se scateniamo questo tipo di potere. Ma
 sono un soldato e seguiro' i miei ordini fino alla fine.}
{451}{}{Continua a leggere.}
{452}{}{::indietro::}
{460}{}{2077-10-19: L'equipaggio sta diventando irrequieto. Wong, eccitato, ha parlato agli ufficiali del piano R e loro erano estatici.
 Non posso biasimarli, anche se non sono d'accordo: Wong ha perso i suoi figli ad Anchorage mentre il fratello di Da Chiang e' stato catturato al largo
 della costa del Maryland.}
{461}{}{Continua a leggere.}
{462}{}{::indietro::}
{470}{}{2077-10-21: Abbiamo completato i preparativi finali per il lancio. Tutto cio' che rimane e' inserire i codici di conferma.
 E' stato un onore servire con questi uomini.}
{471}{}{Continua a leggere.}
{472}{}{::indietro::}
{480}{}{2077-10-23: Abbiamo ricevuto i codici di conferma e saremo in posizione tra quindici minuti. Questa e' probabilmente la mia
 ultima annotazione in questo diario, quindi lasciatemi dichiarare che non approvo questo tipo di atrocita'. La guerra si combatte tra soldati, non
 con bombe e civili. Se qualcuno sopravvive, spero che ci perdoneranno.}
{481}{}{Continua a leggere.}
{482}{}{::indietro::}
{490}{}{2077-10-29: Maledetti quei pazzi! Pensavo che fossimo l'unico gruppo incaricato di attaccare il settore di Los Angeles, ma mi
 sbagliavo. Hanno lanciato il nostro ICBM piu' potente su di esso. Non riesco a capire perche' non fosse diretto su Washington, ma questo non ha importanza.
 Attualmente stiamo derivando nell'oceano. L'Imperatore e' morto, la navigazione e' fuori uso e sembra che questa sara' la nostra
 tomba.}
{491}{}{Continua a leggere.}
{492}{}{::indietro::}
{500}{}{2077-11-04: Stiamo derivando da diversi giorni ormai. Jing e' riuscito a ripristinare parte dell'energia ai nostri sistemi
 di bordo, quindi dovremmo avere abbastanza ossigeno per durare diverse settimane. Sono piu' preoccupato per cibo e acqua - le nostre scorte
 sono basse e non ce n'e' abbastanza per tutti. L'equipaggio sta diventando irrequieto.}
{501}{}{Continua a leggere.}
{502}{}{::indietro::}
{510}{}{2077-11-08: L'Imperatore e' di nuovo online, ma appena. Non abbiamo ancora la navigazione e l'equipaggio e' sull'orlo della
 ammutinamento - ho dovuto fermare due marinai che picchiavano Jing. La situazione e' grave. A meno che non emergiamo nei prossimi giorni,
 temo che ci uccideremo a vicenda.}
{511}{}{Continua a leggere.}
{512}{}{::indietro::}
{520}{}{2077-11-12: Finalmente! Siamo arenati nella baia di San Francisco. I marinai esultavano finche' non abbiamo aperto i
 portelli. La citta' e' un disastro, devastata da tempeste di fuoco e ricadute radioattive. Ho inviato squadre a terra per trovare un sito adatto per il campo.
 Finora nessuna ha segnalato tale luogo. }
{521}{}{Continua a leggere.}
{522}{}{::indietro::}
{530}{}{2077-11-16: La squadra di Lao ha trovato un quartiere abitabile. Gli abitanti lo hanno abbandonato, dopo l'allarme raid aereo
 a quanto pare, ma ha subito pochi danni. La cosa piu' ironica? E' la Chinatown di San Francisco, ancora circondata
 da posti di blocco americani e caserme fortificate. Se solo sapessero...}
{531}{}{Continua a leggere.}
{532}{}{::indietro::}
{540}{}{2077-11-24: Abbiamo preso contatto con il Drago Rosso. Il comando Fantasma Nero del Nord America si e' trascinato verso ovest
 dal 23, dopo aver perso il contatto con CentCom. Non sono molto contenti di essere bloccati sul suolo nemico, ma
 dobbiamo arrangiarci.}
{541}{}{Continua a leggere.}
{542}{}{::indietro::}
{550}{}{2077-12-06: Il campo avanzato dello Shi-Huang-Ti e' allestito e funzionante. I Fantasmi eseguono operazioni di recupero nelle
 aree circostanti e raccolgono qualsiasi rifornimento trovino. Ho dato loro ordini precisi di non ingaggiare i sopravvissuti americani
 senza provocazione - non possiamo antagonizzare potenziali alleati.}
{551}{}{Continua a leggere.}
{552}{}{::indietro::}
{560}{}{2077-12-14: Una stranezza - un culto di nome Chiesa dell'Hubologia e' in qualche modo sopravvissuto alla devastazione in un
 bunker rinforzato vicino a cio' che rimane del ponte Golden Gate. Sono fanatici innocui, ma utili. Le loro risorse,
 la manodopera e la conoscenza dell'area circostante ci aiuteranno a stabilire la nostra nuova casa.}
{561}{}{Continua a leggere.}
{562}{}{::indietro::}
{570}{}{2077-12-27: Le necessita' di base sono coperte. Stiamo attualmente elaborando piani per smontare il sottomarino di elettronica
 e altra attrezzatura utile - non ha senso mantenerlo, dato che il sistema di propulsione e' irreparabile e possiamo
 usare tutto cio' che abbiamo in loco. Jing ha abbozzato piani per una struttura rinforzata - una sorta di 'Palazzo d'Acciaio'.}
{571}{}{Continua a leggere.}
{572}{}{::indietro::}
{580}{}{2077-12-31: Questa sara' la mia ultima annotazione in questo diario. Non sono piu' un Ammiraglio della Marina dell'Esercito Popolare
 di Liberazione. Ho una responsabilita' verso i miei uomini e li guidero' verso il futuro. A partire dal 2078, siamo in piena secessione
 dalla Cina. Presidente Cheng, roditi pure il fegato. Questo e' Ye Li, leader del popolo dello Shi-Huang-Ti, che chiude la trasmissione.}
{581}{}{::indietro::}
{590}{}{Schema Missione R:                                                    Piano di emergenza per la guerra nucleare
 dell'Esercito Popolare di Liberazione in caso di sconfitta imminente da parte di una potenza straniera, accettato dal Partito Comunista Cinese
 l'11 novembre 2073.}
{591}{}{Continua a leggere.}
{600}{}{Il piano include una serie di attacchi nucleari coordinati contro obiettivi strategici in tutta l'America, usando
 aerei strategici, sottomarini nucleari a missili, sistemi di consegna di missili, armi nucleari di fanteria a bassa resa e altri
 dispositivi nucleari. L'obiettivo e' paralizzare la capacita' di rappresaglia e la capacita' militare americana.}
{601}{}{Continua a leggere.}
{610}{}{Lo Shi-Huang-Ti ha il compito di distruggere otto obiettivi sul suolo californiano, tra cui la Struttura di Ricerca West Tek,
 le sedi aziendali a Los Angeles e i principali centri abitati.}
{611}{}{Continua a leggere.}
{620}{}{In caso di ammutinamento, tradimento o diserzione, il Capitano e' autorizzato a ordinare all'Imperatore di prendere il controllo della
 nave e portare a termine la missione.}
{621}{}{::indietro::}
{622}{}{::disconnessione::}
