{100}{}{Scendi per una scala arrugginita all'interno del sottomarino. L'interno e' buio, illuminato solo dalla luce fioca dei
 pochi monitor funzionanti. L'aria e' cattiva, piena del fetore di ruggine e decomposizione. Ti senti circondato e a disagio.}
{101}{}{You descend down a rusted ladder inside the submarine. The interior is dark, lit only by the dull light of the
 few working monitors. The air is bad, filled with the stench of rust and decay. You feel almost like at home.}
