{100}{}{Scendi per una scala arrugginita all'interno del sottomarino. L'interno e' buio, illuminato solo dalla luce fioca dei
 pochi monitor funzionanti. L'aria e' cattiva, piena del fetore di ruggine e decomposizione. Ti senti circondato e a disagio.}
{101}{}{Scendi per una scala arrugginita all'interno del sottomarino. L'interno e' buio, illuminato solo dalla luce fioca dei
 pochi monitor funzionanti. L'aria e' cattiva, piena del fetore di ruggine e decomposizione. Ti senti quasi come a casa.}
