{100}{}{Alt, mutante della Zona Contaminata! Stiamo perlustrando l'area alla ricerca di un nemico dell'Enclave. Identificati immediatamente.}
{101}{}{Chi stai chiamando mutante, stronzo? Vuoi un nemico? Ne hai uno -- proprio qui.}
{102}{}{Senti, sono solo un semplice viaggiatore. Non ho mai nemmeno sentito parlare dell'Enclave. Questa persona che state cercando deve essere piuttosto pericolosa, perche' voi ragazzi sembrate fare sul serio.}
{103}{}{That's enough for me. Kill him.}
{104}{}{Oh, this will be fun!}
{105}{}{Oh si', sono pericolosi eccome, e sospettiamo che stiano fuggendo da Gecko. Per quanto ne sappiamo, potresti essere tu quello che stiamo cercando.}
{106}{}{Be' sono proprio contento di non esserlo, perche' non sembrate il tipo con cui vorrei avere a che fare. Ma senti, se c'e' una persona pericolosa in giro da queste parti, dovrei davvero tornare dalla mia famiglia per avvertirli.}
{107}{}{All right, I give up. Let's party!}
{108}{}{You're not going anywhere just yet. Have you ever been to Gecko?}
{109}{}{Si', certo che ci sono stato. Posto meraviglioso. Voglio dire, la gente del posto e' orribile e puzza un po' e c'e' tutta quella radiazione e roba del genere, ma e' proprio divertente smanettare sui computer. Ah! Avreste dovuto essere li' quando stavo prendendo in giro questo coglione -- sapete, somigliava molto a voi ragazzi.}
{110}{}{Gecko? Assolutamente no, questo e' il piu' vicino che mi avvicino. Non lo sapete che quel posto e' pieno di quei ghoul brutti come il peccato? Perche' lo chiedete?}
{111}{}{OK, ti credo. Sparpagliatevi, uomini. Perlustrate la zona. Dobbiamo trovare questa persona.}
{112}{}{No. I don't believe you. This is our man, boys!}
{113}{}{No. I don't believe you. This is our woman, boys!}
{114}{}{Whoa! Whoa! Aspettate un secondo. Perche' non mi credete? Cosa avrei dovuto fare?}
{115}{}{Qualcuno ha violato la rete informatica dell'Enclave dal Reattore Petrolifero Poseidon. Stiamo cercando di rintracciarlo.}
{116}{}{Violato!? Be', non posso essere stato io. Sono solo un tribale. Accidenti, non so nemmeno come usare un -- come lo avete chiamato? Kom-pu-ter?}
{200}{}{Gecko? Assolutamente no, questo e' il piu' vicino che mi avvicino. Non lo sapete che quel posto e' pieno di quei ghoul brutti come il peccato? E' gia' abbastanza brutto dover badare al mio Zio Lenny, qui. Perche' lo chiedete?}
{201}{}{Urgh?}
{202}{}{Me kill baddies!}
