{100}{}{Vedi un uomo magro, dall'aspetto affabile.}
{101}{}{Vedi Chad, il carovaniere.}
{102}{}{Vedi un uomo magro, con un sorriso che pare uno scudo. Indossa abiti indefinibili e ha il tipico atteggiamento di chi sa cosa sta facendo.}
{120}{}{Ehila', amico! Cosa posso fare per te?}
{121}{}{Altre domande? Vediamo cosa posso fare per darti delle risposte.}
{122}{}{Deerk deegler!}
{123}{}{Chi tu?}
{124}{}{Marcus ha fatto delle domande sul tuo conto.}
{125}{}{Ci sono abbastanza prove per arrestarti con l'accusa di aver rubato del denaro destinato a Broken Hills. E' finita.}
{126}{}{Ci sono abbastanza prove per arrestarti con l'accusa di aver rubato del denaro destinato a Broken Hills. Dammi 1000$ e faro' in modo che tu possa fuggire dalla citta'.}
{127}{}{Chi sei?}
{128}{}{Parlami di questo posto.}
{129}{}{Nulla. Arrivederci.}
{130}{}{Guardate un po' cos'e' sbucato fuori dalle Lande! Scusa, amico, non posso aiutarti.}
{131}{}{Aivedecci!}
{132}{}{Io sono Chad. }
{133}{}{Guarda, sono molto occupato. Per favore, va' a disturbare qualcun altro.}
{134}{}{Sono il capo carovaniere della città. Gestisco gli affari all’altro capo delle rotte commerciali. Ultimamente mi sto occupando soprattutto di Gecko.}
{135}{}{D'accordo!}
{136}{}{Vorrei lavorare con te.}
{137}{}{Sembra eccitante.}
{138}{}{Sembra noioso.}
{139}{}{Ho delle altre domande.}
{140}{}{Grazie. Ciao.}
{141}{}{Vuoi che ti parli di Broken Hills? Beh... sono arrivato qui pochi anni fa. Ho iniziato a lavorare con Bill -– e' il Fornitore -– e sono giunto dove sono adesso. Devo rendere conto a Marcus e a Bill, ma sono io il responsabile del sostentamento di questa citta'.}
{142}{}{Ho delle altre domande.}
{143}{}{Addio.}
{144}{}{Ad esempio?}
{145}{}{Sospetta che tu stia trattenendo parte del denaro destinato a Broken Hills.}
{146}{}{Non proprio. Arrivederci.}
{147}{}{Senti, non so niente di questo, e di certo non mi piace quando la gente mi accusa di cose. Ora ti suggerisco di andartene.}
{150}{}{Scopriro' la verita'. Arrivederci.}
{156}{}{Parla con Bill. Ti aiutera' lui.}
{157}{}{Ho delle altre domande.}
{158}{}{Grazie. Ciao.}
{159}{}{Si', lo e'. Uno magari non ci pensa, ma in questo modo posso viaggiare e vedere il mondo... e mi sento come se contribuissi allo sviluppo di questa citta'. E' un bel modo di vivere.}
{160}{}{Sembra splendido. Mi piacerebbe un lavoro cosi'.}
{161}{}{In realta', mi sembra un po' noioso.}
{162}{}{Ho delle altre domande.}
{163}{}{Addio.}
{164}{}{Sicuramente piu' eccitante di quello che fai tu della tua vita, stronzo.}
{165}{}{Se lo dici tu... Ho delle altre domande.}
{166}{}{Ah ah ah ah! Certo. Ci vediamo, perdente.}
{167}{}{Un giorno la pagherai per questo, coglione.}
{168}{}{Sparisci dalla mia vista, stronzo.}
{169}{}{Quella carovana e' andata proprio a farsi benedire, amico mio. Lo stesso vale per i tuoi soldi.}
{170}{}{Hai davvero fatto un casino con quella carovana, amico mio. Dubito che riuscirai a fartene affidare un'altra da Broken Hills.}
{171}{}{Hai fatto un buon lavoro con quella carovana. Ecco i tuoi 200$.}
{172}{}{Fuori di qui. Il tuo aiuto non e' piu' desiderato.}
{173}{}{Occhi aperti.}
{174}{}{Ti copro io.}
{175}{}{Non lasciare che i bastardi ti colgano di sorpresa.}
{200}{}{Non so di cosa stai parlando. Ti suggerisco di lasciar perdere questa faccenda prima di iniziare a far incazzare la gente. Ora vattene.}
{201}{}{Ho un'idea migliore. Che ne dici se ti picchio a morte invece.}
{202}{}{Risposta sbagliata. Hai scelto la persona sbagliata con cui scherzare.}
{203}{}{D’accordo. Addio.}
{204}{}{Ah accidenti, sapevo che non sarebbe durato per sempre. [Si guarda intorno e abbassa la voce.] Va bene, ascolta. Tieni la bocca chiusa su questa faccenda. Ecco $1000 per tenerti zitto. [Ti da' i soldi.] Ora, se mi scusi, devo andare.}
{205}{}{[FATTO]}
{206}{}{Aiuto! Abbiamo un ladro qui!}
{207}{}{}
{208}{}{Che diavolo!? Chi sei tu?}
{209}{}{Io? Ehm, sono la fatina dei denti. Sono venuto a portarti grandi ricchezze.}
{210}{}{Si' e io sono Babbo Natale. Ora chi cazzo sei e perche' sei in casa mia?}
{211}{}{Davvero? Ho incontrato un tizio a New Reno che sostiene anche lui di essere Babbo Natale.}
{212}{}{*Fissa nel vuoto*}
{213}{}{(continuando) Si', e poi gli ho raccontato la storia della mia vita ad Arroyo...}
{214}{}{Ascolta, non me ne frega un cazzo delle tue cavolate deliranti. Sei tu quello che ha curiosato in giro, facendo domande sul denaro mancante della carovana.}
{215}{}{Esatto. E sono qui per raccogliere l'ultima prova di cui ho bisogno per metterti dentro.}
{216}{}{Oh si'? Lasciami aiutare. I documenti che cerchi sono in una valigetta chiusa a chiave nel cassetto inferiore
 di quel comò la'. Ma non la toccherai mai, perche' ti ammazzero', fottuto benefattore. Se non fosse
 stato per te, avrei potuto continuare a sgraffignare dalle carovane per un altro paio di mesi. Ma no, dovevi andare a
 ficcarti negli affari che non ti riguardano un cazzo. Ora devo fuggire dalla citta', ma almeno avro' il piacere
 di lasciare il tuo cadavere dietro di me.}
{217}{}{Nessuno deve morire qui, Chad. Invece di fare qualcosa di stupido che potrebbe farti uccidere, dovresti calmarti, e ne parleremo con Marcus.}
{218}{}{Pensi che sia stupido? Quel grosso stronzo brutto mi chiuderebbe dentro in un secondo. No, temo che qualcuno morra' di sicuro qui. E non saro' io!}
{219}{}{Sono qui per l'ultima prova nel caso del furto dalla carovana.}
{220}{}{Oh davvero?... Pensavo di riconoscerti.}
{221}{}{Va bene, va bene. Ammetto tutto. Non voglio morire per questo. Di' a Marcus che verra' pacificamente.}
{222}{}{D’accordo, non muoverti. Vado a chiamare Marcus.}
{300}{}{Permetti a Chad di lasciare la citta'.}
{400}{}{Lasciami in pace.}
{2040}{}{Ah accidenti sapevo che non sarebbe durato per sempre. (Si guarda intorno e abbassa la voce.) Va bene ascolta. Tieni la
 bocca chiusa su questa faccenda. Ecco $1000 per tenerti zitto. [Ti da' i soldi e tu gli consegni la sua valigetta.]
 Ora se mi scusi devo andare.}
