{100}{}{Vedi una guardia hubologista.}
{101}{}{E' costruito come una roccia ed e' ben armato.}
{200}{}{Alt! Questa e' proprieta' privata della Chiesa dell'Hubologia. Cosa vuoi qui?}
{201}{}{Sono venuto a saccheggiare questo posto. Ho sentito che c'e' un sacco di ricchezza da prendere.}
{202}{}{Non preoccuparti, fratello, siamo anime affini. Anch'io abbraccio la Chiesa dell'Hubologia.}
{203}{}{Oh si'? [Ti guarda da capo a piedi.] Allora non ti dispiacera' se ti faccio un quiz sulla nostra fede.}
{204}{}{[Sorride ferocemente.] Sei audace. Mi piace. Vediamo quanto sei audace quando ti lascio a sanguinare nella polvere.}
{205}{}{Chiedi pure. Sono pronto.}
{206}{}{Un quiz, eh? Sai cosa? Al diavolo -- ho mentito. Combattiamo.}
{220}{}{Chi ha fondato la Chiesa?}
{221}{}{La Chiesa crede che la vita, l'universo e tutto quanto possano essere simboleggiati da cosa?}
{222}{}{Nel contesto della Chiesa, cosa si intende con il termine "Illuminazione"?}
{230}{}{Herbert Jentz}
{231}{}{Dick Hubbel}
{232}{}{Juan Cruz}
{233}{}{AHS-9}
{234}{}{Hugo Richardson}
{240}{}{Un cerchio.}
{241}{}{Denaro.}
{242}{}{Una ruota che gira.}
{243}{}{Il corno di Odino.}
{244}{}{Un pesce.}
{250}{}{Il ripristino dell'essenza corporea.}
{251}{}{Uno stato di completa euforia.}
{252}{}{Uno stato in cui il cercatore sviluppa una comprensione divina della vera natura delle cose.}
{253}{}{Uno stato raggiunto quando il cercatore ha acquisito cosi' tanta conoscenza da diventare parte integrante dell'universo
 e lasciare indietro questa esistenza terrena.}
{254}{}{Il traguardo finale del percorso spirituale, quando il senso limitato dell'"io" si fonde nel supremo "noi".}
{260}{}{Esatto. Solo un altro Hubologo potrebbe avere tale saggezza. Ti do il benvenuto, e ti chiedo perdono. Posso chiederti perche' sei venuto qui? Pochissimi dei nostri membri conoscono persino questo luogo.}
{261}{}{Ha! Neanche lontanamente. Il collaudato metodo del quiz di sicurezza funziona sempre. Ora, liberiamo il mondo da te, impostore!}
{270}{}{AHS?9 mi ha chiesto di controllare tutte le donazioni. Vuole assicurarsi che qui sia tutto in ordine.}
{271}{}{Sono venuto a fare una donazione.}
{280}{}{Oh, non sapevo stessi seguendo ordini cosi' divini. In tal caso, sei libero di entrare. Ecco, lascia che ti apra questa porta.}
{281}{}{[Aggrugisce la fronte.] Huh, non mi hanno mai detto nulla di ispezioni...}
{282}{}{Grazie. Ci vediamo.}
{283}{}{Ascolta, AHS?9 mi ha detto personalmente di controllare le cose. Mi ha chiesto di recuperare un artefatto specifico donato di recente. E' fondamentale per raggiungere il Padre Stellare.}
{284}{}{Mi sto stufando delle tue bugie. Credo sia ora di strappare un'altra erbaccia dal mondo.}
{290}{}{Ma questo non e' il posto dove si fanno le donazioni. Puoi farlo in una qualsiasi delle nostre chiese.}
{291}{}{Lo so, ma AHS?9 mi ha detto che ai nuovi reclutati e' permesso controllare le cose prima di fare contributi considerevoli.}
{292}{}{[Aggrugisce la fronte.] Huh, non mi hanno mai detto nulla di ispezioni...}
{293}{}{Oh, capisco. E' comprensibile. Sei libero di entrare, ma non trattenerti troppo a lungo.}
{294}{}{Ascolta, sto per dare una grossa somma di denaro alla Chiesa. Voglio assicurarmi che la mia donazione sia al sicuro e usata
 appropriatamente.}
{300}{}{Ciao.}
{301}{}{Spero che sia tutto in ordine.}
{400}{}{Me vuole entrare.}
{410}{}{[Ti guarda in modo strano.] Be', allora ti servira' una password.}
{411}{}{Io passare aria, non parola.}
{412}{}{Me vuole entrare!}
{420}{}{Senti, non ho tempo per questo. Non dovresti essere qui, quindi sparisci o te ne pentirai.}
{421}{}{Ciao ciao!}
{422}{}{Me vuole cose buone dentro. Tu mori ora.}
{430}{}{Ultima occasione. Vai via ora o muori.}
{431}{}{Ti avevo avvertito!}
