{100}{}{Vedi una persona annoiata che indossa un'armatura di cuoio.}
{101}{}{Vedi Max, la guardia della carovana.}
{102}{}{Vedi una persona annoiata e coperta di polvere che indossa un'armatura di cuoio. Dalla puzza di brahmin che emana e dall'incedere sicuro, capisci che si tratta di una guardia della carovana.}
{103}{}{Posso aiutarti?}
{104}{}{Urg?}
{105}{}{Me lavorare qui!}
{106}{}{Chi sei?}
{107}{}{Cosa puoi dirmi a proposito di Chad?}
{108}{}{Non ho tempo da perdere con gli idioti. Spiacente, amico, ma dovrai cercare qualcun altro con cui giocare.}
{109}{}{::sniff::}
{110}{}{Io sono Max. Sono una delle guardie della carovana.}
{111}{}{Cosa puoi dirmi a proposito di Chad?}
{112}{}{Grazie. Ciao.}
{113}{}{Onestamente? Non me ne importa molto di quel tizio. Ultimamente sta maneggiando un sacco di soldi. Voglio dire, certo, e' il
 capo carovana, quindi ha senso che prenda una fetta piu' grande—lo capisco. Ma non c'e' modo che dovrebbe essere
 *cosi'* pieno di soldi. Sarebbe *davvero* interessante dare un'occhiata ai suoi registri.}
{114}{}{Marcus told me he suspects Chad of skimming some of the caravan money that supposed to be going to Broken Hills.
 I told him I'd look into it.}
{115}{}{Grazie. Ciao.}
{116}{}{Grazie. Sono davvero felice che sia finita. Tu pero' faresti bene a guardarti le spalle.}
{117}{}{Addio.}
{118}{}{Il nemico! Muori!}
{119}{}{Oops.}
{120}{}{[Abbassa la voce e si guarda intorno.] Dev'essere quello. In effetti, ero una guardia nell'ultima consegna di uranio a
 Gecko, e ho sentito Chad discutere con il loro rappresentante ghoul. A quanto pare, Broken Hills aveva aumentato
 di recente il prezzo dell'uranio, e il ghoul non era molto contento. Poi sento Chad spiegargli che le nostre scorte di uranio
 stavano finendo a causa di uno sciopero dei minatori, ma il punto e' che non c'e' mai stato alcuno sciopero.}
{121}{}{Davvero? Allora perche' non l'hai riferito a Marcus?}
{122}{}{Sei impazzito? Chad e' un tipo potente in questa citta' e ha un sacco di amici. Se provo a denunciarlo, un sacco di gente mi odiera'. Diamine, potrei persino farmi ammazzare.}
{123}{}{Hmm, then perhaps I could say something to Marcus. I don't plan to stay around here too much longer anyway.}
{124}{}{Hey, you do what you need to do, just don't drag me into it. In fact, we never had this conversation, OK?}
{125}{}{Nessun problema. Addio.}
{126}{}{In realta', un'altra cosa. So che Chad tiene registri di tutte le transazioni che fa. E' un maniaco dei documenti.
 Anzi, e' talmente fissato che scommetto tiene traccia persino dei soldi che si intasca. Il problema e'
 che tiene tutto chiuso nella sua casa dall'altra parte della citta', e non c'e' modo che tu possa entrare—il suo
 sistema di chiusura e' troppo complesso. E ancora: questa conversazione non e' mai avvenuta.}
{127}{}{I'll find a way. Thanks for the extra info.}
{128}{}{Complex system? How am I supposed to get in then?}
{129}{}{[Max riflette per un momento.] Va bene, ascolta. Sembri qualcuno di cui posso fidarmi. La porta della casa di Chad e'
 chiusa con il piu' avanzato sistema di serratura non elettronico che esista — una vera bellezza. Dovrei saperlo, l'ho
 progettato io. Vedi, prima di fare la guardia alle carovane, ero un fabbro serraturiere. Ora, dato che immagino ti servira'
 entrare in quella casa, lascia che ti spieghi come scassinare questo tipo di serrature.}
{130}{}{(Dopo circa cinque minuti Max ha finito di spiegare il funzionamento delle sue serrature.) Ecco, questo dovrebbe bastare per entrare.
 Con queste informazioni persino un principiante puo' scassinare una di quelle serrature. Ora fai attenzione. Ah, e questa conversazione non e' mai avvenuta.}
{131}{}{Don't worry. Thanks for the extra info.}
{200}{}{You learn about Chad's recent skimming from the Gecko caravans.}
