{100}{}{Vedi una guardia hubologista.}
{101}{}{You see a well-armed person with a cruel look in their eyes.}
{110}{}{Vedi un Hubologista.}
{111}{}{Sta fissando le varie apparecchiature informatiche davanti a lui.}
{200}{}{Noi siamo fedeli ad AHS-9.}
{201}{}{The Star Father cares for all of us.}
{202}{}{E' noioso qui, ma il nostro compito e' sorvegliare le donazioni.}
{203}{}{Greetings friend.}
{300}{}{Don't mess with anything.}
