{100}{}{Vedi una guardia hubologista.}
{101}{}{Vedi una persona ben armata, con uno sguardo crudele negli occhi.}
{110}{}{Vedi un Hubologista.}
{111}{}{Sta fissando le varie apparecchiature informatiche davanti a lui.}
{200}{}{Noi siamo fedeli ad AHS-9.}
{201}{}{Il Padre Stellare si prende cura di tutti noi.}
{202}{}{E' noioso qui, ma il nostro compito e' sorvegliare le donazioni.}
{203}{}{Saluti, amico.}
{300}{}{Non toccare niente.}
