{100}{}{Vedi una guardia hubologista stanca.}
{101}{}{Sembra piuttosto annoiato.}
{200}{}{(Ti guarda con aria annoiata) Ehi. Cosa ti porta fin qua giu'?}
{201}{}{Sono qui per darti il cambio in anticipo. Sono io nel prossimo turno di guardia.}
{202}{}{Ashton mi ha mandato a chiamarti. Ha detto che doveva parlarti riguardo l'ultimo gruppo di donazioni.}
{210}{}{Ehi, un momento! Non ti ho mai visto da queste parti. Che ci fai qui?}
{211}{}{Sono una nuova recluta. Sono stato trasferito qui di recente.}
{212}{}{Sì, mi hanno assegnato il compito di ucciderti.}
{220}{}{Maledizione. Non ho tempo per queste stronzate, il mio turno è quasi finito.}
{221}{}{Senti, sembrava piuttosto incazzato. Io non lo farei aspettare.}
{230}{}{Ah, merda. Va bene. Tieni d'occhio tutto mentre sono via. Torno tra qualche minuto.}
{231}{}{Nessun problema.}
{240}{}{Nuova recluta, eh? Ogni tanto ne arrivano qui. Lavoro piuttosto noioso fare la sicurezza qui, se vuoi saperlo. Meglio del reclutamento,
 comunque, quindi non mi lamento. Benvenuto a bordo.}
{241}{}{Grazie. Io, fossi in te, non farei aspettare Ashton.}
{242}{}{Apprezzo il benvenuto. Allora, ti interessa finire il turno in anticipo?}
{250}{}{Certo, perche' no? Tanto qui non succede mai niente di interessante. Ci si vede.}
{251}{}{In bocca al lupo.}
{260}{}{Nuova recluta? Stronzate. I rinforzi sono troppo rari da queste parti. Sembra che abbiamo un topo tra le mani. Addio!}
{300}{}{Ma che cazzo! Aston non ha mai chiesto di vedermi. Non so che diavolo stia succedendo ma non c'e' traccia del tuo permesso di stare qui. Mi sembra proprio che abbiamo un intruso tra le mani — presto un intruso morto.}
{400}{}{Ehi, che diavolo credi di fare!? Cercando di derubarci, proprio davanti ai miei occhi... santo cielo, sei un idiota. Finalmente posso uccidere qualcuno.}
{401}{}{Ehi, che diavolo credi di fare!? Questa e' proprieta' privata, quindi non toccare nulla. Questo e' il tuo unico avvertimento.}
{402}{}{Te l'avevo detto. Cercando di derubarci, proprio davanti ai miei occhi... santo cielo, sei un idiota. Finalmente posso uccidere qualcuno.}
