{100}{}{Vedi un uomo vestito con una tunica.}
{101}{}{Vedi Ashton. È lui il responsabile qui.}
{102}{}{Ha un sorrisetto sul volto.}
{200}{}{Saluti. Il mio nome e' Ashton, e sono io a occuparmi delle cose qui. Sei stato mandato per il turno di sicurezza?}
{201}{}{Sì, in effetti sì.}
{202}{}{No, sono stato mandato da AHS?9 per controllare tutto.}
{210}{}{Eccellente! Non si ha mai troppa sicurezza con quello che conserviamo qui, dico io. Felice di averti qui.}
{211}{}{Davvero? Questo e'... interessante. Sei libero di guardarti intorno, naturalmente. Sono certo che troverai tutto in ordine.}
{220}{}{Grazie. Ma esattamente, cosa stiamo conservando qui?}
{221}{}{D’accordo allora. Ci vediamo in giro.}
{230}{}{Come certamente saprai, ogni donazione alla Chiesa di Hubologia degli ultimi decenni e' conservata qui — e devo dire,
 e' un bel tesoro. Alcune donazioni sono piccole; altre piuttosto grandi. Riceviamo ogni tipo di roba, da armi e munizioni, a gioielli,
 e oggetti antichi, e persino qualche vecchio veicolo. Solo pochi mesi fa, l'attore Don Ravolta ha donato una vera motocicletta Harkley Sports
 del XX secolo — la migliore del suo tempo. Diamine, ci hanno persino donato un obice funzionante. La donazione piu' comune, comunque, e' il denaro — tanto,
 tantissimo denaro.}
{240}{}{Impressionante. Sembra che la Chiesa se la cavi piuttosto bene.}
{241}{}{Si, certo — e per una buona ragione. Le campagne pubblicitarie e un enorme shuttle spaziale non sono attivita' economiche, sai.}
{242}{}{Gia', posso immaginare. Quindi, quanto e' grande questo posto?}
{243}{}{Capisco cosa intendi. Beh, devo andare. Addio.}
{250}{}{La struttura in cui ci troviamo e' un vecchio bunker, probabilmente costruito per uso privato piuttosto che militare. Ci sono due livelli sotto di noi.
 Subito sotto c'e' l'area abitativa — abbiamo dei letti, bagni, attrezzi da esercizio, equipaggiamento di sicurezza. Sotto quello c'e' quello che chiamo il "vault".}
{251}{}{Un Vault?}
{252}{}{Non e' *davvero* un vault, lo chiamo cosi'. E' piu' una stanza di stoccaggio piena di roba. E' li' che teniamo tutte le donazioni. E' sorvegliato tutto il giorno, ogni giorno.}
{260}{}{Interessante. Beh, vado a dare un’occhiata in giro. A dopo.}
{270}{}{Allora, quanto è grande questo posto?}
{300}{}{Ciao di nuovo. Posso aiutarti con qualcosa?}
{301}{}{No, sto solo dando un’occhiata. Addio.}
