{100}{}{You see a man dressed in robes.}
{101}{}{You see Ashton. He is in charge here.}
{102}{}{He has a smirk on his face.}
{200}{}{Saluti. Il mio nome e' Ashton, e sono io a occuparmi delle cose qui. Sei stato mandato per il turno di sicurezza?}
{201}{}{Yeah, actually, I was.}
{202}{}{No, sono stato mandato da AHS?9 per controllare tutto.}
{210}{}{Eccellente! Non si ha mai troppa sicurezza con quello che conserviamo qui, dico io. Felice di averti qui.}
{211}{}{Davvero? Questo e'... interessante. Sei libero di guardarti intorno, naturalmente. Sono certo che troverai tutto in ordine.}
{220}{}{Thanks. What exactly are we storing here, anyway?}
{221}{}{Alright then. See you around.}
{230}{}{Come certamente saprai, ogni donazione alla Chiesa di Hubologia degli ultimi decenni e' conservata qui — e devo dire,
 e' un bel tesoro. Alcune donazioni sono piccole; altre piuttosto grandi. Riceviamo ogni tipo di roba, da armi e munizioni, a gioielli,
 e oggetti antichi, e persino qualche vecchio veicolo. Solo pochi mesi fa, l'attore Don Ravolta ha donato una vera motocicletta Harkley Sports
 del XX secolo — la migliore del suo tempo. Diamine, ci hanno persino donato un obice funzionante. La donazione piu' comune, comunque, e' il denaro — tanto,
 tantissimo denaro.}
{240}{}{Impressionante. Sembra che la Chiesa se la cavi piuttosto bene.}
{241}{}{Si, certo — e per una buona ragione. Le campagne pubblicitarie e un enorme shuttle spaziale non sono attivita' economiche, sai.}
{242}{}{Gia', posso immaginare. Quindi, quanto e' grande questo posto?}
{243}{}{I know what you mean. Well, I must be going. Bye.}
{250}{}{La struttura in cui ci troviamo e' un vecchio bunker, probabilmente costruito per uso privato piuttosto che militare. Ci sono due livelli sotto di noi.
 Subito sotto c'e' l'area abitativa — abbiamo dei letti, bagni, attrezzi da esercizio, equipaggiamento di sicurezza. Sotto quello c'e' quello che chiamo il "vault".}
{251}{}{A vault?}
{252}{}{It's not *really* a vault, I just call it that. It's more of a storage room full of goods. That's where we keep all the donations. It's guarded all day, everyday.}
{260}{}{Interesting. Well, I'm going to have a look around. See you later.}
{270}{}{So, how large is this place?}
{300}{}{Hello again. Help you with something?}
{301}{}{Nope, just looking around. Bye.}
