{100}{}{Apri il cassetto e trovi file e appunti ordinati in fila.}
{101}{}{Search the dresser.}
{102}{}{Te ne vai.}
{103}{}{As you search through the records in the dresser, you notice a thin leather briefcase stuffed carefully deep in the back.}
{104}{}{Tira fuori la valigetta.}
{105}{}{Ignora e continua a cercare.}
{106}{}{Passano 30 minuti e non trovi nulla di importante. Tutto cio' che scopri e' che Chad tiene registri che documentano ogni momento della sua vita. 
In realta' e' un tipo piuttosto noioso. Proprio mentre stai per chiudere i cassetti, senti un colpo di tosse dalla porta d'ingresso e una maniglia che gira...}
{107}{}{Tira fuori la valigetta.}
{108}{}{Inside the briefcase you find papers documenting a whole year's worth of skimming money from
 caravans by Chad.}
{109}{}{Wow, it really looks like Chad was skimming money. Apparently he is preparing to skip town as well,
 better tell Marcus all this.}
{110}{}{30 minutes pass and you find nothing of importance. All that you have found out is that Chad has records
 documenting every moment of his life. He's a pretty boring guy actually.}
