{100}{}{Apri il cassetto e trovi file e appunti ordinati in fila.}
{101}{}{Search the dresser.}
{102}{}{Te ne vai.}
{103}{}{Mentre cerchi tra i registri nel cassetto, noti una sottile valigetta di pelle infilata con cura in fondo.}
{104}{}{Tira fuori la valigetta.}
{105}{}{Ignora e continua a cercare.}
{106}{}{Passano 30 minuti e non trovi nulla di importante. Tutto cio' che scopri e' che Chad tiene registri che documentano ogni momento della sua vita. 
In realta' e' un tipo piuttosto noioso. Proprio mentre stai per chiudere i cassetti, senti un colpo di tosse dalla porta d'ingresso e una maniglia che gira...}
{107}{}{Tira fuori la valigetta.}
{108}{}{Dentro la valigetta trovi documenti che registrano un anno intero di soldi sottratti
 alle carovane da Chad.}
{109}{}{Cavolo, sembra proprio che Chad si intascasse soldi. A quanto pare si sta anche preparando a lasciare la citta'.
 Meglio dire tutto questo a Marcus.}
{110}{}{Passano 30 minuti e non trovi nulla di importante. Tutto cio' che hai scoperto e' che Chad ha registri
 che documentano ogni momento della sua vita. In realta' e' un tipo piuttosto noioso.}
