{100}{}{Vedi una porta di legno.}
{101}{}{Questa porta e' fatta di legno massiccio. Sembra costruita con un nuovo sistema di chiusura.}
{102}{}{Questa porta è saldamente chiusa.}
{103}{}{Usando la tecnica che hai imparato da Max, disattivi con cura il meccanismo di scatto e
 scassini la porta senza sforzo.}
{104}{}{Qualcosa sembra diverso in questa serratura. Decidi di lasciarla stare.}
{105}{}{Stai per metterti al lavoro per scassinare quando noti un piccolo meccanismo di scatto nel sistema di chiusura.
 Se fosse scattato, non saresti mai riuscito a scassinare la porta. Lo rimuovi abilmente e poi, in pochi
 secondi, hai scassinato il resto della porta.}
{106}{}{L'esplosivo non ha fatto un graffio alla porta.}
