{100}{}{You see a sturdy metal door.}
{101}{}{Questo e' un tipo di porta usato nei caveau delle banche. Servirebbero diversi colpi diretti di esplosivi per buttarla giu'. E' chiusa.}
{102}{}{Questo e' un tipo di porta usato nei caveau delle banche. Servirebbero diversi colpi diretti di esplosivi per buttarla giu'. E' aperta.}
{110}{}{L'esplosione scuote la porta. Sebbene molto indebolita, rimane al suo posto.}
{111}{}{La porta esplode in pezzi. Non ne rimane nulla.}
