{100}{}{Vedi una grande cassaforte da pavimento in metallo.}
{101}{}{È una cassaforte molto robusta. È chiusa a chiave.}
{102}{}{È una cassaforte molto robusta. È aperta.}
{170}{}{Scassini abilmente la serratura della cassaforte.}
{171}{}{La tua mancanza di abilità ha bloccato la serratura della cassaforte.}
{172}{}{Non riesci a scassinare la cassaforte.}
{189}{}{Chiudi abilmente la cassaforte a chiave.}
{190}{}{Non riesci a chiudere la cassaforte a chiave.}
{200}{}{La cassaforte è ben chiusa a chiave.}
