{100}{}{Vedi una grande cassaforte da pavimento in metallo.}
{101}{}{E' una cassaforte molto robusta. E' chiusa a chiave.}
{102}{}{E' una cassaforte molto robusta. E' aperta.}
{170}{}{Scassini abilmente la serratura della cassaforte.}
{171}{}{La tua mancanza di abilita' ha bloccato la serratura della cassaforte.}
{172}{}{Non riesci a scassinare la cassaforte.}
{189}{}{Chiudi abilmente la cassaforte a chiave.}
{190}{}{Non riesci a chiudere la cassaforte a chiave.}
{200}{}{La cassaforte e' ben chiusa a chiave.}
