{100}{}{Vedi un tribale.}
{101}{}{Vedi Ombra-che-Cammina.}
{150}{}{Vedi un uomo primitivo molto muscoloso con cicatrici nere che ricoprono la sua faccia. Ti sta fissando in silenzio.}
{151}{}{Vedi Ombra-che-Cammina. Il suo viso e' pesantemente sfregiato da tatuaggi rituali.}
{200}{}{Ti guarda semplicemente in silenzio.}
{201}{}{Ti guarda in silenzio.}
{300}{}{Shhh... Sono a caccia di conigli.}
{400}{}{[Ti guarda con occhi diffidenti.] Chi va la'?}
{401}{}{Il mio nome e' }
{402}{}{. Chi sei?}
{403}{}{I'm on a mission for Vault City. Who are you?}
{404}{}{Il mio nome non e' importante. Sono venuto ad avvertirti. Sei in grave pericolo!}
{405}{}{Sono la tua nemesi. Preparati a raggiungere i tuoi antenati!}
{406}{}{Sono francese. Perche' credi che abbia questo accento assurdo? [Lo fissi stranito.]}
{407}{}{Come non detto. Scusa il disturbo.}
{410}{}{Parli con Ombra Che Cammina. Perche' sei venuto qui?}
{411}{}{Sto cercando di fermare gli attacchi dei predoni a Vault City, e ho motivo di credere che questa sia la loro base operativa. Cosa sai dei predoni?}
{412}{}{I was sent by Vault City on account of Raiders attacking them.}
{413}{}{I was just curious about this place, but I'll be leaving now.}
{414}{}{Sto facendo un po' di pratica al tiro, e tu sembri un ottimo bersaglio mobile.}
{420}{}{Ombra Che Cammina non conosce predoni qui. Ombra Che Cammina conosce solo alcuni Ranger venuti a liberare schiavi da Vault City, quel luogo malvagio. [Ti da' una descrizione che corrisponde a quella dei predoni.]}
{421}{}{E' questo che ti hanno detto, che sono Ranger? Non ci sono Ranger da queste parti, stanno mentendo.}
{422}{}{Ranger? Quelli non sono Ranger. Guarda i loro vestiti. Sei una pedina nel loro gioco. Ti stanno solo usando.}
{423}{}{Senti, sono stato mandato da Vault City per trovare dei predoni. Questi uomini corrispondono alla descrizione.}
{424}{}{Oh, alright. I guess I'll be leaving then.}
{425}{}{I don't believe you. Die, you wicked man!}
{430}{}{Why would they lie to Shadow Who Walks?}
{431}{}{Li avresti aiutati se ti avessero detto che erano predoni, che attaccano innocenti, e che non gliene importa nulla di aiutare qualcuno a Vault City?}
{432}{}{Non lo so. E' un mondo duro, la fuori. La gente si approfitta degli altri continuamente.}
{433}{}{Per farsi una bella risata, forse? Sembri abbastanza stupido da cascarci in tutto.}
{440}{}{Ombra Che Cammina non aiuterebbe mai a fare una cosa simile, sarebbe malvagio. [Ti guarda sospettoso.] Ma perche' Ombra Che Cammina dovrebbe fidarsi di cio' che dici?}
{441}{}{[Tell him of your home tribe.]}
{442}{}{Perche' sono un Ranger, quello vero. [Gli mostri il tuo distintivo.]}
{443}{}{Perche' so per chi lavorano questi predoni, e non e' affatto un brav'uomo. [Gli mostri i dati dell'holodisk]}
{444}{}{I don't know. Sorry to waste your time.}
{445}{}{You don't have to, I'm gonna kill you anyway.}
{450}{}{[Ombra Che Cammina ti guarda in modo diverso, con occhi piu' fiduciosi.] Ora Ombra Che Cammina sa che sei un portatore di verita'. Ombra Che Cammina si fida di te.}
{451}{}{Well, what are you going to do now?}
{452}{}{Do you have any idea why these raiders might be attacking Vault City?}
{453}{}{Divertente, ti ho mentito per tutto il tempo. Come ci si sente, idiota?}
{460}{}{No, non so. So solo che hanno ingannato Ombra Che Cammina per farsi aiutare a trovare la strada.}
{461}{}{Well, what are you going to do now?}
{462}{}{Non e' che per caso li hai sentiti fare nomi o qualcosa del genere?}
{463}{}{Be', lascia stare, li uccidero' tutti. Penso che mi scaldero' un po' prima uccidendo te...}
{470}{}{Hmmm... forse. Quando alcuni di loro sono andati a prendere altre armi rumorose e strane... [Mima qualcuno che usa un fucile]... hanno menzionato un nome... Bishop. Si, parlavano di un uomo chiamato Bishop.}
{471}{}{I see. Well, thank you, Shadow Who Walks, you have been most helpful.}
{472}{}{Bene. Ora che ho le informazioni che volevo eliminero' questo branco di parassiti, iniziando da te...}
{480}{}{Ombra Che Cammina ti ringrazia, Ombra Che Cammina non ama essere ingannato.}
{481}{}{You are welcome. What now, then?}
{482}{}{Oh, davvero? E io che pensavo ci fossi abituato ormai, visto che sei un idiota e tutto il resto...}
{490}{}{Ombra Che Cammina non aiutera' piu'. Ombra Che Cammina tornera' a casa e non mostrera' piu' la strada agli uomini malvagi.}
{491}{}{Bene. Questo dovrebbe impedire agli uomini malvagi di fare ancora del male agli innocenti di Vault City.}
{500}{}{Ombra Che Cammina ti ringrazia, amico, per aver portato la verita'. Che gli spiriti guidino il tuo cammino.}
{501}{}{And yours.}
{600}{}{[Il suo volto si oscura.] Quel luogo malvagio. Perche' Ombra Che Cammina dovrebbe ascoltare qualcuno che viene dalla malvagia Vault City?}
{601}{}{Perche' presto di te restera' solo un'ombra, se non lo fai.}
{602}{}{Non sono venuto qui per farti ascoltare. Sono venuto per farti fuori.}
{610}{}{[Ti osserva con cautela per un momento.] Ombra Che Cammina ascoltera'. Ora, perche' sei qui?}
{611}{}{Vault City e' sotto pesante attacco, e le guardie non sono riuscite a scoprire chi stia davvero attaccando e quali siano le loro intenzioni.}
{612}{}{Be', non ho molto da dirti, quindi lascero' che siano i miei pugni a parlare.}
{620}{}{E perche' Ombra Che Cammina dovrebbe pensare che sia una cosa negativa? Stanno ottenendo cio' che meritano, e Ombra Che Cammina sara' felice quando saranno sconfitti e i loro "servi" liberati.}
{621}{}{So, you support whoever is attacking them?}
{622}{}{Well, I don't think I'm going to let you live long enough for that to happen.}
{630}{}{Ombra Che Cammina mostra loro la strada per Vault City e ritorno. Ombra Che Cammina e' molto importante per loro, serve affinche' trovino la via.}
{631}{}{Well then, I'll just have to kill you, and the attacks should stop.}
{632}{}{Vuoi dire ERA importante, giusto? Quello che sto cercando di dire e' che ora morirai, per mano mia.}
{640}{}{[Una paura crescente gli attraversa il volto, e inizia a indietreggiare.] Ti prego, no! Ombra Che Cammina non desidera morire!}
{641}{}{Allora lascia questo posto, e questa gente, per sempre. Conto fino a dieci, e se non sarai sparito, raggiungerai i tuoi antenati nei cieli. UNO...}
{642}{}{Troppo tardi, mio caro tribale. Raggiungerai i tuoi antenati tra circa... 12 secondi.}
{700}{}{(Il tribale ti guarda in silenzio)}
{701}{}{[Keep staring]}
{702}{}{[Attack]}
{703}{}{Il mio nome e' }
{704}{}{. Chi sei?}
{705}{}{I'm on a mission for Vault City. Who are you?}
{706}{}{Il mio nome non e' importante. Sono venuto ad avvertirti. Sei in grave pericolo!}
{707}{}{Never mind, I'll just leave.}
{708}{}{Non voglio piu' parlare con te, svuotacervelli pulisci-mangiatoie! Scoreggio nella tua direzione generale! Tua madre era un criceto e tuo padre puzzava di sambuco!}
{710}{}{(Il tribale continua a guardarti in silenzio)}
{711}{}{[Keep staring]}
{712}{}{[Attack]}
{713}{}{Il mio nome e' }
{714}{}{. Chi sei?}
{715}{}{I'm on a mission for Vault City. Who are you?}
{716}{}{Il mio nome non e' importante. Sono venuto ad avvertirti. Sei in grave pericolo!}
{717}{}{Never mind, I'll just leave.}
{718}{}{Non voglio piu' parlare con te, svuotacervelli pulisci-mangiatoie! Scoreggio nella tua direzione generale! Tua madre era un criceto e tuo padre puzzava di sambuco!}
{720}{}{(Il tribale continua a guardarti in silenzio. E' chiaro che sta diventando impaziente.)}
{721}{}{[Keep staring]}
{722}{}{[Attack]}
{723}{}{Il mio nome e' }
{724}{}{. Chi sei?}
{725}{}{I'm on a mission for Vault City. Who are you?}
{726}{}{Il mio nome non e' importante. Sono venuto ad avvertirti. Sei in grave pericolo!}
{727}{}{Never mind, I'll just leave.}
{728}{}{Non voglio piu' parlare con te, svuotacervelli pulisci-mangiatoie! Scoreggio nella tua direzione generale! Tua madre era un criceto e tuo padre puzzava di sambuco!}
{800}{}{Ombra Che Cammina non ti crede. Ombra Che Cammina ha finito di parlare. Addio.}
{801}{}{[FINE]}
{802}{}{Don't you turn your back on me tribal. I'm talking to you.}
{810}{}{Come osi minacciare Ombra Che Cammina. Vai via subito.}
{811}{}{[Walk Away]}
{812}{}{[Attack]}
{850}{}{Chi va la'?}
{851}{}{Shhh... Sono a caccia di conigli.}
{852}{}{HeeeeHeee! Hehe... He... Hai bei disegni come un quadro... Heeee!}
{900}{}{Shadow Who Walks does not understand. What do you mean?}
{901}{}{Sei in grave pericolo! Dimmi solo cosa fai qui. Devo sapere se sto parlando con la persona giusta.}
{902}{}{Uh, bad spirits are coming for you.}
{903}{}{The danger is that I am here to kill you.}
{910}{}{Ombra Che Cammina e' uno scout. Ombra Che Cammina guida questi Ranger attraverso le montagne. I guerrieri possono perdersi se
 non conoscono i sentieri tra le montagne.}
{911}{}{Allora sei davvero tu! Il mio Anziano mi ha mandato a dirti che qualcosa di terribile ti accadra'.}
{912}{}{E' questo che ti hanno detto, che sono Ranger? Non ci sono Ranger da queste parti, stanno mentendo.}
{913}{}{Ranger? Quelli non sono Ranger. Guarda i loro vestiti. Sei una pedina nel loro gioco. Ti stanno solo usando.}
{920}{}{Cosa!? Ombra Che Cammina non capisce. Perche' un Anziano dovrebbe dire una cosa simile?}
{921}{}{Ascoltami! La nostra Anziana ha previsto la tua morte. La prossima volta che lascerai questa caverna per guidare questi uomini tra le montagne, non tornerai vivo. Devi andartene subito o gli spiriti malvagi ti prenderanno.}
{922}{}{Do you doubt the Elder?}
{930}{}{P-Perche'... Perche' Ombra Che Cammina dovrebbe crederti? Come ha fatto l'Anziana a prevedere tali eventi?}
{931}{}{Be'... Una volta stava guardando un film... No, no... Eh, stava giocando a un videogioco... Mmmmm... Si! Si chiama Fal-...}
{932}{}{Ha bevuto una pozione, aveva un odore molto forte, e le sono venuti sogni vividi.}
{933}{}{Gliel'ha detto l'osso nel suo naso. E' cosi' che comunica con i nostri antenati.}
{940}{}{Stai mentendo. Non e' cosi' che si parla con gli spiriti. Ora Ombra Che Cammina vedra' che sapore ha la lingua di un bugiardo con la sua salsa brock preferita.}
{941}{}{[FATTO]}
{950}{}{Oh, allora e' vero cio' che dici. Ombra Che Cammina conosce il potere degli spiriti. Cosa deve fare Ombra Che Cammina?}
{951}{}{Be', ho appena parlato con loro e mi hanno detto che non ti apprezzano molto. Mi hanno chiesto di ucciderti.}
{952}{}{Devi lasciare questo posto per sempre e non guidare mai piu' questi uomini. Gli spiriti sono arrabbiati con te per averli condotti tra le montagne. Prega gli spiriti ogni giorno e solo allora la loro ira si placera'.}
{960}{}{Ombra Che Cammina obbedisce. [Ombra Che Cammina corre verso la scala che porta all'esterno]}
{961}{}{You are welcome Shadow Who Runs.}
{1000}{}{Hai distrutto la banda dei predoni. Non saranno piu' in grado di fare razzie in questa regione.}
{1001}{}{Dagli un giorno o due e sono sicuro che questi Predoni abbandoneranno questo posto. Poi potro' cercare informazioni.}
