{100}{}{Entri in una serie di tunnel sotto Trapper Town. L'odore di escrementi di ratto e' piuttosto forte.}
{101}{}{L'esplosione fa cedere i supporti danneggiati e una valanga di rocce cade dall'alto. Mentre accade, senti un forte schianto riecheggiare nella caverna. Guardandoti attorno, vedi che anche gli altri supporti deboli stanno cedendo.}
{103}{}{Hai intrappolato Keeng Ra'at! Senza via d'uscita, la fame sara' tutto cio' che gli restera' da assaporare.}
{104}{}{Meglio levarmi dalla traiettoria di questi supporti prima di essere schiacciato o intrappolato.}
{105}{}{Un altro trave di supporto cede e una valanga di rocce precipita giu'.}
