{100}{}{You see a card dealer.}
{101}{}{Vedi Tre-Carde Monte.}
{150}{}{Vedi un vecchio dall'aspetto ossuto con il viso arrossato dal sole. E' cosi' magro che sembra fatto di ramoscelli.}
{151}{}{Vedi Tre-Carde Monte. Scruta la strada, ti nota e annuisce.}
{152}{}{Vedi Tre-Carde Monte. Scruta la strada, ti nota e annuisce.}
{200}{}{Don't see how I lost...}
{201}{}{Continua a camminare... Monte oggi non e' in affari.}
{202}{}{Ho nascosto la carta sbagliata?}
{203}{}{Come ha fatto quel tribale stupido a scegliere sempre la carta giusta?}
{205}{}{Eeeeh! Eroe! Tutto bene, tutto bene.}
{206}{}{::Ti fa il gesto del pollice alzato::}
{207}{}{::Smiles, nods::}
{208}{}{You done good, hero. You done good.}
{215}{}{Dove diavolo sono le mie carte? Le avevo proprio un attimo fa.}
{216}{}{Maledetti gnomi delle chiavi dell'auto, ora se la prendono anche con le mie carte da gioco.}
{220}{}{Ehi, amico, lascia perdere i casinò. Vieni a giocare con Monte.}
{221}{}{Cerchi un po' di fortuna, amico? Le migliori probabilita' di New Reno! Dai...}
{222}{}{Tu, amico. Sembri uno fortunato, vieni qui.}
{223}{}{Qualcuno vuole giocare? Soldi facili, soldi facili.}
{224}{}{Vieni a giocare. L'altro giorno uno mi ha portato via 50 fiches, facile.}
{225}{}{Semplice, basta indovinare la Regina, la Regina rossa, e vinci. Tutto qui.}
{226}{}{You allergic to easy money? Then get over here.}
{227}{}{Oggi vincono tutti... vuoi essere il prossimo?}
{228}{}{I casinò ti spennano, ti derubano... Monte ti tratta bene, ti da' una vera possibilita'.}
{229}{}{Cerchi un po' di fortuna, signora? Le migliori probabilita' di New Reno! Dai...}
{230}{}{Allergica ai soldi facili, signora? Allora vieni qui.}
{231}{}{Tu, signora. Sembri una fortunata, vieni qui.}
{232}{}{Ehi, signora, lascia perdere i casinò. Vieni a giocare con Monte.}
{233}{}{Monte oggi non e' aperto per giocare, amico; le mie dannate carte sono sparite.}
{234}{}{(Il vecchio sorride, e la pelle attorno agli occhi si increspa.) Cerchi una partita, amico?}
{235}{}{(Il vecchio sorride, e la pelle attorno agli occhi si increspa.) Cerchi una partita, signora?}
{236}{}{(Il vecchio sorride, e la pelle attorno agli occhi si increspa.) Cerchi una partita, eroe?}
{237}{}{(Monte sorride, e la pelle attorno agli occhi si increspa.) Cerchi una partita, amico?}
{238}{}{(Monte sorride, e la pelle attorno agli occhi si increspa.) Cerchi una partita, signora?}
{239}{}{(Monte sorride, e la pelle attorno agli occhi si increspa.) Cerchi una partita, eroe?}
{240}{}{Tre-Carde Monte e' il nome, e il gioco e' lo stesso del nome. Metti giu' 20 fiches e iniziamo.}
{241}{}{Tu imbroglione. Tu non giochi giusto.}
{242}{}{Okay ecco fiches io non sicuro quanto e' 20 quindi ecco un mucchio.}
{243}{}{Uh, io lusingato ma io non voglio iniziare ora... ciaaaao.}
{244}{}{-Allontanati-}
{245}{}{Let's play.}
{246}{}{Uh, get down to what?}
{247}{}{I'm familiar with the game. Let's play.}
{248}{}{Tre-Carde Monte, eh? Metti tre carte a faccia in giu', le mescoli, e io ne scelgo una. Se e' quella giusta — cosa che non sara', visto che la nascondi mentre mescoli — allora vinco. No grazie, amico.}
{249}{}{Tre-Carde Monte, eh? Metti tre carte a faccia in giu', le mescoli, e io ne scelgo una. Se e' quella giusta — cosa che non sara', visto che la nascondi mentre mescoli — allora vinco. No grazie, amico.}
{250}{}{Non oggi, grazie.}
{251}{}{Iniziare cosa? Il gioco, ovviamente!}
{252}{}{Vedi... (ti mostra tre carte) ...una di queste e' una regina. Le metto a faccia in giu', le mescolo, e poi scegli quale e' la regina. Se indovini, vinci.}
{253}{}{That simple, pal.}
{254}{}{That simple, lady.}
{255}{}{I'm not playing with a cheater like you.}
{256}{}{Could you explain the rules again?}
{257}{}{Sounds simple enough. Let's play. Here's 20 chips.}
{258}{}{Non oggi, grazie.}
{260}{}{(Consegni i soldi. Monte annuisce, ti mostra le carte, poi le sbatte a terra e le mescola per qualche secondo.)}
{261}{}{Allora... qual e' la regina, amico?}
{262}{}{Allora... qual e' la regina, signora?}
{263}{}{(You think it's the one on the left.)}
{264}{}{(You think it's the one in the middle.)}
{265}{}{(You think it's the one on the right.)}
{266}{}{(You don't know. The cards moved too fast.)}
{267}{}{Lucy la mancina}
{268}{}{Middle of th'road}
{269}{}{Rightie tightie}
{270}{}{The one on the left.}
{271}{}{The one on the right.}
{272}{}{The one in the middle.}
{280}{}{(Monte gira la carta. E' la...}
{281}{}{Spiacente, amico, non stavolta, ma ci sei andato VICINO.}
{282}{}{Spiacente, signora, non stavolta, ma ci sei andata VICINO.}
{283}{}{You sure do got the eye for it, though. Wanna try again?}
{284}{}{Tu imbroglione. Tu non giochi giusto.}
{285}{}{Okay ecco fiches io non sicuro quanto e' 20 quindi ecco un mucchio.}
{286}{}{Nuh-uh Me no LIKE game BYYYYE}
{287}{}{I'm not playing with a cheater like you.}
{288}{}{Sure. Here's 20 chips.}
{289}{}{No, grazie.}
{300}{}{(You hand over the cash. Monte nods, shows you the cards, then lays them on the ground. As he does, he palms a card, so quickly you almost miss it. He then proceeds to shuffle for a few seconds.)}
{301}{}{Allora... qual e' la regina, amico?}
{302}{}{Allora... qual e' la regina, signora?}
{303}{}{You put it in sleevie weevie you no play fair}
{304}{}{Lucy la mancina}
{305}{}{Middle of th'road}
{306}{}{Rightie tightie}
{307}{}{You goddamn CHEATER. I saw you palm that card. Give me back my cash before I kill you here in the street.}
{308}{}{The one in your sleeve.}
{309}{}{The one on the left.}
{310}{}{The one on the right.}
{311}{}{The one in the middle.}
{320}{}{WHAT did you say, pal?}
{321}{}{WHAT did you say, lady?}
{322}{}{You accusing me of cheating?}
{323}{}{Uh-uh. Me KNOW you cheet}
{324}{}{Nuh-uh! Nuh-uh! Don' be mad. Me going.}
{325}{}{Si'.}
{326}{}{Screw this. Keep the money, I'm outta here.}
{330}{}{Look, I ain't got time for sore losers. You pay your money, you take your chances. If you
 wanna PLAY, fine, but if
 you're just gonna bitch when you lose, then get lost!}
{331}{}{ME BREAK YOU}
{332}{}{Nuh-uh! Nuh-uh! Don' be mad. Me going.}
{333}{}{That's it. You're dead.}
{334}{}{All right, all right. I'm sorry. Here's 20 chips. Let's play again.}
{335}{}{Screw you. Keep the money, I'm outta here.}
{340}{}{(You hand over the cash. Monte nods, then slaps the cards down and shuffles them for a few seconds.)}
{341}{}{Allora... qual e' la regina, amico?}
{342}{}{Allora... qual e' la regina, signora?}
{343}{}{(Monte's using his normal deck! You need to steal his other deck to complete the switch.)}
{344}{}{You put it in sleevie weevie you no play fair}
{345}{}{Uh... Lucy leftie}
{346}{}{Uh... Middle of th'road}
{347}{}{Uh... Rightie tightie}
{348}{}{You goddamn CHEATER. I saw you palm that card. Give me back my cash before I kill you here in the street.}
{349}{}{The one in your sleeve.}
{350}{}{Uh, the one on the left.}
{351}{}{Uh, the one on the right.}
{352}{}{Uh, the one in the middle.}
{360}{}{(Consegni i soldi. Monte annuisce, ti mostra le carte, poi le sbatte a terra e le mescola per qualche secondo.)}
{361}{}{(You hand over the cash. Monte looks uncomfortable.) Uh... all right... (Monte puts the cards on the ground and shuffles them.)}
{362}{}{Allora... qual e' la regina, amico?}
{363}{}{Allora... qual e' la regina, signora?}
{364}{}{(Monte's using the marked deck. Any pick is the right one.)}
{365}{}{Leftie! Leftie!}
{366}{}{Rightie! Rightie!}
{367}{}{Middlie! Middlie!}
{368}{}{Oh, I don't know... the one on the left.}
{369}{}{Hmmmm... maybe the one on the right?}
{370}{}{Gee, I'm not sure... I think it's the one in the middle.}
{375}{}{(Monte turns over the card. It is the queen of hearts. He seems paralyzed with shock.) Uh...? Heh. Eh...}
{376}{}{guess you win, pal.}
{377}{}{guess you win, lady.}
{378}{}{(He hands over the cash reluctantly.)}
{379}{}{Again! Again!}
{380}{}{Thanx me go now}
{381}{}{So we gonna play again or what? C'mon, Monte. I'm just getting started.}
{382}{}{Well, thanks, Monte. See you later.}
{385}{}{(Monte turns over the card. It is the queen of hearts. He looks shocked.) Uh...? Heh... uh...}
{386}{}{guess you win, pal.}
{387}{}{guess you win, lady.}
{388}{}{That cleans me out, though... (Looks at you weakly) Anything else I could do for you?}
{389}{}{Nuttin. Me just wanted sum extra EXP. Bye. Bye.}
{390}{}{What have you GOT?}
{391}{}{Why don't you give me some information?}
{392}{}{Forget it, Monte. We'll call it even for today.}
{400}{}{(Looks pained.) Eh... well, I do have something... but it's worth WAY more than you won... still...}
{401}{}{Well? What is it?}
{402}{}{If it's worth more to you than dying on Golgotha because you welched on a debt, that's your problem. I'd think
 about it, if I were you.}
{404}{}{Eh... hmnnn... depends on what you want to know.}
{405}{}{You know who dusted Wright's kid? Made him O.D. on Jet?}
{406}{}{You know where I could find some guy named Pretty Boy Lloyd?}
{407}{}{You know where my car is, Monte?}
{408}{}{Got anything you think I should know?}
{409}{}{Nevermind, Monte. We're even. See you later.}
{415}{}{Eh... well... look, you ain't heard it from me, but my bets on Renesco, that asshole who runs the pharmacy on the west side.
 I don't know if he sold it TO the kid for sure, but he knows something. That's all I'm gonna say.}
{416}{}{All right then, Monte. We're even.}
{420}{}{Eh... well... (looks like he's fighting an inner battle) ...look, you ain't heard it from me, but if I was you, I'd
 check out the basement of the Desperado.}
{421}{}{All right then, Monte. We're even.}
{425}{}{(Narrows his eyes, leans in) I'd ask ol' Jules at the front of town. Nothing gets by him... and
 if it DID, then he had a finger in it, know what I'm saying?}
{426}{}{All right then, Monte. We're even.}
{430}{}{Well... know that Eldridge fella that runs New Reno Arms? He says he does weapon upgrades, but I never see him do
 any work. Might be worthwhile to check out his place... but you didn't hear that from me.}
{431}{}{All right then, Monte. We're even.}
{435}{}{(Monte frowns as he sees you.) Look, I ain't running no games today, all right? Blow.}
{436}{}{Can I buy that card you showed me before?}
{437}{}{I wanted some information...}
{438}{}{All right, Monte. I'll leave... for now.}
{440}{}{Nope. Ain't gonna part with that. Period. It's GENUINE pre-war memorabilia... a little slice of history. No WAY.}
{441}{}{You making me ANOTHER offer? Look, I told you I ain't selling it.}
{442}{}{How about a thousand chips? I got it with me. It's yours in exchange for that card.}
{443}{}{Not even for 750 chips?}
{444}{}{How about 500 chips?}
{445}{}{250 chips sound about right?}
{446}{}{Okay. Avrei delle altre domande...}
{447}{}{Nevermind then, Monte. I'm outta here.}
{450}{}{You deaf? That amount ain't even enough to interest me.}
{451}{}{How about I suggest another amount...?}
{452}{}{Avrei delle altre domande...}
{453}{}{Nevermind then, Monte. I'm outta here.}
{460}{}{Well, it ain't THAT dear to me. It's yours, pal. (He glances to the right and left, then reaches down and pulls off his
 boot. He twists off the heel and pulls out a playing card from inside.) Here ya go. Take care of it.}
{461}{}{Avrei delle altre domande...}
{462}{}{Thanks, Monte. Always a pleasure.}
{465}{}{(Frowns) Whether I talk depends on what you want to know. And it's not gonna be cheap.}
{466}{}{You know who dusted Wright's kid? Made him O.D. on Jet?}
{467}{}{You know where I could find some guy named Pretty Boy Lloyd?}
{468}{}{You know where my car is, Monte?}
{469}{}{Got anything you think I should know?}
{470}{}{Nevermind then, Monte. I'm outta here.}
{475}{}{No way in Golgotha am I going to even TOUCH that subject. Piss off.}
{476}{}{Look, that subject's just bad news. Leave it alone, all right?}
{477}{}{You making me another offer? Look, I told you I AIN'T going talk about it.}
{478}{}{A thousand chips change your mind? I got it with me.}
{479}{}{Not even for 750 chips?}
{480}{}{How about 500 chips?}
{481}{}{250 chips sound about right?}
{482}{}{Uh... Golgotha?}
{483}{}{Avrei delle altre domande...}
{484}{}{Nevermind then, Monte. I'm outta here.}
{490}{}{(Shakes his head.) No way. Talking about that could get somebody killed, startin' with me. Forget it.}
{491}{}{How about if I offered you this...}
{492}{}{Avrei delle altre domande...}
{493}{}{Nevermind then, Monte. I'm outta here.}
{495}{}{Eh... well... that's a lot of chips. (Licks his lips. He looks like he's fighting an inner battle....but the battle is a brief one.) Look, you ain't heard it from me...}
{496}{}{Understood. Go on.}
{500}{}{(Sneers) Maybe I heard something, maybe I didn't. Name a price.}
{501}{}{All right... talk a price.}
{502}{}{How about a thousand chips? I got it with me.}
{503}{}{Not even for 750 chips?}
{504}{}{How about 500 chips?}
{505}{}{250 chips sound about right?}
{506}{}{Avrei delle altre domande...}
{507}{}{Nevermind then, Monte. I'm outta here.}
{510}{}{Ha! You couldn't buy a bucket of piss for that much. Forget it.}
{511}{}{How about if I offered you this...}
{512}{}{Avrei delle altre domande...}
{513}{}{Nevermind then, Monte. I'm outta here.}
{515}{}{Thaaaat's about right. (Grins evilly.) Look, you ain't heard it from me, but if I was you, I'd check out the basement of the Desperado on Virgin Street. There's a lot of "rats" there, if you catch my drift.}
{516}{}{Avrei delle altre domande...}
{517}{}{Capito. Grazie.}
{520}{}{(Shrugs) Maybe I know something about that, maybe I don't. Tell me a price and I might have something to say.}
{521}{}{All right... talk a price.}
{522}{}{How about a thousand chips? I got it with me.}
{523}{}{Not even for 750 chips?}
{524}{}{How about 500 chips?}
{525}{}{250 chips sound about right?}
{526}{}{Avrei delle altre domande...}
{527}{}{Nevermind then, Monte. I'm outta here.}
{530}{}{(Narrows his eyes, leans in) For that amount, I don't know nothing.}
{531}{}{How about if I offered you this...}
{532}{}{Avrei delle altre domande...}
{533}{}{Nevermind then, Monte. I'm outta here.}
{535}{}{That's about right... (narrows his eyes, leans in) ...I'd ask ol' Jules at the front of town. Nothing
 gets by him... and if it DID, then he had a finger in it, know what I'm saying?}
{536}{}{Avrei delle altre domande...}
{537}{}{All right then, Monte. Thanks.}
{540}{}{(Shrugs) I hear things, I see things. For 200 chips, maybe you can get the benefit of my experience, know what I'm saying?}
{541}{}{Here's 200 chips.}
{542}{}{I'll give you 150.}
{543}{}{100 chips or nothing.}
{544}{}{Avrei delle altre domande...}
{545}{}{Nevermind then, Monte. I'm outta here.}
{550}{}{You deaf? I SAID 200 chips, n' I meant it.}
{551}{}{All right. Here's 200 chips.}
{552}{}{Avrei delle altre domande...}
{553}{}{Nevermind then, Monte. I'm outta here.}
{555}{}{Done. (Monte leans in) Well, know that guy Eldridge, runs New Reno Arms? He SAYS he does
 weapon upgrades, but I never see him do any work. You might want to check out his place... but you didn't hear that from me.}
{556}{}{Avrei delle altre domande...}
{557}{}{Understood. Thanks, Monte.}
{560}{}{Boneyard south of town. Stinks ta high heaven, it does.}
{561}{}{Oh... I see. Now, about the Wright kid...}
{562}{}{Forget the Wright kid. I had some other questions...}
{563}{}{All right then, Monte. Thanks.}
{565}{}{My bets on Renesco, that old asshole who runs the pharmacy on the west side. I don't know
 if he sold it TO the kid for sure, but he knows SOMETHING. (Glances around) That's all I'm gonna say.}
{566}{}{Avrei delle altre domande...}
{567}{}{All right then, Monte. Thanks.}
{570}{}{(He glances around, then reaches down and pulls off his boot. He twists off the heel and pulls out a card... on the card
 is a man with a strange hat, wielding a club.) Interested? It's genuine pre-war memorabilia.}
{571}{}{No, I already have enough inventory items... I'd rather have some information instead.}
{572}{}{Uh, sure. Why not? This'll settle things between us.}
{573}{}{Sorry pal, no chips, no game. Come back when you got more money.}
{574}{}{Sorry lady, no chips, no game. Come back when you got more money.}
{575}{}{Yeah, maybe next time then.}
{576}{}{You quickly swap Monte's deck of cards for the marked deck.}
{600}{}{spades}
{601}{}{hearts}
{602}{}{diamonds}
{603}{}{clubs}
{604}{}{due}
{605}{}{tre}
{606}{}{quattro}
{607}{}{cinque}
{608}{}{sei}
{609}{}{sette}
{610}{}{otto}
{611}{}{nove}
{612}{}{dieci}
{613}{}{ di }
