{100}{}{Vedi un croupier.}
{101}{}{Vedi Tre-Carde Monte.}
{150}{}{Vedi un vecchio dall'aspetto ossuto con il viso arrossato dal sole. E' cosi' magro che sembra fatto di ramoscelli.}
{151}{}{Vedi Tre-Carde Monte. Scruta la strada, ti nota e annuisce.}
{152}{}{Vedi Tre-Carde Monte. Scruta la strada, ti nota e annuisce.}
{200}{}{Non capisco come abbia perso...}
{201}{}{Continua a camminare... Monte oggi non e' in affari.}
{202}{}{Ho nascosto la carta sbagliata?}
{203}{}{Come ha fatto quel tribale stupido a scegliere sempre la carta giusta?}
{205}{}{Eeeeh! Eroe! Tutto bene, tutto bene.}
{206}{}{::Ti fa il gesto del pollice alzato::}
{207}{}{::Sorride e annuisce::}
{208}{}{Hai fatto bene, eroe. Hai fatto bene.}
{215}{}{Dove diavolo sono le mie carte? Le avevo proprio un attimo fa.}
{216}{}{Maledetti gnomi delle chiavi dell'auto, ora se la prendono anche con le mie carte da gioco.}
{220}{}{Ehi, amico, lascia perdere i casinò. Vieni a giocare con Monte.}
{221}{}{Cerchi un po' di fortuna, amico? Le migliori probabilita' di New Reno! Dai...}
{222}{}{Tu, amico. Sembri uno fortunato, vieni qui.}
{223}{}{Qualcuno vuole giocare? Soldi facili, soldi facili.}
{224}{}{Vieni a giocare. L'altro giorno uno mi ha portato via 50 fiches, facile.}
{225}{}{Semplice, basta indovinare la Regina, la Regina rossa, e vinci. Tutto qui.}
{226}{}{Allergico ai soldi facili? Allora vieni qui.}
{227}{}{Oggi vincono tutti... vuoi essere il prossimo?}
{228}{}{I casinò ti spennano, ti derubano... Monte ti tratta bene, ti da' una vera possibilita'.}
{229}{}{Cerchi un po' di fortuna, signora? Le migliori probabilita' di New Reno! Dai...}
{230}{}{Allergica ai soldi facili, signora? Allora vieni qui.}
{231}{}{Tu, signora. Sembri una fortunata, vieni qui.}
{232}{}{Ehi, signora, lascia perdere i casinò. Vieni a giocare con Monte.}
{233}{}{Monte oggi non e' aperto per giocare, amico; le mie dannate carte sono sparite.}
{234}{}{(Il vecchio sorride, e la pelle attorno agli occhi si increspa.) Cerchi una partita, amico?}
{235}{}{(Il vecchio sorride, e la pelle attorno agli occhi si increspa.) Cerchi una partita, signora?}
{236}{}{(Il vecchio sorride, e la pelle attorno agli occhi si increspa.) Cerchi una partita, eroe?}
{237}{}{(Monte sorride, e la pelle attorno agli occhi si increspa.) Cerchi una partita, amico?}
{238}{}{(Monte sorride, e la pelle attorno agli occhi si increspa.) Cerchi una partita, signora?}
{239}{}{(Monte sorride, e la pelle attorno agli occhi si increspa.) Cerchi una partita, eroe?}
{240}{}{Tre-Carde Monte e' il nome, e il gioco e' lo stesso del nome. Metti giu' 20 fiches e iniziamo.}
{241}{}{Tu imbroglione. Tu non giochi giusto.}
{242}{}{Okay ecco fiches io non sicuro quanto e' 20 quindi ecco un mucchio.}
{243}{}{Uh, io lusingato ma io non voglio iniziare ora... ciaaaao.}
{244}{}{-Allontanati-}
{245}{}{Giochiamo.}
{246}{}{Ehm… metterci a fare cosa, esattamente?}
{247}{}{Conosco il gioco. Giochiamo.}
{248}{}{Tre-Carde Monte, eh? Metti tre carte a faccia in giu', le mescoli, e io ne scelgo una. Se e' quella giusta — cosa che non sara', visto che la nascondi mentre mescoli — allora vinco. No grazie, amico.}
{249}{}{Tre-Carde Monte, eh? Metti tre carte a faccia in giu', le mescoli, e io ne scelgo una. Se e' quella giusta — cosa che non sara', visto che la nascondi mentre mescoli — allora vinco. No grazie, amico.}
{250}{}{Non oggi, grazie.}
{251}{}{Iniziare cosa? Il gioco, ovviamente!}
{252}{}{Vedi... (ti mostra tre carte) ...una di queste e' una regina. Le metto a faccia in giu', le mescolo, e poi scegli quale e' la regina. Se indovini, vinci.}
{253}{}{Semplice, amico.}
{254}{}{Semplice, signora.}
{255}{}{Non gioco con uno che bara come te.}
{256}{}{Puoi rispiegarmi le regole?}
{257}{}{Sounds simple enough. Let's play. Here's 20 chips.}
{258}{}{Non oggi, grazie.}
{260}{}{(Consegni i soldi. Monte annuisce, ti mostra le carte, poi le sbatte a terra e le mescola per qualche secondo.)}
{261}{}{Allora... qual e' la regina, amico?}
{262}{}{Allora... qual e' la regina, signora?}
{263}{}{(You think it's the one on the left.)}
{264}{}{(You think it's the one in the middle.)}
{265}{}{(You think it's the one on the right.)}
{266}{}{(You don't know. The cards moved too fast.)}
{267}{}{Lucy la mancina}
{268}{}{Middle of th'road}
{269}{}{Rightie tightie}
{270}{}{The one on the left.}
{271}{}{The one on the right.}
{272}{}{The one in the middle.}
{280}{}{(Monte gira la carta. E' la...}
{281}{}{Spiacente, amico, non stavolta, ma ci sei andato VICINO.}
{282}{}{Spiacente, signora, non stavolta, ma ci sei andata VICINO.}
{283}{}{Pero' ci sai fare, davvero. Vuoi riprovare?}
{284}{}{Tu imbroglione. Tu non giochi giusto.}
{285}{}{Okay ecco fiches io non sicuro quanto e' 20 quindi ecco un mucchio.}
{286}{}{Nuh-uh io NON PIACE gioco CIAAAO.}
{287}{}{Non gioco con uno che bara come te.}
{288}{}{Sure. Here's 20 chips.}
{289}{}{No, grazie.}
{300}{}{(Consegni i soldi. Monte annuisce, ti mostra le carte, poi le posa a terra. Mentre lo fa, nasconde una carta cosi' velocemente che quasi non lo noti. Poi procede a mescolare per qualche secondo.)}
{301}{}{Allora... qual e' la regina, amico?}
{302}{}{Allora... qual e' la regina, signora?}
{303}{}{Tu messo carta in manica tu non giochi giusto.}
{304}{}{Lucy la mancina}
{305}{}{Middle of th'road}
{306}{}{Rightie tightie}
{307}{}{Maledetto IMBROGLIONE. Ti ho visto nascondere quella carta. Ridammi i miei soldi prima che ti faccia fuori qui in mezzo alla strada.}
{308}{}{The one in your sleeve.}
{309}{}{The one on the left.}
{310}{}{The one on the right.}
{311}{}{The one in the middle.}
{320}{}{COSA hai detto, amico?}
{321}{}{WHAT did you say, lady?}
{322}{}{You accusing me of cheating?}
{323}{}{Nuh-uh. Io SAPEVO tu imbroglia.}
{324}{}{Nuh-uh! Nuh-uh! Non arrabbiarti. Io andare.}
{325}{}{Si'.}
{326}{}{Screw this. Keep the money, I'm outta here.}
{330}{}{Ascolta, non ho tempo per i perdenti frignoni. Paghi i tuoi soldi, ti giochi la tua occasione. Se vuoi GIOCARE, bene, ma se devi solo lamentarti quando perdi, allora sparisci!}
{331}{}{ME BREAK YOU}
{332}{}{Nuh-uh! Nuh-uh! Non arrabbiarti. Io andare.}
{333}{}{That's it. You're dead.}
{334}{}{All right, all right. I'm sorry. Here's 20 chips. Let's play again.}
{335}{}{Screw you. Keep the money, I'm outta here.}
{340}{}{(Consegni i soldi. Monte annuisce, poi sbatte le carte a terra e le mescola per qualche secondo.)}
{341}{}{Allora... qual e' la regina, amico?}
{342}{}{Allora... qual e' la regina, signora?}
{343}{}{(Monte sta usando il suo mazzo normale! Devi rubargli l'altro mazzo per completare lo scambio.)}
{344}{}{Tu messo carta in manica tu non giochi giusto.}
{345}{}{Uh... Lucy leftie}
{346}{}{Uh... Quella in mezzo.}
{347}{}{Uh... Rightie tightie}
{348}{}{Maledetto IMBROGLIONE. Ti ho visto nascondere quella carta. Ridammi i miei soldi prima che ti faccia fuori qui in mezzo alla strada.}
{349}{}{The one in your sleeve.}
{350}{}{Uh, the one on the left.}
{351}{}{Uh, the one on the right.}
{352}{}{Uh, the one in the middle.}
{360}{}{(Consegni i soldi. Monte annuisce, ti mostra le carte, poi le sbatte a terra e le mescola per qualche secondo.)}
{361}{}{(Consegni i soldi. Monte sembra a disagio.) Uh... va bene... (Monte posa le carte a terra e le mescola.)}
{362}{}{Allora... qual e' la regina, amico?}
{363}{}{Allora... qual e' la regina, signora?}
{364}{}{(Monte sta usando il mazzo segnato. Qualsiasi scelta e' quella giusta.)}
{365}{}{Leftie! Leftie!}
{366}{}{Rightie! Rightie!}
{367}{}{Mezzo! Mezzo!}
{368}{}{Oh, I don't know... the one on the left.}
{369}{}{Hmmmm... maybe the one on the right?}
{370}{}{Gee, I'm not sure... I think it's the one in the middle.}
{375}{}{(Monte gira la carta. E' la regina di cuori. Sembra paralizzato dallo shock.) Uh...? Heh. Eh...}
{376}{}{guess you win, pal.}
{377}{}{guess you win, lady.}
{378}{}{(He hands over the cash reluctantly.)}
{379}{}{Again! Again!}
{380}{}{Thanx me go now}
{381}{}{Allora, giochiamo ancora o no? Dai, Monte. Ho appena iniziato.}
{382}{}{Well, thanks, Monte. See you later.}
{385}{}{(Monte gira la carta. E' la regina di cuori. Sembra sconvolto.) Uh...? Heh... uh...}
{386}{}{guess you win, pal.}
{387}{}{guess you win, lady.}
{388}{}{That cleans me out, though... (Looks at you weakly) Anything else I could do for you?}
{389}{}{Niente. Io volevo solo un po' di EXP extra. Ciao. Ciao.}
{390}{}{What have you GOT?}
{391}{}{Why don't you give me some information?}
{392}{}{Forget it, Monte. We'll call it even for today.}
{400}{}{(Sembra soffrire.) Eh... be', ho qualcosa... ma vale MOLTO piu' di quello che hai vinto... pero'...}
{401}{}{Well? What is it?}
{402}{}{Se per te vale piu' che morire a Golgotha per non aver pagato un debito, e' un tuo problema. Io ci penserei, fossi in te.}
{404}{}{Eh... hmnnn... depends on what you want to know.}
{405}{}{Sai chi ha fatto fuori il figlio dei Wright? Chi l'ha fatto andare in overdose di Jet?}
{406}{}{You know where I could find some guy named Pretty Boy Lloyd?}
{407}{}{You know where my car is, Monte?}
{408}{}{Hai qualcosa che pensi dovrei sapere?}
{409}{}{Nevermind, Monte. We're even. See you later.}
{415}{}{Eh... be'... senti, non l'hai sentito da me, ma io punto su Renesco, quello stronzo che gestisce la farmacia sul lato ovest. Non so se l'ha venduta LUI al ragazzo, ma sa qualcosa. Questo e' tutto quello che dico.}
{416}{}{All right then, Monte. We're even.}
{420}{}{Eh... be'... (sembra combattere una battaglia interiore) ...senti, non l'hai sentito da me, ma se fossi in te darei un'occhiata al seminterrato del Desperado.}
{421}{}{All right then, Monte. We're even.}
{425}{}{(Socchiude gli occhi, si avvicina) Io chiederei al vecchio Jules all'ingresso della citta'. Niente gli sfugge... e se QUALCOSA gli e' sfuggito, allora ci aveva messo lo zampino, capisci cosa intendo?}
{426}{}{All right then, Monte. We're even.}
{430}{}{Be'... conosci quel tipo Eldridge che gestisce New Reno Arms? Dice che fa potenziamenti alle armi, ma non l'ho mai visto lavorare. Potrebbe valere la pena dare un'occhiata al suo posto... ma non l'hai sentito da me.}
{431}{}{All right then, Monte. We're even.}
{435}{}{(Monte aggrotta le sopracciglia quando ti vede.) Senti, oggi non sto facendo nessun gioco, okay? Sparisci.}
{436}{}{Can I buy that card you showed me before?}
{437}{}{I wanted some information...}
{438}{}{All right, Monte. I'll leave... for now.}
{440}{}{No. Non me ne separo. Punto. E' AUTENTICA memorabilia pre-guerra... un piccolo pezzo di storia. In nessun modo.}
{441}{}{Mi stai facendo UN'ALTRA offerta? Senti, ti ho detto che non lo vendo.}
{442}{}{Che ne dici di mille chip? Ce li ho con me. Sono tuoi in cambio di quella carta.}
{443}{}{Not even for 750 chips?}
{444}{}{How about 500 chips?}
{445}{}{250 chip ti sembrano giusti?}
{446}{}{Okay. Avrei delle altre domande...}
{447}{}{Nevermind then, Monte. I'm outta here.}
{450}{}{Sei sordo? Quella cifra non basta neanche a interessarmi.}
{451}{}{How about I suggest another amount...?}
{452}{}{Avrei delle altre domande...}
{453}{}{Nevermind then, Monte. I'm outta here.}
{460}{}{Be', non ci sono COSI' affezionato. E' tua, amico. (Si guarda a destra e a sinistra, poi si china e si sfila
 lo stivale. Svita il tacco e tira fuori una carta da gioco dall'interno.) Eccola. Trattala bene.}
{461}{}{Avrei delle altre domande...}
{462}{}{Thanks, Monte. Always a pleasure.}
{465}{}{(Corruga la fronte) Se parlo dipende da cosa vuoi sapere. E non sara' a buon mercato.}
{466}{}{Sai chi ha fatto fuori il figlio dei Wright? Chi l'ha fatto andare in overdose di Jet?}
{467}{}{You know where I could find some guy named Pretty Boy Lloyd?}
{468}{}{You know where my car is, Monte?}
{469}{}{Hai qualcosa che pensi dovrei sapere?}
{470}{}{Nevermind then, Monte. I'm outta here.}
{475}{}{Neanche a Golgota mi avvicinerei a quell'argomento. Vaffanculo.}
{476}{}{Senti, quell'argomento porta solo guai. Lascia perdere, ok?}
{477}{}{Mi stai facendo un'altra offerta? Senti, ti ho detto che NON ne parlero'.}
{478}{}{A thousand chips change your mind? I got it with me.}
{479}{}{Not even for 750 chips?}
{480}{}{How about 500 chips?}
{481}{}{250 chip ti sembrano giusti?}
{482}{}{Uh... Golgotha?}
{483}{}{Avrei delle altre domande...}
{484}{}{Nevermind then, Monte. I'm outta here.}
{490}{}{(Scuote la testa.) Neanche per sogno. Parlare di quello potrebbe far fuori qualcuno, a cominciare da me. Lascia perdere.}
{491}{}{E se ti offrissi questo...}
{492}{}{Avrei delle altre domande...}
{493}{}{Nevermind then, Monte. I'm outta here.}
{495}{}{Eh... be'... sono tanti chip. (Si lecca le labbra. Sembra combattuto dentro....ma la battaglia dura poco.) Senti, non l'hai sentito da me...}
{496}{}{Understood. Go on.}
{500}{}{(Sogghigna) Forse ho sentito qualcosa, forse no. Dimmi una cifra.}
{501}{}{All right... talk a price.}
{502}{}{How about a thousand chips? I got it with me.}
{503}{}{Not even for 750 chips?}
{504}{}{How about 500 chips?}
{505}{}{250 chip ti sembrano giusti?}
{506}{}{Avrei delle altre domande...}
{507}{}{Nevermind then, Monte. I'm outta here.}
{510}{}{Ah! Con quella roba non compreresti neanche un secchio di piscio. Lascia perdere.}
{511}{}{E se ti offrissi questo...}
{512}{}{Avrei delle altre domande...}
{513}{}{Nevermind then, Monte. I'm outta here.}
{515}{}{Queeeesta e' la cifra giusta. (Sorride maliziosamente.) Senti, non l'hai sentito da me, ma se fossi in te, darei un'occhiata al seminterrato del Desperado in Virgin Street. Ci sono un sacco di "topi" la', se capisci cosa intendo.}
{516}{}{Avrei delle altre domande...}
{517}{}{Capito. Grazie.}
{520}{}{(Scrolla le spalle) Forse so qualcosa, forse no. Dimmi una cifra e potrei avere qualcosa da dire.}
{521}{}{All right... talk a price.}
{522}{}{How about a thousand chips? I got it with me.}
{523}{}{Not even for 750 chips?}
{524}{}{How about 500 chips?}
{525}{}{250 chip ti sembrano giusti?}
{526}{}{Avrei delle altre domande...}
{527}{}{Nevermind then, Monte. I'm outta here.}
{530}{}{(Strizza gli occhi, si avvicina) Per quella cifra, non so niente.}
{531}{}{E se ti offrissi questo...}
{532}{}{Avrei delle altre domande...}
{533}{}{Nevermind then, Monte. I'm outta here.}
{535}{}{Ci siamo... (strizza gli occhi, si avvicina) ...chiederei al vecchio Jules all'ingresso della citta'. Niente
 gli sfugge... e se qualcosa gli fosse sfuggito, ci aveva messo il dito, capisci cosa intendo?}
{536}{}{Avrei delle altre domande...}
{537}{}{All right then, Monte. Thanks.}
{540}{}{(Scrolla le spalle) Sento cose, vedo cose. Per 200 chip, forse puoi attingere alla mia esperienza, capisci cosa intendo?}
{541}{}{Here's 200 chips.}
{542}{}{I'll give you 150.}
{543}{}{100 chips or nothing.}
{544}{}{Avrei delle altre domande...}
{545}{}{Nevermind then, Monte. I'm outta here.}
{550}{}{Sei sordo? HO DETTO 200 chip, e lo penso davvero.}
{551}{}{All right. Here's 200 chips.}
{552}{}{Avrei delle altre domande...}
{553}{}{Nevermind then, Monte. I'm outta here.}
{555}{}{Affare fatto. (Monte si avvicina) Be', conosci quel tipo Eldridge, quello che gestisce la New Reno Arms? DICE che fa
 potenziamenti alle armi, ma non l'ho mai visto lavorare. Potresti dare un'occhiata al suo posto... ma non l'hai sentito da me.}
{556}{}{Avrei delle altre domande...}
{557}{}{Understood. Thanks, Monte.}
{560}{}{Il Boneyard a sud della citta'. Puzza da fare schifo, quello.}
{561}{}{Oh... I see. Now, about the Wright kid...}
{562}{}{Forget the Wright kid. I had some other questions...}
{563}{}{All right then, Monte. Thanks.}
{565}{}{Io punto su Renesco, quel vecchio stronzo che gestisce la farmacia sul lato ovest. Non so
 se l'ha venduta AL ragazzo di sicuro, ma sa QUALCOSA. (Si guarda intorno) E' tutto quello che diro'.}
{566}{}{Avrei delle altre domande...}
{567}{}{All right then, Monte. Thanks.}
{570}{}{(Si guarda intorno, poi si china e si sfila lo stivale. Svita il tacco e tira fuori una carta... sulla carta
 c'e' un uomo con uno strano cappello che impugna una mazza.) Interessato? E' autentica memorabilia pre-guerra.}
{571}{}{No, ho gia' abbastanza oggetti nell'inventario... preferirei avere qualche informazione invece.}
{572}{}{Uh, certo. Perche' no? Questo chiudera' i conti tra noi.}
{573}{}{Sorry pal, no chips, no game. Come back when you got more money.}
{574}{}{Sorry lady, no chips, no game. Come back when you got more money.}
{575}{}{Yeah, maybe next time then.}
{576}{}{Scambi rapidamente il mazzo di carte di Monte con il mazzo segnato.}
{600}{}{spades}
{601}{}{hearts}
{602}{}{diamonds}
{603}{}{clubs}
{604}{}{due}
{605}{}{tre}
{606}{}{quattro}
{607}{}{cinque}
{608}{}{sei}
{609}{}{sette}
{610}{}{otto}
{611}{}{nove}
{612}{}{dieci}
{613}{}{ di }
