{100}{}{You see a grungy, shaggy looking man.}
{101}{}{I suoi vestiti sono strappati e sporchi. Ha diversi graffi sulle braccia e sulle gambe.}
{150}{}{Woof! Wooof. Woooof.}
{151}{}{Uh, are you alright?}
{152}{}{Uh, right. Bye.}
{153}{}{Hey, I think I found something that might help your condition.}
{154}{}{Hmm... Sembra che tu possa soffrire di un disturbo neurologico, forse epilessia. Purtroppo non posso
 fare nulla. Arrivederci.}
{160}{}{Woof. Woof woof. Woooof.}
{250}{}{Grrr!}
{251}{}{Grrrrrr!}
{252}{}{Grrrrrrrr!}
{253}{}{Grrrrrrrrrr!}
{254}{}{[Shamble away]}
{255}{}{Grrrrrrrrr! Grrr! Woof!}
{256}{}{(L'uomo mugola e se la squaglia.)}
{257}{}{Hehe. Nice doggie...}
{258}{}{Hehe. Io super genio...}
{300}{}{Woof?}
{301}{}{Si'. Ascolta attentamente questa serie di lettere che sto per dirti...}
{302}{}{(Pronunci lentamente la serie di lettere che hai imparato dal computer dell'EPA, assicurandoti di usare le
 inflessioni corrette su ogni lettera. Quando finisci di leggere la frase rialzi lo sguardo verso l'uomo. Ti guarda
 poi scuote tutto il corpo come un cane che cerca di asciugarsi dopo un acquazzone.)}
{303}{}{[AVANTI]}
{304}{}{Woo- Woah. Ehi, riesco a parlare normalmente! Wow, e' fantastico. Cosa mi hai fatto?}
{305}{}{Ho scoperto che se leggi una serie specifica di lettere, assicurandoti di usare le inflessioni corrette su ogni
 lettera, puoi guarire qualcuno dall'autismo o dall'epilessia.}
{306}{}{Mi sembra una bella fesseria, ma ehi, sto parlando, quindi qualcosa di vero ci deve essere. Comunque, apprezzo davvero
 quello che hai fatto. Tieni, prendi questi Stimpak. Li ho trovati mentre cercavo cibo dietro questi edifici.}
{307}{}{Thanks. See you around.}
{350}{}{Uff!}
{351}{}{Woof! Woooof!}
{352}{}{*Si gratta*}
{400}{}{Bau! Heh, stavo scherzando. Grazie ancora per avermi guarito.}
{500}{}{You cure the Barking Man.}
{600}{}{*whimper*}
{601}{}{Il pugile ti guarda con occhi terrorizzati}
