{100}{}{Vedi un uomo dall’aspetto trasandato e arruffato.}
{101}{}{I suoi vestiti sono strappati e sporchi. Ha diversi graffi sulle braccia e sulle gambe.}
{150}{}{Woof! Woof. Woooof.}
{151}{}{Ehm... tutto bene?}
{152}{}{Ehm... va bene. Addio.}
{153}{}{Ehi, credo di aver trovato qualcosa che potrebbe aiutarti.}
{154}{}{Hmm... Sembra che tu possa soffrire di un disturbo neurologico, forse epilessia. Purtroppo non posso
 fare nulla. Arrivederci.}
{160}{}{Woof. Woof?woof. Woooof.}
{250}{}{Grrr!}
{251}{}{Grrrrrr!}
{252}{}{Grrrrrrrr!}
{253}{}{Grrrrrrrrrr!}
{254}{}{[Allontanati barcollando]}
{255}{}{Grrrrrr! Grrr! Woof!}
{256}{}{(L'uomo mugola e se la squaglia.)}
{257}{}{Hehe... bel cagnolino...}
{258}{}{Hehe. Io super genio...}
{300}{}{Woof?}
{301}{}{Si'. Ascolta attentamente questa serie di lettere che sto per dirti...}
{302}{}{(Pronunci lentamente la serie di lettere che hai imparato dal computer dell'EPA, assicurandoti di usare le
 inflessioni corrette su ogni lettera. Quando finisci di leggere la frase rialzi lo sguardo verso l'uomo. Ti guarda
 poi scuote tutto il corpo come un cane che cerca di asciugarsi dopo un acquazzone.)}
{303}{}{[AVANTI]}
{304}{}{Woo- Woah. Ehi, riesco a parlare normalmente! Wow, e' fantastico. Cosa mi hai fatto?}
{305}{}{Ho scoperto che se leggi una serie specifica di lettere, assicurandoti di usare le inflessioni corrette su ogni
 lettera, puoi guarire qualcuno dall'autismo o dall'epilessia.}
{306}{}{Mi sembra una bella fesseria, ma ehi, sto parlando, quindi qualcosa di vero ci deve essere. Comunque, apprezzo davvero
 quello che hai fatto. Tieni, prendi questi Stimpak. Li ho trovati mentre cercavo cibo dietro questi edifici.}
{307}{}{Grazie. Ci vediamo.}
{350}{}{Uff!}
{351}{}{Woof! Woooof!}
{352}{}{*Si gratta*}
{400}{}{Bau! Heh, stavo scherzando. Grazie ancora per avermi guarito.}
{500}{}{Curi l’Uomo?Che?Abbaia.}
{600}{}{*guaito*}
{601}{}{Il pugile ti guarda con occhi terrorizzati.}
