{100}{}{Vedi Nikki la dolce.}
{125}{}{You see one of the casino dealers.}
{150}{}{Vedi Nikki la dolce.}
{151}{}{Vedi Darlin’ Nikki. Ti fa l’occhiolino.}
{152}{}{You see Darlin' Nikki. She motions for you to come over and play.}
{153}{}{Vedi Darlin’ Nikki. Mason aveva ragione sul suo lato B.}
{154}{}{Vedi Darlin’ Nikki. Il suo vestito copre a malapena il suo corpo.}
{155}{}{Vedi Darlin’ Nikki. Mason aveva ragione sul suo lato B.}
{156}{}{Vedi Darlin’ Nikki. Il suo vestito copre a malapena il suo corpo.}
{160}{}{You see Darlin' Nikki. She motions for you to come over and play.}
{161}{}{Vedi Darlin’ Nikki. Il suo vestito copre a malapena il suo corpo.}
{162}{}{Vedi Darlin’ Nikki. Il suo vestito copre a malapena il suo corpo.}
{170}{}{You see one of the casino dealers.}
{171}{}{Vedi una delle croupier del casino'. Ti fa l'occhiolino.}
{172}{}{You see one of the casino dealers. She motions for you to come over and play.}
{173}{}{Vedi una delle croupier del casino'. Ha due gambe niente male.}
{174}{}{Vedi una delle croupier del casino'. I suoi abiti coprono a malapena il suo corpo.}
{175}{}{Vedi una delle croupier del casino'. Profuma davveeero di buono.}
{180}{}{You see one of the casino dealers. She motions for you to come over and play.}
{181}{}{Vedi una delle croupier del casino'. I suoi abiti coprono a malapena il suo corpo.}
{182}{}{Vedi una delle croupier del casino'. I suoi abiti coprono a malapena il suo corpo.}
{183}{}{You see one of the casino dealers. She motions for you to come over and play.}
{200}{}{::Cheers::}
{201}{}{::Applaude::}
{202}{}{::Fischia::}
{203}{}{! Benvenuto nel nostro casino', eroe!}
{204}{}{Credevo ti fossi dimenticato di noi mentre salvavi il mondo.}
{210}{}{Salve, }
{211}{}{Se cerchi un po' di compagnia per dopo...}
{212}{}{Ehi, tu… [strizza l’occhio]… vuoi giocare?}
{213}{}{Sembra cosi'...(trema)...pericoloso.}
{214}{}{Benvenuto nel nostro casino', }
{215}{}{Puo' mettere una buona parola con il boss per me?}
{216}{}{Salve, signora. Me lo dica se posso esserle utile per qualcosa.}
{217}{}{Vuole giocare, signora?}
{218}{}{Sembra cosi'...(trema)...pericolosa.}
{220}{}{Looks like this one's already gambling with his life.}
{221}{}{Uh, credo che sia entrato nel casino' sbagliato...}
{222}{}{Se non se ne va prima che lo vedano i ragazzi...}
{223}{}{Uh-oh. Guai in arrivo...}
{224}{}{Sembra che questa qui stia gia' giocando d'azzardo con la sua vita.}
{225}{}{Uh, credo che sia entrata nel casino' sbagliato...}
{226}{}{Se non se ne va prima che la vedano i ragazzi...}
{230}{}{Hey, muscles. You looking to spend some chips?}
{231}{}{Ehi, campione… [strizza l’occhio]… ti va di giocare?}
{232}{}{Ehi, campione… [sorride]… vuoi tentare la sorte?}
{233}{}{Se cerchi un po' di compagnia per dopo...}
{234}{}{Chissa' se posso rivolgergli la parola...}
{235}{}{Ehi, }
{236}{}{Se vuoi vincere dei soldi, sei venuto nel posto giusto.}
{237}{}{Il miglior casino' di New Reno. Del MONDO, addirittura.}
{238}{}{Donna Fortuna e' qui da noi, stasera... vincono tutti!}
{239}{}{Vieni qui, }
{240}{}{Vuoi bere qualcosa?}
{241}{}{Benvenuto nel nostro casino', }
{242}{}{Salve, }
{243}{}{Vuoi giocare, }
{244}{}{Benvenuto nel nostro casino', }
{250}{}{Hey there, movie man. You looking to spend some chips?}
{251}{}{Ehi, }
{252}{}{Ehi, }
{253}{}{Se vuoi vincere dei soldi, }
{254}{}{Il miglior casino' di New Reno. Del MONDO, addirittura.}
{255}{}{Donna Fortuna e' qui da noi, stasera... vincono tutti!}
{266}{}{Vieni qui, }
{267}{}{Vuoi bere qualcosa?}
{268}{}{Benvenuto nel nostro casino', }
{269}{}{Ehilà, signora Star del Cinema. Vuole spendere lo stipendio?}
{270}{}{Hey there, sweetie. You looking to spend some chips?}
{271}{}{Ehi, dolcezza… [strizza l’occhio]… vuoi giocare?}
{272}{}{Ehi, dolcezza… [sorride]… vuoi tentare la fortuna?}
{273}{}{Se vuoi vincere dei soldi, sei venuto nel posto giusto.}
{274}{}{Il miglior casino' di New Reno. Del MONDO, addirittura.}
{275}{}{Donna Fortuna e' qui da noi, stasera... vincono tutti!}
{276}{}{Vieni qui, e vinci!}
{277}{}{Vuoi bere qualcosa, tesoro?}
{278}{}{Benvenuta nel nostro casino', tesoro.}
{279}{}{Questo tavolo e' libero, se vuoi giocare...}
{280}{}{Ehila', tesoro. Che ne dici di giocarti qualche spicciolo?}
{281}{}{Vuoi giocare un po', tesoro?}
{282}{}{Benvenuta nel nostro casino', tesoro.}
{290}{}{Well, you're crazy for coming in here, but…place your bets. Minimum bet 5 chips. Place your bets…}
{291}{}{Ehm… fate il vostro gioco… puntata minima 5 fiches. Fate il vostro gioco…}
{292}{}{Punti, signore. Puntata minima 5 fiches. Fate il vostro gioco…}
{293}{}{Punti, signora. Puntata minima 5 fiches. Fate il vostro gioco…}
{294}{}{Fate il vostro gioco, puntata minima 5 fiches. Fate il vostro gioco…}
{295}{}{Me no minimo! Me grande!}
{296}{}{Buoni zuccherini! YUM! (mordi i dadi) Ouch! No buoni!}
{297}{}{Cosa essere questo gioco? Me può scommettere pelle di gecko? Me ha pelle di… ooooh… lucine belle là!}
{298}{}{Scommetti 5 fiches?}
{299}{}{Scommetti 15 fiches?}
{300}{}{Scommetti 25 fiches?}
{301}{}{Scommetti 50 fiches?}
{302}{}{Tu essere Nikki?}
{303}{}{Come va, Nikki?}
{304}{}{Whoa, troppo per le mie tasche. Me ne vado.}
{305}{}{Niente giocate oggi, grazie.}
{310}{}{Uh, very well, sir. Come back soon.}
{311}{}{Uh, molto bene, signora. Torna presto.}
{312}{}{Um... Mi hanno detto che qui sul retro stanno distribuendo dei cervelli. Forse dovresti andare a dare un'occhiata.}
{313}{}{Ciaooooo.}
{314}{}{Beeene. }
{315}{}{Uh… cervelli… cosa essere? Me vuole vedere!}
{320}{}{Very well, sir. Come back soon.}
{321}{}{Molto bene, signore. Tornate presto.}
{322}{}{5 fiches? “Troppo per le tue tasche?” Amico, sei nella città sbagliata.}
{323}{}{5 fiches? “Troppo per le tue tasche?” Amico, sei nella città sbagliata.}
{324}{}{5 fiches? “Troppo per le tue tasche?” Ragazza, sei nella città sbagliata.}
{325}{}{5 fiches? “Troppo per le tue tasche?” Ragazza, sei nella città sbagliata.}
{326}{}{Lo faro', grazie.}
{327}{}{Forse, ma almeno *io* non ci vivo.}
{330}{}{Sorry, sir. Better luck next time.}
{331}{}{Mi spiace, signore. Ritentate, sarete piu' fortunata.}
{332}{}{Mi spiace. Ritenta, sarai piu' fortunato.}
{333}{}{Hai [C] fiches. Continui a giocare?}
{334}{}{Smetti di giocare.}
{335}{}{Smetti di giocare.}
{340}{}{Winner! Well done, sir!}
{341}{}{Vincitrice! Ben fatto, signora!}
{342}{}{Vincitore!}
{343}{}{Hai [C] fiches. Continui a giocare?}
{344}{}{Smetti di giocare.}
{345}{}{Smetti di giocare.}
{350}{}{Winner! You've doubled your money! Well done, sir!}
{351}{}{Avete vinto! Prendete il doppio dei soldi che avevate puntato. Ben fatto, signora!}
{352}{}{Hai vinto! Prendi il doppio dei soldi che avevi puntato!}
{353}{}{Hai [C] fiches. Continui a giocare?}
{354}{}{Smetti di giocare.}
{355}{}{Smetti di giocare.}
{360}{}{Winner! You've tripled your money! Luck is in the house tonight! Well done, sir!}
{361}{}{Avete vinto! Prendete il triplo dei soldi che avevate puntato. La Fortuna ci ha fatto visita, stanotte! Ben fatto, signora!}
{362}{}{Hai vinto! Prendi il triplo dei soldi che avevi puntato!}
{363}{}{Hai [C] fiches. Continui a giocare?}
{364}{}{Smetti di giocare.}
{365}{}{Smetti di giocare.}
{370}{}{What do you want now? You here to waste my time, or you gonna place a bet?}
{371}{}{Sono chiunque tu VOGLIA che io sia, tesoro. Allora, vuoi puntare?}
{372}{}{Sono chiunque tu VOGLIA che io sia, cara. Allora, vuoi puntare?}
{373}{}{Fai una puntata.}
{374}{}{Sì. Scommetto che sai dov’è Pretty Boy Lloyd.}
{375}{}{Si', scommetto che tu e Pretty Boy Lloyd stavate entrambi rubando soldi al signor Salvatore. Difficile credere che
 non ti sia accorta di lui che barava tutte quelle volte.}
{376}{}{Conosci qualcuno di nome Pretty Boy Lloyd?}
{377}{}{Parleremo più tardi, Nikki.}
{380}{}{Yeah, I heard he's DEAD. That what you want to hear, killer?! Huh?! Now you gonna place a bet or bullshit me some more?}
{381}{}{No. Vuoi puntare o no?}
{382}{}{Fai una puntata.}
{383}{}{Sì. Scommetto che sai dov’è Pretty Boy Lloyd.}
{384}{}{Si', scommetto che tu e Pretty Boy Lloyd stavate entrambi rubando soldi al signor Salvatore. Difficile credere che non ti sia accorta
 che Lloyd barava tutte quelle volte.}
{385}{}{Parleremo più tardi, Nikki.}
{390}{}{Then that's a bet you'd LOSE, sweetheart, but if you're as stupid as you are ugly, you'd probably bet anyway. I ain't
 seen that bum since he conned Mr. Salvatore.}
{391}{}{Allora è una scommessa che perderesti, tesoro. Non vedo quel pezzente da quando ha fregato il signor Salvatore.}
{392}{}{Allora è una scommessa che perderesti, ragazza. Non vedo quel pezzente da quando ha fregato il signor Salvatore.}
{393}{}{Forse non mi hai sentito la prima volta, quindi per i non udenti: dov'e' Lloyd?}
{394}{}{Abbastanza sospetto che non te ne sia accorta tutte quelle volte. Dovresti essere cieca... o corrotta.}
{395}{}{Bene. Parleremo più tardi, Nikki.}
{400}{}{Sweetheart, I TOLD you that I don't know where he is. Now, look, I'm WORKING here, so go back to whatever rock you --}
{401}{}{Ragazza, TI HO DETTO che non so dove sia. Senti, STO LAVORANDO, quindi torna pure sotto la pietra da cui sei uscita e—}
{402}{}{Nikki, Nikki... sto perdendo la PAZIENZA. Se non mi dici dov'e' Lloyd, perdo anche le staffe.}
{403}{}{Nikki, non so cosa e' successo tra te e Lloyd. Ma sai una cosa? Non ho BISOGNO di saperlo. Diro' semplicemente
 al signor Salvatore quello che sospetto.}
{404}{}{Nikki, so che hai aiutato Lloyd a barare. Dimmi dov'e' Lloyd, e ti do meta' del suo bottino: 500 chip.}
{405}{}{Abbastanza sospetto che non te ne sia accorta tutte quelle volte. Dovresti essere cieca... o corrotta.}
{406}{}{Parleremo più tardi, Nikki.}
{410}{}{You touch me, and Mr. Salvatore will skin you alive.}
{411}{}{Salvatore non ti proteggera'; mazzieri come te se ne trovano a bizzeffe. Smettila di menare il can per l'aia e dimmi dov'e' Lloyd, o ALTRIMENTI.}
{412}{}{Salvatore non ti proteggera'; e' morto. Smettila di menare il can per l'aia e dimmi dov'e' Lloyd, o ALTRIMENTI.}
{413}{}{Nikki, so che hai aiutato Lloyd a barare. Dimmi dov'e' Lloyd, e ti do meta' del suo bottino: 500 chip.}
{414}{}{Abbastanza sospetto che non te ne sia accorta tutte quelle volte. Dovresti essere cieca... o corrotta.}
{415}{}{Parleremo più tardi, Nikki.}
{420}{}{Di cosa stai parlando?}
{421}{}{Nikki, se non mi dici tutto adesso, diro' al signor Salvatore che eri coinvolta, che lo fossi o no.
 Fara' fare a Mason un macello di te, e trovera' qualcuno al tuo posto in un'ora.}
{422}{}{Nikki, so che hai aiutato Lloyd a barare. Dimmi dov'e' Lloyd, e ti do meta' del suo bottino: 500 chip.}
{423}{}{Abbastanza sospetto che non te ne sia accorta tutte quelle volte. Dovresti essere cieca... o corrotta.}
{424}{}{Parleremo più tardi, Nikki.}
{430}{}{Look, LIKE I SAID, I don't know where he is. But *maybe* I heard he used to have a room at the Desperado. You might find
 something there. Now, if you don't mind, I got to get back to work.}
{431}{}{Nikki, so che hai aiutato Lloyd a barare. Dimmi dov'e' Lloyd, e ti do meta' del suo bottino: 500 chip.}
{432}{}{Abbastanza sospetto che non te ne sia accorta tutte quelle volte. Dovresti essere cieca... o corrotta.}
{433}{}{Parleremo più tardi, Nikki.}
{440}{}{Look, I just STARTED working here, and I can't recognize every card counter and two-bit cheat that walks in.
 I gotta pretty good line on shitheads like you, though.}
{441}{}{Oh, quindi e' cosi' che tu e Lloyd vi siete messi insieme?}
{442}{}{Quindi hai appena cominciato a lavorare, eh? Molto conveniente. Be', e' tutto quello che mi serve sapere. Di' a Lloyd che e' un uomo morto.}
{443}{}{Nikki, so che hai aiutato Lloyd a barare. Dimmi dov'e' Lloyd, e ti do meta' del suo bottino: 500 chip.}
{444}{}{Parleremo più tardi, Nikki.}
{450}{}{Yeah, you take enough Jet, and everything seems suspicious, don't it?}
{451}{}{E' DAVVERO sospetto. Avresti dovuto capire che tipo era Lloyd appena e' entrato in questo casino'.}
{452}{}{Nikki, so che hai aiutato Lloyd a barare. Dimmi dov'e' Lloyd, e ti do meta' del suo bottino: 500 chip.}
{453}{}{Parleremo più tardi, Nikki.}
{460}{}{You get the hell outta here right now. I ain't got nothing else to say to you.}
{461}{}{Non ho niente da dirti. Sparisci.}
{462}{}{Per ora, forse no. Ma parlero' con te piu' tardi, Nikki. Puoi contarci.}
{470}{}{You talk smooth...but so do snakes. MAYBE I know where Lloyd is, MAYBE I don't. You got 500 chips?}
{471}{}{Forse. Dipende da cosa hai per me.}
{480}{}{COULD be that Lloyd still has my take, and I ain't sure he's gonna give it to me. So COULD be that - for 500 chips - I
 COULD tell you where his lying ass is hanging out.}
{481}{}{Fatto. Ecco i 500 chip. Dimmi dov'e'.}
{482}{}{E' un prezzo piuttosto alto per un mucchio di "forse" e "potrebbe". Lo trovero' da solo.}
{483}{}{Non ho abbastanza fiches. Tornerò quando ne avrò di più. Spero che sarai ancora qui.}
{490}{}{(Pockets the money) Check the boiler room in the basement of the Desperado. That's where the son of a bitch was
 going to run if things got hot.}
{491}{}{D’accordo. A dopo, Nikki.}
{500}{}{Would you get outta here?! People see us talking like this, then THEY'RE gonna talk. Understand?}
{501}{}{D’accordo. A dopo, Nikki.}
{510}{}{Go to hell, then! I ain't got nothing else to say to you, EVER.}
{511}{}{Mi spezza il cuore. A dopo, Nikki.}
{600}{}{Corrompi Nikki per farti dire dove potrebbe nascondersi Lloyd.}
{1210}{}{. Posso aiutarti in… *qualche* modo?}
{1214}{}{.}
{1235}{}{. Che ne dici di giocare un po'?}
{1239}{}{, e vincerai dei soldi.}
{1241}{}{.}
{1242}{}{. Fammi sapere se ti serve qualcosa.}
{1243}{}{?}
{1244}{}{.}
{1251}{}{…[strizza l’occhio]… vuoi giocare?}
{1252}{}{…[sorride]… vuoi tentare la sorte?}
{1253}{}{, sei nel posto giusto.}
{1266}{}{, e vincerai dei soldi.}
{1268}{}{.}
{1314}{}{ un nuovo oggetto fa sempre comodo.}
{2699}{}{Farai uno spettacolo qui, stanotte?}
