{100}{}{You see the casino pit boss.}
{150}{}{You see a well-dressed man. He is surveying the casino.}
{151}{}{Vedi un capotavola. Sta sorvegliando il casino'.}
{200}{}{Uh…you'll need to remove that armor.}
{201}{}{Ehm, signore… o signora… deve togliersi quell’armatura.}
{202}{}{Signore... signora... non puo' indossare quello nel casino'.}
{205}{}{Uh, perche' si muove cosi' silenziosamente, signore?}
{206}{}{Uh, e' in missione segreta, signore?}
{210}{}{Uh, perche' si muove cosi' silenziosamente, signora?}
{211}{}{Uh, e' in missione segreta, signora?}
{215}{}{Buonasera, }
{216}{}{Sera, }
{220}{}{Buonasera, }
{221}{}{Sera, }
{225}{}{Buongiorno, }
{226}{}{Buongiorno, }
{230}{}{Buongiorno, }
{231}{}{Buongiorno, }
{235}{}{Amico, stai entrando nel casino' sbagliato.}
{236}{}{Farai meglio ad andartene. Subito.}
{237}{}{Questo non e' il posto giusto dove mettere in gioco la tua vita. Sara' meglio che tu te ne vada.}
{238}{}{Troia, stai entrando nel casino' sbagliato.}
{245}{}{Signore, mi dispiace ma deve mettere via quell'arma.}
{250}{}{Signora, mi dispiace ma deve mettere via quell'arma.}
{255}{}{Dolcezza, mi dispiace, ma non puoi portare armi all'interno del casino'. Eh-eh... sei gia' fatale cosi' come sei.}
{260}{}{Dolcezza, con un corpo come quello, non riusciresti a passare inosservata nemmeno in un ospizio per ciechi.}
{265}{}{Selvaggio, farai meglio a mettere via quell'arma IMMEDIATAMENTE.}
{270}{}{Selvaggio, farai meglio a smetterla di muoverti furtivamente... SUBITO.}
{275}{}{Ehi, ehi…Myron! Era da un po' che non ti si vedeva fuori dal laboratorio.}
{276}{}{Sei qui per provare un po' della nuova merce, Myron?}
{277}{}{Ehi! Entra, Myron.}
{280}{}{Shoot. What d'you want to know?}
{281}{}{Fooooooo foo foo fooooo}
{282}{}{-Allontanati-}
{283}{}{Chi sei?}
{284}{}{Che casino' e' questo?}
{285}{}{Puoi dirmi qualcosa sul casino'?}
{286}{}{Conosci qualcuno di nome Pretty Boy Lloyd?}
{287}{}{Chi e' quel vecchio alla slot machine?}
{288}{}{Quel comico che hai sul palco fa schifo. Ti dispiace se ci provo io?}
{289}{}{Ti serve una ballerina per stanotte? Sono disponibile per un ingaggio a tempo limitato.}
{290}{}{Grazie, lo faro'.}
{291}{}{Niente, grazie. Scusa il disturbo.}
{292}{}{Stavo solo controllando. Continua pure.}
{295}{}{Niente droidi.}
{296}{}{Qui non serviamo i droidi.}
{297}{}{Niente droidi. Loro se ne stanno fuori.}
{300}{}{Uh, you better run along now, sir.}
{301}{}{Uh, faresti meglio ad andartene adesso, signora.}
{302}{}{Levati dai piedi, ritardato.}
{303}{}{La mamma dice che ero spezziale}
{304}{}{-Allontanati-}
{305}{}{Non dovrei chiacchierare mentre sono in servizio, ma sono contento che tu abbia distrutto l'Enclave.}
{306}{}{Ehi, }
{310}{}{Need some more chips at table three…}
{311}{}{Bel pubblico, oggi…}
{315}{}{Yeah, yer Mom said I was special, too. Now take a hike…maybe she's along Virgin street somewhere.}
{316}{}{Oh che bello! Ciao ciao}
{317}{}{-Allontanati-}
{320}{}{Need some more chips at table three…}
{321}{}{Buon pubblico stasera...}
{325}{}{Sono il capotavola. Allora, cosa posso fare per te?}
{326}{}{Gestisco il piano del casino' qui. Se hai bisogno di qualcosa, chiedi pure.}
{327}{}{Che casino' e' questo?}
{328}{}{Puoi dirmi qualcosa sul casino'?}
{329}{}{Niente, grazie. Scusa il disturbo.}
{335}{}{Ehi, }
{336}{}{! Heard yer the one who kicked the Enclave back to the stone age! I've been instructed to give you some chips,
 courtesy of the casino. Enjoy yourself, sir.}
{337}{}{! Heard yer the one who kicked the Enclave back to the stone age! I've been instructed to give you some chips,
 courtesy of the casino. Enjoy yourself, ma'am.}
{338}{}{. Cosa c'e', capo? Ti prendo qualcosa? Da bere? Una cameriera?}
{339}{}{. La piu' bella del casino'. Ti prendo qualcosa? Da bere? Un tavolo privato?}
{340}{}{Cosa posso fare per te, amico?}
{341}{}{Cosa posso fare per te, cara?}
{342}{}{Fooooooo foo foo fooooo}
{343}{}{-Allontanati-}
{344}{}{Chi sei?}
{345}{}{Che casino' e' questo?}
{346}{}{Puoi dirmi qualcosa sul casino'?}
{347}{}{Conosci qualcuno di nome Pretty Boy Lloyd?}
{348}{}{Chi e' quel vecchio alla slot machine?}
{349}{}{Quel comico che hai sul palco fa schifo. Ti dispiace se ci provo io?}
{350}{}{Ti serve una ballerina per stanotte? Sono disponibile per un ingaggio a tempo limitato.}
{351}{}{Grazie, lo faro'.}
{352}{}{Niente, grazie. Scusa il disturbo.}
{353}{}{Stavo solo controllando. Continua pure.}
{355}{}{The }
{356}{}{The }
{357}{}{Chi sei?}
{358}{}{Puoi dirmi qualcosa sul casino'?}
{359}{}{Capisco. Grazie delle informazioni.}
{360}{}{Ehi, guarda chi c'e'! Ehi, }
{361}{}{. Welcome to }
{362}{}{Fooooooo foo foo fooooo}
{363}{}{-Allontanati-}
{364}{}{Chi sei?}
{365}{}{Che casino' e' questo?}
{366}{}{Puoi dirmi qualcosa sul casino'?}
{367}{}{Conosci qualcuno di nome Pretty Boy Lloyd?}
{368}{}{Chi e' quel vecchio alla slot machine?}
{369}{}{Grazie. Ti serve una ballerina per stanotte? Sono disponibile per un ingaggio a tempo limitato.}
{370}{}{Grazie, sono lusingata. Sono passata solo per salutare.}
{375}{}{Nope, it's just stubborn... just like him. It could probably use a little repair work, but we ain't got no slot
 mechanics that can fix that damn thing.}
{376}{}{Avrei delle altre domande...}
{377}{}{Interessante. Grazie per l'informazione.}
{385}{}{Si', quel figlio di puttana e' venuto qui circa una settimana fa, ha fregato un tavolo di circa mille chip, poi e' sparito.
 Non so dov'e' adesso, ma aveva una stanza al Desperado.}
{386}{}{Si', un tizio con quel nome affittava una delle stanze al piano di sopra...la 204. Era in pari con i pagamenti, ma e' sparito
 qualche giorno fa e nessuno l'ha visto andarsene.}
{387}{}{Il signor Salvatore ha detto che c'era un mazziere specifico da cui Lloyd ha vinto i soldi. Chi era?}
{388}{}{Avrei delle altre domande...}
{389}{}{Grazie delle informazioni.}
{395}{}{Nikki? Si', e' la', al tavolo centrale. C'e' qualche problema?}
{396}{}{No problem. Just wanted to meet her. I had some other questions...}
{397}{}{Grazie delle informazioni.}
{405}{}{Her name WAS Nikki. She used to work here but she got aced... not too long ago.}
{406}{}{Hmmm. Do you mind if I ask you some other questions...?}
{407}{}{Interessante. Grazie per l'informazione.}
{415}{}{Her name was Nikki. She used to work here but she took off not too long ago. Just packed her shit and bailed.}
{416}{}{Do you mind if I ask you some other questions...}
{417}{}{Interessante. Grazie per l'informazione.}
{425}{}{Sure, be good for business. Dressing room's in the back…}
{426}{}{Eccellente. Saro' sul palco tra qualche minuto...}
{427}{}{Non adesso. Avrei delle altre domande...}
{428}{}{Non adesso, ma tornero'.}
{435}{}{No, stiamo ancora recuperando dalla tua ultima esibizione. Potresti provare in qualche altro casino'.}
{436}{}{All right, thanks. Say, I had some other questions...}
{437}{}{Okay... though I will be back.}
{445}{}{[You count up the evening's chips. Not a bad haul.]}
{446}{}{The leather was a nice touch. }
{447}{}{Anche il bavaglio a sfera che avevi con te non ha guastato. }
{448}{}{[CONTINUA]}
{455}{}{Yeah, he stinks worse than brahmin shit. Still, you...? Aw, why the hell not. A little improv ain't gonna hurt, but
 it's a rough crowd... better hope you're good.}
{456}{}{Oh, sono brava... guarda un po'.}
{457}{}{Non adesso, ma tornero'.}
{500}{}{Roba da ridere. Sei la nuova Milton Berle. Torna tra una settimana per un altro spettacolo.}
{501}{}{E' stato un grande spettacolo. Hai un ottimo numero. Torna tra una settimana per un altro show.}
{502}{}{I will. See you around.}
{510}{}{E' stata una roba orribile. Non so come fai, ma sei addirittura peggio del solito. Non credo che avremo bisogno di te ancora.}
{511}{}{Bene, andro' a portare il mio talento a qualcuno che lo sapra' DAVVERO apprezzare.}
{512}{}{Vabbe'. Ci vediamo.}
{520}{}{Eri in fiamme la' fuori. La prossima Traci Lords. }
{521}{}{I don't think I have seen anyone move like that on stage. You got real talent. }
{522}{}{I will. See you around.}
{523}{}{Come back in a week for another show.}
{530}{}{Sorry, you're not up to our standards.}
{531}{}{Whatever. I got some other questions.}
{532}{}{Bene, andro' a trovare qualcuno che SAPRA' apprezzare il mio talento. Ciao.}
{620}{}{Interested in me doing another comic routine?}
{621}{}{Ti avevo detto di tornare tra una settimana. Hai ancora un po' di tempo, ripassa piu' tardi.}
{622}{}{Alright. I got some questions then.}
{623}{}{I will see you around then.}
{720}{}{Is there an opening for any dancers tonight?}
{721}{}{Ti avevo detto di tornare tra una settimana. Hai ancora un po' di tempo, ripassa piu' tardi.}
{722}{}{Alright. I got some questions then.}
{723}{}{I will see you around then.}
{902}{}{Bishop}
{903}{}{Mordino}
{904}{}{Shark Club}
{905}{}{Desperado}
{1000}{}{Sai che il tuo matrimonio e' nei guai quando tua moglie dice: 'Ti interessa solo una cosa,' e tu non riesci a ricordare quale.}
{1001}{}{Il mio dottore mi ha detto di recente che fare jogging potrebbe aggiungere anni alla mia vita. Credo avesse ragione. Mi sento gia' dieci anni piu' vecchio.}
{1002}{}{Chi non capisce perche' l'America e' la Terra delle Promesse dovrebbe esserci durante una campagna elettorale.}
{1003}{}{I politici mi hanno sempre fatto ridere.}
{1004}{}{Qualcuno mi ha detto una volta che non mi alleno abbastanza. Be', si sbaglia. Mi alleno correndo ai funerali degli amici che si allenano.}
{1215}{}{, signore.}
{1216}{}{, signore.}
{1220}{}{, signora.}
{1221}{}{, signora.}
{1225}{}{, signore.}
{1226}{}{, signore.}
{1230}{}{, signora.}
{1231}{}{, signora.}
{1285}{}{Niente mutanti. Lui aspetta fuori.}
{1286}{}{Non mi interessa se il tuo amico e' uno degli Ex-Men, i mutanti aspettano fuori.}
{1287}{}{Quel mostro mutante non puo' entrare.}
{1306}{}{. Prenditi una pausa dal salvare il mondo e divertiti un po'.}
{1335}{}{This is the }
{1336}{}{This is the }
{1337}{}{Chi sei?}
{1338}{}{Puoi dirmi qualcosa sul casino'?}
{1339}{}{Niente, grazie. Scusa il disturbo.}
{1345}{}{Best goddamn casino in town... but I am a little biased. Anything else you want to know?}
{1346}{}{Il miglior cazzo di casino' in citta', i migliori cazzo di tavoli... ora perche' non vai a darci un'occhiata? Ok?}
{1347}{}{Chi sei?}
{1348}{}{Chi possiede questo casino'?}
{1349}{}{Ok, grazie. Scusa il disturbo.}
{1355}{}{ Famiglia. Hanno pompato molta vita in questo posto, ne hanno fatto un vero locale notturno, un gioiello splendente di New Reno.}
{1356}{}{ Famiglia. Hai qualcosa in contrario? Perche' se non sei qui per giocare, questo non e' il posto per te. Capito?}
{1361}{}{. Love your films.}
{1365}{}{That guy? Old Man McGee? Crazy sumabitch…he's been playing that machine there for the past few years, waiting for the big jackpot. His life fortune must be sitting in that thing, but it won't give him a single chip.}
{1366}{}{Quel tizio? Il vecchio McGee? Un pazzo figlio di puttana, questo e' sicuro. Heh.
 Era proprio incazzato per il fatto che gli hai vinto la fortuna. Stai attento con lui.}
{1367}{}{La macchina e' truccata?}
{1368}{}{Avrei delle altre domande...}
{1369}{}{Grazie delle informazioni.}
{1425}{}{Certo. Speriamo che tu sia bravo come l'ultima volta.}
{1455}{}{Certo. Comunque mi sta venendo a noia il solito. Speriamo che tu sia bravo come l'ultima volta.}
{1500}{}{Umm... Tua mamma e' cosi' grassa che quando e' caduta si e' dondolata fin quando non si e' addormentata cercando di rialzarsi.}
{1501}{}{Tua mamma e' cosi' graaaassa che ho dovuto prendere un aereo, un treno e un'automobile solo per stare dalla parte buona di quella vacca.}
{1502}{}{Allora, cosa ha detto un piatto all'altro?}
{1503}{}{Ok, why were the suspenders arrested?}
{1504}{}{Ok, perche' la donna non riusciva a comprare una panetteria?}
{2000}{}{Il tuo numero comico e' stato un successo.}
{2001}{}{Il tuo numero comico e' stato un flop.}
{2003}{}{A Washington, un uomo si alza per parlare e non dice nulla, e gli altri uomini gli danno torto per tre ore.}
{2010}{}{Il tuo numero di danza erotica e' stato un successo.}
{2335}{}{. Need anything, just ask.}
{2336}{}{. Almeno, l'ultima volta che ho controllato il cartello fuori dalla porta. Allora cosa posso fare per te?}
{2500}{}{[2 hours pass.]}
{2501}{}{[Passa 1 ora.]}
{2502}{}{Lunch is on me.}
{2503}{}{Sono stati arrestati per aver rapinato un paio di pantaloni.}
{2504}{}{Perche' non riusciva a raccogliere abbastanza grana.}
