{100}{}{Benvenuti a New Reno, la piu' grande cittadina del mondo. Il fuoco dei bidoni e le insegne al neon avvolgono la citta' d'un bagliore infernale.}
{101}{}{Davanti a te si estende una desolata distesa ricoperta di tombe. Pali insanguinati spuntano dal terreno con resti di cadaveri legati ad essi.}
{102}{}{Questa sembra essere una vecchia centrale elettrica di rifornimento. Un cimitero di carcasse d'auto circonda l'edificio.}
{103}{}{Sei giunto alle Stalle. Un recinto circonda le due entrate alla fattoria.}
{150}{}{[INDIETRO]}
{151}{}{[AVANTI]}
{201}{}{Salvatore}
{202}{}{Bishop}
{203}{}{Mordino}
{204}{}{Wright}
{221}{}{il Salvatore's}
{222}{}{lo Shark Club}
{223}{}{il Desperado}
{224}{}{}
{300}{}{}
{301}{}{Sussurro}
{302}{}{Ragno}
{303}{}{Morbillo}
{304}{}{Insegnante}
{305}{}{Spostatore}
{306}{}{Toro}
{307}{}{Skipper}
{308}{}{Sssh}
{309}{}{Mancino}
{310}{}{Destro}
{311}{}{Sopracciglia}
{312}{}{Tornado}
{313}{}{Moulty}
{314}{}{Scimmiotto}
{315}{}{Bitorzoluto}
{316}{}{Zampe}
{317}{}{Gooch}
{318}{}{Mannaia}
{319}{}{Brocco}
{320}{}{Due Volte}
{321}{}{Romeo}
{322}{}{Vinnie}
{323}{}{Pivello}
{324}{}{Silenziatore}
{325}{}{Martello}
{326}{}{Nocche}
{327}{}{Bender}
{328}{}{Il Droghiere}
{329}{}{Occhi di Serpe}
{330}{}{Lupo}
{331}{}{L'Accettaro}
{332}{}{Sorridente}
{333}{}{Ciccio}
{334}{}{Perla}
{335}{}{Jimmy di Reno}
{336}{}{Jade}
{337}{}{Faccia Sfregiata}
{338}{}{Diamond}
{339}{}{Asso}
{340}{}{Jack l'Occhio Solo}
{341}{}{Nikki}
{342}{}{Uomo di Ghiaccio}
{343}{}{Furbo}
{344}{}{Scivoloso}
{345}{}{Charlie}
{346}{}{Oppio}
{347}{}{Pugnale}
{348}{}{Sentenza}
{349}{}{Sistematore}
{350}{}{Shark}
{351}{}{Segugio}
{352}{}{Reverendo}
{353}{}{Magnum}
{354}{}{Iceberg}
{355}{}{Gina}
{356}{}{Vicki}
{357}{}{Cacciatore}
{358}{}{Ghigliottina}
{359}{}{Gelo}
{360}{}{Valentino}
{361}{}{Becchino}
{362}{}{Joe il Piccolo}
{363}{}{Regina di Ghiaccio}
{364}{}{Interruttore}
{365}{}{Dollari}
{366}{}{Fiches}
{367}{}{Fortunato}
{368}{}{Saint}
{369}{}{Numeri}
{370}{}{Mantide}
{371}{}{Scorpione}
{372}{}{Ometto}
{373}{}{Sam}
{374}{}{Blue Lou}
{375}{}{Tommy la Pistola}
{376}{}{Jane la Pazza}
{377}{}{Vedova}
{378}{}{Spazzino}
{379}{}{Nine Inch Nick}
{380}{}{Portapioggia}
{381}{}{Re}
{382}{}{Killer}
{383}{}{Santana}
{384}{}{Joey}
{385}{}{Caesar}
{386}{}{Mickey}
{387}{}{Vagabondo}
{388}{}{Giuseppe}
{389}{}{Macellaio}
{390}{}{Red}
{391}{}{Ruby}
{392}{}{X}
{393}{}{}
{400}{}{}
{401}{}{Pugnettoso}
{402}{}{Spinning Jenny}
{403}{}{Pistone}
{404}{}{Hurricane}
{405}{}{Gran Brutto Bastardone}
{406}{}{l'Eletto}
{407}{}{Toro Furioso}
{408}{}{LaMotta}
{409}{}{Mazza}
{410}{}{Joe di Vetro}
{411}{}{Nancy New Reno}
{412}{}{Toro Calvo}
{413}{}{Principessa}
{414}{}{Duke}
{415}{}{Machoman}
{416}{}{Iron Maiden}
{417}{}{Sventratore}
{418}{}{Valkyrie}
{419}{}{Hook}
{420}{}{Serpente a Sonagli}
{421}{}{Ragazza Cattiva}
{422}{}{Mandibola di Roccia}
{423}{}{Muro di Pietra}
{424}{}{Motosega}
{425}{}{Helen Ruote}
{426}{}{Tommy Pistola}
{427}{}{Vedova Nera}
{428}{}{Spacca}
{429}{}{Delilah}
{430}{}{Fulmine}
{431}{}{Jocco}
{432}{}{Sorella Acciaio}
{433}{}{Super martello}
{434}{}{Apollo}
{435}{}{Scrapiron}
{436}{}{Tigre}
{437}{}{Tyson}
{438}{}{Lady J}
{439}{}{Drago}
{440}{}{Clubber Lang}
{441}{}{Duchessa}
{442}{}{Bulldozer}
{443}{}{Adornare}
{444}{}{Luke Mano di Ferro}
{445}{}{Faith}
{446}{}{Dottor Pugno}
{447}{}{La Suora Volante}
{448}{}{Balboa}
{449}{}{Floyd Ray Willis}
{450}{}{Calamity Jane}
{451}{}{Kobra}
{452}{}{Omicidio Sanguinario}
{453}{}{Boia}
{454}{}{Treno Merci}
{455}{}{Super Volpe}
{456}{}{Jim New Reno}
{457}{}{Il Tritaossa}
{458}{}{Rico}
{459}{}{Mano di Martello}
{460}{}{La Vedovaia}
{461}{}{Ufficiale Giudiziario}
{462}{}{Butch Coolidge}
{463}{}{Gatto Randagio}
{464}{}{Bad Mojo}
{465}{made_man_name}{Tank}
{466}{}{Il Picchiatore}
{467}{}{Mynx}
{468}{}{Scorpione}
{469}{}{Pugno Facile}
{470}{}{Cheetah}
{471}{}{Il Verdetto}
{472}{}{Giudice e Giuria}
{473}{}{Piledriver}
{474}{}{Athena}
{475}{}{Cane Pazzo}
{476}{}{}
{496}{}{Grande Stu}
{497}{}{Miami}
{498}{}{X}
{499}{}{Il tuo nome}
{500}{}{}
{501}{}{Rodd Rokks}
{502}{}{Randy Mercury}
{503}{}{Dirk Diggler}
{504}{}{Dick Mountenjoy}
{505}{}{Ronny Rection}
{506}{}{Phil Chambers}
{507}{}{Rod Sweat}
{508}{}{Jack Shooter}
{509}{}{Kurt Loader}
{510}{}{Rick Dripps}
{511}{}{Dick Seamen}
{512}{}{"Il Martello Polacco"}
{513}{}{Ron Jeremy}
{514}{}{Gallo Spaccone}
{515}{}{Vinnie LaJoya}
{516}{}{Sir Lance-a-lot}
{517}{}{Dick Smothers}
{518}{}{Jeremy Bolt}
{519}{}{Mr. Pink}
{520}{}{Ricky Rachtman}
{521}{}{Cuthbert}
{522}{}{Dave Manolesta}
{523}{}{Harry Canyon}
{524}{}{Richie Cunning Linguist}
{525}{}{Bret Bulge}
{526}{}{El Douche}
{527}{}{Johnson Long}
{528}{}{Ebineezer Viti}
{529}{}{Buck Fitch}
{530}{}{Arnold Swollenmember}
{531}{}{Doug Holes}
{532}{}{Freddy Barkwood}
{533}{}{}
{534}{}{}
{535}{}{}
{536}{}{}
{537}{}{}
{538}{}{}
{539}{}{}
{540}{}{}
{541}{}{}
{542}{}{}
{543}{}{}
{544}{}{}
{545}{}{}
{546}{}{}
{547}{}{}
{548}{}{}
{549}{}{}
{550}{}{}
{551}{}{Vixxxen}
{552}{}{Mable Syrup}
{553}{}{Amber Waves}
{554}{}{Lucy Loose}
{555}{}{Amy Ample}
{556}{}{Molly Mounds}
{557}{}{Honey Tits}
{558}{}{Patty Pitt}
{559}{}{Ophelia Balls}
{560}{}{Thelma Schoonmaker}
{561}{}{Alotta Fagina}
{562}{}{Carrie C}
{563}{}{Georgia O'Queef}
{564}{}{Jill Jacks}
{565}{}{Courtney Coxsleeve}
{566}{}{Maria Swallo}
{567}{}{Lady J}
{568}{}{Glenda Glenn}
{569}{}{Queen Elizabeth}
{570}{}{Jenna Jammison}
{571}{}{Bunny LaJoya}
{572}{}{Madame Butterfly}
{573}{}{Jenny X}
{574}{}{Dolce Jane}
{575}{}{Cara Nikki}
{576}{}{Sharonna}
{577}{}{Suzy Q}
{578}{}{Corvega Sally}
{579}{}{Pokeahotass}
{580}{}{Dominatrish}
{581}{}{Principessa X}
{582}{}{Carlotta}
{583}{}{Mary la Baciona}
{584}{}{Vino d'Aprile}
{585}{}{Ruby Red}
{586}{}{Christie Chipps}
{587}{}{Lisa Lix}
{588}{}{Oppio}
{589}{}{Gatto Randagio}
{590}{}{Lady Chatterfly}
{591}{}{La Postina}
{592}{}{Signora Holmes}
{593}{}{Debbie l'Ardita}
{594}{}{Jessica Long}
{595}{}{Mynx}
{596}{}{Sascha}
{597}{}{Valerie Vixen}
{598}{}{Ruth la Spietata}
{599}{}{}
{700}{}{Mal Fisto}
{701}{}{Tommy Pistola}
{702}{}{"Acciaio" Mark Torrance}
{703}{}{Xander "la Cosa Sicura" Holyland}
{704}{}{Ragno}
{705}{}{Magro}
{706}{}{Dolce Jones}
{707}{}{Il Roche}
{708}{}{Tito}
{709}{}{Rudy}
{710}{}{Grande George}
{711}{}{Gooch}
{712}{}{Fat Johnny}
{713}{}{Nicki}
{714}{}{LaMotta}
{715}{}{Ivan}
{716}{}{Joe di Vetro}
{717}{}{Drago}
{718}{}{Tommy Pistola}
{719}{}{Apollo}
{750}{}{Joqq}
{751}{}{Pete McKneely}
{752}{}{Evan Holyfeld}
{753}{}{Il Masticatore}
{1000}{}{Jules ti conduce in un vecchio quartiere alla periferia di New Reno. Non credi che saresti riuscito a trovare questo luogo da solo. Appena arrivati, Jules sparisce.}
{1100}{}{Le tracce ti conducono in un vecchio quartiere alla periferia di New Reno.}
{1200}{}{Scopri una piccola scatola di metallo. Non l'avresti mai trovata se tu non l'avessi cercata.}
{1300}{}{Cody ti conduce in un vecchio quartiere alla periferia di New Reno, poi se ne corre via per la strada dalla quale siete arrivati. Non credi che saresti riuscito a trovare questo luogo da solo.}
{1400}{}{Hai sconfitto il tuo primo avversario.}
{1401}{}{Hai sconfitto il tuo secondo avversario.}
{1402}{}{Hai sconfitto il tuo terzo avversario.}
{1403}{}{Hai sconfitto il Masticatore!}
{1404}{}{Sei diventato il Campione dei Pesi Massimi di New Reno.}
{1405}{}{Hai sconfitto il tuo ultimo avversario!}
{1500}{}{Hai convinto la signora Wright a distruggere la distilleria.}
{1550}{}{Hai assistito alla transazione segreta.}
{1600}{}{Nel mezzo della battaglia, il Masticatore ti strappa un orecchio a morsi.}
{1700}{}{Infuriato, strappi a morsi un orecchio del Masticatore.}
