{100}{}{}
{101}{}{}
{110}{}{I tuoi piedi prudono terribilmente.}
{120}{}{Ti stanno venendo dei brutti calli su entrambi gli alluci.}
{130}{}{Le tue scarpe sono davvero strette; quei calli si stanno infiammando.}
{140}{}{Quei due brutti calli sembrano essersi trasformati in due dita aggiuntive. Ma almeno quel continuo e doloroso prurito se n'e' andato.}
{141}{}{Oh mio Dio, e' Bess!}
{150}{}{Guadagni }
{151}{}{ punti esperienza per aver recuperato il GECK.}
{400}{}{Non riesci a capire nulla dal testo, ma le illustrazioni sono piuttosto informative.}
{600}{}{Something doesn't feel quite right in your stomach.}
{601}{}{Senti una pressione intensa allo stomaco.}
{700}{}{Unisci i pezzi di carta strappati per ottenere un elenco di tre password.}
{900}{}{Something doesn't feel quite right in your stomach.}
{901}{}{Senti una pressione intensa allo stomaco.}
