{100}{}{Vedi il terminale di un computer.}
{101}{}{Vedi un terminale ad interfaccia vocale.}
{102}{}{E' un normale terminale di computer, modificato per riconoscere comandi vocali.}
{103}{}{Esamini il terminale, ma non riesci a trovare nulla di chiaramente rotto. Cosa fai?}
{104}{}{Gli dai un pugno in quel modo 'speciale'.}
{105}{}{Gli dai un calcio in quel posto 'speciale'.}
{106}{}{Esegui il programma diagnostico.}
{107}{}{Lo apri e guardi all'interno.}
{108}{}{Lo lasci stare.}
{109}{}{Osservi la console per un po' e decidi il posto migliore dove piazzare un pugno. Dopo avergli dato il tuo miglior pugno 'riparatutto', il monitor lampeggia un paio di volte e poi si stabilizza. Non succede nient'altro. Cosa fai?}
{110}{}{Gli dai un calcio in quel posto 'speciale'.}
{111}{}{Esegui il programma diagnostico.}
{112}{}{Lo apri e guardi all'interno.}
{113}{}{Lo lasci stare.}
{114}{}{Questo arcinoto metodo di riparazione produce due risultati. Primo: il monitor sembra andare in tilt per alcuni secondi e poi si stabilizza. Secondo: senti il rumore di qualcosa di metallico che si rompe e il pannello al quale hai dato un calcio cade sul pavimento. Cosa fai?}
{115}{}{Esegui il programma diagnostico.}
{116}{}{Il dannato aggeggio e' aperto. Tanto vale dare un'occhiata al suo interno.}
{117}{}{Lo lasci stare.}
{118}{}{Sei sicuro che il sistema sia fornito di una serie di routine diagnostiche. Tuttavia, gli input da tastiera sembra siano stati disabilitati. Il terminale accetta solamente comandi vocali. Cosa fai?}
{119}{}{L'unica cosa rimasta da fare e' guardare all'interno.}
{120}{}{Lo lasci stare.}
{121}{}{Osservando l'ammasso di cavi e circuiti stampati, scopri che il sistema e' stato deliberatamente sabotato. Uno dei circuiti stampati, il modulo di riconoscimento vocale e' irreparabilmente danneggiato e deve essere sostituito. Tutto quello che ti serve adesso e' un modulo di ricambio.}
{122}{}{Fatto.}
{123}{}{Fatto.}
{124}{}{Installi il modulo nel terminale. Il sistema e' riparato.}
{125}{}{Bisogna installare un modulo di riconoscimento vocale perche' il terminale possa diventare operativo.}
{126}{}{Fatto.}
{127}{}{Adesso il sistema funziona bene.}
{128}{}{Accesso alla registrazione delle telecamere di sicurezza in corso... Caricamento filmato olografico in corso...}
{129}{}{Tu sei l'ultimo, Gruthar. La macchia rappresentata dalla tua razza sara' presto spazzata via.}
{130}{}{Di' al tuo cosiddetto Presidente che brucera' all'inferno per questo.}
{131}{}{Come vuoi. Non sei mai stato nient'altro che un animale parlante.}
{132}{}{Potra' anche essere cosi', ma noi siamo stati creati in seguito ai vostri esperimenti. Voi ci avete dato la vita!}
{133}{}{Ed ora io ti daro' la morte.}
{134}{}{Prendete il suo cadavere. Il dottore voleva un esemplare.}
{135}{}{Il loro sangue scorrera' come il Nilo!}
{200}{}{Benvenuto, Abitante del Vault. Per tua comodita', questo terminale Vault-Tec e' stato modificato per rispondere ai comandi vocali. Pronuncia il tuo comando adesso.}
{201}{}{Oh, mi stai confondendo con qualcun altro. Vedi, io non sono l'Abitante del Vault, sono il Prescelto. }
{202}{}{Esegui diagnostica.}
{203}{}{Passa alla modalità di inserimento da tastiera.}
{204}{}{Accedi ai filmati di sicurezza.}
{205}{}{Esci.}
{206}{}{Urk?}
{210}{}{[Una spia lampeggia sul terminale mentre emette vari suoni di clic e ronzii. Dopo alcuni secondi, del testo
 appare sul monitor.] Spiacente, non ho capito il tuo comando. Ripeti il tuo comando, assicurandoti di parlare
 direttamente nel microfono in modo chiaro e preciso. Vault-Tec si scusa per l'inconveniente. Grazie.}
{211}{}{Esegui diagnostica.}
{212}{}{Passa alla modalità di inserimento da tastiera.}
{213}{}{Accedi ai filmati di sicurezza.}
{214}{}{Esci.}
{220}{}{Attendi mentre avvio i controlli diagnostici..Vault-Tec apprezza la tua pazienza... Grazie per aver atteso... Controlli
 diagnostici completati. Tutti i sistemi funzionano correttamente. Dopotutto, stai usando Vault-Tec. }
{221}{}{Indietro.}
{222}{}{Esci.}
{230}{}{Passaggio alla modalita' interfaccia manuale... modalita' interfaccia manuale avviata. Per comodita' degli altri, questo
 terminale tornera' automaticamente alla modalita' interfaccia vocale una volta effettuato il logout. Inserisci il comando.}
{231}{}{Cerca nel database qualsiasi informazione utile.}
{232}{}{Esci.}
{240}{}{Dopo una breve ricerca, scopri tre file che potrebbero valere un'occhiata: Guida alla Sopravvivenza dell'Abitante del Vault
 (Versione Abbreviata), Cronologia del Vault 13, e Diari del Supervisore.}
{241}{}{Accedi alla Guida alla Sopravvivenza dell'Abitante del Vault (Versione Abbreviata). }
{242}{}{Accedi alla Cronologia del Vault 13. }
{243}{}{Accedi ai Diari del Supervisore.}
{244}{}{Esci.}
{250}{}{Benvenuto nel Vault-13, l'ultimo di una serie di opere di difesa pubblica di Vault-Tec, il tuo appaltatore di fiducia
 quando si tratta dei migliori rifugi nucleari. Vault-Tec, l'Ultima Parola dell'America sulle Case.}
{251}{}{[AVANTI]}
{252}{}{La serie di rifugi di sopravvivenza Vault e' progettata dalle fondamenta per offrire la migliore possibilita' di una buona vita
 dopo l'armageddon nucleare. E' dovere di ogni cittadino americano imparare e usare le competenze necessarie per una vita confortevole nel Vault. Il posto migliore da cui cominciare e' con una descrizione della tua nuova casa.}
{253}{}{[AVANTI]}
{254}{}{STATISTICHE IMPORTANTI DEL VAULT 13
                                    Data inizio costruzione: Agosto 2063
                        Data fine costruzione: Marzo 2069
                             Budget iniziale: $400.000.000.000
                                Budget finale, con interessi: $645.000.000.000
                   Numero totale di occupanti: 1.000 (a piena capacita')
                 Durata totale: 10 anni (a piena capacita')
                            Numero di alloggi: 100 (turni di riposo necessari a capacita' massima)}
{255}{}{[AVANTI]}
{256}{}{Per aiutare gli Abitanti del Vault a registrare informazioni (e le informazioni sono estremamente preziose, anzi, potrebbero essere l'arma piu'
 preziosa che abbiamo contro la fine della civilta', quindi presta attenzione!) Vault-Tec ha selezionato il RobCo Pip-Boy 2000 della RobCo Industries come Elaboratore di Informazioni Personali di riferimento per i suoi Abitanti del Vault.}
{257}{}{[AVANTI]}
{258}{}{Il RobCo Pip-Boy 2000 e' un pratico dispositivo che indossi al polso. E' piccolo, specialmente per gli standard odierni, e conservera' una buona quantita' di informazioni per te. E con una grafica moderna super-deluxe
 per di piu'! Consulta il manuale del tuo Pip-Boy per ulteriori informazioni.}
{259}{}{[AVANTI]}
{260}{}{La chiave per un reinserimento riuscito della civilta' dopo una guerra nucleare su vasta scala e' la gente. Qui a Vault-Tec, stiamo lavorando per assicurarci che i tuoi simili (uomini e donne) siano all'altezza del compito di riportare l'America dalla morte.}
{261}{}{[AVANTI]}
{262}{}{Crediamo che un atteggiamento positivo sia uno dei migliori strumenti a nostra disposizione. Se dovessi incontrare degli Abitanti del Vault che mostrano un atteggiamento meno che positivo, sei incoraggiato a segnalarli al Supervisore del tuo Vault. Ricorda, una volta sigillate le porte, la parola del Supervisore e' legge.}
{263}{}{[AVANTI]}
{264}{}{Il Vault-13 viene fornito con gli ultimi equipaggiamenti di sopravvivenza. Gli oggetti nei tuoi contenitori di stoccaggio basteranno a 1.000 persone per 10 anni in un ambiente confortevole e moderno. Quando sara' il momento di lasciare il Vault e tornare a ricostruire l'America, i tuoi amici di Vault-Tec ti hanno fornito tutto cio' di cui avrai bisogno.}
{265}{}{[AVANTI]}
{266}{}{Grazie per aver preso il tempo di leggere la Guida alla Sopravvivenza dell'Abitante del Vault (Versione Abbreviata). Noi di Vault-Tec siamo certi che amerai la tua nuova abitazione sotterranea.}
{267}{}{Accedi alla Cronologia del Vault 13. }
{268}{}{Accedi ai Diari del Supervisore.}
{269}{}{Esci.}
{270}{}{Mentre leggi l'inizio della cronologia, trovi interessante che non venga fornita alcuna ragione per cui il Vault non si e' aperto 10 anni dopo la Grande Guerra, come era stato originariamente progettato. }
{271}{}{[AVANTI]}
{272}{}{Scorrendo avanti, non trovi nulla di interessante fino all'anno 2161, quando l'unico chip dell'acqua funzionante del Vault si rompe. Senti un moto di orgoglio mentre leggi di tuo nonno selezionato per l'importante compito di lasciare il Vault e perlustrare il wasteland alla ricerca di un chip dell'acqua sostitutivo. Tuttavia, e' un po' strano vedere la leggenda piu' venerata della tua tribu' raccontata in un semplice formato a punti elenco.}
{273}{}{[AVANTI]}
{274}{}{Continuando lungo la cronologia, leggi del successo di tuo nonno e del successivo esilio, e di come diversi altri abitanti del Vault abbiano scelto di unirsi a lui piuttosto che restare nella relativa sicurezza del Vault. Scopri anche che il Supervisore fu infine processato e giustiziato dagli abitanti rimasti.}
{275}{}{[AVANTI]}
{276}{}{L'ultima voce della cronologia e' datata maggio 2242. Sembra che, per la prima volta, il Vault 13 abbia ricevuto un segnale di "via libera" da una fonte sconosciuta. Dopo un po' di dibattito, gli abitanti del Vault decisero di aprire le porte e vedere cosa li aspettava nel mondo esterno. Non c'e' nessuna registrazione di cosa sia successo loro dopo.}
{277}{}{Accedi alla Guida alla Sopravvivenza dell'Abitante del Vault (Versione Abbreviata). }
{278}{}{Accedi ai Diari del Supervisore.}
{279}{}{Esci.}
{280}{}{Autorizzazione richiesta. Inserisci la password. }
{281}{}{[INDIETRO]}
{282}{}{[Prova a indovinare la password]}
{283}{}{[Tenta di hackerarlo]}
{284}{}{Esci.}
{290}{}{Password errata. Inserire la password.}
{291}{}{[INDIETRO]}
{292}{}{[Prova a indovinare la password]}
{293}{}{[Tenta di hackerarlo]}
{294}{}{Esci.}
{300}{}{Errata. L'accesso a questi file e' ora bloccato. Vault-Tec si scusa per l'inconveniente.}
{301}{}{[INDIETRO]}
{302}{}{[Tenta di hackerarlo]}
{303}{}{Esci.}
{310}{}{[Provi tutto quello che ti viene in mente, ma non riesci ad ottenere l'accesso. Con un sospiro di resa, torni al menu principale.]}
{311}{}{Esegui diagnostica.}
{312}{}{Passa alla modalità di inserimento da tastiera.}
{313}{}{Accedi ai filmati di sicurezza.}
{314}{}{Esci.}
{320}{}{Password corretta. Tutte le voci tranne una sono state rimosse dal sistema. L'ultima voce dei Diari del Supervisore e' ancora accessibile.}
{321}{}{[Dopo diversi lunghi minuti a lavorare la tua magia tecnica, riesci ad hackerare i Diari del Supervisore. Tuttavia, sembra che ogni voce tranne l'ultima sia stata cancellata.]}
{322}{}{Bene, vediamo cosa aveva da dire questo Supervisore. [Leggi il diario.] }
{323}{}{Eh, come vuoi. [Disconnessione]}
{330}{}{E' questo. Considera queste le mie ultime parole, poiche' dubito di vivere abbastanza da scrivere un'altra voce. Oh no, la gente del Vault ha parlato, e ha reso abbastanza chiaro che vuole la mia testa. Sapevo che questo giorno sarebbe arrivato, da quando LUI e' riuscito ad agitarli facendo l'impossibile. Certo, ha salvato le nostre vite, ma ha anche rovinato tutto.}
{331}{}{[AVANTI]}
{332}{}{Sia noto che ho ricavato poco piacere nell'esiliare il nostro "grande eroe", ma non avevo scelta in merito. Le sue avventure nel mondo esterno lo avevano cambiato troppo. Era una minaccia troppo grande per il progetto. Se lo avessi lasciato restare tra noi, avrebbe potuto scoprire la vera natura dei Vault e mettere a rischio l'esperimento. Anche se non l'avesse fatto, avrebbe almeno ispirato gli altri ad avventurarsi fuori, il che sarebbe stato altrettanto grave.}
{333}{}{[AVANTI]}
{334}{}{Doveva semplicemente andarsene. Non c'era altra opzione. Ma anche questo non e' bastato. No, temo che il danno fosse gia' stato fatto. Ho permesso ai suoi sostenitori piu' testardi di seguirlo in esilio, e poi ho cercato di ristabilire il mio controllo su coloro che rimanevano. Ma non e' servito a nulla -- ero gia' stato demonizzato. Cosi' sia. L'unica cosa di cui sono colpevole e' una vita intera a portare avanti le richieste della nostra Grande Nazione.}
{335}{}{[AVANTI]}
{336}{}{Il mio unico rimpianto e' che il Vault 13 probabilmente non completera' l'esperimento sociale. Una volta che saro' stato eliminato, sono certo che gli altri lasceranno il Vault. Non subito, ovviamente -- ho instillato in loro troppa paura del mondo esterno. Ma alla fine, sono destinati a superare quella paura. Ho pochissima fiducia che il Vault 13 rimanga chiuso fino al 2277, come prescrive l'esperimento.}
{337}{}{[AVANTI]}
{338}{}{Temo di aver mancato al mio dovere di Supervisore. Posso solo sperare che il resto dei Vault pubblici coinvolti nel Programma di Preservazione Sociale abbiano avuto piu' successo. Ai miei superiori, che sono certo leggeranno un giorno questo: perdonatemi. E Dio benedica l'America.}
{339}{}{Cerca altri file che contengano informazioni sul "Programma di Preservazione Sociale".}
{340}{}{Esci.}
{350}{}{Dopo ore a setacciare gli archivi del computer, non riesci a trovare nient'altro che menzioni il Programma di Preservazione Sociale. Mentre rinunci alla ricerca, giuri di non sprecare mai piu' cosi' tanto tempo a fissare uno schermo di computer.}
{351}{}{Esci.}
{360}{}{Dopo ore a setacciare gli archivi del computer, riesci a localizzare alcuni documenti nascosti riguardanti il Programma di Preservazione Sociale. Mentre li leggi, scopri una verita' piuttosto inquietante sui Vault: non erano mai stati concepiti per salvare la popolazione degli Stati Uniti.}
{361}{}{[AVANTI]}
{362}{}{Incredibilmente, tutti e 122 i Vault pubblici di Vault-Tec facevano parte di un grande esperimento sociale orchestrato dal governo statunitense. Solo 17 di quei Vault, denominati "Vault di controllo", erano progettati per funzionare correttamente (sembra che il Vault 8 fosse uno dei pochi fortunati). Il resto era destinato ad avere vari difetti critici, in modo che il governo potesse studiare gli occupanti preselezionati e vedere come reagiscono alle pressioni delle loro situazioni e quanto bene riescono a ricolonizzare una volta aperti i loro Vault.}
{363}{}{[AVANTI]}
{364}{}{Sembra che il ruolo del Vault 13 nell'esperimento fosse di restare chiuso per 200 anni per testare gli effetti dell'isolamento prolungato. A quanto pare, la rottura del chip dell'acqua non era prevista, e ha costretto il Supervisore ad improvvisare selezionando tuo nonno per uscire a procurarsi un nuovo chip. Dopo ulteriori ricerche, riesci a trovare descrizioni di alcuni altri esperimenti dei Vault.}
{365}{}{[AVANTI]}
{366}{}{La porta del Vault 12 era progettata per non chiudersi mai, in modo che gli stronzi dietro questo esperimento potessero "studiare gli effetti delle radiazioni sulla popolazione selezionata". Se ricordi correttamente la leggenda, il Vault 12 era situato sotto la citta' piena di ghoul di Necropolis, dove l'Abitante del Vault trovo' infine il chip dell'acqua. Sembra abbastanza probabile che i ghoul fossero il risultato di questo esperimento.}
{367}{}{[AVANTI]}
{368}{}{Il Vault 15, un'altra location chiave nella missione dell'Abitante del Vault, doveva essere popolato da persone con "ideologie radicalmente diverse" che sarebbero state sigillate nel Vault insieme per 50 anni. Il Vault 27 doveva essere deliberatamente sovraffollato con 2.000 persone -- il doppio della capacita' massima. Non dev'essere stato bello. Il Vault 29 doveva essere popolato solo da chi aveva meno di sedici anni, con i genitori "deliberatamente reindirizzati ad altri Vault".}
{369}{}{[AVANTI]}
{370}{}{L'esperimento del Vault 34 prevedeva un arsenale sovraccarico di armi e munizioni, e, ovviamente, privo di serratura. Che piacere. Il Vault 36 soffriva di estrusori alimentari progettati per produrre solo "una brodaglia acquosa e misera", mentre il Vault 42 era dotato solo di illuminazione fioca -- non erano fornite lampadine da piu' di 40 watt.}
{371}{}{[AVANTI]}
{372}{}{Le attrezzature del Vault 53 erano progettate per guastarsi ogni pochi mesi. Sebbene riparabili, i guasti continui erano destinati a testare lo stress degli abitanti. Ti chiedi quanti meccanici e tecnici esperti abbia prodotto quel Vault. Il Vault 55 avrebbe tutte le sue cassette di intrattenimento rimosse, mentre il Vault 56 avrebbe tutte le sue cassette di intrattenimento rimosse, ad eccezione di una con un attore comico particolarmente scarso.}
{373}{}{[AVANTI]}
{374}{}{Il Vault 68 doveva essere occupato da 999 maschi e una sola femmina. Puoi solo immaginare gli orrori che vi hanno avuto luogo... Il Vault 69, d'altro canto, doveva essere occupato da 999 femmine e un solo maschio... interessante. Gli estrusori di tute del Vault 70 erano progettati per guastarsi dopo 6 mesi. E infine, il Vault 106 era progettato in modo che 10 giorni dopo essere stato sigillato, avrebbe cominciato a "rilasciare droghe psicoattive nel sistema di filtrazione dell'aria".}
{375}{}{Esci.}
{500}{}{Scopri gli Esperimenti dei Vault e i ruoli dei vari Vault.}
{510}{}{Apprendi la storia del Vault 13 e il ruolo del Supervisore negli Esperimenti dei Vault.}
{520}{}{Mi dispiace, non ho capito.}
{521}{}{Esci.}
{2541}{}{Spessore porta: 4 iarde, acciaio
                                       Copertura terrestre: 3.200.000 tonnellate di terreno, a 200 piedi
           Sistema di controllo computer: Calcolatore
                          Alimentazione primaria: Geo-termica
                                Alimentazione secondaria: Sistemi di backup a energia nucleare General Atomics
                                                         Requisiti energetici: 3,98mkw/giorno
                                 Scorte: Equipaggiamento da costruzione completo, fattorie idro-agricole, sistema di purificazione dell'acqua da fiume sotterraneo,
 armamento difensivo per equipaggiare 10 uomini, file di comunicazione, sociali e di intrattenimento (per tutta la durata)}
