{100}{}{Vedi un computer funzionante.}
{101}{}{Questo computer sembra controllare l’ordigno nucleare qui vicino.}
{200}{}{Benvenuto in PoseidoNet. Questo terminale controlla le operazioni della Bomba a Fusione MK-17. Stato attuale della bomba: Disattivata.}
{201}{}{Attiva bomba.}
{202}{}{Esci.}
{210}{}{L'attivazione della bomba richiede due forme di sovrascrittura di sicurezza. Sovrascrittura 1: Tesserino Rosso del Reattore, fornito solo ai
 massimi funzionari della Ricerca statunitense. Sovrascrittura 2: Chiave di Sicurezza Presidenziale, fornita solo al Presidente degli Stati Uniti.}
{220}{}{Sembra che non abbia tutte le tessere magnetiche.}
{221}{}{Inserisci la Tessera Rossa del Reattore.}
{222}{}{Tesserino accettato. Sovrascrittura di sicurezza 1 completata. Sicurezza di livello 2 ancora attiva.}
{223}{}{Inserisci il Pass di Sicurezza Presidenziale.}
{224}{}{Sembra che mi manchi ancora una tessera magnetica.}
{225}{}{Tesserino accettato. Sovrascrittura di sicurezza 2 completata.}
{226}{}{Attiva bomba.}
{227}{}{Esci.}
{228}{}{La bomba e' stata attivata e detonera' in T-meno 5 min. Errore nella procedura di conto alla rovescia. Conto alla rovescia riavviato a
 T-meno 5 secondi. Assicurati di essere ad almeno 80 miglia dall'area dell'esplosione. Buona giornata.}
{229}{}{Madre di Dio…}
