{100}{}{You see a functional computer.}
{101}{}{This computer appears to control the nuclear bombing sitting nearby.}
{200}{}{Benvenuto in PoseidoNet. Questo terminale controlla le operazioni della Bomba a Fusione MK-17. Stato attuale della bomba: Disattivata.}
{201}{}{Activate bomb.}
{202}{}{Esci.}
{210}{}{L'attivazione della bomba richiede due forme di sovrascrittura di sicurezza. Sovrascrittura 1: Tesserino Rosso del Reattore, fornito solo ai
 massimi funzionari della Ricerca statunitense. Sovrascrittura 2: Chiave di Sicurezza Presidenziale, fornita solo al Presidente degli Stati Uniti.}
{220}{}{Looks like I don't have all of these keycards.}
{221}{}{Insert Red Reactor Keycard.}
{222}{}{Tesserino accettato. Sovrascrittura di sicurezza 1 completata. Sicurezza di livello 2 ancora attiva.}
{223}{}{Insert Presidential Security Passkey.}
{224}{}{Looks like I am still missing a keycard.}
{225}{}{Tesserino accettato. Sovrascrittura di sicurezza 2 completata.}
{226}{}{Activate bomb.}
{227}{}{Esci.}
{228}{}{La bomba e' stata attivata e detonera' in T-meno 5 min. Errore nella procedura di conto alla rovescia. Conto alla rovescia riavviato a
 T-meno 5 secondi. Assicurati di essere ad almeno 80 miglia dall'area dell'esplosione. Buona giornata.}
{229}{}{Mother of God...}
