{100}{}{Vedi un vecchio tizio dall'aspetto amichevole.}
{101}{}{E' Doc Jubilee.}
{102}{}{E' un vecchio con una candida barba e uno sguardo piuttosto assente.}
{103}{}{Sono Doc Jubilee. Cosa c'e' che non va, giovanotto?}
{104}{}{Cosa c'e' che non va, giovanotto?}
{105}{}{Me ferito.}
{106}{}{Ho bisogno di un dottore.}
{107}{}{Non potresti semplicemente prendere delle pillole o qualcosa del genere invece di disturbarmi per queste sciocchezze?}
{108}{}{Diavolo, sanguini appena!}
{109}{}{Non so. Non penso di poterla salvare. Forse dovremo amputare questa gamba.}
{110}{}{Stai scherzando.}
{111}{}{Ah-ah.}
{112}{}{Ecco a te, figliuolo.}
{113}{}{Ancora.}
{114}{}{Grazie, Doc. Forse potresti rispondere a qualche domanda.}
{115}{}{Arrivederci.}
{116}{}{Ti costera' 50$.}
{117}{}{Basta che mi curi.}
{118}{}{Me ne vado.}
{119}{}{Tu fare stare me meglio.}
{120}{}{Me va ora.}
{121}{}{No. Non scherzo mai. E' meglio amputare quella gamba prima che vada in gangrena.}
{122}{}{Puoi scordarti di amputarmi qualcosa, capito?}
{123}{}{Questo e' troppo, me ne vado.}
{124}{}{Beh, se poi ti va in gangrena, non venire a dare la colpa a me.}
{125}{}{Non gestisco un istituto di carita'. Dovrai darmi dei soldi prima che io faccia qualcosa.}
{126}{}{Allora, cosa posso fare per te?}
{127}{}{Spara.}
{128}{}{Vault 13?}
{129}{}{Sai dove potrei trovare il Vault 13?}
{130}{}{Ho sentito dire da qualcuno che il signor Westin non sta molto bene. E' vero? Non vorrei che gli capitasse qualcosa. Mi deve dei soldi.}
{131}{}{C'e' questo tizio, Saltbeef, che dice che gli hai rubato una mappa. Cos'e' 'sta storia?}
{132}{}{Sto cercando lavoro. Sai dove potrei trovarne uno?}
{133}{}{Doc, tu non sai nulla a proposito di un gruppo che combatte i malvagi schiavisti, vero?}
{134}{}{Beh, non dovresti preoccuparti, ragazzo. Se non stressa il suo fisico, probabilmente ci sotterrera' tutti. Naturalmente deve sottoporsi a visite periodiche e prendere sempre la sua medicina.}
{135}{}{Buono a sapersi. C'e' un'altra cosa che mi stavo chiedendo...}
{136}{}{Grazie, Doc.}
{137}{}{Quel vecchio ubriacone! L'unica cosa che gli abbia mai preso e' stato il mio dipinto di "Velvet Elvii" - l'ho preso come pagamento.}
{138}{}{Un Velvet Elvii? Posso vederlo?}
{139}{}{Non e' esattamente una mappa, eh? Beh, lascia che ti chieda qualcos'altro.}
{140}{}{Bene, adesso devo andare.}
{141}{}{Non ne sento parlare dal giorno in cui il vecchio Saltbeef e' stato portato qui. Colpo di sole. Bruciato dalle febbri per tre giorni, continuava a vaneggiare dicendo di aver trovato il Vault 13, il suo tesoro.}
{142}{}{Tesoro?}
{143}{}{E allora... dov'e'?}
{144}{}{Dove vault?}
{145}{}{Non saprei dirtelo. Saltbeef ha sempre detto di avere una mappa, ma nessuno l'ha mai vista.}
{146}{}{Saltbeef?}
{147}{}{Un'altra cosa...}
{148}{}{Beh, e' piu' di quanto non avessi prima.}
{149}{}{Il colpo grosso. Saltbeef e' un vecchio cercatore d'uranio - piu' precisamente, un ubriacone. Negli ultimi tempi vive nella proprieta' di Westin.}
{150}{}{Un'altra domanda...}
{151}{}{Grazie per la storia.}
{152}{}{Beh, speravo proprio di ricavarci dei soldi. Te lo lascero' per }
{153}{}{Magari piu' tardi. Un'altra domanda...}
{154}{}{Magari un'altra volta. Devo andare.}
{155}{}{Saltbeef e' un vecchio cercatore d'uranio. Negli ultimi tempi vive nella proprieta' di Westin.}
{156}{}{Un'altra domanda...}
{157}{}{Grazie per la storia.}
{158}{}{Faresti meglio ad andare a parlare con il Presidente Tandi. Ho sentito dire che sta cercando una persona speciale.}
{159}{}{Un'altra domanda...}
{160}{}{Grazie.}
{161}{}{Forse... Esiste un gruppo che ha come obiettivo la scomparsa della schiavitu' e - beh, di praticamente tutte le altre cattiverie. Puoi trovarli in quel grande negozio, che lavorano su qualche automobile.}
{162}{}{Un'altra domanda...}
{163}{}{Grazie.}
{164}{}{Ehi, giu' le mani da li', ragazzaccio!}
{165}{}{Fa' attenzione! Basta poco di quello per farti male.}
{166}{}{Mettilo a posto! Potresti farti male sul serio con quella roba.}
{167}{}{Quelle medicine sono per Mr. Westin, non per te. Mettile giu'.}
{168}{}{Sta' lontano da li'. Devo stare attento. Non vorrei che Mr. Westin assumesse la medicina sbagliata.}
{169}{}{Occhio! Ho appena preparato la medicina per Mr. Westin.}
{170}{}{Sono Doc Jubilee. Cosa c'e' che non va, signorina?}
{171}{}{Cosa c'e' che non va, signorina?}
{172}{}{Ecco a te, signorina.}
{173}{}{Beh, non dovresti preoccuparti, signorina. Se non stressa il suo fisico, probabilmente ci sotterrera' tutti. Naturalmente deve sottoporsi a visite periodiche e prendere sempre la sua medicina.}
{174}{}{Certo. Ecco i }
{175}{}{Grazie; ho cercato di farmi dare i soldi da Saltbeef, ma quel vagabondo non ne ha mai avuti.}
{176}{}{.}
{200}{}{Whoa there, }
{201}{}{figliolo! }
{202}{}{signorina! }
{203}{}{Non puoi toccare quella roba! Ho appena misurato la dose del signor Westin e non vorremmo mica che prendesse le medicine sbagliate. Che diavolo credi di fare?}
{204}{}{Stavo solo cercando di dare un'occhiata a quelle pillole che hai sullo scaffale la'.}
{205}{}{Oh, don't mind me. I was just window shopping.}
{206}{}{Scusa. Ho sempre avuto questa irresistibile compulsione a frugare tra le cose degli altri che non sono mai riuscito a scrollarmi di dosso.}
{207}{}{Onestamente? Non mi aspettavo che fossi cosi' attento. Immagino che dovro' improvvisare.}
{210}{}{Davvero? (Il Dott. Jubilee ti guarda con freddezza.) Direi che sei un po' troppo giovane per soffrire di un cuore malandato.}
{211}{}{E avresti ragione. Chiedo per il mio amico Cassidy. Un tipo piu' anziano. Ha un cuore malato, e viaggiare nel wasteland sta diventando abbastanza duro per lui.}
{212}{}{E vorrei che avessi ragione. L'ho preso da mio padre. O almeno cosi' mi dicono.}
{213}{}{Oh, niente del genere. Sono solo esageratamente curioso, immagino.}
{220}{}{Be', non puoi. Questo e' uno studio privato, non una farmacia. Potresti provare da Duppo, un po' a nord di qui.}
{221}{}{Sounds like just what I'm looking for. Bye.}
{222}{}{Ci daro' un'occhiata. Nel frattempo, pero', ti dispiace se ti faccio qualche domanda?}
{223}{}{No, credo di essere venuto nel posto giusto. Vedo che stai facendo un buon lavoro qui. Pensavo di poter fare una donazione.}
{230}{}{(Il dottore sbatte le palpebre. Le sbatte di nuovo.) Dovresti probabilmente parlarne con qualcuno. Purtroppo
 non sono il tipo giusto di dottore. Tutto quello che devi sapere di quello scaffale e' che se mescoli o contamini una qualsiasi di quelle
 ricette, qualche povero disgraziato finira' in un mare di guai, se e' ancora in questo mondo. Meglio tenerti le mani per te.}
{231}{}{Certo, dottore. Ma, uh, senti-- ho un amico che avrebbe davvero bisogno di alcune di quelle pillole per il cuore che hai la'.
 Pensi di essere disposto a vendermene un po'?}
{240}{}{Awww, }
{241}{}{son, }
{242}{}{signorina, }
{243}{}{Vorrei poterti aiutare, ma non sto prendendo nuovi pazienti adesso. Il Consiglio mi ha assunto a contratto. Non posso venderti pillole neanche-- la gente del Consigliere Westin dovrebbe venire a ritirare quelle tra }
{244}{}{ days, }
{245}{}{ giorno, }
{246}{}{e non avro' proprio il tempo di preparare un altro lotto prima di allora.}
{247}{}{Capisco, dottore. Forse trovero' un farmacista decente da qualche altra parte. Se non e' troppo chiedere, pero', hai qualche consiglio da darmi sull'argomento? Una medicina del genere non si trova spesso.}
{248}{}{Queste sono le regole del gioco, immagino. Comunque, dovrei stare bene. Ho imparato *un sacco* di cardamomagia dai vecchi fumetti. Ridurre i chem pesanti a due volte al giorno AL MASSIMO, assicurarsi di fare esercizio in brevi scatti intensi cosi' il cuore non ha tempo di fare i capricci, roba del genere.}
{250}{}{Mi dispiace per te, amico, ma temo che quelle pillole siano per il Consigliere Westin, e non sto prendendo nuovi pazienti adesso quindi non potrei scriverti una ricetta. Ora per favore, non andare a toccare quello scaffale. Se quelle ricette si mescolano, qualcuno potrebbe finire molto male.}
{260}{}{Let's be clear here, }
{261}{}{mister. }
{262}{}{missy. }
{263}{}{What exactly do you mean by "donation?"}
{264}{}{Un contributo di beneficenza, a sostegno del tuo servizio al pubblico, diciamo... 150 dollari? Puoi contarli nel retro. Ci vorra' solo un minuto, giusto?}
{265}{}{Uh, in realta', credo che dovrei consultare il mio commercialista prima di fare qualcosa di avventato. A dopo, dottore.}
{270}{}{Non posso, temo. Quelle sono per il Consigliere Westin. La sua gente dovrebbe passare a ritirarle tra }
{271}{}{ days, }
{272}{}{ giorno, }
{273}{}{e non avro' il tempo di preparare un altro lotto prima di allora. Sono sicuro che puoi trovare un farmacista con meno lavoro.}
{274}{}{I see. Well, thanks anyway.}
{280}{}{(Il Dott. Jubilee ti fissa a bocca aperta per un momento.) Aw, mi stai prendendo in giro, vero? Devi stare per forza facendo il furbetto. (Ti guarda di nuovo, scuote la testa, gonfia le guance.) Hooo, ragazzo. In ogni caso, non sarei un vero dottore se ti lasciassi andare senza almeno qualche consiglio.}
{281}{}{Vediamo... per cominciare, dovresti probabilmente smettere di fare... be', praticamente quasi tutto dovrebbe bastare. Niente alcol, niente fumo, niente carne rossa, NIENTE chem. Cerca di fare mezz'ora al giorno di esercizio LEGGERO. E prendila con calma. La vita non e' una gara, almeno non del tipo dove vuoi arrivare primo alla fine. A dire il vero, nessuno ascolta mai queste cose, ma almeno staro' piu' tranquillo stanotte.}
{282}{}{Piu' importante, devi trovare un chimico decente e dirgli che hai bisogno di una fornitura regolare di Triprosinil. Tri-pros-i-nil. La roba del wasteland non sara' elegante come quella che ho sullo scaffale la', ma chimicamente e' tutta uguale quando si viene al sodo. 30 milligrammi, due volte al giorno.}
{283}{}{Ora, devi assicurarti di bere molta acqua mentre prendi questa roba. E per l'amor di Dio, stai *piu' lontano che puoi* da quelle pillole per il cazzo come quelle che hanno su a New Reno, capito? Non vanno d'accordo. Se uno le prende insieme all'altra, il suo uccello non sara' di certo l'unica parte di lui a irrigidirsi quel giorno, se mi capisci.}
{284}{}{(Tra te e te) Hmm, potrebbe funzionare. Si'. Magari qualcosa come un composto inibitore PDE-5...}
{285}{}{Oh-- E se *vai* da uno di quei ciarlatani di Reno, potrebbe dirti che questa roba ti protegge il cuore da quasi qualsiasi veleno dello spacciatore che ti venga voglia di provare. Non ti mentiro'-- probabilmente c'e' un po' di verita' in quello. Non rende essere un drogato piu' glamour. Sei grande e vaccinato, quindi non ti faccio la morale, ma ecco come stanno le cose.}
{286}{}{Grazie mille, dottore. Non hai idea di quanto mi sei stato d'aiuto. Prenditi cura di te.}
{287}{}{Tri-pros-i-nil, no pil-lo-le-per-il-caz-zo. Heh heh. Lo terro' a mente. A presto, dottore.}
{290}{}{Pensi di avere a che fare con qualche cerusico losco da bartertown, }
{291}{}{son, }
{292}{}{ragazzina, }
{293}{}{e' cosi'? Non farlo. Sono un professionista medico dell'NCR formato e accreditato, e vale molto di piu' di quella manciatina di spiccioli.}
{294}{}{Mi scuso. Ovviamente, un professionista del tuo calibro merita una donazione di non meno di 250 dollari.}
{295}{}{(Abbassa la testa.) Senti, mi dispiace davvero. Non sono orgoglioso di me stesso, e normalmente non avrei mai tentato una cosa del genere, ma saro' onesto con te: avevo un disperato bisogno di quelle pillole.}
{296}{}{Scusa il disturbo. Credo che sia meglio andarmene prima di cacciarmi in un guaio ancora peggiore.}
{300}{}{(Il Dott. Jubilee comincia a diventare rosso.) Non credo che tu mi abbia sentito la prima volta,}
{301}{}{ ragazzo, }
{302}{}{ donna, }
{303}{}{quindi ascolta bene: sono un dottore dell'NCR. E' un dovere solenne, e viene con un giuramento solenne. Se mi chiedi ancora una volta di pisciare su quel giuramento, l'UNICA parte che finira' dalla finestra e' "prima di tutto, non nuocere." Capito?}
{304}{}{Va bene, al diavolo. Se sei cosi' bravo come sembri credere, forse riuscirai a rammendarti da solo dopo questo.}
{305}{}{Whoa, now. Didn't mean to step on any toes, doc. I'll just leave you be for awhile.}
{310}{}{Say, doc, I was wondering about those heart pills you've got up there on the shelf.}
{311}{}{Sei sicuro di non poter riconsiderare di vendermi alcune di quelle pillole?}
{320}{}{Spiacente, la gente del Consigliere Westin dovrebbe passare a ritirarle tra }
{321}{}{ days, }
{322}{}{ giorno, }
{323}{}{e sono semplicemente troppo occupato per preparare un altro lotto in tempo.}
{324}{}{(Borbotta tra se'.) Dove diavolo ho messo quelle pillole per il signor Westin. Il suo cuore non durera' a lungo senza di esse. (Alza lo sguardo.)
 Oh, scusa. Cosa posso fare per te oggi?}
{325}{}{Non ho potuto fare a meno di sentire quello che dicevi delle pillole per il cuore. Stavo proprio per chiederti di quella medicina.}
{330}{}{(Borbotta tra se'.) Non riesco a credere che il signor Westin sia morto. Non puo' essere colpa mia, ho misurato quelle pillole con precisione. (Alza lo sguardo) Oh, scusa. Cosa posso fare per te oggi?}
