{100}{}{Vedi una ragazza piuttosto carina, vestita con degli indumenti da combattimento.}
{101}{}{E' Elise.}
{102}{}{Da' l'idea di essere una ragazza decisa, come se fosse abituata a dare ordini e a vederli eseguiti.}
{103}{}{Cosa vuoi?}
{104}{}{Ancora tu?}
{105}{}{Mi manda Karl.}
{106}{}{Il dottor Jubilee ha detto che avrei fatto bene a parlare con te.}
{107}{}{Chi sei?}
{108}{}{Guh?}
{109}{}{Sto cercando un gruppo di persone. Persone che odiano lo schiavismo. Si fanno chiamare New California Ranger.}
{110}{}{Potete riparare la mia macchina?}
{111}{}{Uh - Credevo che questo posto fosse abbandonato.}
{112}{}{Davvero? Che cosa ti ha detto?}
{113}{}{Non molto. Ha detto che siete dei bravi ragazzi e che io potrei volermi unire a voi.}
{114}{}{Ha detto che pagate molto bene.}
{115}{}{Io sono Elise. Quello e' Gond. Siamo membri di un "gruppo" che cerca di fare del bene alla gente.}
{116}{}{Non sembrate un istituto di carita' o una chiesa.}
{117}{}{Sembra interessante. Fare del bene in che modo?}
{118}{}{Vorrei soltanto che mi riparaste la macchina.}
{119}{}{Esci di qui. Il saloon e' alla fine della Via Principale.}
{120}{}{Che odiano lo schiavismo, eh? Interessante. Che cosa faresti se trovassi questo gruppo?}
{121}{}{Chiederei di unirmi a loro.}
{122}{}{Gli spaccherei il culo.}
{123}{}{Nulla.}
{124}{}{Non sono affari tuoi. Adesso fuori.}
{125}{}{Abbiamo abbandonato il mondo dell'automobile. Abbiamo chiuso, per sempre. Addio.}
{126}{}{No. Addio.}
{127}{}{D'accordo; allora dimmi: cosa ne pensi degli schiavisti?}
{128}{}{Li odio. Disgustosa, ignobile feccia della terra.}
{129}{}{Se loro mi lasciano in pace, io lascio in pace loro.}
{130}{}{Alcuni dei miei migliori amici sono schiavisti.}
{131}{}{L'unica cosa che ti interessa sono i soldi?}
{132}{}{Certo che no. Io credo nella verita', nella giustizia e nella lotta a difesa degli oppressi.}
{133}{}{E' un inizio - a meno che qualcuno non mi indichi una causa migliore per la quale combattere.}
{134}{}{Esiste forse qualcos'altro?}
{135}{}{Non dire stronzate. Vedo bene che tipo di persona sei. Addio.}
{136}{}{Se non lo sai, allora sto sprecando il mio tempo. Addio.}
{137}{}{No, non siamo un'organizzazione religiosa. Ti dispiace se ti faccio una domanda?}
{138}{}{No, fa' pure.}
{139}{}{Non cosi' in fretta. Devi superare un esame prima di diventare un Ranger.}
{140}{}{Bene. Dimmi di cosa si tratta.}
{141}{}{Un esame? Ma cos'e' - siamo a scuola?}
{142}{}{C'e' uno schiavista, subito fuori citta'. Forse hai visto casa sua. Libera gli schiavi che sono li' e poi torna a parlare con me.}
{143}{}{Posso farlo.}
{144}{}{Assolutamente no. Non voglio fare casino da queste parti.}
{145}{}{Beh, e' il tuo giorno fortunato. }
{146}{}{Questo e' il tipo di comportamento che permette l'esistenza dell'atrocita' dello schiavismo . Mi dispiace, ma non c'e' posto per te nella nostra organizzazione.}
{147}{}{Ok.}
{148}{}{Allora, hai cambiato idea? Sei pronto a dimostrare il tuo valore?}
{149}{}{Bene.}
{150}{}{Che cosa volevi che facessi?}
{151}{}{Non dovresti fare qualcosa? Non tornare qui finche' non avrai portato a termine il lavoro.}
{152}{}{Mi e' gia' arrivata la notizia. Hai liberato gli schiavi. Un buon lavoro! Allora, sei pronto a diventare un Ranger?}
{153}{}{Si'.}
{154}{}{No.}
{155}{}{Mi hanno detto che tu sei quello che ha liberato tutti gli schiavi fuori dai cancelli della citta'. Quella che hai fatto e' stata una bella cosa e vorrei stringerti la mano.}
{156}{}{Grazie.}
{157}{}{Semplice. Noi crediamo che lo schiavismo sia sbagliato e faremo quello che dobbiamo per combatterlo. A NCR abbiamo un sacco di amici altolocati. Grazie a loro abbiamo gia' bandito la schiavitu' nel sud della Repubblica, ma adesso speriamo di diffondere il verbo anche a nord.}
{158}{}{Quello dei Ranger sembra un gruppo del quale sarei fiero di far parte. Consideratemi uno di voi.}
{159}{}{Interessante... Dovro' pensarci un po' su.}
{160}{}{Giuri di combattere lo schiavismo ogniqualvolta si presenti la possibilita' e di aiutare i tuoi compagni Ranger ogniqualvolta ne abbiano bisogno?}
{161}{}{Si'.}
{162}{}{No.}
{163}{}{Congratulazioni, adesso sei un Ranger.}
{164}{}{Benvenuto, compagno Ranger. Mi dispiace che al momento non ci sia molto da fare da queste parti per te. La maggior parte dei nostri uomini sono di pattuglia. Faro' girar voce che adesso sei uno di noi. Non vorrei che uno dei nostri ti sparasse addosso.}
{165}{}{Bene, siamo sempre in cerca di brave persone che appoggino la nostra causa. Se cambi idea, fammi una visita. Sei sicuro di non voler diventare subito un Ranger?}
{166}{}{Sono sicuro.}
{167}{}{Beh, adesso che me l'hai detto, credo proprio che mi piacerebbe diventare un Ranger.}
{168}{}{Capisco. Beh, io rappresento un gruppo chiamato New California Ranger. Qualcuno con un punto di vista come il tuo potrebbe essere adatto a diventare un membro. Sei interessato?}
{169}{}{Ottimo! Consideratemi uno di voi.}
{170}{}{Sembra interessante. Che cosa puoi dirmi a proposito dei Ranger?}
{171}{}{Capisco. Beh, grazie per averci fatto visita, ma non credo che abbiamo altro da dirci. Se cambi idea, torna qui.}
{172}{}{Ok.}
{173}{}{Se e' cosi', devo chiederti di sparire dalla mia vista. Subito!}
{174}{}{Ok.}
{175}{}{Uno schiavista! Vattene da qui prima che rimuova quel tuo tatuaggio con un proiettile!}
{176}{}{Bene.}
{177}{}{Provaci!}
{178}{}{Abbiamo agenti e simpatizzanti in alcune citta' su a nord. Stiamo diffondendo il verbo e colpendo gli schiavisti ovunque ne abbiamo la possibilita'.}
{179}{}{Bentornato. Hai cambiato idea e vuoi diventare uno di noi?}
{180}{}{Nulla.}
{181}{}{Quello non ti appartiene. Adesso vattene, oppure diventero' violenta.}
{182}{}{Non so cosa tu abbia fatto a Gond, ma la pagherai!}
{200}{}{Congratulazioni, ora sei un Ranger. E' tuo dovere giurato combattere la schiavitu' ovunque essa si manifesti. Prenditi cura di te, amico mio.}
{201}{}{Prima di andare, ho delle informazioni che potrebbero interessarti.}
{202}{}{D’accordo, sentiamo.}
{203}{}{Caso vuole che abbia le coordinate di uno dei piu' grandi campi di schiavisti di Metzger. E' molto a nordovest di qui, un paio di giorni di viaggio dal Den.}
{204}{}{Dici sul serio? I nostri Ranger del nord hanno cercato di rintracciare i campi di schiavisti di Metzger da una vita. E' una notizia eccellente, ora dobbiamo solo
 distruggere quel posto orribile. Sai quanto e' ben sorvegliato?}
{205}{}{Le uniche cose che sorvegliano quel posto adesso sono i cadaveri. Ho gia' eliminato tutto il campo.}
{206}{}{Sembra che ci fossero una dozzina di guardie.}
{207}{}{Non saprei dirtelo — non ci sono ancora stato.}
{208}{}{Davvero? E' incredibile! Dovro' diffondere la notizia agli altri Ranger. E' il momento per noi di alzarci e colpire mentre sono
 occupati a leccarsi le ferite. Non posso ringraziarti abbastanza. Siamo davvero in debito con te.}
{209}{}{Il tuo ringraziamento e' tutto cio' di cui ho bisogno. Prenditi cura di te.}
{210}{}{Se sei cosi' soddisfatto del mio lavoro, che ne dici di una piccola ricompensa in contanti?}
{211}{}{Dobbiamo attaccarli subito. Vuoi eliminare questi farabutti per noi?}
{212}{}{Penso di aver fatto abbastanza per oggi. Addio.}
{213}{}{Come Ranger e' mio dovere giurato. Certo che aiutero'.}
{214}{}{Eccellente! Torna quando avrai eliminato il campo.}
{215}{}{Dammi un po’ di tempo. Tornerò quando sarò pronto.}
{216}{}{Certo. A presto.}
{217}{}{Sono uno spontaneo. Non ho bisogno di prepararmi. Mettiamoci in moto.}
{218}{}{In realta', ho cambiato idea. Sono sicuro che tu e gli altri Ranger ve la cavate benissimo senza di me. Buona fortuna.}
{219}{}{In realta', credo che sarebbe meglio se alcuni Ranger venissero con me. Garantirebbe maggior successo sia per la mia parte
 che nella lotta generale contro la schiavitu'.}
{220}{}{No, mi dispiace. Non ho le risorse per radunare degli uomini. E' qualcosa che dovrai fare da solo.}
{221}{}{D’accordo, lo farò da solo. Farò rapporto quando avrò finito.}
{222}{}{D’accordo, lo farò da solo. Ma ho bisogno di prepararmi. Tornerò.}
{223}{}{Allora devo rifiutare. Addio.}
{224}{}{Hai ragione. Mettera' insieme un piccolo gruppo e lo mandero' con te. Sei pronto ad andare adesso?}
{225}{}{Ho bisogno di prepararmi. Tornerò.}
{226}{}{Sono pronto. Andiamo.}
{227}{}{Soldi? Be', suppongo che sia il minimo che potremmo fare. Ecco, 1000 dollari per il tuo disturbo. Grazie ancora.}
{228}{}{È stato un piacere. Addio.}
{229}{}{Sei pronto ad attaccare il campo degli schiavisti?}
{230}{}{Ho bisogno di altro tempo.}
{231}{}{Sono pronto. Facciamolo.}
{232}{}{I tuoi compagni Ranger ti raggiungeranno lungo la strada. In bocca al lupo.}
{233}{}{[FINE]}
{234}{}{Ho sentito la notizia. Grazie mille per il tuo aiuto. Questo dara' sicuramente un bel colpo agli schiavisti. Siamo davvero in debito con te.}
{235}{}{Per favore, non tardare troppo. Questo attacco e' critico nella nostra lotta contro la schiavitu'.}
{236}{}{Aiuti i Ranger nella loro continua lotta contro la schiavitu'.}
{240}{}{Grazie. Arrivederci.}
{250}{}{In realta', un'ultima cosa. Sembri una persona di cui ci si puo' fidare. Qualcuno a cui gli Schiavisti non piacciono affatto.}
{251}{}{Be', ho appena spazzato via un loro intero campo. Cosa avevi in mente?}
{252}{}{Penso di aver fatto abbastanza per l’umanità oggi. Ci vediamo.}
{260}{}{Cosa ci fai qui? Questo e' un posto priv— Ehi, un momento, credo di aver sentito parlare di te. Non sei quello che ha distrutto uno dei campi di schiavi di Metzger?}
{261}{}{Già, ero io.}
{262}{}{Certo che l’ho fatto. Hai qualche problema? }
{263}{}{Forse… perché?}
{264}{}{Non ho idea di cosa tu stia parlando. Ora, se non ti dispiace, vado.}
{270}{}{Quello che hai fatto è stato davvero ammirevole, e vorrei stringerti la mano.}
{271}{}{Affatto. Anzi, vorrei stringerti la mano.}
{272}{}{Perché quello che hai fatto è stato ammirevole, e vorrei stringerti la mano.}
{273}{}{Se sei cosi' soddisfatto del mio lavoro, che ne dici di una piccola ricompensa in contanti?}
{274}{}{Prego. Ora, perché non mi dici chi sei?}
{280}{}{Non abbiamo molti fondi da parte, ma ci hai reso un grande servizio, quindi credo possiamo separarci da qualcosa. Ecco 1000$.}
{281}{}{Grazie. Ciao.}
{282}{}{Grazie. Ora, perché non mi dici chi sei?}
{290}{}{Io sono Elsie. Lui e' Gond. Siamo membri di un gruppo anti-schiavitu' chiamato New California Rangers. Ci servirebbe qualcuno come te. Se ti interessa unirti a noi, ho un incarico per te.}
{291}{}{Sentiamo.}
{292}{}{Non mi interessa. Ciao.}
{300}{}{Posso aiutarti in qualcosa, Ranger?}
