{100}{}{Vedi un uomo in armatura da combattimento.}
{101}{}{Vedi una donna in armatura da combattimento.}
{102}{}{Indossa un distintivo con scritto “NCR Ranger”.}
{103}{}{Indossa un distintivo con scritto “NCR Ranger”.}
{200}{}{Salve collega Ranger. Sei qui per passare la notte?}
{201}{}{Hai ucciso qualche schiavista oggi?}
{202}{}{Abbiamo liberato una dozzina di schiavi oggi.}
{203}{}{Proteggere le Lande e' un lavoro duro, ma qualcuno deve pur farlo.}
{204}{}{Felice di averti con noi. Resta quanto vuoi.}
{205}{}{Ho sentito cosa è successo a Metzger. Ottimo lavoro!}
{300}{}{È uno schiavista! All’attacco!}
{301}{}{Merda, siamo sotto attacco!}
{400}{}{Saluti, amico.}
{401}{}{Questa è proprietà privata. Non restare troppo a lungo.}
{402}{}{Ti piacciono gli schiavisti? Spero proprio di no... per il tuo bene.}
{500}{}{Cosa!? Schiavisti? Come diavolo ci hanno trovato? Dobbiamo difenderci. All'attacco!}
{501}{}{Aspettate! Sono dalla vostra parte. Vi stavo solo portando un po' di bersagli. (si gira verso gli Schiavisti) Scusate ragazzi, sono fatto cosi'. (Attacca gli Schiavisti)}
{502}{}{Sara' divertente! (Attacca i Rangers)}
{600}{}{Hai eliminato il rifugio dei Ranger.}
