{100}{}{You see a man dressed in combat armor.}
{101}{}{You see a woman dressed in combat armor.}
{102}{}{He is wearing a badge that says NCR Ranger.}
{103}{}{She is wearing a badge that says NCR Ranger.}
{200}{}{Salve collega Ranger. Sei qui per passare la notte?}
{201}{}{Kill any slavers today?}
{202}{}{Abbiamo liberato una dozzina di schiavi oggi.}
{203}{}{Proteggere le Lande e' un lavoro duro, ma qualcuno deve pur farlo.}
{204}{}{Good to have you aboard. Stay as long as you wish.}
{205}{}{I heard what happened to Metzger. Great job!}
{300}{}{It's a slaver, attack!}
{301}{}{Shit, we are under attack!}
{400}{}{Saluti, amico.}
{401}{}{This is private property. Don't loiter too long.}
{402}{}{Ti piacciono gli schiavisti? Spero proprio di no... per il tuo bene.}
{500}{}{Cosa!? Schiavisti? Come diavolo ci hanno trovato? Dobbiamo difenderci. All'attacco!}
{501}{}{Aspettate! Sono dalla vostra parte. Vi stavo solo portando un po' di bersagli. (si gira verso gli Schiavisti) Scusate ragazzi, sono fatto cosi'. (Attacca gli Schiavisti)}
{502}{}{Sara' divertente! (Attacca i Rangers)}
{600}{}{You wipe out the Ranger safe house.}
