{100}{}{Vedi un vecchio smunto con una penna infilata dietro un orecchio e degli occhiali appoggiati sulla punta del naso.}
{101}{}{E' Vortis, il proprietario di questo campo schiavi.}
{102}{}{Avra' circa tre denti. Le sue dita e la camicia sono macchiate d'inchiostro blu. Sulla fronte porta un tatuaggio da schiavista che ormai si e' quasi del tutto cancellato.}
{103}{}{E allora cosa vuoi?}
{104}{}{Fratello, benvenuto nella magione di Vortis. Come posso aiutarti?}
{105}{}{Stai cominciando a stufarmi.}
{106}{}{Questo posto e' mio e io, Vortis, mi occupo di affari onesti e assolutamente legittimi; e non credere a quello che ti dicono i tizi di NCR. Dal momento che NCR non ammette schiavi all'interno delle sue mura, io li tengo d'occhio per quei proprietari che devono entrare in citta'.}
{107}{}{Ma cosa sei, stupido? Questo e' un campo schiavi. Ho tutti i permessi in regola.}
{108}{}{}
{109}{}{Avrei solo alcune domande.}
{110}{}{Sto cercando lavoro.}
{111}{}{Uh?}
{112}{}{No essere gabinetto? Me va via.}
{113}{}{Cos'e' questo posto?}
{114}{}{Nulla. Ho sbagliato porta.}
{115}{}{Oh, ma sentitelo, il santerellino. Ragazzi, toglietemi dalla vista questo ipocrita esempio di sante virtu'!}
{116}{}{Affanculo.}
{117}{}{Beh?}
{118}{}{Sto cercando il Vault 13.}
{119}{}{Hai un GECK?}
{120}{}{Cosa puoi dirmi a proposito di questa citta'?}
{121}{}{Tu sei feccia schiavista! Perche' mai non dovrei ucciderti?}
{122}{}{Ho sentito parlare di questi tizi - i Ranger della Nuova California. Ti hanno mai dato problemi?}
{123}{}{Ti dispiace se do un'occhiata in giro?}
{124}{}{Un lavoro? Beh... potrebbe esserci qualcosa. Hai mai sentito parlare dei Ranger della Nuova California?}
{125}{}{Si'.}
{126}{}{No.}
{127}{}{Ma vattela a prendere in culo. Ragazzi, toglietemi dalla vista questo merdoso rompiballe.}
{128}{}{Va' a quel paese!}
{129}{}{Vault 13! Fuori di qui! Quel dannato posto e' solo una leggenda. Vault 13, un corno!}
{130}{}{Un'altra domanda...}
{131}{}{Beh, davvero molto gentile.}
{132}{}{Un che? Beh, qualunque cosa sia, non ce l'ho.}
{133}{}{Un'altra domanda...}
{134}{}{Beh, davvero molto gentile.}
{135}{}{La New California Republic - nient'altro che un ammasso di tipi moderati e di mercanti. Hanno qualche problema con gli schiavisti e la schiavitu', ma - che diavolo! - io ci campo con queste cose.}
{136}{}{Un'altra domanda...}
{137}{}{Grazie, devo andare.}
{138}{}{Qualcuno ti ha detto male. Non ho mai avuto problemi con nessuno - e soprattutto non con i Ranger. Quello che faccio e' tutto legale, non c'e' nulla contro di me.}
{139}{}{Un'altra domanda...}
{140}{}{Proprio cosi'. Devo andare.}
{141}{}{Si'... puo' anche darsi che io abbia qualche problema con i Ranger. Stai cercando lavoro?}
{142}{}{Si'.}
{143}{}{No.}
{144}{}{No, non puoi andare a ficcare il naso dove vuoi, testa di cazzo! Questo non e' un museo!}
{145}{}{Un'altra domanda...}
{146}{}{Sei troppo permaloso per i miei gusti. Me ne vado.}
{147}{}{Bene. Allora... devi sapere che alcune persone li vedono come una potenziale fonte di problemi. Sarebbe davvero una gran cosa se riuscissimo a procurarci una mappa delle loro postazioni nel nord - New Reno, Klamath, ovunque. Sarei disposto a pagare, diciamo, 500$ per una cosa del genere. Credi di potermela procurare?}
{148}{}{Bene.}
{149}{}{Non credo proprio.}
{150}{}{Te ne parlero' io, allora. Questi Ranger si sono messi in testa di eliminare la schiavitu' e gli schiavisti - con la forza. Sono una vera spina nel fianco di tanti lavoratori.}
{151}{}{Lavorano sotto copertura, soprattutto nel nord.}
{152}{}{Cavoli, devo farti un disegno? Attaccano gli schiavisti, si appropriano delle nostre "scorte", e le portano giu' a sud, nel territorio di NCR dove la schiavitu' e' considerata illegale. Allora, ti interessa?}
{153}{}{Non ci sono "e"! Vuoi il lavoro o no?}
{154}{}{E?}
{155}{}{Allora, cosa vuoi che faccia?}
{156}{}{Bene. Quando hai la mappa, io saro' qui.}
{157}{}{E dove potrei trovarla, una mappa?}
{158}{}{Okay. Avrei delle altre domande, pero'.}
{159}{}{Me ne occupo subito. Ci vediamo.}
{160}{}{E cosa diavolo vuoi che ne sappia io!? Se lo sapessi ne avrei gia' una, non credi? Ascolta: dovrebbe esserci una loro squadra in citta'. Trovali e vedi quello che riesci a fare.}
{161}{}{Ancora un paio di domande.}
{162}{}{D'accordo. Tornero'.}
{163}{}{Sei tornato. L'hai presa quella mappa?}
{164}{}{Si'.}
{165}{}{No.}
{166}{}{Sto ancora aspettando che tu porti a termine il tuo primo incarico!}
{167}{}{Oh, certo! Me n'ero dimenticato.}
{168}{}{Da quando hai fatto il tuo lavoro, no. Grazie.}
{169}{}{Solo una domanda o due.}
{170}{}{Nessun problema. Addio.}
{171}{}{Ottimo lavoro. Adesso sara' meglio che tu diventi uccel di bosco, casomai i Ranger dovessero capire cos'e' successo.}
{172}{}{E' stato un piacere fare affari con te.}
{173}{}{Beh, non startene qui imbambolato, imbecille! Qualcuno potrebbe insospettirsi.}
{174}{}{D'accordo, ho capito l'antifona.}
{175}{}{Cosa cazzo...? Guardie! Abbiamo un ospite indesiderato!}
{176}{}{Prova ad entrare li' dentro e ti faro' saltare la testa. Hai capito?}
{177}{}{E' tardi e siamo chiusi. Torna al mattino.}
{200}{}{Bel lavoro. Un'ultima cosa pero'. Sei uno schiavista, giusto? Che ne dici di darmi una mano e ripulire quei rifugi per me? Potrei pagarti — diciamo 1000$.}
{201}{}{Bel lavoro. Un'ultima cosa pero'. Sembri un tipo tosto. Che ne dici di ripulire quei rifugi per me? C'e' una ricompensa — diciamo 1000$.}
{202}{}{Bene.}
{203}{}{Non mi interessa.}
{204}{}{Eccellente. Qui, lascia che ti segni queste coordinate sulla tua mappetta. Riferisci quando hai finito.}
{205}{}{Peggio per te. Ora è meglio che sparisci, nel caso quei Ranger capiscano cosa è successo.}
{206}{}{Okay. Ci vediamo.}
{207}{}{A dire il vero, pensi di poter mandare alcuni dei tuoi uomini con me? Renderebbe tutto molto piu' veloce e garantirebbe il successo.}
{210}{}{Sei tornato. Hai eliminato i rifugi dei Ranger?}
{211}{}{Certo che l'ho fatto. Un gioco da ragazzi.}
{212}{}{Non ancora. Ci sto ancora lavorando.}
{215}{}{Davvero? Dannazione. Questa e' la miglior notizia che abbia sentito finora. Sara' un duro colpo per i Rangers. Bel lavoro. Ecco il tuo pagamento. Ora ti conviene sparire, i Rangers in citta' ti cercheranno di sicuro.}
{216}{}{Che guardino pure — non ho paura. Grazie per i soldi.}
{217}{}{Allora è meglio che lasci la città. A dopo.}
{218}{}{Sembra che qualsiasi cosa io faccia riesca a far arrabbiare qualcuno. Ormai ci sono abituato. Ciao.}
{220}{}{Assolutamente no. Non radunero' nessuno per questo. Se pensi di non farcela, allora vattene.}
{221}{}{Non ho mai detto che non posso farcela. Pensavo solo che ai tuoi uomini sarebbe piaciuto unirsi al divertimento. Ma va bene, me la sbrighero' da solo, nessun problema. Riferiro' quando ho finito.}
{222}{}{Bene, puoi escludermi, stronzo. Non saro' il tuo cagnolino. Addio.}
{223}{}{Mi stai dando del codardo? Nessuno mi chiama cosi' e resta vivo!}
{225}{}{Be', d'accordo. Credo di poter radunare qualche ragazzo per aiutarti. Ti incontreranno lungo la strada. Sei pronto a iniziare ora?}
{226}{}{Dammi un po’ di tempo. Tornerò quando sarò pronto.}
{227}{}{Sono nato pronto. Andiamo a spaccare.}
{228}{}{Sono pronto. Andiamo.}
{229}{}{Penso che passerò. Ho perso interesse. Addio.}
{230}{}{Sei pronto per il raid, o sei qui per farmi perdere altro tempo?}
{231}{}{Ho bisogno di più tempo.}
{232}{}{Sono pronto. Andiamo.}
{240}{}{Elimini i rifugi dei Rangers. Questo infligge un duro colpo ai Rangers nella loro lotta contro la schiavitu'.}
{241}{}{Vorrei comprare degli schiavi.}
{250}{}{Be', che bello. Qui non vendiamo niente. Metzger a nord, al Den, puo' aiutarti con quello.}
{251}{}{Ci sono stato, e la sua “merce” non era all’altezza dei miei standard.}
{252}{}{Visto che ho ucciso Metzger, non so quanto mi possa servire. Credo che uccidero' te invece.}
{260}{}{Ma guarda che tipo difficile. Ti rendi conto che la sua merce non e' limitata al Den, vero? Ha un suo recinto dove vengono scaricati gli schiavi.}
{261}{}{Interessante. Come arrivo a quest’altro posto?}
{270}{}{Cosa, pensi di poter avere tutto gratis? 1000$. Prendere o lasciare.}
{271}{}{Cosa, pensi di poter avere tutto gratis? Inoltre, trasudi virtu'. Non mi piace. 2000$. Prendere o lasciare.}
{272}{}{D’accordo, tieni.}
{273}{}{Lasciamo stare.}
{274}{}{Faccio quello che voglio. E credo che ora ti ucciderò.}
{275}{}{Tornero' quando avro' piu' soldi.}
{280}{}{[Indica sulla tua mappa la posizione del campo degli schiavisti.] E' da quelle parti. Ora cos'altro vuoi per farmi perdere tempo?}
{281}{}{Ho quello che mi serve. Addio.}
