{100}{}{Vedi una motobarca.}
{200}{}{Ti intrufoli nella motovedetta quando la guardia non guarda e ti nascondi alla vista. Verso mezzanotte senti delle voci e percepisci la barca iniziare a muoversi.}
{201}{}{Dopo aver detto ai tuoi compagni di restare fermi, ti intrufoli nella motovedetta quando la guardia non guarda e ti nascondi alla vista. Verso mezzanotte senti delle voci e percepisci la barca iniziare a muoversi.}
{210}{}{Forse dovrei disattivare questa cosa prima di andarmene.}
{220}{}{È troppo rischioso usarlo di nuovo.}
{221}{}{Non saprei proprio dove andare.}
