{100}{}{You see a motor boat.}
{200}{}{Ti intrufoli nella motovedetta quando la guardia non guarda e ti nascondi alla vista. Verso mezzanotte senti delle voci e percepisci la barca iniziare a muoversi.}
{201}{}{Dopo aver detto ai tuoi compagni di restare fermi, ti intrufoli nella motovedetta quando la guardia non guarda e ti nascondi alla vista. Verso mezzanotte senti delle voci e percepisci la barca iniziare a muoversi.}
{210}{}{Maybe I should disarm this thing before I go.}
{220}{}{It's too risky to use that again.}
{221}{}{I wouldn't know where to go.}
