{100}{}{Dopo circa un quarto d'ora, la motovedetta traballante arriva a una torretta arrugginita che spunta dall'acqua, al largo della costa di San Francisco. 
Le acque basse sono torbide, ma puoi vedere chiaramente il profilo del gigantesco sottomarino.}
{101}{}{La squadra tecnica degli Shi sbarca rapidamente e scompare all'interno del sottomarino.}
{102}{}{Mentre ti allontani dal sottomarino, una massiccia esplosione squarcia l'aria, scagliando litri d'acqua in tutte
 le direzioni. Ti volti e noti che dove prima c'era una torretta, ora non c'e' assolutamente piu' nulla.}
