{100}{}{Vedi uno schiavista.}
{101}{}{Questo schiavista ha un’aria davvero minacciosa.}
{102}{}{Questa schiavista ha un’aria davvero feroce.}
{200}{}{Eccoti qua.}
{201}{}{Adesso morirai.}
{202}{}{Merda, i Ranger! È ora di spaccare tutto.}
{300}{}{Ti sei perso, o cosa?}
{301}{}{Don è quello al comando. Parla con lui.}
{302}{}{Questa è proprietà privata. Non bighellonare.}
{303}{}{Non si vedono molte schiaviste in giro.}
{304}{}{E' bello averti tra di noi.}
{305}{}{Ciao. Come va?}
{306}{}{Hai beccato qualche schiavo?}
{307}{}{Ciao.}
{308}{}{Stai uscendo per un’altra spedizione?}
{309}{}{La situazione e' piuttosto tranquilla.}
{310}{}{Quand’è che vedrò un po’ d’azione?}
{311}{}{Catturare schiavi mi mette sempre di buon umore.}
{312}{}{I raid per gli schiavi sono davvero grandiosi.}
{313}{}{Ehi, felice di averti con noi.}
{400}{}{Alt! Dove diavolo credi di andare?}
{401}{}{Metzger mi ha mandato. Devo parlare con chi comanda qui.}
{402}{}{Ho degli schiavi che potrebbero interessarvi.}
{403}{}{Mi hanno chiamato per un problema di roditori. Vale a dire tutti voi qui.}
{404}{}{[Gli occhi dell'uomo si infiammano.] Hai scelto il gruppo sbagliato con cui scherzare. EHI RAGAZZI, ABBIAMO UN INTRUSO!}
{405}{}{[Osserva dall'alto in basso i membri del tuo gruppo.] Penso che potremmo essere interessati. Entra e parla con Don.}
{406}{}{Non e' un po' presto per un'altra consegna? Di cosa ha bisogno Metzger?}
{407}{}{Gli servono alcuni schiavi in buona salute. In particolare schiave donne, se capisci cosa intendo.}
{408}{}{Hehe. Certo che capisco. Be', entra e parla con Don. Sono sicuro che ha quello che il capo vuole.}
{409}{}{Umm... be', lui ehm... ha detto che gli servono altri schiavi.}
{410}{}{Altri schiavi? Ha ricevuto un enorme carico la settimana scorsa. Sei pieno di stronzate e non ho tempo per questo. Vattene ora
 o ti ritrovi una pallottola in testa.}
{411}{}{Me ne stavo andando.}
{412}{}{Penso che resterò… e ti ucciderò per primo.}
{500}{}{Umm... ehm... il capo mi ha mandato.}
{501}{}{Il "capo", eh? Sembra proprio che tu sia pieno di stronzate. Direi che abbiamo un intruso.}
{502}{}{Senti, sono qui per ordine del capo. Sai come diventa quando lo facciamo aspettare.}
{503}{}{Metzger ti ha mandato, eh? A volte sa essere davvero una rottura. Ma, ehm, (l'uomo si agita) non dire a nessuno che l'ho detto.}
{504}{}{Si', Metzger mi ha mandato davvero. Ora devo parlare con chi comanda qui.}
{599}{}{Toccala di nuovo e sei morto.}
{600}{}{Te l’avevo detto, stronzo!}
{800}{}{[FATTO]}
{900}{}{Cosa!? I Rangers! Merda, come ci hanno trovato? Va bene, e' ora di spaccare qualche culo!}
