{100}{}{Vedi uno schiavista dall’aria torva, coperto di sporcizia.}
{101}{}{Vedi uno schiavista dall’aria dura. Sembra essere lui il capo qui.}
{102}{}{Vedi Don, lo schiavista responsabile di questo campo.}
{105}{}{Ehi, che cazzo!? Chi diavolo sei?}
{106}{}{Sono il tuo incubo peggiore. Preparati a morire!}
{107}{}{Mi manda Metzger.}
{108}{}{Sono qui per unirmi a voi.}
{109}{}{Uhh… non è qui che avevo lasciato la mia macchina…}
{200}{}{Prima tu, stronzo.}
{201}{}{Non ho tempo per questo. Prendetelo, ragazzi.}
{202}{}{Unirti a noi? Questo non e' un dannato centro reclutamento. Se vuoi unirti agli schiavisti vai al Den e parla con Metzger.
 Ora ti serve qualcosa o sei qui solo per farmi incazzare?}
{203}{}{Metzger ti ha mandato? [Si agita a disagio.] Non dirmi che vuole gia' altri schiavi — per l'amor del cielo, abbiamo spedito un carico la settimana scorsa.}
{300}{}{In realtà sì, mi serve qualcosa.}
{301}{}{Allora, perche' sei qui?}
{302}{}{Non credo di aver bisogno d’altro.}
{303}{}{Allora levati di torno. Sei un intruso e qui non ti vuole nessuno.}
{304}{}{Me ne stavo andando.}
{305}{}{Oh, me ne andro'... ma solo dopo aver ucciso te e i tuoi amici.}
{307}{}{A dire il vero, si'. Deve intrattenere un pezzo grosso di New Reno e voleva un paio di ragazze in piu' per l'occasione. Ma ehi, se non puoi cederne nessuna... sono sicuro che il capo sara' felicissimo quando tornero' a mani vuote.}
{308}{}{[Gocce di sudore compaiono sulla testa tatuata dell'uomo.] Ehi, aspetta un secondo. Non ho mai detto che non posso cederne qualcuna. Anzi, tieni, prendi la chiave della baracca, e' li' che teniamo le nostre, uh, preferite personali. Il meglio del meglio, diciamo. [Ti porge una chiave e sorride nervosamente.]}
{309}{}{Grazie. Dirò una buona parola per te. Addio.}
{310}{}{Metzger ti ha mandato, eh? Ti sembro cieco? Non indossi nemmeno il nostro dannato marchio. Non so chi tu sia, ma sei pieno di stronzate e mi stai facendo perdere tempo. Per questo, muori. [Fa cenno ai suoi uomini.] Facciamo fuori questo idiota.}
{311}{}{Si, come no. Sei pieno di stronzate e mi stai facendo perdere tempo. Per questo, muori. [Fa cenno ai suoi uomini.] Facciamo fuori questo idiota.}
{400}{}{Sono occupato. Vai da Metzger al Den se vuoi fare una consegna.}
{450}{}{Non ti avevo detto di sparire? Non siamo molto gentili con gli intrusi. E' ora di morire.}
{500}{}{[FATTO]}
{600}{}{Adesso morirai!}
{601}{}{Muori, feccia Ranger!}
{800}{}{Umm... Dai i miei saluti a Metzger.}
{900}{}{No, in realta' mi ha mandato per dare un'occhiata alla vostra merce. Vedi, ho gusti molto particolari, ma sono disposto
 a pagare un prezzo premium.}
{901}{}{Balle. Metzger non ha mai mandato un cliente qui. Non so cosa stai cercando di fare, ma hai tre secondi per levarti dalla mia vista prima che i miei ragazzi ti riempiano di piombo.}
