{100}{}{Vedi uno schiavista.}
{101}{}{Questo schiavista ha un’aria davvero minacciosa.}
{200}{}{Eccoti qua.}
{201}{}{Adesso morirai.}
{202}{}{Shit, Rangers! Time to die!}
{300}{}{You lost or something?}
{301}{}{Don is the one in charge. Talk to him.}
{302}{}{This is private property. No loitering.}
{303}{}{You don't see too many women slavers.}
{304}{}{E' bello averti tra di noi.}
{305}{}{Ciao. Come va?}
{306}{}{Hai beccato qualche schiavo?}
{307}{}{Ciao.}
{308}{}{Heading out on another run?}
{309}{}{La situazione e' piuttosto tranquilla.}
{310}{}{Quand'e' che potro' menare un po' le mani?}
{311}{}{Catturare schiavi mi mette sempre di buon umore.}
{312}{}{I raid per gli schiavi sono davvero grandiosi.}
{313}{}{Hey, glad to have you with us.}
{500}{}{Hey you! What do you think you're doing? I ain't seen you before.}
{501}{}{Metzger mi ha mandato a controllare la sua merce. Sai com'e'. Se non e' perfetta, vola tutto per aria.
 E sono gia' in ritardo. Devo finire questa ispezione e riferire a lui. Vuoi essere tu il responsabile
 del mio ritardo?}
{502}{}{Umm... ehm... Okay, allora vai pure. Io resto qui se ti serve qualcosa.}
{503}{}{Thanks. I'll put in a good word for you with the big man. Bye.}
{504}{}{Strano che Metzger mandi qualcuno senza il nostro tatuaggio. Non mi freghi. E' ora di buttare la spazzatura.}
{505}{}{Look, a one headed brahmin!}
{506}{}{Ma, ehm, non ti ho mai visto prima. Dov'e' il tizio di solito?}
{507}{}{E' malato. Brutta influenza.}
{508}{}{He was killed during a slave run.}
{509}{}{Damn, that's too bad. Well, go ahead then. I'll be here if you need something.}
{510}{}{The flu? Yeah, right. Looks like we got an intruder on our hands.}
{600}{}{I warned you, asshole!}
{800}{}{[FATTO]}
