{100}{}{You see a scowling slaver covered in grime.}
{101}{}{You see a tough looking slaver. He appears to be in charge here.}
{102}{}{You see Don, the slaver in charge of this camp.}
{105}{}{Hey, what the fuck!? Who the hell are you?}
{106}{}{I'm your worst nightmare. Prepare to die!}
{107}{}{Mi manda Metzger.}
{108}{}{I'm here to join.}
{109}{}{Uhh, this isn't where I left my car...}
{200}{}{You first, asshole.}
{201}{}{I don't have time for this, get 'em boys.}
{202}{}{Unirti a noi? Questo non e' un dannato centro reclutamento. Se vuoi unirti agli schiavisti vai al Den e parla con Metzger.
 Ora ti serve qualcosa o sei qui solo per farmi incazzare?}
{203}{}{Metzger ti ha mandato? [Si agita a disagio.] Non dirmi che vuole gia' altri schiavi — per l'amor del cielo, abbiamo spedito un carico la settimana scorsa.}
{300}{}{Actually yes, I do need something.}
{301}{}{Allora, perche' sei qui?}
{302}{}{I don't think I need anything else.}
{303}{}{Allora levati di torno. Sei un intruso e qui non ti vuole nessuno.}
{304}{}{Me ne stavo andando.}
{305}{}{Oh, me ne andro'... ma solo dopo aver ucciso te e i tuoi amici.}
{307}{}{A dire il vero, si'. Deve intrattenere un pezzo grosso di New Reno e voleva un paio di ragazze in piu' per l'occasione. Ma ehi, se non puoi cederne nessuna... sono sicuro che il capo sara' felicissimo quando tornero' a mani vuote.}
{308}{}{[Gocce di sudore compaiono sulla testa tatuata dell'uomo.] Ehi, aspetta un secondo. Non ho mai detto che non posso cederne qualcuna. Anzi, tieni, prendi la chiave della baracca, e' li' che teniamo le nostre, uh, preferite personali. Il meglio del meglio, diciamo. [Ti porge una chiave e sorride nervosamente.]}
{309}{}{Thanks. I'll put in a good word for you. Bye.}
{310}{}{Metzger ti ha mandato, eh? Ti sembro cieco? Non indossi nemmeno il nostro dannato marchio. Non so chi tu sia, ma sei pieno di stronzate e mi stai facendo perdere tempo. Per questo, muori. [Fa cenno ai suoi uomini.] Facciamo fuori questo idiota.}
{311}{}{Si, come no. Sei pieno di stronzate e mi stai facendo perdere tempo. Per questo, muori. [Fa cenno ai suoi uomini.] Facciamo fuori questo idiota.}
{400}{}{Sono occupato. Vai da Metzger al Den se vuoi fare una consegna.}
{450}{}{Non ti avevo detto di sparire? Non siamo molto gentili con gli intrusi. E' ora di morire.}
{500}{}{[FATTO]}
{600}{}{Adesso morirai!}
{601}{}{Die Ranger scum!}
{800}{}{Umm... Dai i miei saluti a Metzger.}
{900}{}{No, in realta' mi ha mandato per dare un'occhiata alla vostra merce. Vedi, ho gusti molto particolari, ma sono disposto
 a pagare un prezzo premium.}
{901}{}{Balle. Metzger non ha mai mandato un cliente qui. Non so cosa stai cercando di fare, ma hai tre secondi per levarti dalla mia vista prima che i miei ragazzi ti riempiano di piombo.}
