{100}{}{Vedi uno schiavista.}
{101}{}{Questo schiavista ha un’aria davvero minacciosa.}
{102}{}{This slaver looks like one mean chick.}
{200}{}{Eccoti qua.}
{201}{}{Adesso morirai.}
{202}{}{Shit, Rangers! Time to kick ass.}
{300}{}{You lost or something?}
{301}{}{Don is the one in charge. Talk to him.}
{302}{}{This is private property. No loitering.}
{303}{}{You don't see too many women slavers.}
{304}{}{E' bello averti tra di noi.}
{305}{}{Ciao. Come va?}
{306}{}{Hai beccato qualche schiavo?}
{307}{}{Ciao.}
{308}{}{Heading out on another run?}
{309}{}{La situazione e' piuttosto tranquilla.}
{310}{}{When am I gonna see some action?}
{311}{}{Catturare schiavi mi mette sempre di buon umore.}
{312}{}{I raid per gli schiavi sono davvero grandiosi.}
{313}{}{Hey, glad to have you with us.}
{400}{}{Hold it right there. Where the hell do you think you're going?}
{401}{}{Metzger mi ha mandato. Devo parlare con chi comanda qui.}
{402}{}{I got some slaves you guys might be interested in.}
{403}{}{Mi hanno chiamato per un problema di roditori. Vale a dire tutti voi qui.}
{404}{}{[Gli occhi dell'uomo si infiammano.] Hai scelto il gruppo sbagliato con cui scherzare. EHI RAGAZZI, ABBIAMO UN INTRUSO!}
{405}{}{[Osserva dall'alto in basso i membri del tuo gruppo.] Penso che potremmo essere interessati. Entra e parla con Don.}
{406}{}{Non e' un po' presto per un'altra consegna? Di cosa ha bisogno Metzger?}
{407}{}{Gli servono alcuni schiavi in buona salute. In particolare schiave donne, se capisci cosa intendo.}
{408}{}{Hehe. Certo che capisco. Be', entra e parla con Don. Sono sicuro che ha quello che il capo vuole.}
{409}{}{Umm... be', lui ehm... ha detto che gli servono altri schiavi.}
{410}{}{Altri schiavi? Ha ricevuto un enorme carico la settimana scorsa. Sei pieno di stronzate e non ho tempo per questo. Vattene ora
 o ti ritrovi una pallottola in testa.}
{411}{}{Me ne stavo andando.}
{412}{}{I think I'll stay and kill you first.}
{500}{}{Umm... ehm... il capo mi ha mandato.}
{501}{}{Il "capo", eh? Sembra proprio che tu sia pieno di stronzate. Direi che abbiamo un intruso.}
{502}{}{Senti, sono qui per ordine del capo. Sai come diventa quando lo facciamo aspettare.}
{503}{}{Metzger ti ha mandato, eh? A volte sa essere davvero una rottura. Ma, ehm, (l'uomo si agita) non dire a nessuno che l'ho detto.}
{504}{}{Si', Metzger mi ha mandato davvero. Ora devo parlare con chi comanda qui.}
{599}{}{Touch it again and you die.}
{600}{}{I warned you asshole!}
{800}{}{[FATTO]}
{900}{}{Cosa!? I Rangers! Merda, come ci hanno trovato? Va bene, e' ora di spaccare qualche culo!}
