{100}{}{Vedi uno schiavista.}
{101}{}{Questo schiavista ha un’aria davvero minacciosa.}
{200}{}{Eccoti qua.}
{201}{}{Adesso morirai.}
{202}{}{Merda, i Ranger! È ora di morire!}
{300}{}{Ti sei perso, o cosa?}
{301}{}{Don è quello al comando. Parla con lui.}
{302}{}{Questa è proprietà privata. Non bighellonare.}
{303}{}{Non si vedono molte schiaviste in giro.}
{304}{}{E' bello averti tra di noi.}
{305}{}{Ciao. Come va?}
{306}{}{Hai beccato qualche schiavo?}
{307}{}{Ciao.}
{308}{}{Stai uscendo per un’altra spedizione?}
{309}{}{La situazione e' piuttosto tranquilla.}
{310}{}{Quand'e' che potro' menare un po' le mani?}
{311}{}{Catturare schiavi mi mette sempre di buon umore.}
{312}{}{I raid per gli schiavi sono davvero grandiosi.}
{313}{}{Ehi, felice di averti con noi.}
{500}{}{Ehi tu! Che credi di fare? Non ti ho mai visto prima.}
{501}{}{Metzger mi ha mandato a controllare la sua merce. Sai com'e'. Se non e' perfetta, vola tutto per aria.
 E sono gia' in ritardo. Devo finire questa ispezione e riferire a lui. Vuoi essere tu il responsabile
 del mio ritardo?}
{502}{}{Umm... ehm... Okay, allora vai pure. Io resto qui se ti serve qualcosa.}
{503}{}{Grazie. Metterò una buona parola per te con il capo. Addio.}
{504}{}{Strano che Metzger mandi qualcuno senza il nostro tatuaggio. Non mi freghi. E' ora di buttare la spazzatura.}
{505}{}{Guarda, un brahmin con una sola testa!}
{506}{}{Ma, ehm, non ti ho mai visto prima. Dov'e' il tizio di solito?}
{507}{}{E' malato. Brutta influenza.}
{508}{}{È stato ucciso durante una spedizione di schiavi.}
{509}{}{Accidenti, che peccato. Va’ pure. Sarò qui se ti serve qualcosa.}
{510}{}{L’influenza? Ma certo… sembra proprio che abbiamo un intruso tra noi.}
{600}{}{Te l’avevo detto, stronzo!}
{800}{}{[FATTO]}
