{100}{}{Vedi un pescatore.}
{101}{}{Vedi una pescatrice.}
{102}{}{Porta con se' un palo appuntito usato per la pesca.}
{103}{}{Sembra impegnata a cucinare.}
{104}{}{Salve.}
{200}{}{Non sei il benvenuto qui.}
{201}{}{Gli spiriti non ti vedono di buon occhio.}
{202}{}{Vattene, straniero.}
{203}{}{Perché ci tormenti?}
{204}{}{Benvenuto, amico.}
{205}{}{Sarai sempre il benvenuto qui.}
{206}{}{Gli spiriti ti accettano come uno di noi.}
{207}{}{Grazie per averci aiutato.}
{208}{}{Credevo che tutti i forestieri fossero malvagi. Non e' cosi'...}
{209}{}{Non farlo.}
{300}{}{Scusa, ma potresti farmi un piccolo favore? Sono un po' occupata qui e non so se posso lasciare questa pentola incustodita.}
{301}{}{Certo. Cosa ti serve?}
{302}{}{Anche io sono occupato. Forse più tardi.}
{303}{}{Ehi, la vita e' piena di problemi e non sono qui per risolverli tutti. Ciao.}
{304}{}{Sto finendo la legna per questo fuoco. Se potessi raccoglierne ancora un po' per me, lo apprezzerei davvero. Lo farei io stessa, ma temo che questa pentola traboccherebbe se la lasciassi incustodita. Sono sicura che si possano trovare dei tronchi nella foresta vicina. Tre fasci sarebbero perfetti.}
{305}{}{Sarà un piacere.}
{306}{}{In realta', per qualche strana ragione, mi capita di avere tre fasci di tronchi addosso proprio adesso. Eccoli.}
{307}{}{Mi aiuterai? Ottimo! Fammi sapere quando li avrai raccolti.}
{308}{}{Ah, eccellente. Questo aiutera' a mantenere vivo il fuoco. Grazie per aver preso il tempo di aiutarmi. Non ho pero' davvero
 nulla con cui ripagarti.}
{309}{}{La tua gratitudine è sufficiente. Stammi bene.}
{310}{}{Niente con cui ripagarmi? Senti signora, avrei potuto morire in quei boschi. E' pieno di ogni tipo di creature mortali. Mi sono giocato il collo per questa cazzo di legna. Per non parlare del fatto che credo che uno dei tronchi mi abbia dato una scheggia. *Odio* le schegge.}
{311}{}{Be', tieni, prendi questi soldi. Non me ne faccio nulla qui. Grazie ancora.}
{312}{}{Meglio così. Addio.}
{313}{}{[FATTO]}
{314}{}{Hmph. Vai a disturbare qualcun altro.}
{315}{}{Hai portato la legna da ardere?}
{316}{}{Sì, ce l’ho proprio qui.}
{317}{}{No, non ancora. Tornerò quando avrò i tre fasci.}
{318}{}{Sei pronto ad aiutarmi?}
{319}{}{Certo. Cosa ti serve?}
{320}{}{No, ho ancora bisogno di tempo. Addio.}
{321}{}{No, e non lo faro'. Risolviti i problemi da sola. Ciao.}
{330}{}{Non te ne fai nulla? Allora perche' non me li hai dati subito? (borbotta) Stupida stronza.}
{400}{}{Che cosa serve?}
{401}{}{Ooo! Fare cibo preferito mio!}
{410}{}{Me cerca.}
{411}{}{Me ha legna. Heh-heh… legna.}
{420}{}{Va bene. Ciao!}
{500}{}{Vile schiavista!}
