{100}{}{Vedi un mercante corpulento con una benda sull’occhio.}
{101}{}{Roy l'Orbo ti osserva attentamente con il suo occhio buono mentre si asciuga il sudore dalla fronte.}
{200}{}{[Mentre tu e Krom vi avvicinate al luogo dell'incontro, venite accolti da un mercante grassoccio con una benda sull'occhio e un
 piccolo seguito di guardie del corpo. Sebbene il mercante stia sudando copiosamente, appare decisamente allegro.]}
{201}{}{[AVANTI]}
{202}{}{[Dopo aver salutato Krom con entusiasmo, si gira verso di te e ti squadra. Sebbene il suo sorriso
 non vacilli mai, il suo occhio indagatore tradisce un accenno di sospetto.] Quindi Krom qui dice che oggi devo fare affari con te.
 [Scrolla le spalle.] La gente mi chiama Roy l'Orbo, ma non riesco proprio a capire perche'. [Ride di gusto alla sua battuta.]
 Come ti chiami, amico?}
{203}{}{Sono }
{204}{}{ di Arroyo.}
{205}{}{Bene. Iniziamo.}
{210}{}{È un vero piacere conoscerti, }
{211}{}{. Se me lo permetti, sei un tipo un po' strano per essere un tribale.}
{212}{}{Non sono un tribale qualunque. In realta', sono il Prescelto.}
{213}{}{Non so cosa intendi. Sono solo un tribale qualunque. Niente di strano in me.}
{214}{}{Oh, per via di quello che indosso? Vedi, sto cercando di lanciare una nuova moda tribale. Sono stanco dei soliti
 pantaloni di pelle di brahmin con una cinghia sul petto. Quello stile e' *cosi'* 2240.}
{215}{}{Chi chiami "tipo strano", grassone figlio di puttana con un occhio solo? [Attacca.]}
{220}{}{[Il suo sorriso vacilla leggermente e annuisce.] Bene, allora veniamo agli affari. Dimmi, amico, hai mai sentito
 parlare di un piccolo oggetto chiamato... uno Stimpak? [Mentre pronuncia l'ultima parola in modo drammatico, tira fuori uno Stimpak dalla tasca del cappotto
 e lo solleva come un meraviglioso artefatto.]}
{230}{}{[Il suo occhio si spalanca e fischia sottovoce.] Il Prescelto, eh? Beh, sono impressionato. Ora diciamo che
 veniamo agli affari. Dimmi, amico, hai mai sentito parlare di un piccolo oggetto chiamato... uno Stimpak? [Mentre pronuncia
 l'ultima parola in modo drammatico, tira fuori uno Stimpak dalla tasca del cappotto e lo solleva come un meraviglioso artefatto.]}
{240}{}{Come vuoi tu, amico. Ora veniamo agli affari, d'accordo? Hai mai sentito parlare di un piccolo oggetto chiamato...
 uno Stimpak? [Mentre pronuncia l'ultima parola in modo drammatico, tira fuori uno Stimpak dalla tasca del cappotto e lo solleva come un
 meraviglioso artefatto.]}
{241}{}{Uh, si'. In realta', sono piuttosto comuni.}
{242}{}{Certo. In realta', li accumulo. Cazzo, sono praticamente un drogato di Stimpak.}
{243}{}{[Scuoti la testa e fissi l'oggetto con stupore.] Cosa essere... stim-pak?}
{250}{}{[Ride nervosamente.] Non direi che sono *comuni*, ma sono certamente ambiti da noi gente civilizzata.
 [Guarda Krom.] E per buone ragioni. Vedi, questi piccoli oggetti contengono poteri curativi magici che ti *stupiranno*
 e ti *meraviglieranno*. Ovviamente, le parole non significano nulla senza prove, quindi permettimi di mostrarti le meraviglie dello Stimpak in azione.}
{251}{}{[Il suo occhio si indurisce per un momento, ma recupera rapidamente la compostezza e guarda Krom.] Vedi, questi piccoli oggetti
 contengono poteri curativi magici che ti *stupiranno* e ti *meraviglieranno*. Ovviamente, le parole non significano nulla senza prove, quindi permettimi
 di mostrarti le meraviglie dello Stimpak in azione.}
{252}{}{Ottima domanda amico mio! Uno Stimpak e' una delle tante grandi meraviglie lasciateci dal Vecchio Mondo. Vedi,
 questi piccoli oggetti contengono poteri curativi magici che ti *stupiranno* e ti *meraviglieranno*. Ovviamente, le parole non significano nulla senza
 prove, quindi permettimi di mostrarti le meraviglie dello Stimpak in azione.}
{253}{}{Questo dovrebbe essere interessante. Vediamo.}
{254}{}{So gia' come funzionano, li ho usati io stesso molte volte.}
{260}{}{[Vi sorride e poi si gira verso una delle sue guardie del corpo.] Warren, dammi la mano. [La guardia corruga la fronte,
 ma fa come le viene detto. Roy tira fuori rapidamente un coltello e lo fa scorrere sul dorso del braccio di Warren. Warren
 fa una smorfia di dolore ma non grida. Roy ti sorride.] Come puoi vedere, Warren ha un bel taglio brutto qui.}
{261}{}{[AVANTI]}
{262}{}{Vi assicuro amici, il taglio e il dolore di Warren sono del tutto reali. Potete vedere che non e' una lama truccata. [Passa
 il coltello a Krom, che lo guarda appena prima di annuire e restituirlo.] Ma ora, guardate. [Inietta lo Stimpak
 nel braccio di Warren. Quasi istantaneamente, il sanguinamento si ferma. Roy usa uno straccio sporco per asciugare la maggior parte del sangue, rivelando un
 taglio quasi guarito.]}
{263}{}{[AVANTI]}
{264}{}{Ora immaginate solo il vantaggio che avere degli Stimpak vi darebbe sulle tribu' rivali. E a differenza di quella
 polvere curativa che voi ragazzi amate preparare, lo Stimpak *non* causa sonnolenza. Anzi, questa piccola meraviglia e' completamente
 *priva* di effetti collaterali. Ma so cosa state pensando, devono costare una fortuna, giusto? Sbagliato. Perche' mi *piacete*,
 ve li sto praticamente regalando.}
{270}{}{[Ignorando il tuo commento, sorride a Krom, poi si gira verso una delle sue guardie del corpo.] Warren, dammi la mano.
 [La guardia corruga la fronte, ma fa come le viene detto. Roy tira fuori rapidamente un coltello e lo fa scorrere sul dorso del braccio di Warren.
 Warren fa una smorfia di dolore ma non grida.] Come puoi vedere, Warren ha un bel taglio brutto qui.}
{275}{}{Quanto?}
{276}{}{Praticamente regalandoli? Quanto stai chiedendo?}
{280}{}{Vi do questa intera cassa piena -- sono *cinquanta* Stimpak -- e tutto quello che chiedo in cambio e' una misera *ventina*
 di pelli di geco dorato. Un affare del genere non si puo' proprio rifiutare.}
{281}{}{[A Krom.] Ha ragione, e' un buon affare. Ottimo, in realta'. [A Roy.] Lo facciamo.}
{282}{}{E' un buon affare, si'. Troppo buono. Qual e' la fregatura?}
{283}{}{Ti offriremo dieci pelli di gecko dorato. Non di più.}
{284}{}{Fammi riflettere un momento.}
{285}{}{No.}
{290}{}{[Il viso di Roy si illumina.] Scelta eccellente! Affare fatto allora. [Gli oggetti vengono scambiati rapidamente, poi Roy si affretta
 verso la sua prossima tappa.]}
{300}{}{[Roy ridacchia e lancia un'occhiata alle sue guardie del corpo prima di riportare il suo occhio su di te.] Senti, un singolo Stimpak vale molto
 di piu' di una singola pelle dorata. Quindi capisci, ve li sto gia' offrendo a uno sconto assurdo. Chiedermi di piu'
 sarebbe una rapina. Venti pelli, o passo a una tribu' piu' ragionevole.}
{301}{}{D’accordo. Lo faremo.}
{302}{}{Allora è meglio che te ne vada. Niente accordo.}
{303}{}{Lasciami un momento per pensarci.}
{305}{}{[Roy corruga la fronte e si gratta il collo ispido. Alla fine emette un lungo sospiro.] Mi stai rovinando, lo sai?
 Ma come favore alla tua tribu', accettero' il tuo accordo. [Gli oggetti vengono scambiati rapidamente, poi Roy si affretta verso la sua
 prossima tappa.]}
{310}{}{[Corruga la fronte.] Non so che tipo di idiota rifiuterebbe un affare del genere. [Scuote la testa e si gira
 verso i suoi uomini.] Bene, andiamo. [Ti lancia un'occhiata.] E vaffanculo per avermi fatto perdere tempo.}
{311}{}{[Lasciali andare.]}
{312}{}{[Attacca]}
{320}{}{Nessuna fregatura, amico mio. Semplicemente ho gia' tutti gli Stimpak di cui ho bisogno, quindi mi sto liberando della scorta in eccesso.
 Le pelli dorate, d'altra parte... non ne avrei mai abbastanza. Certo, cinquanta Stimpak valgono molto di piu' di
 una misera ventina di pelli di geco dorato, ma sto sendo realistico. Non posso aspettarmi che la vostra tribu' -- abili cacciatori come sono certo che siate -- abbia un centinaio di pelli di geco dorato in giro, quindi sto facendo un'offerta piu' ragionevole. *Ecco* perche' e' un affare cosi' buono.}
{321}{}{[A Krom.] Ha ragione, e' un buon affare. Ottimo, in realta'. [A Roy.] Lo facciamo.}
{322}{}{Prima di concordare qualsiasi cosa, vorrei dare un'occhiata al resto della merce.}
{330}{}{[Il suo occhio si restringe leggermente, poi sorride.] Certo. Sono in questa cassa qui vicino a me.}
{331}{}{[FATTO]}
{340}{}{Va bene, ma non metterci troppo. Abbiamo un'altra tappa da fare prima che faccia buio.}
{350}{}{Bene, se hai finito di perdere tempo, mettiamoci in moto. Sono un uomo occupato.}
{351}{}{D’accordo. Accettiamo l’accordo.}
{352}{}{No.}
{353}{}{Devo pensarci un po’ di più.}
{354}{}{Ho un nuovo accordo per te: dacci gli stimpak e potrai tenerti la vita.}
{360}{}{Sei un tipo occupato, eh? Sei anche un bugiardo e un imbroglione.}
{361}{}{Quegli Stimpak sono falsi. Non sono altro che siringhe piene di sangue di brahmin. Stavi cercando di fregare questa tribu'.}
{362}{}{Devo pensarci un po’ di più.}
{363}{}{D’accordo. Accettiamo l’accordo.}
{370}{}{[Si agita a disagio e lancia un'occhiata nervosa a Krom.] Co-cosa stai dicendo?}
{371}{}{Quegli Stimpak sono falsi. Non sono altro che siringhe piene di sangue di brahmin. Stavi cercando di fregare questa
 tribu'.}
{372}{}{Co-- e' impossibile. Hai visto la dimostrazione. Funzionano benissimo. Non staro' qui ad ascoltare mentre cerchi
 di rovinare la mia buona reputazione.}
{373}{}{Certo, lo Stimpak che hai usato durante la dimostrazione era reale. Ma mi piacerebbe vederti riprovare usando uno degli Stimpak in quella cassa.}
{374}{}{Vaffanculo alla tua buona reputazione. Non ti servira' a nulla quando avro' finito. [Attacca.]}
{380}{}{[Sogghigna.] Va bene! Bene! Se dici che sono falsi, forse lo sono. Come faccio a saperlo? Non li ho fatti io
 quel cazzo di roba -- li ho comprati. Quindi *io* sono quello che e' stato fregato qui -- non voi. Ora, dato che non c'e' accordo, non
 sprechero' piu' il mio tempo qui. Ciao.}
{381}{}{[Lasciali andare.]}
{382}{}{[Attacca]}
{390}{}{Chi cazzo credi di essere? [Alle sue guardie del corpo.] Ammazzate questi dannati tribali!}
