{100}{}{You see a fisherman.}
{101}{}{You see a fisherwoman.}
{102}{}{Porta con se' un palo appuntito usato per la pesca.}
{103}{}{She appears to be busily cooking.}
{104}{}{Salve.}
{200}{}{Non sei il benvenuto qui.}
{201}{}{The spirits do not like you.}
{202}{}{Go away, outworlder.}
{203}{}{Why do you plague us?}
{204}{}{Benvenuto, amico.}
{205}{}{You will always be welcome here.}
{206}{}{The spirits accept you as one of us.}
{207}{}{Grazie per averci aiutato.}
{208}{}{Credevo che tutti i forestieri fossero malvagi. Non e' cosi'...}
{209}{}{Non farlo.}
{300}{}{Scusa, ma potresti farmi un piccolo favore? Sono un po' occupata qui e non so se posso lasciare questa pentola incustodita.}
{301}{}{Certo. Cosa ti serve?}
{302}{}{I'm busy too. Perhaps a little later.}
{303}{}{Ehi, la vita e' piena di problemi e non sono qui per risolverli tutti. Ciao.}
{304}{}{Sto finendo la legna per questo fuoco. Se potessi raccoglierne ancora un po' per me, lo apprezzerei davvero. Lo farei io stessa, ma temo che questa pentola traboccherebbe se la lasciassi incustodita. Sono sicura che si possano trovare dei tronchi nella foresta vicina. Tre fasci sarebbero perfetti.}
{305}{}{It would be my pleasure.}
{306}{}{In realta', per qualche strana ragione, mi capita di avere tre fasci di tronchi addosso proprio adesso. Eccoli.}
{307}{}{You'll help me? Great! Let me know when you've collected them.}
{308}{}{Ah, eccellente. Questo aiutera' a mantenere vivo il fuoco. Grazie per aver preso il tempo di aiutarmi. Non ho pero' davvero
 nulla con cui ripagarti.}
{309}{}{Your gratitude is enough. Take care.}
{310}{}{Niente con cui ripagarmi? Senti signora, avrei potuto morire in quei boschi. E' pieno di ogni tipo di creature mortali. Mi sono giocato il collo per questa cazzo di legna. Per non parlare del fatto che credo che uno dei tronchi mi abbia dato una scheggia. *Odio* le schegge.}
{311}{}{Be', tieni, prendi questi soldi. Non me ne faccio nulla qui. Grazie ancora.}
{312}{}{That's better. Bye.}
{313}{}{[FATTO]}
{314}{}{Hmmf. Go bother someone else.}
{315}{}{Did you bring the firewood?}
{316}{}{Yeah, I got it right here.}
{317}{}{No, not yet. I'll be back when I get the three bundles.}
{318}{}{Are you ready to help me?}
{319}{}{Certo. Cosa ti serve?}
{320}{}{No, I still need more time. Bye.}
{321}{}{No, e non lo faro'. Risolviti i problemi da sola. Ciao.}
{330}{}{Non te ne fai nulla? Allora perche' non me li hai dati subito? (borbotta) Stupida stronza.}
{400}{}{Whut you need?}
{401}{}{Ooo! Fare cibo preferito mio!}
{410}{}{I look.}
{411}{}{I have wood. Heh-heh... wood.}
{420}{}{That ok. Bye!}
{500}{}{Vile slaver!}
