{100}{}{You be needin' something?}
{101}{}{Yeah, I was wondering who you're guarding.}
{102}{}{Me? Oh no, I don't need anything. Bye.}
{103}{}{Who you guard?}
{104}{}{Ciao!}
{110}{}{Io sto proteggendo il capo sacro della tribu'. Colui che cammina con gli spiriti. Grande onore proteggerlo. Tenere fuori gli indesiderati, come te. Ora vattene.}
{111}{}{[FATTO]}
{120}{}{Io dico di andartene, ma tu non ascolti. Io libero gli spiriti della furia quando la gente non ascolta. Ti suggerisco di muovere i piedi. Adesso.}
{121}{}{[FATTO]}
{130}{}{Ho sentito delle buone azioni che hai fatto. Vedo che mi sbagliavo su di te. Perdonami per essere stato un uomo scortese, amico. Vai dentro e vai a vedere il grande capo. Ti sta aspettando.}
{131}{}{Ho sentito delle buone azioni che hai fatto, amico. Vai dentro e vai a vedere il grande capo. Ti sta aspettando.}
{132}{}{Grazie.}
{133}{}{Thankee.}
{140}{}{Greetings, fren.}
{141}{}{How goes things, warrior?}
{142}{}{Entra.}
{143}{}{Well met, warrior.}
{144}{}{Good to peep you again, fren.}
{260}{}{Me kill slaver!}
{300}{}{You see a strong looking tribal}
{301}{}{You see the guardian of the tribe leader.}
{302}{}{Quest'uomo ti osserva con uno sguardo penetrante. Chiaramente sta proteggendo qualcuno di importante.}
{500}{}{You always be welcome here, hero.}
