{100}{}{Beh, almeno ora ha una corda funzionante.}
{101}{}{Questo dovrebbe bastare.}
{102}{}{A questo pozzo mancano la corda e il secchio.}
{103}{}{Il pozzo e' gia' stato riparato. Ricordi?}
{104}{}{Ha la corda, ma manca il secchio.}
{200}{}{Vedi un pozzo.}
{201}{}{E' solo un pozzo.}
{202}{}{A un esame piu' attento, il pozzo non funziona. Forse puoi ripararlo.}
{203}{}{Il pozzo funziona di nuovo correttamente.}
