{100}{}{You see a small, young man dressed in rags.}
{101}{}{You see the village shaman.}
{102}{}{Questo giovane fissa l'orizzonte. Ha un'espressione tormentata sul volto.}
{103}{}{The shaman appears to be much more at ease.}
{200}{}{[Sembra immerso nei pensieri. Quando ti nota, sobbalza, poi si ricompone in fretta.] Uh, si', forestiero? Se cerchi guida spirituale, temo di non essere in grado al momento. Forse... forse un'altra volta.}
{201}{}{Eh?! Oh, sei di nuovo tu. Non dovresti avvicinarti alla gente di soppiatto cosi'. Senti, ho molte cose per la testa al momento. Forse potrei aiutarti un'altra volta.}
{202}{}{It seems like something is troubling you. Is there anything I could help you with?}
{203}{}{I'll come back later.}
{204}{}{Huh-huh! Io spaventato te! Buuu!}
{210}{}{Apprezzo l'offerta, ma... No, no, questa e' una questione personale che devo affrontare da solo.}
{211}{}{[Riflette un momento, poi sospira.] E' piuttosto imbarazzante da ammettere ma... Vedi, non ho mai davvero *creduto* negli spiriti, nell'aldila', in nulla di tutto cio'. So cosa stai pensando: a cosa serve uno sciamano che non crede? E' che, beh, o facevo questo o prendevo una lancia e andavo a caccia di gecko con i guerrieri. Ti sembro un guerriero? Aspetta, non rispondere.}
{212}{}{So you're a coward and a deceiver. You disgust me.}
{213}{}{Se non credi, allora come fai a occuparti dei bisogni spirituali del villaggio?}
{220}{}{Oh, non ti biasimo. Anzi, faccio abbastanza schifo anche a me stesso. Non so perche' abbia pensato che potessi aiutarmi. Non merito certo aiuto. Mi sono cacciato da solo in questa situazione, quindi tocca a me uscirne. Ora, se vuoi scusarmi...}
{221}{}{Aspetta un attimo, Capitano Autocommiserazione. Perche' non mi dici esattamente come pensavi che potessi aiutarti?}
{222}{}{No. Non ti scusero' affatto — ti eliminero' e purghero' il mondo della tua patetica esistenza!}
{230}{}{Be', fino a poco tempo fa ero solo il sottoposto dello sciamano del villaggio. Era facile, bastava seguire il suo esempio. Poi lui ha deciso di farsi una nuotata notturna ubriaco nella Grande Acqua Salata e, beh, mi sono ritrovato improvvisamente promosso. Pensavo non sarebbe stato cosi' male. Credevo di poter dire qualche sciocchezza mistica e rendere tutti felici. Ma no. Il giorno stesso in cui divento sciamano mi ritrovo a dover affrontare qualcosa che mi supera completamente.}
{231}{}{Cos'e' successo?}
{240}{}{C'e' un *vero* spirito perduto che vaga nei boschi a sud del villaggio! E' vero, l'ho vista con i miei occhi — una bella ragazza con lo sguardo vuoto dei morti. La vista mi ha gelato fino al midollo. Appena l'ho vista mi sono pisciato addosso e sono scappato piu' veloce che potevo. Gli altri si aspettano che io torni e la guidi nelle nebbie, ma come potrei? Sono troppo terrorizzato per avvicinarmi di nuovo.}
{241}{}{So what could I do to help?}
{242}{}{A meno che tu non abbia un paio di palle di scorta da attaccarmi addosso, non so proprio come potrei aiutare.}
{250}{}{Potresti andare tu da lei. Cercare di capire perche' resta nel mondo dei mortali. Appare nei boschi a sud durante la notte. Se riuscissi a scoprire qualcosa che possa aiutarmi, te ne sarei davvero grato.}
{251}{}{Non e' un mio problema. E' ora che tu ti faccia coraggio e faccia il tuo lavoro.}
{252}{}{I'll look into it.}
{260}{}{Did you change your mind? Will you help me with the lost spirit?}
{261}{}{Like I said before, it's not my problem. Bye.}
{262}{}{Eh, suppongo di poterci dare un'occhiata. Ti faro' sapere cosa scopro.}
{270}{}{You're back. Did you discover anything about the lost spirit?}
{271}{}{I'm working on it. I'll get back to you.}
{272}{}{Ho parlato... cioe', ho ascoltato lo spirito. Sembra sia stata tradita e uccisa dal suo amante, qualcuno di nome Thorg.}
{280}{}{Thorg?! Era lo sciamano di cui ero apprendista. Wow, sapevo che fosse un po' stronzo, ma non l'avrei mai preso per un assassino di giovani ragazze. Hmm, immagino che una coscienza sporca spieghi quella nuotata notturna ubriaca che l'ha portato alla morte. Quindi Thorg era un assassino... guarda un po'...}
{281}{}{So what now?}
{290}{}{[Sospira profondamente.] Ora immagino che tocchi a me mandarla nelle nebbie. Credo di potercela fare, ma ho bisogno che tu venga con me. Non potrei mai affrontarla da solo e nessuno degli altri villaggi verrebbe — credono che sia un cattivo presagio per un non-sciamano incontrare uno spirito perduto.}
{291}{}{Nah. Ho gia' fatto fin troppo per te. Te la caverai da solo.}
{292}{}{Don't worry, I'll help you get through this.}
{293}{}{D'accordo, lo faro'. Ma solo perche' sara' divertente vederti contorcerti dalla paura.}
{300}{}{Ti prego dimmi che ci hai ripensato. Verrai con me a occuparci dello spirito perduto, vero?}
{301}{}{Wrong. You're on your own. Bye.}
{302}{}{D'accordo, lo faro'. Ma solo perche' sara' divertente vederti contorcerti dalla paura.}
{310}{}{Oh, merda... oh, merda... No, posso farcela... Okay. Nessa?}
{311}{}{Ohhh... So cold and alone...}
{312}{}{Nessa, devi udire la mia voce. Ti sto chiamando dal mondo dei mortali.}
{313}{}{Io... io sento qualcuno! Chi c'e'? }
{314}{}{Io sono lo sciamano di questo villaggio. Devi entrare nelle nebbie. Li' troverai la pace.}
{315}{}{Si'! Si', ora vedo le nebbie. Vedo gli spiriti che mi chiamano.}
{316}{}{Va' da loro, Nessa. Entra nelle nebbie e raggiungi i tuoi antenati.}
{317}{}{I'm not alone anymore.}
{320}{}{Grazie per averci aiutato a salvare Serin. Gli ho dato alcune erbe per aiutarlo a riposare e alleviare il dolore. Se gli spiriti vogliono, dovrebbe rimettersi in piedi tra un paio di giorni.}
{330}{}{Vediamo qui... Oh, eccellente. Queste andranno bene. Tieni, prendi un po' di polvere curativa per il tuo tempo. Che i tuoi antenati ti guidino bene.}
{400}{}{Si', si', molto divertente. Ora vai. Sono occupato.}
{401}{}{::Ti giri per andartene, poi ti volti di scatto:: Buu!}
{410}{}{Ah! Dammit! Get out of here! Go!}
{411}{}{Huh-huh! Bu-bye!}
{420}{}{Te l'ho gia' detto, Sempliciotto, vai e lasciami in pace.}
{500}{}{Mi hai dato il coraggio di cui avevo bisogno per servire questo villaggio. Non so come ringraziarti abbastanza.}
{501}{}{I will forever be in your debt.}
{600}{}{Grazie per averci aiutato a salvare Serin. Gli ho dato alcune erbe per aiutarlo a riposare e alleviare il dolore. Dovrebbe rimettersi in piedi tra un paio di giorni.}
{601}{}{That's good to hear. Anything else I can do?}
{602}{}{Sono felice che Serin ce la fara'. Stammi bene.}
{610}{}{In effetti, si', credo ci sia qualcosa. Curare Serin ha consumato gran parte delle mie erbe. Se potessi portarmi cinque Radici di Xander e tre Fiori di Broc, te ne sarei molto grato.}
{611}{}{Cinque Radici di Xander e tre Fiori di Broc, capito. Tornero' quando li avro' trovati.}
{612}{}{Sembra che oggi sia il tuo giorno fortunato. Ho gia' quello che cerchi proprio qui. Prendili, sono tuoi.}
{613}{}{Mi dispiace, ma sono troppo occupato per andare a spasso nei boschi a raccogliere erbe per te.}
{614}{}{Perche' una quantita' cosi' precisa?}
{620}{}{Perche' sono molto... particolare riguardo a certe cose. E' tutta una questione di equilibrio, certi numeri... [Aggronfia la fronte.] Senti, non mi aspetto che tu capisca, ma sono fatto cosi'. Mi servono cinque Radici di Xander e tre Fiori di Broc, non di piu', non di meno. Mi aiuterai?}
{630}{}{Have you obtained the items I need?}
{631}{}{Yup, I have everything right here.}
{632}{}{I'm still looking. Bye.}
{640}{}{Vediamo qui... Oh, eccellente. Queste andranno bene. Tieni, prendi un po' di polvere curativa per il tuo tempo.}
{641}{}{Grazie. Ciao.}
{1000}{}{Hai liberato lo sciamano della tribu' dalle sue preoccupazioni.}
{2000}{}{You deliver the herbs to the Shaman.}
{3000}{}{Sapevo fin dall'inizio che eri un grande eroe... Me l'hanno detto gli spiriti.}
{3001}{}{Sono felice che le mie polveri curative ti abbiano protetto dall'Enclave.}
