{100}{}{You see a strong Tribal warrior.}
{101}{}{This tribal looks very strong, but not very bright.}
{200}{}{Halt! Wut you want?}
{201}{}{Cosa fai qui?}
{202}{}{Io sorvegliare grotta per tribu'. Io assicurarmi nessun uomo cattivo sorprendere noi.}
{203}{}{I see. Could I look around the cave?}
{204}{}{No. Io non avere il permesso di far entrare stranieri in grotta. Capo guerriero dire cosi'.}
{205}{}{Maybe later then.}
{206}{}{You again? Wut dis time?}
{207}{}{Just passing through. Keep up the good work.}
{208}{}{Il capo guerriero mi ha detto che ho il permesso di entrare nella grotta per cercare i cacciatori scomparsi.}
{209}{}{Oh, si', io non vedere quei tipi da un po'. Sperare che stiano bene. Capo guerriero dire ok per entrare? Va bene per me.}
{210}{}{Thanks. I'll let you know if I need anything.}
{300}{}{Ehi, perche' tu correre? Tu trovare qualcosa?}
{301}{}{Si', ho trovato i cacciatori scomparsi. Uno di loro e' morto ma l'altro e' gravemente ferito. Ho bisogno del tuo aiuto
 per portarlo fuori e portarlo dallo Sciamano. Io andare ad aspettare con lo Sciamano mentre tu salvare il cacciatore.}
{302}{}{Membro tribu' avere bisogno di aiuto? Io dover aiutare loro. Nella grotta? Io venire!}
{303}{}{[FATTO]}
{400}{}{Grazie per aiutare Serin. Lui essere buon guerriero. Tu essere amico della tribu'.}
{401}{}{Thanks. Well, I must be going now.}
{402}{}{Hello friend. Wut you need?}
{403}{}{Nothing. Just passing through. Take care.}
{500}{}{You hero! I hug!}
{501}{}{Insegnare a me essere eroe, come te!}
