{100}{}{You see a tribal woman.}
{101}{}{You see Kurisu, Sulik's sister.}
{102}{}{You see a young, full figured tribal woman with several piercings and tattoos.}
{150}{}{[FINE]}
{200}{}{Sulik! [Si blocca e inizia a sussurrare.] Gli spiriti stanno scherzando, o sei davvero tu, fratello?}
{201}{}{Io? No, sono il Prescelto. Devi stare pensando al vecchio naso d'ossa qui.}
{202}{}{[Sulik corre verso il portone e afferra le mani tese di sua sorella. Ti giri per dare un po' di privacy alla loro riunione emozionata. Pochi istanti dopo, un ramoscello si spezza fuori dall'edificio. Sulik lascia la sorella e afferra la sua arma mentre guarda verso la porta. Non arriva piu' alcun suono da fuori.]}
{203}{}{[AVANTI]}
{204}{}{[La sorella di Sulik si gira verso di te.] Gli spiriti delle ossa dicono che tu stai guidando Sulik. Mi chiamo Kurisu, ma ora non e' il momento per i saluti come si deve. Per favore, devi tirarci fuori da questa gabbia e lontano da quegli uomini malvagi dominati dagli spiriti della lussuria. [Sogghigna e sputa nella terra.] Cani luridi non poseranno piu' le mani su di noi. [Sentendo questo, gli occhi di Sulik si spalancano mentre il suo volto si contorce di rabbia. Afferra la sua arma.]}
{205}{}{Aspetta, Sulik, qui siamo in inferiorita'. Fammi vedere se riesco a scassinare questa porta e possiamo sgattaiolare fuori di qui.}
{206}{}{Aspetta, Sulik, qui siamo in inferiorita'. Ho la chiave di questa porta. Facciamo silenzio e sgattaioliamo fuori di qui.}
{207}{}{[Annuisci a Sulik] Questi bastardi pagheranno. Carica l'arma, vecchio amico.}
{208}{}{[Passano alcuni minuti e finalmente senti un clic dalla serratura. La porta si spalanca.]}
{209}{}{[Ti giri verso Kurisu.] Va bene, stai vicina e tieni la testa bassa. [Agli altri schiavi.] State zitti e dirigetevi verso il bosco.}
{210}{}{[Passano alcuni minuti e non riesci ad aprire la porta.]}
{211}{}{Deve esserci un altro modo per aprire questa porta. Fammi vedere se riesco a procurarmi una chiave in qualche modo. Aspettate qui, tornero' a prendervi.}
{212}{}{Va bene, Sulik, e' il momento del tuo piano. E' ora di far fuori la spazzatura.}
{213}{}{[Infili la chiave nella serratura e apri il cancello, che stride mentre si apre.]}
{214}{}{Hai avuto fortuna, amico? Per favore, fai presto.}
{215}{}{Not yet. I'm still working on it.}
{216}{}{I got the keys. Time to get you out of here.}
{217}{}{Perche' c'e' cosi' tanto trambusto la fuori? Ah, sento che molti sono andati a raggiungere gli spiriti. Chi e'... Sulik? Gli spiriti stanno scherzando, o sei davvero tu, fratello?}
{218}{}{Perche' c'e' cosi' tanto trambusto la fuori? Ah, sento che molti sono andati a raggiungere gli spiriti. E sento che sei tu a mandarli. Di cosa hai bisogno, Fabbricatore-di-fantasmi?}
{219}{}{Sono venuto a salvarvi.}
{221}{}{Lode agli spiriti! Per favore, devi tirarci fuori da questa gabbia. Lontano da questo luogo malvagio.}
{222}{}{Gli spiriti ti lodano! Ora devo andare e tornare dal mio popolo. Sono mancata per molto tempo. Per favore, passa dal mio villaggio. E' vicino alla Grande Acqua Salata, qualche giorno a sud-ovest da qui. Grazie, amico.}
{223}{}{[Sulik corre verso il portone e afferra le mani tese di sua sorella. Ti giri per dare un po' di privacy alla loro riunione emozionata. Pochi istanti dopo, sua sorella si gira verso di te.] Gli spiriti delle ossa dicono che tu stai guidando Sulik. Mi chiamo Kurisu, ma ora non e' il momento per i saluti come si deve. Gli Schiavisti, sono morti, vero?}
{224}{}{Yes, the slavers are dead.}
{225}{}{Lode agli spiriti! Per favore, apri questa porta. Siamo impazienti di andarcene da questo luogo malvagio.}
{226}{}{Don't worry. I got a key.}
{227}{}{Alright, let me try and lockpick this door.}
{400}{}{Let's keep moving.}
{401}{}{Please, I wantin' to be home.}
{410}{}{[Ti giri verso Kurisu.] Aspetta, non voglio andarmene finche' non libero gli schiavi nelle altre gabbie. 
Aspettate qui finche' non libero tutti da questo campo. [Agli altri schiavi.] State zitti e dirigetevi verso il bosco. Pensero' io alle guardie.}
{500}{}{Se mi stai scegliendo per un giaciglio, faresti meglio ad aspettarti una lotta -- aspetta, tu non hai il marchio del demone sulla testa. Chi sei?}
{501}{}{I'm the "Chosen One" and who are you?}
{502}{}{Il mio nome e' }
{503}{}{. Chi sei?}
{510}{}{Il mio nome e' Kurisu. Vengo da una tribu' a sud-ovest, vicino alla Grande Acqua Salata. Gli schiavisti mi hanno presa. Hanno preso anche altri, ma loro sono stati mandati via. Dicono che non hanno finito con me. Mi tengono qui per il loro piacere malvagio. Per favore, devi tirarci fuori da questa gabbia e lontano da quegli uomini malvagi.}
{511}{}{Non preoccuparti, sono qui per tirarti fuori. Ho una chiave e il permesso di portarvi via da qui.}
{512}{}{Alright, let me try and lockpick this door.}
{530}{}{E' sicuro ora? Hai mandato gli schiavisti dagli spiriti?}
{531}{}{Yes, it's safe. We can go to your village now.}
{532}{}{Si', ma lasciami liberare prima tutti gli schiavi qui, prima di andare.}
{533}{}{No, not yet. I'll be back when it's safe.}
{600}{}{Lode agli spiriti, siamo finalmente a casa! Grazie mille, amico.}
{601}{}{You're welcome. So, how exactly were you captured?}
{602}{}{Stavo commerciando in un villaggio vicino. Sono arrivati gli schiavisti. Molto spargimento di sangue e caos. Poi tutto e' diventato buio. Mi sono svegliata in una gabbia affollata che puzzava di merda. Presto mi hanno spostata in una gabbia piu' piccola, con quelli che gli piace tenere. Ho visto molti schiavi andare e venire. Triste vedere le persone trattate come bestiame.}
{603}{}{Si', la schiavitu' e' davvero una cosa orribile. Mi dispiace che tu abbia dovuto passare tutto questo, Kurisu. Allora, cosa farai ora?}
{604}{}{Gli schiavisti mi hanno ferita, ma sono lontana dall'essere spezzata. Gli spiriti ti hanno guidato per assicurare la mia liberta'. Chiaramente gli spiriti stanno preparando qualcosa di grande per me. Gli spiriti hanno grandi piani anche per te. E per mio fratello Sulik. Manchera' molto, ma gli spiriti dicono che il suo posto e' camminare accanto a te. Diamine, perfino Nonno Ossa ti apprezza, quindi so che Sulik e' in buone mani. Abbi cura di te.}
{605}{}{Thank you, Kurisu, see you around.}
{606}{}{Gli schiavisti mi hanno ferita, ma sono lontana dall'essere spezzata. Gli spiriti ti hanno guidato per assicurare la mia liberta'. Chiaramente gli spiriti stanno preparando qualcosa di grande per me. Presto, credo che andro' a cercare mio fratello. Conoscendo Sulik, probabilmente si e' cacciato nei guai cercando di venire ad aiutarmi. Ora, forse saro' io ad aiutare lui.}
{607}{}{In realta', credo di aver visto tuo fratello. Faccia piena di tatuaggi e un grande osso nel naso, giusto?}
{608}{}{Quello e' proprio Sulik! E anche Nonno Ossa! Per favore, potresti riportare Sulik a casa? Mi manca cosi' tanto.}
{609}{}{Nessun problema, lo portero' qui. Ci vediamo, Kurisu.}
{610}{}{I don't think I can do that. You see, Sulik is dead.}
{611}{}{Sulik... morto? Davvero, questo e' un giorno oscuro. So che ora e' con Nonno Ossa, ma Sulik... manchera' moltissimo. [Distoglie lo sguardo mentre gli occhi le si riempiono di lacrime.] Per favore... ho bisogno di stare sola ora. Grazie... per avermi riportata a casa.}
{650}{}{Ciao, amico. Qualche fo-- Sulik!}
{651}{}{[AVANTI]}
{652}{}{[Kurisu corre verso Sulik, che la solleva in un abbraccio. Ti giri per dare loro un po' di privacy durante la riunione emozionata. Dopo alcuni istanti, Kurisu si gira verso di te con un sorriso mentre si asciuga le lacrime.] Grazie, amico, per aver trovato mio fratello. Gli spiriti hanno grandi piani per te e per Sulik. Manchera' molto, ma gli spiriti dicono che il suo posto e' camminare accanto a te. Diamine, perfino Nonno Ossa ti apprezza, quindi so che Sulik e' in buone mani. Abbi cura di te.}
{653}{}{Ciao, amico. Hai avuto fortuna a trovare mio fratello Sulik?}
{654}{}{No, still looking. I'll be back when I find him.}
{700}{}{Thanks again, fren. May the spirits bless you.}
{701}{}{Mio fratello Sulik manchera' moltissimo.}
{800}{}{Evil spirits walk with you! Be away!}
{810}{}{Torna dentro l'edificio, Kurisu! Me ne occupo io.}
{820}{}{Please, don't be letting them hurt us.}
{900}{}{Io? No, io Prescelto. Tu parlare con Sulik?}
{910}{}{Yes, bad men dead.}
{920}{}{I got key.}
{921}{}{I try lockpick.}
{922}{}{[Annuisci a Sulik] Ora combattiamo gli uomini cattivi.}
{923}{}{I still work.}
{930}{}{[Ti giri verso Kurisu.] Io proteggere te. [Agli altri schiavi.] Andate a casa.}
{940}{}{Scasso non funziona. Io cercare chiave. Tu aspettare.}
{941}{}{Grimaldello no funziona. [Ti giri verso Sulik] Noi combattere uomini cattivi adesso.}
{950}{}{I "Chosen One". Who yoo?}
{951}{}{Me }
{952}{}{. Who yoo?}
{960}{}{It safe. We go home.}
{961}{}{It no safe. More bad men to kill.}
{970}{}{You welcome. How they get yoo?}
{971}{}{Si', uomini cattivi non buoni. Tu cosa fare adesso?}
{972}{}{Thankeee. Bye!}
{973}{}{Io conoscere Sulik. Sulik amico mio. Lui parlare come me. Lui parlare con osso nel naso.}
{974}{}{I bring him. He miss yoo.}
{975}{}{Me sorry. He dead.}
{976}{}{I still look.}
{1000}{}{Riunisci Sulik con sua sorella.}
{2000}{}{I *knew* the bonespirit's had big plans for you.}
{2001}{}{Prima tu salvare me. Poi tu salvare il mondo. Tu essere proprio l'eroe.}
{2002}{}{You don't be needin' Sulik, no more, do you?}
