{100}{}{Sei entrato in una zona densamente boscosa. C'e' un sentiero stretto che porta a nord.}
{101}{}{Entri in Umbra Shore, casa della Tribu' Umbra. Noti molte differenze nell'aspetto dei abitanti del villaggio e delle tende, come se non tutti venissero dallo stesso posto.}
{102}{}{Hai scoperto cosa è successo ai cacciatori scomparsi.}
{200}{}{Hai salvato la sorella di Sulik dagli schiavisti.}
