{100}{}{Mentre i tuoi occhi si adattano all'oscurita' della grotta, vedi quello che sembra essere il risultato di un crollo. Un guerriero indifeso giace a terra, lottando per liberare la gamba da una grande roccia mentre un geco dorato si lancia verso di lui. Il corpo di un altro guerriero giace immobile nelle vicinanze.}
{101}{}{Irrompi dentro e cerca di salvare il tribale.}
{102}{}{Stand there and watch what happens.}
{200}{}{Se io dover morire, allora io morire come vero guerriero.}
{201}{}{Ahh!}
