{100}{}{Ti serve qualcosa?}
{101}{}{Sì, mi chiedevo chi stai sorvegliando.}
{102}{}{Io? Oh no, non mi serve niente. Addio.}
{103}{}{Chi tu guarda?}
{104}{}{Ciao!}
{110}{}{Io sto proteggendo il capo sacro della tribu'. Colui che cammina con gli spiriti. Grande onore proteggerlo. Tenere fuori gli indesiderati, come te. Ora vattene.}
{111}{}{[FATTO]}
{120}{}{Io dico di andartene, ma tu non ascolti. Io libero gli spiriti della furia quando la gente non ascolta. Ti suggerisco di muovere i piedi. Adesso.}
{121}{}{[FATTO]}
{130}{}{Ho sentito delle buone azioni che hai fatto. Vedo che mi sbagliavo su di te. Perdonami per essere stato un uomo scortese, amico. Vai dentro e vai a vedere il grande capo. Ti sta aspettando.}
{131}{}{Ho sentito delle buone azioni che hai fatto, amico. Vai dentro e vai a vedere il grande capo. Ti sta aspettando.}
{132}{}{Grazie.}
{133}{}{Grezieee}
{140}{}{Saluti, amico.}
{141}{}{Come vanno le cose, guerriero?}
{142}{}{Entra.}
{143}{}{Bentrovato, guerriero.}
{144}{}{Bello rivederti, amico.}
{260}{}{Me uccide schiavista!}
{300}{}{Vedi un tribale dall’aspetto robusto.}
{301}{}{Vedi la guardia del capo tribù.}
{302}{}{Quest'uomo ti osserva con uno sguardo penetrante. Chiaramente sta proteggendo qualcuno di importante.}
{500}{}{Sarai sempre il benvenuto qui, eroe.}
