{100}{}{Beh, almeno ora ha una corda funzionante.}
{101}{}{Questo dovrebbe bastare.}
{102}{}{A questo pozzo mancano la corda e il secchio.}
{103}{}{Il pozzo è già stato riparato. Ricordi?}
{104}{}{Ha la corda, ma manca il secchio.}
{200}{}{Vedi un pozzo.}
{201}{}{It's just a well.}
{202}{}{Upon closer inspection you see that the well is not working. Perhaps you can fix it.}
{203}{}{The well is working fine again.}
