{100}{}{}
{101}{}{You see a member of the tribe.}
{102}{}{You see Marli.}
{103}{}{You see a warrior with a scowl on his face.}
{110}{}{Vattene. Sto cercando consiglio dagli spiriti e non ti gradiscono, forestiero. Se devi parlarmi, fallo un'altra volta.}
{111}{}{No need to be so rude. Bye.}
{112}{}{Hmph. Non ti ho chiesto aiuto, forestiero. Avrei potuto sistemare il pozzo da solo.}
{113}{}{Right. No thanks required.}
{114}{}{Whatever. Way to be ungrateful.}
{120}{}{Cosa vuoi?}
{121}{}{I see you're having some trouble with that well. What's wrong, exactly?}
{130}{}{Cosa c'e'? Ho fatto cadere la corda, ecco cosa c'e'. [Si muove a disagio.] Stavo fissando una corda nuova al pozzo e poi ho alzato lo sguardo e ho visto una bella giovane che si stiracchiava al sole. Gli spiriti della lussuria mi hanno distratto e la corda mi e' scivolata dalle mani e... E a te cosa importa, forestiero? A meno che tu non abbia una corda nuova per me, mi stai solo facendo perdere tempo.}
{131}{}{I don't have a rope on me, but I'll see if I can come up with one. I'll get back to you.}
{132}{}{In effetti ce l'ho. Vedro' se riesco a sistemarti il pozzo.}
{133}{}{No, temo che dovrai semplicemente ammettere agli altri cosa e' successo. Cerca di tenere a bada gli spiriti della lussuria la prossima volta. Addio.}
{140}{}{So is the well fixed yet, or what?}
{141}{}{No, not yet I'm afraid.}
{142}{}{Ti sembra sistemato? Sei proprio accanto a quella dannata cosa. Idiota.}
{150}{}{So, have you fixed up the well yet?}
{151}{}{Sure, I got the rope in place now. See?}
{160}{}{[Dà un'occhiata al pozzo, poi sogghigna.] A cosa serve una corda senza un secchio attaccato? O voi forestieri bevete leccando l'acqua da una corda bagnata? [Scuote la testa e borbotta qualcosa.] Attacca il secchio, e vedro' di darti una ricompensa.}
{161}{}{Right.}
{162}{}{Perche' non attacchi *tu* il secchio, e io vedo se riesco a trattenermi dal prenderti a calci il culo.}
{170}{}{Did you attach the bucket?}
{171}{}{No, non ancora.}
{172}{}{Ti *sembra* che abbia attaccato il secchio?}
{180}{}{Quindi il pozzo e' sistemato, giusto? Con il secchio attaccato e tutto quanto?}
{181}{}{Yes, it's all done.}
{182}{}{...}
{190}{}{[L'angolo della sua bocca si solleva in un mezzo sorriso.] Ah, immagino che voi forestieri non siate poi tutti cosi' male. Tieni, prendi questi soldi. Gli spiriti mi dicono che ti serviranno piu' che a me.}
{191}{}{Grazie.}
{200}{}{May your ancestors guide you well.}
{201}{}{Grazie dell'aiuto.}
{202}{}{Nice to be seeing you again.}
{210}{}{You won't take us alive, slaver!}
{300}{}{D'accordo, calma i tuoi spiriti di rabbia. Lo faro' io. [Borbottando.] Forestiero pazzo...}
{301}{}{[FATTO]}
{310}{}{[Socchiude gli occhi verso di te, poi guarda il pozzo.] No.}
{311}{}{Then no, I guess I didn't attach it yet.}
{320}{}{Ehi, mi hai sentito? Ho chiesto se il pozzo e' sistemato.}
{321}{}{... [Sospiri, poi indichi il pozzo.]}
{330}{}{[Si gira e guarda il pozzo, poi torna a guardarti.] Si', ora sembra a posto. Perche' non l'hai detto subito? Tieni, prendi questi soldi. Gli spiriti mi dicono che ti serviranno piu' che a me.}
{331}{}{... [You take the money and walk away.]}
{400}{}{[Mentre stai per andartene, Marli ti osserva attentamente e gli si illuminano gli occhi.] Ah! Vedo che hai una mitraglietta. [Guarda l'arma con desiderio.] Ne avevamo una, una volta, ma Sulik la teneva sempre per se'. Si e' persa in una battaglia. Un vero peccato. La mia magia sarebbe terribilmente potente se avessi un ruba-anime come quello.}
{401}{}{Se vuoi questa, puoi prenderla. Sono sicuro che ne trovero' un'altra. [Dai la mitraglietta a Marli.]}
{402}{}{Prendila e basta. Non la voglio piu' dopo come la stai guardando. [Dai la mitraglietta a Marli.]}
{403}{}{Si', ci credo. Comunque, io e il mio ruba-anime ce ne andiamo altrove ora.}
{404}{}{You keep your magic to yourself, pal. Bye.}
{410}{}{[Sorride come un maniaco mentre osserva l'arma.] Oh, sei un buon amico per Marli, forestiero. Tieni, stavo conservando questa dolce acqua frizzante, ma credo che dovresti averla tu. [Ti porge una Nuka-Cola.] Ora vado a sputare morte infuocata su qualche gecko. [Corre verso il terreno di caccia.]}
{411}{}{La mia magia ora essere terribile forte!}
{1000}{}{You fix the Tribe's well.}
{2000}{}{Sorry if I was a jerk to you, hero.}
{2001}{}{Sorry, I lost your sub-machine gun. That gecko be a fierce one.}
