{100}{}{Vedi un guerriero tribale forte.}
{101}{}{Questo tribale sembra molto forte, ma non molto sveglio.}
{200}{}{Alt! Cosa tu volere?}
{201}{}{Cosa fai qui?}
{202}{}{Io sorvegliare grotta per tribu'. Io assicurarmi nessun uomo cattivo sorprendere noi.}
{203}{}{Capisco. Posso dare un’occhiata alla caverna?}
{204}{}{No. Io non avere il permesso di far entrare stranieri in grotta. Capo guerriero dire cosi'.}
{205}{}{Forse più tardi, allora.}
{206}{}{Ancora tu? Cosa vuoi stavolta?}
{207}{}{Sono solo di passaggio. Continua così.}
{208}{}{Il capo guerriero mi ha detto che ho il permesso di entrare nella grotta per cercare i cacciatori scomparsi.}
{209}{}{Oh, si', io non vedere quei tipi da un po'. Sperare che stiano bene. Capo guerriero dire ok per entrare? Va bene per me.}
{210}{}{Grazie. Ti farò sapere se mi serve qualcosa.}
{300}{}{Ehi, perche' tu correre? Tu trovare qualcosa?}
{301}{}{Si', ho trovato i cacciatori scomparsi. Uno di loro e' morto ma l'altro e' gravemente ferito. Ho bisogno del tuo aiuto
 per portarlo fuori e portarlo dallo Sciamano. Io andare ad aspettare con lo Sciamano mentre tu salvare il cacciatore.}
{302}{}{Membro tribu' avere bisogno di aiuto? Io dover aiutare loro. Nella grotta? Io venire!}
{303}{}{[FATTO]}
{400}{}{Grazie per aiutare Serin. Lui essere buon guerriero. Tu essere amico della tribu'.}
{401}{}{Grazie. Ora devo andare.}
{402}{}{Ciao amico. Cosa ti serve?}
{403}{}{Niente. Ero solo di passaggio. Stammi bene.}
{500}{}{Tu eroe! Me abbraccia!}
{501}{}{Insegnare a me essere eroe, come te!}
