{100}{}{Vedi un tribale.}
{101}{}{Vedi un membro della tribù.}
{102}{}{Uno dei pochi membri rimasti della tribù.}
{200}{}{Non sei il benvenuto qui.}
{201}{}{Gli spiriti non ti vedono di buon occhio.}
{202}{}{Vattene, straniero.}
{203}{}{Perché ci tormenti?}
{204}{}{Benvenuto, guerriero.}
{205}{}{Sarai sempre il benvenuto qui.}
{206}{}{Gli spiriti ti accettano come uno di noi.}
{207}{}{Grazie per averci aiutato.}
{208}{}{Credevo che tutti i forestieri fossero malvagi. Non e' cosi'...}
{209}{}{Non farlo.}
{210}{}{Gli schiavisti non sono i benvenuti qui!}
{300}{}{Siamo onorati di averti qui, eroe.}
{301}{}{La tua sconfitta dell'Enclave sara' ricordata nelle leggende. I tuoi antenati sono fieri di te.}
