{100}{}{Vedi un guerriero.}
{101}{}{You see Serin.}
{102}{}{He looks badly injured and has a broken leg.}
{103}{}{Vedi Serin. Sembra gravemente ferito e ha una gamba rotta.}
{104}{}{You see Serin. His leg is bandaged and he is hobbling.}
{105}{}{You see Serin. He looks better and he is in a deep sleep.}
{106}{}{You see Serin. He looks like he has recovered nicely.}
{200}{}{*ugh* Muori demonio!! Non riuscirai a-}
{201}{}{Calm down. You're safe now. The gecko is dead.}
{202}{}{Cosa!? Oh, grazie agli spiriti, amico. Temevo di essere spacciato.}
{203}{}{What happened here?}
{204}{}{Jerem e io uscire per caccia settimanale. Prendere passaggio grotta verso campo dove molti geco girare. Caccia andare male. Dover scappare. Troppi geco con spiriti di furia. Noi entrare grotta. Cominciare urlare per aiuto. [Si ferma un momento e fa una smorfia di dolore mentre cerca di massaggiarsi la gamba.]}
{205}{}{Please go on.}
{206}{}{Passaggio gia' essere sull'orlo della rovina. Acqua filtrare da ruscello in alto. Un passo mortale, ma essere grande scorciatoia verso campi. Non piu'. Vedere, noi urlare come sciocchi e soffitto crollare su di noi.}
{207}{}{[Continua]}
{208}{}{Povero Jerem. Io vedere grande roccia schiacciare lui come insetto. Le grandi rocce mancare me, ma morso del Geco no. Proprio quando io pensare di essere al sicuro, un geco venire dal nulla e mordere forte la gamba. Portare me a terra. Non avere lancia, pensare il Geco mangiare me di sicuro. Ma gli spiriti avere altri piani. Portare una grande roccia finale sulla testa del geco. Schiacciarla piatta. Ma schiacciare anche gamba mia.}
{209}{}{[Continua]}
{210}{}{Cosi' io essere bloccato a terra, senza lancia. Improvvisamente, io sentire qualcosa venire verso me dal buio. Si avvicinare, e io vedere essere un grande geco arrabbiato. Le rocce cadute solo renderlo piu' incazzato. Ecco quando tu arrivare, amico. Davvero, io essere in debito con te.}
{211}{}{Wow, che storia. Sembra che tu sia molto fortunato ad essere vivo. Come sta la gamba?}
{212}{}{Non bene, amico. Sembra che roccia essere piu' forte di osso mia gamba. Dubito io alzarmi e camminare via presto.}
{213}{}{Non preoccuparti, sono un medico esperto. Fammi dare un'occhiata alla tua gamba e vedo cosa posso fare.}
{214}{}{Non preoccuparti, non dovrei avere problemi a portarti fuori di qui. Poi possiamo far dare uno sciamano un'occhiata alla tua gamba.}
{215}{}{Probabilmente dovremmo far venire un professionista qui a darci un'occhiata. Vado subito a cercare aiuto. La grotta sembra vuota adesso, quindi dovresti essere al sicuro qui fino al mio ritorno.}
{216}{}{Hmm... Non credo di essere abbastanza forte da portarti fuori di qui, ma scommetto che Sulik potrebbe farcela. [a Sulik] Portiamo fuori questo tizio.}
{217}{}{Hmm... Non credo di essere abbastanza forte da portarti fuori di qui, ma scommetto che Marcus potrebbe farcela. [a Marcus] Portiamo fuori questo tizio.}
{218}{}{[Esamini la gamba del guerriero. E' gravemente lacerata e l'osso e' esposto in alcuni punti. Con abilita' rimetti l'osso in posizione, fermi il sanguinamento, metti un'ingessatura alla gamba e ti metti al lavoro per guarirla.]}
{219}{}{[Dopo circa 15 minuti di lavoro estenuante, la gamba e' in condizioni molto migliori. Sembra che quest'uomo sara' in grado di camminare di nuovo.]}
{220}{}{Bene, dovrebbe bastare. Avrai bisogno di un paio di giorni di riposo per guarire completamente. Non mettere troppo peso sulla gamba in questo periodo e dovresti stare bene.}
{221}{}{Spiriti sacri possedere te, amico! Io ringraziarti. Ora io zoppicare verso lo sciamano. Prendere buona erba per calmare dolore. Ci vediamo al villaggio, amico.}
{222}{}{[Fatto]}
{300}{}{I thank you, fren. Be seeing you back at the village.}
{400}{}{Grazie tanto, amico. Davvero, tu essere benedetto dagli spiriti.}
{500}{}{zzzZZzzz...}
{501}{}{...zzZZZZzz... zzz...}
{600}{}{You heal Serin's leg.}
{700}{}{He needs more help than I can offer. I better get going.}
{1000}{}{Good to be peeping you, hero.}
{1001}{}{I never forget what you done for me, hero.}
