{100}{}{You see a warrior.}
{101}{}{You see Krom, the Head Warrior of the tribe.}
{102}{}{Vedi un guerriero gigantesco e muscoloso. La sua pelle color bronzo porta le cicatrici di innumerevoli battaglie.}
{200}{}{[Questo gigante abbronzato dal sole sembra avere muscoli scolpiti nel granito. Sotto una criniera di capelli neri,
 i suoi occhi blu ardenti ti trapassano.] Io sono Krom, il capo guerriero di questa tribu'. Chi sei, e cosa ti porta qui?}
{201}{}{[Questo gigante abbronzato dal sole sembra avere muscoli scolpiti nel granito. Sotto una criniera di capelli neri,
 i suoi occhi blu ardenti scorrono senza pudore sul tuo corpo.] Io sono Krom, il capo guerriero di questa tribu'. Per gli Dei, ragazza,
 la tua bellezza potrebbe far impazzire un uomo.}
{202}{}{Sono }
{203}{}{, e sono in una sacra missione per salvare il mio villaggio, Arroyo, da una distruzione certa.}
{204}{}{Sono }
{205}{}{, e sono stato in una sacra missione per salvare il mio villaggio, Arroyo, da una distruzione certa. Ma ho trovato cio' che mi serviva.}
{206}{}{I'm a simple wanderer -- nothing more. I'll be moving on now.}
{207}{}{[Smile.] Thank you, Krom.}
{208}{}{Grazie, ma perche' non tieni gli occhi puntati qui su. Va bene, omone?}
{209}{}{Risparmiami i complimenti, va bene, lurido? Non ho alcuna intenzione di andare a letto con te. Diamine, non voglio nemmeno parlare
 con te. Addio.}
{210}{}{Arroyo, si', una delle tribu' del nord. Ma che dire di questa "distruzione certa" di cui parli? Il tuo villaggio e' ben
 fortificato da un grande canyon, no? Sicuramente potete difendervi da tribu' nemiche o predoni.}
{211}{}{Non e' una forza esterna a minacciarci. La mia tribu' sta morendo dall'interno. Abbiamo sofferto una terribile siccita'
 e sembra che il mio villaggio sia destinato a inaridire e morire a meno che io non trovi il sacro GECK in tempo.}
{212}{}{Non e' una forza esterna a minacciarci. La mia tribu' sta morendo dall'interno. Abbiamo sofferto una terribile siccita'
 e sembra che il mio villaggio sia destinato a inaridire e morire a meno che non utilizziamo il GECK che ho trovato.}
{220}{}{Ah, un Garden of Eden Creation Kit, ne ho letto nei vecchi testi. [Sorride cupamente.] E' triste che la tua tribu' sia caduta in tempi difficili, ma e' sciocco riporre tutte le speranze nel trovare qualche "artefatto magico"
 di prima del Grande Silenzio. Sei sicuro che la tua tribu' non ti abbia mandato in una missione inutile solo per liberarsi di te?}
{221}{}{Ah, un Garden of Eden Creation Kit, ne ho letto nei vecchi testi. [Sorride cupamente.] E' triste che la tua tribu' sia caduta in tempi difficili, ma e' sciocco riporre tutte le speranze nel trovare qualche "artefatto magico"
 di prima del Grande Silenzio. Come puoi essere cosi' sicuro che il dispositivo che hai trovato salvera' la tua gente?}
{222}{}{Certo che no. Ho superato con successo il Tempio delle Prove e ottenuto il titolo di prescelto, altamente rispettato.
 Ecco perche' mi e' stata affidata questa missione — perche' ho dimostrato di essere il piu' qualificato. Ora, cosa hai letto riguardo al
 GECK?}
{223}{}{Stai cercando di insultarmi? Sappi che sono il Prescelto. Chiedi scusa, o ti metto al tuo posto.}
{224}{}{Non lo so con certezza, ma ho rischiato troppo per fermarmi ora. Faro' tutto cio' che serve per salvare la mia tribu',
 per quanto folle o pericoloso possa sembrare.}
{230}{}{[Scrolla le sue possenti spalle con disprezzo.] Solo un altro dei gingilli scientifici degli Antichi, creato per
 sostituire il metodo collaudato dell'Uomo che lotta contro la Terra spietata — forgiando la propria esistenza con sudore
 e sangue. Ma se credi davvero che quel dispositivo sia la tua unica speranza, allora ti suggerisco di cercare i Vault sotterranei degli Antichi.
 Ho viaggiato ovunque, ma non ne ho mai trovato uno. Anche se, a dire il vero, non li stavo cercando.}
{231}{}{La mia Anziana e' certa che trovare il GECK sia la nostra migliore possibilita'. Questo e' il compito che mi e' stato affidato,
 quindi e' cio' che intendo fare. Comunque, grazie del consiglio.}
{232}{}{Cercare un Vault, dici? Wow, che *ottimo* consiglio, se solo lo avessi saputo prima. Grazie mille del suggerimento,
 omone.}
{240}{}{[Ride fragorosamente, poi, con una velocita' impossibile per un uomo della sua mole, solleva la lancia
 e assume una posizione di combattimento.] Il Prescelto, eh? Se uno sciocco come te e' il meglio che la tua tribu' puo' offrire, allora la loro fine e' inevitabile.
 Ora, impugna la tua arma cosi' posso spaccarti il cranio, oppure sparisci dalla mia vista.}
{241}{}{[Ride fragorosamente, poi ti da' una pacca sul sedere con una mano che sembra capace di frantumare massi.] Hai un bel fuoco dentro, ragazza. Mi piace.
 Forse potremmo metterlo a buon uso mentre sei qui. Che ne dici?}
{242}{}{Alright, fine, I'm going.}
{243}{}{No one threatens me, asshole!}
{244}{}{To hell with you. I'm leaving. Bye.}
{245}{}{Nessuno mi tocca, stronzo! [Attacca.]}
{246}{}{If you keep your hands to yourself, then I just *might* consider helping.}
{247}{}{Dipende. [Sorriso seducente.] Cosa avevi in mente, omone? [Occhiolino.]}
{250}{}{Sono ben versato nell'arte del sarcasmo. Porta la tua lingua furba altrove prima che te la strappi dalla bocca.}
{251}{}{Alright, fine, I'm going.}
{252}{}{No one threatens me, asshole!}
{260}{}{Sei un tipo testardo. Per gli Dei, potrei anche iniziare a piacerti. [Sorride e ti da' una pacca sulla schiena con una
 mano che sembra capace di frantumare massi.] Finche' sei qui, forse potresti aiutarci con un paio di cose. Che ne dici?}
{261}{}{Sei una tipa testarda. Per gli Dei, potrei anche iniziare a piacerti, ragazza. [Sorride e ti da' una pacca sul sedere
 con una mano che sembra capace di frantumare massi.] Finche' sei qui, forse potresti aiutarci con un paio di cose.
 Che ne dici?}
{262}{}{Certo, credo di poter dare una mano prima di andare. Cosa vorresti che facessi?}
{263}{}{Mi dispiace, ma non ho proprio il tempo. Anzi, dovrei davvero rimettermi in cammino ora. Addio.}
{264}{}{Certo, credo di poter dare una mano prima di andare. Cosa vorresti che facessi?}
{265}{}{If you keep your hands to yourself, then I just *might* consider helping.}
{266}{}{Mi dispiace, ma non ho proprio il tempo. Anzi, dovrei davvero rimettermi in cammino ora. Addio.}
{267}{}{Nessuno mi tocca, stronzo! [Attacca.]}
{268}{}{Dipende. [Sorriso seducente.] Cosa avevi in mente, omone? [Occhiolino.]}
{270}{}{[Sorride in modo lupesco. Nonostante l'aspetto segnato e ruvido, possiede una rude avvenenza.] Dimmi, ragazza,
 qual e' il tuo nome, e cosa ti porta nel nostro villaggio?}
{280}{}{[Volentieri. [Ti guarda negli occhi e sorride in modo lupesco. Nonostante l'aspetto segnato e ruvido, possiede una rude avvenenza.]
 Dimmi, ragazza, qual e' il tuo nome, e cosa ti porta nel nostro villaggio?}
{290}{}{[Krom sorride in modo lupesco, poi ti afferra tra le sue possenti braccia.]}
{291}{}{[Get to it.]}
{292}{}{Ehi! Lasciami andare, hai capito tutto male!}
{300}{}{Al diavolo te, tentatrice! Vai a stuzzicare qualcun altro. Non ho tempo da perdere con te.}
{301}{}{Yeah, well fuck you too. Bye.}
{302}{}{Vabbe'. Ci vediamo.}
{310}{}{[Diverse ore passano in una foschia di passione sudata e brutale. Alla fine, giaci sul pavimento della capanna di Krom, esausta.
 Krom e' al tuo fianco, i suoi occhi divorano i contorni del tuo corpo.] Per gli Dei, ragazza, sei incredibile!}
{311}{}{Thanks. You're not so bad yourself.}
{312}{}{Certo che lo sono. Dopotutto, sono il Prescelto.}
{320}{}{[Krom ti rivolge un sorriso strano.] Gli Dei sanno che hai fatto miracoli per me, ragazza, ma forse ti interesserebbe
 aiutare anche il resto della tribu'?}
{321}{}{Certo, credo di poter dare una mano. Cosa vorresti che facessi?}
{322}{}{Vorrei poter aiutare, ma dovrei davvero andare ora. Mi dispiace.}
{323}{}{Vuoi che mi scopi il resto della tribu'? Che tipo di ragazza credi che io sia?}
{330}{}{[Krom scoppia in una fragorosa risata.] Dei no, ragazza! Anche se potrebbe fare miracoli per il morale dei miei guerrieri, odierei condividere un miele dolce come te. No, ho un compito molto piu' banale per te, se sei disposta.}
{331}{}{That depends. What would you need me to do?}
{340}{}{[Ti osserva attentamente, come se stesse valutando qualcosa.] Devo incontrare uno di quei dannati mercanti civilizzati
 tra poco — un uomo grassoccio e guercio, che mi fido quanto di un radscorpion affamato. Non ci ha ancora traditi,
 ma ho un brutto presentimento per il nostro prossimo incontro.}
{341}{}{E perche'?}
{342}{}{I don't see how I fit into this. What's your point?}
{350}{}{L'ultima volta che abbiamo parlato, si vantava che mi avrebbe portato qualcosa di davvero miracoloso, e che sarebbe stato saggio
 per me portare tutte le pelli di gecko dorato che potevo trasportare. Non so quale sia il suo oggetto miracoloso, ma probabilmente e' qualche
 gingillo civilizzato sperando che io sia abbastanza ignorante da pagarlo piu' del dovuto. Ecco perche' vorrei che fossi tu a fare lo scambio.}
{351}{}{Perche' io?}
{352}{}{Sorry, but I think I'll pass. Bye.}
{360}{}{Perche' sei del mio sangue — una sorella tribale, come ci chiamano — e posso dire che hai avuto esperienza recente
 con il mondo civilizzato. Se prova a fregarti, tu lo noteresti piu' facilmente di me. Inoltre, ho un buon presentimento su di te,
 e ho imparato a fidarmi dei miei istinti.}
{361}{}{Perche' sei del mio sangue — una sorella tribale, come ci chiamano — e posso dire che hai avuto esperienza recente
 con il mondo civilizzato. Se prova a fregarti, tu lo noteresti piu' facilmente di me. Inoltre, ho un buon presentimento su di te, ragazza,
 e ho imparato a fidarmi dei miei istinti.}
{362}{}{Alright. Let's do this.}
{363}{}{Alright, but give me a moment to get ready.}
{364}{}{Se ti aiuto, cosa avro' in cambio?}
{370}{}{[Ride piano.] Ti offro l'ospitalita' della nostra tribu' e l'opportunita' di impressionarmi. Non prometto altro.}
{371}{}{Alright. Let's do this.}
{372}{}{Alright, but give me a moment to get ready.}
{373}{}{Not interested. Bye.}
{375}{}{Are you ready to go?}
{376}{}{Non ancora.}
{377}{}{Alright. Let's do this.}
{380}{}{It's up to you to decide.}
{390}{}{[Krom esamina uno degli stimpak appena acquisiti dalla tribu'.] Questi dovrebbero rivelarsi piuttosto utili. [Avvicina
 lo stimpak al naso, annusa e aggrotta la fronte. Ne spruzza un po' sulla mano e lo assaggia con cautela.] Maledetti gli Dei!
 Sono pieni di sangue di brahmin! Quel bastardo guercio ci ha fregati. In questo momento starà ridendo di noi mentre si gode le sue nuove pelli dorate.}
{391}{}{Sorry about that. I had no idea they were fake.}
{392}{}{Oh well. Live and learn.}
{400}{}{Se rivedo mai quel cane imbroglione, saro' lieto di spaccargli il cranio. Ora, se vuoi scusarmi,
 devo sbarazzarmi di alcune fiale di sangue di brahmin. Forse lo sciamano potrebbe farne qualcosa.}
{410}{}{Non mi importava di quel bastardo brutto, ma per gli Dei, non avevo intenzione di farlo a pezzi. Certo, ora la sua merce e' libera
 da prendere, ma se si sparge la voce che e' venuto a commerciare con noi e non e' mai tornato, verremo messi al bando dai mercanti.}
{411}{}{Non mi importava di quel bastardo brutto, ma per gli Dei ragazza, non avevo intenzione di farlo a pezzi. Certo, ora la sua merce e' libera
 da prendere, ma se si sparge la voce che e' venuto a commerciare con noi e non e' mai tornato, verremo messi al bando dai mercanti.}
{412}{}{Sorry, I guess I got carried away.}
{413}{}{Era feccia civilizzata e meritava la morte.}
{414}{}{Oops.}
{420}{}{Ora vedo che e' stato un errore affidarti questo compito. Terra' gli occhi ben aperti su di te finche' resterai nel nostro
 villaggio. Ora vieni, sistemiamo questo pasticcio e andiamo.}
{430}{}{Quel bastardo bugiardo ha avuto cio' che meritava. Che la sua sorte sia una lezione per qualsiasi mercante che pensi di poterci rubare i nostri beni.
 Hai fatto bene a scoprire il suo inganno. Vedo che ho fatto una scelta saggia nel fidarmi di te. Sei il benvenuto tra noi, e puoi considerare la nostra tribu'
 come la tua. Tuttavia, potrei chiedere ancora il tuo aiuto in futuro. Ora vieni, lasciamo che questi cadaveri marciscano al sole.}
{431}{}{Quel bastardo bugiardo ha avuto cio' che meritava. Che la sua sorte sia una lezione per qualsiasi mercante che pensi di poterci ingannare.
 Hai fatto bene a scoprire il suo inganno. Bella, acuta e letale — per gli Dei, ragazza, hai tutto. Sei la benvenuta tra noi,
 e puoi considerare la nostra tribu' come la tua. Tuttavia, potrei chiedere ancora il tuo aiuto in futuro. Ora vieni, lasciamo che questi cadaveri marciscano al sole.}
{440}{}{Non ti biasimo per non aver fatto lo scambio. Anche io avevo un brutto presentimento. Ammetto che quegli stimpak
 sarebbero stati utili, ma siamo sopravvissuti senza, e continueremo a farlo. Ora, sei il benvenuto tra noi,
 e puoi considerare la nostra tribu' come la tua. Tuttavia, potrei chiedere ancora il tuo aiuto in futuro. Grazie per l'aiuto.}
{441}{}{Non ti biasimo per non aver fatto lo scambio. Anche io avevo un brutto presentimento. Ammetto che quegli stimpak sarebbero
 stati utili, ma siamo sopravvissuti senza, e continueremo a farlo. Sei la benvenuta tra noi, ragazza,
 e puoi considerare la nostra tribu' come la tua. Tuttavia, potrei chiedere ancora il tuo aiuto in futuro. Grazie per l'aiuto.}
{442}{}{Nessun problema.}
{443}{}{My pleasure.}
{444}{}{Vabbe'. Ci vediamo.}
{450}{}{Se rivedo mai quel cane imbroglione, saro' felice di spaccargli il cranio. Tuttavia, hai fatto bene a scoprire il suo inganno.
 Vedo che ho fatto una scelta saggia nel fidarmi di te. Sei il benvenuto tra noi, e puoi considerare la nostra tribu' come la tua.
 Tuttavia, potrei chiedere ancora il tuo aiuto in futuro. Grazie per l'aiuto.}
{451}{}{Se rivedo mai quel cane imbroglione, saro' felice di spaccargli il cranio. Tuttavia, hai fatto bene a scoprire il suo inganno.
 Vedo che ho fatto una scelta saggia nel fidarmi di te, ragazza. Sei la benvenuta tra noi, e puoi considerare la nostra tribu' come la tua.
 Tuttavia, potrei chiedere ancora il tuo aiuto in futuro. Grazie per l'aiuto.}
{452}{}{Nessun problema.}
{453}{}{My pleasure.}
{454}{}{Vabbe'. Ci vediamo.}
{460}{}{[Il gigante guerriero annuisce in segno di saluto mentre ti avvicini.] Bentornato, amico. Ti serve qualcosa?}
{461}{}{[Il gigante guerriero sorride mentre ti vede avvicinarti.] Per gli Dei, quasi dimenticavo quanto sei splendida. Ti serve qualcosa, ragazza?}
{462}{}{I was wondering if I could ask you a couple questions.}
{463}{}{No, sorry, I thought this was a different tent. I'll be going now.}
{464}{}{[Sorriso seducente] Si', omone. Ho proprio bisogno di qualcosa. [Occhiolino.]}
{470}{}{Certamente.}
{471}{}{You look like you've been through a lot. I was wondering what your story is.}
{472}{}{What could you tell me about this village?}
{473}{}{Is there anything going on here I could help you with?}
{474}{}{Uh, strano. Sembra che abbia dimenticato cosa volevo chiederti. Tornero' se mi torna in mente. Addio.}
{480}{}{[Ride piano.] Si', credo di averne passate molte. Vengo da una tribu' lontana, a nord. Quando avevo quindici anni,
 siamo stati attaccati da selvaggi. Mi svegliai quel giorno come un ragazzo, ma quando il sole tramonto' su quella scena cupa,
 mi ero fatto strada fino alla virilita' con la lama. Ogni uomo, donna e bambino era morto, tranne me. Ah, ma cos'e' la vita senza battaglia e conflitto?
 O spezza un uomo, o lo forgia come acciaio. Porto le mie cicatrici con orgoglio.}
{481}{}{So what'd you do then?}
{482}{}{Alright, I think I've heard enough. Let me ask you something else.}
{490}{}{Ammucchiai i corpi e li guardai bruciare per tutta la notte. Poi raccolsi cio' che potevo e iniziai a vagare. Passai
 del tempo con varie tribu'; combattere molte battaglie. Trascorsi un po' di tempo tra gli uomini "civilizzati", ma mi stancarono presto.
 Troppi cani senza onore nascosti dietro le loro armi. Preferisco una buona battaglia di carne e acciaio. Non sono un uomo complicato.
 Dammi battaglie e banchetti, vino e donne. Cos'altro conta in questo mondo cupo?}
{491}{}{So how'd you end up here?}
{500}{}{Arrivai qui un paio d'anni fa. Questa tribu' mi accolse e mi tratto' bene. Mi offrirono di diventare il loro capo guerriero,
 cosa che ovviamente accettai. Mi sono trovato bene qui, accanto alla Grande Acqua Salata. Ma sento crescere dentro di me il richiamo del viaggio.
 Un giorno non lontano, credo che riprendero' il cammino per vedere cosa gli Dei hanno in serbo per me.}
{501}{}{Thanks for the story. Could I ask you something else?}
{502}{}{Thanks for the story. Bye.}
{510}{}{Vediamo... La maggior parte dei membri di questo villaggio proviene da tre piccole tribu' che decisero di unirsi molti
 anni fa per evitare l'estinzione. Cio' crea un interessante miscuglio di usanze e dialetti. E, cosa piu' importante,
 crea un buon miscuglio di donne. A parte questo, non c'e' molto da dire. E' un villaggio semplice dove lottiamo per forgiare
 una semplice esistenza.}
{511}{}{Alright, thanks. Could I ask you something else?}
{512}{}{Okay, grazie. Ci vediamo.}
{520}{}{A dire il vero, sembra che Marli stia avendo qualche problema con il pozzo. Se ti va di aiutare, potresti andare a vedere qual e' il problema.}
{521}{}{Okay, grazie. Ci vediamo.}
{522}{}{Alright, maybe I'll do that. But first, could I ask you something else?}
{530}{}{Bene rivederti, amico. Se hai un momento, avrei di nuovo bisogno del tuo aiuto.}
{531}{}{Bene rivederti, ragazza. Se hai un momento, avrei bisogno del tuo aiuto.}
{532}{}{Certo. Cosa ti serve?}
{533}{}{Sorry, I'm busy now. Perhaps later.}
{540}{}{Due dei nostri cacciatori, Serin e Jerem, non sono ancora tornati dal terreno di caccia e alcuni stanno iniziando a preoccuparsi. Sono due dei nostri migliori guerrieri, e non vorrei pensare che sia successo loro qualcosa. Andrei a cercarli io stesso, ma se i villaggi vedessero che mi interesso cosi' tanto, temo che penserebbero al peggio. Preferisco non agitare nessuno finche' non so cosa sta succedendo. Quindi, li cercherai tu per me?}
{541}{}{Alright, but where should I look?}
{542}{}{Mi dispiace, ma non ho tempo per cercarli. Inoltre, sono sicuro che torneranno presto. Addio.}
{543}{}{I'm not here to babysit your warriors. Bye.}
{550}{}{Controlla il terreno di caccia, a nord. Il modo piu' rapido per arrivarci e' attraverso la grotta a ovest, vicino alla Grande Acqua Salata. Normalmente non consiglierei quella strada, perche' rischia di crollare, ma e' importante che tu faccia in fretta. Procedi con cautela nella grotta, e dovresti farcela.}
{551}{}{Alright, I'll hurry and try to find them.}
{552}{}{Aspetta, vuoi che passi in una grotta che sta per crollare? Hmm... Merda, mi sono appena ricordato! Devo andare a salvare la mia tribu'! Scusa, devo scappare.}
{560}{}{Do you bring news of the lost hunters?}
{561}{}{Not yet. I'll keep looking.}
{562}{}{Si', li ho trovati nella grotta. Sono entrambi morti.}
{570}{}{[Krom annuisce, il volto cupo.] Come?}
{571}{}{C'e' stato un crollo. Uno e' stato schiacciato dalle rocce; l'altro e' rimasto intrappolato sotto le macerie, poi divorato vivo da un gecko. E' stato piuttosto brutale.}
{580}{}{Uccisi da un dannato crollo. Maledetti gli Dei! Odio perdere uomini validi in questo modo. Avrebbero dovuto morire sul campo di battaglia, come i veri guerrieri che erano. [Scuote la testa.] La loro perdita e' un duro colpo per questa tribu'. Comunque, grazie per averli cercati. I tuoi servigi non sono piu' necessari.}
{581}{}{Sure, anytime. Bye.}
{582}{}{Sono certo che fossero grandi uomini. Addio.}
{590}{}{Grazie per aver trovato i cacciatori. La perdita di Jerem e' grave, era un guerriero abile. Avrebbe dovuto morire
 sul campo di battaglia, non per un dannato crollo. Comunque, Serin dovrebbe riprendersi completamente, grazie a te, amico. Sarai
 sempre il benvenuto qui.}
{591}{}{Grazie per aver trovato i cacciatori. La perdita di Jerem e' grave, era un guerriero abile. Avrebbe dovuto morire
 sul campo di battaglia, non per un dannato crollo. Comunque, Serin dovrebbe riprendersi completamente, grazie a te, ragazza. Sarai
 sempre la benvenuta qui.}
{592}{}{Thanks. Take care, Krom.}
{800}{}{Mia tribu', Arroyo, bisogno aiuto. Io aiuto. Io speciale aiutante prescelto.}
{801}{}{[Krom ride.] Si', sei sicuramente speciale. [Sorride e ti arruffa i capelli con una mano che sembra capace
 di frantumare massi.] Ti piace aiutare, eh? Che ne diresti di diventare l'aiutante speciale della nostra tribu'?}
{802}{}{I help! Wut you need?}
{803}{}{Nuh-uh. Io aiuto Arroyo. No tempo aiutare altri. Biiiee!}
{810}{}{Abbiamo bisogno di armi appuntite. [Indica la sua lancia.] Cinque lance, come questa. [Alza le dita.] *Cinque*.
 Inoltre, servono *dieci*, il doppio, coltelli. [Tira fuori un coltello e te lo mostra.] Come questo, okay? Cinque
 lance, non importa quanto affilate. E dieci coltelli normali. Capito?}
{811}{}{Otay. Io andare trovare cose appuntite.}
{812}{}{I have many pointy things. I no need them all.}
{820}{}{Did you change your mind? Want to be our tribe's special helper?}
{821}{}{Io speciale. Io essere grande aiutante per tribu'.}
{830}{}{You find all the pointy things I asked for?}
{831}{}{I found.}
{832}{}{I still look.}
{840}{}{[Krom esamina rapidamente le armi, poi sorride e ti da' una pacca sulla schiena.] Hai fatto un buon lavoro. Grazie. Ora vai, e non cacciarti nei guai.}
{841}{}{Ciao!}
{850}{}{[Krom ti arruffa i capelli.] Ecco il mio aiutante speciale. Ora vai, e non cacciarti nei guai.}
{851}{}{Ciao!}
{860}{}{Come to press your luck, have you?}
{861}{}{No, I've come to kick your ass.}
{862}{}{No, I just wanted to apologize for offending you.}
{863}{}{No, I was just leaving.}
{870}{}{Ah, it seems I'm in a forgiving mood today, friend. Now what can I do for you?}
{871}{}{Non mi piace essere preso in giro, ragazza, ma per gli Dei, come potrei restare arrabbiato con una dea come te? Ora, cosa posso fare per te?}
{872}{}{Lasciamo perdere. Ci vediamo.}
{1000}{}{[Il gigante guerriero annuisce rispettosamente.] Be', se non e' il grande eroe delle Lande. E' stata un'impresa notevole,
 mandare quei cani dell'Enclave dritti all'inferno cosi'. A dire il vero, sentire le storie delle tue imprese mi ha ispirato
 a tornare anch'io nelle Lande.}
{1001}{}{Where will you go?}
{1002}{}{Te ne vai cosi'? Ma sei il capo guerriero della tribu'.}
{1003}{}{D'accordo. Buona fortuna nel tuo viaggio, Krom.}
{1010}{}{[Scrolla le sue larghe spalle.] L'est sembra una direzione buona quanto qualsiasi altra. Si', credo che andro' a est a vedere
 cosa mi attende.}
{1020}{}{Metteranno semplicemente un altro guerriero al mio posto. Diamine, i capi guerrieri di solito non vivono molto piu' di un paio d'anni comunque, quindi direi che mi sono guadagnato la pensione.}
{2000}{}{You restock the Tribe with more weapons.}
{2500}{}{Sei caduto vittima dell'inganno di Roy.}
{2501}{}{You needlessly kill the merchant.}
{2502}{}{Smascheri l'inganno di Roy e ti assicuri che non commerci mai piu'.}
{2503}{}{You decline to trade with Roy.}
{2504}{}{You expose Roy's deception.}
{3000}{}{Begone vile slaver!}
