{100}{}{You see an ancient looking tribal.}
{101}{}{You see the elderly chief of the tribe.}
{102}{}{[Il vecchio fuma la sua pipa e ti osserva con occhi grigio spento che sembrano penetrare nell'anima. Ti fa cenno di sederti di fronte a lui nella tenda piena di fumo.] Grazie per aver riportato Kurisu al nostro villaggio. [Fa un lungo tiro dalla pipa.] Gli spiriti... hanno molto da dire su di te. Molto davvero. Dimmi, hai bisogno di qualcosa?}
{103}{}{[Il vecchio fuma la sua pipa e ti osserva con occhi grigio spento che sembrano penetrare nell'anima. Ti fa cenno di sederti di fronte a lui nella tenda piena di fumo.] Siamo molto grati per i tuoi servizi, Viandante. [Fa un lungo tiro dalla pipa.] Gli spiriti... hanno molto da dire su di te. Molto davvero. Dimmi, cosa ti porta al nostro villaggio?}
{104}{}{Welcome back, child. Was there something else you needed?}
{105}{}{What can this old man do for you?}
{106}{}{I am on a quest for the Holy GECK. Do you know anything about this?}
{107}{}{Sto cercando una donna scomparsa. E' la sorella del mio amico, Sulik.}
{108}{}{Is there anything else that needs to be done around here?}
{109}{}{Lasciamo perdere. Ci vediamo.}
{110}{}{Il Santo G.E.C.K... [Fa un lungo tiro dalla pipa.] C'e' una creatura che a volte cacciamo -- a volte, ci caccia lei. Un geco. No, sento che non e' quello che cerchi. Temo che il tuo Santo G.E.C.K. sia al di la' della mia comprensione.}
{111}{}{Lascia che ti chieda qualcos'altro.}
{112}{}{That's all I need to know. Bye.}
{120}{}{Sulik? [Annuisce.] Uno dei nostri migliori uomini. Ugualmente abile nell'arte della caccia e nell'arte di comunicare con gli spiriti delle ossa. Ci ha lasciati per trovare sua sorella, Kurisu, che non e' mai tornata da una tribu' vicina. Dimmi, figlio, dov'e' Sulik adesso?}
{121}{}{Oh, e' proprio qui. Ehi, Sulik, vieni qui...}
{122}{}{Oh, sta bene. Gli ho detto di aspettare mentre sbrigavo alcune cose.}
{123}{}{Mi dispiace, ma e' morto.}
{124}{}{[Sulik e il capo della tribu' si scambiano i saluti.] Mi da' grande piacere rivedere Sulik. Gli spiriti delle ossa mi avevano detto che era finito nei guai. Ma sua sorella, Kurisu?}
{125}{}{E' bello sapere che Sulik sta bene. Eravamo preoccupati che si fosse cacciato nei guai. Quindi, sua sorella e' ancora scomparsa?
 Anche lei e' un membro della nostra tribu'.}
{126}{}{[Corruga la fronte e fuma la pipa in silenzio per molto tempo. Proprio quando stai considerando di andartene. Alla fine parla.] Gli spiriti erano forti in Sulik. Ho sempre pensato che un giorno avrebbe potuto prendere il mio posto. Ora, vedo che gli spiriti avevano altri piani per Sulik. Ma sua sorella, Kurisu?}
{127}{}{E' stata catturata dagli schiavisti. Ho offerto a Sulik assistenza per trovarla. Sai qualcosa che potrebbe aiutare nella ricerca?}
{128}{}{[Chiude gli occhi per molto tempo. Proprio quando pensi che si sia addormentato, comincia a parlare.] Gli schiavisti sono guidati da un uomo con un'anima oscura. Metzger. Dimora in uno dei gusci in rovina delle citta' degli Antichi. Lo chiamano il Den. [Apre gli occhi.] Forse, la tiene la'. Gli spiriti delle ossa non dicono altro.}
{129}{}{Grazie. Lascia che ti chieda qualcos'altro.}
{130}{}{Grazie, figlio, ma sono a posto. Forse altri non lo sono. Chiedi in giro per il villaggio.}
{140}{}{I look for GECK.}
{141}{}{I looking for missing woman. She sister of friend Sulik.}
{142}{}{Addio.}
{150}{}{I ask more.}
{160}{}{Oh, lui essere proprio qui. Sulik, uomo capo volere parlare.}
{161}{}{Oh, lui stare bene. Lui aspettare me.}
{162}{}{I sorry. He dead.}
{170}{}{Si', uomini cattivi prendere lei. Io aiutare Sulik. Tu sapere dove lei essere?}
{200}{}{Your evil ends here, slaver!}
{300}{}{[Il vecchio fuma la sua pipa e ti osserva con occhi grigio spento che sembrano penetrare nell'anima. Ti fa cenno di sederti di fronte a lui nella tenda piena di fumo.] Hai compiuto una grande impresa, figlio. Sento le grida di molti spiriti delle ossa malvagi perduti nella Grande Acqua Salata. Ora che ti sei dimostrato all'altezza, posso condividere con te il grande segreto finale.}
{301}{}{Alright, finally! Let's hear it.}
{302}{}{Not interested, old man. Bye.}
{310}{}{[Fa un lungo tiro dalla pipa, poi chiude gli occhi. Dopo un momento, annuisce.] Si'. Vedo che lo spirito del Grande Orso ha guidato la tua missione, infondendo nuova vita a vecchie ossa. Anche altri. Forse ti sono apparsi in una visione. Venuti da molto, molto lontano... dove i mutanti non sono ammessi.}
{311}{}{Di che cosa diavolo stai parlando?}
{312}{}{Si' si', ho avuto l'incontro speciale di Star Wars. Non dirmi che questo e' il grande segreto finale.}
{320}{}{Il segreto finale... il segreto piu' grande dell'intero gioco... e', [Mentre fa una pausa drammatica, fa un altro tiro dalla pipa. Improvvisamente, la pipa gli scivola dalle mani e cade nella sua veste, incendiandolo istantaneamente.]}
{321}{}{Fuck!}
