{100}{}{You see a lost spirit.}
{101}{}{You see Nessa, the lost spirit.}
{102}{}{Vedi lo spirito di una giovane ragazza, illuminato dal freddo bagliore della luna.}
{103}{}{Sono tradita. Tradita e sola.}
{104}{}{Come puo' aver fatto una cosa simile a *me*?}
{105}{}{The blood... So much blood...}
{110}{}{Diceva di amarmi. Che potevamo ricominciare insieme. Come ha potuto farmi questo?}
{111}{}{Who did this to you? Can you hear me?}
{120}{}{E' tutta una bugia. Non mi ama affatto. Oh, ha un coltello! Fa male! Lo sguardo nei suoi occhi, cosi' freddo, cosi'...}
{121}{}{Se puoi sentirmi, dimmi chi ti sta facendo del male. Chi ti ha fatto questo?}
{122}{}{That's it--that's enough for me. I'm outta here.}
{130}{}{Se ne sta andando ora. Mi sta lasciando qui a morire da sola. Come e' potuto accadere?}
{131}{}{Ti prego, dammi solo un nome. Dammi qualcosa su cui lavorare.}
{140}{}{Non doveva andare cosi'. Dicevi di voler mettere su famiglia con me. Oh, fa cosi' freddo... credo che sto morendo... No! Questo non e' reale! Non mi faresti mai questo, Thorg! Ti amo! Nessa ti amera' per sempre...}
{141}{}{Thank you, Nessa. That's all I needed to hear.}
{150}{}{It's so lonely in the dark... So very lonely.}
{151}{}{[Fatto]}
{160}{}{Il sangue non smette mai di scorrere... perche' questo dolore non finisce?}
{161}{}{Don't worry, Nessa, I'm going to help you find peace soon.}
{300}{}{Uh... You talkin' to me, glow-lady?}
{310}{}{Dove sta l'uomo col coltello? Io non vedo nessun uomo col coltello. Di cosa stai parlando? Perche' brilli cosi', comunque? Sei dipendente da qualche sorsata di gamma?}
{320}{}{Ascolta, donna-luminosa, NON C'E' NESSUN UOMO COL COLTELLO! Non sta andando da nessuna parte perche' non c'e' nessuno tranne te e me!}
{330}{}{Io penso che tu sia carina, donna-luminosa, ma sei troppo fuori di testa per essere adatta a me. A volte non ha nemmeno senso quello che dici! Hai bisogno di aiuto, ma io non so come dartelo. Quindi, uh... io vado ora, ok? Ciao-ciao!}
