{100}{}{Vedi un guerriero.}
{101}{}{Vedi Serin.}
{102}{}{Sembra gravemente ferito e ha una gamba rotta.}
{103}{}{Vedi Serin. Sembra gravemente ferito e ha una gamba rotta.}
{104}{}{Vedi Serin. La sua gamba è fasciata e zoppica.}
{105}{}{Vedi Serin. Sembra stare meglio ed è in un sonno profondo.}
{106}{}{Vedi Serin. Sembra essersi ripreso bene.}
{200}{}{*ugh* Muori demonio!! Non riuscirai a-}
{201}{}{Calmati. Ora sei al sicuro. Il gecko è morto.}
{202}{}{Cosa!? Oh, grazie agli spiriti, amico. Temevo di essere spacciato.}
{203}{}{Cosa è successo qui?}
{204}{}{Jerem e io uscire per caccia settimanale. Prendere passaggio grotta verso campo dove molti geco girare. Caccia andare male. Dover scappare. Troppi geco con spiriti di furia. Noi entrare grotta. Cominciare urlare per aiuto. [Si ferma un momento e fa una smorfia di dolore mentre cerca di massaggiarsi la gamba.]}
{205}{}{Per favore, continua.}
{206}{}{Passaggio gia' essere sull'orlo della rovina. Acqua filtrare da ruscello in alto. Un passo mortale, ma essere grande scorciatoia verso campi. Non piu'. Vedere, noi urlare come sciocchi e soffitto crollare su di noi.}
{207}{}{[Continua]}
{208}{}{Povero Jerem. Io vedere grande roccia schiacciare lui come insetto. Le grandi rocce mancare me, ma morso del Geco no. Proprio quando io pensare di essere al sicuro, un geco venire dal nulla e mordere forte la gamba. Portare me a terra. Non avere lancia, pensare il Geco mangiare me di sicuro. Ma gli spiriti avere altri piani. Portare una grande roccia finale sulla testa del geco. Schiacciarla piatta. Ma schiacciare anche gamba mia.}
{209}{}{[Continua]}
{210}{}{Cosi' io essere bloccato a terra, senza lancia. Improvvisamente, io sentire qualcosa venire verso me dal buio. Si avvicinare, e io vedere essere un grande geco arrabbiato. Le rocce cadute solo renderlo piu' incazzato. Ecco quando tu arrivare, amico. Davvero, io essere in debito con te.}
{211}{}{Wow, che storia. Sembra che tu sia molto fortunato ad essere vivo. Come sta la gamba?}
{212}{}{Non bene, amico. Sembra che roccia essere piu' forte di osso mia gamba. Dubito io alzarmi e camminare via presto.}
{213}{}{Non preoccuparti, sono un medico esperto. Fammi dare un'occhiata alla tua gamba e vedo cosa posso fare.}
{214}{}{Non preoccuparti, non dovrei avere problemi a portarti fuori di qui. Poi possiamo far dare uno sciamano un'occhiata alla tua gamba.}
{215}{}{Probabilmente dovremmo far venire un professionista qui a darci un'occhiata. Vado subito a cercare aiuto. La grotta sembra vuota adesso, quindi dovresti essere al sicuro qui fino al mio ritorno.}
{216}{}{Hmm... Non credo di essere abbastanza forte da portarti fuori di qui, ma scommetto che Sulik potrebbe farcela. [a Sulik] Portiamo fuori questo tizio.}
{217}{}{Hmm... Non credo di essere abbastanza forte da portarti fuori di qui, ma scommetto che Marcus potrebbe farcela. [a Marcus] Portiamo fuori questo tizio.}
{218}{}{[Esamini la gamba del guerriero. E' gravemente lacerata e l'osso e' esposto in alcuni punti. Con abilita' rimetti l'osso in posizione, fermi il sanguinamento, metti un'ingessatura alla gamba e ti metti al lavoro per guarirla.]}
{219}{}{[Dopo circa 15 minuti di lavoro estenuante, la gamba e' in condizioni molto migliori. Sembra che quest'uomo sara' in grado di camminare di nuovo.]}
{220}{}{Bene, dovrebbe bastare. Avrai bisogno di un paio di giorni di riposo per guarire completamente. Non mettere troppo peso sulla gamba in questo periodo e dovresti stare bene.}
{221}{}{Spiriti sacri possedere te, amico! Io ringraziarti. Ora io zoppicare verso lo sciamano. Prendere buona erba per calmare dolore. Ci vediamo al villaggio, amico.}
{222}{}{[Fatto]}
{300}{}{Ti ringrazio, amico. Ci vediamo al villaggio.}
{400}{}{Grazie tanto, amico. Davvero, tu essere benedetto dagli spiriti.}
{500}{}{ZzzZZzzz…}
{501}{}{…zzZZZzz… zzz…}
{600}{}{Curi la gamba di Serin.}
{700}{}{Ha bisogno di più aiuto di quanto io possa offrirgli. È meglio che vada.}
{1000}{}{Bello rivederti, eroe.}
{1001}{}{Non dimenticherò mai ciò che hai fatto per me, eroe.}
