{100}{}{}
{101}{}{Vedi un membro della tribù.}
{102}{}{Vedi Marli.}
{103}{}{Vedi un guerriero con un’espressione torva.}
{110}{}{Vattene. Sto cercando consiglio dagli spiriti e non ti gradiscono, forestiero. Se devi parlarmi, fallo un'altra volta.}
{111}{}{Non c’è bisogno di essere così scortese. Addio.}
{112}{}{Hmph. Non ti ho chiesto aiuto, forestiero. Avrei potuto sistemare il pozzo da solo.}
{113}{}{Già. Nessun ringraziamento necessario.}
{114}{}{Come vuoi. Bel modo di essere ingrato.}
{120}{}{Cosa vuoi?}
{121}{}{Vedo che avete problemi con il pozzo. Qual è esattamente il problema?}
{130}{}{Cosa c'e'? Ho fatto cadere la corda, ecco cosa c'e'. [Si muove a disagio.] Stavo fissando una corda nuova al pozzo e poi ho alzato lo sguardo e ho visto una bella giovane che si stiracchiava al sole. Gli spiriti della lussuria mi hanno distratto e la corda mi e' scivolata dalle mani e... E a te cosa importa, forestiero? A meno che tu non abbia una corda nuova per me, mi stai solo facendo perdere tempo.}
{131}{}{Non ho una corda con me, ma vedrò se riesco a trovarne una. Tornerò da te.}
{132}{}{In effetti ce l'ho. Vedro' se riesco a sistemarti il pozzo.}
{133}{}{No, temo che dovrai semplicemente ammettere agli altri cosa e' successo. Cerca di tenere a bada gli spiriti della lussuria la prossima volta. Addio.}
{140}{}{Allora, il pozzo è stato riparato oppure no?}
{141}{}{No, temo di no. Non ancora.}
{142}{}{Ti sembra sistemato? Sei proprio accanto a quella dannata cosa. Idiota.}
{150}{}{Allora, hai riparato il pozzo?}
{151}{}{Sì, ho sistemato la corda. Vedi?}
{160}{}{[Dà un'occhiata al pozzo, poi sogghigna.] A cosa serve una corda senza un secchio attaccato? O voi forestieri bevete leccando l'acqua da una corda bagnata? [Scuote la testa e borbotta qualcosa.] Attacca il secchio, e vedro' di darti una ricompensa.}
{161}{}{Right.}
{162}{}{Perche' non attacchi *tu* il secchio, e io vedo se riesco a trattenermi dal prenderti a calci il culo.}
{170}{}{Hai attaccato anche il secchio?}
{171}{}{No, non ancora.}
{172}{}{Ti *sembra* che abbia attaccato il secchio?}
{180}{}{Quindi il pozzo e' sistemato, giusto? Con il secchio attaccato e tutto quanto?}
{181}{}{Sì, è tutto sistemato.}
{182}{}{...}
{190}{}{[L'angolo della sua bocca si solleva in un mezzo sorriso.] Ah, immagino che voi forestieri non siate poi tutti cosi' male. Tieni, prendi questi soldi. Gli spiriti mi dicono che ti serviranno piu' che a me.}
{191}{}{Grazie.}
{200}{}{Che i tuoi antenati ti guidino bene.}
{201}{}{Grazie dell'aiuto.}
{202}{}{È un piacere rivederti.}
{210}{}{Non ci prenderai vivi, schiavista!}
{300}{}{D'accordo, calma i tuoi spiriti di rabbia. Lo faro' io. [Borbottando.] Forestiero pazzo...}
{301}{}{[FATTO]}
{310}{}{[Socchiude gli occhi verso di te, poi guarda il pozzo.] No.}
{311}{}{Allora no, immagino di non averlo ancora attaccato.}
{320}{}{Ehi, mi hai sentito? Ho chiesto se il pozzo e' sistemato.}
{321}{}{... [Sospiri, poi indichi il pozzo.]}
{330}{}{[Si gira e guarda il pozzo, poi torna a guardarti.] Si', ora sembra a posto. Perche' non l'hai detto subito? Tieni, prendi questi soldi. Gli spiriti mi dicono che ti serviranno piu' che a me.}
{331}{}{… [Prendi i soldi e te ne vai.]}
{400}{}{[Mentre stai per andartene, Marli ti osserva attentamente e gli si illuminano gli occhi.] Ah! Vedo che hai una mitraglietta. [Guarda l'arma con desiderio.] Ne avevamo una, una volta, ma Sulik la teneva sempre per se'. Si e' persa in una battaglia. Un vero peccato. La mia magia sarebbe terribilmente potente se avessi un ruba-anime come quello.}
{401}{}{Se vuoi questa, puoi prenderla. Sono sicuro che ne trovero' un'altra. [Dai la mitraglietta a Marli.]}
{402}{}{Prendila e basta. Non la voglio piu' dopo come la stai guardando. [Dai la mitraglietta a Marli.]}
{403}{}{Si', ci credo. Comunque, io e il mio ruba-anime ce ne andiamo altrove ora.}
{404}{}{Tieniti pure la tua magia, amico. Addio.}
{410}{}{[Sorride come un maniaco mentre osserva l'arma.] Oh, sei un buon amico per Marli, forestiero. Tieni, stavo conservando questa dolce acqua frizzante, ma credo che dovresti averla tu. [Ti porge una Nuka-Cola.] Ora vado a sputare morte infuocata su qualche gecko. [Corre verso il terreno di caccia.]}
{411}{}{La mia magia ora essere terribile forte!}
{1000}{}{Hai riparato il pozzo della tribù.}
{2000}{}{Scusa se sono stato uno stronzo con te, eroe.}
{2001}{}{Scusa, ho perso la tua mitraglietta. Quel gecko essere feroce davvero.}
