{100}{}{Vedi uno spirito perduto.}
{101}{}{Vedi Nessa, lo spirito perduto.}
{102}{}{Vedi lo spirito di una giovane ragazza, illuminato dal freddo bagliore della luna.}
{103}{}{Sono tradita. Tradita e sola.}
{104}{}{Come puo' aver fatto una cosa simile a *me*?}
{105}{}{Il sangue… così tanto sangue…}
{110}{}{Diceva di amarmi. Che potevamo ricominciare insieme. Come ha potuto farmi questo?}
{111}{}{Chi ti ha fatto questo? Mi senti?}
{120}{}{E' tutta una bugia. Non mi ama affatto. Oh, ha un coltello! Fa male! Lo sguardo nei suoi occhi, cosi' freddo, cosi'...}
{121}{}{Se puoi sentirmi, dimmi chi ti sta facendo del male. Chi ti ha fatto questo?}
{122}{}{Basta così. Per me è abbastanza. Me ne vado.}
{130}{}{Se ne sta andando ora. Mi sta lasciando qui a morire da sola. Come e' potuto accadere?}
{131}{}{Ti prego, dammi solo un nome. Dammi qualcosa su cui lavorare.}
{140}{}{Non doveva andare cosi'. Dicevi di voler mettere su famiglia con me. Oh, fa cosi' freddo... credo che sto morendo... No! Questo non e' reale! Non mi faresti mai questo, Thorg! Ti amo! Nessa ti amera' per sempre...}
{141}{}{Grazie, Nessa. È tutto ciò che avevo bisogno di sapere.}
{150}{}{È così solitario nel buio… così terribilmente solitario…}
{151}{}{[Fatto]}
{160}{}{Il sangue non smette mai di scorrere... perche' questo dolore non finisce?}
{161}{}{Non preoccuparti, Nessa. Presto ti aiuterò a trovare la pace.}
{300}{}{Uh… stai parlando con me, signora-luminosa?}
{310}{}{Dove sta l'uomo col coltello? Io non vedo nessun uomo col coltello. Di cosa stai parlando? Perche' brilli cosi', comunque? Sei dipendente da qualche sorsata di gamma?}
{320}{}{Ascolta, donna-luminosa, NON C'E' NESSUN UOMO COL COLTELLO! Non sta andando da nessuna parte perche' non c'e' nessuno tranne te e me!}
{330}{}{Io penso che tu sia carina, donna-luminosa, ma sei troppo fuori di testa per essere adatta a me. A volte non ha nemmeno senso quello che dici! Hai bisogno di aiuto, ma io non so come dartelo. Quindi, uh... io vado ora, ok? Ciao-ciao!}
