{100}{}{You see a crate.}
{101}{}{A crate that appears to be full of stimpaks.}
{102}{}{Vedi una cassa piena di inutili Stimpak falsi.}
{200}{}{[Dopo una rapida occhiata alla cassa, hai stabilito che ci sono circa cinquanta Stimpak, proprio come aveva detto il mercante.]}
{201}{}{[Examine them further.]}
{202}{}{[DONE.]}
{203}{}{Dopo averli esaminati attentamente, non noti nulla di insolito negli Stimpak.}
{204}{}{[DONE.]}
{205}{}{A un'ispezione piu' attenta, questi Stimpak ti sembrano un po' strani. Ne prendi uno e spruzzi un po' del suo liquido sul palmo. Annusando il liquido cremisi, capisci cos'e' davvero: sangue di brahmin.}
{206}{}{[DONE.]}
