{100}{}{Vedi un uomo sporco ma dall'aspetto robusto.}
{101}{}{Vedi Connar.}
{102}{}{Ehi, tu! Cosa ci fai li'?!}
{103}{}{Adesso sta' fermo dove sei, viaggiatore. Che cosa ci fai qui?}
{104}{}{Sto eliminando tutte queste talpe mutanti.}
{105}{}{Perche', cosa ti interessa?}
{106}{}{Perche' tu URLA!}
{107}{}{Scommetto che ti hanno mandato quei bastardi di Vault City. Meglio che te ne vada e lasci tutto il resto in vita.}
{108}{}{Beh, e' un po' tardi per farlo.}
{109}{}{Perche'?}
{110}{}{Scusa, ho del lavoro da fare.}
{111}{}{Quelle creature sono l’unica cosa che impedisce a Vault City di farci diventare i loro “servi”.}
{112}{}{Mi pagano per eliminare queste bestie, quindi è quello che farò.}
{113}{}{Questo non me l'avevano detto.}
{114}{}{Loro mi pagano perche' io mi sbarazzi dei mostri e ho completato il mio lavoro.}
{115}{}{Idiota! Perche' diavolo l'hai fatto?!}
{116}{}{Mi servivano i soldi.}
{117}{}{Verrano a prenderci se lo fai, lo sai questo?}
{118}{}{Non e' un problema mio.}
{119}{}{Beh, spero che ti vadano di traverso. Presto, loro verranno a prenderci.}
{120}{}{Non sapevo che fosse questo il motivo per cui volevano che qualcuno lo facesse.}
{121}{}{Certo, beh, comunque non tratto con la spazzatura come te.}
{122}{}{Beh, noi non possiamo permettere che tu lo faccia.}
{123}{}{Bisogna fare quello che bisogna fare.}
{124}{}{E hai creduto a loro sulla parola? Hai un sacco di cose da imparare dal mondo, amico.}
{125}{}{C'e' niente che possa fare per aiutarvi?}
{126}{}{I tipi di Vault City non sono certo i piu' coraggiosi del mondo. Basta un po' di casino e scappano come conigli. Se avessimo un po' di armi, credo che potremmo tenerli a distanza.}
{127}{}{Potrei aiutarti, ma le armi non sono economiche. Che tipo di armi cerchi?}
{128}{}{[Ti guarda con un sorriso incerto.] Sei davvero serio nell'aiutarci, vero? Va bene, se te la senti,
 allora dei fucili sarebbero l'ideale--cosi' potremmo iniziare a farli fuori da lontano. Quindi, se vuoi davvero aiutare,
 portaci dei fucili automatici--quattro basteranno. Oh, e anche un fucile a pompa sarebbe utile, nel caso le cose si facciano ravvicinate e sporche.}
{129}{}{Vedrò cosa posso fare. Ma come ho detto, le armi costano, quindi avrò bisogno di soldi.}
{130}{}{Non sei il benvenuto qui. Vattene.}
{131}{}{Ho cambiato idea. Cosa posso fare per aiutarvi?}
{132}{}{Certo... beh, voi non rimarrete qui a lungo, comunque.}
{133}{}{Come se me ne fregasse qualcosa.}
{134}{}{Sei tornato! Hai portato le armi per noi?}
{135}{}{Che cos'e' che vi serviva?}
{136}{}{Si', eccole qua.}
{137}{}{Ci servono quattro fucili d’assalto e un fucile a pompa. Prima ce li porti, meglio è.}
{138}{}{Okay.}
{139}{}{Perfetto! Con queste bellezze, nei prossimi mesi riusciremo a fare qualcosa di questo posto. Grazie mille e, se mai avrai bisogno di un posto dove riposare, sarai sempre il benvenuto qui, amico.}
{140}{}{Di nulla.}
{141}{}{Ciao! Le cose vanno bene. Il mese prossimo lavoreremo per espandere il villaggio.}
{142}{}{Ehila'! Le cose vanno bene, come vedi. Da' un'occhiata in giro, se ne hai il tempo.}
{143}{}{Stiamo continuando a costruire. Speriamo di espandere nuovamente le mura entro la fine del prossimo mese.}
{144}{}{Saluti! Il villaggio si è espanso di nuovo, proprio come speravamo. Sei il benvenuto, come sempre.}
{145}{}{Non abbiamo più nulla da temere da Vault City — sembra che potremo vivere qui in pace. Grazie ancora, viaggiatore.}
{146}{}{Cerca solo di non uccidere niente qui intorno, sempliciotto.}
{147}{}{Che diavolo hai fatto?! Maledetto traditore! Ti odio!!!}
{148}{}{Ooops…}
{149}{}{Fammi uscire di qui!!!}
{150}{}{Cosa ti ho fatto di male?}
{151}{}{Aiutatemi!}
{152}{}{Certo. Tieni, questo e' tutto quello che possiamo permetterci. [Ti porge 5.000$.] Forse sono un dannato idiota a fidarmi
 di uno sconosciuto, ma sei la nostra unica speranza di restare liberi. Parla con Vecchio Joe nel cortile di Vault City. Di solito
 e' dentro o vicino al bar. Sapra' cosa fare.}
{153}{}{Sto andando.}
{154}{}{Posso farti un paio di domande?}
{155}{}{Certo, cosa hai in mente?}
{156}{}{Da dove vengono queste talpe giganti, e perche' non sono aggressive?}
{157}{}{Niente, addio.}
{158}{}{Beh, e' una storia un po' strana. Vedi, un giorno e' arrivato qui un gruppo di ghoul, borbottando qualcosa su una "rinascita",
 e distribuendo questi strani amuleti. [Ti mostra un amuleto a forma di Ankh.] Questi grossi roditori sono venuti con loro, e i ghoul hanno detto
 che d'ora in poi ci avrebbero protetti. I ghoul se ne sono andati--probabilmente tornati a Gecko--ma i roditori sono rimasti, e
 sono qui da allora. Come ho detto, roba piuttosto strana. E' una scocciatura pulire dopo queste bestie, ma diamine,
 se tengono Vault City lontana dal nostro culo, allora credo di poter sopportare un po' di merda di ratto.}
{159}{}{Molto interessante. Pensi che potrei avere uno di quegli amuleti?}
{160}{}{Certo. Ce ne hanno dati cosi' tanti, e non sappiamo che diavolo farcene. Tieni, prendine uno.}
{161}{}{Grazie mille. Addio.}
{162}{}{No, ma ho una grande notizia: ho convinto il consiglio di Vault City a non toccare il vostro villaggio.}
{163}{}{Cosa? Ci lasceranno davvero in pace? Non capisco... come ci sei riuscito? Giuro che se mi stai prendendo in giro...}
{164}{}{E' vero--fidati. Sono riuscito a muovere qualche filo e a trovare un accordo, ma i dettagli non contano. La cosa importante e' che tu e la tua gente ora siete al sicuro.}
{165}{}{Grazie dal profondo del mio cuore... em... A proposito, ancora non so il tuo nome.}
{166}{}{Il mio nome è - }
{167}{}{Grazie, }
{168}{}{, ma che mi dici dei soldi che ti ho dato per comprare le armi?}
{169}{}{Sarai sempre il benvenuto qui! Addio.}
{170}{}{Si', ma non credo che ti serviranno. Almeno non contro Vault City. Vedi, ho convinto il consiglio di Vault City a non toccare il vostro villaggio.}
{171}{}{Lo farò. Ma prima ho alcune domande.}
{172}{}{Lasciamo perdere. Ci vediamo.}
{173}{}{Non ancora. Tornerò quando li avrò.}
{174}{}{Grazie! Ci vediamo.}
{200}{}{Guarda caso ho già quello che ti serve proprio qui.}
{201}{}{A quanto pare, ho gia' tutte quelle armi con me. Suppongo di poterne cedere alcune, ma sei sicuro che questo sia il modo migliore di procedere?}
{202}{}{Ho le armi che ti servono, ma onestamente penso che ci possa essere un modo migliore per farlo. C'e' un uomo ragionevole nel consiglio di Vault City, il Consigliere Anziano McClure. Sono sicuro di poterlo convincere a spingere il consiglio verso una soluzione pacifica.}
{203}{}{Onestamente, penso che ci possa essere un modo migliore per farlo. C'e' un uomo ragionevole nel consiglio di Vault City, il Consigliere Anziano McClure. Sono sicuro di poterlo convincere a spingere il consiglio verso una soluzione pacifica.}
{205}{}{Ha! Pensi davvero che a quei pezzi grossi del consiglio importi qualcosa di quello che ci succede? Non essere cosi' ingenuo, amico mio, quei bastardi di Vault City non sono affidabili. Ora per favore, vai a cercare Joe nel cortile di Vault City. Se non e' nel bar, allora non sara' lontano. Vecchio Joe sapra' cosa fare. Puoi fidarti di lui. Per favore, fai presto.}
{206}{}{D’accordo. Tornerò quando avrò novità.}
{210}{}{Credimi, abbiamo considerato l'alternativa, ma l'unica cosa a cui quei bastardi di Vault City risponderanno e' la violenza. Ora, ci darai le armi? Paghero' 5.000$ per averle. La liberta' non ha prezzo.}
{211}{}{Davvero?! Eccellente. Tieni, ti do 5.000$ per quelle armi. Sono tutti i soldi che abbiamo, ma non c'e' prezzo troppo alto per la liberta'. Ci hai reso un grande servizio, e sarai sempre il benvenuto qui.}
{212}{}{D’accordo. Ecco le armi.}
{213}{}{No, ho deciso di no. Addio.}
{214}{}{Nessun prezzo troppo alto, eh? Beh, so come funziona l'economia. Un aumento della domanda significa un aumento dei prezzi.}
{215}{}{[FATTO]}
{216}{}{[ATTACCA]}
{217}{}{Ascolta, iniziare una guerra con Vault City non e' la risposta. Certo, potreste respingerli per mesi, forse anche anni, ma non potrete resistere per sempre. E nel frattempo, vite andranno perse inutilmente. Ma se riuscissi a convincere anche solo un membro del consiglio di Vault City a ragionare, allora so che potremmo raggiungere un accordo pacifico.}
{218}{}{Hmm... Va bene, mi fido che tu abbia a cuore i nostri interessi. Se davvero pensi di poter ragionare con uno dei loro consiglieri, allora fai pure un tentativo. Tuttavia, penso che dovresti parlare con Vecchio Joe e sentire cosa ha da dire. Lo trovi nel bar del cortile o nei dintorni. Buona fortuna. Contiamo tutti su di te.}
{220}{}{Dovevo immaginarlo che saresti stato un altro opportunista senza cuore. E' da gente come te che abbiamo fondato questa comunita' per allontanarci. Sai che c'e'? Lascia perdere. Non abbiamo bisogno dell'aiuto di uno come te. Ora ti suggerisco di andartene.}
{221}{}{Dovevo immaginarlo che saresti stato un altro opportunista senza cuore. E' da gente come te che abbiamo fondato questa comunita' per allontanarci. [Sospira.] Va bene, aggiungeremo un altro migliaio, ma questo ci lascia senza nulla. Ora ci darai le armi?}
{222}{}{Certo, è stato un piacere fare affari con te. Addio.}
{223}{}{In realtà penso di poter trovare un’offerta migliore altrove. Addio.}
{225}{}{Eccellente. Tieni, ti do 5.000$ per quelle armi. Sono tutti i soldi che abbiamo, ma non c'e' prezzo troppo alto per la liberta'. Ci hai reso un grande servizio, e sarai sempre il benvenuto qui.}
{226}{}{D’accordo, stammi bene allora.}
{300}{}{Ci sono novita' sul nostro dilemma?}
{301}{}{Non ancora. Tornerò quando avrò trovato qualcosa.}
{302}{}{Buone notizie: ho convinto il consiglio di Vault City a non toccare il vostro villaggio.}
{310}{}{Se sei disposto a separarti da quelle armi che porti, siamo pronti a pagarti 5.000$ per averle.}
{311}{}{Affare fatto. Ecco le armi.}
{312}{}{Niente accordo. E' un mondo pericoloso la fuori e ho bisogno di tutte le armi che posso procurarmi. Addio.}
{400}{}{Grazie, amico. Con queste armi abbiamo una possibilita'!}
{401}{}{Bentornato. Grazie a te siamo riusciti a respingere la pattuglia di Vault City. Non ci daranno piu' fastidio.}
{500}{}{Non scocciarmi.}
{600}{}{Come si chiamava il tuo contatto a Vault City?}
{601}{}{Vecchio Joe. Come suggerisce il nome, e' davvero un vecchio tizio. Lo trovi nel bar del cortile o a vagare nei dintorni.}
{602}{}{Okay, grazie.}
{603}{}{Quindi, chi è esattamente?}
{604}{}{Vecchio Joe e' davvero un personaggio, questo e' certo. Dice di avere piu' di cent'anni, ma non so se credergli. Racconta ogni sorta di cosa. Dice perfino di aver salvato il mondo una volta. L'uomo e' pieno di storie--credo che la maggior parte siano stronzate, ma sono davvero divertenti. Tiene d'occhio le cose a Vault City per noi, e fa un dannato buon lavoro considerando che e' vecchio come la terra e quasi cieco.}
{605}{}{Interessante. Devo andare.}
{606}{}{Lui dice di aver aiutato a salvare il mondo? Sai, anch'io sono in una sorta di missione per salvare il mondo--o almeno per salvare *il mio* mondo.}
{610}{}{Bene. Buon per te. Continua cosi'. Ma non dimenticarti di aiutarci.}
{611}{}{Non lo farò. A dopo.}
{612}{}{Probabilmente me ne dimentichero', in effetti. Ho cosi' tante missioni che e' difficile tenerne traccia. Se non fosse per questo comodo Pip-Boy, chissa' dove sarei. Ci si vede.}
{700}{}{Ah, giusto. Ecco. [Gli dai 5.000$]}
{701}{}{Scusa, ho dovuto spenderli come parte dell’accordo.}
{702}{}{Merda, non ho abbastanza per ripagarti. Devo averne spesi alcuni senza pensarci. Te li restituiro' appena posso.}
{710}{}{Grazie. Tieni. [Ti restituisce 2.500$.] Tienili. E' il minimo che possiamo fare per ripagarti.}
{720}{}{Oh, capisco. Beh, se ci ha comprato la liberta', allora valeva ogni moneta. Grazie ancora per tutto quello che hai fatto per noi.}
{730}{}{Facciamo cosi'--che ne dici di restituirci solo la meta'? Hai 2.500$?}
{731}{}{Certo, tieni. [Gli dai 2.500$]}
{732}{}{Mi spiace, non ne ho così tanti.}
{740}{}{Grazie, }
{741}{}{Non dimenticheremo ciò che hai fatto per noi.}
{750}{}{Capisco... beh, non preoccuparti. I soldi non sono importanti quanto la nostra liberta'. Grazie.}
