{100}{}{Vedi un contadino.}
{101}{}{Vedi un contadino.}
{102}{}{Salve.}
{103}{}{Buona giornata a te.}
{104}{}{Benvenuto nel nostro Villaggio.}
{105}{}{I mostri ci proteggono.}
{106}{}{Benvenuto.}
{107}{}{Avremo presto bisogno di quei fucili.}
{108}{}{Per favore, sbrigati a portarci quelle armi.}
{109}{}{Perche' hai ucciso i mostri? Ora Vault City verra' a cercarci.}
{110}{}{Vattene e non tornare piu'!!}
{111}{}{Vattene immediatamente da qui!}
{112}{}{Ora siamo al sicuro.}
{113}{}{Hai la nostra gratitudine.}
{114}{}{Che Dio sia con te, straniero.}
{115}{}{Vai a parlare con Connar.}
{116}{}{Ah! Avresti dovuto vederli scappare!}
{117}{}{La Pattuglia della Citta' e' scappata con la coda tra le gambe. Ha, gliel'abbiamo fatta vedere!}
{118}{}{Chi avrebbe mai pensato che quei ragazzi di Vault City si sarebbero rivelati tali codardi!}
