{100}{}{Vedi un contadino.}
{101}{}{Vedi un contadino.}
{102}{}{Salve.}
{103}{}{Buona giornata a te.}
{104}{}{Benvenuto nel nostro Villaggio.}
{105}{}{I mostri ci proteggono.}
{106}{}{Welcome.}
{107}{}{We will need those rifles soon.}
{108}{}{Please hurry and bring us those weapons.}
{109}{}{Perche' hai ucciso i mostri? Ora Vault City verra' a cercarci.}
{110}{}{Vattene e non tornare piu'!!}
{111}{}{Vattene immediatamente da qui!}
{112}{}{We are safe now.}
{113}{}{You have our gratitude.}
{114}{}{God be with you, stranger.}
{115}{}{Go speak to Connar.}
{116}{}{Ha! You should have seen them run!}
{117}{}{La Pattuglia della Citta' e' scappata con la coda tra le gambe. Ha, gliel'abbiamo fatta vedere!}
{118}{}{Chi avrebbe mai pensato che quei ragazzi di Vault City si sarebbero rivelati tali codardi!}
