{100}{}{Vedi un uomo basso e gioviale.}
{101}{}{Vedi Happy Harry, il proprietario del negozio.}
{102}{}{Beh, salve... cosa posso fare per te?}
{103}{}{Vorrei barattare delle cose. Posso vedere cos'hai?}
{104}{}{E' ancora in vendita quell'aratro la' fuori?}
{105}{}{Me compra}
{106}{}{Per oggi niente, grazie.}
{107}{}{Spiacente. Non posso aiutarti, vicino.}
{108}{}{Beh, si'. Te lo posso vendere per... diciamo... ottocento.}
{109}{}{Te ne daro' seicento.}
{110}{}{D'accordo. Lo prendo.}
{111}{}{Eh, ottocento? Tornero'... con i soldi.}
{112}{}{Scordatelo. Gli Smith possono anche morire di fame.}
{113}{}{E' tuo. [incassa il denaro.] Lo prendi subito, o desideri che venga recapitato da qualche parte?}
{114}{}{Consegnalo agli Smith.}
{115}{}{Spiacente, amico. Ti costera' ottocento monete.}
{119}{}{Hai bisogno dei soldi per pagarmi, amico.}
{120}{}{Tornero' con i soldi.}
{121}{}{Nessun problema. Lo faro' consegnare immediatamente.}
{122}{}{Credevi di poterti servire da solo, eh? Dannato ladro... Guardie! Guardie!}
{123}{}{Dave mi ha mandato. Stiamo cercando di riparare una pompa dell'acqua rotta, e ha detto che tu avresti un motore di ricambio.}
{124}{}{Lavori con Dave, eh? Si', conosco quel tizio. Vedo che ha ancora il talento di far fare agli altri il lavoro duro--bastardo pigro.
 [Ride.] Comunque, credo di avere quello che cerchi, ma fammi controllare dietro. [Harry va nel retrobottega dove senti scatole spostate e mosse. Torna un minuto dopo.] Si', ce l'ho proprio qui. 500$ e' tutta tua.}
{125}{}{Certo. Ecco i soldi.}
{126}{}{500? Dannazione. Spero che mi rimborsino per questo. Va bene, ecco i soldi.}
{127}{}{Thanks for the business. Take care.}
{128}{}{Addio.}
{129}{}{Connar sent me for the goods.}
{130}{}{[Gli occhi di Harry guizzano rapidamente, sembra un po' nervoso] Si', certo. Solo un momento...}
{131}{}{[Harry ti porta i fucili.] Tieni, prendili. Sono diecimila, e facciamo in fretta.}
{132}{}{Of course, here's the money.}
{133}{}{Ma Connar mi ha dato solo cinque mila.}
{134}{}{Ma Connar mi ha dato solo due mila.}
{135}{}{Non e' un mio problema. Guarda, la mia attivita' fatica gia' abbastanza cosi'. Se qualcuno scopre che sto fornendo armi a Connar, le cose si metteranno davvero male, molto in fretta. Inoltre, gli sto gia' facendo uno sconto.}
{136}{}{Guarda, ci sto mettendo il collo... Oh, al diavolo, non ho tempo per discutere. Prendili e basta. [Si infila rapidamente i tuoi soldi in tasca.] Ora vattene. E ricorda, non li hai comprati da me.}
{137}{}{Eccellente. Ma ricorda, non hai comprato queste armi qui.}
{138}{}{It's a deal. Bye.}
{139}{}{[AVANTI]}
{140}{}{Well then, wait a bit until I get the money.}
{141}{}{Well, have you brought the money?}
{142}{}{What if I just give you five grand?}
{143}{}{What about two grand?}
{144}{}{Ehmmm... diecimila?! Non ho tutti quei soldi; aspetta un po' finche' non li recupero.}
{145}{}{Dannazione! Chi diavolo potrebbe avermi denunciato?!}
{146}{}{Hey! What was I imprisoned for?}
{147}{}{Well, at least the food's not bad.}
{148}{}{Che cosa stai guardando?}
{149}{}{What will happen to my shop now?}
{200}{}{500$? Ehi, magari potresti farmi un qualche sconto, voglio dire, tu e Dave siete amici, giusto?}
{201}{}{A dire la verita', non mi e' mai importato molto di quel tizio. 500$ per il motore. Prendere o lasciare.}
{202}{}{Fine. Here's the money.}
{203}{}{Forget it, I'm outta here.}
{204}{}{$500!? Forget this, I'm outta here.}
{1288}{}{Looks like I don't have enough money. Bye.}
