{100}{}{Vedi un vecchio con un barlume di follia negli occhi.}
{101}{}{Vedi il Vecchio Joe, l'"idiot savant" locale.}
{102}{}{Ciao. E' da un po' che non ci si vede.}
{103}{}{Ti conosco?}
{104}{}{Ah, si'. E' da un po'. Che cosa hai fatto in questo periodo?}
{105}{}{Beh, e' passato un po' di tempo. Cos'hai fatto in questo periodo?}
{106}{}{Un po' questo e un po' quello. Come fai a conoscermi?}
{107}{}{Senti, vecchio, non so chi diavolo tu sia.}
{108}{}{Eh, si'. Beh, ho girato un po'; alla fine sono finito qui, in questo posto dimenticato da dio. Non e' come i bei vecchi tempi. Nossignore.}
{109}{}{Certo, i bei vecchi tempi. Ricordi quella volta che noi...}
{110}{}{Ultimamente non e' piu' lo stesso, questo e' sicuro. Ora... cos'abbiamo fatto insieme?}
{111}{}{Non ti ricordi di me, eh? Infatti mi sembri un po' troppo giovane.}
{112}{}{Cosa stai cercando di dirmi?}
{113}{}{Hai un'aria cosi' familiare, pero'... Ah, devono essere i miei vecchi occhi. Beh, buona giornata a te.}
{114}{}{Uh, certo... addio.}
{115}{}{Gia'... abbiamo proprio fatto vedere l'inferno al Master, vero? E' andato tutto a puttane dopo che te ne sei andato. Sono stato costretto a spostarmi di continuo e a cambiar nome. Dov'eri finito?}
{116}{}{Ho vissuto in un piccolo villaggio.}
{117}{}{Beh, farai meglio a stare attento da queste parti. Le cose non sono cosi' chiare come una volta. Farai meglio a guardarti le spalle.}
{118}{}{Okay, grazie.}
{119}{}{Ho cercato il tuo Vault per un po', ma non l'ho mai trovato. Allora, hai qualche bella storia da raccontare al tuo vecchio amico Ian?}
{120}{}{Ian?}
{121}{}{Certo, Ian. Non ti ricordi di me? Sono passati un sacco di anni. Pensavo che non avresti mai dimenticato il tuo migliore amico. Beh... a parte quella faccenda degli spari alla schiena. Scusami ancora per quello.}
{122}{}{Mi dispiace, ma forse mi hai scambiato l'Abitante del Vault. Il mio villaggio e' stato fondato da una persona che proveniva dal Vault.}
{123}{}{Beh, questo spiega un po' le cose. Beh, mi fa piacere sentire che il mio amico ha fatto qualcosa di buono. Beh, il vecchio Ian ha un consiglio per te. Sta' attento. Questo posto non e' cosi' candido come sembra.}
{124}{}{Cosa sta succedendo?}
{125}{}{Beh, i Cittadini di Vault City tengono molto alla loro stirpe e non considerano molto le persone come me e te. Prendi questa. Ti proteggera' se le cose dovessero complicarsi un po'. Probabilmente non dovresti farti vedere a parlare con un vecchio pazzo. Farai meglio ad andartene.}
{126}{}{Thanks for your help. Bye.}
{127}{}{Lascia riposare questo povero vecchio.}
{128}{}{Cosi' familiare...}
{129}{}{Adesso lasciami solo.}
{130}{}{Faresti meglio ad andare.}
{131}{}{Si insospettiranno se ci vedono parlare ancora.}
{132}{}{Su, vai. Fa' in modo che il mio vecchio amico sia fiero di te.}
{133}{}{Grazie. Un'ultima cosa pero'. Sto cercando di aiutare un piccolo villaggio a nord-est di qui. Un tizio di nome Connar mi ha detto di cercarti e parlarti.}
{134}{}{Connar, eh? E' un bravo ragazzo. Tengo d'occhio le cose per lui. Allora, cosa vuole esattamente stavolta?}
{135}{}{Sta cercando di procurarsi delle armi. Pensa che con un po' di potenza di fuoco potrebbero tenere a bada le pattuglie di Vault City.}
{136}{}{Ah, quindi questo e' il suo nuovo piano, eh? Bene, vai al negozio di Happy Harry. Di' a Harry che ti manda Connar, e dovrebbe sistemarti -- credo che abbia qualche arma nascosta proprio per un'occasione del genere. Ma se vuoi il mio parere, non sono sicuro che sia il modo migliore di affrontare la situazione.}
{137}{}{Allora vado a parlare con Harry. Stammi bene, vecchio amico.}
{138}{}{Why, what do you mean?}
{139}{}{Connar e la sua gente hanno un forte spirito combattivo, ma in questo caso non bastera'. Vault City ha risorse quasi illimitate, e alla fine avra' la meglio. A volte e' meglio parlare e cercare di ragionare con le persone. E' una lezione che ho imparato dal mio vecchio amico, l'Abitante del Vault. Il Consigliere Anziano McClure si e' dimostrato un uomo ragionevole. Forse si puo' trovare un accordo con lui?}
{140}{}{Hmm... potrei doverci pensare. Grazie di tutto, ciao.}
{141}{}{Forse andro' a parlare con lui allora. Tuttavia, ero curioso riguardo alle talpe giganti che stanno proteggendo il villaggio.}
{142}{}{Si', cosa vuoi dirmi?}
{143}{}{Any idea where they're from or who's controlling them?}
{144}{}{Di quello non sono sicuro. Un gruppo di ghoul e' passato con loro. Portavano strani amuleti e parlavano di una sorta di "Rinascita". Questo e' piu' o meno tutto cio' che so. Potresti voler dare un'occhiata a Gecko comunque. Quel posto pullula di ghoul. A proposito di grossi ratti, ti ho mai raccontato di quando l'Abitante del Vault ed io siamo andati al Vault 15?}
{145}{}{No, ma conosco bene la storia, e' diventata una leggenda sacra nella mia tribu'. Comunque, forse andro' a vedere cosa posso trovare a Gecko. Stammi bene, Ian.}
{146}{}{Uh, thanks for the tip. I think you are the man I need to see though. Connar sent me to ask you for some things.}
{147}{}{Wait a minute! Connar told me you have some information.}
{148}{}{No, ma conosco bene la storia, e' diventata una leggenda sacra nella mia tribu'. Comunque, forse andro' a vedere cosa posso trovare a Gecko. Stammi bene.}
{150}{}{Era interessato a procurarsi delle armi per respingere le pattuglie di Vault City, ma l'ho convinto che c'e' una soluzione migliore.}
{151}{}{Ah, quindi questo e' il suo nuovo piano, eh? Si', Connar e' un brav'uomo, ma non sempre pensa le cose fino in fondo. A volte e' meglio parlare e cercare di ragionare con le persone. E' una lezione che ho imparato dal mio vecchio amico, l'Abitante del Vault.}
{152}{}{Well, any idea who on the council I might be able to talk to?}
{153}{}{Penso che il Consigliere Anziano McClure possa essere l'uomo giusto con cui parlare. Che ne pensi?}
{154}{}{Il Consigliere Anziano McClure e' un uomo intelligente qui a Vault City. Forse si puo' trovare un accordo con lui?}
{155}{}{Alright. I'll try to speak with him. Bye.}
{156}{}{Forse andro' a parlare con lui allora. Tuttavia, ero curioso riguardo alle talpe giganti che stanno proteggendo il villaggio.}
{157}{}{Sarebbe la tua scelta migliore. E' l'unico nel consiglio ad avere ancora un briciolo di ragionevolezza.}
{158}{}{Alright. I'll try to speak with him. Bye.}
{159}{}{Allora andro' a parlare con lui. Tuttavia, ero curioso riguardo alle talpe giganti che stanno proteggendo il villaggio.}
{200}{}{Ehi, se sei davvero lo stesso Ian che viaggio' con il mio antenato, allora ho una domanda per te.}
{201}{}{Alright, let's hear it.}
{202}{}{Come diavolo fai a essere ancora vivo? Devi avere piu' di cent'anni. Senza contare le memorie dell'Abitante del Vault, che dicono che sei stato bruciato vivo a Necropolis da un supermutante con un lanciafiamme.}
{203}{}{[Scoppia in una risata roca per un po'; poi si calma e si asciuga un paio di lacrime.] Oh, questa e' buona. Bruciato vivo da un lanciafiamme, ah! Vedi, dissi all'Abitante del Vault di inventarsi una storia su come fossi morto, perche' non volevo che i nostri vecchi nemici cercassero di darmi la caccia -- ecco perche' ho cambiato nome. Gli dissi di farmi morire in un'esplosione di gloria, e a quanto pare l'ha presa alla lettera. Ah, questa e' fantastica.}
{204}{}{Heh, immagino che questo chiarisca tutto. Comunque, ero curioso riguardo alle talpe giganti che stanno proteggendo il villaggio.}
{205}{}{That still doesn't explain how you're still alive and well after all these years.}
{206}{}{Ehi, sono confuso quanto te. Chissa'? Forse ha a che fare con tutte le radiazioni a cui sono stato esposto ai vecchi tempi. Diamine, quando siamo andati al Bagliore, ricordo che l'Abitante del Vault ingoiava Rad-X come fossero caramelle, ma ne ha offerto qualcuno al vecchio Ian? Certo che no. Credo fosse ancora arrabbiato per un piccolo incidente di fuoco amico. Heh heh. [Sospira.] Bei tempi quelli.}
{207}{}{Ne sono certo. Grazie per la storia Joe, ehm, Ian. Stammi bene.}
{208}{}{Ne sono certo. Grazie per la storia Joe, ehm, Ian. Comunque, ero curioso riguardo alle talpe giganti che stanno proteggendo il villaggio.}
{300}{}{Un momento! Sei tu il contatto a Vault City di cui parlava Connar?}
