{100}{}{You see the caravan master.}
{101}{}{You see Mr. Baron, the master of this caravan.}
{200}{}{Salve viaggiatore, mi chiamo Robert Baron, capo di questa carovana. Cerchi di fare uno scambio?}
{201}{}{Sure. Let's see what you've got.}
{202}{}{Actually, I wanted to speak with you on behalf of a nearby village.}
{203}{}{Nope. I'll be on my way now.}
{204}{}{Robert Baron, eh? Hai mai pensato di farti chiamare Bobby Baron? Suona bene, non credi?}
{210}{}{Penso che tua madre ti abbia fatto rimbalzare la testa un paio di volte. Ora, vuoi commerciare o no? Sono un uomo impegnato.}
{220}{}{D'accordo. C'e' qualcos'altro?}
{221}{}{Si', in effetti volevo parlarti a nome di un villaggio qui vicino.}
{222}{}{Nope. I'll be on my way now.}
{230}{}{[Aggrinza la fronte.] Villaggio? Non so di cosa stai--oh! Stai parlando di quel piccolo cesso infestato dai ratti laggiu'?}
{231}{}{Uh, maybe.}
{232}{}{Si', lo sono.}
{233}{}{Non e' un cesso. Sono una comunita' in difficolta' che sta facendo veri progressi.}
{240}{}{Senti, li ho gia' incontrati, e ti diro' la stessa cosa che ho detto a loro. Sono semplicemente troppo piccoli per valere il mio tempo. Inoltre, quel posto e' fetido come l'inferno.}
{241}{}{Alright. I gave it a shot. Bye.}
{242}{}{Oh, dai, non e' cosi' fuori mano. Ci passi praticamente davanti.}
{243}{}{Is there *any* way I could get you to change your mind?}
{250}{}{Se non hai intenzione di acquistare nulla, allora vattene!}
{251}{}{Barattiamo.}
{252}{}{Sorry, I'll go now.}
{253}{}{I think I'll waste *you* asshole.}
{254}{}{C'e' *qualche* modo per convincerti a cambiare idea sul commerciare con il villaggio?}
{260}{}{E allora? Non mi importa se e' solo un *minuto* fuori strada, non vale la seccatura.}
{261}{}{Alright. I see it's useless to reason with you. Bye.}
{262}{}{Is there *any* way I could get you to change your mind?}
{263}{}{E' un peccato, perche' un mercante intelligente coglierebbe al volo questa opportunita'. Ma ehi, se non sei interessato, immagino che dovro' rivolgermi altrove...}
{270}{}{Aspetta un momento. Non ho detto con certezza che non fossi interessato. Qual e' questa opportunita' di cui parli?}
{271}{}{Vedi, quel villaggio forse ora non sembra un granche', ma ho informazioni privilegiate che praticamente garantiscono che diventera' il nuovo posto caldo. Fidati, esplodera' nei prossimi anni. Quindi, se fossi in te, vorrei costruire rapporti adesso, prima che diventino troppo grandi e tu perda l'occasione.}
{280}{}{Ahah! Ti aspetti che creda che quel cesso diventera' qualcosa di valido? Credo di aver finito di perdere tempo con te.}
{281}{}{Alright. I see it's useless to reason with you. Bye.}
{282}{}{Is there *any* way I could get you to change your mind?}
{290}{}{Non stai scherzando, vero? Hmm, suppongo che non faccia male fare una piccola deviazione ogni tanto. Diamine, non e' nemmeno fuori mano. Grazie del consiglio, amico.}
{291}{}{No problem. See ya.}
{292}{}{Yep. Addio.}
{300}{}{[Sembra riflettere sulla tua domanda.] Forse... esattamente di cosa stiamo parlando?}
{301}{}{Rendi quel villaggio una tappa regolare del tuo percorso e, in cambio, ti paghero' 500$.}
{302}{}{Rendi quel villaggio una tappa regolare del tuo percorso e, in cambio, faro' la mia parte per assicurarmi che nulla di "spiacevole" accada alla tua carovana.}
{303}{}{Rendi quel villaggio una tappa regolare del tuo percorso e, in cambio, ti faro' divertire come non dimenticherai mai.}
{304}{}{Rendi quel villaggio una tappa regolare del tuo percorso e, in cambio, mia moglie qui ti fara' divertire come non dimenticherai mai.}
{305}{}{Actually, never mind. Bye.}
{310}{}{Ora si' che parli la mia lingua! Va bene, affare fatto. [Ti strappa avidamente i soldi di mano e ti stringe la mano.]}
{311}{}{Pleasure doing business with you. Bye.}
{312}{}{Addio.}
{320}{}{$500? Not worth it. Make it $1,000 and you've got a deal.}
{321}{}{I don't have that much. Bye.}
{322}{}{Alright, fine. $1,000 it is.}
{323}{}{No deal. Goodbye.}
{330}{}{Ora si' che parli la mia lingua! Affare fatto. [Ti strappa avidamente i soldi di mano e ti stringe la mano.]}
{331}{}{Pleasure doing business with you. Bye.}
{332}{}{Addio.}
{340}{}{Mi stai minacciando? Nessuno mi minaccia e resta vivo! (ai suoi guardiani della carovana) Uccidete questo stupido stronzo!}
{341}{}{Fatevi sotto!}
{350}{}{Senti, non voglio problemi. Se vuoi che passi da quel villaggio a commerciare, va bene, nessun problema. Diamine, non e' nemmeno fuori mano. Nessun problema.}
{351}{}{Sono contento che ci siamo capiti. Ti terro' d'occhio. Addio.}
{352}{}{Speriamo per te che non ci siano problemi. Perche' se ci sono, li risolvo io. Addio.}
{353}{}{[Lo fissi intensamente per un momento, poi ti allontani lentamente.]}
{360}{}{Ugh! Dio no! Preferirei scopare una brahmin. Ora vattene e smettila di farmi perdere tempo.}
{361}{}{Fuck you, asshole! [Attack.]}
{362}{}{Va bene, ma potevi semplicemente dire di no. Non c'era bisogno di fare lo stronzo.}
{363}{}{You don't know what you're missing.}
{364}{}{[Ti copri la faccia brutta con le mani e scappi via piangendo.]}
{370}{}{Eh, scusa ragazza. Non sono dell'umore giusto adesso. Hai qualcos'altro da offrire?}
{371}{}{Rendi quel villaggio una tappa regolare del tuo percorso e, in cambio, ti paghero' 500$.}
{372}{}{Rendi quel villaggio una tappa regolare del tuo percorso e, in cambio, faro' la mia parte per assicurarmi che nulla di "spiacevole" accada alla tua carovana.}
{373}{}{No. Ci vediamo.}
{380}{}{[Ti guarda dall'alto in basso, poi sorride.] Credo che abbiamo un accordo. Lo prendi dal retro?}
{381}{}{Baby, I take it any way you want to give it.}
{382}{}{You'll just have to find out, won't you?}
{383}{}{Ugh! Assolutamente no! Ora sbrighiamoci a finire questa cosa prima che vomiti.}
{390}{}{[Il mercante ti sorride mentre si riallaccia la cintura.] Cazzo, sai davvero come concludere un buon affare. Se mai avrai bisogno di convincere un mercante a fare qualcos'altro, assicurati di cercarmi. Ora dovrei proprio andare. E' stato un piacere fare affari con te.}
{391}{}{[Rabbrividisci.] Una volta e' piu' che sufficiente. Addio.}
{392}{}{Anytime. Bye.}
{393}{}{Addio.}
{400}{}{[Guarda Miria dall'alto in basso, poi sorride.] Credo che abbiamo un accordo. [Ti stringe la mano, poi mette un braccio attorno a Miria e la accompagna in un posto piu' appartato.]}
{401}{}{[Batti il piede mentre aspetti.]}
{402}{}{[Fischietta mentre lavora]}
{403}{}{[Check your weapons while you wait.]}
{404}{}{[Rimani li' in silenzio e incroci sguardi imbarazzanti con le guardie della carovana mentre ascolti i suoni di tua moglie che viene profanata dal mercante.]}
{410}{}{[Un'ora dopo, vedi Robert Baron e Miria, ora sudati e spettinati dopo il loro amplesso, tornare verso di te. Noti che Miria cammina con una lieve zoppia. Il mercante ti sorride mentre si riallaccia la cintura.] Cazzo, sai davvero come concludere un buon affare. Se mai avrai bisogno di convincere un mercante a fare qualcos'altro, assicurati di cercarmi. Ora dovrei proprio andare. E' stato un piacere fare affari con te.}
{411}{}{Vabbe'. Ci vediamo.}
{412}{}{Anytime. Bye.}
{413}{}{Addio.}
{500}{}{Hai convinto il mercante ad aggiungere il villaggio alla sua rotta commerciale.}
{510}{}{Uccidi il mercante, assicurandoti cosi' che il villaggio non possa commerciare.}
