{100}{}{Vedi una giovane donna.}
{101}{}{You see Ann, Connar's wife.}
{102}{}{She appears to be busily cooking.}
{200}{}{Oh, salve, sono Ann, la moglie di Connar. Devi essere tu quello che ci ha aiutati. Non posso dirti quanto apprezziamo tutto cio' che hai fatto. E' difficile credere che finalmente possiamo vivere in pace senza la paura che gli scagnozzi di Vault City vengano a portarci via dalle nostre case.}
{201}{}{Felice di essere stato d'aiuto. Sembri piuttosto impegnata qui. Hai bisogno di aiuto con qualcosa?}
{202}{}{No problem. See you around.}
{300}{}{In realta', *potrei* aver bisogno di aiuto. Ora che stiamo diventando piu' organizzati, stiamo iniziando a vedere i nostri numeri crescere. Il problema e' che non sono sicura che avremo abbastanza cibo per tutti. Mio marito ha provato a convincere le carovane a fermarsi qui, ma non pensano che valiamo il loro tempo. Non e' che potresti farli ricredere?}
{301}{}{Sorry lady, but I think I've done enough here. I need to move on now. Bye.}
{302}{}{Non potete mai occuparvi dei vostri fottuti problemi? Addio.}
{303}{}{Sure. I'll see what I can do. Who do I talk to about this?}
{310}{}{Uno dei capi carovana, il signor Baron, passera' di qui a breve. La pista delle carovane non e' lontana da questo villaggio. Se potessi andare la' e incontrarlo, te ne saremmo tutti molto grati.}
{311}{}{Alright, I'll give it a shot. Show me where he is.}
{312}{}{Alright, but I'm not ready yet. I'll let you know when I am.}
{313}{}{On second thought, you're going to have to handle this on your own. Sorry.}
{320}{}{Are you ready to go meet the caravan master yet?}
{321}{}{Not yet. Bye.}
{322}{}{Alright. I'm ready.}
{330}{}{Oh, sei tu! Grazie per aver parlato con il signor Baron. Era appena passato per prendere accordi commerciali con mio marito. Hai fatto cosi' tanto per aiutarci, ti saremo per sempre debitori!}
{331}{}{It's the least I could do. Take care.}
{332}{}{You think I do all this for free? Let's talk money.}
{340}{}{[Ann sembra un po' agitata.] Beh, si'... d'accordo. Avevo messo via qualcosa per un'emergenza, ma suppongo che tu possa averlo. E pensare che ti consideravo una brava persona.}
{341}{}{Looks are in the eyes of the beholder, lady. Good day.}
{342}{}{Sorry, money makes the world go round. Bye.}
{350}{}{Oh, sei tu! Ho sentito cosa hai fatto al signor Baron. Non mi e' mai piaciuto, ma non dovevi ucciderlo. Come comunita' soffriremo senza un commercio adeguato.}
{351}{}{Sorry, mistakes happen. Bye.}
{352}{}{Not my problem. Bye.}
{353}{}{Non dovete preoccuparvi di nessun dannato mercante. Perche' ho intenzione di uccidere tutti voi.}
{400}{}{Did Vault City send you?}
{401}{}{We have the right to live here, you know.}
{402}{}{Non ho nient'altro da dirti.}
{403}{}{Thanks again for everything!}
{404}{}{Thanks so much!}
{405}{}{Finalmente siamo al sicuro.}
{406}{}{Grazie di tutto! Assicurati di ripassare quando avremo ampliato il posto. Avro' finalmente una cucina funzionante in cui cucinare.}
{410}{}{Ciao.}
{411}{}{Sembri piuttosto impegnato qui. Hai bisogno di aiuto con qualcosa?}
{412}{}{Lasciamo perdere. Ci vediamo.}
{420}{}{How did it go?}
{421}{}{Come e' andata cosa? Oh, il mercante. In realta', ho perso interesse e me ne sono andato in giro.}
{430}{}{Cosa!? Ti rendi conto che questa era la nostra ultima occasione per prendere accordi con lui? Ora sembriamo degli idioti per avergli dato buca. Ci hai condannati.}
{431}{}{Sorry, mistakes happen. Bye.}
{432}{}{Not my problem. Bye.}
{433}{}{Non dovete preoccuparvi di nessun dannato mercante. Perche' ho intenzione di uccidere tutti voi.}
{500}{}{Hai convinto il mercante ad aggiungere il villaggio alla sua rotta commerciale.}
{510}{}{Hai ucciso il mercante, assicurando cosi' che il villaggio non possa commerciare.}
{511}{}{Non riesci a convincere il mercante ad aggiungere il villaggio alla sua rotta commerciale.}
