{100}{}{Vedi un ragazzino.}
{101}{}{Vedi una bambina.}
{102}{}{Sorride quando ti vede.}
{103}{}{Sorride quando ti vede.}
{104}{}{Ti guarda con incertezza.}
{105}{}{Ti guarda con incertezza.}
{106}{}{Ti fulmina con lo sguardo.}
{107}{}{Ti lancia un’occhiataccia.}
{200}{}{Grazie per averci aiutato, signore!}
{201}{}{Urrà, ora siamo al sicuro!}
{202}{}{Grazie per averci aiutato, signora!}
{203}{}{Urrà, ora siamo al sicuro!}
{204}{}{Sei cattivo!}
{205}{}{Sei qui per aiutarci?}
