{100}{}{Vedi un ragazzino.}
{101}{}{Vedi una bambina.}
{102}{}{Sorride quando ti vede.}
{103}{}{Lei sorride quando ti vede.}
{104}{}{Ti guarda con incertezza.}
{105}{}{Lei ti guarda con incertezza.}
{106}{}{Ti fulmina con lo sguardo.}
{107}{}{She glares at you.}
{200}{}{Thanks for helping us mister!}
{201}{}{Yippie we are safe now!}
{202}{}{Thanks for helping us ma'am!}
{203}{}{Yippie we are safe now!}
{204}{}{You're mean!}
{205}{}{Are you here to help us?}
