{100}{}{Quando entri nel piccolo villaggio, il tuo naso viene assalito dal familiare tanfo di roditore. Vedi diverse talpe giganti che si aggirano. Stranamente, non sembrano interessate ad attaccare te o i contadini che vivono qui.}
{101}{}{Il villaggio sembra vuoto. L'aria puzza di carcasse di talpe giganti in decomposizione.}
{102}{}{Il villaggio e' cambiato molto dalla tua ultima visita.}
{103}{}{E' cambiato ancora di piu' dall'ultima volta che sei stato qui. Sembra che la protezione delle talpe giganti sia stata sostituita da un muro.}
{104}{}{Hey! Where'd everybody go?}
