{100}{}{Vedi un bambino molto iperattivo.}
{101}{}{Vedi il piccolo Todd.}
{200}{}{BOOM!!! Amo le 'splosioni!}
{201}{}{Bam-bam! Io sparo ai mutanti!}
{202}{}{Vorrei vedere più esplosioni!}
{203}{}{Tutto dovrebbe esplodere!}
{300}{}{Puoi far esplodere qualcosa, signore?}
{301}{}{Quando saro' grande, governero' il mondo!}
{302}{}{Non mi piace stare qui, voglio trasferirmi sulla costa est!}
{303}{}{I miei vestiti sono magici!}
{304}{}{I grandi parlano troppo!}
{305}{}{La Confraternita d'Acciaio sono i cavalieri della Zona Contaminata!}
{306}{}{Tutti i mutanti sono cattivi!}
{307}{}{Scommetto che il mio orsacchiotto potrebbe ucciderti!}
{308}{}{Mio papa' e' scomparso di nuovo!}
{309}{}{A volte bevo dai cessi!}
{310}{}{Cosa significa “cont-i-newy-t”?}
{311}{}{Puoi far esplodere qualcosa, signora?}
