{100}{}{You see a very hyperactive little boy.}
{101}{}{You see Little Todd.}
{200}{}{BOOM!!! Amo le 'splosioni!}
{201}{}{Bam-bam! Io sparo ai mutanti!}
{202}{}{I wish I saw more 'splosions!}
{203}{}{Everything should explode!}
{300}{}{Can you blow something up, Mister?}
{301}{}{Quando saro' grande, governero' il mondo!}
{302}{}{Non mi piace stare qui, voglio trasferirmi sulla costa est!}
{303}{}{My clothes are magic!}
{304}{}{Grownups talk too much!}
{305}{}{La Confraternita d'Acciaio sono i cavalieri della Zona Contaminata!}
{306}{}{All mutants are evil!}
{307}{}{I bet my teddy bear could kill you!}
{308}{}{Mio papa' e' scomparso di nuovo!}
{309}{}{A volte bevo dai cessi!}
{310}{}{What's cont-i-newy-t mean?}
{311}{}{Can you blow something up, Misses?}
