{100}{}{Fumi un Commie.}
{101}{}{Fumi un altro Commie.}
{102}{}{Dentro il tuo elmetto c'e' un avviso: "PERICOLO! - Vietato fumare!!" Pensi che sia meglio fare come dice.}
{103}{}{Li hai fumati tutti.}
{104}{}{Ti serve prima un accendino.}
{200}{}{Fumi una canna.}
{201}{}{Fumi un’altra canna.}
{203}{}{Hai finito l’erba.}
{210}{}{Whoa. Questa erba e' SUPERBA.}
{211}{}{Ok, mi sdraio qui per un po’.}
{212}{}{Cominci a sentirti MOLTO stordito.}
{213}{}{Mi sento davvero strano, adesso...}
{214}{}{...dev'essere cosi' che si sente Hakunin nel suo giardino.}
{215}{}{È stato folle. Però ora mi sento meglio.}
{216}{}{Oh, merda...}
{217}{}{Svieni.}
{218}{}{Ti svegli stordito e confuso.}
{250}{}{Fumare e' un'abitudine disgustosa per una donna.}
