{100}{}{You smoke a Commie.}
{101}{}{You smoke another Commie.}
{102}{}{Dentro il tuo elmetto c'e' un avviso: "PERICOLO! - Vietato fumare!!" Pensi che sia meglio fare come dice.}
{103}{}{You've smoked 'em all.}
{104}{}{You need a lighter first.}
{200}{}{You smoke a joint.}
{201}{}{You smoke another joint.}
{203}{}{You're all outa weed.}
{210}{}{Whoa. Questa erba e' SUPERBA.}
{211}{}{Okay, I'm just gonna lie down here for a while.}
{212}{}{You begin to feel VERY light headed.}
{213}{}{I am feeling really strange right now...}
{214}{}{...dev'essere cosi' che si sente Hakunin nel suo giardino.}
{215}{}{That was crazy. I feel better now though.}
{216}{}{Oh shit...}
{217}{}{You pass out.}
{218}{}{Ti svegli stordito e confuso.}
{250}{}{Fumare e' un'abitudine disgustosa per una donna.}
