{100}{}{Ves al comerciante Bill.}
{101}{}{Ves a un comerciante de aspecto viejo.}
{200}{}{Hola, viajero. Me llamo Bill. ¿Qué puedo hacer por ti?}
{201}{}{Bienvenido de nuevo. ¿Necesitas algo más?}
{202}{}{Vamos a comerciar.}
{203}{}{He oído que eres el hombre con quien hablar sobre caravanas.}
{204}{}{No importa. Adiós.}
{210}{}{Digamos que he notado que se han acumulado muchos equipos y objetos viejos aquí en la Abadía. 
Supongo que no has encontrado nada... especial, durante tu tiempo aquí, ¿verdad?}
{211}{}{Je, así que te diste cuenta, ¿eh? Sí, la gente de la Abadía tiene una especie de fascinación por todo lo anterior a la guerra,
  especialmente si tiene que ver con la tecnología. Han formado una especie de religión rara en torno a eso. No lo entiendo del todo,
  la verdad, pero son buenas personas y pagan un buen dinero por cualquier cosa antes de la guerra que logre tener en mis manos. Pero de todos modos,
  en cuanto a algo especial ... hmm, [Él mira a Marcus.] Es gracioso que preguntes, quizás tenga algo que
  podría interesar a tu amigo aquí.}
{212}{}{Je, así que te diste cuenta, ¿eh? Sí, la gente de la Abadía tiene una especie de fascinación por todo lo anterior a la guerra
 especialmente si tiene que ver con la tecnología. Han formado una especie de religión rara en torno a eso. No lo entiendo del todo
 la verdad, pero son buenas personas y pagan un buen dinero por cualquier cosa antes de la guerra que logre tener en mis manos. Pero de todos modos
 en cuanto a algo especial... hmm, [Él echa un vistazo a tu grupo.] Lo siento, no creo que tenga nada especial que te pueda ser
  útil en este momento.}
{213}{}{Oh, bien. Déjame ver lo que tienes a la venta.}
{214}{}{Está bien. Déjame preguntarte otra cosa.}
{215}{}{¿Cómo qué?}
{216}{}{Verás, una caravana pasó por aquí hace no mucho, diciendo que venían del sur profundo. Dijeron que los
  habían atacado algunos de esos malditos mutantes (mirando a Marcus) sin ofender, grandote. De todos modos, se pasaron alardeando
  de cómo habían acabado con todos los mutantes. Afirmaron que habían sido casi una docena, y yo no les creí. Pero resulta
  que tenían alguna prueba.}
{217}{}{¿En serio? ¿Qué fue eso?}
{218}{}{Un conjunto descomunal de armadura mutante que habían logrado salvar de uno de los cadáveres. Por supuesto, por lo que sé,
  se lo robó a los huesos de un mutie muerto hace mucho tiempo que encontraron en las ruinas, pero ¿quién sabe? De todos modos, no fueron
  ansioso por seguir arrastrando lo pesado, así que me lo ofrecieron por poco dinero. No sabía lo que haría
  con eso, pero pensé que un trato un trato.}
{219}{}{Bueno, estoy seguro de que Marcus podría beneficiarse de esto. ¿Cuanto por esto?}
{220}{}{Eso es interesante. Bueno, Marcus aquí es lo suficientemente duro. No creo que necesitemos ese artículo. Déjame preguntarte
  algo más.}
{221}{}{Bueno, este chico malo podría fundirse fácilmente para hacer tres o cuatro conjuntos de armadura de metal. Digamos $ 3000.}
{222}{}{Tengo suficiente para eso.}
{223}{}{Creo que voy a pasar por ahora. Déjeme preguntarle otra cosa.}
{224}{}{Bien entonces. Esto nos va a llevar a dos de nosotros para mover esto, así que déjame ayudarte a que se adapte a tu amigo aquí.}
{225}{}{[HECHO]}
{226}{}{Oye, esto encaja muy bien!}
{300}{}{Podría saber una cosa o dos. ¿Qué querías saber?}
{301}{}{¿Con qué frecuencia se reabastece?}
{302}{}{¿Las caravanas están contratando?}
{303}{}{Pensándolo mejor, tengo que ir.}
{304}{}{Recibo un nuevo envío de suministros dos veces al mes. Francamente, me gustaría que vinieran con más frecuencia, pero solo estamos en una
  ruta comercial menor, así que supongo que es lo mejor que podemos obtener.}
{305}{}{No estoy muy seguro. Por lo general, los que pasan por aquí están bastante bien equipados y no están realmente interesados en
 dando vueltas por mucho tiempo. Pero si buscas conectar con uno de ellos, me dirigiría a Redding o incluso a NCR.
 Tienen caravanas bastante activas y siempre se necesita ayuda.}
{306}{}{Interesante. Tenía curiosidad por algo más.}
{307}{}{Gracias. Vamos a comerciar.}
{308}{}{Bien, gracias por la información. Nos vemos.}
{400}{}{¿Conseguiste todo lo que necesitabas?}
{401}{}{La verdad, me gustaría echar otro vistazo a tu mercancía si no es molestia.}
{402}{}{Sí, lo hice. Hasta luego.}
