{100}{}{Ves una bomba de agua.}
{101}{}{Ves una bomba de agua muy vieja que parece estar roto.}
{102}{}{Ahora la bomba de agua funciona correctamente.}
{103}{}{Necesitarás algo más que solo tus manos para arreglar esta máquina. Tal vez algunas herramientas ayudarían con la instalación 
 de esta pieza.}
{104}{}{Has reparado la bomba de agua.}
{105}{}{No has conseguido reparar la bomba.}
{106}{}{Has descubierto de lo que va mal en la bomba de agua.}
{200}{}{Abres la máquina y miras dentro. Ves muchos engranajes y motores oxidados. Uno de los motores
tiene una grieta.}
{201}{}{Lo dejas para otro día.}
{202}{}{Investigar más.}
{203}{}{Upon closer inspection you see that the crack is not the cause of the trouble, but rather
 the connection for where the wires go. The connectors seem to have burned out over the years of use. It's going to
 take a whole new motor as well as a new set of wires to get this machine working again.}
{204}{}{Salir.}
