{100}{}{Ves al guardián del cementerio del monasterio.}
{101}{}{Ves al hermano Samuel, el guardián del cementerio.}
{102}{}{Se ve borracho y un poco adormilado.}
{200}{}{* hickup * Por qué, 'aquí, mi nombre es Samuel. ¿Qué, uh, * hickup * te trae por aquí?}
{201}{}{*hip* Hola de nuevo.}
{202}{}{Solo voy a echar un vistazo. ¿Tiendes a este cementerio?}
{203}{}{¿Conoces a un Padre Tully?}
{204}{}{Padre Tully, ¿dices? [Parece que se está metiendo en el cerebro tratando de recordar.] Sí ... yo * hickup * 'cuerdo a Tully. ¿Cómo está ese chico de todos modos? No lo he visto desde que fue expulsado hace mucho tiempo * hipo * hace mucho tiempo. [Sonríe borracho mientras reflexiona.] Muchacho, era un pitido. Él y yo juntos, * hickup * qué combo.}
{205}{}{Ahora vive en Nuevo Reno, predicando la buena palabra, er, algo así. Sabes, ustedes dos se parecen mucho.}
{206}{}{Nuevo Reno, ¿eh? [Se apoya en su pala, saca una pequeña botella y da un gran trago.] Recuerdo que dijo que iba a *hip* 
 dirigirse hacia allí. Me alegra que llegara allí con seguridad. Siempre *hip* me gustó ese tipo. Un verdadero personaje. 
 Si lo ves de nuevo, dile a Ol' Sammy que todavía está vivo y coleando.}
{207}{}{Lo haré. Aunque tengo algunas preguntas más.}
{208}{}{Lo haré. Cuídate, Sam.}
{209}{}{No importa. Lamento molestarte.}
{210}{}{En realidad, solo iba a decir que él envía sus saludos. Me aseguraré de decirle que también dices hola. Sin embargo tengo algunas otras preguntas.}
{211}{}{En realidad, solo iba a decir que él envía sus saludos. Me aseguraré de decirle que también dices hola. Cuídate Sam.}
{300}{}{¿Qué quieres *hipo* saber?}
{301}{}{¿Eres el guardián del cementerio?}
{302}{}{¿Qué puedes contarme acerca de la Abadía?}
{303}{}{¿Puedo ayudarle en algo?}
{400}{}{Sí, *hip* me encargo de cuidar estas tumbas. Nadie más quiere *hip* hacerlo, así que Ol' Sammy se quedó con el trabajo. 
 No es tan malo como podría parecer. Tiene sus... ventajas, si sabes a qué me refiero. [Sonríe con torpeza y mueve sus cejas pobladas 
 hacia ti.]}
{401}{}{No. No sé a lo que te refieres y no quiero saberlo. Adiós.}
{402}{}{No. No sé a lo que te refieres. Pero déjeme preguntarle otra cosa.}
{403}{}{No. No sé a lo que quires decir, pero tengo una curiosidad mórbida...}
{404}{}{Demonios, sí lo hago. Nada me excita como un cadáver podrido.}
{410}{}{Vaya!, puedo estar al aire libre y nadie está cerca para decirle a Ol' Sammy cuándo ha tenido ¨suficiente¨. 
 ¡Yo sé cuándo he tenido suficiente... cuando no queda nada! [Se ríe, lo que rápidamente se convierte en un horrible acceso de tos. 
 Después de toser hasta expulsar un par de pulmones, sonríe hacia ti.]}
{411}{}{Eh, *por supuesto* eso es lo que quería decir. [Suspiro de alivio]. Sin embargo, permíteme preguntarte otra cosa.}
{420}{}{[Sus ojos se abren con sorpresa y parece estar instantáneamente sobrio.] Eso no es lo que quise decir, tú... ¡ERES UN MONSTRUO, MANÍACO! 
 ¡Aléjate de mí!}
{421}{}{Lo que sea, viejo borracho de mierda. No sabes de lo que te estás perdiendo.}
{430}{}{¡Demonio asqueroso! ¡Fuera!}
{500}{}{La Abadía, bueno, este lugar * hip* ha sido mi 'ogar por la mayor parte de mi vida. Todo mundo 'quí *hipo* es agradable, y 
 cualquier persona es bienvenida, siempre y cuando *hip* no cause problemas. Yo, yo mismo, no paso demasiado tiempo en el mona- 
 *hip* -monasterio, pero sé que nuestros lectores tienen todo tipo de información que se ha recopilado durante los últimos años.
 Tal vez algunos de ellos *hip* pueden ser de alguna utilidad para ti.}
{501}{}{¿No pasas mucho tiempo en la iglesia? Eres un monje, ¿verdad?}
{502}{}{[Se sonríe, mostrando una boca con dientes podridos y espacios vacíos.] *hip* Bueno, digamos que los otros monjes *hip* no 
 ven con buenos ojos mis ejem.. mis habitos con la bebida.}
{503}{}{Tiene sentido, supongo. Tengo algunas preguntas más.}
{504}{}{Supongo que sí. Ya nos veremos, Sammy.}
{505}{}{Ya veo. Mira, debo irme.}
{600}{}{Hmm ... * hickup * déjame ... déjame ver un minuto. Sí, podría tener algo, si estás preparado.}
{601}{}{Eh, olvídelo, Sam. Debo irme ahora.}
{602}{}{Claro, Sam, qué necesitas?}
{603}{}{Bueno, en los últimos días, he visto *hip* que algunas de estas tumbas están siendo desenterradas. Quien sea que lo esté haciendo
  no parece llegar tan lejos, pero es un *hip* un martirio para mí volver a llenarlas.}
{604}{}{Hmm, ¿has intentado averiguar quién ha estado haciendo esto?}
{605}{}{Claro que *hip* lo intenté. La otra vez me quedé hasta la medianoche y nadie apareció. Debo haberme quedado dormido
 poco después de beber demasiado supongo. [Sonríe, saca su frasco y toma un fuerte trago.] Entonces 
 *hip*, ¿qué dices? ¿Quieres ayudar?}
{606}{}{De acuerdo, veré lo que puedo hacer. ¿Sabes also más que pueda ayudarme?}
{607}{}{Bueno, ahora que lo mencionas, recuerdo *hip* que el Sr. Peterson dijo algo acerca de escuchar algunos ruidos que vienen de su campo. 
 Él podría saber algo sobre esto. Él y esa bonita pequeña esposa viven allí mismo. 
 [Señala el edificio al sur del cementerio.]}
{608}{}{Sé lo que podemos hacer.}
{609}{}{Creo que voy a pasar. Debo irme.}
{700}{}{He cuidado de la situación de excavación de las tumbas. No deberíais tener más problemas aquí.}
{701}{}{Bueno, esas son *hickup* buenas noticias. Me alegro de no caer en más tumbas *hickup* abiertas. Gracias por la ayuda.}
{702}{}{Encantado de ayudar. Aunque tengo algunas preguntas.}
{703}{}{Bueno, cuídate, entonces.}
{704}{}{No creo que las tumbas abiertas sean la verdadera razón por la que caes Samuel, pero tomatelo con calma ahora.}
{1000}{}{*Silbas*}
{1001}{}{*Cof* *Cof*}
{1002}{}{*Se aclara la garganta*}
{1003}{}{*Cof*}
{1004}{}{*Suspiro*}
{1005}{}{*Hickup*}
{2000}{}{Ha sido un *hipo* largo día. Vuelve por l'mañana.}
