{100}{}{}
{101}{}{}
{110}{}{Tus pies te pican mucho.}
{120}{}{Te está saliendo un horrible juanete en cada pie.}
{130}{}{Tus zapatos te aprietan mucho; esos juanetes están realmente hinchados.}
{140}{}{El asqueroso juanete en cada pie parece haberse convertido en un dedo extra. Pero, al menos, 
 esa persistente comezón ha desaparecido.}
{141}{}{¡Oh, Dios mío, es Bess!}
{150}{}{Ganas }
{151}{}{ puntos de experiencia por conseguir el GECK.}
{400}{}{No se puede entender una cosa en el texto, pero las ilustraciones son muy informativos.}
{600}{}{Algo no se siente del todo bien en su estómago.}
{601}{}{Se siente una intensa presión en su estómago.}
{700}{}{Adjuntar los pedazos de papel para obtener una lista de tres contraseñas.}
{900}{}{Algo no se siente del todo bien en su estómago.}
{901}{}{Se siente una intensa presión en su estómago.}
