{100}{}{Du ser handlare Bill.}
{101}{}{Du ser en äldre köpman.}
{200}{}{Hallå där, resenär. Jag heter Bill. Vad kan jag ta fram åt dig?}
{201}{}{Välkommen tillbaka. Behöver du något annat?}
{202}{}{Låt oss förhandla.}
{203}{}{Jag har hört att du är mannen man ska prata med om karavaner.}
{204}{}{Det är inte viktigt. Hej då.}
{210}{}{Säg, jag har märkt att en hel del gammal utrustning och föremål har samlats in här i Klostret.
 Jag antar att du inte har hittat något speciellt under din tid här?}
{211}{}{Så du har märkt det, va? Ja, Klosterfolket är lite fascinerade av allt som är från förkrigstiden,
 speciellt om det är teknikrelaterat. De har bildat någon slags knasig religion kring det. Jag förstår det inte riktigt,
 själv, men de är trevliga människor och de betalar bra för allt förkrigstida som jag lyckas få tag på. Men hur som helst,
 när det gäller något speciellt ... hmm, [Han tittar mot Marcus.] Det är roligt att du frågar, jag kanske har något som
 skulle intressera din vän här.}
{212}{}{Så du har märkt det, va? Ja, Klosterfolket är lite fascinerade av allt som är från förkrigstiden,
 speciellt om det är teknikrelaterat. De har bildat någon slags knasig religion kring det. Jag förstår det inte riktigt,
 själv, men de är trevliga människor och de betalar bra för allt förkrigstida som jag lyckas få tag på. Men hur som helst,
 när det gäller något speciellt... hmm, [Han tittar mot din grupp.] Ledsen, jag tror inte att jag har något speciellt som du skulle finna
 användbart just nu.}
{213}{}{Jaha, ja. Låt oss se vad du har i lager istället.}
{214}{}{Det är okej. Låt mig fråga dig något annat.}
{215}{}{Så som?}
{216}{}{En karavan kom hit för inte så länge sen och påstod sig komma från den djupa södern. Sa att de hade
 blivit attackerade av några av de där vidriga mutanterna (vänder sig till Marcus) inget illa menat, stora killen. Hur som helst, de skröt en hel del
 om hur de hade dödat alla mutanter. Påstod att det hade varit nästan ett dussin av dem, och jag trodde att det var skitsnack. Men det visade sig
 att de hade en del bevis.}
{217}{}{Ja? Vad var det?}
{218}{}{En stor mutantrustning som de hade lyckats rädda från ett av liken. Naturligtvis, så vitt jag vet, stal de
 den från benen på någon sedan länge död mutant som de hade snubblat över i ödemarken, men vem vet? Hur som helst, de var int'
 sugna på att släpa runt på den tunga saken, så de erbjöd den till mig för en billig penning. Jag visste inte vad jag någonsin skulle göra
 med den, men jag tänkte att ett fynd är ett fynd.}
{219}{}{Jag är säker på att Marcus här kan dra nytta av detta. Hur mycket kostar det?}
{220}{}{Det var intressant. Marcus här är tuff nog. Jag tror inte att vi behöver den där. Låt mig fråga dig
något annat.}
{221}{}{Den här rackaren kan lätt smältas ner för att göra tre eller fyra uppsättningar metallrustningar. Låt oss säga 3 000 dollar.}
{222}{}{Jag har råd med det.}
{223}{}{Jag tror att jag står över just nu. Låt mig fråga dig något annat.}
{224}{}{Okej, då så. Det kommer att krävas två av oss för att flytta den här saken, så låt mig hjälpa dig att se till att den passar din vän.}
{225}{}{[Färdig]}
{226}{}{Hörru, den passar bra!}
{300}{}{Jag kanske vet en sak eller två. Vad skulle du vilja veta?}
{301}{}{Hur ofta får du nya leveranser?}
{302}{}{Anlitar karavanerna?}
{303}{}{Vid närmare eftertanke måste jag gå.}
{304}{}{Jag får en ny leverans av varor två gånger i månaden. Ärligt talat önskar jag att de skulle komma oftare, men vi är bara på en
 mindre handelsväg så jag antar att det här är det bästa vi kan få.}
{305}{}{I'm not quite sure. Usually, the ones that stop by here are pretty well equipped and not really interested in
 hanging around very long. But if you're looking to hook up with one of em, I'd head over to Redding or even down to NCR.
 They've got pretty active caravans and good help is always wanted.}
{306}{}{Interesting. I was curious about something else.}
{307}{}{Thanks. Let's barter.}
{308}{}{Well, thanks for the information. See you around.}
{400}{}{Found everything you need?}
{401}{}{Actually, I'd like to take another look at your goods.}
{402}{}{Ja, det gjorde jag. Vi ses.}
