{100}{}{Du ser en stark nunna.}
{101}{}{Du ser Elaine.}
{102}{}{Du ser henne fortfarande.}
{200}{}{Hälsningar!}
{201}{}{Hej, vad heter du?}
{202}{}{Vad kan du berätta om Klostret?}
{203}{}{Hej då.}
{300}{}{Om du vill veta mer om vår orden, prata med Abboten. Du hittar honom i hans rum på tredje våningen.}
{301}{}{Jag förstår. Några fler frågor...}
{400}{}{Självklart. Vad skulle du vilja veta?}
{401}{}{Vad heter du?}
{402}{}{Inget egentligen, hej då.}
{403}{}{Vad kan du berätta om Klostret?}
{500}{}{Jag heter Elaine.}
{501}{}{Jag förstår. Några fler frågor...}
{600}{}{Innan du går, kanske du kan göra mig en tjänst. Jag ska ta den här maskindelen till Max i
 kopieringsrummet i källaren. Men du förstår, mitt vänstra knä har krånglat på sistone, och det är en riktig smärta för mig att gå upp och ner
 alla dessa trappor. Skulle det besvära dig alltför mycket att ge honom den här delen åt mig?}
{601}{}{Visst.}
{602}{}{Ledsen, jag har inte tid med det här. Hej då.}
{603}{}{Do I look like your personal delivery service? Do it yourself, you fat lazy bitch. Bye.}
{604}{}{Thanks! Here's the part. The copying room is in the basement. Just use the stairs directly behind Brother Matthew
 in the chapel area.}
{605}{}{Not a problem. [You take the part.] I'll bring it down to Max right away.}
{700}{}{Jag }
{701}{}{. Who you?}
{710}{}{Hehe. That pretty name.}
{711}{}{Hej då!}
{720}{}{You're a special little guy aren't you? Could you do me a BIG favor and be my special helper today?}
{721}{}{You're a special little gal aren't you? Could you do me a BIG favor and be my special helper today?}
{722}{}{Me special. Me help.}
{723}{}{Me no wanna help.}
{730}{}{Really? Great! Please give this machine part to Max in the copying room. He can be found in the BASEMENT. Okay?}
{731}{}{I no let you down!}
{740}{}{You keep on truckin' now.}
