{100}{}{Du ser en stark nunna.}
{101}{}{Du ser Elaine.}
{102}{}{Du ser henne fortfarande.}
{200}{}{Hälsningar!}
{201}{}{Hej, vad heter du?}
{202}{}{Vad kan du berätta om Klostret?}
{203}{}{Hej då.}
{300}{}{Om du vill veta mer om vår orden, prata med Abboten. Du hittar honom i hans rum på tredje våningen.}
{301}{}{Jag förstår. Några fler frågor...}
{400}{}{Självklart. Vad skulle du vilja veta?}
{401}{}{Vad heter du?}
{402}{}{Inget egentligen, hej då.}
{403}{}{Vad kan du berätta om Klostret?}
{500}{}{Jag heter Elaine.}
{501}{}{Jag förstår. Några fler frågor...}
{600}{}{Innan du går, kanske du kan göra mig en tjänst. Jag ska ta den här maskindelen till Max i
 kopieringsrummet i källaren. Men du förstår, mitt vänstra knä har krånglat på sistone, och det är en riktig smärta för mig att gå upp och ner
 alla dessa trappor. Skulle det besvära dig alltför mycket att ge honom den här delen åt mig?}
{601}{}{Visst.}
{602}{}{Ledsen, jag har inte tid med det här. Hej då.}
{603}{}{Ser jag ut som din personliga leveransservice? Gör det själv, din feta, lata subba. Hej då.}
{604}{}{Tack! Här har du delen. Kopieringsrummet ligger i källaren. Använd bara trappan direkt bakom broder Matthew
 i kapellområdet.}
{605}{}{Inga problem. [Du tar delen.] Jag tar ner den till Max på en gång.}
{700}{}{Jag }
{701}{}{. Vem du?}
{710}{}{Hehe. Det fint namn.}
{711}{}{Hej då!}
{720}{}{Du är en speciell liten kille, eller hur? Kan du göra mig en STOR tjänst och vara min speciella hjälpreda idag?}
{721}{}{Du är en speciell liten tjej, eller hur? Kan du göra mig en STOR tjänst och vara min speciella hjälpreda idag?}
{722}{}{Jag speciell. Jag hjälpa.}
{723}{}{Jag inte vill hjälpa.}
{730}{}{Verkligen? Jättebra! Ge den här maskindelen till Max i kopieringsrummet. Han kan hittas i KÄLLAREN. Okej?}
{731}{}{Jag inte svika dig!}
{740}{}{Knata vidare nu.}
