{100}{}{You see a grave marker.}
{101}{}{På gravmarkören står det: }
{102}{}{"Här ligger broder Gregory. En man som inte kände till några gränser."}
{103}{}{"Faster Patty. Skönt att bli av med henne"}
{104}{}{Här ligger Per Joner. Dog en sten för kort."}
{105}{}{"Here lies Father Michael. Founder, Father, Fighter."}
{106}{}{"En ateist. Uppklädd och ingenstans att ta vägen."}
{107}{}{"Here lies Johnny Yeast. Pardon me for not rising."}
{108}{}{"Mary Jane. Kärleksfull hustru och mor."}
{109}{}{”'Schackmatt!' var ropet till käre gamle Jon, På livets schackbräde var han bara en bonde.}
{110}{}{”Herr Johan Märklig, här ligger en ärlig advokat, och han är Märklig.”}
{111}{}{"Tårar kan inte återställa henne -- därför gråter jag.}
{112}{}{"Varje dag på varje sätt blir jag bättre och bättre."}
{250}{}{Det finns inget skrivet på denna gravmarkör.}
{251}{}{Gravmarkören är för sprucken och trasig för att läsas.}
{252}{}{The name on the grave marker reads John Doe.}
{253}{}{The name and date on this headstone have been worn off by the weather.}
