{100}{}{Du ser en Tuff Vakt.}
{101}{}{Du ser en imponerande muskulös, men åldrande vakt med hud bränd av solen. Han måste ha varit något alldeles extra under sina
 bästa dagar. Hans genomträngande blick verkar följa dig överallt.}
{200}{}{Hej på dig, resenär. Välkommen till Klostret. Håll dig på mattan så kommer vi att komma bra överens.}
{201}{}{Jag håller koll på dig, slavhandlare. Ett felsteg och du kommer att besudla vår kyrkogård för resten av evigheten.
 Jag skulle inte önska dig det, och jag är ganska säker på att du inte skulle njuta av det heller, så få inga roliga idéer i din
 snedvridna hjärna.}
{202}{}{Vem är du?}
{203}{}{Var kan jag byta till mig lite förnödenheter?}
{204}{}{Någon gräver upp gravar, varför gör ni inget åt det?}
{205}{}{Jag hörde nåt om djur i källaren. Vet du något om det?}
{206}{}{Jag tror det är dags att jag skickar dig till en grav. Dags att dansa, gamle gubbe.}
{207}{}{Bry dig inte om det. Adjö.}
{300}{}{Ingen... Bara en gammal pensionerad karavanvakt. Många människor misstar mig för någon slags sheriff eftersom jag får
 folk att följa lagen häromkring, men det är jag inte. Jag tar bara hand om det här samhället eftersom jag tycker
 att det är värt att skydda.}
{301}{}{Och i gengäld tar samhället hand om mig. Jag får lite gratis sprit från munkarna, Peterson ser till
 att jag får mat och Bill ser till att jag har ammunition och stimulanter. Inget dåligt pensionärsjobb, om du frågar mig.}
{302}{}{Det är jag som håller ordning på dig, och det är allt du behöver veta. Fortsätt nu med dina affärer och lämna mig
 ensam.}
{303}{}{Det är ett trevligt arrangemang. Låt mig fråga dig något annat.}
{304}{}{Visst, adjö.}
{305}{}{Tror du att du kan håller koll på mig? Låt oss se dig försöka, gamle man. Det här ska bli kul.}
{400}{}{Du kan hitta Bill, vår lokala köpman, i byggnaden mittemot här. Annars bör du gå till Percy's Överlevnadsredskåp
 i skrotgården i Gecko eller Glada Harry's I gården i Valvstaden.}
{401}{}{Bra att veta. Jag har en annan fråga.}
{402}{}{Tack, hej då.}
{500}{}{Om någon är fattig eller girig nog att försöka gräva upp gravar, så är det deras ensak. Det är inte som att de döda kan
 använda det de är begravda med ändå. Inte mitt problem... Jag ligger inte sömnlös på grund av det.}
{501}{}{Låt mig fråga dig något annat.}
{502}{}{Hej då.}
{600}{}{Ja, och broder Thomas saknas. Han var en smart man, men lite dumdristig. Jag vet inte vad som finns där nere,
 men jag tror inte att det bara är en massa råttor och radioaktiva skorpisar.}
{601}{}{Ja, och broder Thomas saknas. Jag vet inte vad som finns där nere, men jag tror inte att det bara är ett gäng råttor
 och radioaktiva skorpisar. Varför tar du inte reda på det, tuffing?}
{602}{}{Så varför går du inte och kollar?}
{603}{}{Du är tuffingen häromkring, eller hur? Varför drar du inte tummen ur röven och går ner dit?}
{610}{}{Det är lite pinsamt, men efter att ha tillbringat så mycket tid utomhus med karavanerna blir jag väldigt nervös när jag
 går under jorden. Väggarna bara sluter sig om mig och jag får svårt att andas... Du kanske kan ta reda på vad som hände med
 Broder Thomas?}
{611}{}{Jag ska se vad jag kan göra. Under tiden vill jag fråga dig en annan sak.}
{612}{}{Hej då.}
{613}{}{Jag är en tuffing, och därför kommer jag att ge dig stryk.}
{700}{}{Vad mer vill du veta?}
{800}{}{Det är trevligt att se dig igen.}
{801}{}{Jag håller ett öga på dig.}
