{100}{}{You see Hank.}
{101}{}{You see a greasy monk.}
{102}{}{He is messing with a still.}
{200}{}{Hey, buddy. Do you have a lighter on you?}
{201}{}{Yep. [Hand your lighter to him.]}
{202}{}{This is perfect. Thanks!}
{203}{}{Out of curiosity, what exactly are you doing here?}
{204}{}{Sure. Since you brought me a lighter, here's one on the house.}
{205}{}{[Drick det.]}
{206}{}{Jag har ändrat mig Jag vill inte ha någon alkohol. Hej då.}
{207}{}{(Du känner dig varm och avslappnad efter att du har druckit vinet).}
{208}{}{Ge me' en till, Hank.}
{209}{}{Jag ska gå nu, hej då.}
{210}{}{(Plötsligt mår du skit, sedan börjar din syn bli suddig. Du faller på marken...)}
{211}{}{[KLAR]}
{212}{}{Nej, tyvärr.}
{213}{}{Hej igen.}
{214}{}{Hej och hej då.}
{215}{}{Den här kommer inte att vara gratis. Den kommer att kosta dig $20.}
{216}{}{Visst. Här är pengarna.}
{217}{}{Nej, jag har fått nog. Kanske nästa gång.}
{218}{}{(Han stoppar pengarna i fickan.) Okej då, här är drinken.}
{219}{}{Jag kommer tillbaka när jag har mer pengar.}
{220}{}{Har du lyckats hitta en tändare?}
{250}{}{Jag skulle vilja köpa lite av alkoholen som ni tillverkar här.}
{251}{}{Jag ser mig bara omkring. Ta hand om dig.}
{252}{}{Visst. $20 flaskan.}
{253}{}{[Håll i den.]}
{300}{}{Var har jag lagt min tändare?}
{301}{}{Jag behöver en tändare.}
{302}{}{KAN NÅGON GE MIG EN TÄNDARE!?}
{303}{}{Eh, hej på dig.}
{304}{}{Tyvärr, jag kan inte snacka med dig nu.}
{400}{}{Åh, titta på alla vackra stjärnor!}
{500}{}{Hallå. Behöver du något?}
{501}{}{Hej, tack igen för tändaren. Den är bättre än min gamla.}
{600}{}{We brew our own alcohol here at the monastery. Some of the most powerful stuff you'll taste in the Wastes.}
{601}{}{Mind if I try some?}
{602}{}{Sounds interesting. I must be going.}
{700}{}{That's too bad. I lost mine recently and I can't seem to find it anywhere. If you ever get a hold of one,
 I'd be glad to take it off your hands.}
{701}{}{Sure. If I come across one I'll let you know. Bye.}
{702}{}{Sorry. I'm a bit of a collector and keep all that I find. Bye.}
{800}{}{Li-ter? I have fire maker. It burn me many times. (You hold up a lighter.)}
{810}{}{Yeah, that's what I need. Will you give it to me?}
{811}{}{Otay. I no likee it.}
{812}{}{I no give you.}
{820}{}{You no now burn self too. Bye!}
