{100}{}{Du ser Hank.}
{101}{}{Du ser en oljig munk.}
{102}{}{Han mixtrar med en destilleringsmaskin.}
{200}{}{Hej, kompis. Har du en tändare på dig?}
{201}{}{Japp. [Ge honom din tändare.]}
{202}{}{Det här är perfekt. Tack för det!}
{203}{}{Av ren nyfikenhet, vad exakt gör du här?}
{204}{}{Visst. Eftersom du gav mig en tändare, så bjuder jag på en.}
{205}{}{[Drick det.]}
{206}{}{Jag har ändrat mig Jag vill inte ha någon alkohol. Hej då.}
{207}{}{(Du känner dig varm och avslappnad efter att du har druckit vinet).}
{208}{}{Ge me' en till, Hank.}
{209}{}{Jag ska gå nu, hej då.}
{210}{}{(Plötsligt mår du skit, sedan börjar din syn bli suddig. Du faller på marken...)}
{211}{}{[KLAR]}
{212}{}{Nej, tyvärr.}
{213}{}{Hej igen.}
{214}{}{Hej och hej då.}
{215}{}{Den här kommer inte att vara gratis. Den kommer att kosta dig $20.}
{216}{}{Visst. Här är pengarna.}
{217}{}{Nej, jag har fått nog. Kanske nästa gång.}
{218}{}{(Han stoppar pengarna i fickan.) Okej då, här är drinken.}
{219}{}{Jag kommer tillbaka när jag har mer pengar.}
{220}{}{Har du lyckats hitta en tändare?}
{250}{}{Jag skulle vilja köpa lite av alkoholen som ni tillverkar här.}
{251}{}{Jag ser mig bara omkring. Ta hand om dig.}
{252}{}{Visst. $20 flaskan.}
{253}{}{[Håll i den.]}
{300}{}{Var har jag lagt min tändare?}
{301}{}{Jag behöver en tändare.}
{302}{}{KAN NÅGON GE MIG EN TÄNDARE!?}
{303}{}{Eh, hej på dig.}
{304}{}{Tyvärr, jag kan inte snacka med dig nu.}
{400}{}{Åh, titta på alla vackra stjärnor!}
{500}{}{Hallå. Behöver du något?}
{501}{}{Hej, tack igen för tändaren. Den är bättre än min gamla.}
{600}{}{Vi brygger vår egen alkohol här i klostret. Några av de starkaste sakerna du kommer att smaka i ödemarkerna.}
{601}{}{Får jag smaka lite?}
{602}{}{Låter intressant. Jag måste gå.}
{700}{}{Det var tråkigt. Jag förlorade min nyligen och jag kan inte hitta den någonstans. Om du någonsin får tag på en,
 skulle jag gärna vilja ha den.}
{701}{}{Visst. Om jag hittar en så hör jag av mig. Hej då.}
{702}{}{Jag är ledsen. Jag är lite av en samlare och behåller allt jag hittar. Hej då.}
{800}{}{Tenn-hare? Jag har en eldgörare. Den bränna mig många gånger. (Du håller upp en tändare.)}
{810}{}{Ja, det är vad jag behöver. Kan du ge den till mig?}
{811}{}{Otej. Jag inte gilla den.}
{812}{}{Jag inte ge dig.}
{820}{}{Du inte bränna dig också nu. Heddå!}
