{100}{}{Du ser Jack, Klostrets sjukvårdare.}
{101}{}{Han har ett rött kors på axeln.}
{200}{}{Om du är skadad, prata med mig.}
{300}{}{Hur kan jag hjälpa dig?}
{301}{}{Jag är skadad, kan du hjälpa mig?}
{302}{}{[Dräggel.]}
{303}{}{Så vad gör du här på Klostret?}
{304}{}{Hej då.}
{400}{}{Det är färdigt!}
{401}{}{Tack.}
{402}{}{Sluta med det där!}
{403}{}{[FORTSÄTT]}
{404}{}{[LÄMNA]}
{405}{}{SLUTA! SLUTA! SLUTA!}
{406}{}{[FORTSÄTT]}
{407}{}{[SLUTA]}
{408}{}{(Plötsligt börjar Jack smälta.) JAG SMÄLTER, JAG SMÄLTER, ÅH VILKEN VÄRLD...}
{409}{}{Vad i hel...}
{500}{}{Stjäl inte mina medicinska förnödenheter!}
{501}{}{Du får %d erfarenhetspoäng för att ha fått Jack att smälta. Är du glad nu, din sjuka jävel?}
{600}{}{Jag är läkare. Jag har tagit hand Klostrets folk i ungefär, åh, femton år nu, tror jag.}
{601}{}{Jag förstår. Det låter som många år av att studera alla medicinska böcker från förkrigstiden i Klostrets bibliotek. Du måste vara en riktigt bra doktor.}
{602}{}{Var fick du tag på all din medicinska utrustning?}
{603}{}{Intressant. Jag tror att jag ska gå nu.}
{604}{}{[He frowns.] I fancy myself a fine doctor, but I can't credit the books for that since I'm not even allowed to... never mind, I won't get into that. My father was a doctor, and he passed his knowledge down to me.}
{605}{}{Åh, jag förstår.}
{700}{}{En del av medicinerna fick jag av min far. De flesta av de andra fanns redan här i Klostret.}
{701}{}{Intressant, hej då.}
{702}{}{Tror du att du kan ge mig lite av dina mediciner? Du verkar ha mer än du använder.}
{703}{}{You want me to just *give* them to you? What makes you think you deserve them more than the people of the Abbey?}
{704}{}{Because I tend to get hurt... a lot.}
{705}{}{Because I'm on a holy quest to find a Garden Of Eden Creation Kit. You see, my entire village will perish if
 I don't find this device in time. Your people, on the other hand, seem to live a peaceful life without much need for so
 much healing equipment. I'm not asking for a lot, even the smallest amount you could give me would help me greatly.}
{706}{}{[He ponders over your words for a moment, then nods.] Alright, I'll give you some of our excess medical supplies.
 It sounds like you're gonna need 'em. Here. [He hands them to you.] Good luck, wanderer.}
{707}{}{Thanks, Jack. You're a true savior of the wastes. Bye.}
{708}{}{Then perhaps you should learn to be more careful. Sorry, I'm not going to just give away the Abbey's medical supplies.}
{709}{}{Fine. GOODBYE.}
{800}{}{I can't talk right now.}
{801}{}{Sorry, I'm in the middle of something now. Come see me later.}
{802}{}{Hello again.}
