{100}{}{Du ser Jack, Klostrets sjukvårdare.}
{101}{}{Han har ett rött kors på axeln.}
{200}{}{Om du är skadad, prata med mig.}
{300}{}{Hur kan jag hjälpa dig?}
{301}{}{Jag är skadad, kan du hjälpa mig?}
{302}{}{[Dräggel.]}
{303}{}{Så vad gör du här på Klostret?}
{304}{}{Hej då.}
{400}{}{Det är färdigt!}
{401}{}{Tack.}
{402}{}{Sluta med det där!}
{403}{}{[FORTSÄTT]}
{404}{}{[LÄMNA]}
{405}{}{SLUTA! SLUTA! SLUTA!}
{406}{}{[FORTSÄTT]}
{407}{}{[SLUTA]}
{408}{}{(Plötsligt börjar Jack smälta.) JAG SMÄLTER, JAG SMÄLTER, ÅH VILKEN VÄRLD...}
{409}{}{Vad i hel...}
{500}{}{Stjäl inte mina medicinska förnödenheter!}
{501}{}{Du får %d erfarenhetspoäng för att ha fått Jack att smälta. Är du glad nu, din sjuka jävel?}
{600}{}{Jag är läkare. Jag har tagit hand Klostrets folk i ungefär, åh, femton år nu, tror jag.}
{601}{}{Jag förstår. Det låter som många år av att studera alla medicinska böcker från förkrigstiden i Klostrets bibliotek. Du måste vara en riktigt bra doktor.}
{602}{}{Var fick du tag på all din medicinska utrustning?}
{603}{}{Intressant. Jag tror att jag ska gå nu.}
{604}{}{[Han rynkar pannan.] Jag tycker att jag är en bra läkare, men jag kan inte ge böckerna äran för det eftersom jag inte ens får... glöm det, jag ska inte gå in på det. Min far var läkare och han förde sin kunskap vidare till mig.}
{605}{}{Åh, jag förstår.}
{700}{}{En del av medicinerna fick jag av min far. De flesta av de andra fanns redan här i Klostret.}
{701}{}{Intressant, hej då.}
{702}{}{Tror du att du kan ge mig lite av dina mediciner? Du verkar ha mer än du använder.}
{703}{}{Vill du att jag bara ska *ge* dem till dig? Vad får dig att tro att du förtjänar dem mer än folket i Klostret?}
{704}{}{För att jag brukar bli skadad... ofta.}
{705}{}{Because I'm on a holy quest to find a Garden Of Eden Creation Kit. You see, my entire village will perish if
 I don't find this device in time. Your people, on the other hand, seem to live a peaceful life without much need for so
 much healing equipment. I'm not asking for a lot, even the smallest amount you could give me would help me greatly.}
{706}{}{[Han funderar över dina ord ett ögonblick och nickar sedan.] Okej, jag ska ge dig lite av vår överblivna medicinska utrustning.
 Det låter som om du kommer att behöva dem. Här. [Han ger dem till dig.] Lycka till, vandrare.}
{707}{}{Tack, Jack. Du har räddat mig från ödemarkens faror. Adjö.}
{708}{}{Då kanske du borde lära dig att vara mer försiktig. Ledsen, men jag tänker inte bara ge bort Klostrets medicinska utrustning.}
{709}{}{Okej. HEJ DÅ.}
{800}{}{Jag kan inte prata just nu.}
{801}{}{Ledsen, jag är mitt uppe i något nu. Kom och träffa mig senare.}
{802}{}{Hej igen.}
