{100}{}{Du ser en ung munk med glasögon.}
{101}{}{Du ser broder Jason.}
{102}{}{Den här munken verkar grubbla.}
{200}{}{[Den unge munken plockar snabbt fram en "Tragik"-kortlek när du närmar dig.] Vad är det du vill?}
{201}{}{Inget från dig. Hej då.}
{202}{}{Jag vill veta varför du just gömde kortleken för mig.}
{210}{}{Jag vet inte vad du pratar om. Jag har inte någon kortlek.}
{211}{}{Ljug inte för mig. Jag såg att du stoppade ner den i fickan. Jag ville bara veta varför.}
{212}{}{Okej, vad du än säger. Vi ses.}
{220}{}{Berätta inte för någon, okej? Det är inte meningen att vi ska "använda" reliker från förkrigstiden, bara dyrka dem. Men dessa Tragik-
 korten är så jävla coola. [Han verkar försvinna in i en annan värld medan han tittar kärleksfullt på kortleken. Efter en stund,
 tittar han upp på dig.] Åh, förlåt. Jag är broder Jason förresten. Jag antar att du inte spelar Tragik?}
{221}{}{ÅKALLA HOPSAMLANDET!!!}
{222}{}{Ja, för fan, jag älskar Tragik, Hopsamlingen.}
{223}{}{Jag har provat det, men det är inget för mig.}
{224}{}{Jag brukade vara beroende som fan av det spelet. Jag försöker hålla mig borta från det nu.}
{225}{}{Näpp.}
{226}{}{Nej, för fan. Ser jag ut som en patetisk förlorare?}
{230}{}{Dra åt helvete, din skitstövel. Lämna mig bara ifred.}
{231}{}{Dra åt helvete, din hora. Lämna mig bara ifred.}
{232}{}{Jag skulle gärna göra det, men jag är överväldigad av en önskan att göra dig stor kroppslig skada.}
{233}{}{Okej, bra. Hej då.}
{234}{}{Jag är ledsen. Det var oförskämt av mig. Jag är bara inte ett fan av Tragik.}
{240}{}{Jag skulle gärna spela mot dig, men det är för riskabelt. Jag vill inte att de här tas ifrån mig. Det är det jag hatar
 med det här stället. Vi sitter på en jäkla guldgruva av fantastiska saker från före kriget, men vi förbjuder oss själva
 från att njuta av det. Det är helt obegripligt. Det är helt jävla idiotiskt.}
{241}{}{Ah man, jag vet vad du menar. Jag önskar att jag kunde spela mer själv, men det är för riskabelt. Jag vill inte att de här ska tas ifrån mig.
 Det är det jag hatar med det här stället. Vi sitter på en jäkla guldgruva av fantastiska saker från före kriget, men vi
 förbjuder oss själva från att njuta av det. Det är helt obegripligt. Det är helt jävla idiotiskt.}
{242}{}{[Han skrattar.] Vi har en missbrukare på halsen här, ser jag. Jag önskar att jag kunde spela mer själv, men det är för riskabelt.
 Jag vill inte att de här tas ifrån mig. Det är det jag hatar med det här stället. Vi sitter på en jäkla guldgruva av fantastiska saker
 från före kriget, men vi förbjuder oss själva från att njuta av det. Det är helt obegripligt. Det är helt jävla idiotiskt.}
{243}{}{Det spelar ingen roll, vi skulle ändå inte kunna spela - det är för riskabelt. Jag vill inte att de här ska tas ifrån mig. Det är det
 jag hatar med det här stället. Vi sitter på en jäkla guldgruva av fantastiska saker från före kriget, men vi förbjuder oss själva
 från att njuta av det. Det är helt obegripligt. Det är helt jävla idiotiskt.}
{244}{}{Ja, det låter dumt.}
{245}{}{Om du inte håller med om din ordens ideal, varför är du då en munk?}
{250}{}{Tror du att jag valde att bli munk? Jag föddes in i den här skitlivsstilen. Jag önskar bara att de andra skulle vakna upp och
 se hur dumt det är att inte dra nytta av allt det här fina vi har samlat på oss. Men nej, de är helt nöjda med att
 dyrka och katalogisera relikerna, men aldrig göra något användbart med dem. Som jag sa, det är jävligt idiotiskt.}
{251}{}{Du har en poäng, det låter ganska dumt.}
{252}{}{Lika korkad som jag som sitter här och lyssnar på dig när du gnäller om ditt liv. Hej då.}
{253}{}{Om du tycker att det är så dumt, varför gör du då inte något för att försöka ändra på saker och ting?}
{260}{}{Äntligen någon som håller med mig! Jag har en idé, och du kanske kan hjälpa mig. Du förstår, munkarna
 här har spenderat *år* med att transkribera förkrigsinformation till vår databas. Om någon skulle "råka"
 formatera databasen, skulle de förlora allt det arbetet. Jag tror att något sådant kan chocka dem tillbaka till sina sinnen och vi
 kanske äntligen ger upp detta dumma sätt att leva. Så, vad säger du?}
{261}{}{Jag säger att det är en hemsk idé och att jag har pratat färdigt med dig.}
{262}{}{Radera åratal av någon annans hårda arbete? Låter kul. Jag fixar det.}
{263}{}{Varför formaterar du det inte själv?}
{264}{}{Om du hatar att vara här, varför åker du inte bara härifrån?}
{270}{}{Jag har faktiskt en idé om hur man kan förändra saker. Du kanske kan hjälpa mig. Du förstår, munkarna här har
 tillbringat *år* med att transkribera förkrigsinformation till vår databas. Om någon skulle råka formatera
 databasen, skulle de förlora allt det arbetet. Jag tror att något sådant kan chocka dem tillbaka till sina sinnen och vi kan äntligen
 ge upp det här dumma sättet att leva. Så, vad säger du?}
{271}{}{Jag säger att det är en hemsk idé och att jag har pratat färdigt med dig.}
{272}{}{Radera hundratals år av någon annans hårda arbete? Låter kul. Jag gör det.}
{273}{}{Varför formaterar du det inte själv?}
{274}{}{Om du hatar att vara här, varför åker du inte bara härifrån?}
{280}{}{Skojar du med mig? De skulle korsfästa mig om jag gjorde det. Du däremot, du är en erfaren äventyrare. Fan, jag slår vad om
 att du skulle kunna massakrera alla här utan att svettas. Så kommer du att göra det, eller är du rädd för ett gäng pacifistiska munkar?}
{281}{}{Jag är inte rädd för någon. Jag gör det.}
{282}{}{Okej, då. Jag gör det.}
{283}{}{Nä, istället tror jag att jag ska testa din massakerteori. Jag börjar med dig.}
{284}{}{Jag står över. Det är bara inte min stil. Hej då.}
{285}{}{Nej, jag tänker inte göra det. Om du hatar att vara här, varför flyttar du inte bara?}
{286}{}{Om du inte har ändrat dig om att hjälpa mig, så dra åt helvete.}
{287}{}{Okej, då. Jag gör det.}
{288}{}{Nej, jag tänker inte göra det. Om du hatar att vara här, varför flyttar du inte bara?}
{290}{}{Gör du det? Allvarligt? Åh, det är ju fantastiskt. Men först måste du få tillgång, för de skyddar databasen ganska
 noga. Men det borde inte vara så svårt, de här munkarna litar ganska enkelt på andra. De kommer att bli skitförbannade när
 du formaterar den, men de är ett gäng mesar, så oroa dig inte för det. Försök bara att inte döda någon -- jag vill inte att saker
 ska gå för långt, vet du?}
{291}{}{Visst. Något annat?}
{292}{}{Jag ger inga löften. Var det något mer?}
{300}{}{Formatera den och stick sen, för de vill inte ha dig här. Bry dig inte ens om att komma och berätta för mig
 att du gjorde det, för jag måste låtsas vara lika förbannad som alla andra, annars misstänker de att något är på gång. Tack igen för att du
 gör det här. Det är för deras eget bästa.}
{301}{}{Om du säger det så. Hej då.}
{310}{}{Är du inte klok? Jag har aldrig varit ute i ödemarken, men jag har en jävligt bra uppfattning om hur det är. Jag skulle
 ha tur om jag klarar mig femtio meter innan en radioaktiv skorpion kör upp en meterlång gadd i röven på mig. Eller ännu värre, jag skulle bli tillfångatagen
 och torterad av ett gäng galna plundrare *eller* så skulle jag bli uppäten levande av en kannibalistisk stam. Hur som helst. Jag vet bara att om
 jag drar härifrån, skulle jag vara körd. Så nej, jag är fast här.}
{311}{}{Det är inte *så* illa där ute... Faktiskt, så har du rätt. Du skulle förmodligen inte ens ta dig till Gecko.
 Åtminstone inte utan hjälp. Men tänk om jag sa att jag skulle eskortera dig?}
{312}{}{Sucks to be you. Bye.}
{313}{}{Håll hoppet uppe. Jag är säker på att det finns en stad i närheten som är säker att resa till.}
{315}{}{Ja, om du hittar en, så säg till.}
{316}{}{Fixar det. Hej då.}
{320}{}{Till Gecko? Det är ghulstaden, eller hur? Tack, men nej tack.}
{321}{}{Ghulerna där är faktiskt riktigt vänliga. Dessutom vet jag en som älskar ett bra parti Tragik.}
{322}{}{Hörru, ghulerna där är faktiskt riktigt trevliga.}
{323}{}{Hörru, jag har hört att ghulerna där faktiskt är riktigt trevliga.}
{324}{}{Okej, då. Skyll dig själv. Adjö.}
{330}{}{No shit, another Tragic player? Hmm, that kind of changes things... I wonder if he'd have a Black Dahlia to
 trade. Alright. I'll go if you'll escort me.}
{331}{}{Komså går vi.}
{332}{}{Okej, men jag måste ta hand om några saker först. Jag hör av mig när jag är redo att resa.}
{340}{}{Jasså? Det ändrar inte det faktum att de ser ut som brahminskit. Nej tack.}
{341}{}{Okej, då. Skyll dig själv. Adjö.}
{350}{}{Vad vill du?}
{351}{}{Jag ville bara säga hej. Vi ses.}
{352}{}{Jag ändrade mig. Jag ska formatera datorn åt dig.}
{353}{}{Du kanske vill tänka lite mer på mitt erbjudande att ta dig till Gecko, för jag känner
 någon där som älskar att spela Tragik.}
{354}{}{Jag känner nån i Gecko som älskar att spela Tragik. Jag kan ta med dig dit.}
{360}{}{Är vi redo att dra snart? Jag vill gärna veta vad för slags Tragik-kort den här snubben har.}
{361}{}{Okej, då drar vi.}
{362}{}{Inte än. Jag hör av mig.}
{370}{}{[När ni anländer till Gecko presenterar du den unge munken för Wooz. De kommer snabbt överens och börjar jämföra sina
 Tragik-kortlekar. Du är på väg att gå därifrån när broder Jason drar sig undan från Tragik länge nog för att snacka lite med dig].}
{371}{}{[MER]}
{372}{}{Holy shit, Wooz *does* have a Black Dahlia! That alone has made this trip worthwhile. Sure, the ghouls are ugly
 as hell, but I found if I take off my glasses, then they're kinda tolerable. Anyway, thanks a lot for bringing me. Here,
 I, uh, "borrowed" this from the Abbey's Memorabilia, amazingly it's one of the few tech relics that still works.
 [He hands you a Stealth Boy.] See ya.}
{373}{}{Tack. Hej då.}
{374}{}{Jag är bara glad att jag slipper höra dig gnälla mer. Hej då.}
{380}{}{Holy shit, Wooz *does* have a Black Dahlia! That alone has made this trip worthwhile. Sure, the ghouls are ugly
 as hell, but I found if I take off my glasses, then they're kinda tolerable. Anyway, thanks a lot for bringing me here.
 Here, [He reaches into his pocket, then frowns.] what the hell? I could swear I had it. Uh, sorry, but looks like I misplaced
 your reward, so you'll have to make due with a simple thanks. See ya.}
{381}{}{Oroa dig inte för det. Jag är bara glad att jag kunde hjälpa till. Hej då.}
{382}{}{Jag är bara glad att jag slipper höra dig gnälla mer. Hej då.}
{400}{}{Kan inte prata... måste bygga en starkare kortlek...}
{500}{}{Lämna mig ifred.}
{501}{}{Gå härifrån.}
{502}{}{Dra åt helvete.}
{600}{}{Åh, hej, det är du. Nån sprängde reaktorn vid Gecko och alla ghuler stack. Ingen anledning för mig att stanna där,
 så jag gick därifrån och kom tillbaka hit. Lyckligtvis för mig ifrågasatte inte munkarna här min frånvaro, så jag är inte i trubbel för att jag stack.
 Det här suger dock, jag trodde att jag skulle få ett nytt liv och göra det jag älskar. [Han suckar djupt]}
{601}{}{Det var tråkigt att höra. Vi ses.}
{602}{}{Sånt är livet. Ena stunden är du på toppen av världen och i nästa stund ligger du med ansiktet i leran. Lev och lär. Hej då.}
{610}{}{Antar att jag bara får vänja mig vid det här stället.}
{1000}{}{Du eskorterar broder Jason säkert till hans nya hem.}
