{100}{}{You see a bespectacled young monk.}
{101}{}{Du ser broder Jason.}
{102}{}{Den här munken verkar grubbla.}
{200}{}{[Den unge munken plockar snabbt fram en "Tragik"-kortlek när du närmar dig.] Vad är det du vill?}
{201}{}{Inget från dig. Hej då.}
{202}{}{Jag vill veta varför du just gömde kortleken för mig.}
{210}{}{Jag vet inte vad du pratar om. Jag har inte någon kortlek.}
{211}{}{Ljug inte för mig. Jag såg att du stoppade ner den i fickan. Jag ville bara veta varför.}
{212}{}{Okej, vad du än säger. Vi ses.}
{220}{}{Berätta inte för någon, okej? Det är inte meningen att vi ska "använda" reliker från förkrigstiden, bara dyrka dem. Men dessa Tragik-
 korten är så jävla coola. [Han verkar försvinna in i en annan värld medan han tittar kärleksfullt på kortleken. Efter en stund,
 tittar han upp på dig.] Åh, förlåt. Jag är broder Jason förresten. Jag antar att du inte spelar Tragik?}
{221}{}{ÅKALLA HOPSAMLANDET!!!}
{222}{}{Ja, för fan, jag älskar Tragik, Hopsamlingen.}
{223}{}{Jag har provat det, men det är inget för mig.}
{224}{}{Jag brukade vara beroende som fan av det spelet. Jag försöker hålla mig borta från det nu.}
{225}{}{Näpp.}
{226}{}{Nej, för fan. Ser jag ut som en patetisk förlorare?}
{230}{}{Dra åt helvete, din skitstövel. Lämna mig bara ifred.}
{231}{}{Dra åt helvete, din hora. Lämna mig bara ifred.}
{232}{}{Jag skulle gärna göra det, men jag är överväldigad av en önskan att göra dig stor kroppslig skada.}
{233}{}{Okej, bra. Hej då.}
{234}{}{Jag är ledsen. Det var oförskämt av mig. Jag är bara inte ett fan av Tragik.}
{240}{}{Jag skulle gärna spela mot dig, men det är för riskabelt. Jag vill inte att de här tas ifrån mig. Det är det jag hatar
 med det här stället. Vi sitter på en jäkla guldgruva av fantastiska saker från före kriget, men vi förbjuder oss själva
 från att njuta av det. Det är helt obegripligt. Det är helt jävla idiotiskt.}
{241}{}{Ah man, jag vet vad du menar. Jag önskar att jag kunde spela mer själv, men det är för riskabelt. Jag vill inte att de här ska tas ifrån mig.
 Det är det jag hatar med det här stället. Vi sitter på en jäkla guldgruva av fantastiska saker från före kriget, men vi
 förbjuder oss själva från att njuta av det. Det är helt obegripligt. Det är helt jävla idiotiskt.}
{242}{}{[Han skrattar.] Vi har en missbrukare på halsen här, ser jag. Jag önskar att jag kunde spela mer själv, men det är för riskabelt.
 Jag vill inte att de här tas ifrån mig. Det är det jag hatar med det här stället. Vi sitter på en jäkla guldgruva av fantastiska saker
 från före kriget, men vi förbjuder oss själva från att njuta av det. Det är helt obegripligt. Det är helt jävla idiotiskt.}
{243}{}{Det spelar ingen roll, vi skulle ändå inte kunna spela - det är för riskabelt. Jag vill inte att de här ska tas ifrån mig. Det är det
 jag hatar med det här stället. Vi sitter på en jäkla guldgruva av fantastiska saker från före kriget, men vi förbjuder oss själva
 från att njuta av det. Det är helt obegripligt. Det är helt jävla idiotiskt.}
{244}{}{Ja, det låter dumt.}
{245}{}{Om du inte håller med om din ordens ideal, varför är du då en munk?}
{250}{}{Tror du att jag valde att bli munk? Jag föddes in i den här skitlivsstilen. Jag önskar bara att de andra skulle vakna upp och
 se hur dumt det är att inte dra nytta av allt det här fina vi har samlat på oss. Men nej, de är helt nöjda med att
 dyrka och katalogisera relikerna, men aldrig göra något användbart med dem. Som jag sa, det är jävligt idiotiskt.}
{251}{}{Du har en poäng, det låter ganska dumt.}
{252}{}{Lika korkad som jag som sitter här och lyssnar på dig när du gnäller om ditt liv. Hej då.}
{253}{}{Om du tycker att det är så dumt, varför gör du då inte något för att försöka ändra på saker och ting?}
{260}{}{Äntligen någon som håller med mig! Jag har en idé, och du kanske kan hjälpa mig. Du förstår, munkarna
 här har spenderat *år* med att transkribera förkrigsinformation till vår databas. Om någon skulle "råka"
 formatera databasen, skulle de förlora allt det arbetet. Jag tror att något sådant kan chocka dem tillbaka till sina sinnen och vi
 kanske äntligen ger upp detta dumma sätt att leva. Så, vad säger du?}
{261}{}{Jag säger att det är en hemsk idé och att jag har pratat färdigt med dig.}
{262}{}{Radera åratal av någon annans hårda arbete? Låter kul. Jag fixar det.}
{263}{}{Varför formaterar du det inte själv?}
{264}{}{Om du hatar att vara här, varför åker du inte bara härifrån?}
{270}{}{Jag har faktiskt en idé om hur man kan förändra saker. Du kanske kan hjälpa mig. Du förstår, munkarna här har
 tillbringat *år* med att transkribera förkrigsinformation till vår databas. Om någon skulle råka formatera
 databasen, skulle de förlora allt det arbetet. Jag tror att något sådant kan chocka dem tillbaka till sina sinnen och vi kan äntligen
 ge upp det här dumma sättet att leva. Så, vad säger du?}
{271}{}{Jag säger att det är en hemsk idé och att jag har pratat färdigt med dig.}
{272}{}{Radera hundratals år av någon annans hårda arbete? Låter kul. Jag gör det.}
{273}{}{Varför formaterar du det inte själv?}
{274}{}{Om du hatar att vara här, varför åker du inte bara härifrån?}
{280}{}{Skojar du med mig? De skulle korsfästa mig om jag gjorde det. Du däremot, du är en erfaren äventyrare. Fan, jag slår vad om
 att du skulle kunna massakrera alla här utan att svettas. Så kommer du att göra det, eller är du rädd för ett gäng pacifistiska munkar?}
{281}{}{Jag är inte rädd för någon. Jag gör det.}
{282}{}{Okej, då. Jag gör det.}
{283}{}{Nä, istället tror jag att jag ska testa din massakerteori. Jag börjar med dig.}
{284}{}{Jag står över. Det är bara inte min stil. Hej då.}
{285}{}{Nej, jag tänker inte göra det. Om du hatar att vara här, varför flyttar du inte bara?}
{286}{}{Om du inte har ändrat dig om att hjälpa mig, så dra åt helvete.}
{287}{}{Okej, då. Jag gör det.}
{288}{}{Nej, jag tänker inte göra det. Om du hatar att vara här, varför flyttar du inte bara?}
{290}{}{You will? Seriously? Oh man, that's awesome. But first, you'll need to get access, 'cause they're pretty protective
 of the database. It shouldn't be too hard though, these monks are pretty trusting. They're gonna be pissed as hell when
 you format it, but they're all a bunch of wimps, so don't worry about it. Just try not to kill anyone -- I don't want things
 to get too out of hand, you know?}
{291}{}{Sure. Anything else?}
{292}{}{Jag ger inga löften. Var det något mer?}
{300}{}{Just format it, then take off, cause they're not going to want you around here. Don't even bother to come tell me
 you did it, because I'll have to act just as pissed as everyone else or they'll suspect something's up. Thanks again for
 doing this. It's for their own good.}
{301}{}{Whatever you say. Bye.}
{310}{}{Are you crazy? I've never been out in the wastes, but I've got a pretty damn good idea as to what it's like. I'd
 be lucky to make if fifty yards before a radscorpion shoved a foot-long stinger up my ass. Or even worse, I'd get captured
 and tortured by a gang of maniac raiders *or* I'd be eaten alive by cannibalistic tribals. Whatever. I just know that if
 I left here, I'd be fucked. So no, I'm stuck here.}
{311}{}{Hey, it's not *that* bad out there... Actually, you're right. You probably wouldn't even make it to Gecko.
 At least, not without help. But what if I said I'd escort you?}
{312}{}{Sucks to be you. Bye.}
{313}{}{Keep your hopes up. I'm sure there is a town nearby that would be safe to travel to.}
{315}{}{Yeah, well if you find one, let me know.}
{316}{}{Will do. Bye.}
{320}{}{To Gecko? That's the ghoul town, right? Thanks, but no thanks.}
{321}{}{Hey, the ghouls there are actually really friendly. Besides, I know one in particular that loves a good game of Tragic.}
{322}{}{Hey, the ghouls there are actually really friendly.}
{323}{}{Hey, I hear the ghouls there are actually really friendly.}
{324}{}{Alright. Suit yourself. Bye.}
{330}{}{No shit, another Tragic player? Hmm, that kind of changes things... I wonder if he'd have a Black Dahlia to
 trade. Alright. I'll go if you'll escort me.}
{331}{}{Lets go.}
{332}{}{Alright, but I need to take care of some things first. I'll let you know when I'm ready to go.}
{340}{}{Oh yeah? That doesn't change the fact that they look like brahmin shit. No thanks.}
{341}{}{Alright. Suit yourself. Bye.}
{350}{}{Vad vill du?}
{351}{}{I just wanted to say hi. See ya.}
{352}{}{I changed my mind. I'll format the computer for you.}
{353}{}{Hey, you might want to reconsider my offer to take you to Gecko, because I know
 someone there that loves a good game of Tragic.}
{354}{}{Hey, I know someone in Gecko that loves a good game of Tragic. I could take you there.}
{360}{}{Are we ready to go yet? I'm dying to know what kind of Tragic cards this guy's got.}
{361}{}{Alright, let's go.}
{362}{}{Not yet. I'll let you know.}
{370}{}{[Upon arriving in Gecko you introduce the young monk to Wooz. They quickly hit it off and begin comparing their
 Tragic card decks. You're about to leave when Brother Jason pulls himself away from Tragic long enough to have a word with you.]}
{371}{}{[MER]}
{372}{}{Holy shit, Wooz *does* have a Black Dahlia! That alone has made this trip worthwhile. Sure, the ghouls are ugly
 as hell, but I found if I take off my glasses, then they're kinda tolerable. Anyway, thanks a lot for bringing me. Here,
 I, uh, "borrowed" this from the Abbey's Memorabilia, amazingly it's one of the few tech relics that still works.
 [He hands you a Stealth Boy.] See ya.}
{373}{}{Tack. Hej då.}
{374}{}{I'm just happy I won't have to hear you bitch anymore. Bye.}
{380}{}{Holy shit, Wooz *does* have a Black Dahlia! That alone has made this trip worthwhile. Sure, the ghouls are ugly
 as hell, but I found if I take off my glasses, then they're kinda tolerable. Anyway, thanks a lot for bringing me here.
 Here, [He reaches into his pocket, then frowns.] what the hell? I could swear I had it. Uh, sorry, but looks like I misplaced
 your reward, so you'll have to make due with a simple thanks. See ya.}
{381}{}{Oh, uh, don't worry about it. Just glad I could help. Bye.}
{382}{}{I'm just happy I won't have to hear you bitch anymore. Bye.}
{400}{}{Can't talk... must build more powerful deck...}
{500}{}{Leave me alone.}
{501}{}{Go away.}
{502}{}{Fuck off.}
{600}{}{Oh, hey, it's you. Somebody blew up the reactor at Gecko and all the ghouls left. No reason for me to stay there,
 so I left and came back here. Luckily for me the monks here didn't question my absence, so I'm not in any trouble for leaving.
 This sucks though, I thought I was going to have a new life doing what I love. [He sighs deeply]}
{601}{}{Sorry to hear that. See you around.}
{602}{}{That's life. One minute you're on top of the world and the next instant you're face down in the mud. Live and learn. Bye.}
{610}{}{Guess I just gotta get used to this place.}
{1000}{}{You safely escort Brother Jason to his new home.}
