{100}{}{You see Brother John.}
{101}{}{You see one of the Abbey's older Monks.}
{102}{}{Du ser en gammal munk. Han ser ut att vara i början av sjuttioårsåldern.}
{300}{}{Hej på dig, lillkisen.}
{301}{}{Vem är du?}
{302}{}{Have you heard anything about a GECK or Vault 13?}
{303}{}{Hej då.}
{400}{}{Mitt namn är John, jag är en av de äldsta munkarna här.}
{401}{}{Så, vad är ditt jobb?}
{402}{}{Jag förstår, hej då.}
{403}{}{Jag brukade jobba på en gård, men det var dåligt för mitt hjärta.}
{404}{}{Har du hjärtproblem?}
{405}{}{Det är synd, hej då!}
{406}{}{Yeah, I have a bad heart. If I still had my heart pills, it would ease my life a lot more. It is very difficult
 to find medicine for that problem in today's world you know.}
{407}{}{I might have a solution for your heart problems...}
{408}{}{Sorry to hear that, Bye.}
{410}{}{Hej då.}
{411}{}{You do? Are you saying that you actually HAVE heart pills?}
{412}{}{Yes, I do. It would be a pleasure to give them to you.}
{413}{}{Yeah, I have heart pills. You can have them for $400.}
{414}{}{I was only joking. I don't have any heart pills.}
{415}{}{[He takes the pills from you.] Thank you, my friend! Here, please take this item as a gesture of gratitude.}
{416}{}{Happy to help, and thanks for the item. Bye!}
{417}{}{(He becomes quite angry, but then calms down) Ok, fine, here's your money. Now give me the pills!}
{418}{}{I have decided to keep the pills myself. Thanks for the money!}
{419}{}{Nice doing business with you, Bye.}
{420}{}{Hmmm, sorry, I haven't. Talk to the Abbot, he might know something.}
{421}{}{I'll do that, thanks. Now I have some other questions.}
{422}{}{If I weren't so sick, I would beat the shit out of you. NOW GET OUT OF HERE!}
{423}{}{Fine, I'll go.}
{500}{}{Thank you again for those heart pills, my friend. Good luck on your travels.}
{600}{}{Just go away, please.}
{700}{}{You showed John just how cruel the world is.}
