{100}{}{Du ser broder John.}
{101}{}{Du ser en av Klostrets äldre munkar.}
{102}{}{Du ser en gammal munk. Han ser ut att vara i början av sjuttioårsåldern.}
{300}{}{Hej på dig, lillkisen.}
{301}{}{Vem är du?}
{302}{}{Har du hört något om en GECK eller Valv 13?}
{303}{}{Hej då.}
{400}{}{Mitt namn är John, jag är en av de äldsta munkarna här.}
{401}{}{Så, vad är ditt jobb?}
{402}{}{Jag förstår, hej då.}
{403}{}{Jag brukade jobba på en gård, men det var dåligt för mitt hjärta.}
{404}{}{Har du hjärtproblem?}
{405}{}{Det är synd, hej då!}
{406}{}{Ja, jag har ett dåligt hjärta. Om jag fortfarande hade mina hjärtpiller skulle det underlätta mitt liv mycket mer. Det är väldigt svårt
 att hitta medicin för det problemet i dagens värld, vet du.}
{407}{}{Jag kanske har en lösning på dina hjärtproblem...}
{408}{}{Det var tråkigt att höra, Hej då.}
{410}{}{Hej då.}
{411}{}{Gör du? Menar du att du faktiskt HAR hjärtpiller?}
{412}{}{Ja, det har jag. Det skulle vara ett nöje att ge dem till dig.}
{413}{}{Ja, jag har hjärtpiller. Du kan få dem för $400.}
{414}{}{Jag skojade bara. Jag har inga hjärtpiller.}
{415}{}{[Han tar pillren från dig.] Tack, min vän! Här, var snäll och ta det här som en tacksamhetsgest.}
{416}{}{Jag hjälper gärna till, och tack för grejen. Hej då!}
{417}{}{(Han blir ganska arg, men lugnar sedan ner sig) Okej, visst, här är dina pengar. Ge mig nu pillren!}
{418}{}{Jag har bestämt mig för att behålla pillren själv. Tack för pengarna!}
{419}{}{Trevligt att göra affärer med dig, Hej då.}
{420}{}{Tyvärr, det har jag inte. Prata med Abboten, han kanske vet något.}
{421}{}{Jag ska göra det, tack. Nu har jag några andra frågor.}
{422}{}{Om jag inte var så sjuk skulle jag spöa skiten ur dig. FÖRSVINN HÄRIFRÅN NU!}
{423}{}{Okej, då går jag.}
{500}{}{Tack igen för de där hjärtpillren, min vän. Lycka till på dina resor.}
{600}{}{Gå bara härifrån, snälla.}
{700}{}{Du visade John hur grym världen verkligen är.}
