{100}{}{Du ser en medelålders munk.}
{101}{}{Du ser broder Matthew.}
{102}{}{Han står på ett podium och predikar för Klostrets invånare.}
{200}{}{Gott folk i Klostret. Ta er en stund att lyssna, för jag har mycket att säga.}
{201}{}{Här samlar vi de heliga reliker från ett sekel sedan länge förflutet.}
{202}{}{Bränd av Eldfloden som fört oss mot det mörka slutet.}
{203}{}{För att bevara den gamla visdomen, en minnessak vi skapa skall.}
{204}{}{Vi måste vakta och vårda den, även om lågan blivit kall;}
{205}{}{Den kan tändas igen, om visdomen missanvänds.}
{206}{}{Därmed ingen veta skall, vi rädes Eldfloden åter tänds.}
{207}{}{Men en dag ska människor resa sig över sin vilja till förstörelse.}
{208}{}{Och Minnesmärket ska finnas där, väntande på botgörelse.}
{209}{}{Så vi utför vår heliga uppgift, all visdom i vår hand.}
{210}{}{Aldrig mer använda, men skydda från tidens tand.}
{211}{}{Så nu mina vänner, res iväg med huvudet högt;}
{212}{}{För ni har alla visdomens väktare mött.}
{213}{}{Ta nu ett ögonblick och reflektera över det jag sagt.}
{224}{}{Ta nu ett ögonblick och reflektera över det jag sagt.}
{300}{}{Var hälsad, min vän. Jag tror inte att jag har sett dig här förut. Mitt namn är broder Matthew och jag hjälper till
 att sprida ordet om vikten av att bevara de gamlas kunskap.}
{301}{}{Det är trevligt att träffa dig, Matte. Jag heter }
{302}{}{ och jag är på jakt efter den heliga GECK.}
{303}{}{Ursäkta, jag måste gå.}
{400}{}{En GECK, va? Jag tycker mig minnas att jag läste något om det under en av mina transkriberingssessioner. Så det måste
 finnas i vår databas, men jag är rädd att tillgången till våra datorer är begränsad. Men om du pratar med Abboten, är det
 möjligt att han ger dig tillgång. Det skadar inte att försöka i alla fall. Åh, och känn dig fri att bläddra igenom vår samling
 av heliga förkrigsreliker. Jag skulle be dig att inte skada något, men jag är rädd att allt redan är trasigt bortom all räddning.}
{401}{}{Jag tror att jag kanske gör det. Jag har dock några frågor.}
{402}{}{Tack. Jag tror att jag ska göra det nu.}
{500}{}{Jag står till er tjänst. Vad skulle du vilja veta?}
{501}{}{Vad kan du berätta om den här platsen?}
{502}{}{Du verkar vara väldigt poetisk i dina predikningar. Finns det någon anledning till det?}
{503}{}{Det var inget. Ha det så bra.}
{600}{}{Klostret är ett hem för vem som helst, så länge de inte ställer till med problem. Vi är ett självständigt samhälle och får sällan
 besökare, som du själv. Majoriteten av de du ser här härstammar från de ursprungliga grundarna som bosatte sig i
 detta gamla kloster inte långt efter den stora Eldfloden.}
{601}{}{Fortsätt.}
{602}{}{Den lugna, fridfulla stämningen häromkring har gjort det till ett tilltalande hem för andra resenärer som har vandrat
 hit genom åren för att fly från det mörka kaoset i ödemarken. Naturligtvis ligger denna plats verkliga värde
 i dess stora bibliotek. Det är fyllt med gamla böcker som innehåller en förlorad tids märkliga visdom. Med tiden har vi börjat se
 oss själva som bevarare och väktare av den visdomen.}
{603}{}{Mycket intressant. En annan fråga.}
{604}{}{Intressant. Nåväl, jag måste gå.}
{700}{}{[Mannen skrattar åt din fråga] Nej, ingen särskild anledning. Jag har bara läst mycket poesi under hela mitt liv
 och jag tycker om att använda det i min undervisning. Det hjälper till att lämna en starkare intryck på de som lyssnar.}
{701}{}{Rimligt nog. En annan fråga.}
{800}{}{Det är trevligt att se dig igen }
{801}{}{. Vad kan jag göra för dig?}
{802}{}{Jag har några frågor.}
{803}{}{Det var inget. Vi ses.}
