{100}{}{Du ser Max.}
{101}{}{Du ser en vanlig klostermunk.}
{102}{}{Han ser lite nervös ut.}
{200}{}{Hej, vad kan jag göra för dig?}
{201}{}{Jag har något från Elaine...}
{202}{}{Vad är det här för ställe?}
{203}{}{Hej då.}
{300}{}{Låt mig gissa. Det är den där servicedelen jag bad om, eller hur?}
{301}{}{Ja, här är den.}
{302}{}{Nej, jag testade dig bara.}
{303}{}{(Han tar delen från dina händer) Äntligen! Nu kan vi fixa den här tryckmaskinen. Tack, ta den här överlevnadshandboken för besväret.}
{304}{}{Tack.}
{305}{}{Jag har inte tid med det här. Har du delen eller inte?}
{306}{}{Ja, jag har den.}
{307}{}{Hur som helst, jag sticker.}
{400}{}{Det här är vårt tryckeri. Här kopierar vi våra böcker.}
{401}{}{Ok, tack för informationen.}
{500}{}{Du får %d erfarenhetspoäng för att ha levererat delen.}
{600}{}{I be BIG helper today. I have macheen part from pretty name woman.}
{610}{}{That must be the service part that I requested from Elaine. Thanks for bringing this to me. Here, take this
 survival manual for your trouble... uh if you can read it that is.}
{611}{}{I read ten words. I likie pitcher books more. They fun to look. Tankee!}
