{100}{}{Du ser en medelålders munk.}
{101}{}{Du ser broder Matthew.}
{102}{}{Han står på ett podium och predikar för Klostrets invånare.}
{200}{}{Gott folk i Klostret. Ta er en stund att lyssna, för jag har mycket att säga.}
{201}{}{Här samlar vi de heliga relikerna från en svunnen tid.}
{202}{}{Scorched by the Flame Deluge, into the dark, we were cast.}
{203}{}{För att bevara den gamla visdomen, en minnessak vi skapa skall.}
{204}{}{Vi måste vakta och vårda den, även om lågan har blivit kall;}
{205}{}{It could ignite once again, should the wisdom be misused.}
{206}{}{Thus, no one shall learn, for fear of another, Flame Deluge.}
{207}{}{But one day, men shall rise above their desire for destruction.}
{208}{}{And the Memorabilia will be there, awaiting re-introduction.}
{209}{}{So we tend to our holy task, lest all that wisdom, we lose.}
{210}{}{We must preserve and protect it, but never shall we use.}
{211}{}{So go now my friends, and let your spirits be lifted;}
{212}{}{For the guardians of knowledge, we have each, been gifted.}
{213}{}{Now, please take a moment and reflect on what I have said.}
{224}{}{Now, please take a moment and reflect on what I have said.}
{300}{}{Var hälsad, min vän. Jag tror inte att jag har sett dig här förut. Mitt namn är broder Matthew och jag hjälper till
 att sprida ordet om vikten av att bevara de gamlas kunskap.}
{301}{}{Det är trevligt att träffa dig, Matte. Jag heter }
{302}{}{ och jag är på jakt efter den heliga GECK.}
{303}{}{Ursäkta, jag måste gå.}
{400}{}{En GECK, va? Jag tycker mig minnas att jag läste något om det under en av mina transkriberingssessioner. Så det måste
 finnas i vår databas, men jag är rädd att tillgången till våra datorer är begränsad. Men om du pratar med Abboten, är det
 möjligt att han ger dig tillgång. Det skadar inte att försöka i alla fall. Åh, och känn dig fri att bläddra igenom vår samling
 av heliga förkrigsreliker. Jag skulle be dig att inte skada något, men jag är rädd att allt redan är trasigt bortom all räddning.}
{401}{}{Jag tror att jag kanske gör det. Jag har dock några frågor.}
{402}{}{Tack. Jag tror att jag ska göra det nu.}
{500}{}{Jag står till er tjänst. Vad skulle du vilja veta?}
{501}{}{Vad kan du berätta om den här platsen?}
{502}{}{Du verkar vara väldigt poetisk i dina predikningar. Finns det någon anledning till det?}
{503}{}{Nevermind. Take care.}
{600}{}{The Abbey is home to anyone, so long as they don't cause trouble. We are an independent community and rarely get
 visitors, such as yourself. The majority of those you see here are descended from the original founders that settled in
 this old monastery not long after the great Flame Deluge.}
{601}{}{Fortsätt.}
{602}{}{Den lugna, fridfulla stämningen häromkring har gjort det till ett tilltalande hem för andra resenärer som har vandrat
 hit genom åren för att fly från det mörka kaoset i ödemarken. Naturligtvis ligger denna plats verkliga värde
 i dess stora bibliotek. Det är fyllt med gamla böcker som innehåller en förlorad tids märkliga visdom. Med tiden har vi börjat se
 oss själva som bevarare och väktare av den visdomen.}
{603}{}{Mycket intressant. En annan fråga.}
{604}{}{Intressant. Nåväl, jag måste gå.}
{700}{}{[Mannen skrattar åt din fråga] Nej, ingen särskild anledning. Jag har bara läst mycket poesi under hela mitt liv
 och jag tycker om att använda det i min undervisning. Det hjälper till att lämna en starkare intryck på de som lyssnar.}
{701}{}{Rimligt nog. En annan fråga.}
{800}{}{Det är trevligt att se dig igen }
{801}{}{. Vad kan jag göra för dig?}
{802}{}{Jag har några frågor.}
{803}{}{Det var inget. Vi ses.}
