{100}{}{Du ser Max.}
{101}{}{Du ser en vanlig klostermunk.}
{102}{}{Han ser lite nervös ut.}
{200}{}{Hej, vad kan jag göra för dig?}
{201}{}{Jag har något från Elaine...}
{202}{}{Vad är det här för ställe?}
{203}{}{Hej då.}
{300}{}{Låt mig gissa. Det är den där servicedelen jag bad om, eller hur?}
{301}{}{Ja, här är den.}
{302}{}{Nej, jag testade dig bara.}
{303}{}{(Han tar delen från dina händer) Äntligen! Nu kan vi fixa den här tryckmaskinen. Tack, ta den här överlevnadshandboken för besväret.}
{304}{}{Tack.}
{305}{}{Jag har inte tid med det här. Har du delen eller inte?}
{306}{}{Ja, jag har den.}
{307}{}{Hur som helst, jag sticker.}
{400}{}{Det här är vårt tryckeri. Här kopierar vi våra böcker.}
{401}{}{Ok, tack för informationen.}
{500}{}{Du får %d erfarenhetspoäng för att ha levererat delen.}
{600}{}{Jag e STOR hjälpare idag. Jag har massiindel från finnamn kvinna.}
{610}{}{Det måste vara den reservdel som jag bad om från Elaine. Tack för att du kom hit med den. Här, ta den här
 överlevnadsmanualen för ditt besvär... eh om du kan läsa den vill säga.}
{611}{}{Jag läsa tio ord. Jag gillar bildbokar mer. De kul att titta. Taack!}
