{100}{}{Du ser en handlare.}
{102}{}{Du ser en handlare som försöker laga vattenpumpen.}
{103}{}{Jag kan bara inte få den här saken att fungera!}
{104}{}{Detta verkar vara mycket svårt att laga.}
{105}{}{Vilken jävla skit den här är!}
{106}{}{Envis liten skitunge är vi?}
{107}{}{Kan du hjälpa mig?}
{108}{}{Du kanske har mer tur med den här.}
{109}{}{Hej, tack för att du lagade vattenpumpen!}
{110}{}{Du borde meddela huvudmunken att vattenpumpen nu är lagad.}
{200}{}{Tack för att du hjälper oss med den här saken.}
{300}{}{Åh, vilken ski-... ehh, jag är lite upptagen just nu. Behöver du något eller
 slösar du bara bort min tid?}
{301}{}{Faktiskt ja, Abboten skickade mig. Han sa att vattenpumpen har lite problem.}
{302}{}{Hah, "har problem" är en underdrift. Den här gamla grejen är helt förstörd. Det finns ingen chans
 att den kommer att fungera igen.}
{303}{}{Jag förstår. Då antar jag att det inte skulle skada något om jag tog en titt på den.}
{304}{}{Visst, varsågod. Inte som att du kan förstöra den mer.}
{305}{}{Jag vill inte störa, men vad är det som verkar vara problemet här?}
{306}{}{Huvudvattenpumpen för klostret är trasig. Den jäkla saken har dragit sina sista andetag de senaste dagarna
 och nu har den till sist stannat.}
{307}{}{Jag är lite teknikintresserad, får jag ta en titt?}
{308}{}{Jag är inte så bra på maskiner, men jag kanske kan se om det går att göra något.}
{309}{}{Visst, ingen stoppar dig.}
{310}{}{Eh, jag är ledsen. Hej då.}
{311}{}{Jag ska se vad jag kan göra då.}
{312}{}{Jag tänkte att jag kanske kunde hjälpa till, men om du vill vara en skitstövel så är du välkommen att lösa det på egen hand.}
{313}{}{Jag sa till abboten att jag gärna hjälper till, men om du vill vara en skitstövel får du gärna lösa det på egen hand.}
{320}{}{[Han kisar på dig ett ögonblick och släpper sedan långsamt ut andan i en suck.] Ledsen vän, den här saken är en
 riktig bitch, och den ha' gjort mig helt upprörd. Jag menade inte att snäsa åt dig.}
{321}{}{Tja, vad verkar vara problemet då?}
{322}{}{Visst, hej då.}
{330}{}{Kom tillbaka och prata med mig i morgon bitti.}
{400}{}{Åh, det är du igen. Har du lyckats än?}
{401}{}{Nej, inte än. Jag hör av mig om jag gör det.}
{402}{}{Ja, faktiskt. Jag tittade inuti och det verkar som om motorn är helt paj. Anslutningarna är körda, så vi
 måste få tag på en ny motor, samt några kablar för att återansluta allt eftersom de gamla kablarna är stekta.}
{500}{}{Hmmm... Kontakterna är körda på huvudmotorn, va? Tja, jag har några kablar här med mig som kommer att fungera, men inte
 den specifika motorn. Jag är säker på att Valvstaden har delen dock. Gå dit och prata med Harry på huvudgården. Säg till honom att
 Dave skickade dig. Den jäkla motorn är dyr, men han borde ge dig en bra deal.}
{501}{}{Jag ska dit nu. Kommer snart tillbaka.}
{502}{}{Vänta lite. Jag var glad att hjälpa dig att förstå problemet, men vem sa att jag är villig att vandra över
 ödemarken för att köpa en dyr motor till dig? Om du vill ha min hjälp, så kommer det att kosta dig.}
{503}{}{Vad sägs om att *du* säger det till Harry när du hämtar den helt jäkla själv? Jag är inte din jävla springpojke. Hej då.}
{510}{}{Okej, jag skulle inte förvänta mig att någon gör jobbet gratis. Delen kommer att kosta dig cirka 500 och jag tror att 100 mer för
 ditt besvär är rimligt. Här får du 600.}
{511}{}{Det var bättre. Jag kommer tillbaka med delen.}
{600}{}{Nån tur med den där delen? Den här maskinen lagar inte sig själv.}
{601}{}{Nej, inte än. Jag kommer tillbaka när jag får den.}
{602}{}{Japp, jag har delen här.}
{700}{}{Utmärkt. Ska jag installera den jäkla saken, eller vill du ha nöjet?}
{701}{}{Jag tror att jag klarar av det. Stig åt sidan.}
{702}{}{Jag tror att jag har gjort tillräckligt med det här jobbet. Kör igång och installera den själv.}
{800}{}{Okej bra, lämna över den.}
{801}{}{Varsågod.}
{900}{}{Så där ja.}
{901}{}{Vattenpumpen har reparerats.}
{910}{}{(Torkar svetten från pannan.) Ja, behöver du något?}
{911}{}{Abboten sa att du kanske behövde lite hjälp. Vad verkar vara problemet?}
{912}{}{Bry dig inte om det. Adjö.}
{913}{}{Jag tog en titt på vattenpumpen och det verkar som om motorn är helt paj. Anslutningarna är körda, så vi
 måste få tag på en ny motor, samt några kablar för att återansluta allt eftersom de gamla kablarna är stekta.}
