{100}{}{Du ser en handlare.}
{102}{}{Du ser en handlare som försöker laga vattenpumpen.}
{103}{}{Jag kan bara inte få den här saken att fungera!}
{104}{}{Detta verkar vara mycket svårt att laga.}
{105}{}{Vilken jävla skit den här är!}
{106}{}{Envis liten skitunge är vi?}
{107}{}{Kan du hjälpa mig?}
{108}{}{Du kanske har mer tur med den här.}
{109}{}{Hej, tack för att du lagade vattenpumpen!}
{110}{}{Du borde meddela huvudmunken att vattenpumpen nu är lagad.}
{200}{}{Tack för att du hjälper oss med den här saken.}
{300}{}{Åh, vilken ski-... ehh, jag är lite upptagen just nu. Behöver du något eller
 slösar du bara bort min tid?}
{301}{}{Faktiskt ja, Abboten skickade mig. Han sa att vattenpumpen har lite problem.}
{302}{}{Hah, "har problem" är en underdrift. Den här gamla grejen är helt förstörd. Det finns ingen chans
 att den kommer att fungera igen.}
{303}{}{Jag förstår. Då antar jag att det inte skulle skada något om jag tog en titt på den.}
{304}{}{Visst, varsågod. Inte som att du kan förstöra den mer.}
{305}{}{Jag vill inte störa, men vad är det som verkar vara problemet här?}
{306}{}{Huvudvattenpumpen för klostret är trasig. Den jäkla saken har dragit sina sista andetag de senaste dagarna
 och nu har den till sist stannat.}
{307}{}{Jag är lite teknikintresserad, får jag ta en titt?}
{308}{}{Jag är inte så bra på maskiner, men jag kanske kan se om det går att göra något.}
{309}{}{Visst, ingen stoppar dig.}
{310}{}{Eh, jag är ledsen. Hej då.}
{311}{}{Jag ska se vad jag kan göra då.}
{312}{}{Jag tänkte att jag kanske kunde hjälpa till, men om du vill vara en skitstövel så är du välkommen att lösa det på egen hand.}
{313}{}{Jag sa till abboten att jag gärna hjälper till, men om du vill vara en skitstövel får du gärna lösa det på egen hand.}
{320}{}{[He squints at you for a moment, then slowly lets out his breath in a sigh.] Sorry friend, this thing's being a
 real bitch, and it's gotten me all worked up. I didn't mean to snap at ya. }
{321}{}{Well, what seems to be the problem then?}
{322}{}{Whatever, bye.}
{330}{}{Come back and talk to me in the morning.}
{400}{}{Oh, it's you again. Any luck?}
{401}{}{No, not yet. I'll get back to you if I do.}
{402}{}{Actually, yes. I looked inside and it seems the motor is completely busted. The connections are shot, so we're
 going to have to get our hands on a new motor, as well as some wires to reconnect everything since the old wires are fried.}
{500}{}{Hmm... the connectors are shot on the main motor, eh? Well, I got some wires here with me that will work, but not
 that specific motor. I am sure Vault City has the part though. Go there and speak with Harry in the main courtyard. Tell him
 Dave sent you. Damn motor is expensive, but he should give you a good deal.}
{501}{}{I'll head there now. Be back soon.}
{502}{}{Vänta lite. Jag var glad att hjälpa dig att förstå problemet, men vem sa att jag är villig att vandra över
 ödemarken för att köpa en dyr motor till dig? Om du vill ha min hjälp, så kommer det att kosta dig.}
{503}{}{Vad sägs om att *du* säger det till Harry när du hämtar den helt jäkla själv? Jag är inte din jävla springpojke. Hej då.}
{510}{}{Okej, jag skulle inte förvänta mig att någon gör jobbet gratis. Delen kommer att kosta dig cirka 500 och jag tror att 100 mer för
 ditt besvär är rimligt. Här får du 600.}
{511}{}{Det var bättre. Jag kommer tillbaka med delen.}
{600}{}{Nån tur med den där delen? Den här maskinen lagar inte sig själv.}
{601}{}{Nej, inte än. Jag kommer tillbaka när jag får den.}
{602}{}{Japp, jag har delen här.}
{700}{}{Utmärkt. Ska jag installera den jäkla saken, eller vill du ha nöjet?}
{701}{}{Jag tror att jag klarar av det. Stig åt sidan.}
{702}{}{Actually, I think I've done enough on this job. Go ahead and install it yourself.}
{800}{}{Alright fine, hand it over.}
{801}{}{Here you go.}
{900}{}{That should do it.}
{901}{}{The water pump has been repaired.}
{910}{}{(Wipes the sweat from his forehead.) Yeah, need something?}
{911}{}{The Abbot said you might need some assistance. What seems to be the trouble?}
{912}{}{Nevermind. Goodbye.}
{913}{}{I took a look at the water pump and it seems the motor is completely busted. The connections are shot, so we're
 going to have to get our hands on a new motor, as well as some wires to reconnect everything since the old wires are fried.}
