{100}{}{Ni ser fru Peterson.}
{101}{}{Du ser en ung, vacker kvinna. Hon ler när hon ser dig.}
{200}{}{Välkommen till klostret, min vän.}
{201}{}{Prata med min man om du behöver något.}
{202}{}{Vacker dag, eller hur?}
{300}{}{Välkommen till klostret, min vän.}
{301}{}{Prata med min man om du behöver något.}
{302}{}{Härlig kväll, eller hur?}
{400}{}{Jag har inget att säga till dig. Snälla, gå härifrån.}
