{100}{}{Du ser en ung man som ser stark ut.}
{101}{}{Ni ser herr Peterson.}
{200}{}{Hej, min vän. Jag har inte sett dig här förut. Första gången i Klostret?}
{201}{}{Trevligt att se dig igen. Vad kan jag göra för dig?}
{202}{}{Japp. Vad kan du berätta om det här stället?}
{203}{}{Jag är på jakt efter den heliga GECK. Vet du något om detta?}
{204}{}{Broder Samuel sa att du kanske vet något om vem som stör gravarna. Han sa att du hörde några
 ljud som kom från era grödor.}
{205}{}{Strunt samma, jag måste gå.}
{300}{}{Frugan och jag kom hit för några år sedan tillsammans med en karavan. Vi trivdes så bra här att vi bestämde oss för att stanna och starta vår
 egna lilla gård. Låt mig säga er, Klostret kanske inte är lika häftigt som New Reno, eller lika avancerat som Valvstaden, men så vitt
 jag bryr mig är det här stället så bra som det kan bli i ödemarken. Allahär är anständiga, och folk tar hand om
 varandra. Visst, vissa platser kanske erbjuder mer säkerhet, men på bekostnad av personlig frihet. Nej, tack.}
{301}{}{Kom du med en karavan? Kommer de hit ofta?}
{302}{}{Inte särskilt. Klostret är för litet och isolerat för att karavanerna ska ta sig hit för vår skull. Det spelar dock ingen roll, vi är
 ett ganska självförsörjande samhälle - -odlar vår egen mat, bränner vår egen sprit - så vi klarar oss alldeles utmärkt. Hur som helst, Bill är mannen
 du borde prata med om karavaner, han driver lanthandeln strax sydvästerut.}
{303}{}{Det låter jättebra, men jag måste verkligen gå.}
{304}{}{Intressant. Jag var nyfiken på något annat.}
{305}{}{Strunt samma, jag måste gå.}
{400}{}{Vad mer skulle du vilja veta?}
{401}{}{Vad kan du berätta om Klostret?}
{402}{}{Do you know anything about a Garden of Eden Creation Kit?}
{500}{}{Ledsen, jag har aldrig hört talas om det. Men om det har att göra med förkrigstiden, så slår jag vad om att det finns något om det
 i Klostrets datorer. Oturligt nog för dig, så är de där munkarna väldigt rädda om sin information--förskräckta att det ska
 leda till ett nytt krig eller något liknande om folk lär sig för mycket. Men det kan ändå vara värt att fråga runt där.}
{501}{}{Tack, jag ska göra det. Jag har dock några fler frågor.}
{502}{}{Tack för tipset. Jag ska gå och kolla upp det direkt.}
{600}{}{Skickade broder Samuel hit dig? Vad håller den där fyllbulten på med?}
{601}{}{Sköter gravarna som vanligt, antar jag. Så om det du hörde...}
{602}{}{[John sätter sig i sin stol och häller upp en shot whisky.] Allt började för några dagar sedan. Min fru och
 jag förberedde för att gå och lägga oss när vi hörde lite prassel ute på fältet. Jag tog min lykta och rusade ut för att se om
 jag kunde hitta källan till ljudet. Men så fort jag kom ut på fälten hade oljudet upphört.}
{603}{}{Fortsätt.}
{604}{}{Jag måste verkligen gå.}
{605}{}{Men, nästa natt hörde vi ingenting. Natten därefter däremot hörde vi prassel från fältet
 igen. Den här gången smög jag mig fram till fönstret och tittade ut i stället för att rusa ut. När jag kikade in i mörkret såg jag ett
 svagt ljus, som från en gammal lykta eller något, som rörde sig bland grödorna. Efter ett par minuter rörde sig ljuset mot
 kyrkogården.}
{606}{}{Jag ville gå ut och konfrontera vem eller vad det nu var, men frugan övertalade mig att stanna inne och kolla
 på det morgonen efter. Så morgonen därpå ser jag att några av mina grödor har ätits upp och det finns färska fotspår
 överallt. Jag har inget emot att ge mat till de fattiga, men jag gillar inte tjuvar.}
{607}{}{Jag ska försöka fånga på den här personen. Jag kanske väntar till midnatt och ser om jag får reda på nåt. Nåväl,
 tack för informationen. Ta hand om er.}
{608}{}{Jag ska se vad jag kan göra. Jag har några frågor till innan jag går.}
{609}{}{Den här historien börjar bli lite för lång. Hej då.}
{610}{}{Låt mig förstå det här rätt. Du'skulle gärna hjälpa någon som smyger runt ditt hus på natten, stjäl dina
 grödor och försöker råna dina döda? Jag har träffat många galningar i mina dagar, men du kanske tar priset. Det är ett mirakel
 att du har överlevt så här länge.}
{611}{}{[Han kisar med ögonen, men lyckas behålla fattningen.] Det är så vi gör saker här i Klostret. Om vänlighet
 är så stötande för dig, då föreslår jag att du försvinner ut ur mitt hus. Jag tänker inte sitta här och låta någon vandrande
 stammedlem förolämpa mig framför min fru.}
{612}{}{Okej, okej, jag går nu.}
{613}{}{Okej, tuffing, nu kommer den här "vandrande stammedlemmen" att döda dig inför din fru. Då kanske jag också dödar henne.
 Va fan, jag kanske dödar alla på det här patetiska jävla ställe. Trodde du att ni alla kunde gömma er från ödemarkens fasor?
 Nå, gissa vad, min naiva vän? Fasorna har hittat dig, och dess namn är }
{700}{}{Dra åt helvete.}
{710}{}{Kul att se dig igen. Tom har varit till stor hjälp här. Tack igen för att du löste allt det där. Nu, vad kan jag göra för dig?}
{6061}{}{Efter det frågade jag broder Samuel om något hade hänt på kyrkogården. Det var då han berättade för mig att någon
 hade börjat gräva upp några av gravarna. Tydligen är den som gör det inte tillräckligt stark för att gräva på en natt.
 Jag skulle gissa att det är en gammal tiggare som hoppas på att gräva upp en skatt. Om du någonsin får reda på vem som gör det här, säg till dem att
 komma förbi. Det finns inget behov av tjuveri här i Klostret och jag skulle gärna hjälpa den här personen på alla sätt jag kan.}
