{100}{}{Du ser en ung man som ser stark ut.}
{101}{}{Ni ser herr Peterson.}
{200}{}{Hej, min vän. Jag har inte sett dig här förut. Första gången i Klostret?}
{201}{}{Trevligt att se dig igen. Vad kan jag göra för dig?}
{202}{}{Japp. Vad kan du berätta om det här stället?}
{203}{}{Jag är på jakt efter den heliga GECK. Vet du något om detta?}
{204}{}{Broder Samuel sa att du kanske vet något om vem som stör gravarna. Han sa att du hörde några
 ljud som kom från era grödor.}
{205}{}{Strunt samma, jag måste gå.}
{300}{}{Frugan och jag kom hit för några år sedan tillsammans med en karavan. Vi trivdes så bra här att vi bestämde oss för att stanna och starta vår
 egna lilla gård. Låt mig säga er, Klostret kanske inte är lika häftigt som New Reno, eller lika avancerat som Valvstaden, men så vitt
 jag bryr mig är det här stället så bra som det kan bli i ödemarken. Allahär är anständiga, och folk tar hand om
 varandra. Visst, vissa platser kanske erbjuder mer säkerhet, men på bekostnad av personlig frihet. Nej, tack.}
{301}{}{Kom du med en karavan? Kommer de hit ofta?}
{302}{}{Inte särskilt. Klostret är för litet och isolerat för att karavanerna ska ta sig hit för vår skull. Det spelar dock ingen roll, vi är
 ett ganska självförsörjande samhälle - -odlar vår egen mat, bränner vår egen sprit - så vi klarar oss alldeles utmärkt. Hur som helst, Bill är mannen
 du borde prata med om karavaner, han driver lanthandeln strax sydvästerut.}
{303}{}{Det låter jättebra, men jag måste verkligen gå.}
{304}{}{Intressant. Jag var nyfiken på något annat.}
{305}{}{Strunt samma, jag måste gå.}
{400}{}{Vad mer skulle du vilja veta?}
{401}{}{Vad kan du berätta om Klostret?}
{402}{}{Do you know anything about a Garden of Eden Creation Kit?}
{500}{}{Ledsen, jag har aldrig hört talas om det. Men om det har att göra med förkrigstiden, så slår jag vad om att det finns något om det
 i Klostrets datorer. Oturligt nog för dig, så är de där munkarna väldigt rädda om sin information--förskräckta att det ska
 leda till ett nytt krig eller något liknande om folk lär sig för mycket. Men det kan ändå vara värt att fråga runt där.}
{501}{}{Tack, jag ska göra det. Jag har dock några fler frågor.}
{502}{}{Tack för tipset. Jag ska gå och kolla upp det direkt.}
{600}{}{Skickade broder Samuel hit dig? Vad håller den där fyllbulten på med?}
{601}{}{Sköter gravarna som vanligt, antar jag. Så om det du hörde...}
{602}{}{[John sätter sig i sin stol och häller upp en shot whisky.] Allt började för några dagar sedan. Min fru och
 jag förberedde för att gå och lägga oss när vi hörde lite prassel ute på fältet. Jag tog min lykta och rusade ut för att se om
 jag kunde hitta källan till ljudet. Men så fort jag kom ut på fälten hade oljudet upphört.}
{603}{}{Fortsätt.}
{604}{}{Jag måste verkligen gå.}
{605}{}{Well, the next night we didn't hear a thing. But the night after that, we heard rustling coming from the field
 again. This time I crept to the window and looked out rather than rushing outside. Peering into the darkness, I saw a
 dim light, like from an old lantern or something, moving among the crops. After a couple minutes the light moved toward
 the cemetery.}
{606}{}{I wanted to go out and confront whoever--or whatever--it was, but the wife convinced me to stay inside and check
 on things in the morning. So the next morning, I see some of my crops had been eaten and there's fresh footprints all
 around. Now, I don't mind feeding the poor, but I don't take kindly to thieves.}
{607}{}{I'll try and catch this individual. Maybe I'll wait around midnight and see if I can find anything out. Well,
 thanks for the information. Take care.}
{608}{}{I'll see what I can do. I have some more questions before I go.}
{609}{}{This story is getting a little too long. Bye.}
{610}{}{Let me get this straight. You'd be happy to help someone that lurks around your house at night, steals your
 crops, and tries to rob your dead? I've met a lot of loonies in my day, but you just might take the cake. It's a marvel
 you've survived this long.}
{611}{}{[Han kisar med ögonen, men lyckas behålla fattningen.] Det är så vi gör saker här i Klostret. Om vänlighet
 är så stötande för dig, då föreslår jag att du försvinner ut ur mitt hus. Jag tänker inte sitta här och låta någon vandrande
 stammedlem förolämpa mig framför min fru.}
{612}{}{Alright, alright, I'm leaving.}
{613}{}{Okej, tuffing, nu kommer den här "vandrande stammedlemmen" att döda dig inför din fru. Då kanske jag också dödar henne.
 Va fan, jag kanske dödar alla på det här patetiska jävla ställe. Trodde du att ni alla kunde gömma er från ödemarkens fasor?
 Nå, gissa vad, min naiva vän? Fasorna har hittat dig, och dess namn är }
{700}{}{Get the hell outta here.}
{710}{}{Good to see you again. Tom's been a big help around here. Thanks again for sorting all that out. Now, what can I do for you?}
{6061}{}{After that, I asked Brother Samuel if anything had happened in the graveyard. That's when he told me someone
 had begun digging up some of the graves. Apparently, whoever's doing this isn't strong enough to dig in one night.
 I'd guess it's an old beggar hoping to dig up some treasure. If you ever find out who's doing this, please tell 'em to
 stop by. There's no need for thievery here in the Abbey and I'd be happy to help this person in any way I can.}
