{100}{}{Du ser en bonde.}
{101}{}{Du ser en bonde som ser frisk ut.}
{102}{}{Du ser en person.}
{103}{}{Har du druckit för mycket sprit på sistone?}
{104}{}{Håll dig borta från alkoholen ett tag.}
{105}{}{Jag ser att du drack Hanks "speciella" blandning.}
{106}{}{Välkommen, hjälte!}
{107}{}{You really showed those Enclave bastards!}
{108}{}{Du är sannerligen en hjälte!}
{109}{}{I've heard that you destroyed the Enclave, well done!}
{110}{}{Hej.}
{111}{}{Jag hoppas att det börjar regna snart, annars kommer mina grödor inte att överleva.}
{112}{}{Vi får inte så många besökare här.}
{113}{}{Välkommen!}
{114}{}{Yeah, I know. It's pretty boring here, but at least we're safe from raiders and such...}
{115}{}{Hi, tribal.}
{116}{}{It sure is a hot day today!}
{117}{}{Good farming grounds here...}
{118}{}{Have a nice day.}
{119}{}{Welcome to the Abbey, wanderer!}
{120}{}{Impressive monastery we have here, eh?}
{200}{}{Get your freaking hands off me!}
