{100}{}{Du ser en bonde.}
{101}{}{Du ser en bonde som ser frisk ut.}
{102}{}{Du ser en person.}
{103}{}{Har du druckit för mycket sprit på sistone?}
{104}{}{Håll dig borta från alkoholen ett tag.}
{105}{}{Jag ser att du drack Hanks "speciella" blandning.}
{106}{}{Välkommen, hjälte!}
{107}{}{Du visade verkligen de där Enklavsjävlarna!}
{108}{}{Du är sannerligen en hjälte!}
{109}{}{Jag har hört att du förstörde Enklaven, bra gjort!}
{110}{}{Hej.}
{111}{}{Jag hoppas att det börjar regna snart, annars kommer mina grödor inte att överleva.}
{112}{}{Vi får inte så många besökare här.}
{113}{}{Välkommen!}
{114}{}{Ja, jag vet. Det är ganska tråkigt här, men vi är i alla fall säkra från plundrare och sånt...}
{115}{}{Hi, tribal.}
{116}{}{Det är verkligen en varm dag idag!}
{117}{}{Bra jordbruksmark här...}
{118}{}{Ha en trevlig dag.}
{119}{}{Välkommen till Klostret, vandrare!}
{120}{}{Imponerande kloster vi har här, va?}
{200}{}{Ta bort dina jäkla händer från mig!}
