{100}{}{Du ser en vattenpump.}
{101}{}{Du ser en riktigt gammal vattenpump som ser ut att vara trasig.}
{102}{}{Vattenpumpen fungerar bra nu.}
{103}{}{Du kommer att behöva mer än bara dina händer för att fixa den här maskinen. Kanske några verktyg skulle hjälpa till med att installera
 den här delen.}
{104}{}{Du reparerade vattenpumpen.}
{105}{}{Du misslyckades med att reparera pumpen.}
{106}{}{Du tar reda på vad som är fel på vattenpumpen.}
{200}{}{Du öppnar maskinen och tittar in. Du ser en massa rostiga kugghjul och motorer. En av motorerna
 har en spricka i sig.}
{201}{}{Sluta för dagen.}
{202}{}{Undersök mer.}
{203}{}{Vid närmare granskning ser du att sprickan inte är orsaken till problemet, utan snarare
 anslutningen för sladdarna. Kontakterna verkar ha brunnit ut under åren av användning. Det kommer att
 behövas en helt ny motor och en ny uppsättning sladdar för att få den här maskinen att fungera igen.}
{204}{}{Avsluta.}
