{100}{}{You see a waterpump.}
{101}{}{You see a really old waterpump that appears to be broken.}
{102}{}{The waterpump is working fine now.}
{103}{}{Du kommer att behöva mer än bara dina händer för att fixa den här maskinen. Kanske några verktyg skulle hjälpa till med att installera
 den här delen.}
{104}{}{Du reparerade vattenpumpen.}
{105}{}{Du misslyckades med att reparera pumpen.}
{106}{}{Du tar reda på vad som är fel på vattenpumpen.}
{200}{}{Du öppnar maskinen och tittar in. Du ser en massa rostiga kugghjul och motorer. En av motorerna
 har en spricka i sig.}
{201}{}{Sluta för dagen.}
{202}{}{Undersök mer.}
{203}{}{Upon closer inspection you see that the crack is not the cause of the trouble, but rather
 the connection for where the wires go. The connectors seem to have burned out over the years of use. It's going to
 take a whole new motor as well as a new set of wires to get this machine working again.}
{204}{}{Avsluta.}
