{100}{}{Du ser klostrets kyrkogårdsvaktmästare.}
{101}{}{Du ser broder Samuel, kyrkogårdsvaktmästaren.}
{102}{}{Han ser full och lite sömnig ut.}
{200}{}{*hick* Men, 'allå där, jag heter Samuel. Vad, eh, *hick* för dig hit?}
{201}{}{*hick* Hej igen.}
{202}{}{Jag ser mig bara omkring. Sköter du om den här kyrkogården?}
{203}{}{Känner du en Fader Tully?}
{204}{}{Father Tully, you say? [He appears to be racking his brain trying to remember.] Yeah... I *hickup* 'member Tully.
 How's that fella doin anyway? I 'aven't seen him since he was kicked out of 'ere long time *hiccup* long time ago.
 [He grins drunkenly as he reflects.] Boy he was a hoot. Him and me together, *hickup* what a combo.}
{205}{}{He lives in New Reno now, preachin' the good word, er, something like that. You know, you two seem a lot alike.}
{206}{}{New Reno, huh? [He leans on his shovel, pulls out a small flask and takes a big swig.] I 'member him sayin he'd
 *hickup* be headin that way. I'm glad he made it there safely. I always *hickup* liked that fella. A real hoot. If you
 see him again, tell him Ol' Sammy is still alive an' kickin.}
{207}{}{I'll do that. I got some other questions though.}
{208}{}{I'll do that. Take care Sam.}
{209}{}{Nevermind. Sorry to bother you.}
{210}{}{Actually I was just going to say that he sends his greetings. I'll be sure to tell him you say hello as well. I got some other questions though.}
{211}{}{Actually I was just going to say that he sends his greetings. I'll be sure to tell him you say hello as well. Take care Sam.}
{300}{}{What do you *hickup* wanna know?}
{301}{}{Are you the gravekeeper?}
{302}{}{Vad kan du berätta om Klostret?}
{303}{}{Anything I can help you with?}
{400}{}{Yes, *hickup* I tend to these 'ere graves. Nobody else wants to *hickup* do it, so Ol' Sammy got th' job. It's
 not as bad as one might think. It's got its... perks, if you know what I mean. [He grins sloppily and wiggles his bushy
 eyebrows at you.]}
{401}{}{No. I don't know what you mean, and I never want to. Bye.}
{402}{}{No. I don't know what you mean. But I think I'd rather ask you something else. }
{403}{}{No. I don't know what you mean, but I'm morbidly curious...}
{404}{}{Hell yeah I do. Nothing turns me on like a rotten cadaver.}
{410}{}{Why, I get to be outdoors, and no one's 'round to tell Ol' Sammy when he's had enough. I *know* when I've
 'ad enough... when 'ere's none left! [He cackles, which quickly turns into a hideous cough. After coughing up a lung
 or two, he smiles at you.]}
{411}{}{Oh, of *course* that's what you meant. [Sigh of relief.] Let me ask you something else, though.}
{420}{}{[His eyes go wide with shock and he seems to instantly sober.] That's not what I meant, you... you MONSTER! FIEND!
 Get away from me! }
{421}{}{Whatever, you drunk old fuck. You don't know what you're missing.}
{430}{}{Foul demon! Be gone!}
{500}{}{The Abbey, well, this place *hickup* has been my 'ome fer most of my life. Everone 'ere *hickup* is nice, and
 anyone's welcome, long as they *hickup* don't cause trouble. I, myself, don't spend too much time in th'
 mona-*hickup*-monastery, but I know our 'puters have all kinds of info that's been collected over th' years. Maybe
 some of it *hickup* might be of some use to you.}
{501}{}{You don't spend much time in the church? You are a monk, aren't you?}
{502}{}{[He grins, revealing a gap filled set of rotten teeth.] Well, *hickup* let's just say that th' other monks don't
 take *hickup* too kindly to my, uh, drinking habits.}
{503}{}{Makes sense I guess. I got some more questions.}
{504}{}{Jag antar det. Vi ses, Sammy.}
{505}{}{Jag förstår. Jag måste gå nu.}
{600}{}{Hmm... *Hick* lå' me t'nka lite. Ja, jag kanske har nåt, om du ä' sugen på de'.}
{601}{}{Eh, glöm det, Sam. Jag måste gå nu.}
{602}{}{Visst, Sam, vad behöver du?}
{603}{}{De sen'ste dagar'a har jag *hick* märkt att nå'ra av gravarna grävts upp. Så, vem som än gö' det här
 verkar inte ha kommi' så långt, men det är *hick* förjäkligt fö' mig att fylla opp dem igen.}
{604}{}{Hmm, så har du försökt ta reda på vem som har gjort det här?}
{605}{}{Visst *hick* försökte jag. En kväll stannade jag kvar till midnatt eller så och ingen dök upp. Jag måste ha somnat
 strax efter. För mycket drickande tro' ja'. [Han flinar, tar fram sin plunta och tar en rejäl klunk.] Så, vad säger
 *hick* du? Vill du hjälpa till?}
{606}{}{Alright, I'll see what I can do. Do you know anything else that might help me?}
{607}{}{Well, now that you mention it, I do *hickup* 'member Mr. Peterson sayin something about hearing some noises comin
 from his field. He might know something about this. He and that pretty little wife a his live right over there.
 [He points to the building south of the graveyard.]}
{608}{}{I'll see what I can do.}
{609}{}{I think I'll pass. I must be going.}
{700}{}{I took care of the grave digging situation. You shouldn't have any more problems out here.}
{701}{}{Well, that's *hickup* good news. Glad I won't be falling into any more open *hickup* graves. Thanks fer th' help.}
{702}{}{Glad to help. I got some questions though.}
{703}{}{Well, take care then.}
{704}{}{I don't think open graves are the real reason you're falling down Samuel, but you take it easy now.}
{1000}{}{*Vissling*}
{1001}{}{*Host* *Host*}
{1002}{}{*Rensar halsen*}
{1003}{}{*Host*}
{1004}{}{*Suck*}
{1005}{}{*Hick*}
{2000}{}{Det har varit en *hick* lång dag. Kom te'baks imorrn.}
