{100}{}{Du ser brovakten.}
{101}{}{Du ser Mynoc, brovakten.}
{150}{}{Framför dig står en stor krigare från din by,
 med ett spjut i handen.}
{151}{}{[TALA]}
{152}{}{Hej, Utvalde. På väg för att hitta GECK?}
{153}{}{Ja.}
{154}{}{Ja. Men innan jag går skulle jag vilja ställa
 några frågor till dig.}
{155}{}{Inte riktigt än. Jag ska se mig omkring
 lite mer.}
{156}{}{Må gudarna vaka över dig.}
{157}{}{Tack, hej då.}
{158}{}{Vad vill du veta?}
{159}{}{Vad kan du berätta om männen som handlar med våra
 by?}
{160}{}{Vad kan du berätta om det här föremålet jag har från
 ett valv?}
{161}{}{Inget, glöm det.}
{162}{}{Nå väl, men slösa inte för mycket tid. Utan GECK,
 är vi dödsdömda.}
{163}{}{Jag vet, oroa dig inte -- Jag har allt under kontroll.}
{164}{}{Varför?}
{165}{}{Jag måste gå nu. Hej då.}
{166}{}{Handlarna? De kommer från Klamath ungefär varannan månad. De
 kommer inte förrän om en månad eller mer, men Klamath ligger bara några dagar
 österut härifrån.}
{167}{}{Tack. Hej då.}
{168}{}{Vad kan du berätta om det här föremålet jag har från
 det heliga valvet?}
{169}{}{Ser ut som en vattenkalebass gjord av metall. Kanske
 valvet skickade den till oss som ett omen.}
{170}{}{Kan du berätta vem som tog med sig det här föremålet till vår by?}
{171}{}{Tack så mycket. Jag måste gå nu. Adjö.}
{172}{}{Jag hoppas att du gör det.}
{173}{}{Ditt överdrivna självförtroende får oss alla att lida! Adjö!}
{174}{}{Farväl.}
{175}{}{Why? Look around you -- our village dies. The gardens wither and
 every day children and old ones collapse. You must bring Eden to us before
 it is too late!}
{176}{}{Och jag ska ta hand om det. Adjö.}
{177}{}{Jag är den Utvalde - jag "måste " bara göra som jag
 behagar. Adjö.}
{178}{}{Jag minns inte hans namn, bara att han var gammal och högljudd - för
 högljudd för att uppföra sig ordentligt - men han visste många saker. Han var från Klamath, österut
 som jag sa.}
{179}{}{Tack, hej då.}
{180}{}{Är du kvar här? Du måste gå och hitta GECK. Att stanna här
 hjälper oss inte.}
{181}{}{Den här bron är allt du behöver bry dig om,
 min vän. Jag kan ta hand om mig själv.}
{182}{}{Jag var på väg ut. Adjö, min vän.}
{183}{}{Jag tänker inte tala med dig längre, ditt olydiga svin!}
{184}{}{Jag skulle vilja fråga dig något annat.}
{185}{}{Det var snabbt! Har du hittat det heliga Valv 13?}
{186}{}{Ja.}
{187}{}{Nej, inte än.}
{188}{}{Har du? Underbart! Tog du med dig GECK:en
 tillbaka?}
{189}{}{Nej.}
{190}{}{Nej, jag har inte pratat med folket i valvet än.}
{191}{}{Jag tror inte att du har med det att göra, min vän.}
{192}{}{Inte? Utvalde, tre gamla har dött sedan du lämnade oss. Du får
 inte slösa mer tid.}
{193}{}{Jag ska hitta den, oroa er inte.}
{194}{}{Jag börjar bli trött på ditt ständiga tjat.}
{195}{}{Varför pratar du med mig? Prata med dem, och hämta GECK:en.}
{196}{}{Det ska jag göra -- allt i sinom tid, min vän.}
{197}{}{Jag börjar bli trött på ditt ständiga tjat.}
{198}{}{Vad nytt om GECK:en, Utvalde?}
{199}{}{Jag har hittat valvet!}
{200}{}{Jag har inte lyckats hitta Valv 13.}
{201}{}{Ser man på, det är ju Den Utvalde.}
{202}{}{Hej.}
{203}{}{Håll tyst.}
{204}{}{Får jag ställa en fråga?}
{205}{}{Nej, jag har inte tid med dig.}
{206}{}{Visst. Adjö.}
{207}{}{Nåväl. Vi ses.}
{208}{}{Gå och dö.}
{209}{}{Var hälsad, ers tröghet! Se bro? Du korsa, du var försiktig.
 Bro farlig. Du inte vill falla. Okej?}
{210}{}{Ehh... Hunh?}
{211}{}{Din usling! Du har svikit byn!}
{212}{}{Du förråder oss. För det kommer du att dö!}
{213}{}{Du är en förrädare mot ditt eget folk.}
{214}{}{Varför gör du så här?}
{215}{}{Den Äldste hade fel. Du är ond.}
{300}{}{Min far lärde mig att göra starkare blad än de flesta. Ge mig en bit
 flinta så lagar jag ditt spjut också. Du kommer att behöva det i vildmarken.}
{301}{}{Var skulle jag få tag på den här flintstenen?}
{302}{}{They say your Aunt Morlis has been hoarding a piece. She's so
 ill-tempered I don't think anyone's asked her. Of course, the witch will want
 something in return.}
{303}{}{Tack. Hej då.}
{304}{}{Did you talk your aunt out of her flint?}
{305}{}{Ja, jag har lite här.}
{306}{}{Inte än.}
{307}{}{Det är en bra bit. Ge mig ditt spjut.}
{308}{}{Varsågod.}
{309}{}{Jag antar att jag inte har någon.}
{310}{}{Nu sätter du ihop delarna så här...}
{311}{}{Den Utvalde utan spjut? Tja, du får ta ett av
 mina. Låt oss nu sätta igång...}
{312}{}{Här är ditt nya spjut.}
{313}{}{Tack, min vän -- det här kommer att hjälpa mycket.}
{314}{}{Ja, men jag undrade över ditt spjut. Det ser lite
 annorlunda ut.}
{400}{}{Välkommen hem, Utvalde! Hittade du valvet? Har du återvänt med GECK?}
{401}{}{Jag inte hitta än.}
{402}{}{Nej, jag har inte hittat det än.}
{403}{}{Jag är inte på humör för dina frågor. Adjö.}
{404}{}{Det går inte så bra, Utvalde. Torkan blir värre och våra grödor kommer
 säkert på att vissna. Vi försöker rädda vad vi kan för att bygga upp våra matreserver.}
{405}{}{Varför inte byta andra byar?}
{406}{}{Jag göra gott jag kan. Jag hitta GECK. Jag återvända.}
{407}{}{Varför kan vi inte handla med andra byar för att få den mat vi behöver? }
{408}{}{Jag gör mitt bästa. När jag hittar GECK kommer jag tillbaka med det.}
{409}{}{Vi är ett enkelt folk och har inte mycket att erbjuda i handeln. De få städer som vi har
 kontaktat medan du var borta har inte visat något intresse för att hjälpa oss.}
{410}{}{Jag fatta.}
{411}{}{Jag förstår.}
{412}{}{Du är vårt enda hopp, Utvalde. Snälla, svik oss inte!}
{413}{}{Det är trevligt att se dig, Utvalde. Hur går det med ditt uppdrag?}
{414}{}{Jag fortfarande leta.}
{415}{}{Jag letar fortfarande.}
{416}{}{Jag vill inte prata om det.}
{417}{}{Du måste skynda. Saker och ting blir värre här hemma. Snart kommer det att finnas lite mat och
 den Äldste talar om att ransonera det vi har. Jag fruktar för Arroyos framtid.}
{418}{}{Utvalde! Snälla, säg att du har slutfört ditt uppdrag. Vår by håller på att dö, och så
 gör vårt folk.}
{419}{}{Nej, jag fortfarande leta.}
{420}{}{Nej, jag letar fortfarande.}
{421}{}{Hur är det?}
{422}{}{Jag är ledsen, Utvalde, men jag börjar tvivla på mitt förtroende för dig. Självaste livet för
 vårt folk ligger i dina händer. Snälla, hitta det heliga Tretton och återvänd till oss med GECK!}
{423}{}{Our crops fail, the brahmin die, everyone goes hungry now. The cries of the children at night
 allow no one any sleep. We are becoming a desperate people.}
{424}{}{Jag fortsätta titta.}
{425}{}{Jag ska göra vad jag kan.}
{426}{}{Ännu en gång återvänder du till oss, Utvalde. Inte tomhänt, hoppas jag?}
{427}{}{Jag ledsen, jag inte hitta GECK än.}
{428}{}{Jag är ledsen, men jag har fortfarande inte hittat GECK.}
{429}{}{Jag har fått nog av det här.}
{430}{}{Folk dör här medan du strosar runt i landet. Du kanske borde söka
 någon annanstans istället för att återvända hit.}
{500}{}{Har du pratat med den Äldste än?}
{600}{}{Any final advice for me before I head out into the unknown?}
{601}{}{Certainly. Beware the weapons of the Outsiders. The gecko's bite is nothing compared to the destructive power of their boom-sticks.}
{602}{}{Got it. Anything else?}
{603}{}{Do not give your trust freely. Honor means very little out in the wastes. Stay alert and always question the motives of others.}
{604}{}{Sure thing. Is that all?}
{605}{}{Never forget your roots. The world outside our village is full of shiny toys and luxuries that might make our life here in Arroyo appear simple and plain.
 But remember that the lifestyle of the Outsiders produces wicked men ruled by greed and corruption. Be wary not to become like He-Who-Must-Not-Be-Named.}
{606}{}{I'll never forget my roots. Thanks for the advice, Mynoc.}
{607}{}{He-Who-Must-Not-Be-Named? Uh... who?}
{608}{}{Are you so drunk with the glory of being the Chosen One that you've forgotten about... [Mynoc quickly glances around to be sure no one is listening in, then leans forward and lowers his voice to a whisper.] ... Kaga?}
{609}{}{Oh! Yeah, that guy. I'll make sure I don't end up like him. Thanks.}
{610}{}{Oh, that's who I thought you meant. But, uh, why don't you go ahead and tell me what his deal is again. I really love that story.}
{611}{}{[Mynoc mumbles something under his breath and shakes his head before beginning his tale.] As you should know, he was once the greatest warrior of our tribe. He led many expeditions into the outside world, and it was there where corruption began to poison his mind.}
{612}{}{He became infatuated with the ways of the Outsiders, where power could bring anyone great respect and luxury. He began to view himself as superior to his fellow tribesmen who were content to live a more simple life.}
{613}{}{What a jerk.}
{614}{}{Fortsätt.}
{615}{}{When our tribe fell into these hard times, he deemed himself our people's savior and entered the Temple of Trials to prove himself to be the Chosen One.}
{616}{}{Fortsätt.}
{617}{}{Nevermind, I don't want to hear this story anymore. Bye.}
{618}{}{He made his way through the Temple, quickly reaching the final test: a hand-to-hand battle with a fellow warrior.}
{619}{}{Fortsätt.}
{620}{}{Wait, he blew up that door and everything? Do we have it rebuilt every time someone goes through the temple? Speaking of that, who built the temple in the first place?}
{621}{}{I don't have time to answer all your silly questions. Do you want me to finish the tale, or not?}
{622}{}{Sorry. Please continue.}
{623}{}{Actually, I think I'm ready to go. See you around.}
{624}{}{During the final trial, He-Who-Must-Not-Be-Named unsheathed a hidden blade and used it to kill his opponent. When the Elder confronted him about his dishonorable use of a hidden weapon, he argued that it was not cheating, but rather proved him to be a cunning warrior.}
{625}{}{The Elder did not agree. He-Who-Must-Not-Be-Named was forcibly exiled from our tribe and his name was never to be spoken amongst us again. As he was cast away into the wastes, he swore an oath of vengeance. Vengeance against our tribe, and especially against you.}
{626}{}{Me? What'd I do?}
{627}{}{Thanks for the story, but I'd best be on my way now.}
{628}{}{You are the Chosen One, a title he feels is rightfully his. His pride will not allow you to live.}
{629}{}{I'm not going to worry about it. He's probably dead out in the wastes by now, anyway.}
{630}{}{I'll be on my guard. Hopefully he's dead out in the wastes by now.}
{631}{}{Listen, and understand. He-Who-Must-Not-Be-Named is out there. He can't be bargained with. He can't be reasoned with. He won't feel pity, or remorse, or fear. And he absolutely will not stop, ever, until you are dead.}
{632}{}{You know, I think you might be overdoing it with the melodrama, just a tad. Anyway, thanks for the advice. I'll see you around, Mynoc.}
{633}{}{I'll keep that in mind. Take care, Mynoc.}
{640}{}{Could you tell me anything about this Kaga guy?}
{641}{}{[His eyes go wide and he looks around nervously as if expecting to suddenly be struck by lightning.] Have you lost your senses out in the wastes?! You should know better than to speak the name of the outcast! He is to be referred to only as He-Who-Must-Not-Be-Named.
 Our village suffers enough without inviting the wrath of the Gods upon us. [He raises his eyes nervously to the sky.]}
{642}{}{Sorry about that, Mynoc. But would you mind telling me what Ka... I mean, "He-Who's" deal is again? I really love that story.}
{643}{}{You know, I'd forgotten how stupidly superstitious you people could be. I'll see you around.}
{650}{}{I've faced him before, so I'm sure I can handle him if our paths cross again.}
{651}{}{Actually, he's already dead. I left his corpse out there to rot in the wastes.}
{660}{}{[Mynoc nods grimly.] He may have strayed from the path, but he was once a great and respected warrior. I hope his troubled soul has found peace in the next world.}
{661}{}{Indeed. I'll see you around, Mynoc.}
{662}{}{Whatever. He seemed like an asshole to me. I'll see you around, Mynoc.}
{1000}{}{Äldste}
{1001}{}{Grundare}
{1002}{}{Valvinvånare}
{1003}{}{Arroyo}
{1004}{}{Klamath}
{1005}{}{Valv}
{1006}{}{Den Utvalde}
{1007}{}{Shaman}
{1008}{}{Hakunin}
{1009}{}{Helande pulver}
{1010}{}{Bro}
{1011}{}{Mynoc}
{1100}{}{Den Äldste är din mamma och vår ledare.}
{1101}{}{Vår store förfader som gav oss kunskap.}
{1102}{}{Den förste att kämpa och vinna över kaos.}
{1103}{}{Det skulle vara vår vackra by.}
{1104}{}{Det är en handelsutpost några dagar österut.}
{1105}{}{Valvet är himmelriket.}
{1106}{}{Du är den Utvalde.}
{1107}{}{Han läker oss med sina örter och sin magi. Han är i den
 norra delen av vår by.}
{1108}{}{Han läker oss med sina örter och sin magi. Han är i den
 norra delen av vår by.}
{1109}{}{Det är ett magiskt pulver som kommer att läka dig, men kommer
 gör dig sömnig.}
{1110}{}{Den stora bron leder ut ur vår by i söder.}
{1111}{}{Det skulle vara jag.}
