{100}{}{Du ser en liten datorterminal.}
{101}{}{Du ser klostrets datorterminal.}
{102}{}{Du ser en liten datorterminal. Den ser ut att vara funktionell.}
{103}{}{Du startar datorn och skannar alla tillgängliga filer. Du hittar några filer som innehåller nyckelorden "GECK" och "Valv".}
{104}{}{Läs information om GECK.}
{105}{}{Läs information om Valv.}
{106}{}{FEL! passerkort hittades inte. Vänligen sätt in passerkortet i krypteringsfacket.}
{107}{}{(Du sätter in passerkortet i kortplatsen) PIIP!, passerkort accepterat. LADDAR Vindblås 2075......FÄRDIG.}
{108}{}{Mata in kommando.}
{109}{}{Skanna filer efter information om GECK eller VALV 13.}
{110}{}{Öppna andra filer.}
{111}{}{Spela Sten Sax Påse.}
{112}{}{Tillbaka.}
{113}{}{Logga ut.}
{114}{}{[FORTSÄTT]}
{115}{}{Du hittar några filer som innehåller nyckelorden "GECK" och "Valv".}
{116}{}{Bläddra bland filer som handlar om "GECK".}
{117}{}{Bläddra bland filer som handlar om "Valv".}
{118}{}{Sökprogrammet verkar vara lite för svårt för dig.}
{119}{}{Your eyes widen and your heart quickens as you discover what appears to be an old advertisement for a Garden of Eden
 Creation Kit. The ad depicts a grinning cartoon guy in a vault suit holding up a large case that says, "Survival Kit". It's
 almost as if the smiling bastard is taunting you.}
{120}{}{Du bläddrar igenom filerna, som mest innehåller regeringspropaganda om hur fantastiskt livet i Valven skulle vara.
 Du får veta att den amerikanska regeringen i mitten av 2000-talet gav Valv-Tek i uppdrag att bygga 122 Valv över hela USA.
 Dessa Valv var avsedda att fungera som skyddsrum för upp till 1 000 amerikanska medborgare i händelse av en nukleär förintelse. Inom de underjordiska
 Valvens säkra väggar kunde Valinvånare leva en lyxig tillvaro i väntan på signalen som informerade dem om att
 världen på ytan återigen är beboelig.}
{121}{}{När du söker igenom systemet hittar du hundratals digitaliserade böcker och tidskrifter som är kategoriserade på hårddisken. Du
 skulle inte ens veta var man skulle börja leta efter något användbart.}
{122}{}{När du söker igenom systemet hittar du hundratals digitaliserade böcker och tidskrifter kategoriserade på hårddisken. Eftersom
 du är insatt i hur information vanligtvis lagras, kanske en sökning efter ämne skulle ge dig något användbart.}
{123}{}{[MER]}
{124}{}{According to the ad, the kit includes a "Base Replicator Unit", which "replicates food and basic items needed for building
 your new world", a "Holodisc Reader with Library", which "includes selections from the Library of Congress, complete set of encyclopedias,
 and other life saving information, all contained on four-hundred and sixty handy holodiscs!" and it even contains a "Miniature Pen Flashlight!"
 Surely, this miracle device is exactly what you need to save your dying village.}
{125}{}{Läs mer.}
{126}{}{Du fortsätter att bläddra i filerna, men det enda du hittar om Valv 13 säger bara att det ligger i Kalifornien,
 vilket inte hjälper dig mycket.}
{130}{}{Lägg till information.}
{131}{}{[Du har inget att tillägga.] Tillbaka.}
{132}{}{Ange information om Botani.}
{133}{}{Mata in [Bla] information.}
{140}{}{Läs Hjälp/Om-filen.}
{141}{}{Grattis till den lyckade installationen av Vindblås 2075! Denna version är den mest avancerade Vindblås-versionen hittills.
 Med sannolikheten för endast en krasch per miljon funktionsanrop bekräftad, är våra tekniker övertygade om att Vindblås är perfekt
 för alla företagsmiljöer. Det senaste tillskottet till Vindblås 2075 är en förbättrad och finjusterad kodbas som nu bara slösar bort 15%
 av dina CPU-cykler på bakgrundsadministrationtill skillnad från tidigare versioner som skulle slösa upp till 25% av dina CPU-cykler.
 Naturligtvis har mycket användarhänsyn tagits i denna senaste version. Som med tidigare versioner av Vindblås, är de vanliga
 kommandon för att Söka, Lägga till, Flytta, Ta bort och Formatera tillgängliga för användaren.}
{142}{}{Formatera filsystem, inklusive alla backup-databaser på värd- och nätverksmaskiner.}
{143}{}{Tillbaka.}
{144}{}{Formatering av backup-databas... LYCKAD... Formatering av aktuellt filsystem... VÄNTAR... Varning: Det har inträffat ett katastrofalt fel.
 Vänligen vänta...}
{145}{}{Vänta.}
{146}{}{...Systemfel: Operationen slutfördes framgångsrikt...(Ett skrikande ljud börjar höras inifrån datorn och från andra i närheten.}
{147}{}{[Gå iväg.]}
{148}{}{Fel: Inget tangentbord hittades. Tryck på valfri tangent för att starta om.}
{150}{}{Laddar upp Naturvårdsverkets botaniska informationsdisk... Uppladdning slutförd. Ha en trevlig dag.}
{200}{}{Sten, Sax, Påse V.0.3. Välj ett alternativ.}
{201}{}{Välj STEN.}
{202}{}{Välj PÅSE.}
{203}{}{Välj SAX.}
{204}{}{Återgå till huvudmenyn.}
{205}{}{Terminalen väljer.....Beräknar.....Terminalen vinner!}
{206}{}{Terminalen väljer.....Beräknar.....Användaren vinner!}
{207}{}{Terminalen väljer.....Beräknar.....Oavgjort!}
{300}{}{(Datorskärmen visar olika färgmönster.)}
{301}{}{Åhh! Fina färger.}
{302}{}{Stappla iväg.}
{400}{}{Läs mer.}
{401}{}{Återgå till menyn.}
{402}{}{Sök efter ämne.}
{403}{}{Ange ett ämne att söka efter.}
{404}{}{Vetenskap.}
{405}{}{Reparation.}
{406}{}{Medicin.}
{407}{}{Vapenanvändning.}
{408}{}{Övertygande argument.}
{410}{}{Efter några timmars läsning lär du dig mer om vetenskapens konst.}
{411}{}{Efter några timmars läsning lär du dig mer om konsten att reparera maskiner.}
{412}{}{Efter några timmars läsning lär du dig mer om läkekonsten.}
{413}{}{Efter några timmars läsning lär du dig mer om konsten att försvara sig med ett vapen.}
{414}{}{Efter några timmars läsning lär du dig mer om konsten att övertyga.}
{420}{}{Efter några timmars läsning lär du dig ingenting om vetenskapens konst.}
{421}{}{Efter några timmars läsning lär du dig ingenting om konsten att reparera maskiner.}
{422}{}{Efter några timmars läsning lär du dig ingenting om läkekonsten.}
{423}{}{Efter några timmars läsning lär du dig ingenting om konsten att avfyra ett vapen.}
{424}{}{Efter några timmars läsning lär du dig ingenting om konsten att övertyga.}
{430}{}{Tillbaka.}
{500}{}{När du läser fler artiklar får du veta att GECK utvecklades av Framtid-Tek, en division av Valv-Tek, och att
 den var standardutrustning i alla Valv-Teks valv. Den var tänkt att användas när man lämnade ett Valv, för att hjälpa till att återupprätta livet i
 de hårda miljöerna i en värld som förstörts av kärnvapenkrig.}
{501}{}{När du läser vidare upptäcker du att GECK inte riktigt är den mirakelapparat som annonsen utmålade den som. "Basåterskaparen"
 är faktiskt inget annat än ett gödningssystem som innehåller matfrön, jordtillskott och kemikalier som är speciellt konstruerade för att
 förvandla torra ödemarker till bördig jord. Dess påstående att den kan "bygga grundläggande föremål " syftar faktiskt på nya koder som den ger
 Valvets maskiner, så att de kan skapa nya föremål från automaterna. GECK innehåller också ritningar för grundläggande kraftfält
 och konstruktionen av väggar och byggnader gjorda av "sand-tong".}
{502}{}{[MER]}
{503}{}{Det verkar som om själva GECK är avsedd att demonteras under användningens gång. Du läste ett exempel på hur dess kalla fusionskraftkälla
 är avsedd att användas som huvudströmkälla för staden. GECK innehåller även instruktioner om hur man demonterar delar av
 Valvet för att skapa hem och försvarsstrukturer för det nya samhället. När du har läst igenom filerna bestämmer du dig för att även om
 det inte är den magiska anordning som den Äldste verkar tro, är det fortfarande ditt bästa alternativ att hitta en GECK om du hoppas kunna rädda din stam.}
{1000}{}{Du laddar upp Naturvårdsverkets Botani-holodisk.}
{2000}{}{Du formaterar klostrets bokdatabaser.}
