{100}{}{Du ser Abboten, Klostrets andlige ledare.}
{101}{}{Det är något med den här munken som får dig att tro att han är ganska viktig.}
{200}{}{Välkommen resenär.}
{201}{}{Frid vare med dig.}
{202}{}{Vi är kunskapens väktare.}
{203}{}{Jag är ledsen, men kunskap om våra böcker är inte till någon nytta för dig.}
{300}{}{Välkommen till Klostret, resenär. Hur kan jag hjälpa dig?}
{301}{}{What can you tell me about your order?}
{302}{}{Har du någonsin hört talas om en apparat som kallas GECK?}
{303}{}{Vet du var jag kan hitta Vault 13?}
{304}{}{Hej då.}
{400}{}{Vad vill du veta?}
{401}{}{Okej. Jag skulle vilja veta något annat.}
{402}{}{Hmm... det låter *faktiskt* bekant. Ja, jag minns att broder Thomas nämnde något om det nyligen. Jag är ledsen, men jag minns inte exakt vad han sa.}
{403}{}{Det är okej. Peka bara ut var broder Thomas är så frågar jag honom.}
{404}{}{Jag vet ingenting om det.}
{405}{}{Nåväl, tack ändå.}
{406}{}{Jag är rädd att jag inte kommer att kunna göra det. Du förstår, jag har fått intrycket att broder Thomas inte längre är bland
 de levande. Men lyckligtvis för er var han en av våra mest pålitliga transkriberare. Jag är säker på att alla artiklar han kom över
 om informationen du söker har transkriberats till våra datorer.}
{407}{}{Vänta lite, du "har fått intrycket" att broder Thomas är död? Där jag kommer ifrån är döden en ganska tydlig sak. Så, är han död, eller är han inte?}
{408}{}{Broder Thomas har varit försvunnen i flera dagar, ända sedan han gick ner till grottorna under Klostret. [Han drar en utmattad suck.]
 Du förstår, några av Klostrets invånare påstod sig ha sett ett enormt odjur lura där nere, och broder Thomas var ganska skeptisk.
 Han tog på sig att gå och skingra dessa rykten, men det visar sig att hans försvinnande bara har bekräftat dem ytterligare.}
{409}{}{Hmmm. Jag kanske borde ta en titt på vad som finns där nere. *JAG ÄR* den utvalde trots allt...}
{410}{}{Jag är äventyrlig. Jag kan ta en titt.}
{411}{}{Skulle du verkligen göra det? När du är där nere kanske du kan leta efter en viss bok. Du förstår, den var senast
 i broder Thomas ägo, och den är mycket viktig för oss, eftersom den ärvdes genom leden från våra grundare.
 Om du kunde hämta den boken, skulle jag vara mycket tacksam. Jag skulle ge dig full tillgång till våra datorer, så att du
 kan leta efter vad du än önskar.}
{412}{}{Det är en överenskommelse. Jag kommer snart tillbaka.}
{413}{}{Kanske, låt mig tänka på det här lite mer...}
{414}{}{Tack så mycket. Låt mig veta om du hittar boken.}
{415}{}{Okej, hej då.}
{416}{}{Hej, min vän.}
{417}{}{Jag har dödat ditt odjur och jag har din bok.}
{418}{}{Utmärkt! Låt mig ta den!}
{419}{}{Varsågod.}
{420}{}{Inte så fort. Hur mycket är den värd för dig?}
{421}{}{[Han tar boken från dig och smeker dess omslag som för att lugna den.] Du har gjort oss en stor tjänst. Du har nu
 full tillgång till våra datorer i biblioteket. Säg till broder Paul att jag ger dig tillstånd att använda våra filer.}
{422}{}{Tack.}
{423}{}{Vill du ha pengar för den? Visst, här är $250. Gå till broder Paul för att få tillgång till datorerna.}
{424}{}{Tack för pengarna, hej då.}
{425}{}{Du borde titta igenom en dator på andra våningen, nu när du har full tillgång dit.}
{426}{}{Okej, hej då.}
{430}{}{Vad är syftet med er grupp?}
{431}{}{Vad är historien bakom Klostret?}
{432}{}{Hmm, jag har inga frågor just nu.}
{433}{}{Our holy mission is to read, copy and take care of our sacred books of knowledge and other relics of the lost age.
 It is our hope that with this knowledge we are able to create a Memorabilia that might one day help humanity emerge from
 its self-imposed Dark Age. Any information that we come across is recorded, lest it be lost like so much was in the
 great Flame Deluge.}
{434}{}{After the Great War, the guiding hands of fate directed our ancestors to this old Abbey in the mountains. Due to
 its remote location, the monastery survived the Flame Deluge mostly unscathed. As our ancestors explored the building,
 they discovered an extensive library of books. And not just religious texts, oh no, this library contained the gamut of
 written works, from literary classics, to scientific encyclopedias.}
{435}{}{What happened then?}
{436}{}{I've heard enough.}
{437}{}{They soon realized the true treasure trove of wisdom stored within those books--especially the scientific tomes.
 Here were the chronicles of a fallen civilization. A lost age. There were a few who thought it might be best to
 destroy this knowledge, for fear that it would once again guide humanity towards apocalypse. But it was eventually
 decided that they would instead dedicate themselves to ensuring the preservation of the books, to be released when,
 and if, the world was ready for it.}
{438}{}{(Mer)}
{439}{}{And so, utilizing a small printing press, they began making copies of the books, and also transcribing them
 into the Abbey's computers to preserve them digitally, should the physical books ever be destroyed. Over the long years,
 others have come across the Abbey, and some have elected to stay and live out their lives in the tranquil quiet of our mountain home.}
{440}{}{Thanks for the story.}
{441}{}{Where did your ancestors come from?}
{442}{}{They never told where they originally came from. We suspect that they came here originally from the east.}
{443}{}{Well, thanks for the story.}
{444}{}{Do you need any help here at the monastery?}
{445}{}{I found out what's wrong with your water pump.}
{446}{}{Do you know anything about the original founders?}
{447}{}{I do not know all the names of our founders, but the most important one I am aware of is Miller.
 Before the Great War he was an electrical engineer working for the United States government. Shortly thereafter,
 he converted to Catholicism and made an oath with himself that we would spend the rest of his life preserving the
 knowledge of the past. His greatest fear was that this knowledge would be lost forever and thus needed to be preserved
 so that future generations may benefit.}
{448}{}{You must be quite knowledgeable having read so much.}
{449}{}{I have indeed read much in my life. Yet you might be disappointed at the limitations of my knowledge. You see,
 we record and preserve. We are forbidden to act upon the wisdom of these books, therefore our understanding of the text is quite limited.}
{450}{}{Wait, you're telling me that you just blindly transcribe these books without even trying to comprehend them?}
{451}{}{As I've said, it is our job to preserve this knowledge, not to understand it. Before this knowledge can be
 returned to mankind, he must first prove to have risen above his tendency of mass genocide. That's the only way to
 ensure that history does not repeat itself.}
{452}{}{Well, I've got news for you: that day's never going to come. And while you're hoarding all this knowledge in your
 little mountain paradise here, people out in the wasteland are struggling every day to survive. In fact, my entire tribe
 is on the brink of destruction. The knowledge contained in these books could help cure diseases, improve crops, and greatly
 increase the chance of humanity's survival.}
{453}{}{Ah, well I suppose you make a good point. But it just seems like the information stored here could help out a lot
 of people. Even if you don't think the world's ready for this knowledge, I don't see why *you* can't at least try to learn from it.
 Otherwise, what's the point of keeping it?}
{454}{}{I understand your frustration with our ways, but you must understand that this is the way things have always been
 for us. To alter things now, after so many years... that would be blasphemous against our faith. No, I feel we must continue
 to live by the rules set by our ancestors.}
{455}{}{I understand your frustration with our ways, but you must understand that this is the way things have always been
 for us. To alter things now, after so many years... that would be blasphemous against our faith. Still, I shall consider
 your words. I sense great wisdom in you, wanderer. It is a pity I have met very few like you.}
{456}{}{Thanks. I'd like to know something else though.}
{457}{}{Very well. I'd like to know something else though.}
{500}{}{Sluta med det där!}
{501}{}{You gain %d experience points for bringing back the book.}
{600}{}{I fixed your broken waterpump.}
{601}{}{That is great news, indeed. That waterpump had been acting up for quite some time. Those merchants said they
 could take care of it, but they didn't seem to be making much progress. It's a good thing you came along. Thank you again.}
{602}{}{I expect some money for this you know. Now cough it up!}
{603}{}{No problem. I have some other questions though.}
{604}{}{I'm glad to be of assistance. Take care.}
{605}{}{[Frowns.] I see. Fine, here, take these coins. Now go, and stop bothering me.}
{606}{}{Thank you, *father*.}
{700}{}{Uhh... no I seem to have misplaced it.}
{701}{}{What!? [He sighs deeply.] It is most unfortunate that you were unable to recover that book. But you say you've
 killed the beast? Hm, then it should be safe to send our own people down to continue searching for it. Anyway, for your
 service, I shall grant you access to our computers. Go see Brother Paul for the access key.}
{702}{}{Tack.}
{800}{}{Actually, yes. Our main water pump has been acting up for some time, and now it finally seems to have broken down
 completely. If you know anything about machinery, do you think you could take a look and see if something could be done?
 There are a few merchants already working on it. I fear that little progress has been made though.}
{801}{}{I'm happy to help. I'll report back on the progress.}
{802}{}{Sure, I'll be glad to help... for a price of course.}
{803}{}{Actually on second thought, let me ask you something else.}
{804}{}{What!? Oh, fine. If that's the kind of person you are, then you shall receive payment for your service. Here's
 25 coins to begin with.  Please let me know if something can be done. [The man sighs as he hands you the coins]}
{805}{}{Hey, no need for the sighing. You think everything in life comes for free? Now, let me get to work.}
{806}{}{Really? Please, do tell.}
{807}{}{The motor gave out and fried all the connectors. I'm going to Vault City to get a new part.}
{808}{}{Oh thank you. You are indeed a great help. Please report back once you install the new part.}
{809}{}{I will. Be back soon.}
{900}{}{You explain to the Abbot that while the information they hold could lead to mankind's annihilation, it could also lead to mankind's salvation.}
{901}{}{You learn about the original founder of the Abbey.}
{1000}{}{I killie scary monster down in cave.}
{1010}{}{Really? That's great. That is very brave of you. You're a big boy.}
{1011}{}{Really? That's great. That is very brave of you. You're a big girl.}
{1012}{}{(smile) I know.}
{1020}{}{Did you happen to find a book lying there? A friend of mine had it, and he went missing.}
{1021}{}{I find book. Here, it heavy and no pitchers inside.}
{1022}{}{I no find book. Sorree. I go look now.}
{1030}{}{I find book.}
{1031}{}{That's great. Thanks. You're one special guy.}
{1032}{}{That's great. Thanks. You're one special gal.}
{1033}{}{JIPPIE.}
{1100}{}{I was down there earlier. I saw a few dead bodies, so I'm guessing one of them belonged to your missing monk. If
 it makes you feel any better, I killed the thing responsible for his death.}
{1110}{}{Ah... so it's as I feared. Brother Thomas shall be dearly missed. You have my thanks for ridding us of whatever
 wasteland beasts lurked down there. However, I... I don't suppose you found a book while you were down there. It's a very
 important book that was last known to be in Brother Thomas's possession.}
{1111}{}{No, but I suppose I could go back and check.}
{1112}{}{Do you mean this book?}
{1113}{}{Before I go, let me ask you something else.}
{1411}{}{Very interesting. I have to go now.}
{3000}{}{Hur kan jag hjälpa dig?}
{4091}{}{So no one else has even bothered to go down there and check on him? What if he's simply trapped down there somehow, and he's slowly starving to death?}
{4092}{}{I suppose that's possible, but you must understand. We are a peaceful people. The thought of going up against one of those wasteland monsters is terrifying to us. We're simply not equipped for such confrontations. }
{4177}{}{I've killed the beast.}
{4188}{}{Excellent! And how about the book; were you able to recover it?}
{6020}{}{If you truly want to show your gratitude, how about some money for my trouble?}
