{100}{}{Du ser en kort man som bär en bok i sina händer.}
{101}{}{Du ser Doc Jones, doktorn.}
{102}{}{Du ser en kort man med en bok som heter "Så, Du Vill bli Läkare."}
{103}{}{Hej, jag är Doc Jones. Du kan kalla mig Doc. Vad kan jag hjälpa dig med?}
{104}{}{Har aj-aj. Du fixa?}
{105}{}{Mår dåligt. Du fixa?}
{106}{}{Jag lam, du fixa?}
{107}{}{Har frågor. Okej?}
{108}{}{Ledsen, jag gå.}
{109}{}{Jag är skadad. Kan du hjälpa mig?}
{110}{}{Jag känner mig sjuk. Kan ni hjälpa mig?}
{111}{}{Jag är handikappad. Kan du hjälpa mig?}
{112}{}{Jag vill ställa några frågor till dig.}
{113}{}{Säger bara hej.}
{114}{}{Javisst. Här, vi ger dig en spruta av det här -- det här kommer att svida lite -- nu ett bandage,
 och där, nu är allt klart.}
{115}{}{Jag tacka. Hej då.}
{116}{}{Tack, Doc. Jag känner mig mycket bättre.}
{117}{}{Why, certainly. Here, you'll need to drink this -- all of it, I know it tastes foul. Now, just
 lie down on the bed over there, and I'll wake you in the morning.}
{118}{}{Me feel good. Bye.}
{119}{}{Thanks Doc, that did the trick.}
{120}{}{I'm sorry, but I don't have the proper facilities to perform surgery. I'd suggest you go to one
 of the bigger cities and see a surgeon. Try Vault City. It's north of here.}
{121}{}{Okay. Bye}
{122}{}{All right. Thanks anyway.}
{123}{}{What would you like to know?}
{124}{}{You work Darion?}
{125}{}{You leave here when want?}
{126}{}{What you know about Darion?}
{127}{}{How you be here?}
{128}{}{You say Darion got doggie?}
{129}{}{Jag gå nu.}
{130}{}{Do you work for Darion?}
{131}{}{Can you leave here if you want?}
{132}{}{What can you tell me about Darion?}
{133}{}{How did you come to be here in the first place?}
{134}{}{You mentioned Darion has a dog?}
{135}{}{Thanks for the information. I'll be heading out now.}
{136}{}{Well, yes and no. It's not by choice. I'm a prisoner here. Darion is getting up there in years
 and he needs a dedicated physician to look after him. The Khans keep me here for his needs. I'd rather
 be here for the people in the town above. They have no medical help at all, and there is a lot I can
 do to aid them.}
{137}{}{Okay. Need know more.}
{138}{}{Tack. Hej då.}
{139}{}{That's very commendable of you.}
{140}{}{I see. I'll be going now.}
{141}{}{They're squatters! Let 'em die. Get on with your life.}
{142}{}{No, I'm pretty much trapped here. I can't even leave to refill my medical supplies. Darion
 sends out for anything I need.}
{143}{}{Me got it. Go now.}
{144}{}{Need ask more.}
{145}{}{I guess you just aren't a trustworthy enough person to be allowed freedom.}
{146}{}{All right. I'm sorry, but I have to get going.}
{147}{}{I'm sorry to hear that.}
{148}{}{Darion is a mental case, plain and simple. He's got more spooks in his head than his dog has
 fleas. As far as I can figure it, he was a member of another gang called the Khans. They kidnapped
 this girl, Tandi, and held her for ransom. Her father didn't take kindly to that, and hired some merc
 to get her back. Darion was the only one to come out alive.}
{149}{}{Uh... what you said.}
{150}{}{Got go now.}
{151}{}{Uh-huh. Well, I'll be leaving now.}
{152}{}{Wow; I'm impressed with your knowledge.}
{153}{}{Låter som min typ av kille.}
{154}{}{Jag blev kidnappad. Jag var på väg från Valvstaden till Nya Reno för en välförtjänt semester. Gick
 till sängs en kväll och vaknade bunden och med munkavle nästa morgon. Runt en vecka senare var jag här. Har varit
 här sedan dess.}
{155}{}{Ugh.}
{156}{}{Tack. Jag gå nu.}
{157}{}{De svaga är ofta de starkas byte.}
{158}{}{I'm sorry to hear that.}
{159}{}{Intressant, men jag måste gå.}
{160}{}{Ja, han har en hund. Personligen tycker jag att det är den elakaste, mest avskyvärda varelsen på
 jorden. Den verkar dock älska Darion, så jag antar att den inte kan vara så illa.}
{161}{}{Frågar mer.}
{162}{}{Uh, bye.}
{163}{}{I see. Well, thanks for the warning.}
{164}{}{Ah. Well, I've got to go.}
{165}{}{I'll not help someone like you. Go away.}
{166}{}{Okay, well, you take care, and come back if you need anything.}
{167}{}{Färdigt.}
{168}{}{Now he's paranoid. He believes that Tandi is out to get him. He's obsessed with revenge, and he
 wants Tandi dead. He's riddled with guilt 'cause he hid and lived, rather than dying with his
 gang... and the list goes on and on.}
{200}{}{Darion is dead.}
{201}{}{Dar-e-on dead.}
{202}{}{He is!? Oh, this is wonderful news.}
{203}{}{What are you going to do now?}
{204}{}{What yoo do?}
{205}{}{Well, I see no reason to return to my old life. The town above us doesn't have any medical assistance, so I think
 I will go up and help them. Thank you again for freeing me.}
{206}{}{Of course. See you later.}
{207}{}{Hej då!}
{210}{}{I still need to pack a few things. I'll see you on the outside.}
{220}{}{Hey there, good to see you again! Everyone here really appreciates what you have done. I personally am glad
 to be out of there. Working for Darion was a nightmare.}
{221}{}{Glad I could help. So, tell me a little bit more about yourself.}
{222}{}{Alright, see you around.}
{230}{}{Well you see, I'm originally from the New California Republic, but I realized I had a gift for medical practices.
 So I trained as much as I could under the NCR medical staff, and once I had learned all I could, I decided to try and
 learn more by making my way to Vault City. I was lucky enough to meet Dr. Troy while he was tending an injured citizen
 outside the vault, and long story short, he agreed to finalize my training in Vault City. I had just finished my training
 and was heading out when Darion captured me.}
{231}{}{That's terrible. Well, I hope everything works out for you now.}
{240}{}{I hope so too. I think I can put my medical skills to good use here.}
{241}{}{Hej då.}
{250}{}{Thanks again for everything.}
{251}{}{It feels good to be helping civilized people again.}
