{100}{}{You see a customer.}
{101}{}{You see a townsperson.}
{150}{}{He looks like he's headed somewhere.}
{151}{}{She looks like she's headed somewhere.}
{152}{}{He's busy drinking and talking to other customers.}
{153}{}{She seems to be busy talking.}
{154}{}{He's looking over Tubby's shelves.}
{155}{}{She seems to be looking around Tubby's store.}
{156}{}{You don't see anything unusual about him.}
{157}{}{You don't see anything unusual about her.}
{200}{}{Försvinn från mig!}
{201}{}{Lämna mig ifred!}
{202}{}{Rör mig inte!}
{203}{}{Sluta!}
{204}{}{Vad är det du gör?}
{300}{}{Ursäkta, kan inte prata just nu.}
{301}{}{Vart var jag på väg nu igen?}
{302}{}{Hej.}
{303}{}{Ursäkta mig.}
{304}{}{Hej.}
{305}{}{Hos Becky är det bäst, och inte bara för priserna.}
{306}{}{Är du här för drinkarna eller för borden?}
{307}{}{Nu saknar vi bara några trubadurer.}
{308}{}{Hej.}
{309}{}{Är du en spelare?}
{310}{}{Hur är det där ute?}
{311}{}{Frankie är en skitstövel. Han är elak mot Becky utan anledning.}
{312}{}{Är du en vän till Becky?}
{313}{}{Ta en drink, kompis!}
{314}{}{Drick upp! Drinkar är billiga!}
{315}{}{Det är inte möjligt att dessa är utspädda.}
{316}{}{Den där färgaren vet verkligen vad hon håller på med.}
{317}{}{Det finns inget bättre än goda drinkar och trevligt sällskap.}
{318}{}{Det enda problemet med Beckys drinkar är att man lätt dricker för mycket!}
{319}{}{Becky... jag menar Rebecca, hon är verkligen en riktig raring.}
{320}{}{Om någon någonsin rör henne kommer de att få ångra sig.}
{321}{}{Det här är verkligen bra.}
{340}{}{Vi borde döda dig för det du gjorde.}
{341}{}{Jag vet inte vad hon gjorde mot dig, men hon förtjänade inte att dö.}
{342}{}{Vi kanske ska åka till New Reno, eftersom Becky's är stängt.}
{343}{}{Jag saknar Beckys leende.}
{344}{}{Ingen mer billig sprit.}
{345}{}{Lyan är inte densamma utan Becky's.}
{360}{}{Frankie har verkligen en trångt hål... i väggen, alltså.}
{361}{}{Jag gillar Hålet bättre än Becky's.}
{362}{}{Vi kallar den här platsen för Hålet.}
{363}{}{Sätt dig ner. Åh, vänta lite. Kanske inte.}
{364}{}{Frankie's är fullt av liv och rörelse. Becky's är bara en pengaslukare.}
{365}{}{Frankie gillar verkligen inte Becky.}
{366}{}{Frankie säger att Beckys drinkar är urvattnade.}
{367}{}{Hur går det?}
{368}{}{Frankie vet hur man festar.}
{369}{}{Beckys bord är riggade! Eller, det är i alla fall vad Frankie säger.}
{370}{}{Botten upp!}
{390}{}{Fan, jag varnade Frankie för hur han behandlade folk.}
{391}{}{Frankie borde ha hållit sig i skinnet.}
{392}{}{Var ska vi nu hänga?}
{393}{}{Synd att Frankie är borta. Han visste hur man festade.}
{394}{}{Du har ett riktigt temperament. Vad har Frankie gjort mot dig?}
{395}{}{Har Frankie förolämpat din mamma eller nåt?}
{410}{}{I'm just looking around.}
{411}{}{Jag är inte säker på vad jag letar efter.}
{412}{}{Tubby använder verkligen en hel del Jet.}
{413}{}{Har du sett något bra?}
{414}{}{Inte mycket här.}
{415}{}{Tubby behöver hitta bättre leverantörer.}
{416}{}{Behöver du droger? Tubby brukar ha ett bra lager.}
{430}{}{Varför dödade du Tubby?}
{431}{}{Ingen stor förlust, men Tubby var den enda riktiga affären i stan.}
{432}{}{Vad gjorde Tubby för att göra dig arg?}
{433}{}{Tubby sålde en massa skit till dig, eller hur?}
{434}{}{Det ryktas att du gjorde dig av med Tubby på grund av en dålig affär eller något sånt.}
{435}{}{Det förvånar mig egentligen inte. Många har varit missnöjda med Tubby på sistone.}
{440}{}{Det finns inget som intresserar mig idag...}
{441}{}{Hej. Jag pratade bara med min goda vän Flick.}
{442}{}{Vad gör du här inne?}
{443}{}{Är du också en vän till Flick?}
{444}{}{Jag har inte gjort någonting.}
{445}{}{Vad stirrar du på?}
{446}{}{Låtsas bara att du inte ser mig.}
{447}{}{Bry dig inte om mig.}
{460}{}{Fan också. Du dödade Flick.}
{461}{}{Lurade Flick dig?}
{462}{}{Flick har ägnat sig åt farligt arbete.}
{463}{}{Det där med Flick suger.}
{464}{}{Undrar vad alla de där barnen ska ta sig till nu när Flick är död.}
{465}{}{Jag är förvånad över att Flick höll ut så länge.}
{480}{}{Det här är vårt hem.}
{481}{}{De flesta av oss har vuxit upp med Mamsens mat.}
{482}{}{Jag har känt Mamsen sedan jag var liten.}
{483}{}{Mamsen tar hand om alla i Lyan.}
{484}{}{Mamsen kan göra en smörgås av vad som helst.}
{485}{}{Jag hoppas att du lär känna Mamsen lika väl som oss.}
{486}{}{Fantastiskt sällskap, fantastisk mat. Vad mer kan man önska sig?}
{487}{}{Skål!}
{488}{}{Hej.}
{500}{}{Hur kunde du skada stackars gamla Mamsen?}
{501}{}{Jag känner, jag menar, kände Mamsen hela mitt liv.}
{502}{}{Vad har hon egentligen gjort dig?}
{503}{}{Mördare! Stackars Mamsen...}
{504}{}{Varför var du tvungen att göra så?}
{505}{}{Ditt hjärtlösa monster!}
