{100}{}{Du ser en invånare från Lyan.}
{101}{}{Du ser Derek.}
{150}{}{Han ser ganska smidig ut.}
{200}{}{Stick härifrån.}
{201}{}{Jag är för trött för att prata.}
{202}{}{Stick härifrån. Det här är mitt ställe.}
{203}{}{Skaffa dig en egen sovplats.}
{204}{}{Sluta störa mig.}
{205}{}{Jag är helt slut.}
{206}{}{Doh!}
{207}{}{Hej, vad gör du här?}
{220}{}{Håll dig borta från Metzger, stammedlem.}
{221}{}{Varför är det alltid så jäkla varmt?}
{222}{}{Varför bor vi i öknen?}
{223}{}{Jag är en duktig kock.}
{224}{}{En dag ska jag öppna en egen restaurang.}
{225}{}{Jag önskar att jag hade ett riktigt kök.}
{226}{}{Varför är det alltid jag som drabbas?}
{227}{}{Folk lurar mig hela tiden.}
{228}{}{Fred är en drömmare – huvudplan, så fan heller.}
{240}{}{Tyst! De är överallt.}
{241}{}{Få dem att sluta!}
{242}{}{Så du hittade den där jäkla boken?}
{243}{}{Jag vet inte varför Becky inte vill anställa mig.}
{244}{}{Jag kommer inte att bli galen!}
{245}{}{Jag har fått min sovplats!}
{246}{}{De kommer oftast fram på natten.}
{247}{}{Jag gillar potatisar!}
{248}{}{Gå inte på det gröna utan stövlar!}
{249}{}{Just turn it inside out.}
{250}{}{Oh, my head hurts really bad now.}
{251}{}{I'm a grandmaster cook!}
{252}{}{I would never poison a newbie's food.}
{260}{}{Hey you looking for some freshly baked bread?}
{261}{}{Ja.}
{262}{}{I'm looking for Becky's book.}
{263}{}{No, bye.}
{270}{}{Oh, hi again.}
{271}{}{So where's Becky's book?}
{272}{}{Hey, how about some of that bread?}
{273}{}{Hej då.}
{280}{}{Ha! So am I. Have I told you what a great cook I am? Becky wont' hire me for some reason. She says I'm unstable.}
{281}{}{She's probably right.}
{282}{}{I'm looking for Becky's book.}
{283}{}{That's great. I've uh... got to go.}
{290}{}{What? You! Screw you buddy! I'm not... Ow! Fuck.}
{291}{}{What? You! Screw you lady! I'm not... Ow! Fuck.}
{292}{}{Förbannat.}
{293}{}{Så e de'.}
{300}{}{Jaha. Jag tyckte inte om den. För mycket kyssar. Jag slängde den i hörnet i den där byggnaden... nä den där byggnaden... nej... var det en byggnad? Kanske tappade jag den någon annanstans... eller kastade jag den? Aj! Mitt huvud!}
{301}{}{Boken? Åh, den boken. Vem skickade dig? Jag är inte säker på om du står på rätt sida. Glöm inte näsduken.}
{302}{}{Jag kan inte! De är... åh nej... Har du osten? Göm dig!}
{303}{}{Hallå! Det är inte mitt problem. Vad skulle jag ha gjort? Slåss mot dem? Små gröna män med stora spetsiga tänder! Fan! Aj! Sluta med det där!}
{304}{}{Mitt huvud gör ont! Vad... vem sa det där?}
{305}{}{Det där hjälper verkligen.}
{306}{}{Eh.}
{310}{}{Va? Driver du med mig! Dra åt helvete! Jag är inte instabil! Jag kan laga mat! Jag hör inga röster i huvudet!}
{311}{}{Jag ska - fan! Skit också! Förbannat! Sluta med det där. Var tyst! Vadå?... Okej.}
{312}{}{Hörru! Vänt- åh... fan.}
{313}{}{Hej då.}
{314}{}{Ingenting.}
{320}{}{Hallå! Lämna mig ifred!}
{321}{}{Rör mig inte!}
