{100}{}{Du ser en invånare från Lyan.}
{101}{}{Du ser Derek.}
{150}{}{Han ser ganska smidig ut.}
{200}{}{Stick härifrån.}
{201}{}{Jag är för trött för att prata.}
{202}{}{Stick härifrån. Det här är mitt ställe.}
{203}{}{Skaffa dig en egen sovplats.}
{204}{}{Sluta störa mig.}
{205}{}{Jag är helt slut.}
{206}{}{Doh!}
{207}{}{Hej, vad gör du här?}
{220}{}{Håll dig borta från Metzger, stammedlem.}
{221}{}{Varför är det alltid så jäkla varmt?}
{222}{}{Varför bor vi i öknen?}
{223}{}{Jag är en duktig kock.}
{224}{}{En dag ska jag öppna en egen restaurang.}
{225}{}{Jag önskar att jag hade ett riktigt kök.}
{226}{}{Varför är det alltid jag som drabbas?}
{227}{}{Folk lurar mig hela tiden.}
{228}{}{Fred är en drömmare – huvudplan, så fan heller.}
{240}{}{Tyst! De är överallt.}
{241}{}{Få dem att sluta!}
{242}{}{Så du hittade den där jäkla boken?}
{243}{}{Jag vet inte varför Becky inte vill anställa mig.}
{244}{}{Jag kommer inte att bli galen!}
{245}{}{Jag har fått min sovplats!}
{246}{}{De kommer oftast fram på natten.}
{247}{}{Jag gillar potatisar!}
{248}{}{Gå inte på det gröna utan stövlar!}
{249}{}{Just turn it inside out.}
{250}{}{Oh, my head hurts really bad now.}
{251}{}{I'm a grandmaster cook!}
{252}{}{I would never poison a newbie's food.}
{260}{}{Hey you looking for some freshly baked bread?}
{261}{}{Ja.}
{262}{}{I'm looking for Becky's book.}
{263}{}{No, bye.}
{270}{}{Oh, hi again.}
{271}{}{So where's Becky's book?}
{272}{}{Hey, how about some of that bread?}
{273}{}{Hej då.}
{280}{}{Ha! So am I. Have I told you what a great cook I am? Becky wont' hire me for some reason. She says I'm unstable.}
{281}{}{She's probably right.}
{282}{}{I'm looking for Becky's book.}
{283}{}{That's great. I've uh... got to go.}
{290}{}{What? You! Screw you buddy! I'm not... Ow! Fuck.}
{291}{}{What? You! Screw you lady! I'm not... Ow! Fuck.}
{292}{}{Förbannat.}
{293}{}{Nuf Said.}
{300}{}{Oh yeah. I didn't like it. Too much kissing. I threw it in the corner of that building... no that building... no... was it a building? Maybe I dropped it somewhere else... or did I throw it? Ow! My head!}
{301}{}{Book? Oh, that book. Who sent you? I'm not sure if that's the proper side. Don't forget the tissue.}
{302}{}{I can't! They're... oh crap... Do you have the cheese? Hide!}
{303}{}{Hey! Not my problem. What was I supposed to do? Fight them? Little green men, big pointy teeth! Fuck! Ouch! Stop that!}
{304}{}{My head hurts! What... who said that?}
{305}{}{That helps a lot.}
{306}{}{Eh.}
{310}{}{What? Are you mocking me! Screw you! I'm not unstable! I can cook! I don't have voices in my head!}
{311}{}{I'm gonna- shit! Fuck! Damn it! Stop that. Be quiet! What?... Okay.}
{312}{}{Hey! Sto- do... fuck.}
{313}{}{Hej då.}
{314}{}{Ingenting.}
{320}{}{Hey! Get away from me!}
{321}{}{Rör mig inte!}
