{100}{}{Du ser en knarklangare.}
{101}{}{Du ser en knarklangare.}
{102}{}{Om du är ute efter att göra en affär, så har jag det du söker.}
{103}{}{Visst, visa mig.}
{104}{}{Kanske en annan gång.}
{105}{}{Hittade du det du letade efter?}
{106}{}{Tack. Hej då.}
{200}{}{Du ser en ligist.}
{201}{}{Du ser en ligist.}
{202}{}{Jag är här för att skydda stället. Prata med langaren om du vill köpa något.}
