{100}{}{Du ser en tunn, oljig man.}
{150}{}{Du ser Flick, som kliar sig ordentligt i skrevet.}
{151}{}{Du ser en oren man med en otäck ansiktsryckning.}
{200}{}{Draa hääifrån, din idiot.}
{201}{}{Hörru, köttbullen! Ja, du. Draa hääirån.}
{202}{}{Är du dum elle'?}
{203}{}{Whatchur problem, eh?}
{204}{}{Draa hääifrån, fö' i helvette}
{220}{}{Hallå dä', jag ä' Flick. Vad i helvete vill du, va?}
{221}{}{Now what? You wastin' my time heeya.}
{222}{}{What's with the wacky accent, Flick?}
{223}{}{What the hell do you do here?}
{224}{}{I'm looking for a Vault - oh yeah, and some trader named Vic, too. Know where they might be?}
{225}{}{I'd like to trade with you.}
{240}{}{That 'bout do it for ya, pal?}
{241}{}{Actually I'd like to take another look at your goods if I may.}
{242}{}{Actually, I'd like to ask you a question.}
{243}{}{That did it. See you around, Flick.}
{260}{}{I'm a fuckin' provider, waddya think? I'm like a good Samurai-itan guy.}
{261}{}{Say what?}
{262}{}{Yeah, uh, well... let me ask you something else.}
{263}{}{Eh, åh. OK, Hej då, Flick.}
{280}{}{I provide fer them little paisanos.}
{281}{}{You provide little pianos?}
{290}{}{Pai-san-o, you know, the kids. My kids.}
{291}{}{Dina barn?}
{292}{}{Jag är inte riktigt intresserad av musiklektioner för barn. Låt mig fråga dig om något annat.}
{300}{}{Ja, de jobbar för mig. De ger mig saker. Små saker. Du vet.}
{301}{}{Uh, no.}
{302}{}{Åh, okej. Låt mig fråga dig något annat då.}
{303}{}{Jaha, jag förstår. Jag vill inte störa din, eh, stil. Hej då.}
{315}{}{They bring me stuff that they find. Little, little things. Stuff no one ain't usin' no more. In return, I takes care of 'em.}
{316}{}{Låter som ett trevligt arrangemang.}
{325}{}{(Flick rycker på axlarna) Jag klarar mig bra.}
{326}{}{Låt mig fråga dig om något annat då.}
{327}{}{De måste ha gett dig några riktiga fynd. Låt mig se vad du har.}
{328}{}{Jag kollar bara. Hej då, Flick.}
{340}{}{What you talkin' about? You think I'm a fucking stupid pirla? Some dumb filio di puttana? You think I'm some kinda clown? Am I here to amuse you, is that it?}
{341}{}{Uh, no. Sorry, I was just curious. Let me ask you about something else.}
{342}{}{Yeah, that's right, shithead. And nothing's going to amuse me more than your death-throes.}
{343}{}{Well, if you're going to get all huffy about it, I'm leaving.}
{360}{}{Vault huh? Maybe Momma knows about that, 'cause I don't. But that Vic guy - him I know. Metzger's got that porca pistola.}
{361}{}{Vic? Ain't that him with you? You biota. But Momma, her I know.}
{362}{}{Who's Metzger?}
{363}{}{Who's Momma?}
{364}{}{Thanks. Let me ask you something else.}
{365}{}{Thanks, that's all I need to know. Goodbye.}
{380}{}{Momma runs a food place over in da East side a town. Just past the graveyard. Nice place, she got good pasta, Mama mia.}
{381}{}{Thanks, What about that Metzger fellow that's got Vic?}
{382}{}{Thanks. Let me ask you something else.}
{383}{}{Thanks, that's all I need to know. Goodbye.}
{400}{}{That's right. Metzger, that stronzo, he's dead. I don't know what happen to Vic.}
{401}{}{That Metzger, he's a real rompiballe, that one. Runs the Slaver's Guild. East side of town, just north of Momma's. Anyhow, he got Vic, I know.}
{402}{}{Thanks, now what about Momma?}
{403}{}{Thanks. Let me ask you something else.}
{404}{}{Thanks, that's all I need to know. Goodbye.}
{410}{}{Well fuck me sideways, look who came by. The good samaritan who "saved the children" decided to grace me with his presence.
 You know, I'm a good Samurai-itan guy myself -- providin' fer them little paisanos and all. That is, until you came along and made that
 fuckin' orphanage idea a reality.}
{411}{}{Well fuck me sideways, look who came by. The good samaritan who "saved the children" decided to grace me with her presence.
 You know, I'm a good Samurai-itan guy myself -- providin' fer them little paisanos and all. That is, until you came along and made that
 fuckin' orphanage idea a reality.}
{412}{}{You provide little pianos?}
{413}{}{You sound like you don't like the fact that the children are no longer roaming the streets.}
{420}{}{Hey, don't get me wrong. Life on the street is tough fer them kids, but it's the end of our little arrangement that gets me down.}
{421}{}{What arrangement?}
{422}{}{You mean them pickpocketing from people and bringing the items to you to sell.}
{430}{}{Försök inte vara smart mot mig, din jävel. Barnen ger mig saker som de *hittar.* Jag vet inte var de får dem ifrån och ärligt talat bryr jag mig inte ett skit.}
{431}{}{Just det.}
{432}{}{Du är full av det. Jag är trött på skumma typer som du som utnyttjar folk för egen vinning. Dags att dö!}
{440}{}{Pai-san-o, you know, the kids. My kids.}
{441}{}{Och du har en överenskommelse med dem?}
{450}{}{They bring me stuff that they find. Little, little things. Stuff no one ain't usin' no more. In return, I takes care of 'em.}
{451}{}{Låter som ett trevligt arrangemang.}
{460}{}{Yeah... business was good 'til you came along. See, yer little stunt's gonna cost me. My business is gonna suffer thanks to you.
 Because of this, I don't really like you too much. In fact, I fuckin' hate you. But, I'm a business man, so if you need to barter,
 get to it. If not, fuck off.}
{461}{}{Alright, let's see what you have in stock then.}
{462}{}{I think I have all I need. Goodbye.}
{463}{}{I think I'll stay... and kick your ass.}
{470}{}{You again? You better be here to make some good trades, 'cause I'm getting real fuckin' sick of looking at you.
 In fact, I vomit in my mouth a little every time I see yer face. That's how much you disgust me. And if yer not here to
 trade, then I suggest you turn around and walk the fuck outta here.}
{471}{}{Let's trade.}
{472}{}{Jag kollar bara. Hej då, Flick.}
{480}{}{You done wastin' my time?}
{481}{}{Let me take another look.}
{482}{}{That should do it. Goodbye Flick.}
