{100}{}{You see a Hologram.}
{101}{}{You see the Director of Public Relations.}
{102}{}{Hologram 40011. She is in charge of all the tours and press releases at the EPA.}
{200}{}{[This attractive female hologram greets you with a friendly smile.] Hello visitor, and welcome to the EPA. How may I help you? Lunch will be served in the cafeteria at mid-day for all company employees.}
{201}{}{What? Oh nevermind. Who are you?}
{202}{}{I need to be going. Bye.}
{210}{}{Me? I'm Hologram 40011, the Director of Public Relations. I organize trips, tours and other things and ensure that the place is running smoothly for the public on a day to day basis. The tour of the EPA museum will begin shortly. Please have your passes ready.}
{211}{}{That sounds like a riveting job. Goodbye.}
{212}{}{So maybe you could help me with something?}
{220}{}{Of course. I'd love to help. How may I assist you? Tour pamphlets can be found in the main office and in letterboxes throughout the EPA.}
{221}{}{There's some doors around the complex that I can't open without speaking a password. I'd really like to get through them and see more of your facility. I don't suppose you know the password?}
{230}{}{Of course I know the password, but unfortunately, I'm unable to share it with you. I understand your enthusiasm for wanting to experience all that this great facility has to offer, but there are rules we must follow for your own safety. Remember everyone, we offer guided tours of our complex at predetermined times.}
{231}{}{Oh, you don't have to worry about my safety, I'm the Chosen One. Besides, when's the last time you had a *real* visitor? Do you really want to leave me disappointed?}
{232}{}{Right then. Goodbye}
{240}{}{Självklart inte. Men om jag ger dig lösenordet, kan jag inte bara utsätta dig för fara, utan även komplexet. Barn, var snälla och reta inte hologrammen.}
{241}{}{Hur kan det äventyra komplexet? Jag gillar inte att säga det, men det här komplexet har redan gått åt helvete. Det finns inget annat här än farliga kemikalier och trasiga robotar. Ärligt talat, jag ser inte hur jag skulle kunna göra saken värre.}
{242}{}{Åh glöm det då.}
{250}{}{Jag... jag vet inte. Jag skulle trotsa protokollet. Men... kanske om du kunde hjälpa mig med något. Besökare, observera att den blå nivån är begränsad av skäl som är mycket ointressanta. Det finns ingen anledning att vara nyfiken på det.}
{251}{}{Visst, jag kan hjälpa dig. Berätta bara vad du behöver.}
{260}{}{Ja, det ser mycket bättre ut här inne nu, tack. Lösenordet är ABRE. Tala bara tydligt till dörren och den
 kommer att öppnas. Kan alla nu vara snälla och...}
{261}{}{JA, vi har redan hört dig. Tack för koden. Hej då.}
{270}{}{Hej igen. Vad är det du behöver? EPA-komplexet kommer att vara stängt under överskådlig framtid på grund av personalbrist.}
{271}{}{Nu när jag har mer tid, kan du berätta vad du gör här?}
{272}{}{Det är inte viktigt.}
{280}{}{Welcome back, visitor. There isn't a tour at the moment, but if you'd like to wait around for enough visitors to arrive, I'd be happy to arrange one.}
{281}{}{I don't want to go on a tour, thanks. Goodbye.}
{282}{}{I wonder if you could do something for me?}
{290}{}{Hello there. I'm a little busy at the moment designing a new tour program for the coming season. Could you come back later?}
{291}{}{I would, but I'm in too much of a hurry. You see, I *really* need the password for those doors. Would you please give it to me?}
{300}{}{Thanks again for your assistance, and please be responsible with the password I gave you. Remember, that's our little secret. Thank you for visiting the EPA, I hope you have a pleasant experience.}
{301}{}{Tack. Hej då.}
{302}{}{Come visit us again sometime.}
{303}{}{Don't forget to visit the EPA souvenir stand.}
{310}{}{Do you think you could fix the lighting? It's improper for me to conduct tours through such a dimly lit complex.
 If you could brighten this place up for me, I'll give you the password. Please, remember to wash your hands thoroughly
 after visiting our petting zoo.}
{311}{}{Alright. I'll see what I can do.}
{312}{}{Nevermind. I'm not interested.}
{320}{}{The complex is still looking rather drab. You're still going to fix the lights, aren't you? Remember visitors, all waivers must be signed before the end of the tour.}
{321}{}{Don't worry. I'm working on it.}
{322}{}{I'll get around to it.}
{330}{}{We'd have more visitors if the grounds were clean.}
{331}{}{How am I supposed to conduct tours without proper lighting?}
{332}{}{Those plants are killing all potential tourists.}
{333}{}{All those broken down robots are *very* unsightly.}
{334}{}{10031, you've been useless for decades.}
{335}{}{All I'm saying, is that this place needs to be more presentable.}
{336}{}{Destroying the complex is not the answer.}
