{100}{}{Bạn gặp thương gia Bill.}
{101}{}{Bạn gặp một thương gia có ngoại hình đứng tuổi.}
{200}{}{Xin chào, lữ khách. Tên tôi là Bill. Tôi có thể giúp gì cho cô?}
{201}{}{Chào mừng quay lại. Cô cần thêm gì không?}
{202}{}{Hãy giao dịch.}
{203}{}{Tôi nghe nói muốn biết về đoàn lữ hành thì đến gặp ông.}
{204}{}{Không có gì. Xin chào.}
{210}{}{Này, tôi thấy ở Tu viện họ đã sưu tập rất nhiều đồ và vật dụng cũ.
Tôi tự hỏi liệu ông có tìm thấy thứ gì đó... đặc biệt trong lúc ở đây không?}
{211}{}{Hể, vậy là cô cũng để ý hả? Đúng vậy, những người ở Tu viện khá là thích những đồ trước chiến tranh,
nhất là mấy món công nghệ. Họ đã dựng lên cả một thứ tôn giáo kì quái cho sở thích này. Tôi không hiểu lắm,
nhưng họ là những người tốt và trả đẫm tiền cho bất cứ thứ gì trước chiến tranh mà tôi kiếm được. Nhưng mà,
thứ gì đó đặc biệt à... Hừm, [Ông ta liếc nhìn Marcus]. Tình cờ thật đấy, tôi có đúng thứ này mà anh bạn
đây có thể sẽ cần.}
{212}{}{Hể, vậy là cô cũng để ý hả? Đúng vậy, những người ở Tu viện khá là thích những đồ trước chiến tranh,
nhất là mấy món công nghệ. Họ đã dựng lên cả một thứ tôn giáo kì quái cho sở thích này. Tôi không hiểu lắm,
nhưng họ là những người tốt và trả đẫm tiền cho bất cứ thứ gì trước chiến tranh mà tôi kiếm được. Nhưng mà,
thứ gì đó đặc biệt à... Hừm, [Ông ta liếc nhìn nhóm của bạn]. Rất tiếc, tôi e là hiện tại tôi không có thứ gì
đặc biệt mà cô cần.}
{213}{}{Vậy à. Thế thì xem ông đang có gì trong kho nào.}
{214}{}{Được rồi. Tôi muốn hỏi về thứ khác.}
{215}{}{Như là?}
{216}{}{Cô thấy đấy, một đoàn lữ hành có ghé qua chỗ này cách đây không lâu, tự nhận đến từ phía Nam xa xôi. Họ nói
bị một đám đột biến xấu xa tấn công (quay sang Marcus) tôi không có ý gì đâu, anh chàng to lớn ạ. Mà rồi họ cứ huyên
thuyên về việc đã diệt gọn cả đám gần nửa tá đột biến, còn tôi thì cho rằng đấy chỉ là chuyện bố láo. Ấy thế mà thực tế
là họ lại có bằng chứng.}
{217}{}{Ồ? Thứ gì vậy?}
{218}{}{Một bộ áo giáp khổng lồ dành cho người đột biến mà họ đã lấy ra được từ một cái xác. Dĩ nhiên, theo như tôi đoán thì
có thể đám này đã moi được từ xương một gã đột biến đã tạch từ lâu mà họ tình cờ gặp trong hoang mạc, nhưng ai mà
biết được? Dù sao thì họ cũng không muốn vác đống tạ đấy mãi nên đã bán cho tôi với giá đồng nát. Tôi còn chẳng biết
sẽ làm gì với cục nợ này, nhưng chắc vẫn là món hời.}
{219}{}{Chà, tôi chắc là Marcus có thể dùng được thứ này. Giá nhiêu thế?}
{220}{}{Hấp dẫn đấy. Mà Marcus đủ cứng rồi. Tôi e là bọn tôi sẽ không cần thứ này. Tôi muốn hỏi về chuyện khác.}
{221}{}{Ồ, cục nợ này bỏ nồi đun ra cũng phải đúc được tầm ba hoặc bốn bộ giáp sắt. Chốt giá 3000$ nhé.}
{222}{}{Được, tôi mua.}
{223}{}{Chắc là để sau đi. Tôi muốn hỏi về chuyện khác.}
{224}{}{Vậy là chốt kèo. Bộ giáp này cần đến hai người khiêng cơ, nên để tôi lắp đồ cho cậu bạn đây.}
{225}{}{[Đã xong]}
{226}{}{Ầy, vừa zin luôn!}
{300}{}{Chắc là tôi biết đấy. Cô muốn hỏi gì nào?}
{301}{}{Bao lâu thì ông lại nhập hàng một lần?}
{302}{}{Đoàn lữ hành có tuyển người không?}
{303}{}{Mà thôi, tôi phải đi đây.}
{304}{}{Tôi nhập hàng hai lần mỗi tháng. Nói thật thì tôi ước gì bọn họ có thể đến thường xuyên hơn, nhưng chỗ khỉ ho
cò gáy này thì đành chấp nhận vậy thôi.}
{305}{}{Tôi không chắc lắm. Thường thì những người đến đây đều đeo đồ kín người và không muốn ở lại quá lâu.
Nhưng nếu cô muốn nhập đoàn với một trong số họ thì tôi chắc là có đoàn đi Redding hoặc thậm chí là đến
tận NCR. Mấy đoàn này di chuyển nhiều và họ luôn cần thêm người đủ lực.}
{306}{}{Hay đấy. Tôi đang thắc mắc về thứ khác.}
{307}{}{Cám ơn. Giao dịch nào.}
{308}{}{Ồ, cám ơn vì thông tin. Gặp ông sau.}
{400}{}{Đã tìm thấy những thứ cô cần chưa?}
{401}{}{À tôi muốn xem kho hàng thêm lần nữa.}
{402}{}{Tôi xong rồi. Gặp ông sau.}
