{100}{}{Bạn thấy Hank.}
{101}{}{Bạn thấy một thầy tu dính đầy dầu mỡ.}
{102}{}{Ông ta đang vật lộn với cái bình lọc.}
{200}{}{Này, cô bạn. Cô có bật lửa ở đấy không?}
{201}{}{Có. [Đưa bật lửa cho ông ta].}
{202}{}{Tuyệt vời. Cám ơn!}
{203}{}{Thắc mắc chút, ông đang làm cái quái gì ở đây thế?}
{204}{}{Được. Vì cậu đã mang bật lửa đến cho tôi, cốc này miễn phí.}
{205}{}{[Uống].}
{206}{}{Tôi đổi ý rồi, tôi không muốn lấy rượu. Chào nhé.}
{207}{}{(Bạn cảm thấy ấm áp và khoan khoái sau khi uống hết rượu).}
{208}{}{Thêm cốc nữa nào, Hank.}
{209}{}{Tôi phải đi đây. Chào.}
{210}{}{(Đột nhiên bạn cảm thấy như bòi, rồi mắt bạn mờ dần. Bạn gục xuống sàn...)}
{211}{}{[XONG]}
{212}{}{Không, xin lỗi.}
{213}{}{Chào.}
{214}{}{Chào và tạm biệt.}
{215}{}{Cốc này mất phí đấy, 20$.}
{216}{}{Được. Tiền đây.}
{217}{}{Thôi, tôi uống đủ rồi. Có lẽ để sau.}
{218}{}{(Ông ta bỏ tiền vào túi). Được rồi, rượu đây.}
{219}{}{Tôi sẽ quay lại khi nào có tiền.}
{220}{}{Có tìm được cái bật lửa nào không?}
{250}{}{Tôi muốn mua một ít rượu mà ông nấu ở đây.}
{251}{}{Chỉ ngó quanh thôi. Bảo trọng.}
{252}{}{Được chứ. 20$ một chai.}
{253}{}{[Giữ lại].}
{300}{}{Tôi để cái bật lửa ở đâu rồi?}
{301}{}{Tôi cần bật lửa.}
{302}{}{AI ĐÓ MANG BẬT LỬA ĐẾN ĐÂY ĐƯỢC KHÔNG!?}
{303}{}{Ờ, xin chào.}
{304}{}{Xin lỗi, hiện tôi không nói chuyện được.}
{400}{}{Ồ, nhìn những ngôi sao xinh đẹp kìa!}
{500}{}{Chào. Cần gì không?}
{501}{}{Này, cám ơn lần nữa vì cái bật lửa. Nó tốt hơn cái trước đây của tôi nhiều.}
{600}{}{Chúng tôi tự nấu rượu tại tu viện. Đây là một trong số những đồ ngon nhất hiện có tại Hoang mạc.}
{601}{}{Tôi thử được không?}
{602}{}{Nghe hấp dẫn đấy. Tôi phải đi đây.}
{700}{}{Tệ thật đấy. Gần đây tôi mới bị mất và chẳng tìm thấy nó đâu cả. Nếu cô mà tìm thấy một cái thì
vui lòng mang nó đến cho tôi nhé.}
{701}{}{Được. Tôi sẽ báo nếu tôi tìm được. Chào.}
{702}{}{Tiếc thật, tôi thích sưu tầm nên tôi giữ mọi thứ tôi kiếm được. Chào.}
{800}{}{Bật-lửa? Ngộ có máy lửa. Nó đốt ngộ nhiều. (Bạn giơ bật lửa lên).}
{810}{}{Đúng là thứ tôi cần. Cậu đưa nó cho tôi nhé?}
{811}{}{Ô kê. Ngộ khôn thít nó.}
{812}{}{Ngộ không đưa ông.}
{820}{}{Ông không đốt mình giờ. Chào!}
