{100}{}{Bạn thấy Jack, bác sĩ của Tu viện.}
{101}{}{Ông ta đeo biểu tượng chữ thập đỏ trên vai.}
{200}{}{Nếu cậu bị thương thì đến gặp tôi.}
{300}{}{Tôi giúp gì được nhỉ?}
{301}{}{Tôi bị thương, ông giúp tôi được không?}
{302}{}{[Chảy nước dãi].}
{303}{}{Vậy ông làm gì ở Tu viện vậy?}
{304}{}{Chào.}
{400}{}{Xong rồi!}
{401}{}{Cám ơn.}
{402}{}{Dừng lại!}
{403}{}{[TIẾP TỤC]}
{404}{}{[BỎ ĐI]}
{405}{}{DỪNG LẠI! DỪNG LẠI! DỪNG LẠI!}
{406}{}{[TIẾP TỤC]}
{407}{}{[DỪNG]}
{408}{}{(Đột nhiên, Jack bắt đầu chảy ra) TÔI ĐANG CHẢY, TÔI ĐANG CHẢY RA, ÔI GIỜI...}
{409}{}{Cái đi...}
{500}{}{Này, đừng có ăn trộm vật tư ý tế của tôi!}
{501}{}{Bạn nhận được 200 điểm kinh nghiệm vì đã làm Jack tan chảy. Vui lắm nhỉ, đồ bệnh hoạn?}
{600}{}{Tôi là bác sĩ. Tôi đã chăm sóc mọi người ở Tu viện này trong khoảng, ồ, tầm 15 năm rồi, chắc vậy.}
{601}{}{Vậy ư. Dành từng đấy năm để đọc toàn bộ chỗ sách y học trước chiến tranh trong thư viện, chắc hẳn ông là bác sĩ giỏi lắm.}
{602}{}{Ông kiếm đâu ra chỗ thiết bị y tế này thế?}
{603}{}{Hay đấy. Tôi e là tôi phải đi đây.}
{604}{}{[Ông ta cau mày]. Tôi tự cho mình là bác sĩ giỏi, nhưng tôi có học được quái gì đâu khi mà tôi còn chẳng được phép... mà thôi, bỏ qua đi. Cha tôi là bác sĩ, và ông truyền lại những
kiến thức này cho tôi.}
{605}{}{À, tôi hiểu rồi.}
{700}{}{Một số thuốc ở đây tôi nhận lại từ cha mình. Chỗ còn lại hầu hết có sẵn ở Tu viện.}
{701}{}{Hay đấy, chào.}
{702}{}{Ông xem liệu có thể cho tôi xin một ít thuốc được không? Có vẻ ông dư thừa khá nhiều.}
{703}{}{Cô muốn tôi *đưa* chúng cho cô? Cái gì khiến cô nghĩ rằng cô đáng được dùng thuốc hơn những người ở Tu viện?}
{704}{}{Bởi vì tôi hay bị thương... nhiều lần.}
{705}{}{Bởi vì tôi đang thực hiện nhiệm vụ thần thánh là đi tìm Bộ tạo Vườn Địa đàng. Ông thấy đấy, cả làng tôi sẽ
diệt vong nếu tôi không tìm được thứ này kịp thời. Còn những người của ông ở đây có vẻ như đang sống bình yên và
không cần nhiều thiết bị y tế đến thế này. Tôi không đòi hỏi đâu, ông cho bao nhiêu thì cho. Ít cũng là nhiều.}
{706}{}{[Ông ta đắn đo một lúc, rồi gật đầu]. Được rồi, tôi sẽ cho cậu một vài đồ y tế dư thừa của chúng tôi. Có vẻ như
cậu sẽ cần chúng. Đây. [Ông ta trao đồ cho bạn]. Chúc may mắn, người lữ khách.}
{707}{}{Cám ơn, Jack. Ông đúng là vị cứu tinh thực sự của hoang mạc. Tạm biệt.}
{708}{}{Vậy thì có lẽ cô nên học cách cẩn thận hơn. Xin lỗi, tôi sẽ không đem đồ y tế của Tu viện đi làm từ thiện đâu.}
{709}{}{Được rồi. TẠM BIỆT.}
{800}{}{Giờ tôi không nói chuyện được.}
{801}{}{Xin lỗi, tôi đang dở tay. Quay lại sau nhé.}
{802}{}{Chào gặp lại.}
