{100}{}{Bạn thấy Max.}
{101}{}{Bạn thấy một thầy tu bình thường của Tu viện.}
{102}{}{Ông ta trông có vẻ lo lắng.}
{200}{}{Xin chào. Tôi có thể giúp gì được?}
{201}{}{Tôi có thứ này do Elaine gửi...}
{202}{}{Đây là nơi nào?}
{203}{}{Chào.}
{300}{}{Để tôi đoán nhé. Đây là bộ phận mà tôi đã yêu cầu, phải không?}
{301}{}{Đúng vậy, nó đây.}
{302}{}{Không, tôi chỉ thử ông thôi.}
{303}{}{(Ông ta lấy bộ phận khỏi tay bạn) Mãi cũng có! Giờ thì ta có thể sửa cái máy in này. Cám ơn nhé, hãy cầm quyển sách sinh tồn này thay lời cám ơn.}
{304}{}{Cám ơn.}
{305}{}{Này, tôi không có thời gian để đùa. Cô có bộ phận hay không nào?}
{306}{}{Có, tôi có cầm đây.}
{307}{}{Chậc, tôi đi đây.}
{400}{}{Đây là xưởng in của tu viện. Chúng tôi in sách tại đây.}
{401}{}{Ok, cám ơn vì thông tin.}
{500}{}{Bạn nhận được 100 điểm kinh nghiệm vì đã gửi bộ phận.}
{600}{}{Ngộ là trợ thủ LỚN hôm nay. Ngộ có bộ mạy từ bà tên đẹp.}
{610}{}{Chắc là bộ phận máy mà tôi yêu cầu Elaine. Cám ơn đã cầm nó xuống. Đây, cầm lấy quyển sách hướng dẫn
sinh tồn này thay lời cảm ơn... nếu mà cô biết đọc.}
{611}{}{Ngộ đọc mười chữ. Ngộ thích sách ạnh hơn. Nhìn thú hơn. Tắc kè!}
