{100}{}{Bạn thấy một thương gia.}
{102}{}{Bạn thấy một thương gia đang cố gắng sửa máy bơm nước.}
{103}{}{Mẹ nó mãi đéo chạy!}
{104}{}{Thứ này có vẻ rất khó sửa.}
{105}{}{Đúng là cục cứt đồng nát!}
{106}{}{Của nợ này cứng đầu vl nhỉ?}
{107}{}{Cô giúp tôi một tay được không?}
{108}{}{Có thể cô sẽ hợp với thứ này hơn.}
{109}{}{Này, cám ơn đã sửa máy bơm nước!}
{110}{}{Cô nên báo với thầy tu trưởng là máy bơm nước đã sửa được rồi.}
{200}{}{Cám ơn đã giúp chúng tôi sửa thứ này.}
{300}{}{À, đúng là cục cư- ờ, tôi đang dở tay. Cô có cần gì không hay chỉ muốn tán gẫu thôi?}
{301}{}{Thực ra là có. Thầy trụ trì cử tôi đến. Ông ta nói máy bơm nước có vấn đề.}
{302}{}{Hế, "có vấn đề" cái củ cải. Cục sắt vụn này nát như tương rồi. Đếch có chuyện nó tiếp tục
chạy nữa đâu.}
{303}{}{Hiểu rồi. Vậy chắc không vấn đề gì nếu tôi ngó thử nhỉ.}
{304}{}{Được chứ, cứ tự nhiên. Đằng nào cũng có hỏng hơn được nữa đâu.}
{305}{}{Tôi không muốn làm phiền, nhưng có chuyện gì ở đây thế?}
{306}{}{Cái máy bơm nước chính cho Tu viện tạch rồi. Thứ chết tiệt này són được vài giọt cuối cùng mấy ngày
trước và đến giờ thì chính thức đi đời rồi.}
{307}{}{Tôi biết một chút về kĩ thuật, có phiền không nếu tôi ngó qua chút?}
{308}{}{Ồ, tôi không giỏi máy móc lắm, nhưng có lẽ tôi có thể xem liệu có làm gì được không.}
{309}{}{Được, chẳng ai cấm cả.}
{310}{}{Ờ, xin lỗi. Tạm biệt.}
{311}{}{Để tôi xem tôi có thể làm gì.}
{312}{}{Tôi nghĩ là mình có thể giúp, nhưng nếu ông cứ chửi bới như vậy thì tự đi mà sửa lấy nhé.}
{313}{}{Tôi có nói với Thầy trụ trì là tôi sẵn sàng giúp, nhưng nếu ông cứ chửi bới như vậy thì tự đi mà sửa lấy nhé.}
{320}{}{[Ông ta nheo mắt nhìn bạn một thoáng, rồi chầm chậm thở dài một hơi]. Xin lỗi cô bạn, thứ này mãi không
chạy và nó làm tôi phát điên lên được. Tôi không có ý chửi ai cả.}
{321}{}{Ồ, vậy vấn đề là gì thế?}
{322}{}{Sao cũng được, tạm biệt.}
{330}{}{Hãy quay lại nói chuyện với tôi vào buổi sáng.}
{400}{}{Ồ, lại là cô. Có tìm thấy gì không?}
{401}{}{Không, chưa thấy gì. Tìm thấy gì thì tôi sẽ báo.}
{402}{}{Thực ra là có. Tôi đã xem bên trong và có vẻ như động cơ chết hẳn rồi. Dây nối cũng cháy rồi, nên chúng ta sẽ
cần tìm một bộ động cơ mới và vài đoạn dây để nối mọi thứ lại.}
{500}{}{Hừm... đầu nối trên động cơ chính cháy rồi à? Ờ, tôi có sẵn dây ở đây rồi, nhưng động cơ cho cái máy này thì không.
Tôi chắc là Thành phố Vault có đấy. Hãy đi đến đó và nói với Harry ở sân chính. Bảo hắn ta là Dave cử cô đến.
Cục động cơ đắt đấy, nhưng chắc hắn ta sẽ giảm giá cho cô.}
{501}{}{Tôi sẽ đến đó ngay. Gặp lại sau.}
{502}{}{Chà, gượm chút đã. Tôi rất vui vì đã giúp ông tìm ra vấn đề, nhưng ai nói là tôi sẵn sàng vượt qua hoang mạc
để mua cho ông cục động cơ đắt tiền vậy? Nếu muốn tôi giúp thì xì tiền ra đây.}
{503}{}{Sao *ông* không tự vác xác đến mà nói với Harry ấy? Tôi đâu phải tay sai vặt của ông. Chào nhé.}
{510}{}{Được rồi, tôi cũng không nghĩ là có người làm miễn phí đâu. Bộ phận này có giá khoảng 500 và tôi nghĩ trả công
cho cô 100 là hợp lí. 600 đây.}
{511}{}{Tốt hơn rồi đấy. Tôi sẽ mang bộ phận quay lại.}
{600}{}{Có tìm thấy bộ phận chưa vậy? Cái máy này không tự sửa đâu.}
{601}{}{Chưa. Tôi sẽ quay lại khi nào có.}
{602}{}{Có, bộ phận ngay đây rồi.}
{700}{}{Tuyệt. Muốn tôi lắp của nợ đấy vào không, hay cô muốn tự chơi hơn?}
{701}{}{Tôi nghĩ mình làm được. Tránh ra nào.}
{702}{}{Thực ra tôi nghĩ là mình làm thế là đủ rồi. Ông tự đi mà lắp lấy đi.}
{800}{}{Được rồi, đưa bộ phận đây.}
{801}{}{Đây.}
{900}{}{Vậy là xong.}
{901}{}{Máy bơm nước đã được sửa chữa.}
{910}{}{(Lau mồ hôi trán). Ờ, cần gì không?}
{911}{}{Thầy trụ trì nói ông có thể cần trợ giúp. Có vấn đề gì vậy?}
{912}{}{Không có gì. Xin chào.}
{913}{}{Tôi đã xem máy bơm nước và có vẻ như động cơ chết hẳn rồi. Dây nối cũng cháy rồi, nên chúng ta sẽ
cần tìm một bộ động cơ mới và vài đoạn dây để nối mọi thứ lại.}
