{100}{}{Bạn thấy một chàng trai trẻ khỏe.}
{101}{}{Bạn thấy Ông Peterson.}
{200}{}{Xin chào cô bạn. Tôi nhớ là chưa thấy cô ở đây bao giờ. Lần đầu đến với Tu viện à?}
{201}{}{Rất vui được gặp lại. Tôi có thể giúp gì nhỉ?}
{202}{}{Ừ. Anh có thể giới thiệu về nơi này được không?}
{203}{}{Tôi đang trên hành trình đi tìm GECK thần thánh. Anh có biết gì về thứ này không?}
{204}{}{Thầy Samuel nói anh có thể biết gì đó về kẻ đang đào trộm mộ. Ông ta nói anh có nghe thấy vài tiếng động
trong khu vườn của mình.}
{205}{}{Không có gì, tôi phải đi đây.}
{300}{}{Mấy năm trước tôi và vợ đi cùng một đoàn lữ hành đến đây. Chúng tôi thích nơi này đến nỗi quyết định ở lại và mở
khu vườn nhỏ của mình. Nghe này, Tu viện có thể không lấp lánh như New Reno hay hiện đại như Thành phố Vault,
nhưng theo như tôi biết thì nơi này là tốt nhất ở hoang mạc rồi. Người dân ở đây lành lắm, mọi người quan tâm lẫn
nhau. Đúng là một vài chỗ khác có thể an toàn hơn, nhưng đổi lại thì không có tự do cá nhân. Tôi không muốn thế.}
{301}{}{Anh đi theo đoàn lữ hành à? Họ có hay đến đây không?}
{302}{}{Không hẳn. Tu viện quá bé và biệt lập nên các đoàn lữ hành không hay đến lắm. Nhưng không sao, chúng tôi gần như
là một cộng đồng tự cung tự cấp -- tự trồng cây, tự nấu rượu -- nên mọi thứ đều ổn. Mà nếu muốn tìm đoàn lữ hành thì hãy
nói chuyện với Bill, ông ta mở quán tạp hóa ở phía Tây Nam khu này.}
{303}{}{Nghe hấp dẫn thật đấy, nhưng tôi thực sự phải đi đây.}
{304}{}{Hay đấy. Tôi đang thắc mắc về thứ khác.}
{305}{}{Không có gì, tôi phải đi đây.}
{400}{}{Cô còn muốn biết gì nữa?}
{401}{}{Bà có thể kể gì cho tôi về Tu viện?}
{402}{}{Anh có biết gì về Bộ tạo Vườn địa đàng không?}
{500}{}{Tôi chưa từng nghe đến thứ này. Nhưng nếu đấy là đồ từ thời trước chiến tranh thì tôi chắc là sẽ có gì đó trong
máy tính của tu viện đấy. Đáng tiếc cho cô là các thầy tu ở giấu kiến thức như giấu vàng ý -- họ sợ chúng sẽ dẫn
đến một cuộc chiến tranh hoặc gì đó nếu mọi người biết nhiều quá. Nhưng cứ thử hỏi quanh đây xem.}
{501}{}{Cám ơn, tôi sẽ thử. Tôi vẫn còn mấy câu hỏi nữa.}
{502}{}{Cám ơn về lời khuyên. Tôi sẽ đi vào thử giờ đây.}
{600}{}{Thầy Samuel cử cô đến đây? Lão bợm rượu đấy lại muốn gì nữa đây?}
{601}{}{Chăm sóc khu mộ như mọi khi, chắc vậy. Còn về những tiếng động mà anh nghe thấy...}
{602}{}{[John ngồi xuống ghế và tự rót cho mình một ly whiskey]. Mọi thứ bắt đầu vài ngày trước. Tôi và vợ đang xếp
giường thì nghe thấy có tiếng sột soạt ngoài vườn. Tôi vớ lấy đèn và lao ra ngoài để xem ai đang gây ra tiếng động.
Ngay khi tôi ra đến vườn thì tiếng động dừng lại.}
{603}{}{Tiếp tục đi.}
{604}{}{Này, tôi thật sự phải đi đây.}
{605}{}{Ờ, đến đêm hôm sau thì chúng tôi chẳng nghe thấy gì cả. Nhưng đêm sau đó thì chúng tôi lại nghe tiếng sột soạt
trên đồng lần nữa. Lần này tôi lẻn đến bên cửa sổ và ngó ra thay vì lao ra như trước. Trong đêm tối, tôi nhìn thấy một
đốm sáng lập lòe như thể là cái đèn cầy hay thứ gì đó, di chuyển trên đồng. Sau một vài phút, đốm sáng đi về phía
khu nghĩa trang.}
{606}{}{Tôi muốn đi ra và đối diện với người -- hoặc thứ gì đó, nhưng vợ tôi khuyên tôi ở trong nhà, khi nào trời sáng thì ra.
Vậy là đến sáng hôm sau, tôi thấy một vài cây trồng đã bị gặm và có vết chân mới đi ở khắp nơi. Ầy, tôi có thể bố thí
cho người nghèo, nhưng còn lũ trộm cắp thì lại khác.}
{607}{}{Tôi sẽ thử túm cổ gã này. Có thể tôi sẽ chờ đến nữa đêm xem có thể tìm thấy gì không. Ừ, cám ơn về
thông tin này nhé. Bảo trọng.}
{608}{}{Tôi sẽ xem tôi có thể làm gì. Tôi có thêm vài câu hỏi trước khi đi.}
{609}{}{Câu chuyện này càng lúc càng dài rồi đấy. Tạm biệt.}
{610}{}{Để tôi vào thẳng vấn đề nhé. Anh muốn giúp kẻ đã lang thang quanh nhà anh vào buổi tối, ăn trộm
lương thực và cố lấy đồ của người chết? Tôi đã gặp nhiều kẻ điên trước đây, nhưng anh hẳn là số một luôn. Anh vẫn
còn sống đến giờ đúng là một phép màu đấy.}
{611}{}{[Anh ta nheo mắt lại, nhưng vẫn giữ được bình tĩnh]. Ở Tu viện này chúng tôi sống như vậy. Nếu lòng tốt khiến cô
thấy khó chịu thì tôi khuyên cô nên biến khỏi nhà tôi ngay. Tôi sẽ không ngồi đây để nghe một mụ tộc nhân xỉ vả trước
mặt vợ mình đâu.}
{612}{}{Rồi, rồi, tôi đi.}
{613}{}{OK thôi anh giai cứng, giờ thì "tộc nhân lang thang" này sẽ giết anh giai ngay trước mặt vợ. Có thể sau đó tôi sẽ
giết cả cô ta luôn. Mẹ kiếp, chắc là tôi sẽ giết toàn bộ lũ người ở chỗ củ lìn này. Các người nghĩ rằng mình có thể trốn 
tránh khỏi nỗi khiếp sợ của hoang mạc? Biết gì không, anh giai đần? Thần chết đã đến, với cái tên là }
{700}{}{Cút khỏi đây ngay.}
{710}{}{Rất vui được gặp lại. Tom đã giúp đỡ chúng tôi nhiều lắm. Cám ơn lần nữa vì đã giải quyết mọi thứ. Giờ thì tôi có thể giúp gì nhỉ?}
{6061}{}{Sau đó tôi có hỏi Thầy Samuel xem có chuyện gì xảy ra trong nghĩa trang không. Ông ta nói rằng có kẻ nào đó đã
lật tung mấy ngôi mộ lên. Có vẻ như kẻ đó không có đủ sức để đào trong một đêm. Tôi chắc là một ông lão ăn xin
nào đấy mong tìm được của thôi. Nếu cậu tìm thấy người làm chuyện đó thì hãy bảo họ đến đây. Ở Tu viện này
không ai cần phải đi ăn cắp cả, tôi sẽ sẵn lòng giúp đỡ người này bằng mọi cách có thể.}
