{100}{}{Bạn thấy một nông dân.}
{101}{}{Bạn thấy một nông dân khỏe mạnh.}
{102}{}{Bạn thấy một người.}
{103}{}{Bú nhiều rượu quá à?}
{104}{}{Tạm cai rượu một thời gian đi.}
{105}{}{Tôi thấy cô đã uống loại "đặc biệt" của Hank.}
{106}{}{Chào mừng, người hùng!}
{107}{}{Anh đã cho lũ khốn Enclave biết mặt!}
{108}{}{Anh đúng là một người hùng thực sự!}
{109}{}{Tôi nghe nói anh đã phá hủy Enclave, làm tốt lắm!}
{110}{}{Chào.}
{111}{}{Tôi hi vọng là trời sẽ sớm mưa, nếu không thì cây trồng của tôi sẽ chết hết.}
{112}{}{Chúng tôi không có nhiều khách đến đây.}
{113}{}{Xin chào!}
{114}{}{Ừ tôi biết. Ở đây buồn tẻ lắm, nhưng ít nhất chúng tôi cũng không bị cướp hay gì cả...}
{115}{}{Chào, tộc nhân.}
{116}{}{Hôm nay nóng thật đấy!}
{117}{}{Đất ruộng ở đây tốt lắm...}
{118}{}{Chúc một ngày tốt lành.}
{119}{}{Chào mừng đến với Tu viện, người lữ khách!}
{120}{}{Tu viện ở đây ấn tượng đấy chứ hả?}
{200}{}{Bỏ cái tay của ngươi khỏi người ta ngay!}
