{100}{}{Bạn thấy người gác nghĩa trang của tu viện.}
{101}{}{Bạn thấy Thầy Samuel, người gác nghĩa trang.}
{102}{}{Ông ta trông có vẻ say rượu và hơi buồn ngủ.}
{200}{}{*nấc* Ầy, khỏe chứ, Samuel đây. Cái, ờ *nấc* cô đến đây làm gì thế?}
{201}{}{*nấc* Chào.}
{202}{}{Chỉ ngó quanh thôi. Ông trông coi khu nghĩa trang này à?}
{203}{}{Ông có biết Cha Tully không?}
{204}{}{Cha Tully à? [Ông ta có vẻ như đang nhíu hết cả não để nhớ lại]. Ừ... ta *nấc* có nhớ Tully. Mà gã đấy sao rồi? Ta
chưa gặp lại hắn từ lúc hắn ta bị đá đít khỏi chỗ này từ hồi xưa *nấc* xưa lắm rồi. [Ông ta cười toe toét trong
say xỉn khi nhớ lại] Chà, hắn ta nói dối như cuội nhá. Hắn và ta cùng nhau, *nấc* một cặp bài trùng.}
{205}{}{Ông ta giờ sống ở New Reno, rao giảng kinh thánh, ờ, đại loại thế. Biết gì không, hai ông giống hệt nhau.}
{206}{}{New Reno à? [Ông ta dựa vào cái xẻng, lôi ra một bịch nhỏ rồi tợp một ngụm thật sâu]. Ta nhớ là hắn ta có nói
*nấc* sẽ đi lối đấy. Mừng là hắn ta đã đến nơi an toàn. Ta luôn *nấc* thích gã này. Một tay lừa thứ thiệt. Nếu gặp lại
thì bảo gã là Sammy già vẫn đang sống nhăn răng nhé.}
{207}{}{Tôi sẽ làm vậy. Mà tôi vẫn còn mấy câu hỏi nữa.}
{208}{}{Tôi sẽ làm vậy. Bảo trọng nhé Sam.}
{209}{}{Không có gì. Xin lỗi đã làm phiền.}
{210}{}{Thật ra là tôi đang định nói là ông ta gửi lời chào. Tôi sẽ nói với ông ta là ông cũng gừi lời chào. Mà tôi vẫn còn mấy câu cần hỏi.}
{211}{}{Thật ra là tôi đang định nói là ông ta gửi lời chào. Tôi sẽ nói với ông ta là ông cũng gửi lời chào. Bảo trọng nhé Sam.}
{300}{}{Cô *nấc* muốn biết gì nào?}
{301}{}{Ông là người gác nghĩa trang à?}
{302}{}{Bà có thể kể gì cho tôi về Tu viện?}
{303}{}{Tôi có thể giúp gì được ông không?}
{400}{}{Ừ, *nấc* ta chăm sóc khu nghĩa trang này. Không ai muốn *nấc* làm việc này, vậy nên Sammy già có việc làm.
Cũng không tệ như họ nghĩ. Có nhiều... điểm tốt, cô biết đấy. [Ông ta toét miệng cười sặc và nheo nheo
cặp mày rậm].}
{401}{}{Không, tôi không biết và cũng không muốn biết. Tạm biệt.}
{402}{}{Không. Tôi không biết. Nhưng tôi muốn hỏi ông về chuyện khác.}
{403}{}{Không. Tôi không biết, nhưng tôi tò mò đến chết đi được...}
{404}{}{Đậu má tôi biết chứ. Không gì kích thích hơn cảnh một cái xác thối rữa cả.}
{410}{}{Sao chứ, ta được ra ngoài và chẳng ma nào đến đây để bảo Sammy già dừng lại cả. Ta *biết* khi nào ta say chứ...
khi cạn không còn giọt nào! [Ông ta cười lớn, nhưng nhanh chóng gặp phải cơn ho sặc sụa. Sau khi ho đến
vỡ tung cả phổi, ông ta mỉm cười với bạn].}
{411}{}{Ờ, dĩ *nhiên* ý ông là thế. [Thở dài nhẹ nhõm]. Để tôi hỏi ông chuyện khác.}
{420}{}{[Ông ta tròn mắt vì sốc và dường như tỉnh táo trở lại]. Ý ta không phải vậy, đồ... đồ QUÁI VẬT! QUỶ ĐÓI!
Tránh xa ta ra!}
{421}{}{Sao cũng được, lão già say xỉn. Lão không biết mình đang bỏ lỡ điều gì đâu.}
{430}{}{Ác quỷ xấu xa! Biến đi!}
{500}{}{Tu viện, ờ, đây là nơi *nấc* ta đã sống cả đời ở đây. Mọi người ở đây *nấc* rất tốt, và ai cũng được đón chào,
miễn là họ *nấc* không gây rắc rối. Bản thân ta tuy không ở lâu trong tu *nấc* viện, nhưng ta biết trong
máy tính có rất nhiều thứ họ đã sưu tập trong nhiều năm. Có thể cậu sẽ tìm thấy thứ gì đó *nấc* có ích
trong đó.}
{501}{}{Ông không ở lâu trong nhà thờ ư? Chẳng phải ông là thầy tu sao?}
{502}{}{[Ông ta phá ra cười, để lộ ra hàm răng sâu nham nhở]. Ờ thì *nấc* chắc là các thầy tu khác không
thích lắm *nấc* cái thói uống rượu của ta.}
{503}{}{Chắc là vậy. Tôi có thêm câu hỏi.}
{504}{}{Chắc vậy. Gặp lại ông sau Sammy.}
{505}{}{Hiểu rồi. Tôi phải đi đây.}
{600}{}{Hừm... *nấc* để ta... để ta nghĩ một chút. Ừ, ta có việc này, nếu cô muốn giúp.}
{601}{}{Ừ, không có gì đâu Sam. Giờ tôi phải đi đây.}
{602}{}{Được chứ Sam, ông cần gì nào?}
{603}{}{Ờ, mấy ngày gần đây ta *nấc* để ý thấy có mấy ngôi mộ bị đào lên. Tuy là kẻ nào làm việc đó có vẻ như chưa
đến mức quá đà, nhưng mà *nấc* mất công ta đi lấp chúng lại.}
{604}{}{Hừm, ông có thử tìm xem là ai đang làm việc đó chưa?}
{605}{}{Chắc chắn *nấc* là có chứ. Có đêm ta thức đến canh hai hay tầm đó, nhưng chẳng thấy ai xuất hiện cả. Sau đó ta
ngủ gục mất. Chắc là hơi quá chén. [Ông ta cười khà, lôi bịch rượu ra tu một ngụm lớn]. Giờ cậu nghĩ *nấc* sao?
Có muốn giúp không?}
{606}{}{Được rồi, để tôi xem tôi có thể làm gì. Ông có biết điều gì khác có ích không?}
{607}{}{Ờ, nhắc mới nhớ, ta nhớ *nấc* là Ông Peterson có nói về việc nghe thấy tiếng động gì đó từ khu ruộng. Cậu ta
có thể biết gì đó về chuyện này. Cậu ta cùng cô vợ bé nhỏ xinh đẹp sống ở ngay kia. [Ông ta chỉ tay về phía
tòa nhà phía Nam của nghĩa trang].}
{608}{}{Để tôi xem tôi có thể làm gì.}
{609}{}{Chắc là thôi. Tôi phải đi đây.}
{700}{}{Tôi đã lo xong vụ đào trộm mộ rồi. Chắc là ông không còn có vấn đề gì nữa đâu.}
{701}{}{Ồ, thật là *nấc* tin đáng để tu một hơi dài. Mừng là ta sẽ không còn ngã vào ngôi mộ *nấc* hở nào nữa. Cám ơn đã giúp.}
{702}{}{Rất vui khi giúp được ông. Tôi vẫn còn vài câu hỏi nữa.}
{703}{}{Được rồi, bảo trọng nhé.}
{704}{}{Tôi không nghĩ mấy ngôi mộ hở là lí do chính khiến ông ngã đâu Samuel, nhưng từ giờ ông có thể thư giãn rồi.}
{1000}{}{*Huýt sáo*}
{1001}{}{*Ho khục khặc*}
{1002}{}{*Hắng giọng*}
{1003}{}{*Ho*}
{1004}{}{*Thở dài*}
{1005}{}{*Nấc*}
{2000}{}{Đúng là một *nấc* ngày dài. Sáng mai quay lại nhé.}
