{100}{}{Bạn thấy một ông lão lưng còng.}
{101}{}{Ông lão già nua đầy mùi mồ hôi và có thể là cả nước tiểu. Ông ta mặc đồ rách rưới, lấm lem bùn đất và đang cầm xẻng.}
{102}{}{Bạn thấy Tom.}
{200}{}{[Ông lão giật bắn mình khi thấy bạn lại gần]. Ờ, này, tôi phải đi đây...}
{201}{}{Hượm đã. [Bạn túm lấy cánh tay của ông ta khi ông ta bắt đầu bước đi]. Ông là ai, ông đang làm gì ở đây vào
giờ này?}
{202}{}{Cái gì? Tại sao, ờ... tôi là Tom. Chẳng lẽ một người già cả không được đi dạo đêm mà không bị tra tấn bằng một đống
câu hỏi nữa à?}
{203}{}{Không hề khi ông đang lén lút như kẻ trộm, lại còn vác xẻng nữa.}
{204}{}{Được rồi, nhưng sao ông lại cầm cả xẻng theo?}
{205}{}{Sao cũng được, tôi đi đây.}
{206}{}{Không có gì. Xin lỗi đã làm phiền.}
{207}{}{Ý cô là thứ cũ kĩ này? [Ông ta liếc nhìn cái xẻng rỉ sét trên tay]. Ừ thì, ai mà biết được lúc nào có thể tìm thấy
thứ gì đó cần được đào lên. Chuẩn bị thôi mà.}
{208}{}{Tìm thấy gì đó hả? Ý ông là một ngôi mộ?}
{209}{}{Sống có chuẩn bị như vậy là tốt. Ồ, bảo trọng nhé.}
{210}{}{[Tom tròn mắt] Tôi không chắc là, ờ, ý cô là gì.}
{211}{}{Tôm, ông đang ở trong nghĩa trang, người ông lấm đầy bùn đất và đã quá nửa đêm rồi. Sao hả, ngay cả gã Torr
cũng nghĩ ra. Đã đến lúc trả lời tôi rồi, Tom. Tại sao ông lại đào những ngôi mộ này lên?}
{212}{}{[Ông ta đặt xẻng xuống và thở dài]. Được rồi, tôi sẽ nói. Thân thể tôi không còn được như xưa nữa. Tôi không
có việc làm và chẳng biết kiếm ăn bằng cách nào. Tôi biết đào trộm mộ không phải là điều tốt, nhưng đây là cách để tôi
kiếm một chút tiền. Tôi chỉ cố sống thôi... tôi không định phá hoại gì cả.}
{213}{}{Tôi không nghĩ rằng đi đào trộm mộ là việc mà người như ông nên làm. Biết gì không? Cứ tiếp tục ra khỏi đây
và chúng ta sẽ coi như chưa từng gặp nhau. Tôi không muốn thấy ông còn luẩn quẩn ở đây nữa, được chứ?}
{214}{}{[Ông lão trông có vẻ như muốn phản đối, rồi dừng lại]. Đươc rồi, cô là nhất. Cô đã đẩy Tom già nua xuống tận
đáy rồi. [Ông ta nhặt xẻng lên rồi lê bước đi].}
{215}{}{Mà nghĩ lại thì chắc thế giới sẽ tốt đẹp hơn nếu tôi giết ông.}
{216}{}{Vĩnh biệt Tom.}
{217}{}{Tôi nghe nói ông còn ăn trộm cây trồng của nông dân ở quanh đây.}
{218}{}{[Ông lão run rẩy]. Tôi biết làm thế nào được! Tôi đói mờ cả mắt còn mấy cái cây thì trông ngon quá. Làm ơn đi,
tôi không định gây hại gì. Nghe này, tôi sẽ biến khỏi đây và cô sẽ không còn nhìn thấy tôi nữa. Tôi hứa đấy!}
{219}{}{Được rồi, hãy đi đi. Trước khi tôi đổi ý.}
{220}{}{Chờ đã, không cần phải vậy. Nhà Peterson, chủ của khu ruộng này là những người rất tốt bụng. Ông Peterson
thậm chí còn sẵn sàng nói chuyện với người đã ăn trộm cây trồng để đưa ra thỏa thuận hợp tình nữa. Hãy đến
nói chuyện với anh ta. Tôi chắc là anh ta có thể giúp ông bằng cách nào đó.}
{221}{}{[Ông lão sáng mắt lên]. Điều đó nghe không tệ chút nào. Này, cám ơn nhé. Có lẽ thế giới này không tệ hại như
tôi đã từng nghĩ.}
{222}{}{Bảo trọng nhé, Tom. Tôi sẽ quay lại sau để xem mọi chuyện thế nào.}
{223}{}{Tôi rất hi vọng là thanh niên Peterson này thân thiện như lời cô nói.}
{300}{}{Bạn thấy Tom. Ông ta mặc đồ lao động mới và đang vui vẻ huýt sáo.}
{301}{}{Ô kìa! Ồ, cậu đã đúng. Ông Peterson đúng là một thanh niên tốt bụng. Cậu ta đã tha thứ cho tôi và thậm chí
còn nhận tôi vào cày ruộng nữa. Cậu ta nói sau khi tôi trả hết số lương thực mà tôi đã lấy, tôi sẽ bắt đầu được
nhận lương tuần. Cám ơn đã giúp đỡ.}
{302}{}{Không có gì, Tom. Giờ thì ông hãy bảo trọng nhé.}
{303}{}{Được rồi tôi ước- Ồ, chờ một chút. Tôi muốn tặng cô thứ gì đó vì đã giúp đỡ ông già này. Tôi tìm thấy cái
bật lửa này trong mộ một cô gái mà tôi đã đào lên mấy tuần trước. Hi vọng là nó sẽ có ích cho cô.}
{304}{}{Cám ơn, Tom. Tôi chắc là thứ này sẽ có ích. Gặp lại ông sau.}
{305}{}{(Ông lão gật đầu và tiếp tục công việc).}
{306}{}{[KẾT THÚC]}
{307}{}{Xin chào. Cám ơn vì mọi thứ!}
{308}{}{*Huýt sáo*}
{400}{}{Lũ thanh niên không biết điều. Mày đâu phải bố tao. Tao sẽ giết mày.}
{450}{}{Nghe này, tôi cũng đi đào mộ rồi. Tôi hơi mắc chứng cuồng ăn trộm. Lí do của ông là gì?}
{451}{}{Tom, tôi không lạ lắm với việc đào mộ. Ai cũng cần thú vui cho riêng mình. Giờ thì ông cứ đi đi.}
{1000}{}{Bạn tìm ra người đã đào mộ và giúp Tom có một cuộc sống mới.}
{1001}{}{Bạn tìm ra người đã đào mộ.}
{1002}{}{Tôi đi đây. Đâu cần phải giục người già cả chứ.}
{1003}{}{Bạn thấy Tom. Ông lão tươi cười trong bộ quần áo lao động mới.}
{1004}{}{Ông ta trông có vẻ tốt hơn nhiều và mỉm cười khi bạn lại gần.}
