{100}{}{Bạn thấy Jordan, đang múa ngọn giáo như mọi khi.}
{101}{}{Bạn thấy Jordan, đang múa ngọn giáo như mọi khi.}
{102}{}{Chúc may mắn! Ngôi làng trông chờ vào cô.}
{103}{}{Cứu tinh, nhìn cách cô múa giáo thế thì chả mấy mà cô làm mồi
cho gecko. Tôi có thể chỉ cô vài đường.}
{104}{}{Được thôi.}
{105}{}{Không, cám ơn.}
{106}{}{Sẽ mất một thời gian đấy.}
{107}{}{Cô học nhanh đấy -- có vẻ như cô đã học hết những gì tôi
có thể dạy rồi.}
{108}{}{Cám ơn Jordan. Anh đã giúp tôi rất nhiều đấy.}
