{100}{}{B?n th?y Jordan, đang múa ng?n giáo như m?i khi.}
{101}{}{B?n th?y Jordan, đang múa ng?n giáo như m?i khi.}
{102}{}{Chúc may m?n! Ngôi làng trông ch? vào cô.}
{103}{}{C?u tinh, nh?n cách cô múa giáo th? th? ch? m?y mà cô làm m?i
cho gecko. Tôi có th? ch? cô vài đư?ng.}
{104}{}{Đư?c thôi.}
{105}{}{Không, cám ơn.}
{106}{}{S? m?t m?t th?i gian đ?y.}
{107}{}{Cô h?c nhanh đ?y -- có v? như cô đ? h?c h?t nh?ng g? tôi
có th? d?y r?i.}
{108}{}{Cám ơn Jordan. Anh đ? giúp tôi r?t nhi?u đ?y.}
