{100}{}{Bạn thấy người gác cầu.}
{101}{}{Bạn thấy Mynoc, người gác cầu.}
{150}{}{Đứng trước bạn là một chiến binh cao to của làng,
nắm trong tay một ngọn giáo.}
{151}{}{[NÓI CHUYỆN]}
{152}{}{Chào, Cứu tinh. Đi tìm GECK hả?}
{153}{}{Đúng vậy.}
{154}{}{Đúng vậy. Nhưng trước khi đi, tôi muốn hỏi vài câu.}
{155}{}{Chưa. Tôi đang đi vòng quanh xem xét thêm
một lát đã.}
{156}{}{Ồ, cầu các thần phù hộ cho cô.}
{157}{}{Cám ơn, tạm biệt.}
{158}{}{Muốn biết gì nào?}
{159}{}{Anh có thể nói cho tôi biết về người trao đổi hàng hóa
với làng chúng ta không?}
{160}{}{Anh có biết gì về thứ này mà tôi lấy được từ hầm
không?}
{161}{}{Không, không có gì.}
{162}{}{Được rồi, nhưng đừng có mất nhiều thời gian quá. Không có
GECK, chúng ta tiêu tùng đấy.}
{163}{}{Tôi biết, đừng lo -- Mọi chuyện đều trong tầm kiểm soát.}
{164}{}{Tại sao?}
{165}{}{Tôi phải đi đây. Tạm biệt.}
{166}{}{Đám thương gia ấy hả? Họ đến từ Klamath khoảng 2 tháng một lần. Lần
tiếp theo còn hơn một tháng nữa cơ, nhưng đi đến Klamath thì chỉ mất vài
ngày về phía Đông.}
{167}{}{Cám ơn. Tạm biệt.}
{168}{}{Anh có biết gì về thứ này mà tôi lấy được từ hầm
thần không?}
{169}{}{Trông giống một bầu đựng nước bằng kim loại. Có thể
hầm gửi nó đến đây như một điềm báo.}
{170}{}{Anh có thể cho tôi biết ai đã mang thứ này đến làng chúng ta không?}
{171}{}{Cám ơn. Tôi phải đi đây. Tạm biệt.}
{172}{}{Hi vọng là vậy.}
{173}{}{Cô mà tự tin quá sẽ khiến tất cả chúng ta phải trả giá đấy! Tạm biệt!}
{174}{}{Tạm biệt.}
{175}{}{Tại sao à? Nhìn quanh xem -- Ngôi làng đang chết. Vườn tược héo úa,
ngày nào cũng có trẻ con và người già nằm xuống. Cô phải mang Địa đàng về
trước khi quá muộn!}
{176}{}{Rồi tôi sẽ lo chuyện đó. Tạm biệt.}
{177}{}{Tôi là Cứu tinh -- Tôi "phải" làm theo ý tôi.
Tạm biệt.}
{178}{}{Tôi không nhớ tên, nhưng lão ta già với to mồm lắm -- nói to chả
giữ ý gì cả -- nhưng lão ta biết nhiều lắm. Lão đến từ Klamath, về phía Đông
như tôi vừa nói.}
{179}{}{Cám ơn, tạm biệt.}
{180}{}{Sao cậu vẫn còn ở đây? Cậu phải đi tìm GECK. Cậu ở đây
chẳng có ích gì đâu.}
{181}{}{Anh chỉ cần lo gác cầu thôi, anh bạn ạ. Tôi
có thể tự lo thân được.}
{182}{}{Tôi chuẩn bị đi đây. Tạm biệt, anh bạn.}
{183}{}{Tôi không nói chuyện với anh nữa đâu, đồ lợn khó bảo!}
{184}{}{Tôi muốn hỏi thêm câu nữa.}
{185}{}{Nhanh thật đấy! Cô đã tìm thấy Vault 13 thần thánh chưa?}
{186}{}{Đúng vậy.}
{187}{}{Chưa.}
{188}{}{Thấy rồi? Tuyệt quá! Cô có mang GECK về
không?}
{189}{}{Không.}
{190}{}{Chưa. Tôi vẫn chưa nói chuyện với đám người trong hầm.}
{191}{}{Tôi thấy rằng đấy không phải là việc của anh, bạn tôi ạ.}
{192}{}{Chưa ư? Cứu tinh, ba người già đã chết kể từ lúc cô rời đi. Cô không
được lãng phí thêm thời gian nữa.}
{193}{}{Tôi sẽ tìm thấy, đừng lo.}
{194}{}{Tôi thấy mệt mỏi với mấy lời càu nhàu của anh lắm rồi.}
{195}{}{Ồ, thế thì sao cô lại đi nói chuyện với tôi? Đến nói chuyện với họ và lấy GECK đi.}
{196}{}{Tôi sẽ làm mà -- thịt chó sẽ có mắm tôm, bạn tôi ơi.}
{197}{}{Tôi thấy mệt mỏi với mấy lời càu nhàu của anh lắm rồi.}
{198}{}{Có tin gì về GECK chưa, Cứu tinh?}
{199}{}{Tôi đã tìm thấy căn hầm!}
{200}{}{Tôi chưa tìm thấy Vault 13.}
{201}{}{Ồ, nhìn này, Cứu tinh về rồi.}
{202}{}{Chào.}
{203}{}{Câm mồm đi.}
{204}{}{Tôi hỏi một câu được không?}
{205}{}{Không, tôi không có rảnh.}
{206}{}{Sao cũng được. Tạm biệt.}
{207}{}{Ồ được rồi. Gặp lại sau.}
{208}{}{Đi chết đi.}
{209}{}{Chào cô ngốc! Thấy cầu chứ? Qua cầu, cẩn thận đấy.
Cầu đáng sợ lắm. Mày không muốn ngã chứ. Okay?}
{210}{}{Ờ... Hớ?}
{211}{}{Khốn nạn! Mày đã khiến cả làng thất vọng!}
{212}{}{Mày đã phản bội chúng ta. Giờ thì chết đi!}
{213}{}{Mày đã phản bội chính những người đồng tộc.}
{214}{}{Tại sao mày lại làm thế?}
{215}{}{Trưởng lão đã nhầm. Mày đúng là ác quỷ.}
{300}{}{Cha tôi dạy tôi cách tạo ra lưỡi dao sắc hơn. Kiếm cho tôi một cục đá mài và
tôi sẽ sửa giáo cho cô. Nó sẽ có ích cho cô ngoài hoang địa đấy.}
{301}{}{Tôi có thể kiếm đá mài ở đâu được?}
{302}{}{Có người bảo Dì Morlis đang giữ một cục. Mụ ta khó tính như ma
nên tôi chắc chẳng ai buồn hỏi đâu. Dĩ nhiên là mụ già ấy sẽ muốn đổi
lấy thứ gì đó.}
{303}{}{Cám ơn. Tạm biệt.}
{304}{}{Cô đã nói chuyện với bà dì về cục đá mài chưa?}
{305}{}{Rồi, tôi có đá ở đây.}
{306}{}{Chưa.}
{307}{}{Cục này tốt đấy. Đưa giáo cho tôi.}
{308}{}{Đây.}
{309}{}{Chắc là tôi không có rồi.}
{310}{}{Giờ thì đặt viên đá vào đây...}
{311}{}{Cứu tinh mà không có giáo á? Đây, cô lấy một cái của tôi mà dùng.
Giờ thì bắt đầu vào việc nào...}
{312}{}{Giáo mới của cô đây.}
{313}{}{Cám ơn bạn tôi -- Thứ này rất có ích đấy.}
{314}{}{Ừ, nhưng tôi muốn hỏi về cây giáo của anh. Trông nó có vẻ hơi
khác.}
{400}{}{Chào mừng về đến nhà, Cứu tinh! Cô tìm thấy căn hầm chưa? Cô có mang GECK về không?}
{401}{}{Ngộ không thấy chưa.}
{402}{}{Chưa, tôi chưa tìm thấy.}
{403}{}{Tôi không rảnh để trả lời câu hỏi của anh. Chào.}
{404}{}{Mọi thứ không ổn rồi, Cứu tinh à. Cơn hạn hán càng ngày càng tệ, cây trồng của chúng ta
sắp héo hết rồi. Chúng ta đang cố hái hết những gì còn sót lại để tích trữ lương thực.}
{405}{}{Sao không trao đổi với làng khác?}
{406}{}{Ngộ làm tốt nhất ngộ làm. Ngộ tìm GECK. Ngộ về.}
{407}{}{Tại sao chúng ta không trao đổi với các ngôi làng khác để lấy lương thực cần thiết?}
{408}{}{Tôi đang cố hết sức đây. Tôi sẽ trở lại khi nào tìm thấy GECK.}
{409}{}{Chúng ta sống đơn giản nên gần như không có gì để trao đổi. Mấy thị trấn mà chúng ta
đã liên lạc trong lúc cậu đi vắng không muốn giúp đỡ chúng ta.}
{410}{}{Ngộ thấy.}
{411}{}{Hiểu rồi.}
{412}{}{Cậu là hi vọng duy nhất của chúng ta, Cứu tinh ạ. Đừng khiến chúng ta thất vọng!}
{413}{}{Rất vui được gặp lại cậu, Cứu tinh. Nhiệm vụ của cậu đến đâu rồi?}
{414}{}{Ngộ vẫn tìm.}
{415}{}{Tôi vẫn đang tìm.}
{416}{}{Tôi không muốn nói với anh.}
{417}{}{Cậu phải nhanh lên. Mọi thứ ở làng đang ngày càng xấu đi. Lương thực sắp cạn rồi,
Trưởng lão nói chúng ta phải dè sẻn. Tôi thấy lo cho tương lai của Arroyo.}
{418}{}{Cứu tinh! Làm ơn nói với tôi là cô đã hoàn thành nhiệm vụ đi. Ngôi làng đang chết dần, mọi
người cũng thế.}
{419}{}{Không, ngộ vẫn tìm.}
{420}{}{Không, tôi vẫn đang tìm.}
{421}{}{Mọi chuyện thế nào rồi?}
{422}{}{Tôi rất tiếc, Cứu tinh, nhưng tôi bắt đầu thấy mất niềm in vào cô. Cuộc sống của cả bộ tộc
nằm trong tay cô. Làm ơn đi tìm số 13 thần thánh và mang GECK về cho chúng ta!}
{423}{}{Cây trồng héo úa, đàn bò chết dần, mọi người đều đói. Tiếng trẻ con khóc đêm làm không ai
ngủ được. Chúng ta đang đi đến đường cùng rồi.}
{424}{}{Ngộ tiếp tục tìm.}
{425}{}{Tôi sẽ làm những gì có thể.}
{426}{}{Cứu tinh, cô lại một lần nữa quay về. Tôi hi vọng không phải tay trắng chứ?}
{427}{}{Ngộ xin lỗi, không thấy GECK chưa.}
{428}{}{Tôi xin lỗi, tôi vẫn chưa tìm thấy GECK.}
{429}{}{Đủ lắm rồi.}
{430}{}{Mọi người đang chết còn cô thì cứ dạo quanh làng. Có lẽ cô nên đi tìm chỗ khác thay vì
quay lại đây.}
{500}{}{Cô đã nói chuyện với Trưởng lão chưa?}
{600}{}{Có lời khuyên cuối nào cho tôi trước khi tôi tiến vào đất hoang không?}
{601}{}{Chắc chắn rồi. Hãy nhớ cẩn thận trước vũ khí của đám Người ngoại tộc. Cú cắn của gecko không thể so được với sức hủy diệt từ mấy cây gậy lửa của chúng đâu.}
{602}{}{Hiểu rồi. Còn gì nữa không?}
{603}{}{Đừng có gặp ai cũng tin. Danh dự chẳng có nghĩa lí gì ngoài hoang mạc. Luôn cảnh giác và xem xét ý của người khác.}
{604}{}{Chắc rồi. Hết chưa nhỉ?}
{605}{}{Đừng quên gốc gác của mình. Thế giới bên ngoài làng đầy những thứ đồ chơi sáng bóng và phú quý mà nếu so sánh thì cuộc sống ở Arroyo trông có vẻ
đơn giản. Nhưng hãy nhớ rằng lối sống của Người ngoại tộc tạo ra những kẻ xấu xa tham lam và độc ác. Cẩn thận đừng trở thành Kẻ-không-được-gọi-tên.}
{606}{}{Tôi sẽ không bao giờ quên gốc gác của mình. Cám ơn vì lời khuyên, Mynoc.}
{607}{}{Kẻ-không-được-gọi-tên? Ờ... ai thế?}
{608}{}{Cô say men hào quang của Cứu tinh đến mức quên mất rồi à... [Mynoc liếc nhanh xung quanh để chắc là không có ai, rồi rướn người về phía bạn và hạ giọng thì thầm]... Kaga?}
{609}{}{Ồ! Đúng rồi, gã đó. Tôi sẽ đảm bảo mình không trở thành như vậy. Cám ơn.}
{610}{}{Ồ, ý anh là gã đó. Ờ nhưng mà, sao anh không tiếp tục kể lại cho tôi chuyện của hắn ta đi. Tôi thích câu chuyện đó lắm.}
{611}{}{[Mynoc lẩm bẩm gì đó trong mồm và lắc đầu trước khi bắt đầu câu chuyện]. Cậu biết đây, hắn ta từng là chiến binh mạnh nhất của bộ tộc. Hắn đã dẫn đầu nhiều đoàn tiến vào thế giới bên ngoài, và đó là nơi mà cái xấu bắt đầu thấm dần vào đầu hắn.}
{612}{}{Hắn ta trở nên say mê với cách sống của Người ngoại tộc, nơi mà sức mạnh có thể khiến bất kì ai cũng được phú quý và kinh sợ. Hắn ta bắt đầu tự coi mình là cao quý hơn những người đồng tộc vốn hài lòng với cuộc sống bình dị.}
{613}{}{Đúng là tởm lợm.}
{614}{}{Tiếp tục đi.}
{615}{}{Khi cả bộ tộc rơi vào thời kì khó khăn, hắn tự cho mình là người cứu cánh và tiến vào Ngôi đền thử thách để chứng tỏ hắn là Cứu tinh.}
{616}{}{Tiếp tục đi.}
{617}{}{Thôi, tôi không muốn nghe thêm chuyện này nữa. Chào nhé.}
{618}{}{Hắn đã tiến vào Đền, nhanh chóng đến với thử thách cuối cùng: chiến đấu bằng tay không với một chiến binh đồng tộc.}
{619}{}{Tiếp tục đi.}
{620}{}{Chờ đã, hắn ta đã cho nổ tung cánh cửa và những thứ khác? Chúng ta phải xây lại mọi thứ mỗi lần có người tiến vào đền? Mà nói vậy, ai là người đầu tiên xây đền thế?}
{621}{}{Tôi không có thời gian để trả lời tất cả các câu hỏi ngu ngốc. Có muốn tôi kết thúc câu chuyện không?}
{622}{}{Xin lỗi. Tiếp đi.}
{623}{}{Thực ra tôi nghĩ là mình sẵn sàng để đi rồi. Gặp lại sau.}
{624}{}{Trong thử thách cuối cùng, Kẻ-không-được-gọi-tên đã dùng một con dao giấu kín để giết đối thủ. Khi Trưởng lão hỏi về việc giấu và sử dụng vũ khí một cách hèn hạ, hắn ta cãi rằng đấy không phải là gian lận, mà chứng tỏ rằng hắn ta là một chiến binh khôn ngoan.}
{625}{}{Trưởng lão không đồng ý với việc đó. Kẻ-không-được-gọi-tên đã bị buộc phải rời khỏi bộ tộc và tên của hắn ta vĩnh viễn không được chúng ta nhắc đến nữa. Khi bị trục xuất ra ngoài đất hoang, hắn ta thề sẽ trả thù. Mối thù với bộ tộc và nhất là với cô.}
{626}{}{Tôi ư? Tôi đã làm gì?}
{627}{}{Cám ơn về câu chuyện, nhưng giờ tốt nhất là tôi nên lên đường thôi.}
{628}{}{Cô là Cứu tinh, danh hiệu mà hắn cho rằng thuộc về hắn. Tính cao ngạo khiến hắn muốn cô phải chết.}
{629}{}{Tôi không thấy có gì đáng lo cả. Giờ này chắc hẳn hắn ta nghẻo ngoài hoang mạc rồi.}
{630}{}{Tôi sẽ cẩn thận. Hi vọng là giờ này hắn ta nghẻo ngoài hoang mạc rồi.}
{631}{}{Nghe này và nhớ lấy. Kẻ-không-được-gọi-tên ở ngoài đó. Không thể thuyết phục hay trao đổi với hắn ta được. Hắn không biết thương hại, hối hận hay sợ ai. Và hắn chắc chắn sẽ không dừng lại cho đến khi cô chết.}
{632}{}{Anh biết đấy, tôi nghĩ là anh có thể viết kịch hơi quá rồi, một chút thôi. Dù sao thì cũng cám ơn vì lời khuyên. Gặp lại anh sau, Mynoc.}
{633}{}{Tôi sẽ để tâm đến điều đó. Bảo trọng, Mynoc.}
{640}{}{Anh có thể kể thêm gì cho tôi về gã Kaga này không?}
{641}{}{[Anh ta tròn mắt và bồn chồn nhìn quanh như thể sắp bị sét đánh]. Cô nghịch cát ngoài hoang mạc đến mụ cả người rồi à!? Cô phải hiểu là không được gọi tên của kẻ bị trục xuất chứ! Phải gọi hắn ta là Kẻ-không-được-gọi-tên.
Ngôi làng đã đủ khốn khổ rồi, không cần làm các Thần tức giận thêm đâu. [Anh ta run rẩy ngước mắt nhìn lên trời].}
{642}{}{Xin lỗi nhé Mynoc. Nhưng liệu anh có thể kể lại về Ka... ý tôi là, "Kẻ-đó" lần nữa không? Tôi rất thích câu chuyện đó.}
{643}{}{Anh biết đấy, tôi quên mất là mấy người mê tín như anh ngốc đến mức nào. Gặp lại anh sau.}
{650}{}{Tôi đã đối diện với hắn ta rồi nên tôi chắc là mình có thể xử lý gã đó nếu gặp lại lần nữa.}
{651}{}{Thực ra thì hắn ta chết rồi. Tôi đã để xác của hắn ta thối rữa ngoài hoang mạc.}
{660}{}{[Mynoc trầm giọng gật đầu]. Hắn ta có thể đã lạc lối, nhưng dù sao vẫn từng là một chiến binh mạnh mẽ đáng kính. Tôi hi vọng linh hồn tội lỗi của hắn có thể tìm thấy sự binh an ở thế giới bên kia.}
{661}{}{Đúng vậy. Gặp lại anh sau, Mynoc.}
{662}{}{Sao cũng được. Với tôi hắn ta chỉ là một kẻ cao ngạo thôi. Gặp lại anh sau, Mynoc.}
{1000}{}{Trưởng lão}
{1001}{}{Người mở làng}
{1002}{}{Cụ tổ từ Vault}
{1003}{}{Arroyo}
{1004}{}{Klamath}
{1005}{}{Vault}
{1006}{}{Cứu tinh}
{1007}{}{Thầy cúng}
{1008}{}{Hakunin}
{1009}{}{Bột chữa thương}
{1010}{}{Cầu}
{1011}{}{Mynoc}
{1100}{}{Trưởng lão là mẹ cô đồng thời là trưởng làng.}
{1101}{}{Cụ tổ vĩ đại đã truyền kiến thức cho chúng ta.}
{1102}{}{Người đầu tiên chiến đấu và chiến thắng cái xấu.}
{1103}{}{Đó là ngôi làng xinh đẹp của chúng ta.}
{1104}{}{Đó là một khu buôn bán cách nơi này vài ngày về phía Đông.}
{1105}{}{Vault là thiên đường.}
{1106}{}{Cô là Cứu tinh.}
{1107}{}{Ông ta trị thương bằng thảo dược và phép thuật. Ông ta
ở khu phía Bắc của ngôi làng.}
{1108}{}{Ông ta trị thương bằng thảo dược và phép thuật. Ông ta
ở khu phía Bắc của ngôi làng.}
{1109}{}{Đây là một túi bột phép có thể trị thương cho cô,
nhưng cô sẽ thấy buồn ngủ khi dùng.}
{1110}{}{Cây Cầu Lớn dẫn ra ngoài làng ở phía Nam.}
{1111}{}{Đó là tôi.}
