{100}{}{B?n th?y Cameron, m?t ngư?i đ?ng t?c.}
{101}{}{B?n th?y Cameron.}
{102}{}{B?n th?y m?t c?u trai tr? có cơ b?p cu?n cu?n v?i dáng v? r?t t? tin.}
{103}{}{Xin chào,}
{104}{}{. Tôi có vinh d? đư?c làm th? thách cu?i cùng c?a cô. Đ? ti?p t?c nhi?m v?, cô ph?i th?ng
tôi trong cu?c đ?u tay không. Chúng ta b?t đ?u đư?c ch??}
{105}{}{Ng? mu?n h?i.}
{106}{}{Đư?c, ta đánh.}
{107}{}{Không, ng? s?n sàng trư?c.}
{108}{}{Tôi có m?y câu c?n h?i trư?c.}
{109}{}{Đư?c r?i, nh?y nào.}
{110}{}{Tôi ngh? là m?nh c?n chu?n b? m?t chút.}
{111}{}{Cô mu?n bi?t g? nào?}
{112}{}{Sao ta l?i đánh?}
{113}{}{Ta đánh đ?n ch?t?}
{114}{}{Ta đánh tay không?}
{115}{}{Okê, đánh thôi.}
{116}{}{Ng? c?n s?n sàng.}
{117}{}{T?i sao chúng ta l?i ph?i đánh nhau?}
{118}{}{Chúng ta có c?n đánh nhau đ?n ch?t không?}
{119}{}{Anh nói là chúng ta s? đánh tay không à?}
{120}{}{H?y b?t đ?u tr?n đ?u nào.}
{121}{}{Tôi c?n chu?n b? cho tr?n đ?u m?t chút.}
{122}{}{Ch?ng đư?ng c?a C?u tinh không h? d? dàng,}
{123}{}{. Cô s? ph?i đ?i di?n v?i r?t nhi?u th? thách trong su?t cu?c đ?i, và th? thách khó khăn nh?t
chính là đ?i đ?u v?i ngư?i đ?ng t?c. S? có lúc l?i nói và ng? đi?u không có tác d?ng g? c?, ch? có
th? gi?i quy?t b?ng n?m đ?m mà thôi. Th? thách này giúp cô đ?i m?t v?i ngư?i khác, nh?n th?ng
vào m?t c?a h?n ta và bi?t r?ng cô có th? c?n ph?i gi?t h?n. }
{124}{}{Okay.}
{125}{}{Hi?u r?i.}
{126}{}{Không đâu, b?n tôi ơi. Cô ch? c?n đánh th?ng tôi. Đ?n lúc đó, chúng ta s? k?t thúc tr?n đ?u.}
{127}{}{Ng? hi?u.}
{128}{}{Đư?c r?i.}
{129}{}{Đúng v?y. V? khí khi?n chúng ta gi? kho?ng cách v?i chi?n tr?n và không c?n ngh? v? h?u qu? c?a
hành đ?ng c?a m?nh cho ngư?i khác. Khi dùng tay tr?n đ?m ngư?i khác, cô v?a nh?n th?y v?a
c?m nh?n đư?c n?i đau đ?n mà m?nh gây ra. Tr?n đ?u s? tr? nên r?t th?t và mang tính cá nhân. Đây
là m?t bài h?c quan tr?ng dành cho cô, }
{130}{}{.}
{131}{}{Ng? hi?u r?i.}
{132}{}{Tôi hi?u r?i.}
{133}{}{Đư?c r?i. Chúng ta b?t đ?u đư?c ch??}
{134}{}{Ng? s?n sàng.}
{135}{}{Không, ng? s?n sàng trư?c.}
{136}{}{Tôi đ? s?n sàng.}
{137}{}{Chưa, tôi c?n chu?n b? m?t chút.}
{138}{}{Đư?c r?i. Quay l?i b?o tôi khi nào cô đ? s?n sàng cho th? thách.}
{139}{}{Are you ready for your challenge, }
{140}{}{?}
{141}{}{Me ready. }
{142}{}{Me not ready yet.}
{143}{}{I think so.}
{144}{}{No, give me a minute.}
{145}{}{Excellent! Your equipment will be kept in the trunk outside of the room.
 You can get it after the fight. Let the fight begin! Good luck to you }
{146}{}{.}
{147}{}{It is good to see you again, Chosen One. How may I help you?}
{148}{}{Me want visit temple again.}
{149}{}{Want fight again?}
{150}{}{Just say hello. Me go now.}
{151}{}{I'd like to visit the temple again.}
{152}{}{Hello, Cameron. Ready for another fight?}
{153}{}{Just thought I'd say hi. See you later.}
{154}{}{Take the path to my left, Chosen One. It leads to the temple proper.
 The cave entrance behind me will return you to the last chamber.}
{155}{}{Okay, me go.}
{156}{}{All right. Thanks}
{157}{}{No thank you, Chosen One. I still carry the bruises from our last encounter and will need
 years to recover!}
{158}{}{Go bye, Cameron.}
{159}{}{Ha! Good day to you, Cameron.}
{160}{}{Chosen One, my ass. I am going to make you the dead one!}
{161}{}{You have defeated me. You are worthy, Chosen One.}
{165}{}{I disagree with you. I think that a peaceful solution to any problem is possible.}
{166}{}{You may be correct, }
{167}{}{, but not in our current situation. You must defeat me to succeed in your trial.}
{168}{}{Look, I don't know all of your strengths and weaknesses, and you don't know mine.
 Accidents do happen, so what if one of us inadvertently kills the other? Let's just
 end this now rather than take that chance, okay?}
{169}{}{Hmm... I see your point. I wouldn't want to be responsible for
 killing you when all I meant to do was test your mettle. Very well -- you may
 pass, Chosen One.}
{170}{}{Hmm... I see your point. However, we must still do battle. I will
 simply take care not to hurt you too much.}
{171}{}{Thanks! I'll see you back in the village.}
{172}{}{Hi?u r?i.}
{200}{}{I don't seem to remember our last battle, Chosen One. I will always wonder how you managed
 to get past me.}
{201}{}{You have a tongue of purest silver, Chosen One. Your skill with words will open many doors
 for you.}
{300}{}{And to you as well, Chosen One. May the spirits guide you on your quest.}
{301}{}{Thanks, Cameron.}
{302}{}{Chosen One, I could not help but notice that you lack strong combat skills. It has been my experience that you cannot always rely on your wits or words for protection. With your permission I will teach you a few things that I think you will find most useful.}
{303}{}{Yes, you teach.}
{304}{}{No, me not need.}
{305}{}{Yes, please teach me all that you can.}
{306}{}{Thanks, but I think I can handle myself just fine.}
{307}{}{You learn well, Chosen One. I think you will be able to handle yourself in a fight now. However, remember that even the strongest of warriors must sometimes retreat. There is no shame in living to fight another day.}
{308}{}{Me thank you, Cameron.}
{309}{}{Thanks, Cameron. I will remember your words.}
{310}{}{Very well. Return to me if you change your mind.}
{311}{}{Me thank you, Cameron.}
{312}{}{Thanks, Cameron. I will remember your offer.}
{400}{}{Do you ever think about stepping down from your position as the Temple's final trial? I mean, it can be pretty risky.}
{401}{}{Life is a constant series of risks, Chosen One. With each new dawn, every one of us takes a risk simply by stepping from our homes to greet the unknown day. Why do you ask?}
{402}{}{No reason. I'll talk with you later, Cameron.}
{403}{}{Well, I was just thinking about what happened to your predecessor, you know, during his battle with... uh, "He-Who-Must-Not-Be-Named".}
{410}{}{Ah, that was a dark day, indeed, for our tribe lost two good men: one in body, the other in spirit. But the foul deed of that day is no concern of mine. My time will come when the Gods deem it so.}
{411}{}{And may that day be a long time coming. Good day, Cameron.}
{412}{}{Are they even going to have other people attempt the Temple? Hasn't it already been determined that I'm the Chosen One?}
{420}{}{There will always be a need to test the might of our people. And I take great honor in doing my part.}
{421}{}{Alright, I'll see you later, Cameron.}
