{100}{}{Bạn thấy Thầy trụ trì, người đứng đầu tôn giáo của Tu viện.}
{101}{}{Có thứ gì đó về thầy tu này khiến bạn tin rằng ông ta rất quan trọng.}
{200}{}{Xin chào, người lữ khách.}
{201}{}{Bình an nhé.}
{202}{}{Chúng tôi là những người giữ gìn kiến thức.}
{203}{}{Tôi rất tiếc, nhưng kiến thức trong sách của chúng tôi không giúp gì được cho cô.}
{300}{}{Chào mừng đến với Tu viện, người lữ khách. Tôi có thể giúp gì đây?}
{301}{}{Ông có thể nói gì về hội không?}
{302}{}{Ông có từng nghe nói đến một thứ gọi là GECK chưa?}
{303}{}{Ông có biết tôi có thể tìm Vault 13 ở đâu không?}
{304}{}{Chào.}
{400}{}{Muốn biết gì nào?}
{401}{}{Okay. Tôi muốn hỏi về việc khác.}
{402}{}{Hừm... nghe *có vẻ* quen. Ồ, có, tôi nhớ là Thầy Thomas gần đây có nhắc gì đó đến thứ này. Thứ lỗi nhưng tôi không nhớ chính xác ông ta đã nói gì.}
{403}{}{Không sao. Chỉ cần nói cho tôi biết Thầy Thomas ở đâu và tôi sẽ đi hỏi ông ta.}
{404}{}{Tôi không biết gì về chuyện đó.}
{405}{}{Ồ, dẫu sao thì cũng cám ơn.}
{406}{}{Tôi e là tôi không làm được chuyện đó. Cậu xem, tôi ngờ là Thầy Thomas không còn sống nữa. Nhưng thật may cho cô
thầy là một trong những người ghi chép đáng tin cậy nhất. Tôi chắc là bất kì nội dung nào mà ông ta có được về thông tin
cô đang tìm kiếm đã được ghi vào trong máy tính của chúng tôi.}
{407}{}{Chờ đã, ông đang "ngờ" rằng thầy Thomas đã chết? Ở ngoài kia cái chết rõ ràng lắm. Ông ta thực ra đã chết hay chưa?}
{408}{}{Huynh Thomas đã mất tích trong nhiều ngày kể từ khi ông ta đi xuống hang động bên dưới Tu viện [Ông ta thở dài yếu ớt].
Cậu thấy đấy, một vài người trong Tu viện kể rằng có nhìn thấy một con quái vật to lớn ẩn thân dưới đó, nhưng Thầy Thomas
không tin điều đó. Ông ta tự mình đi xuống để xóa bỏ tin đồn, vậy mà trên thực tế việc ông ta mất tích chỉ là minh chứng rõ hơn.}
{409}{}{Hừm. Chắc là tôi nên đi xem có gì dưới đó. *TÔI* là cứu tinh cơ mà...}
{410}{}{Tôi chuyên đi phiêu lưu. Tôi có thể đi xem sao.}
{411}{}{Cô sẽ làm vậy thật à? Chắc là trong lúc xuống đó, cô có thể tìm một cuốn sách này. Cô xem, thầy Thomas là người
cuối cùng giữ cuốn sách, và nó rất quan trọng với chúng tôi. Cuốn sách đã được truyền lại từ thời người sáng lập. Nếu
cô có thể lấy lại cuốn sách thì tôi sẽ rất biết ơn. Nói luôn là tôi sẽ cấp cho cô toàn bộ quyền truy cập vào máy tính
để cô có thể tìm kiếm bất cứ cái gì cô muốn.}
{412}{}{Cứ vậy đi. Tôi sẽ sớm trở lại.}
{413}{}{Có thể. Để tôi nghĩ thêm một lát đã...}
{414}{}{Cám ơn. Vui lòng nói cho tôi biết khi nào tìm thấy sách.}
{415}{}{Ok, tạm biệt.}
{416}{}{Xin chào, bạn tôi.}
{417}{}{Tôi đã tiêu diệt con quái vật và lấy lại sách đây.}
{418}{}{Tuyệt vời! Hãy đưa cho tôi!}
{419}{}{Đây.}
{420}{}{Từ từ đã. Cuốn sách này đáng giá bao nhiêu?}
{421}{}{[Ông ta nhận cuốn sách từ tay bạn và vuốt ve bìa sách như thể để an ủi]. Cô đã giúp chúng tôi rất nhiều. Giờ
thì cô có đầy đủ quyền truy cập vào máy tính trong thư viện. Hãy nói với Huynh Paul là tôi cấp quyền truy cập cho cô.}
{422}{}{Cám ơn.}
{423}{}{Cô muốn lấy tiền à? Được rồi, cầm lấy 250$. Đến gặp Huynh Paul để lấy quyền truy cập máy tính.}
{424}{}{Cám ơn về chỗ tiền, tạm biệt.}
{425}{}{Cô nên dùng máy tính trên tầng hai, giờ thì cô đã có đầy đủ quyền truy cập rồi.}
{426}{}{Ok, tạm biệt.}
{430}{}{Hội này có mục đích gì vậy?}
{431}{}{Lịch sử của Tu viện ra sao?}
{432}{}{Hừm, tôi hiện không có câu hỏi nào.}
{433}{}{Nhiệm vụ thần thánh của chúng tôi là đọc, sao chép và bảo quản những cuốn sách kiến thức thiêng liêng cùng
những bảo vật khác từ thời đã mất. Chúng tôi hi vọng là với kiến thức này, chúng tôi có thể tạo ra Khu kỉ vật để một ngày
nào đó giúp nhân loại thoát khỏi thời kì Đen tối do mình tự gây ra. Tất cả những thông tin chúng tôi tìm thấy đều được
ghi lại để khỏi bị mất như rất nhiều thứ khác trong cơn Đại Hỏa.}
{434}{}{Sau Đại chiến, bàn tay dẫn lối của vận mệnh đã chỉ đường cho tổ tiên chúng tôi đến với Tu viện cũ trong núi này. Nhờ
vị trí biệt lập, tu viện đã thoát khỏi cơn Đại Hỏa mà không bị hư hại nhiều. Trong lúc khám phá tòa nhà, tổ tiên chúng tôi
phát hiện một thư viện đầy sách. Và không chỉ có sách tôn giáo, ồ, thư viện này còn chứa đựng rất nhiều tác phẩm viết
nữa, từ văn học cổ điển đến bách khoa toàn thư khoa học.}
{435}{}{Sau đó thì sao?}
{436}{}{Tôi nghe đủ rồi.}
{437}{}{Họ nhanh chóng nhận ra kho báu kiến thức thật sự chứa trong những cuốn sách này -- nhất là những cuốn
khoa học. Đây là biên niên sử về một nền văn minh đã sụp đổ. Một thời đã mất. Có một số người tin rằng tốt nhất
nên hủy những kiến thức này, sợ rằng chúng sẽ một lần nữa hướng nhân loại đến tận thế. Nhưng cuối cùng họ
quyết định rằng thay vào đó, họ sẽ cống hiến cả đời để bảo quản những cuốn sách, để đưa kiến thức trở lại khi và
nếu, thế giới đã sẵn sàng đón nhận.}
{438}{}{(Thêm)}
{439}{}{Và như vậy, sử dụng một máy in nhỏ, họ bắt đầu sao chép các cuốn sách cũng như ghi chép lại chúng vào
máy tính của Tu viện để bảo quản dạng số, phòng khi sách bản gốc bị hư hại. Qua nhiều năm dài, những người khác
đã đến Tu viện và một số đã chọn ở lại để sống đời tĩnh lặng trong ngôi nhà trên núi này.}
{440}{}{Cám ơn về câu chuyện.}
{441}{}{Tổ tiên của các ông đến từ đâu?}
{442}{}{Họ chẳng nói gì về nguồn gốc ban đầu cả. Chúng tôi ngờ rằng họ ban đầu đến từ phía Đông.}
{443}{}{Ồ, cám ơn về câu chuyện.}
{444}{}{Ông có cần giúp gì ở tu viện không?}
{445}{}{Tôi đã tìm ra lí do máy bơm nước bị hỏng rồi.}
{446}{}{Ông có biết gì về những người sáng lập ban đầu không?}
{447}{}{Tôi không biết tất cả tên của những người sáng lập, nhưng người quan trọng nhất mà tôi biết là Miller.
Trước Đại chiến ông là một kĩ sư điện làm việc cho chính phủ Hoa Kỳ. Không lâu sau đó, ông cải sang đạo Công giáo
và lập lời thề rằng sẽ dành cả cuộc đời để bảo tồn kiến thức trong quá khứ. Điều khiến ông sợ nhất là kiến thức sẽ bị
mất đi mãi mãi và do đó, cần được bảo tồn để các thế hệ tương lai được hưởng lợi.}
{448}{}{Ông đọc nhiều thế chắc phải biết nhiều lắm.}
{449}{}{Đúng là tôi đã đọc rất nhiều trong suốt cuộc đời. Nhưng có thể cô sẽ thấy thất vọng trước giới hạn kiến thức
của tôi. Cô thấy đấy, chúng tôi ghi chép và bảo tồn. Chúng tôi bị cấm sử dụng tri thức trong sách, do đó chúng tôi chỉ hiểu một phần thôi.}
{450}{}{Chờ đã, ông đang nói là các ông chỉ nhắm mắt chép lại sách chứ không thèm tìm hiểu chúng có nghĩa gì?}
{451}{}{Như đã nói, công việc của chúng tôi là bảo tồn kiến thức chứ không phải để hiểu. Trước khi những kiến thức
này trở lại với nhận loại, loài người đầu tiên cần chứng minh họ đã vượt lên trên cái thói diệt chủng hàng loạt. Đó là
cách duy nhất để đảm bảo rằng lịch sử sẽ không lặp lại.}
{452}{}{Ồ, vậy thì tôi có tin tức cho ông đây: ngày đó sẽ chẳng bao giờ đến cả. Trong lúc các ông đang ôm mớ kiến thức trong
thiên đường nhỏ trên núi này, những người khác ở hoang mạc đang vật lộn hằng ngày để sinh tồn. Thực ra, cả tộc tôi đang
trên bờ vực diệt vong. Những kiến thức có trong đống sách này có thể giúp chữa bệnh, cải tạo cây trồng và nâng cao khả năng
sống sót của nhân loại đấy.}
{453}{}{Ah, chắc là ông nói có điểm đúng. Nhưng có vẻ những thông tin được lưu trữ ở đây có thể giúp đỡ rất nhiều người.
Dù cho các ông có nghĩ rằng thế giới chưa sẵn sàng để đón nhận kiến thức, nhưng tôi không hiểu tại sao *ông* chí ít
không thử học hỏi chúng. Nếu không thì việc lưu giữ có nghĩa lí gì?}
{454}{}{Tôi hiểu là cô thấy khó chịu với lẽ sống này, nhưng cô phải hiểu rằng đây là cách mà chúng tôi luôn tuân theo.
Giờ mà thay đổi, sau bao nhiêu năm... điều đó sẽ trái ngược hoàn toàn với đức tin của chúng tôi. Không, tôi thấy là
chúng tôi cần tiếp tục sống theo các giới luật do tổ tiên đặt ra.}
{455}{}{Tôi hiểu là cô thấy khó chịu với lẽ sống này, nhưng cô phải hiểu rằng đây là cách mà chúng tôi luôn tuân theo.
Giờ mà thay đổi, sau bao nhiêu năm... điều đó sẽ trái ngược hoàn toàn với đức tin của chúng tôi. Tuy vậy, tôi sẽ suy
nghĩ về lời của cô. Tôi cảm nhận được trí tuệ của cô, người lữ khách. Thật tiếc là tôi chỉ gặp được số ít người như cô.}
{456}{}{Cám ơn. Tôi muốn hỏi về việc khác nữa.}
{457}{}{Được rồi. Tôi muốn hỏi về việc khác nữa.}
{500}{}{Dừng lại!}
{501}{}{Bạn nhận được 200 điểm kinh nghiệm vì đã mang cuốn sách trở lại.}
{600}{}{Tôi đã sửa cái máy bơm nước bị hỏng rồi.}
{601}{}{Đúng là tin tốt đấy. Cái máy bơm nước đấy bị trục trặc lâu lắm rồi. Mấy tay thương lái cứ bảo để đấy họ lo, nhưng
mãi chẳng thấy có kết quả gì. Thật tốt là cô đã đến giúp. Cám ơn cô nhiều.}
{602}{}{Ông biết là sửa chữa thì phải mất phí đấy nhé. Giờ thì nôn tiền ra!}
{603}{}{Không vấn đề. Tôi vẫn còn mấy câu muốn hỏi nữa.}
{604}{}{Mừng là tôi đã giúp được. Bảo trọng.}
{605}{}{[Cau mày]. Hiểu rồi. Được rồi, đây, cầm lấy mấy đồng này. Giờ thì đi đi và đừng có làm phiền tôi nữa.}
{606}{}{Cám ơn, *cha*.}
{700}{}{Ờ... chưa, hình như tôi để nhầm chỗ rồi.}
{701}{}{Cái gì!? [Ông ta thở mạnh]. Thật đáng tiếc là cô không lấy lại được sách. Nhưng cô nói rằng đã tiêu diệt con
quái vật? Hừm, vậy thì chắc là đã đủ an toàn để cử người xuống đó tiếp tục tìm kiếm. À đấy, để cảm ơn, tôi sẽ cấp cho
cô quyền truy cập máy tính. Hãy đến gặp Huynh Paul để lấy khóa truy cập.}
{702}{}{Cám ơn.}
{800}{}{Thực ra là có. Cái máy bơm nước chính của chúng tôi bị trục trặc lâu lắm rồi, đến giờ thì có vẻ đã bị hỏng hẳn. Nếu cô
biết về máy móc thì liệu cô có thể xem qua xem có làm được gì không? Có mấy tay lái buôn đang sửa rồi nhưng tôi e là
chẳng có tiến triển gì mấy.}
{801}{}{Được tôi sẽ giúp. Tôi sẽ báo lại tình hình sau.}
{802}{}{Được chứ, tôi rất sẵn lòng giúp... nếu có trả công, dĩ nhiên rồi.}
{803}{}{Dưng mà nghĩ lại thì, để tôi hỏi chuyện khác.}
{804}{}{Cái gì!? Ồ, được rồi. Nếu cậu là người như vậy thì cậu sẽ được trả công nếu giúp được. Đây là 25 xu phí ban đầu.
Vui lòng báo lại cho tôi nếu cậu có thể làm gì đó [Ông ta thở dài khi đưa mấy đồng xu cho bạn].}
{805}{}{Này, sao phải thở dài. Ông nghĩ mọi thứ trên đời đều miễn phí à? Giờ thì để tôi vào việc nào.}
{806}{}{Thật ư? Vui lòng nói đi.}
{807}{}{Cục động cơ nát rồi và đám đầu nối thì cháy sạch. Tôi sẽ đi đến Thành phố Vault để lấy bộ phận mới.}
{808}{}{Ồ cám ơn. Cô đúng là giỏi thật. Vui lòng báo lại sau khi cô đã lắp xong bộ phận mới.}
{809}{}{Được rồi, tôi sẽ sớm trở lại.}
{900}{}{Bạn giải thích cho Thầy trụ trì rằng dù cho những thông tin họ đang bảo tồn có thể dẫn loài người đến sự diệt vong, thì chúng cũng có thể cứu rỗi loài người.}
{901}{}{Bạn tìm hiểu về người sáng lập ban đầu của Tu viện.}
{1000}{}{Ngộ tiêu riệt con quái dưới hang rồi.}
{1010}{}{Thật ư? Tuyệt vời. Dũng cảm lắm, cậu bé nhớn.}
{1011}{}{Thật ư? Tuyệt vời. Dũng cảm lắm, cô bé nhớn.}
{1012}{}{(cười) Ngộ biết.}
{1020}{}{Cậu có tìm thấy cuốn sách nào ở đấy không? Một người bạn của tôi cầm nhưng ông ta bị mất tích rồi.}
{1021}{}{Ngộ tìm sách. Đây, nặng vc và không có hình.}
{1022}{}{Ngộ không tìm sách. Sin lỗi. Ngộ tìm sách giờ.}
{1030}{}{Ngộ tìm sách.}
{1031}{}{Tuyệt vời. Cám ơn, đúng là một cậu bé đặc biệt.}
{1032}{}{Tuyệt vời. Cám ơn, đúng là một cô bé đặc biệt.}
{1033}{}{YAY.}
{1100}{}{Tôi có xuống đó lúc nãy. Tôi nhìn thấy mấy xác chết nên chắc thầy tu mất tích là một trong số đó. Có thể ông sẽ
cảm thấy khá hơn vì tôi đã diệt cái thứ đã giết ông ta.}
{1110}{}{À... vậy là điều tôi e ngại đã đúng. Thật tiếc khi Huynh Thomas không còn nữa. Cám ơn cô đã loại bỏ giúp
chúng tôi thứ quái quỷ ngoài hoang mạc núp ở dưới đó. Tuy nhiên, tôi... không biết cô có tìm thấy cuốn sách nào dưới đó
không. Đó là một cuốn sách rất quan trọng mà Huynh Thomas là người cầm cuối cùng.}
{1111}{}{Không, nhưng chắc là tôi có thể quay lại xem sao.}
{1112}{}{Ý ông là cuốn sách này?}
{1113}{}{Trước khi đi, tôi muốn hỏi chuyện khác.}
{1411}{}{Hay đấy. Tôi phải đi đây.}
{3000}{}{Tôi giúp gì được nhỉ?}
{4091}{}{Vậy là chẳng có ai buồn xuống đó tìm ông ta à? Thế nếu ông ta chỉ đơn giản là bị mắc kẹt lại dưới đó và đang chết dần vì đói thì sao?}
{4092}{}{Cũng có thể, nhưng cô phải hiểu điều này. Chúng tôi là những người sống thanh bình. Việc phải đối diện với một trong số quái vật ngoài hoang mạc khiến chúng tôi sợ chết khiếp. Chúng tôi đơn giản là không sẵn sàng để đối diện thứ đó.}
{4177}{}{Tôi đã tiêu diệt con quái vật.}
{4188}{}{Tuyệt vời! Vậy còn cuốn sách thì sao, cô có thu hồi lại được không?}
{6020}{}{Nếu ông thật lòng muốn cám ơn thì sao không gửi tôi chút tiền vì đã bỏ công ấy?}
