{100}{}{B?n th?y Th?y tr? tr?, ngư?i đ?ng đ?u tôn giáo c?a Tu vi?n.}
{101}{}{Có th? g? đó v? th?y tu này khi?n b?n tin r?ng ông ta r?t quan tr?ng.}
{200}{}{Xin chào, ngư?i l? khách.}
{201}{}{B?nh an nhé.}
{202}{}{Chúng tôi là nh?ng ngư?i gi? g?n ki?n th?c.}
{203}{}{Tôi r?t ti?c, nhưng ki?n th?c trong sách c?a chúng tôi không giúp g? đư?c cho cô.}
{300}{}{Chào m?ng đ?n v?i Tu vi?n, ngư?i l? khách. Tôi có th? giúp g? đây?}
{301}{}{Ông có th? nói g? v? h?i không?}
{302}{}{Ông có t?ng nghe nói đ?n m?t th? g?i là GECK chưa?}
{303}{}{Ông có bi?t tôi có th? t?m Vault 13 ? đâu không?}
{304}{}{Chào.}
{400}{}{Mu?n bi?t g? nào?}
{401}{}{Okay. Tôi mu?n h?i v? vi?c khác.}
{402}{}{H?m... nghe *có v?* quen. ?, có, tôi nh? là Th?y Thomas g?n đây có nh?c g? đó đ?n th? này. Th? l?i nhưng tôi không nh? chính xác ông ta đ? nói g?.}
{403}{}{Không sao. Ch? c?n nói cho tôi bi?t Th?y Thomas ? đâu và tôi s? đi h?i ông ta.}
{404}{}{Tôi không bi?t g? v? chuy?n đó.}
{405}{}{?, d?u sao th? c?ng cám ơn.}
{406}{}{Tôi e là tôi không làm đư?c chuy?n đó. C?u xem, tôi ng? là Th?y Thomas không c?n s?ng n?a. Nhưng th?t may cho cô
th?y là m?t trong nh?ng ngư?i ghi chép đáng tin c?y nh?t. Tôi ch?c là b?t k? n?i dung nào mà ông ta có đư?c v? thông tin
cô đang t?m ki?m đ? đư?c ghi vào trong máy tính c?a chúng tôi.}
{407}{}{Ch? đ?, ông đang "ng?" r?ng th?y Thomas đ? ch?t? ? ngoài kia cái ch?t r? ràng l?m. Ông ta th?c ra đ? ch?t hay chưa?}
{408}{}{Huynh Thomas đ? m?t tích trong nhi?u ngày k? t? khi ông ta đi xu?ng hang đ?ng bên dư?i Tu vi?n [Ông ta th? dài y?u ?t].
Cô th?y đ?y, m?t vài ngư?i trong Tu vi?n k? r?ng có nh?n th?y m?t con quái v?t to l?n ?n thân dư?i đó, nhưng Th?y Thomas
không tin đi?u đó. Ông ta t? m?nh đi xu?ng đ? xóa b? tin đ?n, v?y mà trên th?c t? vi?c ông ta m?t tích ch? là minh ch?ng r? hơn.}
{409}{}{H?m. Ch?c là tôi nên đi xem có g? dư?i đó. *TÔI* là c?u tinh cơ mà...}
{410}{}{Tôi chuyên đi phiêu lưu. Tôi có th? đi xem sao.}
{411}{}{Cô s? làm v?y th?t à? Ch?c là trong lúc xu?ng đó, cô có th? t?m m?t cu?n sách này. Cô xem, th?y Thomas là ngư?i
cu?i cùng gi? cu?n sách, và nó r?t quan tr?ng v?i chúng tôi. Cu?n sách đ? đư?c truy?n l?i t? th?i ngư?i sáng l?p. N?u
cô có th? l?y l?i cu?n sách th? tôi s? r?t bi?t ơn. Nói luôn là tôi s? c?p cho cô toàn b? quy?n truy c?p vào máy tính
đ? cô có th? t?m ki?m b?t c? cái g? cô mu?n.}
{412}{}{C? v?y đi. Tôi s? s?m tr? l?i.}
{413}{}{Có th?. Đ? tôi ngh? thêm m?t lát đ?...}
{414}{}{Cám ơn. Vui l?ng nói cho tôi bi?t khi nào t?m th?y sách.}
{415}{}{Ok, t?m bi?t.}
{416}{}{Xin chào, b?n tôi.}
{417}{}{Tôi đ? tiêu di?t con quái v?t và l?y l?i sách đây.}
{418}{}{Tuy?t v?i! H?y đưa cho tôi!}
{419}{}{Đây.}
{420}{}{T? t? đ?. Cu?n sách này đáng giá bao nhiêu?}
{421}{}{[He takes the book from you and caresses its cover as if to sooth it.] You have done us a great service. You now
 have full access to our computers in the library. Tell Brother Paul I grant you permission to access our files.}
{422}{}{Cám ơn.}
{423}{}{You want money for it? Fine, here's $250. Go see Brother Paul for access to the computers.}
{424}{}{Thanks for the money, bye.}
{425}{}{You should look on a second floor computer, now that you have full access there.}
{426}{}{Ok, t?m bi?t.}
{430}{}{What is the purpose of your order?}
{431}{}{What is the history behind the Abbey?}
{432}{}{Hmm, I don't have any questions at the moment.}
{433}{}{Our holy mission is to read, copy and take care of our sacred books of knowledge and other relics of the lost age.
 It is our hope that with this knowledge we are able to create a Memorabilia that might one day help humanity emerge from
 its self-imposed Dark Age. Any information that we come across is recorded, lest it be lost like so much was in the
 great Flame Deluge.}
{434}{}{After the Great War, the guiding hands of fate directed our ancestors to this old Abbey in the mountains. Due to
 its remote location, the monastery survived the Flame Deluge mostly unscathed. As our ancestors explored the building,
 they discovered an extensive library of books. And not just religious texts, oh no, this library contained the gamut of
 written works, from literary classics, to scientific encyclopedias.}
{435}{}{What happened then?}
{436}{}{I've heard enough.}
{437}{}{They soon realized the true treasure trove of wisdom stored within those books--especially the scientific tomes.
 Here were the chronicles of a fallen civilization. A lost age. There were a few who thought it might be best to
 destroy this knowledge, for fear that it would once again guide humanity towards apocalypse. But it was eventually
 decided that they would instead dedicate themselves to ensuring the preservation of the books, to be released when,
 and if, the world was ready for it.}
{438}{}{(More)}
{439}{}{And so, utilizing a small printing press, they began making copies of the books, and also transcribing them
 into the Abbey's computers to preserve them digitally, should the physical books ever be destroyed. Over the long years,
 others have come across the Abbey, and some have elected to stay and live out their lives in the tranquil quiet of our mountain home.}
{440}{}{Thanks for the story.}
{441}{}{Where did your ancestors come from?}
{442}{}{They never told where they originally came from. We suspect that they came here originally from the east.}
{443}{}{Well, thanks for the story.}
{444}{}{Do you need any help here at the monastery?}
{445}{}{I found out what's wrong with your water pump.}
{446}{}{Do you know anything about the original founders?}
{447}{}{I do not know all the names of our founders, but the most important one I am aware of is Miller.
 Before the Great War he was an electrical engineer working for the United States government. Shortly thereafter,
 he converted to Catholicism and made an oath with himself that we would spend the rest of his life preserving the
 knowledge of the past. His greatest fear was that this knowledge would be lost forever and thus needed to be preserved
 so that future generations may benefit.}
{448}{}{You must be quite knowledgeable having read so much.}
{449}{}{I have indeed read much in my life. Yet you might be disappointed at the limitations of my knowledge. You see,
 we record and preserve. We are forbidden to act upon the wisdom of these books, therefore our understanding of the text is quite limited.}
{450}{}{Wait, you're telling me that you just blindly transcribe these books without even trying to comprehend them?}
{451}{}{As I've said, it is our job to preserve this knowledge, not to understand it. Before this knowledge can be
 returned to mankind, he must first prove to have risen above his tendency of mass genocide. That's the only way to
 ensure that history does not repeat itself.}
{452}{}{Well, I've got news for you: that day's never going to come. And while you're hoarding all this knowledge in your
 little mountain paradise here, people out in the wasteland are struggling every day to survive. In fact, my entire tribe
 is on the brink of destruction. The knowledge contained in these books could help cure diseases, improve crops, and greatly
 increase the chance of humanity's survival.}
{453}{}{Ah, well I suppose you make a good point. But it just seems like the information stored here could help out a lot
 of people. Even if you don't think the world's ready for this knowledge, I don't see why *you* can't at least try to learn from it.
 Otherwise, what's the point of keeping it?}
{454}{}{I understand your frustration with our ways, but you must understand that this is the way things have always been
 for us. To alter things now, after so many years... that would be blasphemous against our faith. No, I feel we must continue
 to live by the rules set by our ancestors.}
{455}{}{I understand your frustration with our ways, but you must understand that this is the way things have always been
 for us. To alter things now, after so many years... that would be blasphemous against our faith. Still, I shall consider
 your words. I sense great wisdom in you, wanderer. It is a pity I have met very few like you.}
{456}{}{Thanks. I'd like to know something else though.}
{457}{}{Very well. I'd like to know something else though.}
{500}{}{D?ng l?i!}
{501}{}{You gain 200 experience points for bringing back the book.}
{600}{}{I fixed your broken waterpump.}
{601}{}{That is great news, indeed. That waterpump had been acting up for quite some time. Those merchants said they
 could take care of it, but they didn't seem to be making much progress. It's a good thing you came along. Thank you again.}
{602}{}{I expect some money for this you know. Now cough it up!}
{603}{}{No problem. I have some other questions though.}
{604}{}{I'm glad to be of assistance. Take care.}
{605}{}{[Frowns.] I see. Fine, here, take these coins. Now go, and stop bothering me.}
{606}{}{Thank you, *father*.}
{700}{}{Uhh... no I seem to have misplaced it.}
{701}{}{What!? [He sighs deeply.] It is most unfortunate that you were unable to recover that book. But you say you've
 killed the beast? Hm, then it should be safe to send our own people down to continue searching for it. Anyway, for your
 service, I shall grant you access to our computers. Go see Brother Paul for the access key.}
{702}{}{Cám ơn.}
{800}{}{Actually, yes. Our main water pump has been acting up for some time, and now it finally seems to have broken down
 completely. If you know anything about machinery, do you think you could take a look and see if something could be done?
 There are a few merchants already working on it. I fear that little progress has been made though.}
{801}{}{I'm happy to help. I'll report back on the progress.}
{802}{}{Sure, I'll be glad to help... for a price of course.}
{803}{}{Actually on second thought, let me ask you something else.}
{804}{}{What!? Oh, fine. If that's the kind of person you are, then you shall receive payment for your service. Here's
 25 coins to begin with.  Please let me know if something can be done. [The man sighs as he hands you the coins]}
{805}{}{Hey, no need for the sighing. You think everything in life comes for free? Now, let me get to work.}
{806}{}{Really? Please, do tell.}
{807}{}{The motor gave out and fried all the connectors. I'm going to Vault City to get a new part.}
{808}{}{Oh thank you. You are indeed a great help. Please report back once you install the new part.}
{809}{}{I will. Be back soon.}
{900}{}{You explain to the Abbot that while the information they hold could lead to mankind's annihilation, it could also lead to mankind's salvation.}
{901}{}{You learn about the original founder of the Abbey.}
{1000}{}{I killie scary monster down in cave.}
{1010}{}{Really? That's great. That is very brave of you. You're a big boy.}
{1011}{}{Really? That's great. That is very brave of you. You're a big girl.}
{1012}{}{(smile) I know.}
{1020}{}{Did you happen to find a book lying there? A friend of mine had it, and he went missing.}
{1021}{}{I find book. Here, it heavy and no pitchers inside.}
{1022}{}{I no find book. Sorree. I go look now.}
{1030}{}{I find book.}
{1031}{}{That's great. Thanks. You're one special guy.}
{1032}{}{That's great. Thanks. You're one special gal.}
{1033}{}{YAY.}
{1100}{}{I was down there earlier. I saw a few dead bodies, so I'm guessing one of them belonged to your missing monk. If
 it makes you feel any better, I killed the thing responsible for his death.}
{1110}{}{Ah... so it's as I feared. Brother Thomas shall be dearly missed. You have my thanks for ridding us of whatever
 wasteland beasts lurked down there. However, I... I don't suppose you found a book while you were down there. It's a very
 important book that was last known to be in Brother Thomas's possession.}
{1111}{}{No, but I suppose I could go back and check.}
{1112}{}{Do you mean this book?}
{1113}{}{Before I go, let me ask you something else.}
{1411}{}{Very interesting. I have to go now.}
{3000}{}{Tôi giúp g? đư?c nh??}
{4091}{}{So no one else has even bothered to go down there and check on him? What if he's simply trapped down there somehow, and he's slowly starving to death?}
{4092}{}{I suppose that's possible, but you must understand. We are a peaceful people. The thought of going up against one of those wasteland monsters is terrifying to us. We're simply not equipped for such confrontations. }
{4177}{}{I've killed the beast.}
{4188}{}{Excellent! And how about the book; were you able to recover it?}
{6020}{}{If you truly want to show your gratitude, how about some money for my trouble?}
