{100}{}{Bạn thấy một thầy tu máy tính.}
{101}{}{Bạn thấy thầy Paul.}
{102}{}{Thầy tu này trông giống một con nghiện máy tính.}
{200}{}{Chào!}
{201}{}{Chào.}
{202}{}{Nào, hôm nay mình sao lưu đống dữ liệu máy tính chưa nhỉ...}
{203}{}{Thứ lỗi nhưng tôi không có thời gian cho người thông minh như cô.}
{300}{}{Vâng?}
{301}{}{Các ông có nhiều máy tính ở đây thật đấy.}
{302}{}{Bà có thể kể gì cho tôi về Tu viện?}
{303}{}{Hãy nói cho tôi biết về thầy trụ trì.}
{304}{}{Ông có thông tin gì về GECK không?}
{305}{}{Ông có biết tôi có thể tìm Vault 13 ở đâu không?}
{306}{}{Chào.}
{307}{}{Tôi đang cần một số thông tin cụ thể.}
{308}{}{Như là?}
{400}{}{Ừ, đúng vậy. Rất nhiều là đằng khác, theo như tôi biết. Biết nói sao cho tỏ cái sự chán khi phải sao lưu đống
dữ liệu này từng ngày một. Có quá nhiều thông tin để lưu trữ, nhưng dĩ nhiên là phải có người làm rồi.}
{401}{}{Hẳn rồi. Mà này, tôi có mấy câu hỏi khác.}
{402}{}{Chúng tôi là một cộng đồng độc lập. Ai cũng được chào đón ở đây miễn là biết giữ ý.}
{403}{}{Ok.}
{404}{}{Thầy trụ trì là một người lãnh đạo giáo phái tốt, nhưng thầy trở nên hơi cáu kỉnh sau khi thầy Thomas bị con quái vật làm hại.}
{405}{}{Loại quái vật nào vậy?}
{406}{}{Tôi chưa tự mình nhìn thấy – có cho gì đi chăng nữa thì tôi cũng sẽ không đi xuống chỗ đó để lọ mọ dưới
cái hang đâu – nhưng nếu tôi không nhầm thì chắc là mấy con bò cạp quá khổ thôi.}
{407}{}{Nếu chưa nhìn thấy thì sao ông lại nghĩ đấy là bò cạp?}
{408}{}{Bởi vì tôi có nghe thấy tiếng vọng trong hang – tiếng càng kẹp và tiếng chân bò sột soạt.}
{409}{}{Chắc vậy.}
{410}{}{Có chứ. Hãy xem trong cái máy tính đằng kia. Đây, dùng cái thẻ này để truy cập các tệp tin mã hóa của chúng tôi [Ông ta đưa cho bạn một cái thẻ truy cập].}
{411}{}{Ồ, cám ơn nhiều!}
{412}{}{Tôi không biết gì về Vault 13, nhưng có một Thành phố Vault ở phía Nam. Có thể họ có thông tin mà cô cần.}
{413}{}{Cám ơn.}
{414}{}{Cái máy tính bên cạnh tôi chắc là có thông tin mà cô đang tìm, nhưng cô cần có thẻ truy cập để sử dụng.
Chúng tôi lựa chọn người có thể truy cập rất kĩ, nhưng nếu cậu nói chuyện với Thầy trụ trì thì có thể thầy sẽ cấp quyền cho cô.}
{415}{}{Ồ, cám ơn.}
{420}{}{Chắc là ông đọc nhiều sách trong lúc rảnh lắm. Tôi tự hỏi điều thú vị nhất mà ông có thể kể cho tôi là gì?}
{421}{}{Hừm, để xem nào. Cô có biết là một vết nứt trên thân cây sẽ luôn duy trì cùng cự ly so với mặt đất khi cái cây mọc cao thêm?}
{422}{}{Chắc rồi. Nếu tôi gặp thứ gì như vậy thì chắc chắn tôi sẽ báo cho ông biết.}
{423}{}{Vậy à... Ồ, tôi có mấy câu hỏi khác.}
{424}{}{Thật chứ? Tôi sẽ rất biết ơn đấy.}
{425}{}{Không vấn đề gì. Tôi có mấy câu hỏi khác.}
{426}{}{Cứ vậy đi. Ồ, gặp lại sau.}
{430}{}{Tôi tìm thấy một số thông tin về Thực vật mà ông có thể quan tâm.}
{431}{}{Thật ư?! Tuyệt vời. Làm ơn hãy nói cho tôi ngay.}
{432}{}{Tuyệt cú mèo! Tôi sẽ lấy cái holodisk này cho thêm vào cơ sở dữ liệu trong máy tính ngay đây. Tôi rất cảm kích
việc cô dành thời gian đi tìm. Cám ơn cô đã thu thập thứ này cho tôi.}
{433}{}{Ồ xem nào... Việc hiểu về sự phá hủy môi trường và tuyệt chủng giống loài phụ thuộc vào độ chính xác và hoàn thiện của việc phân loại và lập hệ thống thực vật. Điều này có nghĩa là...}
{434}{}{Cứ vậy đi. Tôi vẫn còn mấy câu hỏi nữa.}
{435}{}{Không vấn đề gì. Gặp lại sau.}
{436}{}{Tuyệt cú mèo! Tôi rất cảm kích việc cô dành thời gian đi tìm thứ này cho tôi. Vui lòng đi tải thông tin này vào máy tính của chúng tôi.}
{437}{}{Không vấn đề gì. Tôi đi làm giờ đây. Gặp lại sau.}
{500}{}{Dừng lại, đồ chết tiệt!}
{550}{}{Cái máy tính cạnh tôi đây chắc là có thông tin đấy. Giờ cô có quyền truy cập rồi nên tự tìm đi.}
{600}{}{Thầy trụ trì đã cấp cho tôi quyền truy cập máy tính ở đây.}
{601}{}{À đúng rồi, tôi có nghe về việc cô đã làm. Cám ơn đã giải quyết chuyện đó. Đây là khóa truy cập (Ông ta đưa khóa cho bạn). Xem vui nhé!}
{602}{}{Cám ơn. Gặp lại sau.}
{650}{}{Chào mừng, người lữ khách! Tôi là Thầy Paul và tôi là người lo việc thu thập thông tin cho Tu viện. Tôi có thể giúp gì được đây?}
{651}{}{Rất vui được gặp ông, Paul. Tôi có vài câu hỏi.}
{652}{}{Không có gì. Gặp lại ông sau.}
{4210}{}{Ừ, không, tôi không biết. Chuyện đó... hay đấy.}
{4211}{}{Và cô có biết rằng 96% dưa chuột là nước?}
{4212}{}{Ồ, 96% à? Hấp dẫn đấy, Nhưng, ừm, dưa chuột là cái gì vậy?}
{4213}{}{Tôi chưa nhìn thấy lần nào, nhưng tôi có đọc rồi [Ông ta lo lắng liếc quanh rồi hạ giọng]. Tôi biết là chúng tôi không
được phép nghiên cứu sách ở đây, nhưng trong lúc chép lại một cuốn về thực vật, tôi hoàn toàn bị cuốn hút vào đó.
Thế giới thực vật đơn giản là cực kì thú vị. Có thể, trong hành trình của mình, nếu cô tình cờ có được thông tin về loài
thực vật nào đó thì cô mang đến cho tôi được không? Tôi sẽ rất cảm kích đấy. Dĩ nhiên đây là bí mật giữa chúng ta thôi.}
{4220}{}{Tôi không nghĩ là mình muốn góp phần vào cái thói ham cây của ông. Xin lỗi.}
{4221}{}{Ồ, được thôi. Rồi, quên điều tôi vừa nói đi.}
{4222}{}{Để tôi hỏi chuyện khác.}
