{100}{}{Bạn thấy một thầy tu máy tính.}
{101}{}{Bạn thấy thầy Paul.}
{102}{}{Thầy tu này trông giống một con nghiện máy tính.}
{200}{}{Chào!}
{201}{}{Chào.}
{202}{}{Nào, hôm nay mình sao lưu đống dữ liệu máy tính chưa nhỉ...}
{203}{}{Thứ lỗi nhưng tôi không có thời gian cho người thông minh như cô.}
{300}{}{Vâng?}
{301}{}{Các ông có nhiều máy tính ở đây thật đấy.}
{302}{}{Bà có thể kể gì cho tôi về Tu viện?}
{303}{}{Hãy nói cho tôi biết về thầy trụ trì.}
{304}{}{Ông có thông tin gì về GECK không?}
{305}{}{Ông có biết tôi có thể tìm Vault 13 ở đâu không?}
{306}{}{Chào.}
{307}{}{Tôi đang cần một số thông tin cụ thể.}
{308}{}{Như là?}
{400}{}{Ừ, đúng vậy. Rất nhiều là đằng khác, theo như tôi biết. Biết nói sao cho tỏ cái sự chán khi phải sao lưu đống
dữ liệu này từng ngày một. Có quá nhiều thông tin để lưu trữ, nhưng dĩ nhiên là phải có người làm rồi.}
{401}{}{Hẳn rồi. Mà này, tôi có mấy câu hỏi khác.}
{402}{}{Chúng tôi là một cộng đồng độc lập. Ai cũng được chào đón ở đây miễn là biết giữ ý.}
{403}{}{Ok.}
{404}{}{Thầy trụ trì là một người lãnh đạo giáo phái tốt, nhưng thầy trở nên hơi cáu kỉnh sau khi thầy Thomas bị con quái vật làm hại.}
{405}{}{Loại quái vật nào vậy?}
{406}{}{Tôi chưa tự mình nhìn thấy – có cho gì đi chăng nữa thì tôi cũng sẽ không đi xuống chỗ đó để lọ mọ dưới
cái hang đâu – nhưng nếu tôi không nhầm thì chắc là mấy con bò cạp quá khổ thôi.}
{407}{}{Nếu chưa nhìn thấy thì sao ông lại nghĩ đấy là bò cạp?}
{408}{}{Bởi vì tôi có nghe thấy tiếng vọng trong hang – tiếng càng kẹp và tiếng chân bò sột soạt.}
{409}{}{Chắc vậy.}
{410}{}{Có chứ. Hãy xem trong cái máy tính đằng kia. Đây, dùng cái thẻ này để truy cập các tệp tin mã hóa của chúng tôi [Ông ta đưa cho bạn một cái thẻ truy cập].}
{411}{}{Ồ, cám ơn nhiều!}
{412}{}{Tôi không biết gì về Vault 13, nhưng có một Thành phố Vault ở phía Nam. Có thể họ có thông tin mà cô cần.}
{413}{}{Cám ơn.}
{414}{}{Cái máy tính bên cạnh tôi chắc là có thông tin mà cô đang tìm, nhưng cô cần có thẻ truy cập để sử dụng.
Chúng tôi lựa chọn người có thể truy cập rất kĩ, nhưng nếu cậu nói chuyện với Thầy trụ trì thì có thể thầy sẽ cấp quyền cho cô.}
{415}{}{Ồ, cám ơn.}
{420}{}{Chắc là ông đọc nhiều sách trong lúc rảnh lắm. Tôi tự hỏi điều thú vị nhất mà ông có thể kể cho tôi là gì?}
{421}{}{Hmm, let's see. Did you know a notch in a tree will remain the same distance from the ground as the tree grows?}
{422}{}{Sure. If I come across anything like that, I'll be sure to let you know.}
{423}{}{Right... Well, I have some other questions.}
{424}{}{Would you? I'd appreciate that.}
{425}{}{No problem. I have some other questions.}
{426}{}{Any time. Well, see you around.}
{430}{}{I found some information about Botany that might interest you.}
{431}{}{Really?! That's great. Please, do tell immediately.}
{432}{}{Fascinating! I shall take this holodisk and add it to the computer database immediately. I appreciate you
 taking the time to find this for me. Thank you for collecting this for me.}
{433}{}{Well you see... Understanding habitat destruction and species extinction is dependent on an accurate and complete catalog of plant systematics and taxonomy. And then this means that...}
{434}{}{Any time. I have some other questions though.}
{435}{}{No problem. See you around.}
{436}{}{Fascinating! I appreciate you taking the time to find this for me. Please go and upload this information to our computers.}
{437}{}{No problem, I'll do that now. See you around.}
{500}{}{Stop that, moron!}
{550}{}{That computer near me should have some information about it. You now have access, so take a look for yourself.}
{600}{}{The Abbot gave me permission to access the computers here.}
{601}{}{Ah yes, I heard about what you did. Thanks for taking care of that situation. Here is the access key. (He hands you the key.) Enjoy!}
{602}{}{Thanks. See you around.}
{650}{}{Greetings traveler! I am Brother Paul and I am in charge of the collection of information for the Abbey. What can I do for you?}
{651}{}{Nice to meet you, Paul. I have some questions.}
{652}{}{Không có gì. Gặp lại ông sau.}
{4210}{}{Uh, no, I can't say I knew that. That's... interesting.}
{4211}{}{And did you know a cucumber is 96% water?}
{4212}{}{Wow, 96%, huh? Fascinating. But, um, what's a cucumber?}
{4213}{}{I've never seen one, but I've read about them. [He looks around nervously and lowers his voice.] I know we're
 not supposed to actually study these books, but when I was transcribing a book on botany, I just couldn't help but get
 sucked into it. The world of plants is simply captivating. Perhaps, if, during your travels, you happen upon some botany
 information, you could bring it to me? I'd be most grateful. Of course, it'd have to be our secret.}
{4220}{}{I don't think I want to contribute to your plant obsession. Sorry.}
{4221}{}{Oh, well then. Fine, forget I asked.}
{4222}{}{Để tôi hỏi chuyện khác.}
