{100}{}{Bạn thấy một người đàn ông lùn đang cầm sách trong tay.}
{101}{}{Bạn thấy Bác sĩ Jones, thầy thuốc.}
{102}{}{Bạn thấy một người đàn ông lùn với quyển sách có tên "Vậy là bạn muốn làm Bác sĩ".}
{103}{}{Chào, tôi là Bác sĩ Jones. Hãy gọi tôi là bác sĩ. Tôi giúp gì được nhỉ?}
{104}{}{Bị đao. Sửa không?}
{105}{}{Bị ngứa. Sửa không?}
{106}{}{Ngộ què, sửa không?}
{107}{}{Muốn hỏi. Okay?}
{108}{}{Xin lỗi, ngộ đi.}
{109}{}{Tôi bị thương. Ông giúp tôi được không?}
{110}{}{Tôi thấy bị bệnh. Ông giúp tôi được không?}
{111}{}{Tôi bị gãy tay chân. Ông giúp tôi được không?}
{112}{}{Tôi muốn hỏi một vài câu.}
{113}{}{Chỉ chào thôi.}
{114}{}{Ồ, dĩ nhiên rồi. Đây, tôi sẽ tiêm cho cô mũi này -- sẽ hơi xót một xíu -- giờ thì dán cái
băng này, rồi xong, cậu ổn rồi.}
{115}{}{Ngộ cám ơn. Tạm biệt.}
{116}{}{Cám ơn, Bác sĩ. Tôi thấy khá hơn nhiều rồi.}
{117}{}{Ồ, dĩ nhiên rồi. Đây, cô sẽ cần uống thứ này -- tất cả chứ, tôi biết vị hơi tởm. Rồi, giờ
thì nằm lên chiếc giường đằng kia, sáng mai tôi sẽ đánh thức cô.}
{118}{}{Ngộ thấy ổn. Tạm biệt.}
{119}{}{Cám ơn Bác sĩ, chữa tài thật đấy.}
{120}{}{Tôi rất tiếc nhưng tôi không có đủ thiết bị cần thiết để tiến hành phẫu thuật. Tôi khuyên cô nên
đi tới một thành phố lớn và gặp bác sĩ phẫu thuật. Thử Thành phố Vault xem. Đi về phía Bắc chỗ này.}
{121}{}{Okay. Tạm biệt.}
{122}{}{Được rồi. Dù sao cũng cám ơn.}
{123}{}{Muốn hỏi gì thế?}
{124}{}{Ông làm Darion?}
{125}{}{Ông đi đây nếu muốn?}
{126}{}{Ông biết gì về Darion?}
{127}{}{Sao ông ở đây?}
{128}{}{Ông bảo Darion có chóa?}
{129}{}{Ngộ đi giờ.}
{130}{}{Ông có làm việc cho Darion không?}
{131}{}{Ông có thể rời khỏi chỗ này nếu muốn không?}
{132}{}{Ông có thể nói về Darion được không?}
{133}{}{Sao ông lại đến chỗ này vậy?}
{134}{}{Ông nói rằng Darion có một con chó à?}
{135}{}{Cám ơn về thông tin. Tôi đi ra ngoài giờ đây.}
{136}{}{Ồ, vừa có vừa không. Tôi không tự nguyện mà bị bắt phải ở đây. Darion đã ở đây nhiều năm và
cần một bác sĩ riêng để chăm sóc sức khỏe. Đám Khan giữ tôi ở đây để lo cho hắn. Bản thân tôi
thà chăm sóc cho những người ở khu trại còn hơn. Họ chẳng có ai chăm sóc y tế cả, còn tôi thì
có thể giúp họ được nhiều thứ.}
{137}{}{Okay. Cần biết thêm.}
{138}{}{Cám ơn. Tạm biệt.}
{139}{}{Ồ, ông đáng khen đấy chứ.}
{140}{}{Hiểu rồi. Tôi sẽ đi giờ đây.}
{141}{}{Đấy là đám ở mượn thôi mà! Kệ chúng chết đi. Hãy lo cho cuộc sống của ông chứ.}
{142}{}{Không, tôi gần như bị giam ở đây. Tôi thậm chí còn không thể đi lấy vật tư y tế được. Darion
cử người đi lấy mọi thứ tôi cần.}
{143}{}{Ngộ hiểu. Đi giờ.}
{144}{}{Cần hỏi thêm.}
{145}{}{Tôi chắc là ông không phải là người đáng tin để được thả tự do.}
{146}{}{Được rồi. Rất tiếc nhưng tôi phải đi đây.}
{147}{}{Rất tiếc khi nghe điều đó.}
{148}{}{Darion đơn giản là có vấn đề về thần kinh. Hắn ta có nhiều sạn trong đầu còn hơn cả số rận trên
con chó kìa. Theo như tôi đoán thì hắn là thành viên của một băng tên là Khan. Chúng bắt cóc một
phụ nữ tên là Tandi và giam giữ cô ta để đòi tiền chuộc. Cha cô gái không muốn giải quyết hòa bình và
thuê mấy tay thợ săn để cứu con gái về. Darion là kẻ sống sót duy nhất.}
{149}{}{Ừ... như ông nói.}
{150}{}{Phải đi giờ.}
{151}{}{Uh-huh. Ồ, tôi phải đi giờ.}
{152}{}{Ồ, tôi thấy ấn tượng với kiến thức của ông đấy.}
{153}{}{Nghe giống bạn tôi đấy.}
{154}{}{Tôi đã bị bắt cóc. Lúc đó tôi đang đi từ Thành phố Vault đến New Reno trong một kì nghỉ dài. Một đêm
tôi lên giường nằm và sáng hôm sau tỉnh giấc, thấy tay chân bị trói và nhét giẻ vào mồm. Sau khoảng một
tuần, tôi ở đây. Từ đó đến giờ tôi chỉ ở đây.}
{155}{}{Ờ.}
{156}{}{Cám ơn. Ngộ đi giờ.}
{157}{}{Kẻ mạnh ăn thịt kẻ yếu thôi.}
{158}{}{Rất tiếc khi nghe điều đó.}
{159}{}{Hay đấy, nhưng tôi phải đi đây.}
{160}{}{Ừ, hắn ta có một con chó. Bản thân tôi nghĩ rằng đấy là con vật dữ dằn, độc ác nhất trên
quả đất. Nhưng mà nó có vẻ yêu Darion, nên là có thể không tệ đến vậy.}
{161}{}{Ngộ hỏi thêm.}
{162}{}{Ừ, tạm biệt.}
{163}{}{Hiểu rồi. Ồ, cám ơn đã cảnh báo.}
{164}{}{À. Ồ, tôi cần đi đây.}
{165}{}{Tôi sẽ không giúp người như cậu đâu. Đi chỗ khác đi.}
{166}{}{Okay, ồ, nhớ giữ gìn nhé, và quay lại nếu cần gì đó.}
{167}{}{Đã xong.}
{168}{}{Giờ thì hắn ta bị hoang tưởng. Hắn tin rằng Tandi đến để bắt hắn. Hắn ta bị ám ảnh với việc trả thù,
và hắn muốn Tandi phải chết. Hắn luôn cảm thấy tội lỗi vì đã lẩn trốn và sống sót, thay vì chết cùng
với băng nhóm... mấy chuyện như vậy.}
{200}{}{Darion chết rồi.}
{201}{}{Dar-e-on chết.}
{202}{}{Thật à!? Ồ, đúng là tin mừng.}
{203}{}{Từ giờ ông sẽ làm gì?}
{204}{}{Ôn làm gì?}
{205}{}{Ồ, tôi không thấy có lí do gì để quay lại cuộc sống trước kia. Khu trại ở trên mặt đất không có trợ giúp y tế nào, nên
tôi nghĩ rằng mình sẽ lên đó giúp họ. Cám ơn đã giải thoát tôi.}
{206}{}{Dĩ nhiên rồi. Gặp lại sau.}
{207}{}{Chào!}
{210}{}{Tôi vẫn còn cần phải gói ghém vài thứ. Gặp lại bên ngoài sau.}
{220}{}{Ầy chào, rất vui được gặp lại! Mọi người ở đây đều cảm kích trước những gì cậu đã làm. Bản thân tôi thấy rất vui
khi thoát được khỏi nơi đó. Làm việc cho Darion đúng là cơn ác mộng.}
{221}{}{Rất vui vì tôi đã giúp được. Giờ thì nói về bản thân ông một chút đi.}
{222}{}{Được rồi, gặp lại sau.}
{230}{}{Ồ cậu thấy đấy, tôi xuất thân từ Cộng hòa New California, nhưng tôi nhận thấy rằng mình có thiên bẩm về ngành y.
Vì vậy tôi đã trau dồi hết mức có thể với đội ngũ y tế của NCR, và sau khi học hết tất cả tôi quyết định thử đi học hỏi
thêm bằng cách đi đến Thành phố Vault. Tôi rất may mắn gặp được Bác sĩ Troy trong lúc ông ta đang chữa trị cho một
cư dân bị thương bên ngoài vault, và nói ngắn gọn thì ông ta đồng ý cho tôi thực tập ở Thành phố Vault. Tôi vừa mới
hoàn thiện quá trình thực tập và đi ra ngoài nhưng lại bị Darion túm cổ.}
{231}{}{That's terrible. Well, I hope everything works out for you now.}
{240}{}{I hope so too. I think I can put my medical skills to good use here.}
{241}{}{Chào.}
{250}{}{Thanks again for everything.}
{251}{}{It feels good to be helping civilized people again.}
