{100}{}{Bạn thấy một đầu bếp.}
{101}{}{Bạn thấy Cookie, đầu bếp.}
{102}{}{Bạn thấy một người mặc giáp đội mũ đầu bếp và quàng tạp dề.}
{103}{}{Này cậu lính. Cậu đang kiếm đồ bỏ mồm hay muốn nói chuyện thế?}
{104}{}{Ngộ muốn ăn.}
{105}{}{Ngộ muốn chuyện.}
{106}{}{Tôi muốn ăn món gì đó.}
{107}{}{Hãy nói chuyện một lát.}
{108}{}{Ồ, đây. Cứt bôi trên gạch ngói. Tuyết và cứt ruồi ở đằng kia. Gì nữa không?}
{109}{}{Ông muốn ngộ ăn gì?}
{110}{}{Cứt? Tuyết? Đây là món lìn gì thế?}
{111}{}{Tôi xin lỗi, chắc hẳn cậu là lính mới. Tôi không có ý chửi bới gì đâu, ở đây chúng tôi gọi đồ ăn như vậy.
Cứt bôi trên gạch ngói là bò thái miếng trên đĩa nướng. Tuyết và cứt ruồi là tên khác của muối và tiêu.}
{112}{}{Ồ... cám ơn. Chúng ta nói chuyện khi ăn.}
{113}{}{Được rồi, xin lỗi. Hãy nói chuyện trong lúc tôi ăn.}
{114}{}{Muốn nói chuyện gì nào?}
{115}{}{Có chuyện gì thế?}
{116}{}{Bản vẽ máy bay ở đâu?}
{118}{}{Căn cứ chính ở đâu?}
{119}{}{Ngộ cần quay lại nhiệm vụ. Cám ơn.}
{120}{}{Chuyện gì đang diễn ra ở đây thế?}
{121}{}{Tôi đang quan tâm tới cái máy bay trực thăng. Nếu muốn xem bản vẽ thì tôi có thể tìm ở đâu nhỉ?}
{123}{}{Căn cứ chính của Enclave nằm ở đâu thế?}
{124}{}{Cám ơn. Tôi cần phải quay về chỗ trực đây.}
{125}{}{Muốn nghe tin gậm giường không? Tôi có thể nói cho cậu về chuyện mới nhất ở phòng bảo trì, phòng thí nghiệm hoặc của đám lính.}
{126}{}{Muốn nghe chuyện gì nào?}
{127}{}{Phòng bảo trì thì sao?}
{128}{}{Phòng thí nghiệm thì sao?}
{129}{}{Đám lính thì sao?}
{130}{}{Gì nữa không?}
{131}{}{Ngộ nghe đủ rồi.}
{132}{}{Phòng bảo trì có chuyện gì thế?}
{133}{}{Ông có tin gì về phòng thí nghiệm không?}
{134}{}{Đám lính có gì hay ho không?}
{135}{}{Có chuyện gì nữa không?}
{136}{}{Tôi nghĩ là mình nghe đủ rồi.}
{137}{}{Raul, thợ cơ khí máy bay trực thăng không thích Quincy, trưởng phòng bảo trì. Hai người bọn họ
lúc nào cũng hục hặc nhau. Tôi không nghĩ đấy là do nghề nghiệp. Dù sao thì Raul là một gã kiêu ngạo
còn Quincy thì khá ổn. Tôi hi vọng là ông ta cuối cùng sẽ thắng.}
{138}{}{Okay.}
{139}{}{Ờ, chắc vậy.}
{140}{}{Phòng thí nghiệm do một lão hói từ Enclave tên là Schreber nắm quyền. Đm cái loại sống chó; đéo quan tâm
đến ai hoặc gì hết cả. Lão đang làm thí nghiệm gì đó trên deathclaw ở dưới đó, nhưng tôi không biết là làm gì.
Dù sao thì lão ta cũng gây ra đủ loại tiếng động cho đến khi chỉ huy ra lệnh ốp cách âm cả căn phòng đó.}
{141}{}{Hiểu rồi.}
{142}{}{Hay đấy.}
{143}{}{Ha! Đến phần ái tình rồi, cô bạn. Có vẻ như một con nghiện máy tính đã yêu một cô lính gác ở phía ngoài phòng thí nghiệm. Thậm chí còn đặt tên tình củm cho cô ta nữa, gọi là "Snookie" mới hài chứ.}
{144}{}{Đáng yêu đấy.}
{145}{}{Nà, hết chuyện ở đây rồi. Nếu nghe thêm được gì tôi sẽ nói thêm sau. Tôi thích kể lại những gì mà tôi nghe được!}
{146}{}{Cám ơn.}
{147}{}{Sao cô lại quan tâm đến thứ đó? Ồ mà chả sao. Quincy giữ chúng trong phòng bảo trì, tôi nghĩ thế.}
{148}{}{Okay.}
{149}{}{Đâu vậy?}
{150}{}{Hiểu rồi.}
{151}{}{Ở chỗ nào thế?}
{152}{}{Góc phía Đông Bắc của căn cứ, bạn tôi à. Đến là thấy.}
{153}{}{Okay. Cám ơn.}
{156}{}{Tôi thấy lạ là cậu lại không biết đấy, chắc cậu là dân địa phương. Còn căn cứ chính thì nằm ở chính con mẹ nó
giữa biển. Ồ, không hẳn là giữa lỗ đít lắm, nhưng cũng gần như vậy. Cách duy nhất để đến đó là bằng tàu hoặc
máy bay nhưng con tàu chết tiệt đã bị sửa đổi rồi. Cần một cái thẻ fob để vận hành mớ sắt vụn đấy.}
{157}{}{Fob?}
{158}{}{Yeah, a passkey. Commander keeps it in his office. Without it ya can't access some areas of the ship and that
 keeps the locals down in San Fran from paying an unwelcome visit.}
{159}{}{Good idea.}
{160}{}{Where commander office?}
{161}{}{That's a good idea.}
{162}{}{So where's the commander's office?}
{163}{}{Take the elevator in the next room down, follow the hallway to the main junction, and go straight. }
{164}{}{Cám ơn.}
{165}{}{Hey, soldier. Good to hear from you again. Grub or talk this time?}
{166}{}{Food.}
{167}{}{Chitchat.}
{168}{}{Me just say hi.}
{169}{}{Neither, I'm just saying hi.}
{170}{}{Here ya go. It's dead, it's cooked, it's unidentifiable. Enjoy.}
{171}{}{Uh... Thanks.}
{172}{}{Son, I can tell from the smell that you're not wearin' one of them powered armor suits.
 If the Sarge sees you out of uniform you're screwed. And I ain't talking the type of screwing that feels good. Now get your ass down to supply and suit up.}
{173}{}{Little lady, I can tell from the smell that you're not wearin' one of them powered armor suits.
 If the Sarge sees you out of uniform you're screwed. And I ain't talking the type of screwing that feels good. Now get your ass down to supply and suit up.}
{174}{}{Đâu vậy?}
{175}{}{Okay.}
{176}{}{Ở chỗ nào thế?}
{177}{}{I'll take care of it.}
{178}{}{Take the elevator in the next room down, follow the hall to the main junction, turn left, and it's the first door on your left. Off you go.}
{179}{}{Cám ơn.}
{180}{}{Holy shit! I'm just a cook... and a blind one at that. I didn't see any intruders come through here.}
{181}{}{Cám ơn.}
{182}{}{Damned alarms. Always such a ruckus when they go off.}
{183}{}{What the hell is that damn thing going on about this time?}
{184}{}{I wish to hell we'd use silent alarms, damn thing gives me a headache.}
{185}{}{I'm gonna fry your ass up and serve it on a plate.}
{186}{}{Your goose is cooked. Ha! I made a funny!}
{187}{}{Out of the frying pan and into the fire.}
