{100}{}{Bạn thấy một lính gác.}
{101}{}{Bạn thấy một lính gác mặc power armor.}
{102}{}{Bạn thấy một người mặc power armor có thiết kế khác lạ. Có miếng phù hiệu trên tấm giáp ngực mà bạn không nhận ra.}
{103}{}{Không có gì mới.}
{104}{}{Tôi không thấy có gì mới, cô thì sao?}
{105}{}{Này cậu lính, sao cậu không về vị trí gác đi? Đừng có đi lang thang ở đây.}
{106}{}{Cô đang không mặc quân phục.}
{107}{}{Tốt hơn hết là đến chỗ Trung sĩ báo cáo rồi đi nhận quân phục đi.}
{108}{}{Cậu to gan lắm mới đi lại mà không mặc quân phục đấy. Tốt nhất là nên đi báo lại cho hậu cần đi.}
{109}{}{Chúng mày là thế đéo nào... Báo động! Có kẻ xâm nhập!}
{110}{}{Chúng ta đã bị xâm nhập! Báo động!}
{111}{}{Có nhiều kẻ đột nhập! Rung chuông báo động lên!}
{112}{}{Cảnh báo an ninh! Khóa căn cứ!}
{113}{}{Bảo vệ toàn bộ căn cứ! Chúng ta đang báo động!}
{114}{}{Báo động có kẻ đột nhập! Vào mã đỏ!}
{115}{}{Chúng tao sẽ cho mày cạp đất!}
{116}{}{Enclave sẽ thống trị cả thế giới!}
{117}{}{Mày phải chết để Enclave tồn tại!}
{200}{}{...đồ chết tiệt...}
{201}{}{...đúng rồi, TỐT HƠN HẾT là mày nên bước đi...}
{202}{}{...con chó này đen thế...}
{203}{}{...vâng, thưa ngài! đcm ngài!...}
{300}{}{Chờ đã. Cô đang làm cái quái gì với chiếc máy bay thế? Làm gì có lịch bay nào trong mấy ngày tới.}
{301}{}{Nrg?}
{302}{}{Tôi biết.}
{303}{}{Tôi xin lỗi. Tôi chỉ xem thôi. Đi giờ đây.}
{304}{}{Kế hoạch đã thay đổi. Tôi sẽ lấy chiếc máy bay này.}
{310}{}{Cái gì? Ồ, hiểu rồi. Này, đừng có động vào. Được chứ? Động vào lần nữa là chết đấy.}
{311}{}{(Cười rồi tấn công).}
{312}{}{(Đi khỏi).}
{315}{}{Ồ cứt thật, có vẻ như chúng ta bị đột nhập rồi. Mã đỏ! Nhắc lại, mã Đỏ!}
{316}{}{Nghe hay đấy. Động vào cái máy bay lần nữa và tôi sẽ nhồi chì vào đầu cô.}
{320}{}{Rồi. Và cô là...}
{321}{}{Chuẩn bị đi đây. Xin lỗi đã làm phiền.}
{322}{}{Chuẩn bị đi gửi tin quan trọng về căn cứ chính.}
{323}{}{Ồ thật ư? Và tin này về việc gì thế.}
{324}{}{Đây là siêu bí mật. Tôi không thể nói được.}
{325}{}{Tôi sẽ nói cho anh, nhưng phải tuyệt đối bảo đảm không được tiết lộ thông tin này cho bất kì ai khác vì có thể
sẽ dẫn đến đại hoảng loạn. Biết gì không? Tôi nhận thấy một trong số chuyến hàng nô lệ gần đây đã bị nhiễm một loại 
virus không xác định và cực kì nguy hiểm. Tôi *phải* đi đến căn cứ ngay, nếu không tất cả chúng ta sẽ tiêu đời. Giờ thì 
đừng có làm lãng phí thời gian nữa vì không thể chờ được nữa đâu.}
{326}{}{Được, tôi tin cô. Có vẻ như chúng ta có kẻ đột nhập...}
{327}{}{Mẹ nó chứ! À, sao cũng được. Chẳng ai nói cái cứt gì cho tôi cả. Rồi. Đi đi.}
{328}{}{Ồ, nghe tệ thật đấy. Vậy thì cô nên lên đường đi, tôi không muốn dính phải cứt đâu. Ồ và đừng lo, tôi sẽ không nói với ai đâu.}
{329}{}{[XONG]}
{400}{}{[Sau khoảng nửa giờ ngồi trong khoang chứa tối tăm, bạn nhận thấy chiếc máy bay đã chạm đất. Một thoáng sau,
cửa khoang chứa mở ra và bạn thấy một nhóm lính mặc power armor. Một người trong số này nhìn lại bạn rồi quay sang 
những người khác] Cái đm! Một trong số lũ thổ dân đột biến đu càng trực thăng này! BÁO ĐỘNG! Chúng ta bị đột nhập!}
{401}{}{[Sau khoảng nửa giờ ngồi trong khoang chứa tối tăm, bạn nhận thấy chiếc máy bay đã chạm đất. Một thoáng sau,
cửa khoang chứa mở ra và bạn thấy một nhóm lính mặc power armor. Một người trong số này nhìn lại bạn rồi quay sang 
những người khác] Cái đm! Mấy đứa thổ dân đột biến bám càng trực thăng này! BÁO ĐỘNG! Chúng ta bị đột nhập!}
{402}{}{[Nhảy ra và xem bạn có thể tiêu diệt bao nhiêu tên trước khi chúng thịt bạn].}
{403}{}{[Giơ hai tay đầu hàng và hi vọng sẽ được sống].}
{410}{}{Ai dà, có vẻ như tay đột biến này không dám đấu. Có lẽ chúng ta nên dẫn hắn ta đến chỗ Chỉ huy -- xem ông ta 
muốn xử lí việc này thế nào.}
{411}{}{Ai dà, có vẻ như tay đột biến này không dám đấu. Có lẽ chúng ta nên dẫn cô ta đến chỗ Chỉ huy -- xem ông ta 
muốn xử lí việc này thế nào.}
{412}{}{Ai dà, có vẻ như lũ đột biến này không dám đấu. Có lẽ chúng ta nên dẫn chúng đến chỗ Chỉ huy -- xem ông ta muốn
xử lí việc này thế nào.}
{420}{}{[Sau khoảng nửa giờ ngồi trong khoang chứa tối tăm, bạn nhận thấy chiếc máy bay đã chạm đất. Một thoáng sau,
cửa khoang chứa mở ra và bạn thấy một nhóm lính Enclave. Một người trong số họ nhìn lại bạn] Mày làm cái lìn gì ở trong đó
thế? Mày làm gì có quyền đi làm nhiệm vụ đó. Tên mày là gì, đồ lính?}
{421}{}{Tên gì không quan trọng, vì tôi không đến đây để nói chuyện [Nhảy ra và bắt đầu chiến đấu].}
{422}{}{Tôi? Ồ, tôi, ừ *ho khan*lẩm bẩm*ho khan*. Đừng để ý đến tôi. Mà thực tế là giờ tôi phải đi đây [Chui ra và 
cố bước đi một cách tự nhiên].}
{423}{}{Tên tôi là }
{424}{}{. Tôi đang ở đâu thế?}
{425}{}{Không, tên *cậu* là gì, cậu lính? Tôi ở đây để thử thách cậu và tôi phải nói là cậu đã THẤT BẠI rồi. Nếu tôi là
một sát thủ hoang mạc liều chết thì cậu và cả lũ các cậu giờ đã toi rồi! Không thể chấp nhận được! Cẩn trọng vào, lũ lính!}
{426}{}{Ừ... tên tôi }
{427}{}{. Tôi thích cưỡi chim sắt đi chơi! Bay lại đi! Đi tiếp lần nữa!}
{428}{}{Mày không cần biết tên. Ngộ không thích mày. Ngộ giết [Nhảy ra và bắt đầu chiến đấu].}
{430}{}{Cô làm sao thế, say à? Cô đang ở Navarro chứ đâu nữa. Nếu đầu óc có vấn đề thì cô nên đi khám sức khỏe đi. Có thể cô đã bị nhiễm phóng xạ ngoài đó rồi.}
{440}{}{Don't give me that bullshit. You're one of the new recruits, aren't you? Heh. That smart mouth of yours is gonna land you in all sorts of trouble--and I can't wait to see it happen. Now get back to your post, soldier.}
{450}{}{Sir! Yes sir!}
{451}{}{Ma'am! Yes ma'am!}
{460}{}{[The soldier looks at one of his comrades.] My God, contact with all the muties and radiation out there must have made him retarded. You see? *That's* why I never volunteer for those wasteland runs. Anyway, let's put this stupid bastard out of his misery before he contaminates us.}
{461}{}{[The soldier looks at one of his comrades.] My God, contact with all the muties and radiation out there must have made her retarded. You see? *That's* why I never volunteer for those wasteland runs. Anyway, let's put this stupid bitch out of her misery before she contaminates us.}
