{100}{}{Bạn thấy một lính gác.}
{101}{}{Bạn thấy một lính gác mặc power armor.}
{102}{}{Bạn thấy một người mặc power armor có thiết kế khác lạ. Có miếng phù hiệu trên tấm giáp ngực mà bạn không nhận ra.}
{103}{}{Không có gì mới.}
{104}{}{Tôi không thấy có gì mới, cô thì sao?}
{105}{}{Này cậu lính, sao cậu không về vị trí gác đi? Đừng có đi lang thang ở đây.}
{106}{}{Cô đang không mặc quân phục.}
{107}{}{Tốt hơn hết là đến chỗ Trung sĩ báo cáo rồi đi nhận quân phục đi.}
{108}{}{Cậu to gan lắm mới đi lại mà không mặc quân phục đấy. Tốt nhất là nên đi báo lại cho hậu cần đi.}
{109}{}{Chúng mày là thế đéo nào... Báo động! Có kẻ xâm nhập!}
{110}{}{Chúng ta đã bị xâm nhập! Báo động!}
{111}{}{Có nhiều kẻ đột nhập! Rung chuông báo động lên!}
{112}{}{Cảnh báo an ninh! Khóa căn cứ!}
{113}{}{Bảo vệ toàn bộ căn cứ! Chúng ta đang báo động!}
{114}{}{Báo động có kẻ đột nhập! Vào mã đỏ!}
{115}{}{Chúng tao sẽ cho mày cạp đất!}
{116}{}{Enclave sẽ thống trị cả thế giới!}
{117}{}{Mày phải chết để Enclave tồn tại!}
{200}{}{...đồ chết tiệt...}
{201}{}{...đúng rồi, TỐT HƠN HẾT là mày nên bước đi...}
{202}{}{...con chó này đen thế...}
{203}{}{...vâng, thưa ngài! đcm ngài!...}
{300}{}{Chờ đã. Cô đang làm cái quái gì với chiếc máy bay thế? Làm gì có lịch bay nào trong mấy ngày tới.}
{301}{}{Nrg?}
{302}{}{Tôi biết.}
{303}{}{Tôi xin lỗi. Tôi chỉ xem thôi. Đi giờ đây.}
{304}{}{Kế hoạch đã thay đổi. Tôi sẽ lấy chiếc máy bay này.}
{310}{}{Cái gì? Ồ, hiểu rồi. Này, đừng có động vào. Được chứ? Động vào lần nữa là chết đấy.}
{311}{}{(Cười rồi tấn công).}
{312}{}{(Đi khỏi).}
{315}{}{Ồ cứt thật, có vẻ như chúng ta bị đột nhập rồi. Mã đỏ! Nhắc lại, mã Đỏ!}
{316}{}{Nghe hay đấy. Động vào cái máy bay lần nữa và tôi sẽ nhồi chì vào đầu cô.}
{320}{}{Rồi. Và cô là...}
{321}{}{Chuẩn bị đi đây. Xin lỗi đã làm phiền.}
{322}{}{Chuẩn bị đi gửi tin quan trọng về căn cứ chính.}
{323}{}{Ồ thật ư? Và tin này về việc gì thế.}
{324}{}{Đây là siêu bí mật. Tôi không thể nói được.}
{325}{}{Tôi sẽ nói cho anh, nhưng phải tuyệt đối bảo đảm không được tiết lộ thông tin này cho bất kì ai khác vì có thể
sẽ dẫn đến đại hoảng loạn. Biết gì không? Tôi nhận thấy một trong số chuyến hàng nô lệ gần đây đã bị nhiễm một loại 
virus không xác định và cực kì nguy hiểm. Tôi *phải* đi đến căn cứ ngay, nếu không tất cả chúng ta sẽ tiêu đời. Giờ thì 
đừng có làm lãng phí thời gian nữa vì không thể chờ được nữa đâu.}
{326}{}{Được, tôi tin cô. Có vẻ như chúng ta có kẻ đột nhập...}
{327}{}{Mẹ nó chứ! À, sao cũng được. Chẳng ai nói cái cứt gì cho tôi cả. Rồi. Đi đi.}
{328}{}{Woah, that sounds bad. You better get moving then, I don't want this shit on my hands. Oh, and don't worry, I won't tell anyone.}
{329}{}{[XONG]}
{400}{}{[After a half hour of sitting in the dark cargo hold, you feel the craft touch down to earth once more. A moment
 later, the cargo door opens and you see a squad of power armored soldiers. One of them does a double take at you then
 turns to the others.] Holy shit! One of those mutie wastlanders stowed away in the 'bird! ALERT! We got an intruder!}
{401}{}{[After a half hour of sitting in the dark cargo hold, you feel the craft touch down to earth once more. A moment
 later, the cargo door opens and you see a squad of power armored soldiers. One of them does a double take at you then
 turns to the others.] Holy shit! Some of those mutie wastlanders stowed away in the 'bird! ALERT! We got intruders!}
{402}{}{[Jump out and see how many you can take down before they waste you.]}
{403}{}{[Raise hands in surrender and hope for the best.]}
{410}{}{Aw, it doesn't look like the mutie's gonna put up a fight. Maybe we should bring him to the Commander -- see
 what he wants to do about this.}
{411}{}{Aw, it doesn't look like the mutie's gonna put up a fight. Maybe we should bring her to the Commander -- see
 what he wants to do about this.}
{412}{}{Aw, it doesn't look like the muties are gonna put up a fight. Maybe we should bring them to the Commander -- see
 what he wants to do about this.}
{420}{}{[After a half hour of sitting in the dark cargo hold, you feel the craft touch down to earth once more. A moment
 later, the cargo door opens and you see a squad of Enclave soldiers. One of them does a double-take at you.] What the hell
 are you doing back here? You weren't authorized to be on that mission. What's your name, soldier?}
{421}{}{It doesn't matter what my name is, 'cause I'm not here to talk. [Jump out and start fighting.]}
{422}{}{Me? Oh, I'm, uh, *cough*mumble*cough*. Don't mind me, though. In fact, I should probably be going now.
 [Get out and attempt to walk away nonchalantly.]}
{423}{}{My name's }
{424}{}{. Where am I?}
{425}{}{No, what's *your* name, soldier? I was put here to test you and I gotta say you FAILED. If I were a wasteland
 suicide assassin you and your whole crew would be dead right now! That is unacceptable! Shape up, soldier!}
{426}{}{Uh . . . my name }
{427}{}{. I take fun ride in metal birdie! Go again! Wanna go again!}
{428}{}{You not need know my name. I no like you. I kill. [Jump out and start fighting.]}
{430}{}{What are you, drunk? You're at Navarro, of course. If you're having memory problems, soldier, you might wanna go get yourself checked out. Maybe some of that radiation out there got to you.}
{440}{}{Don't give me that bullshit. You're one of the new recruits, aren't you? Heh. That smart mouth of yours is gonna land you in all sorts of trouble--and I can't wait to see it happen. Now get back to your post, soldier.}
{450}{}{Sir! Yes sir!}
{451}{}{Ma'am! Yes ma'am!}
{460}{}{[The soldier looks at one of his comrades.] My God, contact with all the muties and radiation out there must have made him retarded. You see? *That's* why I never volunteer for those wasteland runs. Anyway, let's put this stupid bastard out of his misery before he contaminates us.}
{461}{}{[The soldier looks at one of his comrades.] My God, contact with all the muties and radiation out there must have made her retarded. You see? *That's* why I never volunteer for those wasteland runs. Anyway, let's put this stupid bitch out of her misery before she contaminates us.}
