{100}{}{}
{101}{}{}
{110}{}{Deine Füße jucken fürchterlich.}
{120}{}{Du entdeckst störende Schwellungen an jedem Fuß.}
{130}{}{Deine Schuhe sind plötzlich zu eng, diese Schwellungen entzünden sich.}
{140}{}{Diese Schwellungen an den Füßen scheinen sich zu einem sechsten Zeh auszuwachsen. Aber zumindest ist der ständige brennende Schmerz weg.}
{141}{}{Oh mein Gott, das ist ja Bess!}
{150}{}{Du erhältst }
{151}{}{ Erfahrungspunkte, weil du das GECK gefunden hast.}
{400}{}{Du kapierst nichts vom Text, aber die Bilder sind recht informativ.}
{600}{}{In deinem Magen fühlt sich etwas nicht richtig an.}
{601}{}{Du spürst einen starken Druck in deinem Magen.}
{700}{}{Du fügst die zerrissenen Papierstücke zusammen, um eine Liste mit drei Passwörtern zu erhalten.}
{900}{}{In deinem Magen fühlt sich etwas nicht richtig an.}
{901}{}{Du spürst einen starken Druck in deinem Magen.}
